{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "5.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.3.1.jar",
          "url": "box-command-feature-5.3.1.jar",
          "size": 79306,
          "sha512": "00b5724a9e80620f2dad7dc8969d737791e0822a7f5872af3d7c9ea66cc817144ca3c9e57b065f4a3928e7c1f421d68fcd085d471035a2f0f40ffd9d60035042",
          "sha256": "bb503b134c71be1788510782af92f0af5050d3bb93e9eb7e709b13cdd9545d56",
          "sha1": "69c741d55376d5e2f13a05dfa08654b40dd93917",
          "md5": "b577c06d2af498ea33799b4a9d33d587"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.3.1.jar",
          "url": "box-command-feature-5.3.1.jar",
          "size": 79306,
          "sha512": "00b5724a9e80620f2dad7dc8969d737791e0822a7f5872af3d7c9ea66cc817144ca3c9e57b065f4a3928e7c1f421d68fcd085d471035a2f0f40ffd9d60035042",
          "sha256": "bb503b134c71be1788510782af92f0af5050d3bb93e9eb7e709b13cdd9545d56",
          "sha1": "69c741d55376d5e2f13a05dfa08654b40dd93917",
          "md5": "b577c06d2af498ea33799b4a9d33d587"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.3.1-javadoc.jar",
          "url": "box-command-feature-5.3.1-javadoc.jar",
          "size": 183942,
          "sha512": "abfca48525442db8ca90fe7ef50d9a56f9173082673a9c783c500f059cd4706e642aa8edbf87b25ebae7d445bf44c735ae8ee8779c53bffd6bcc733d14e018c3",
          "sha256": "b40f59ecc044d6e0ff49f88e47e51c7038fcd661b6b0a3b81bbbc8383349f100",
          "sha1": "f04258db6b813708e720ac5a774eccbe5d7ead0f",
          "md5": "3eb09e451ad6e82010dfef399da8585a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.3.1-sources.jar",
          "url": "box-command-feature-5.3.1-sources.jar",
          "size": 28439,
          "sha512": "344d7549af7a03a56c2862003297d908b4d1a2d2440c2571d83c59711c906238a0aa58f7599c5b9950599bafdc10a3a3873583091ff4a1322408f4d6b09aeb03",
          "sha256": "6aa8894d6fe12fc854fd2b9fa7a7201f523a1db29aa73b6aee7da899235360de",
          "sha1": "aaf336592657b94838128d1449b244fd7251294f",
          "md5": "640b2ce1a45ee423121d07d593a244c8"
        }
      ]
    }
  ]
}
