{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "5.2.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.2.0-rc.1.jar",
          "url": "box-command-feature-5.2.0-rc.1.jar",
          "size": 73843,
          "sha512": "5996a1a578bd315f9cdf3677b8e2f43374e871950956cd2da178259dca33e155677ae7fac0eb7b7fd2787cd8f0e90392d2a4e8edf8263748ceef0333aca500a5",
          "sha256": "b41c1e315c7c9bd12c94823a79cfcd6012b9f38986bc2c5b6ece25e5e10753f5",
          "sha1": "007e05c2950c1f469ac11d9743b540c3ea368b54",
          "md5": "080ee761d57d81ca6f50e7743b50395b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.2.0-rc.1.jar",
          "url": "box-command-feature-5.2.0-rc.1.jar",
          "size": 73843,
          "sha512": "5996a1a578bd315f9cdf3677b8e2f43374e871950956cd2da178259dca33e155677ae7fac0eb7b7fd2787cd8f0e90392d2a4e8edf8263748ceef0333aca500a5",
          "sha256": "b41c1e315c7c9bd12c94823a79cfcd6012b9f38986bc2c5b6ece25e5e10753f5",
          "sha1": "007e05c2950c1f469ac11d9743b540c3ea368b54",
          "md5": "080ee761d57d81ca6f50e7743b50395b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.2.0-rc.1-javadoc.jar",
          "url": "box-command-feature-5.2.0-rc.1-javadoc.jar",
          "size": 168602,
          "sha512": "62812e93da3c61be676c54f10bdc1e13b0c51fd247a08424a78eb94d5234e2364fcb0ce1625120d5243f811aa5b4b466380318bdcdd6a1b9e7272359cfa7e89c",
          "sha256": "f481e89006136fcf133c6c2262a0699f6475e33367bdecd5a89751497ee3368a",
          "sha1": "3053063e7eaa9a24cd6908db7d0826a952672a32",
          "md5": "c0de06f84ccca7afbd2d468304946317"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.2.0-rc.1-sources.jar",
          "url": "box-command-feature-5.2.0-rc.1-sources.jar",
          "size": 25638,
          "sha512": "60dffb393e7ddcd51546b827114ea6c87d603c3ef8832656f34593912066560d0883b2163ea17e086d98665a962f1c0a0c7098e7033a2998e760bbfd284665fa",
          "sha256": "c7844b344839624c3cc528794cef28291256943b9496ec78bd4a46433cf41993",
          "sha1": "05921940db01893bed2d16fc3be08bae53f20599",
          "md5": "1c7c8b3c427ce429c9b6f98dc4a8d532"
        }
      ]
    }
  ]
}
