{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-5.1.0.jar",
          "url": "box-bundle-5.1.0.jar",
          "size": 13953,
          "sha512": "fa7389a2e7ea6cc2f29e62bb56396fc3d77257992c7a852956bd57eaa72e718006f68e32567986b8372e4099494233b2cf8ade56e3166beb97a14bfe2fb55bf5",
          "sha256": "9efe52e744cfb2683778d227b37295ee2d23bef95ba989dc816fb413c3548d9f",
          "sha1": "ad1bbae0d04226eda24b2a09e6554614a3e9f399",
          "md5": "b93faae63251a433e2dff53cd23fa814"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-5.1.0.jar",
          "url": "box-bundle-5.1.0.jar",
          "size": 13953,
          "sha512": "fa7389a2e7ea6cc2f29e62bb56396fc3d77257992c7a852956bd57eaa72e718006f68e32567986b8372e4099494233b2cf8ade56e3166beb97a14bfe2fb55bf5",
          "sha256": "9efe52e744cfb2683778d227b37295ee2d23bef95ba989dc816fb413c3548d9f",
          "sha1": "ad1bbae0d04226eda24b2a09e6554614a3e9f399",
          "md5": "b93faae63251a433e2dff53cd23fa814"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.1.0-javadoc.jar",
          "url": "box-bundle-5.1.0-javadoc.jar",
          "size": 82105,
          "sha512": "d280dd9a487018a59c02e1045fab2ec79d895469719710b273fb71e0bd77045d1c8109fdf00366026f37c4661e6eac462401159f1148d2bb0a53505b063bc25a",
          "sha256": "43118791f0833099becd1d34a1d1301b05ddf94822f40229c954a1c8f6569507",
          "sha1": "c1e5abfdabb071ad2f3a30f3a4f506315550663b",
          "md5": "9220247700d959816ae3898ee4e26176"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.1.0-sources.jar",
          "url": "box-bundle-5.1.0-sources.jar",
          "size": 11780,
          "sha512": "12d0e004b038ee18b56bc7dc2a63c2e8fad9b1f3530cd7587a57f857d1ae4cccabcffa4ef9ee1edffc55af1273905db1372b8ae6bca44f1b5f00e858121e1bfe",
          "sha256": "e72e836a81bf283d222759c04fdce00e15bad5f1113b416fd099f11218496b82",
          "sha1": "75f6287c47c5f8e9e27d45234616806dbb645ad1",
          "md5": "4ad3132bbacaded309ac446bbf92c00a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.1.0-all.jar",
          "url": "box-bundle-5.1.0-all.jar",
          "size": 773864,
          "sha512": "967aa70695b3532335107d4f9efb1cfd6fb78915120ead2ef8c3ce9d1503d289654cb1192b3a9413d877c8c0b82ffede5625ebf5272b0ba5ac235a913fc041ee",
          "sha256": "d197f8b4b55608021bf51d9e2c0e9faf28aab47762afca7429a294795c285dd8",
          "sha1": "efb09c7ab20ffef52e9418d56f831e8e03fd8b89",
          "md5": "8027617a51fc981e12873c0eee037c8d"
        }
      ]
    }
  ]
}
