{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "5.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.5.4.jar",
          "url": "box-command-feature-5.5.4.jar",
          "size": 81521,
          "sha512": "747147112f4aaadc28f19ad913e2937c30fcb7400305b3f2748e0c528e3884d9dbbdc890eaab2133b20f2ed3cacf0007eded3b6c32f3e7ec3a7ef620f9f20c61",
          "sha256": "43c6508ccd186fec803d98ac2ec71226f178cfb88b639cd36bb9fbfe52e9a8ed",
          "sha1": "55898ef2758ced0ec167f034ae19a430c96222a8",
          "md5": "b6f1aa641a7e79e1c15bec5a4731143d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.5.4.jar",
          "url": "box-command-feature-5.5.4.jar",
          "size": 81521,
          "sha512": "747147112f4aaadc28f19ad913e2937c30fcb7400305b3f2748e0c528e3884d9dbbdc890eaab2133b20f2ed3cacf0007eded3b6c32f3e7ec3a7ef620f9f20c61",
          "sha256": "43c6508ccd186fec803d98ac2ec71226f178cfb88b639cd36bb9fbfe52e9a8ed",
          "sha1": "55898ef2758ced0ec167f034ae19a430c96222a8",
          "md5": "b6f1aa641a7e79e1c15bec5a4731143d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.5.4-javadoc.jar",
          "url": "box-command-feature-5.5.4-javadoc.jar",
          "size": 190245,
          "sha512": "0c86acea5a0ce077753c181113469f2aed934ff02e0f2b0697c16f7e9ddd1eff4e1aedfafc40e0607a7df319e33d4aba9e648692fdf371524d9c811eefb89b2e",
          "sha256": "0008494d7770c3ead60500b1ee89625e1d5a9805f57df5b245bdcc71de8fbbfd",
          "sha1": "1ea3a9e978d1944a2f0470a3ea60e12ee6b1863c",
          "md5": "4c13575d1b5cb96e50c53b665ca14501"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.5.4-sources.jar",
          "url": "box-command-feature-5.5.4-sources.jar",
          "size": 29108,
          "sha512": "d6356d995ccc419efa2d13bacb0aa70f131a1313b64f79f5ea6c11f1e5dcf6d8248b386c6f19bdb4dc764954c699e7140f19bd5053d48c89f0069fb17d5bfb47",
          "sha256": "3b859ea2af7d664319f59d6e13438a4b32b7841b4482f2271f5ef63a8a626bce",
          "sha1": "157f916a93f76cfa6493b1030035ab543d5cab46",
          "md5": "ac08b647cd0fa1b7110277b3b6e828e0"
        }
      ]
    }
  ]
}
