{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "5.0.0-rc.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.0.0-rc.5.jar",
          "url": "box-command-feature-5.0.0-rc.5.jar",
          "size": 65177,
          "sha512": "59facbe437ade6c3085f093af530e0782777564deccd6da3dfacda98d22f87fff6a19936872e3c9a2fddddc6df107ecc117440ee1b37166bc128df8d1e255c81",
          "sha256": "993045d5fff72995e0d8e0f1da028b1f82d5ef7bf6eac8fcb3227efc96992176",
          "sha1": "c96ed09e11820fc9bea9d040499fba51e300e187",
          "md5": "e7742cca82f6ebc64f6ad138bc20aa02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.0.0-rc.5.jar",
          "url": "box-command-feature-5.0.0-rc.5.jar",
          "size": 65177,
          "sha512": "59facbe437ade6c3085f093af530e0782777564deccd6da3dfacda98d22f87fff6a19936872e3c9a2fddddc6df107ecc117440ee1b37166bc128df8d1e255c81",
          "sha256": "993045d5fff72995e0d8e0f1da028b1f82d5ef7bf6eac8fcb3227efc96992176",
          "sha1": "c96ed09e11820fc9bea9d040499fba51e300e187",
          "md5": "e7742cca82f6ebc64f6ad138bc20aa02"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.0.0-rc.5-javadoc.jar",
          "url": "box-command-feature-5.0.0-rc.5-javadoc.jar",
          "size": 174482,
          "sha512": "dc94a3760cbbbde39f8c1d8e7cc8ec2b72a6b64e1c3d04d67c195356ed9a9cb8008c28c21eea176986136af99197cbdb339253b7e3cb0e555d9f0d146c874bf3",
          "sha256": "102f76840715f1e991c9a53e27f57cfb46584ec42189dc2ca5e9020995b0a535",
          "sha1": "4f3da465b701201798a537d78316848814c5d2ea",
          "md5": "ce05ee7cb0e6b85331284d37e60ccc59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.0.0-rc.5-sources.jar",
          "url": "box-command-feature-5.0.0-rc.5-sources.jar",
          "size": 24030,
          "sha512": "60f67ba663ff58d9f560d7829c02de0232314fe7632b3c684301cb2fc42f666b4b9daec48a24ee112f9e7b15fd61994e583979f8e7093ee9f7db987a1f5e100c",
          "sha256": "152c9fe9998295e61213393fd5562538516a614a4b0fa01a9a245c805455968b",
          "sha1": "11d5fc9fe6bb56c08deaa412c2ba1deaf32acfe9",
          "md5": "24703322cf0b2332d9a14c9811d80f96"
        }
      ]
    }
  ]
}
