{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 86001,
          "sha512": "5483bab8c4fbaf3de353f0d584e30dd95e295f575ce7267d091395678ab1c79ae1f063580a5ccef8efa4b2af7f7fab5ac9cf3147e47792eb6f9ef8e89774ae25",
          "sha256": "fdc1440be2a5014bd0f8f6c9a838b6731f55d5faa61cb186895616d06a408198",
          "sha1": "42e86f606c77006d3bec90e0c2849093516b5828",
          "md5": "0e4359b7848976acf8289b154ff1babd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.translationloader",
          "module": "translationloader",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 86001,
          "sha512": "5483bab8c4fbaf3de353f0d584e30dd95e295f575ce7267d091395678ab1c79ae1f063580a5ccef8efa4b2af7f7fab5ac9cf3147e47792eb6f9ef8e89774ae25",
          "sha256": "fdc1440be2a5014bd0f8f6c9a838b6731f55d5faa61cb186895616d06a408198",
          "sha1": "42e86f606c77006d3bec90e0c2849093516b5828",
          "md5": "0e4359b7848976acf8289b154ff1babd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 205608,
          "sha512": "bb11ea82e0d64cbe5b905c27f62cba6bf8d6563dc08e144048769adfe192bed63bd4b8ef31be9c3431254f0c8e27ac1b2534a56f8f9bbf8ecd2552e40dcb6681",
          "sha256": "3da7392deb53b161250b3fffa30a05966a30330aad5b1e55e1845248924870b5",
          "sha1": "ab9d85c1da89e82ab36b5835b6cf0edd66c24a01",
          "md5": "8197c66d50506c8b4eef59d060b58a10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "size": 36518,
          "sha512": "cdbd946c10246c145465b72a3fe0019180c75fdc4ce1bc1a029433933b2c1cb70b20bbeba736638e0da81942cc2a1c2117e1511016a738ef18b0015ecff90291",
          "sha256": "78f9c1c49ffbda4f8d3e5cab0f1af53c130ad483e9978aca5a957b275abf21f3",
          "sha1": "b14bd9eea1c3b44898099315de468644cf00198b",
          "md5": "497129abb9946fd99ea6720e21f3ee2b"
        }
      ]
    }
  ]
}
