{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 81484,
          "sha512": "851ca546a2f59f8de25f47637eb796a485036852958020a580cbebc1297307fb2440ba566de1ede42e63567ffdb4a3d0e6cb281d00daa0aabbe6b111a22956d8",
          "sha256": "7657652ebf2b6935b0d1761f0b5c2bcbb7f47a2a7df7fd43fa28fc5515915014",
          "sha1": "6baa094add1052a7bebc2aa0387a258e66b75d5b",
          "md5": "be43c52bf19ff75b9492c5a380f54f36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.translationloader",
          "module": "translationloader",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 81484,
          "sha512": "851ca546a2f59f8de25f47637eb796a485036852958020a580cbebc1297307fb2440ba566de1ede42e63567ffdb4a3d0e6cb281d00daa0aabbe6b111a22956d8",
          "sha256": "7657652ebf2b6935b0d1761f0b5c2bcbb7f47a2a7df7fd43fa28fc5515915014",
          "sha1": "6baa094add1052a7bebc2aa0387a258e66b75d5b",
          "md5": "be43c52bf19ff75b9492c5a380f54f36"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 198925,
          "sha512": "2f687fbbc8f953912077be5b8ee63494c44b4dc08fa6e4a96f02813e161dbde413982437f581f2e92aa2e36a1b1992e6c7e877585af213c0e3baf16c01669cff",
          "sha256": "6b94ba348984bb9c61a6c386e4e6831c85e5f642d8f3e3d800dd95c69cc361fa",
          "sha1": "202b7b48ea8e1acb7413987ed3f4ec091f467879",
          "md5": "daaac5fe530ae58205e6b84d30f37d08"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "size": 34609,
          "sha512": "9d171a866e69359f2203406f3fbd029441051a0241a1476079b1081444ad59cf384da7eba61d3852b4f2c4455ddae824aa4e3f475a1d7806fceff261f6c21a42",
          "sha256": "1d1dff3f03360cd043d6f3afed2196d1de69196d427d21fa22ba675086ac4a19",
          "sha1": "cdfa28f2a64c84acfad11361b476a48b1d9a81c4",
          "md5": "278e81d32e4217bda37b439d193ef2a3"
        }
      ]
    }
  ]
}
