{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 73988,
          "sha512": "3bede43f36288ed375cddee817b4d1970e12322ee60609f8f7be2233605bb1b4aabd39b9e51a238ab8487802b9fdd5272500a8245cff38c648dc4e6d4793c9a9",
          "sha256": "65102ab327d1336f71f07255725d7dbbd29c936e76d019b04b6732ae902e9bdc",
          "sha1": "d193f05a9b625aef6cc175df7d087c13987c7b12",
          "md5": "a45b799c11537888a7811ec6bee8ea2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 73988,
          "sha512": "3bede43f36288ed375cddee817b4d1970e12322ee60609f8f7be2233605bb1b4aabd39b9e51a238ab8487802b9fdd5272500a8245cff38c648dc4e6d4793c9a9",
          "sha256": "65102ab327d1336f71f07255725d7dbbd29c936e76d019b04b6732ae902e9bdc",
          "sha1": "d193f05a9b625aef6cc175df7d087c13987c7b12",
          "md5": "a45b799c11537888a7811ec6bee8ea2e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 192078,
          "sha512": "08fff226ae3db40d9dd1dbae1a75220d6be9cc02def6a862a0224fd14a8bc029575c718abc55f722b1cdeebd2fd3fd054b330aff62186197b8da593287ad28b1",
          "sha256": "9766029adc07a8e5a31ded56a85602ac93414ca6cceeebb8a31ce58e440c5cd3",
          "sha1": "fe2cbd1bfd0324746f6f866ee3c375850333eeee",
          "md5": "55eb40bbe3ca50834dfab1017f3f93cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "size": 32481,
          "sha512": "711cc76b314d13cab77087ed933af0d729673b74de2219e532a914ae875fdaacf7a31fa653a82ce079326d2f94c9880673c968288ff79ffa632811ba761d6e7c",
          "sha256": "2febe84aa9881c80b8f8af824172117b5912dd862ad56befc19acfad41177b79",
          "sha1": "6a2cbeb303c62713d4ce5516ef03e8897a62090b",
          "md5": "c4dfe67eeb0207e2c52ce2c88524eace"
        }
      ]
    }
  ]
}
