{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 81484,
          "sha512": "d3b4ab62de52e9f45b4390bc41169743f02f693e3346d59a886238894f2b13b225dda23a2cf1e9fe28119abaa99c886dfa202e97d3709d48d4f19f7309ff6f29",
          "sha256": "089b7b1e8b3a06a86838d0d449eb13b6b7ea30b0349344da2efc776a2bd8e984",
          "sha1": "fa4fc773e61447c1dfe304a285b67a47b07b5841",
          "md5": "4f0899b4ca3f10b98d1d76c881d6d6bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.translationloader",
          "module": "translationloader",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 81484,
          "sha512": "d3b4ab62de52e9f45b4390bc41169743f02f693e3346d59a886238894f2b13b225dda23a2cf1e9fe28119abaa99c886dfa202e97d3709d48d4f19f7309ff6f29",
          "sha256": "089b7b1e8b3a06a86838d0d449eb13b6b7ea30b0349344da2efc776a2bd8e984",
          "sha1": "fa4fc773e61447c1dfe304a285b67a47b07b5841",
          "md5": "4f0899b4ca3f10b98d1d76c881d6d6bd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 198916,
          "sha512": "2ca8f4a4bda2f8e682499cc5e9fb7995cc83d7af36427dcc6772dbe82b704443864df0af6ac23c8ecac6e5a86a00e307f01dfa7f48fab3e635879a7e2a388cfb",
          "sha256": "87ab8fef3f2ba9c3693bc72bec651d0d06b88b92f7597e8070cec24aa22d2a49",
          "sha1": "6ca4479d3345390c3d8f3f76c84fce7089d0445e",
          "md5": "214d5eedfb1f135f863d610e707e625d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "size": 34609,
          "sha512": "fdf737733dcceb6653a4e7f2c58b4378951eb5568b4a79dda0948f816ab84f2c86d0824ed334dc7ba3fbe482b1df5d2ce2248c9a2d4fb78235dd7a997d50f634",
          "sha256": "f9dc0b503c4a673b1631a7cb9790a34330726ce74302c15fd9363c2414e505b6",
          "sha1": "da74d1670dfadb855dab169a2b3e034c7d62c156",
          "md5": "875197bd056590c2eeaecbaefdefe163"
        }
      ]
    }
  ]
}
