{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 81484,
          "sha512": "3194fcdc6a926c4022a6f2b164ac57662a80ed82b4ef86501ee1041513ab46bb12d943b85e2ec93404a081c8043f1f614e6fb72a4f7f886071f63742f688b344",
          "sha256": "267262be419596269088be11808a335901e623bc787f774617de21ef8c5a0891",
          "sha1": "a90756c37cd68abbc17b52fd9342289ab4a39398",
          "md5": "bf90868bb22f893f8cb327f853d4583c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.translationloader",
          "module": "translationloader",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 81484,
          "sha512": "3194fcdc6a926c4022a6f2b164ac57662a80ed82b4ef86501ee1041513ab46bb12d943b85e2ec93404a081c8043f1f614e6fb72a4f7f886071f63742f688b344",
          "sha256": "267262be419596269088be11808a335901e623bc787f774617de21ef8c5a0891",
          "sha1": "a90756c37cd68abbc17b52fd9342289ab4a39398",
          "md5": "bf90868bb22f893f8cb327f853d4583c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 198925,
          "sha512": "6d9f097337e935e8b5d47a124106463159a719514d77237283dd8052f1200218d59268e01e9bcc0b2ea937dc30fd583eea55c5d546f5f366b1e53a9620c5fb06",
          "sha256": "8e3a1acb3198059881356211c339b822414529faa2958023ba8b3ab8cb21c271",
          "sha1": "61a411b24f7084363f4de5b3dbb10adce04ef0de",
          "md5": "caf56fa0d97453c1877be0f8d090f562"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "size": 34609,
          "sha512": "b5cdb8c0b4b3796ff839652e1a513b669b258c1c32280e253976f269d66c0662a5e0fcb6b72565ba3be78d206f5e106d6d3d545fb15005b4ae00d07a0c641095",
          "sha256": "d8184af2aa5ac81bc1d4424104b7f1439a86070f04ab9581fc1f7cfda9a97615",
          "sha1": "dfd3e3df1898ea8d8f6b69d467528d10cfa3baa2",
          "md5": "109df63056d75044bea08e74c9e4b6ec"
        }
      ]
    }
  ]
}
