{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 83881,
          "sha512": "5cdd00837579dbb203645d68543ce9c0dcc395ab028855f7306c0dc88ed922e32376be41fe96f94c599850630bda5847afce00d0d70b86ac05d166338c4efc17",
          "sha256": "7076c4e4a7e97fbf57beb624a67ff30b85c8b8536151e69f620eeb28a41a9fbf",
          "sha1": "718ae8b65bb24fc72af2fa37d951eec196e832ba",
          "md5": "fd79f6fff6a544a2886c0085e2fdda1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 83881,
          "sha512": "5cdd00837579dbb203645d68543ce9c0dcc395ab028855f7306c0dc88ed922e32376be41fe96f94c599850630bda5847afce00d0d70b86ac05d166338c4efc17",
          "sha256": "7076c4e4a7e97fbf57beb624a67ff30b85c8b8536151e69f620eeb28a41a9fbf",
          "sha1": "718ae8b65bb24fc72af2fa37d951eec196e832ba",
          "md5": "fd79f6fff6a544a2886c0085e2fdda1e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 210792,
          "sha512": "3ea90e9ac43155a5ab29a9ce101342e981820a7e8407882b959cbfdd7c7d7e45cca72adbb4603118fb81f9a2fea64e4a3fc5b9f8648fc30f806396c1979f5cc3",
          "sha256": "53d227719b3453d38abc3b7c16d2e3cd00afcb8b2098cf90b76186bd18cd17f2",
          "sha1": "b2a44907bb0a0c8a9378da8c98c756e8b8f3d51d",
          "md5": "2ac3cc3ffa3c954235d00058dbfeada9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "size": 36696,
          "sha512": "6732fa013ed803dc79064025e970b470c3396b8b3002fb740dd24a06cf7b583695f8034bab73d2ff48cb7c0f4a05e8f21153794ea6b9f3dfa4eedd7b8fdf0223",
          "sha256": "d61bc3fc6e3f04ac7164b940fc48142e446b0b1965848712b5b70f385e954fc7",
          "sha1": "64930d3d25219b5bbf5be3f20679791e4c769cfc",
          "md5": "565d029ebb8a8ab526cc655bb0d94c9c"
        }
      ]
    }
  ]
}
