{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 81484,
          "sha512": "08af4b0326f86ecee9bb0dbc15e4da6928e00cc69ba6e84a43f6225a29c2e1a0759979404e6d473fdd478ca640f98ac4ca461172623c9fa6f05f38c341a13ef4",
          "sha256": "ac1031a75533f0ab1d1fbeb70772755712a3f8a786481cfcfc3a295944e4c8a6",
          "sha1": "7f0b59a5b247c5c13223193dba02fcb213e83865",
          "md5": "dd8456dafe45d2ccffc0e9108127f875"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.translationloader",
          "module": "translationloader",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 81484,
          "sha512": "08af4b0326f86ecee9bb0dbc15e4da6928e00cc69ba6e84a43f6225a29c2e1a0759979404e6d473fdd478ca640f98ac4ca461172623c9fa6f05f38c341a13ef4",
          "sha256": "ac1031a75533f0ab1d1fbeb70772755712a3f8a786481cfcfc3a295944e4c8a6",
          "sha1": "7f0b59a5b247c5c13223193dba02fcb213e83865",
          "md5": "dd8456dafe45d2ccffc0e9108127f875"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 198926,
          "sha512": "3cda120075136a083e696511a0dde6850089a1d01cf2040a3e3d8e6e086f1fa858f759d4175843b5e81f4c49814b580593cbf8f858b754cd1effa5f1d54553b5",
          "sha256": "48b6c8d5c5f23510e3aa31658765541dd370ac06e19036a975537e8ddbfa094f",
          "sha1": "8dc2346a47978b6ed625cfc3f6c6910077b0c49b",
          "md5": "d8cc687087b297914c0c6b53dc3edf27"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "size": 34609,
          "sha512": "e8632fdc3e3d55da6193c1fe5c62b775f86023f6d3a36af4248018529313f51ddf911556897963dec78634bce77fa60a6ab1f167b232db95e38861ab980833e2",
          "sha256": "7265b0ebdf594d76586a65c16d9313864ef76d87ab8e382613042326fae16ecc",
          "sha1": "17a1853ec096679acb37e6d4302623f0057b5a45",
          "md5": "686290775fb44ae9546b5a5f0a819844"
        }
      ]
    }
  ]
}
