{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 86065,
          "sha512": "896dae69247728d84bfb89b3d75abac7bc3048182754ec683e17cd43232d078097933dc002d8053b94c9abd8790c6ad19264bb0eff289bb7c120ab3a35a34f8b",
          "sha256": "e04f342dcef88b958d9c8b5911b1968bf11fbb8b319d4a6de45264a52f18217f",
          "sha1": "43b6322b83a513c7cf70325e9b8b67471da2824e",
          "md5": "339aedf95362856ccd81fd54c063d9ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT.jar",
          "url": "box-core-6.0.0-SNAPSHOT.jar",
          "size": 86065,
          "sha512": "896dae69247728d84bfb89b3d75abac7bc3048182754ec683e17cd43232d078097933dc002d8053b94c9abd8790c6ad19264bb0eff289bb7c120ab3a35a34f8b",
          "sha256": "e04f342dcef88b958d9c8b5911b1968bf11fbb8b319d4a6de45264a52f18217f",
          "sha1": "43b6322b83a513c7cf70325e9b8b67471da2824e",
          "md5": "339aedf95362856ccd81fd54c063d9ca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-core-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 225235,
          "sha512": "04e5c9f265d019fb8275683736bbb6caa599121304645785426b5af7c604841c9cf8acb89d4650f8518e07d7663d65301448a8eb7f4fab25210bd7f9fd5338da",
          "sha256": "6830ed53a1e910a63fbbad1ce7d9872db99277ff3f78ae3e121b4c55f84153ca",
          "sha1": "2acc43651e8f80f6f2f11a48bf9a4aa117f19fa0",
          "md5": "72d194a8de112c5000a464562d3428c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-core-6.0.0-SNAPSHOT-sources.jar",
          "size": 37499,
          "sha512": "c4d7f46165d4299f203406bb2fa5813ca144365c54e98b7e1f18216519af1eae47cd72383e39880f526b470c8e722faa19459edc8ad34ecdc70769ad18e3e3e4",
          "sha256": "13f32c2293cbca1e85aef738af42669ebc64efd6f9c8272032c0796e986da418",
          "sha1": "55abecf8a76b7db3e8711a44f6158977776ed09b",
          "md5": "faa2bc315dc996fc337e42207047666c"
        }
      ]
    }
  ]
}
