{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-migrator",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-5.4.0.jar",
          "url": "box-storage-migrator-5.4.0.jar",
          "size": 17863,
          "sha512": "4f16fc6f0da5e0ad4bdee43b230534b88f877d0563b0caa92f979da07e88bc6de5369a8d1fb8233c6301860150f94d3141aa60f76a9662bd0a94335ce2e0b96b",
          "sha256": "ebba7b84dc5d4edfc2104123fcc1db7a3e2b0800ac3fb7767e2365078ed5f4f8",
          "sha1": "652662dd03fb90f98e5fb13be94823a00d064435",
          "md5": "a219f9dd4f9f08eb94458bb8b8a15544"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-5.4.0.jar",
          "url": "box-storage-migrator-5.4.0.jar",
          "size": 17863,
          "sha512": "4f16fc6f0da5e0ad4bdee43b230534b88f877d0563b0caa92f979da07e88bc6de5369a8d1fb8233c6301860150f94d3141aa60f76a9662bd0a94335ce2e0b96b",
          "sha256": "ebba7b84dc5d4edfc2104123fcc1db7a3e2b0800ac3fb7767e2365078ed5f4f8",
          "sha1": "652662dd03fb90f98e5fb13be94823a00d064435",
          "md5": "a219f9dd4f9f08eb94458bb8b8a15544"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-5.4.0-javadoc.jar",
          "url": "box-storage-migrator-5.4.0-javadoc.jar",
          "size": 119583,
          "sha512": "5449b4e48cfdf73f5c98601173c0c12601f1a28f86ce47bf7825f25eba23bba71a1e27a7c02289950c6265591ef9d264e04c22b3e5d3acd3e8088c25abd48104",
          "sha256": "bc1976cb424eac15e336787793f54d49b34b3549cf655ad42535d3c103228413",
          "sha1": "9339efc7ce802ce7d2891a3c0d99ed1c90fab90d",
          "md5": "c459e19d7130a14d7898d8167c56060d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-5.4.0-sources.jar",
          "url": "box-storage-migrator-5.4.0-sources.jar",
          "size": 8546,
          "sha512": "15cd81f3986ac593d70733e57cf242e9cc31f229184dc3d85ab23e9dd427cac364e4e4e3d75e67bcde54ab15d808a3ae735743f76d7ed85da5842cb93004ac92",
          "sha256": "5236049865341b767ba16f510e0f6a1994a7f615ea6d7764d9f7afaa2804ca23",
          "sha1": "15d8a26ac6382a6cafd4dc999c19a42e101d612c",
          "md5": "5fe2e3e3c3bebc7f0edd68e65b714aa2"
        }
      ]
    }
  ]
}
