{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.1.0.jar",
          "url": "box-command-feature-5.1.0.jar",
          "size": 65206,
          "sha512": "a4b37f52204716823ececb2a4d8277fb2844102b81631e0856d1ca2143dd9fef18fc33b80a7c5c3261a6ec0176b6be49b43c6c1d0c8e98b6fb5e76dc5a5573e6",
          "sha256": "d2d2d1dffb0365a58f6695debb120f1197b1631b3fbace4d2e8285bdb5839754",
          "sha1": "daa393363c6b3577490d248f97aa676214ea0aef",
          "md5": "59675adaedd8cdc09ae744fc52eb9c4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.1.0.jar",
          "url": "box-command-feature-5.1.0.jar",
          "size": 65206,
          "sha512": "a4b37f52204716823ececb2a4d8277fb2844102b81631e0856d1ca2143dd9fef18fc33b80a7c5c3261a6ec0176b6be49b43c6c1d0c8e98b6fb5e76dc5a5573e6",
          "sha256": "d2d2d1dffb0365a58f6695debb120f1197b1631b3fbace4d2e8285bdb5839754",
          "sha1": "daa393363c6b3577490d248f97aa676214ea0aef",
          "md5": "59675adaedd8cdc09ae744fc52eb9c4d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.1.0-javadoc.jar",
          "url": "box-command-feature-5.1.0-javadoc.jar",
          "size": 138412,
          "sha512": "52bb21724ae7a39e43d2caed087d9f43b1946aaf50471987fe337b8ff3b1fb982fd762ee67c7480f96509eb43b9461fc3d36ca04701dbec57649e6318094d2cc",
          "sha256": "67d63e008ea3610b55e4583d1dca76bdc7a0f285de8858c3f30dc3c1acc6cc90",
          "sha1": "87c9a1d8508a2f87af918e2164337a3d486e9d0f",
          "md5": "06e05498f4e52e72f8361f9f36657d33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.1.0-sources.jar",
          "url": "box-command-feature-5.1.0-sources.jar",
          "size": 24041,
          "sha512": "7b8d8d2123be1e3cee778b9e0ef358a244fd76539a08872b41e4259052d274209666b416696400518c1173b05e710f9a84e4131fed2b8b4e063e192e3f6d197e",
          "sha256": "fdf391395bced2320896085b9151ca7df7c482af4ff20ded8c2cc3a7c244ebd1",
          "sha1": "eeae21c05f8894d294b5b76ba8a0b3e9cd6a9ead",
          "md5": "f535d6a6b46d6919d83f49c1aa0846ba"
        }
      ]
    }
  ]
}
