{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "4cc29032a77897542782cc80d9952fb229cb07e7fb76a604fc4b48dbe8f12622c2629d45d7b7810612d2335ed768e605cfaebca2cac6566d425f68b2d2ef3695",
          "sha256": "4518e485d0cac117fc395eb2f876947701ec60ff9e7c93148f8cd8c4eb19c858",
          "sha1": "49f56b2c819fbf6a5e4f27b8876f7e6e7c0dfd13",
          "md5": "82e25b5743311440697823167f305d90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "4cc29032a77897542782cc80d9952fb229cb07e7fb76a604fc4b48dbe8f12622c2629d45d7b7810612d2335ed768e605cfaebca2cac6566d425f68b2d2ef3695",
          "sha256": "4518e485d0cac117fc395eb2f876947701ec60ff9e7c93148f8cd8c4eb19c858",
          "sha1": "49f56b2c819fbf6a5e4f27b8876f7e6e7c0dfd13",
          "md5": "82e25b5743311440697823167f305d90"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117160,
          "sha512": "bee723122946b6d81d580c9f693fe666bcad5c0e35881b066d0d99f7a246758afb7d567e7d9baeaebd35d80949173120e3a90b846bc90b08814d220a61066be4",
          "sha256": "16daf3561eb07299d8481aa597460cc607eab4b0b716aeddaffb3f4cd11981c9",
          "sha1": "8b61d64b8862e6a7701f91fffa5c5f4ead35f17c",
          "md5": "d515479dfb3e4070dfe81704ba6f6c9b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5985,
          "sha512": "f4d0be5816ff737f82f86414ff43ab8bd8ea10312a3e2f1be2ffa2d62302f7b6a3bc2d7b9b877e08281296a5dc1c6c5758cfaf4ce1a7e174d0ae8226c41d3b80",
          "sha256": "539b0ecc6621a8362bf0c778aecbce007a0853d71067838728e9c9b39c4fce44",
          "sha1": "acd9eaf978c98380c1bd3af772f848d5063979e8",
          "md5": "bce237df54a6aab054a84539df7e4ddc"
        }
      ]
    }
  ]
}
