{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12559,
          "sha512": "15696373efa6b14a54ce871ab23f25c79de264d97c89e3b877a796c8d7481a4da12982f2f8a7d14c3c83d65d3dc43dfb14b8ce671ed2ac88030c48e7086df28b",
          "sha256": "858e6adab55ef1c8441f6dc0306fba33b408b9c828e19c86dd8c0f20a94c6969",
          "sha1": "1dabfa0e8e819133b6bf9e77b9b44f3da2eb3f1c",
          "md5": "01a12efa10bcdb5b8975132c88eaa7a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12559,
          "sha512": "15696373efa6b14a54ce871ab23f25c79de264d97c89e3b877a796c8d7481a4da12982f2f8a7d14c3c83d65d3dc43dfb14b8ce671ed2ac88030c48e7086df28b",
          "sha256": "858e6adab55ef1c8441f6dc0306fba33b408b9c828e19c86dd8c0f20a94c6969",
          "sha1": "1dabfa0e8e819133b6bf9e77b9b44f3da2eb3f1c",
          "md5": "01a12efa10bcdb5b8975132c88eaa7a5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106435,
          "sha512": "21fe89e65ca92a3d5ceecbb7cdc6d1850207f504dba24ff5b478f0357f484e89a655daddcc350ad84d496a1f7793fbdf191d3c4a9ef9370f72b82048e4c121de",
          "sha256": "dbb8d0ae36822e42f1570d6cd22612af983f468df918930a97993dccbdf43084",
          "sha1": "841117030dbf00615efb0aa34bdf956105231507",
          "md5": "0d6b52be09e0d2812898ec095c187540"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "42f4dadcbc2f40facc5fad7f9260ac52df2fc28c4428c0e336879bddaccbe781d67a6914fd057d0bf3f733dee238f1eb22f2f12b17c973c37cbc772a83705976",
          "sha256": "f9a985b3714f44364018b75fab3dad020d4452fec54728894934fa90432bba9e",
          "sha1": "1896af0512c9c99268b98d784e228028cbbf725b",
          "md5": "e43339a49324a081023212f76a9a31c4"
        }
      ]
    }
  ]
}
