{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "954f3816245b61620baa1d62a4703e039248e8a427f95a2b6f0d190a20f1f2ffacec4eae0b571322423db022fd526642596b35325f17303372f23079f3352187",
          "sha256": "d0d8837bd783e0a41e113454eaaa8303a96e77944a1dfcd7b1b90786dc253aec",
          "sha1": "6cbd56c3843d39c31a45aa4001455534f53e050d",
          "md5": "a65a45ca2eb23d5f3461b86d90451427"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "954f3816245b61620baa1d62a4703e039248e8a427f95a2b6f0d190a20f1f2ffacec4eae0b571322423db022fd526642596b35325f17303372f23079f3352187",
          "sha256": "d0d8837bd783e0a41e113454eaaa8303a96e77944a1dfcd7b1b90786dc253aec",
          "sha1": "6cbd56c3843d39c31a45aa4001455534f53e050d",
          "md5": "a65a45ca2eb23d5f3461b86d90451427"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117061,
          "sha512": "44821794fb7a117f9d793769876f51c3b3c32e718e6be3aa5cd6dcac26f4d4137ca79fc93af20e4cc21da5eb9083635fcb4866b0b55a9054e4e31dd77ae96410",
          "sha256": "d1f07481e5ae01ed7d8943111477a5b08c80a6568f17a3d867e694438fa8e33d",
          "sha1": "082bbcca5bdb02352c577a6faced0d59b8daf04e",
          "md5": "4b41f1e43f84ff0793cd1fb0a5791375"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5950,
          "sha512": "bc40a3385de36463a0db40782bbc0130ada7509945c8c6fece5ac1d70197886cb6023c21178b5359bb5b2d23576a263f9015da0085eb39dfdf8b59fc94ac8dfa",
          "sha256": "fabd7b07dd10afeab84fc2be46625c044c1ebaa10a57ba9d416c39c15a9e35cd",
          "sha1": "4d77a7286157c4f46e68e4d26a5ff99a346f5190",
          "md5": "37bebff7bb4cb22849eaffdee5113653"
        }
      ]
    }
  ]
}
