{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "70b3729c152463d7401b2034ae30634e13ae9a2b9c399110d2093d6aef3e74fbd39519a47fcd137f5d74da6215479f79b1e08e3517a35f10793ccad35ac0171c",
          "sha256": "97374e0778cec48505ceab975b614bd7734c34c6ae203f3f13bd742a3573941c",
          "sha1": "9227401338dd1acb6768f6f6be8eddd718a14448",
          "md5": "b3fa01acc47e1d7a3c4ca0e1f67b3a5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "70b3729c152463d7401b2034ae30634e13ae9a2b9c399110d2093d6aef3e74fbd39519a47fcd137f5d74da6215479f79b1e08e3517a35f10793ccad35ac0171c",
          "sha256": "97374e0778cec48505ceab975b614bd7734c34c6ae203f3f13bd742a3573941c",
          "sha1": "9227401338dd1acb6768f6f6be8eddd718a14448",
          "md5": "b3fa01acc47e1d7a3c4ca0e1f67b3a5b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 118373,
          "sha512": "d60061e0736b34c46974817f3950473a0a2bf3577f06dd0cea3167b53003458ebb31883a4d893c713c93e744294c148dda31bcb4829c91f620530a784c09fed7",
          "sha256": "e28ae21321bfcd095c6bb61f5cce1c59c86055a9befecd0b3d73478cd45a9146",
          "sha1": "01a74fb41cbc01a060869f858d87a16593b28c03",
          "md5": "0156f189043a1bf98e6ae482c2e992df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "4a23eb3f7daef333394e1e712687ad2071eab0d418d0e312efa34f60311479f27e0246a897f209b7939bdb57d452f96e6e290bc422068d478bd47ff86851433b",
          "sha256": "8b18a7f8d034110cdf854a393e53b3c76c201844bd816eb33501efb97f8ff067",
          "sha1": "ddafaa014b8779916add6063ff17c269813d732e",
          "md5": "a2671ea9d0674e300363a6f05e9e081b"
        }
      ]
    }
  ]
}
