{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "a2f7c3cf311f9fe0f2b100c59f864af10ee0e6d2eea3d85e1e048c27322dcf34a181a89e2aa95fb7ae1bdf683d7ccb28f4bab55043c6e087716387f031e89475",
          "sha256": "ee9f5263f796905535f664d0474ea038026475720c56c50f4aed740c3aeb2031",
          "sha1": "a0d68354345f9e5cef4843615d87ae4e74dee4e4",
          "md5": "ed20c609253121fa53b53500b2fb8b25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "a2f7c3cf311f9fe0f2b100c59f864af10ee0e6d2eea3d85e1e048c27322dcf34a181a89e2aa95fb7ae1bdf683d7ccb28f4bab55043c6e087716387f031e89475",
          "sha256": "ee9f5263f796905535f664d0474ea038026475720c56c50f4aed740c3aeb2031",
          "sha1": "a0d68354345f9e5cef4843615d87ae4e74dee4e4",
          "md5": "ed20c609253121fa53b53500b2fb8b25"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117160,
          "sha512": "57aeddf4075b0a434433a5102b4ba4c98ae54be9605b326e9c35983a5270e066893beaf7fda84fc3be76eae62ef8a3b897f9b8cb6a78df96b0d625742103d7ef",
          "sha256": "4c6e9056205db6ab5fe499a69bd0836c7b9bd4cdf74e5288fa2dfbf46c40ba17",
          "sha1": "0055863f61b229165877740a3e603bd75b4f3311",
          "md5": "c0163388d1d7b2f4e54ec5c762aa66c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5985,
          "sha512": "960b82c154e6439132c0036b29db31395618d91948b14aea1c4eba9c6a3d3b6c6c37dea6127ac85a887de49d24d417a4529d4f6396846a7a807c227e3675c91c",
          "sha256": "8a0c5cc00b5550da800d90ee936227cac0dbc9464aceff594b44d748f5f41457",
          "sha1": "58001e8367244b57cb8b67cbfac3d8b39735fe08",
          "md5": "02a3a0f30d2c70a5dbd5c5592d712400"
        }
      ]
    }
  ]
}
