{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "22febcf734c2813630bbe78e52e5159e785e871c353cbc9306205163b94dd3743e3bc7873584aad991042bbe026a22092ea5be5d61e6be61fc218669b0e9a4c3",
          "sha256": "e308edd35118d8637835fe9beb82c594e84f004d42565f29db5554dedabcc8b0",
          "sha1": "d4f2232758d986631c669e3239d2585623baf4c4",
          "md5": "e78ba8a19e85447445cd248a110ee37c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "22febcf734c2813630bbe78e52e5159e785e871c353cbc9306205163b94dd3743e3bc7873584aad991042bbe026a22092ea5be5d61e6be61fc218669b0e9a4c3",
          "sha256": "e308edd35118d8637835fe9beb82c594e84f004d42565f29db5554dedabcc8b0",
          "sha1": "d4f2232758d986631c669e3239d2585623baf4c4",
          "md5": "e78ba8a19e85447445cd248a110ee37c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117061,
          "sha512": "ecde51833e9859eac5bc35d3d8ade9b5d805b40bf274bfb29574df48ec884c0d2b9783fcd0e984469399322e39fc4611f72ce9c690e9b90d590cf771cb4a41d0",
          "sha256": "7b97c83cc4e46bb16d44e6ea12ea4846ac9b5e6922acc6003148212b591a2c22",
          "sha1": "65a6ef0365949d622aee1a58ce7ed4365a1491e6",
          "md5": "fe85e094a75c5e0be7cddc3886633398"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5950,
          "sha512": "59f67a88d0a5667fd85ac2c7e152453a3566eaa49fc05938680dc3d15d92fb07bb856c839353b5e9eae078113ab8e788de01538a39c036d8069e896b06ad59cf",
          "sha256": "486858b5f2fedcfdbefb84559bc10bf7be607f8563cea91176f8402ba9b40bb0",
          "sha1": "e35bb900108074647e519ace688f1cdbff45e583",
          "md5": "c4df7ccba8b2992c725b9bc72072f475"
        }
      ]
    }
  ]
}
