{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 14006,
          "sha512": "ad7b3b49fc663b5f2e9646ce46ff57e8543deb8cb0606168bdeb07bd5e47560b3a5ba383f0b08213bb60523ea054115089ce5d19030335bb2f71b709a9534263",
          "sha256": "f106a58e06f71e73b18ed8475ae375fbbba17e15a193c88153b696739e85983e",
          "sha1": "19dd672ee0ef5ff167620159528ed2f85a970f61",
          "md5": "7ddda78976ea4c06330370f832dfb5d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 14006,
          "sha512": "ad7b3b49fc663b5f2e9646ce46ff57e8543deb8cb0606168bdeb07bd5e47560b3a5ba383f0b08213bb60523ea054115089ce5d19030335bb2f71b709a9534263",
          "sha256": "f106a58e06f71e73b18ed8475ae375fbbba17e15a193c88153b696739e85983e",
          "sha1": "19dd672ee0ef5ff167620159528ed2f85a970f61",
          "md5": "7ddda78976ea4c06330370f832dfb5d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 111718,
          "sha512": "640eb096470c66da0a6bb17b133493d024cd1a76cd48d129c466e64af9f327c0219d08eff1fa89d55594eb395fdcf342d7dbc1dceb42030acef98f8abd2fc77b",
          "sha256": "799728eb0931a7ec11d15e399a0a8b7bd8a98cdf5b68ca6cbff533e51eaccb8a",
          "sha1": "852cdfa414111400a07df397511aadaddb118d73",
          "md5": "2ba62854234a65bc2832206d8718b8c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6463,
          "sha512": "86987da3922d7184ecdf70aa67d412ed60873102e559c3ff82e78fd9e1f10a22433f2407592b3da2178f35552f9d267a5f283e987399a7c2d3d4cf69b1a91929",
          "sha256": "dd6c50ad0fc9ce16877b7b235c54cea9e14ec40da6bbdff1af9a7fc67500fcc4",
          "sha1": "212f7ee994a8c10db83179c440e0244523578744",
          "md5": "e0c736a19a3e10f180c8eae1a5d8319c"
        }
      ]
    }
  ]
}
