{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "f74d82b01fe15ced8d5e7a177bc622a636ca3479bb46aa2d838917967a3c746f2f80a10c53e1bf5c546b9e8bd33876570cbbd17c876d76360f99d5d5970fe274",
          "sha256": "31bb598ba64659a418fc5eaec732ba264129e294bbcbf20efd6b9aae9a63efb3",
          "sha1": "91b6d1497c042e628061fa5a13a8e2fc9245715c",
          "md5": "8fee99f55c039400b92ed8cad32f2586"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "f74d82b01fe15ced8d5e7a177bc622a636ca3479bb46aa2d838917967a3c746f2f80a10c53e1bf5c546b9e8bd33876570cbbd17c876d76360f99d5d5970fe274",
          "sha256": "31bb598ba64659a418fc5eaec732ba264129e294bbcbf20efd6b9aae9a63efb3",
          "sha1": "91b6d1497c042e628061fa5a13a8e2fc9245715c",
          "md5": "8fee99f55c039400b92ed8cad32f2586"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117830,
          "sha512": "8c68fb6b3f0456bb107c9877277667a39f6f005c723f15922f6759887c4b8b1c2a8da53a9b0193d86eadeb620f162e4a28ee7a5ebead6593d3e0f996d3bdb06e",
          "sha256": "fd477888d1386f08c35fd70e813d954be435397b1885a9e3c223ebe4cd6fb899",
          "sha1": "490e3133c75d3b153ef985eea36637d461ed11f4",
          "md5": "ce6d971baf713948cb6af59115d09cae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5984,
          "sha512": "273c5a453dde03642a7f1fb68d0dccacfb099e5099cd623e4322efa771334d105ade78ba2b2e646204712893c38f4c30a57c336d4170acc429fda527bc9ea2fe",
          "sha256": "624246a106ece70cf369d01bdc1cfc819399693cb299fc39f9c730c7f3e073b7",
          "sha1": "d25b4eeca7ac3509592ce96290b5c2e0acb2d1a1",
          "md5": "96280343103ebff91cbec5b608c07883"
        }
      ]
    }
  ]
}
