{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "d31473d312aee7f29ef0907108b6e44e2705683d8897d551a007fc6afcd4397f19ba32123b964e2520e5514957e8edb66a8e95b3d34c91293de905a008311ad7",
          "sha256": "b9d2ff219d43bb9196618ba10400cc996d28b7a87063206dbca6c9beb77b1531",
          "sha1": "2261b407cedc3d63ff9ff55175d85a20972b3a8a",
          "md5": "2332aa8253cf5166f4a8939675f40ff8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "d31473d312aee7f29ef0907108b6e44e2705683d8897d551a007fc6afcd4397f19ba32123b964e2520e5514957e8edb66a8e95b3d34c91293de905a008311ad7",
          "sha256": "b9d2ff219d43bb9196618ba10400cc996d28b7a87063206dbca6c9beb77b1531",
          "sha1": "2261b407cedc3d63ff9ff55175d85a20972b3a8a",
          "md5": "2332aa8253cf5166f4a8939675f40ff8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117061,
          "sha512": "46c8a9a5cad98798ac30dcf2ffb07148ee1d311502657a1b55a7eaa7bfa43d864cba2cebd59546eb7719aca060d72b6e72795bce174711f008d240f2b1e760a4",
          "sha256": "8532746b62531b294bc3f7e716b4cb0e30938c485d19a89effb868de0e31e630",
          "sha1": "99f3683e5ab55af823987223bff2aa95090fef45",
          "md5": "a3f90849bb471dd991abeb524e596aa1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5950,
          "sha512": "6b922c08a7bb1fa21184a3d230b8d39cbae538586a21757cbc4f458faadfb39f03213b893182856b769cf104729183e6b4979cc0941d5564dfc984f03e24819b",
          "sha256": "c1eaf9b0d2f823d51c4844a8addb558b52ba3c09ff0355099f39bc756aef279c",
          "sha1": "b4cb5ab43318b9af5ba59088f3991d9551b5e6e7",
          "md5": "a04e632ebf24099503803913544fd8f8"
        }
      ]
    }
  ]
}
