{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12559,
          "sha512": "14e879ca8ce2a54a2ef7e21e4c1e76b5646bce89d8dd48929611ddff1ef0cd46bfed22d6c9514e331c0f8e304503f92c44d43c8fdbfc99f5df42cf7fa51fe7a6",
          "sha256": "8419035dc7d1eb39766d3ce2cf3a3e9315b9a9b86ab7201d76c7fcbd9b1e06b8",
          "sha1": "882f2ce5f2b7d8f4bb81230858f3947e3c7ab041",
          "md5": "f343603c5a641538215d70d17412d54d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12559,
          "sha512": "14e879ca8ce2a54a2ef7e21e4c1e76b5646bce89d8dd48929611ddff1ef0cd46bfed22d6c9514e331c0f8e304503f92c44d43c8fdbfc99f5df42cf7fa51fe7a6",
          "sha256": "8419035dc7d1eb39766d3ce2cf3a3e9315b9a9b86ab7201d76c7fcbd9b1e06b8",
          "sha1": "882f2ce5f2b7d8f4bb81230858f3947e3c7ab041",
          "md5": "f343603c5a641538215d70d17412d54d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106435,
          "sha512": "61b54191a335e9a53002e2b4b5054e30f12c955b20701af56655823204c75d18e41d669d5181e41bb2e93d129446b27ea6cbdd0206030396d6b31ce5f5be5efd",
          "sha256": "8d96f87caa406fe88013c59cca0d5f4ca5d055fb697294cd2bc234ea08b5c55e",
          "sha1": "e8446fe0e086c42cc1553a7876dd4294709921e3",
          "md5": "81c0d7ea260bd38e39049c50451fa152"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "ad45d6b522f1e7287896217ae846369a673f8f435947bb1c5f7d6233613cdc1e787548ba9a6495cf2d5dbe7d5860c1f891e4d39f329ae5b55555939401979491",
          "sha256": "b93900dc8aef0dcb75c0392f9b01414d7bb5bb100c281e3fa188b2ac95dc8e80",
          "sha1": "4fff93822816ab86d0a437d09f2badf791cf5393",
          "md5": "4f7c5d88d95cf7a8aa1345e947ef8b67"
        }
      ]
    }
  ]
}
