{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "9ca67cfe2c6710f9d0902d749b3b85ea37fa46bef8e706c578f16d35d367ac39a7d346b12f28ec05cf2dd32183e8125f232b3fd904ee44dc561e6d663630852a",
          "sha256": "102819fcb1953a3d680424148d18ccbc540023f23beffa446357f2316ff7af12",
          "sha1": "b57224ffd64135308cd87698bc213fb66e74649e",
          "md5": "29db86837d70f617875fe74015880980"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "9ca67cfe2c6710f9d0902d749b3b85ea37fa46bef8e706c578f16d35d367ac39a7d346b12f28ec05cf2dd32183e8125f232b3fd904ee44dc561e6d663630852a",
          "sha256": "102819fcb1953a3d680424148d18ccbc540023f23beffa446357f2316ff7af12",
          "sha1": "b57224ffd64135308cd87698bc213fb66e74649e",
          "md5": "29db86837d70f617875fe74015880980"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117169,
          "sha512": "7c6633af8a2fcf9720f2aa6b8154fe5df016c1aaac94faa52b02014112151bd20e103bed9f18411db320f9057ff505a8e9ac74b4a1b17875c5c57379c5656341",
          "sha256": "837308ea33d0755de4e3aa660bacea187372dda1957ecefd214b76cac2554205",
          "sha1": "7647019903882bfef5dc53dc026959657ef35ea4",
          "md5": "38c8b62d8f6fabd7eef5e59fbe0aca9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5984,
          "sha512": "f50a0074b30d067e84bf34534acf22889a78ed13fe1bd4f9bdc1a1bb0a5cafdca54a59feec5f5999cd3f4cdd7e8d4abae7941ebd7dbcc49b566d4b02f4526933",
          "sha256": "e2fafd4607efa9ff069a9cb816ddef10910830933bd2c246455942719854a6ba",
          "sha1": "9c532f5c00d073b396090dcd963fd1bc34ee86d5",
          "md5": "5abcadebeca9ae64262047bf05ff3f71"
        }
      ]
    }
  ]
}
