{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "e464a0fddb0155bb0746738e60150c6db519f0455059f41c17f7a4335027a64893354fd86158633923175dccf91b644659db4bb3532cce44b02b922114661a28",
          "sha256": "ff628421dd434448e18e557df5470b2d548ffdaa84adfc77ad39978d5815f1ce",
          "sha1": "401d720208b6992db3ba7e742ed0e4f6cf26b102",
          "md5": "1f10d49ac9ee2cd36598426c22464026"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "e464a0fddb0155bb0746738e60150c6db519f0455059f41c17f7a4335027a64893354fd86158633923175dccf91b644659db4bb3532cce44b02b922114661a28",
          "sha256": "ff628421dd434448e18e557df5470b2d548ffdaa84adfc77ad39978d5815f1ce",
          "sha1": "401d720208b6992db3ba7e742ed0e4f6cf26b102",
          "md5": "1f10d49ac9ee2cd36598426c22464026"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 118373,
          "sha512": "ef4b42a4d7904f0625f836e6f5118e66b25aafcb535a57a8013585408877893682f00946acb70eff240cd000254dc921c6d5d6ea0c8d549a4e33e683782c7d9c",
          "sha256": "2fed157403e214a500a3cb1d413b28b116a27215b0b83eccd7c7a5c9781629c9",
          "sha1": "20d9dab78a2e07a6a4e0ad8cf573e5689fbeb030",
          "md5": "5277e7fd030085d0150caf524dce5f06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "10ace0156fd23084a43189a3602b16d70064d93d4f6674f0f82df1f9da1bb3599b7ad08e75df92ea7abfb9a26a1d07865450af7d869fb5eea605eec43efed0de",
          "sha256": "750581ee57124039b7e27ba588ee10083800350cdfc16db217c157058edf99fa",
          "sha1": "8bffd342fa5a692a9bbcb2d98f236672939c9e9f",
          "md5": "61fe92081ce5f9af87fd24ac565fa299"
        }
      ]
    }
  ]
}
