{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12559,
          "sha512": "777ac55f33067f28bd79348f05c056a1499a7188b8c4e639e274bf22bed4d195ad98c0271f6abbf9d631b90d249776f0b90a77c15e2d274266728a50150f817d",
          "sha256": "c64801c7bea0526f7b0e758dd9de785b3e3105ad1c2bd2b474e4f48232219e75",
          "sha1": "6dc971616f1af768ce0ca14331ada8b7508020cc",
          "md5": "edb7438bbb0f42356d1cf4c1fd551dd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12559,
          "sha512": "777ac55f33067f28bd79348f05c056a1499a7188b8c4e639e274bf22bed4d195ad98c0271f6abbf9d631b90d249776f0b90a77c15e2d274266728a50150f817d",
          "sha256": "c64801c7bea0526f7b0e758dd9de785b3e3105ad1c2bd2b474e4f48232219e75",
          "sha1": "6dc971616f1af768ce0ca14331ada8b7508020cc",
          "md5": "edb7438bbb0f42356d1cf4c1fd551dd1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106435,
          "sha512": "621827fd15f0b6d97641930a40ad745a1bc578acf4faa0dc1a0876f32beab70dd09893192f088f605955cade49ea95dbdbf102e9a8b2332ebc17af40b05f6d62",
          "sha256": "d77a663b0607e81c4825c39278af17fb55d54ff82371c68438cc00884b71740f",
          "sha1": "80093080e22b0f588f95061143f964f12ea3f30b",
          "md5": "34fc249b49a91686ea456e68f507cc30"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "efb719bcede214859c16a5b4b5ee01a2aff1a89b02fdd19b4aec6c324462458cf5cdb279e05bcd2b0d5ad9cbe51f4cefe4326bfc342677cccbd1a4933a9187cf",
          "sha256": "620047c77734eaaa7565e90e1aa5b15856eddcec2a3211f05a5d01046c20843e",
          "sha1": "f9c69e17be048028f296de99b7c99845314e9897",
          "md5": "fad1e621625a8418036b6d3bd53d5918"
        }
      ]
    }
  ]
}
