{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "91efb3fb34e419178491b499884831683e7766fbe3efb6e4df24e46c4a03ce524259ace39ba4a63fcbac897a1c7bb248674a67c8e3267179f3219282cf02e074",
          "sha256": "f4f30a0794e20d39f81d412851b73a15bf497b6cded8acbe1e35b6757aab92f8",
          "sha1": "8d2112f5160d94be7347978155a1628d6cb9d6a5",
          "md5": "5558dc03c2680b76a63568ac52e1c49b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "91efb3fb34e419178491b499884831683e7766fbe3efb6e4df24e46c4a03ce524259ace39ba4a63fcbac897a1c7bb248674a67c8e3267179f3219282cf02e074",
          "sha256": "f4f30a0794e20d39f81d412851b73a15bf497b6cded8acbe1e35b6757aab92f8",
          "sha1": "8d2112f5160d94be7347978155a1628d6cb9d6a5",
          "md5": "5558dc03c2680b76a63568ac52e1c49b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117830,
          "sha512": "4fc4ef03382db83e13d079ace954acc912750b8a5a27b873e8ff9d16fa06dc635ff47335983db9c8da1fb2f6d8687ecfc71851fde0d2ed246ccf4a7b98e986a7",
          "sha256": "05663bc4109a38248fba6bf81866bac6c78317da1cdf07ca24c8e5af096d7b4a",
          "sha1": "752ac84ff060811aef0cf10ea77b17d6dce99f82",
          "md5": "a02cda462256963978e40677f04e8d28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5984,
          "sha512": "4d94a743883cdfde88f4a2b3b637606458f16f6086d12143969ecee9f2f559b7e1d002e56c7df0786a261feacd16625f2215928dda42780ec6badbff16af13f0",
          "sha256": "592eb7e6ad9220dec7652b2454a7288a3ebc9fe7713c90966d00177cb3f0e434",
          "sha1": "794d5389461f3f2572a9e5f0762f3199d6628f37",
          "md5": "1beffdce93eed3adce6d26287fece9bb"
        }
      ]
    }
  ]
}
