{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "d0290e80bb7d6b58d73f6d5df1b55506cd98559bbdd051027c54ddee277b9ca49f21e128cd69d88664137d2e2140201788d0580497884fcff1dc4d05500d2627",
          "sha256": "9a933c69053f2cbce3bbc50d741c2d75bfea39be0416911b712ad05d80651135",
          "sha1": "6dba12b969d602d17f6ee00d861543cc2f51e0b4",
          "md5": "7d3408d4c47a1327ab2c5e01e413d339"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "d0290e80bb7d6b58d73f6d5df1b55506cd98559bbdd051027c54ddee277b9ca49f21e128cd69d88664137d2e2140201788d0580497884fcff1dc4d05500d2627",
          "sha256": "9a933c69053f2cbce3bbc50d741c2d75bfea39be0416911b712ad05d80651135",
          "sha1": "6dba12b969d602d17f6ee00d861543cc2f51e0b4",
          "md5": "7d3408d4c47a1327ab2c5e01e413d339"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117169,
          "sha512": "d2031303990f7bbad1f7679137ade7162567f2d0d9e5e575f7c807a782c1f965832839e4ccad96908e5040024ca46ecf7ab16769fe1916f03f36b269ddb08a09",
          "sha256": "833fd1e3c08d54b613020b3e38bb59f71fc97b923c6187cee9f601cb9cb4cdb2",
          "sha1": "2b69016706029e5e5969566b743c1532827d3fdd",
          "md5": "5a8c9724fbaad27183769f995fd073f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5984,
          "sha512": "e49b3d83d6a4de040434efb7b3a150768979ae224c8a0918d35d23feaa00bce703d7ede8539316031a71446dd9c0fdcb4cddd8b2e37b20179be999cb6a2a2645",
          "sha256": "1037c9e391dbcc9a4c22b77575c34930b41ad67758df0a28fe10cc228be185f7",
          "sha1": "da8b38ca81b5f8945b84e81b657a45a6780cb777",
          "md5": "c6bec66118f7b769842c52e7c8f51aae"
        }
      ]
    }
  ]
}
