{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 13802,
          "sha512": "f07e133c086ab1c948df8592b38609b7e067a2526a4b01c1ba4aa5addc9a6c3155f014a9f6f71f24f19038816e8a340c60de6558c9eae1f1871199f46b235efd",
          "sha256": "59d4ba3d3518ac8cb11e9ac1a7eca1174ef6509a019057ba6882ede0d97f6a01",
          "sha1": "5ec5a252f021a3054a68208fac7b567dcecc0b12",
          "md5": "68730c62b9308f88e1fd93a5a0161173"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 13802,
          "sha512": "f07e133c086ab1c948df8592b38609b7e067a2526a4b01c1ba4aa5addc9a6c3155f014a9f6f71f24f19038816e8a340c60de6558c9eae1f1871199f46b235efd",
          "sha256": "59d4ba3d3518ac8cb11e9ac1a7eca1174ef6509a019057ba6882ede0d97f6a01",
          "sha1": "5ec5a252f021a3054a68208fac7b567dcecc0b12",
          "md5": "68730c62b9308f88e1fd93a5a0161173"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116706,
          "sha512": "66e12e050fd5d2ce8929a073c639a74867b19d65d213c10f88d90fa4a7683b34524732a9aa6746b56e7cf2c102e9c048b3d9e924136e8ad6e72f635d5527463b",
          "sha256": "55da16d98ecc6fefd5951a989a6a51046c32c91703495736a0afe3a83197a445",
          "sha1": "ce480b866d8eab335950e97eb6eff40b44a9ab63",
          "md5": "865dd27e96d96faa81566169f9470e25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6717,
          "sha512": "41b4192a3a5b8c425a17e7871feceffce70c00353945575245f341ea40675d4aba0789545676cb574c342918cb36ff1dc82e3cefaec97e6be1fa8e49ea365d40",
          "sha256": "0522cb06f1410cfc4d8c0e7ed620e087c92051b4cd29408f63bec4ea39d5750f",
          "sha1": "755ff5a8825f214035a56d0ce3db9ccd41925d26",
          "md5": "794a157bf1c9349041fafa19e6412b2d"
        }
      ]
    }
  ]
}
