{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "4ef9bb5d554ac0272d505a17749471fadf0e7d91c98edaff5888160a02302e46315a13503233fa9bfbbffd5a798a92cc9366af688d05a141a4617cf1b5941efa",
          "sha256": "cab3f150f44633d5637ea759d9cfe48a08a39b0bf31c3a2faddecb52435f8f2a",
          "sha1": "7afd2bdaba664342af513c829e21304fefbcfc88",
          "md5": "7ffd4e0bd24afe3c1b0073b65a7fe7a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "4ef9bb5d554ac0272d505a17749471fadf0e7d91c98edaff5888160a02302e46315a13503233fa9bfbbffd5a798a92cc9366af688d05a141a4617cf1b5941efa",
          "sha256": "cab3f150f44633d5637ea759d9cfe48a08a39b0bf31c3a2faddecb52435f8f2a",
          "sha1": "7afd2bdaba664342af513c829e21304fefbcfc88",
          "md5": "7ffd4e0bd24afe3c1b0073b65a7fe7a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117061,
          "sha512": "83f231c075f0b685fbc383b548b142be6b1fa19b3def202127b5501614ac9396e1d8b4f0de8196fc3fb0470b8f44fa8090cd201b2e0b64b7f65d68d4d570b941",
          "sha256": "b44b2b02814b1fd30a6a0136f80d39b60021dee0ef102186872471831140e663",
          "sha1": "67dce3d8e9b507b88101ddbdfcfcf07b16f5d0f8",
          "md5": "593db58f7b004dd43aec668af4fb25e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5950,
          "sha512": "d685f0201069633076b6efb61bc9528965225c60287042d5eed3c898e040dd8cb883b74c3533842a39820871497c9a7953f51133850468446b015715d40382ad",
          "sha256": "0895131cbf980500e511c159f9bde3c26c93e39c17439dfacf4bc8af094142ea",
          "sha1": "09ed402eb11a5dc0e6405865fb1b9d9cfa0bc565",
          "md5": "4f4723b0443c931c94a8063f22b8c035"
        }
      ]
    }
  ]
}
