{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12559,
          "sha512": "69184dbfa2405ca49374e5591b1c413807087045fd7b6f667389a1882074c40f5386c94c6e325f516cb551528bd457d1ba13852a95172faabe359fbaaeeb2178",
          "sha256": "987e64648990cad31c516b925390152ec19a73161a5775012bba58517a04402e",
          "sha1": "5cb6320900aa76e8c9ddfade0159ddbc7a1c4aaa",
          "md5": "b9193b65cc32c18d05b11ad1d5bfd41d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12559,
          "sha512": "69184dbfa2405ca49374e5591b1c413807087045fd7b6f667389a1882074c40f5386c94c6e325f516cb551528bd457d1ba13852a95172faabe359fbaaeeb2178",
          "sha256": "987e64648990cad31c516b925390152ec19a73161a5775012bba58517a04402e",
          "sha1": "5cb6320900aa76e8c9ddfade0159ddbc7a1c4aaa",
          "md5": "b9193b65cc32c18d05b11ad1d5bfd41d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106435,
          "sha512": "0629db9fa6c310ca26b606ef2d3d6cb36d77909d9f7b21a128cafc26f43a1452e6691ee7fb68f677216fa5f8d686148423651acc63292d8f7f4d87e703a91853",
          "sha256": "e0d809a7f4b3995f361db847cc8c2349ce2157e99f46ad715e14e0a562d54889",
          "sha1": "ea00ead75811c1d3cfc5c220817302ae1f7fb179",
          "md5": "c6c2dfb29ba75e50b030d6e91397d1ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "c0e3b74f1eafaf268df76bd0b82a2d2765de1c7ba1b49a7ea4ec90455c9d0d752fa1b284023812a43bf6d3ad67a5c66c169c3e801fc3a318fcba84c15295ad80",
          "sha256": "48d1d410e8c2e3ce7295fa638e6d532ea8f162423a3fb50f4f91022dfd8045a2",
          "sha1": "0bbdc17dba59c8f2224e829c2b952c75bd90544d",
          "md5": "5535002b7a23cdb52512c78bd11e98aa"
        }
      ]
    }
  ]
}
