{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "96262bd3da35777bde00180766b313dbd17e6acd97049a3740ed1937241c70317b6dbee5a63fea7fe24d0a0da4b598b5154999e68e14993a26a3371d4ab6ba4f",
          "sha256": "3d76c4328ad8fd0ed019388ee16d3b132b8e55603f895900fc88857a1c00c6b9",
          "sha1": "7a584be0acf7ff50b41d480dede693c4a0174d21",
          "md5": "6f90834101e4f361bce9d15b65937ba6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "96262bd3da35777bde00180766b313dbd17e6acd97049a3740ed1937241c70317b6dbee5a63fea7fe24d0a0da4b598b5154999e68e14993a26a3371d4ab6ba4f",
          "sha256": "3d76c4328ad8fd0ed019388ee16d3b132b8e55603f895900fc88857a1c00c6b9",
          "sha1": "7a584be0acf7ff50b41d480dede693c4a0174d21",
          "md5": "6f90834101e4f361bce9d15b65937ba6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117830,
          "sha512": "5143af2b4978085448aeaacc9476f4d86d860bce8c8895e61f8fa144b7a2a4f8e83942721a6b44ec8c3b069f412c2a79c27943ef5fbbd26b409c5862b02baf63",
          "sha256": "1eb3af21fcd5768b24c7a152570ea079dac9e6ea6948f5246132b65f1a4c7f96",
          "sha1": "369ba92097458e7ca8298ab32d02f07ee7a9f369",
          "md5": "5b465284059839587fc17829e4f64f66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5984,
          "sha512": "851ed711c8e294e5ffea2e65647a08bec20f3affca140e8e720f05c086decdadd427f58a3b023121ac9049d9bb300d281933b0e4f9dbcb98357d0d8a7eb94380",
          "sha256": "a4a7cffe735542e2670fc729b363e869a735089682c41079b94909a7645f975e",
          "sha1": "ef224b95bdc997af3c3f204de69ee42568888a87",
          "md5": "3511ee220ba6173ce36ed9e0f2c34d5f"
        }
      ]
    }
  ]
}
