{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 14006,
          "sha512": "9be51c1e7714845ad8d76367e32b9016a2376fe92f66453052f4ed2b6de0734b27880249413b194de1362127a73582c398ed3237f55a1a6578086db2120915e5",
          "sha256": "9387b4c0e47b2031330c8bdb8c9df0ce1f3df1797e470d9e0ba29db711e1e543",
          "sha1": "fc816a6962d40f59a5eb83b158884b738a73aab4",
          "md5": "84af5cf30a9a217f17301d44f2f606c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 14006,
          "sha512": "9be51c1e7714845ad8d76367e32b9016a2376fe92f66453052f4ed2b6de0734b27880249413b194de1362127a73582c398ed3237f55a1a6578086db2120915e5",
          "sha256": "9387b4c0e47b2031330c8bdb8c9df0ce1f3df1797e470d9e0ba29db711e1e543",
          "sha1": "fc816a6962d40f59a5eb83b158884b738a73aab4",
          "md5": "84af5cf30a9a217f17301d44f2f606c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 111718,
          "sha512": "c0488afe003267ce54800c2226e7a19536ed4f039db13512d10ed5593aca000db29b48bf0772e623dcb47adb5a4cf0353d0292a746614dad8ff81916d0038e95",
          "sha256": "3b8a786bd591377253ef44fbbcbfcdb3901fd6756a09d2a0964f8ca42cdffb98",
          "sha1": "58a8de9849b9d7175ab21af2876a1d37cc34e00c",
          "md5": "0485ac92b9c3446108574a21d7fb5ff6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6463,
          "sha512": "320b7774f8326ef66158ad99deeca91e2088389ee5249d095ee866e147ae36de202008ede121d62a90baa13147b967ca2b09437a4604a9a56d01ad30f416083b",
          "sha256": "9bdcb2e25746e21daeddb5e701d88726e4750d0a17c152598e7850f62d3379a7",
          "sha1": "0fca4537c2b4dfb26dc9474500614473f2842a4b",
          "md5": "a597533bf53ec95110f0ea91b073528b"
        }
      ]
    }
  ]
}
