{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 14006,
          "sha512": "7bda771ab529cf5740868274f31ed4721debaa4f58061d5c23286cebe4fe86a3ce8d46cab1285d13b301d19bc242de080da587f53e09783c2e5bdb02ab1a6fa7",
          "sha256": "96e15fe3753d56641ee6cab05af6063b6fbc794f4945f3c0ffc61ab591b7decd",
          "sha1": "d86e51e3a624386ed8d25560188b9df5de8ceb81",
          "md5": "691bdc38d5e9701b162ff3dfdfb0996a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 14006,
          "sha512": "7bda771ab529cf5740868274f31ed4721debaa4f58061d5c23286cebe4fe86a3ce8d46cab1285d13b301d19bc242de080da587f53e09783c2e5bdb02ab1a6fa7",
          "sha256": "96e15fe3753d56641ee6cab05af6063b6fbc794f4945f3c0ffc61ab591b7decd",
          "sha1": "d86e51e3a624386ed8d25560188b9df5de8ceb81",
          "md5": "691bdc38d5e9701b162ff3dfdfb0996a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 111718,
          "sha512": "66005ad1caaea4b1a106e18df531b9ab0dbe79be4ab7902dae3432f2829032dc271eedcce366fadbc665ec088a60c136dab79a94d1beaebffc15e66a633bfff2",
          "sha256": "ddf76c2558d6fa7719c15dc9022be033f891389edd73ffd038288b9186cb6188",
          "sha1": "793972f3bfd978201453fd202428987056c15405",
          "md5": "775b3137a10225274cd0a7282ad3606d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6463,
          "sha512": "b7814c0880f3d2fc0efcc9f31b8012519f2df23fca9c6c56708e5c9ae8b2406a521005f3c05c2ec2fe0b36e07e24948626977cd78b74781cc02d2cc40002cc90",
          "sha256": "6154a30c1369a3623f36716105ddfe9276fc023c8fb8738252b14d3ab89f025f",
          "sha1": "b39c04b971f7065da9119e75f2e409943e74027c",
          "md5": "06b6c3f6ba15e8b6baf3eee1ace4232a"
        }
      ]
    }
  ]
}
