{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "4b522ba38ccd3130c8abc0decd6bbf07833d77df932ee4902235cc10b6015d78542b2ea41badbc0dc450661305092ef07a71250ef752b07837a0a6f1f36f0890",
          "sha256": "4f39e6a458b19c3c3379232d7624a9ee13f984c710ce92d0d2b0a22024fb5c03",
          "sha1": "36807803eefb525306a814bca402e787798b0aa7",
          "md5": "2ae55addec99eb1cfe426093d39cf3c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "4b522ba38ccd3130c8abc0decd6bbf07833d77df932ee4902235cc10b6015d78542b2ea41badbc0dc450661305092ef07a71250ef752b07837a0a6f1f36f0890",
          "sha256": "4f39e6a458b19c3c3379232d7624a9ee13f984c710ce92d0d2b0a22024fb5c03",
          "sha1": "36807803eefb525306a814bca402e787798b0aa7",
          "md5": "2ae55addec99eb1cfe426093d39cf3c0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 118373,
          "sha512": "d88b180386e474a37cea8e851030257dd8de2b1f74c746325bfa8712ab677074b1fffd7474e31ca34bcf8b6b77eb607055895b6f871ce1bb9bd6ca1f60548e06",
          "sha256": "750846f43f46675e3b998ec492c17e6bd0b052eadb645cf81e4878907deff26b",
          "sha1": "dd5424334d57662194d4d5b4e53157bfd33cb575",
          "md5": "d90944798f7531f21d2eb4c92f84c700"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "e14a06a61502351b7b8cb038b1203d2e228ad7d3bffd46ed2f588f3d7a1ee6c7f85431def6a753ff7fecddc8b7cd114e480a8f2e8d5ce53f85dfdfb325a6bc4b",
          "sha256": "51808869d4f3b997e61ede9eca0aa2461558dbfcf8747e405e81b920ccefdf44",
          "sha1": "abd8a8e76efcc4b3d2c4186c8a217917a1103dd5",
          "md5": "b6dcba7520f8c6f8d08bc15cb58283e1"
        }
      ]
    }
  ]
}
