{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "8902fa7888a0a21365d5a5a9a1ab136758d5734fcc5d14e10df78536ba30c8efff404c5a5e025ceb1cd83b65426ce234fe0dda6516eed0c515c51bf1cc621ffd",
          "sha256": "252bed7818f46768f4014eb35e44f41c68dac783f646a090e2064841c6f73dbf",
          "sha1": "908ab635be75aa584c9a23bc996a465239af542b",
          "md5": "82b7e0d9a6c4e83d6bfa63b0650f5aec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "8902fa7888a0a21365d5a5a9a1ab136758d5734fcc5d14e10df78536ba30c8efff404c5a5e025ceb1cd83b65426ce234fe0dda6516eed0c515c51bf1cc621ffd",
          "sha256": "252bed7818f46768f4014eb35e44f41c68dac783f646a090e2064841c6f73dbf",
          "sha1": "908ab635be75aa584c9a23bc996a465239af542b",
          "md5": "82b7e0d9a6c4e83d6bfa63b0650f5aec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117831,
          "sha512": "9aa8ede429f8e1c24e4ec5bcb296f559116f0d45c0c8f5562790650d1ab508dbb093dac76d381fa52624ac97f0547a973163df46ff1220b93d1493a422419b4b",
          "sha256": "7e2cf0d3c86f7c746b37f0672719e9d5e39df3f31d058e61a1c266144cde7a99",
          "sha1": "3b0337a3a5d0cb04bef8de6822925700ebd9ddbe",
          "md5": "fc6f6b00ce052d9ef84c7c9e1bcb46c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5984,
          "sha512": "71d8e9ea01c07092421f5affec89e628001049f6db2b778cd7665df27f6e6f642c1e8e98278b2b5183eaaf983d38a105e7f444ec061aea0d55f0ff4a40b7df85",
          "sha256": "a43e11601384efa4505f4c86787bbe8eca3aff7d997786faee66c8166b73e8d0",
          "sha1": "3737fec84657ae6ce5be5ee1bcb58069b152ea8f",
          "md5": "b94486c6936ccf0eee3ac6271cdffd9d"
        }
      ]
    }
  ]
}
