{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "7ce07c7a6e74a3ae6d440429cdd8e1d5f7f78ef53029f441276cd226573c152963a7924245f428e3b9006fb29abb197065509152fbb92f4f638387767bf1f648",
          "sha256": "6646fda583dd53187bff22a4315a93023724cd7a84f65966a2833da442584e94",
          "sha1": "e309218e408b8b45b57030e535f90429e962d94c",
          "md5": "fb7ca2ae807c73bc43be81a9e38ca388"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "7ce07c7a6e74a3ae6d440429cdd8e1d5f7f78ef53029f441276cd226573c152963a7924245f428e3b9006fb29abb197065509152fbb92f4f638387767bf1f648",
          "sha256": "6646fda583dd53187bff22a4315a93023724cd7a84f65966a2833da442584e94",
          "sha1": "e309218e408b8b45b57030e535f90429e962d94c",
          "md5": "fb7ca2ae807c73bc43be81a9e38ca388"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117061,
          "sha512": "a428b910350b95510a148f2c482af1eedf92510ad8306f159a57a154da065e7dbd152f59ee5885789db28971ea6b533349ec6ff5dceb0373ff0c8aba698dee8e",
          "sha256": "fce5e6665ea2392680154db471835ca501d26f0d3d47e5cb1fd1f23c30059b1b",
          "sha1": "0a4fe760e09022954c18f06a3dfd99b497ca5403",
          "md5": "77fdad94169dbec6482ebd217b8363df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5950,
          "sha512": "12ae78623424d341f7b1a1277516c6fc104ce83b75e2190ce8c0d70dfb1a3ba98adadacdf11060e32e895f6630a044ef909f4b44b9dc6f57ca692055e1d48f96",
          "sha256": "3e48055679a2c5b7c5e4161830a88dd52e77a723f9a55f476904f76a40cb525f",
          "sha1": "f9c2fb2995c46f7974379c0348b25879019c6e91",
          "md5": "2513dde7a499b8409d8891990fc2c9cc"
        }
      ]
    }
  ]
}
