{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "4b39cb4bfcbe286923c6c6335705515c949a518b8735f4d2f94e7f9ad24066e19c0ae7373e82e94b6db474e66e0277a438a0a155c9ba359520b623ed64ebb715",
          "sha256": "40e6c5df647bd3db307172e4dfab882aa62dfb33f4a8f7b45af1b2ee15bf2e1b",
          "sha1": "236046768c98af957a1dc598fecb701caa3777a0",
          "md5": "9d0006f6f491056167ae98a70b1f73e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "4b39cb4bfcbe286923c6c6335705515c949a518b8735f4d2f94e7f9ad24066e19c0ae7373e82e94b6db474e66e0277a438a0a155c9ba359520b623ed64ebb715",
          "sha256": "40e6c5df647bd3db307172e4dfab882aa62dfb33f4a8f7b45af1b2ee15bf2e1b",
          "sha1": "236046768c98af957a1dc598fecb701caa3777a0",
          "md5": "9d0006f6f491056167ae98a70b1f73e5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117321,
          "sha512": "7efb7e48ab41f8566592e9dcf7d97786442e409c611942ebeeec39b5d9fb64751e81c5510cee181118f1142453660190bc2e03f38b02bcee56bfe89febec3fc1",
          "sha256": "3a93a14b0827ac5c61948309f796404fd3d43a47432acf4d7b6f075ee321981d",
          "sha1": "1ef3d801611134738d9dc5205ff80a7aacc12a39",
          "md5": "a55c4935045882fb17c26203e50aacbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5985,
          "sha512": "3516f84a400397967edeb66eedb802bc13214db82323e3a64d7aef51089ef436ebd0e7c657ecdfaaa5050daaa83b9a5faa56363d553be33f332a9d7aad37f69d",
          "sha256": "d4eb05c6b0784531bcf8b0768fc9e0cc4860fabdfc0c79a1a4db3d4d24ab9fa8",
          "sha1": "fad408e2a6b44c2d2de84f6adf940e1d941484ca",
          "md5": "b1c409e79e8759d7f1ebb94222457717"
        }
      ]
    }
  ]
}
