{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "6a7ad47f33b77c8ba9823587a565b08d2f305d63a1149d64ed202c8a5eba9f14d5936d242cb34e9b59f6b6da233f719b080a6f5955c1db2e1c423c69f597c0d9",
          "sha256": "b3b569fc244c40a0d9437d9f45bd5dbc9c0d4b3ea07c72aa137e1e21c0f0c195",
          "sha1": "c3acb98fda51effe229513450fb0a13b227670f2",
          "md5": "5b79edfab491b9372c28687bc693882f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "6a7ad47f33b77c8ba9823587a565b08d2f305d63a1149d64ed202c8a5eba9f14d5936d242cb34e9b59f6b6da233f719b080a6f5955c1db2e1c423c69f597c0d9",
          "sha256": "b3b569fc244c40a0d9437d9f45bd5dbc9c0d4b3ea07c72aa137e1e21c0f0c195",
          "sha1": "c3acb98fda51effe229513450fb0a13b227670f2",
          "md5": "5b79edfab491b9372c28687bc693882f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 118373,
          "sha512": "9dd0d5be3e481ed71ff53a6ccc296dbe25bf25663905f197385cdfc48f1247f60e42c99222fe95f69fddb541b0d3e9906ca6aa8dbc604e31b49de8469e465938",
          "sha256": "c5ad1dcd7cde76f2aefa5de66cd867fc5d67d72d0775fc692c8b13bff51d721d",
          "sha1": "c89e5f8ac8a675e41bb9a938234937db3666f784",
          "md5": "b53f310bc40391c6a0aced658b86827d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "96ab1f2a0acf2833447945b1dd5a58de52d2653b0a2e8d9b0400066bc206c0060e4ec12d2cb59895808b241fb4d6da6f9fa9b27df115ee574a053165b7ac992e",
          "sha256": "30278c5496be196913dde789c47eab65e46b61f17647b5f5d90f91f22759e3cf",
          "sha1": "3297a2faaa6fb80f0c80629dc0b0f184e1923b3f",
          "md5": "37d48a0ff641445bb4226aea211f97d0"
        }
      ]
    }
  ]
}
