{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "570f2150439e78058fb584fa5dd0bb0c4718abab72a684e716d423e9e3742e3952d900be514866aa7fcdeb015d1c0eab8d0424df9e9dae4eebec6278854c8611",
          "sha256": "175592afdc64eeca03212f68392b6f033d9ab8e35b479655dccbcfef26d9e9d9",
          "sha1": "7623d6ab66655531c3a04248b6233697627996b4",
          "md5": "2c30651153bd72ff0cf58fe97a3d8e58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "570f2150439e78058fb584fa5dd0bb0c4718abab72a684e716d423e9e3742e3952d900be514866aa7fcdeb015d1c0eab8d0424df9e9dae4eebec6278854c8611",
          "sha256": "175592afdc64eeca03212f68392b6f033d9ab8e35b479655dccbcfef26d9e9d9",
          "sha1": "7623d6ab66655531c3a04248b6233697627996b4",
          "md5": "2c30651153bd72ff0cf58fe97a3d8e58"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117061,
          "sha512": "4e1c97e9bcad1b6793f790521bccc5c3013df19cf63e8331119216ef2b1ca770557341bb0f4c1ebd70b6343cb032fe3af2ee02ea84d6071df99e1700d7ce708c",
          "sha256": "2c5d054db9c275245baf198b9ade55bc670efb28542a53ffe23c7f964b5222db",
          "sha1": "2ad8073e58185a61f3dd151dc9f1028e4c8bdb8d",
          "md5": "45d1bea0889834cf4bb3bb64fe7b62c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5950,
          "sha512": "12449c6894141cd0eca4d096fdb4ef7c9f4fa45e96256c9e5a9b00d3f361af4d1e5204e5bbaded2b4527e77bfa2a00ec29133261148179c311acc83824b23a6e",
          "sha256": "ffe1d1c8f50337499dc05b4b6a8b702eea6e3dfb1ddd5eb84ad9327afa4a2fd1",
          "sha1": "306687661a2b4e5330772b84ebb7f55de039de83",
          "md5": "254eda9acfcb62b20e5c3d86cce5c7aa"
        }
      ]
    }
  ]
}
