{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "b2901b2c9a348124dcf934e48530b48a64ed0f79ee78f43dfdb858030825f18b5155667aad31ff26972ecec54765dc94552e6ca478fd344aa0148dec12ba14ba",
          "sha256": "92c8a792839070c386609d17f7735d3cc724f7e45214503d47114b1135f2e4bc",
          "sha1": "b5b1f8c356b3b901048839f268347207a252fc4e",
          "md5": "da5c19362fb3bb4cbfdb860aa7abe5fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "b2901b2c9a348124dcf934e48530b48a64ed0f79ee78f43dfdb858030825f18b5155667aad31ff26972ecec54765dc94552e6ca478fd344aa0148dec12ba14ba",
          "sha256": "92c8a792839070c386609d17f7735d3cc724f7e45214503d47114b1135f2e4bc",
          "sha1": "b5b1f8c356b3b901048839f268347207a252fc4e",
          "md5": "da5c19362fb3bb4cbfdb860aa7abe5fc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 118373,
          "sha512": "911760b9effde04e614cb42378863ee6220db19e8f2105c418a060c2bfea8af3dbc64bb19d25cb24cef595b29626ad4c9792188b11c7b39267670f8940d0f0aa",
          "sha256": "d2e8da7249292ecca49dddda0baff3adeab00711f2c3cf197b3e31a9c1365701",
          "sha1": "0ffc1b212f5b4eb7a87a90e22f6d31a94a8f0820",
          "md5": "043e949b519383d6e08e1a960b8f2dd7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "d1b604438a0880b17fccb4f301645b25aff0c33830531ead28fed9bb938c0dcf85d57e04b3e226460ea3dce174d445f883f87726c5a70f683c35fe749580628c",
          "sha256": "b42f0d8b7047430dd736d7281c597633f4c914b07737c96df78251b495afc2e4",
          "sha1": "5a14de1d439d4abf15f8ee6f65110b56257de219",
          "md5": "1c55eda392a3e400c82fdc3e743be06f"
        }
      ]
    }
  ]
}
