{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "bd6569d7eaac3c62673960efd4c51c5122aa4842c4b8adf4adc5f979eb10b2716576752402fe7aaaa99ca5e4717e0ce7e9aeb3644dafff28a9f7a285e2c4ebe1",
          "sha256": "d64ee563ee2bc69214af8ee1d24e88c7489ebceb6e6ef72ad8d4d21e065eda4f",
          "sha1": "280bd6025bc0aabf27d954d51f99bf0ecefa2229",
          "md5": "da08d52c2da62a160bed409cf8638b70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "bd6569d7eaac3c62673960efd4c51c5122aa4842c4b8adf4adc5f979eb10b2716576752402fe7aaaa99ca5e4717e0ce7e9aeb3644dafff28a9f7a285e2c4ebe1",
          "sha256": "d64ee563ee2bc69214af8ee1d24e88c7489ebceb6e6ef72ad8d4d21e065eda4f",
          "sha1": "280bd6025bc0aabf27d954d51f99bf0ecefa2229",
          "md5": "da08d52c2da62a160bed409cf8638b70"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117160,
          "sha512": "cc4bb0bdda29fa21aacf08c94b9b44706e363b5021a6b16b72794a3631febae07ca1663a60546622acda4df9b1fde9978ed81d492e1289aaea82544a8c34f565",
          "sha256": "869b48fcf6ebb82267109a3394db1d18d411c1d9bbe617d026c47c96755a04ba",
          "sha1": "efd0b4102ba018bf22e9c745096c73665f48b739",
          "md5": "6adccd963f778f7193b140632380f287"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5985,
          "sha512": "75dd387e0fcf9eedd6d6f11917f7ecc6eaa762432e61203c06b7c55556ff931cd9e4560ce75685344daf63f3845449b092e3b5c19404b3c7fd0acc2789728a5b",
          "sha256": "56bf96c7b20cc208a37f78876a2e90ea4b6865393e3446a0614e0a5859498190",
          "sha1": "7cb8dca26aa2592b402b69939f0286eb5fa259c4",
          "md5": "d6f33b80050f3d58b01400b10aa63e8a"
        }
      ]
    }
  ]
}
