{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "59d26c00e4a2ed11adcf6fbdc3a7888d54255e708ee34458364dbe54018ac3890c02605acecdb775569865bb397fe13ff130a4aedff7bce8693f30e5f9110acf",
          "sha256": "9004c884523efe54bd393105aeda7ac999c9f2b3e1dc77d664ee3f8b135bf9eb",
          "sha1": "5b5033d57fdef36479253b7f39c1a0675ef44eb3",
          "md5": "eb652d2925f5afe144e40785333e5753"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "59d26c00e4a2ed11adcf6fbdc3a7888d54255e708ee34458364dbe54018ac3890c02605acecdb775569865bb397fe13ff130a4aedff7bce8693f30e5f9110acf",
          "sha256": "9004c884523efe54bd393105aeda7ac999c9f2b3e1dc77d664ee3f8b135bf9eb",
          "sha1": "5b5033d57fdef36479253b7f39c1a0675ef44eb3",
          "md5": "eb652d2925f5afe144e40785333e5753"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 118373,
          "sha512": "545aeca058e8cf28a9c64698ae8fa93bc0164a3f12a6bb03acdf7af42c7398033b4b4143b57d58928b93857aade207651d4cdc1396a7133dbecc86d73b8ee5e3",
          "sha256": "7701ea678ad06b6b8353b58a9b49f2b9549d21c6dbbb2b8080f3fd2e782fa156",
          "sha1": "8d3cd3a317d02596f733318e22a0ae364b65f777",
          "md5": "2916b66e67105bc7f027b8c190a23571"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "365b20ba1f9c897415d92a2f7e51bb760943b86d6cc15ff77bd14eb1110c4f0bfade9cecd72843f19163ac4fdc587af12b05518733dd9ddcf47b7177c04e5965",
          "sha256": "e4dc660cb62555d96f66b142f383c2625795ade821c02a9b2fcbdc7001a9ae26",
          "sha1": "595da46b657d87046de3a946074acf5b31d54986",
          "md5": "90a87467900d916fdcdf4edbfb6d6903"
        }
      ]
    }
  ]
}
