{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "1f3b1f483a359173d3bdb88d20b6faf82615f0774bd81cd86cd27e74d1e8a7ec7ee44e26de2eac65e7a7a64772a9bd31b6ec0ae00c38265dff22de6e38b57887",
          "sha256": "47d1297110217a980e703e1c2bf6cbbb1c86f95406abbdf97749a0916f967811",
          "sha1": "bdeab9f93fc983457c8991ff5968a547f0dc0575",
          "md5": "457d29224da6d41a1aa616f3d931546d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "1f3b1f483a359173d3bdb88d20b6faf82615f0774bd81cd86cd27e74d1e8a7ec7ee44e26de2eac65e7a7a64772a9bd31b6ec0ae00c38265dff22de6e38b57887",
          "sha256": "47d1297110217a980e703e1c2bf6cbbb1c86f95406abbdf97749a0916f967811",
          "sha1": "bdeab9f93fc983457c8991ff5968a547f0dc0575",
          "md5": "457d29224da6d41a1aa616f3d931546d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 118373,
          "sha512": "8f850500caf4576cf2bdab39fab840f37a8ad4be7ca7b434027dcde4f2c897aed2a8b97a9690ea785359cf88e3928e148049cdfa59e6390396470296156bdd51",
          "sha256": "33b9537b71df2b3159fb4efc38ed1e344807b4c9e45b7315179f4a02fbcfd3b7",
          "sha1": "476774dcc655a372ed793a8c260c3de9040134e7",
          "md5": "e5473af74a8cc37af527d2ff0bccf873"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "104fe1169950f1c536903e1275247ee60efced2c5b6fca18bfd381db2b9599811754cbf3675ebc49da1670564b9d5142a7c0d0060ca45b98c59b2aca6178f286",
          "sha256": "ddf375398a33d1ee8865754cb36dd5852da66ebe91051904ee90c1c08d4f3f5a",
          "sha1": "60f2b48b6febf46543fe95e3a619225e5747654b",
          "md5": "220a216c908003a2ad2852299ac46091"
        }
      ]
    }
  ]
}
