{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 14093,
          "sha512": "497abf767428fdaea81613b56709e98c4d0b12dfd50aa0109135f334e4a39299909d873a8df95fe3de76eda08a5c5486ec81c638f0db0bb56d93fe7086240005",
          "sha256": "8917b34fd1fca6a9a787f6319f6c30115cca817019369901e8ebb2a7462050a7",
          "sha1": "b9d59bd9a5b3d7a8add79d8b3ecb66a17acf494b",
          "md5": "6d1cdea23142eee4360815479b61150e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 14093,
          "sha512": "497abf767428fdaea81613b56709e98c4d0b12dfd50aa0109135f334e4a39299909d873a8df95fe3de76eda08a5c5486ec81c638f0db0bb56d93fe7086240005",
          "sha256": "8917b34fd1fca6a9a787f6319f6c30115cca817019369901e8ebb2a7462050a7",
          "sha1": "b9d59bd9a5b3d7a8add79d8b3ecb66a17acf494b",
          "md5": "6d1cdea23142eee4360815479b61150e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 111614,
          "sha512": "9f10e36ab0dc615170319f50fbd54ce00ddb7ffdd542077aef744e4a73d85503468ec373fb1668c30fea9dceac50372aed5db40cab0d74d7b947d17d1dae32ff",
          "sha256": "c87a77d0e7595f21b24a8b14b4327191a5819b684590580827492a087c362c4f",
          "sha1": "a2ebfe169990ad386fba828473e48cb5a1a1d612",
          "md5": "ede935acf7c054efe6ee594363c7e6fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6527,
          "sha512": "6e07b68b14474b75ae3f36caebcabeca73de33541fd3c5644b153d29533ca23735a1ae19681b574bcf5becf109b69a2826f37f2815afee6d2924fa5e03dc4af4",
          "sha256": "13ca96a705ff0868b8569cefb7b14ac91351617a9b70492b52981508a9ee9546",
          "sha1": "1f5bd957df4851c56c33b946afbe2523d4c3ed29",
          "md5": "26aff7e87e0ddc2d331e78838d01a1e7"
        }
      ]
    }
  ]
}
