{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "4a0e970db853f2512619e84d9e0c851903737acbc9e4a4665c9295998f6b19e7306c99aefef975483d0eb00bdf5334938d61f39f8a81f92ad8e81277d37dae5f",
          "sha256": "c9ca3c092df694b286fdb25fc956e5226e901327cf33a98b31af71003fdc2ce7",
          "sha1": "f34479504ed34389072b5b3eb16014c71419a7e7",
          "md5": "00410c1a18e9f64eb213a80ef9905634"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12191,
          "sha512": "4a0e970db853f2512619e84d9e0c851903737acbc9e4a4665c9295998f6b19e7306c99aefef975483d0eb00bdf5334938d61f39f8a81f92ad8e81277d37dae5f",
          "sha256": "c9ca3c092df694b286fdb25fc956e5226e901327cf33a98b31af71003fdc2ce7",
          "sha1": "f34479504ed34389072b5b3eb16014c71419a7e7",
          "md5": "00410c1a18e9f64eb213a80ef9905634"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117061,
          "sha512": "afbfcf5f6729a3a8ba0e01f1c8dd636ab435c1aa38cefa38bb3017b5c1155817c13ddefb5b051d89cdd4699fee2a737ee5592f63aa8d1180e8b38d026e09bdb2",
          "sha256": "b5fccf71284e9237acc7d815dabcbfded8017fa63ab1ecd0750fab53d4434c5f",
          "sha1": "3a43ef7d2941a28c463b057814b34b3751697d12",
          "md5": "210dc9037c2178392266951ed03adbda"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5950,
          "sha512": "0a219f07464b17c648041506ecff775df79019ca955da3094fa7a0fe5eb2ff5acb3719fff4fb20fe6d9a9c25cc859d69532ec7a13b619695efc385960eab86a9",
          "sha256": "4430281a7258a18179656e0b444dcae894a11a7d7d9b524a0aeac30fc97a1843",
          "sha1": "44c17e79a6a14359670ad578f233008092febb63",
          "md5": "686ecb73a3bc24be0fe1be48973c36db"
        }
      ]
    }
  ]
}
