{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "a872560db118e5831c6f8332cb409b29484522d6c8da0258f4a60d68c420e32e66ba04093ec69d16491a512221734a07620793fa6922c7c7c2b011c1537946d0",
          "sha256": "ce33b920c77f1f2c4f716ad6dbcf07858db5c43f853faf3b82f9f386069a0b6d",
          "sha1": "e5c286201c3d4437c0456b57c76a696cd4152cfd",
          "md5": "25f95e1807702e46d043803465162fbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "a872560db118e5831c6f8332cb409b29484522d6c8da0258f4a60d68c420e32e66ba04093ec69d16491a512221734a07620793fa6922c7c7c2b011c1537946d0",
          "sha256": "ce33b920c77f1f2c4f716ad6dbcf07858db5c43f853faf3b82f9f386069a0b6d",
          "sha1": "e5c286201c3d4437c0456b57c76a696cd4152cfd",
          "md5": "25f95e1807702e46d043803465162fbb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 118373,
          "sha512": "c4f029e374b4bdeb5a78532ac2362db617c6d7181fae3873db1973e657232d6253c99d6472664ccc5f147e231a6374d78ce8e48d50f6dd459e6b7aa32fe73f18",
          "sha256": "a131cd2c6078a2871c3a05196578087eac6ac4ddbbfadc71e87ef9bbf3fdaf5a",
          "sha1": "32a236391b3fa15ad41e054784f7e888316fdc21",
          "md5": "3fd684eae7c3e5d4126e46f582eedec7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "38a2a1265824c4b940767069635b1fff06e2b82a4412ab84d56519afdcb14f88429ccb09cf7f451d2f95d28f2a2650452a95ca1bbee8e0c4a954f8eacc21c4f1",
          "sha256": "9daf68049fe713283202543ee8d8d437413127bc98c518013c0cb8597ef75121",
          "sha1": "241cc54570410905319791d8775581664e740f7e",
          "md5": "e68dc26b0240842c60ab8344c69d82d6"
        }
      ]
    }
  ]
}
