{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "753e490c60573d9365f9fd72f8edb6983ee5d7610287fa11938708e9c0204136a49b4390c9542e17b05d0c5f2c99ff96728ba084d35f054f2ab1ec520d54f175",
          "sha256": "a05c57bb67277f34a6557a91c98712cfd2fe32053ee769bc3cccb20e2cc5183a",
          "sha1": "899f657d27dff1a3bf5e9864c52429adab6838fb",
          "md5": "41f3263b28c031b0bd7844111cb8d2eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12573,
          "sha512": "753e490c60573d9365f9fd72f8edb6983ee5d7610287fa11938708e9c0204136a49b4390c9542e17b05d0c5f2c99ff96728ba084d35f054f2ab1ec520d54f175",
          "sha256": "a05c57bb67277f34a6557a91c98712cfd2fe32053ee769bc3cccb20e2cc5183a",
          "sha1": "899f657d27dff1a3bf5e9864c52429adab6838fb",
          "md5": "41f3263b28c031b0bd7844111cb8d2eb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 118373,
          "sha512": "33c21818f6f418197d5980479c04c1e12a4086cac99c7f51ce0d48deaade882f3abce2f2ef4a5793105d908d122fed625d5bd76cd1467b1b1bdeeb5520e80e0c",
          "sha256": "5f9532f603d3093daf4a1dc7e2de20939adfd336f9c4ccbbdfc1525417292a6a",
          "sha1": "a383c03b79b512f15f153f3502a16b715c3a9ba8",
          "md5": "4784d51fd5203adcd98fd9f2914c0476"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 6105,
          "sha512": "502f8f34e00fe4d535d3896e7009c676d86a7f35ef536f860c5674ad4e9be4ab14bbbdb23820b964541a3bbb05d52d07b73fa403c7737e2e87be7b5570b4b4db",
          "sha256": "1ec722c35ae3d4331bf1ed542944a7dc739c47c7155dc64b3f4eb6526b9d53de",
          "sha1": "e6d118bac0bba14b996517aaf494d72a88aff215",
          "md5": "3d23ba2e9f986f3f11e9e30fc785359c"
        }
      ]
    }
  ]
}
