{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "94f7a7fcd86619149c26c6a1f06ecaab1cf5580fbbf688a4ba2d5761a1d564033ab1666992d8f50285368ee5e64b47780f240a0295bf91558357f117e6fa4d04",
          "sha256": "e67988bc7312ce71b867aa3586eea8bbc3d68cb255d53886d2d31ada8a547f0b",
          "sha1": "41ac22af08abd2cc7b47e880a012e73be8b7db56",
          "md5": "21963f53c960169239d7b7d896a24750"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "94f7a7fcd86619149c26c6a1f06ecaab1cf5580fbbf688a4ba2d5761a1d564033ab1666992d8f50285368ee5e64b47780f240a0295bf91558357f117e6fa4d04",
          "sha256": "e67988bc7312ce71b867aa3586eea8bbc3d68cb255d53886d2d31ada8a547f0b",
          "sha1": "41ac22af08abd2cc7b47e880a012e73be8b7db56",
          "md5": "21963f53c960169239d7b7d896a24750"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117321,
          "sha512": "37720e33de28238fb8ce85a54cb9ab00c9655f0fe3df85e8240077347c73a39ce704afce92d1433c182d72d8dea37f0ec4a0a4b67c97f420b218c506d0e58fe8",
          "sha256": "7bc70b43ab99a739619c39f1d07446be7b3eb9c72d6893fbd1ba622bd59d7c3b",
          "sha1": "8b8e3234de482583913002e192354f671a49d188",
          "md5": "160d8cb654cf6bf4d2bafca672146381"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5985,
          "sha512": "3bea5842cd30901b34749c23140bf2c2158ec317db593d908193e13a6e6e70bc110442d79d0ee159683e4bbb9d63ed2256d70be964f7e1bf4d22cbe59774811d",
          "sha256": "58a3b46950ac7544d696f6a6dedbd0fa59d7b6aa9bc33f9d8567532da04a3426",
          "sha1": "b7c7b094210296b4fcb96e3e3374e2a92335a865",
          "md5": "394166da9458e3503b75e9e13715b481"
        }
      ]
    }
  ]
}
