{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "fda34b8b8862b85e831d6f86a2a6dd92370c87cf8467dc18b22aa3a4071bcbf5b7faf4da23f94bb2723ac1c10be6dff4376ffee6faeb072a3530eb34dd857299",
          "sha256": "a5d499c163fe220a62d9f87c39efb3c143a04e79003a4321c678ea17d52a59f8",
          "sha1": "b474b521d18e555e312d41be62707bae347d533f",
          "md5": "df0f7113a73e55cccd8280504aee842d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "fda34b8b8862b85e831d6f86a2a6dd92370c87cf8467dc18b22aa3a4071bcbf5b7faf4da23f94bb2723ac1c10be6dff4376ffee6faeb072a3530eb34dd857299",
          "sha256": "a5d499c163fe220a62d9f87c39efb3c143a04e79003a4321c678ea17d52a59f8",
          "sha1": "b474b521d18e555e312d41be62707bae347d533f",
          "md5": "df0f7113a73e55cccd8280504aee842d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117321,
          "sha512": "c958a6a890c1d827c2532edd12dd01a6e7c4b6b254411d0ab1145f5cff7802aff02ecc217918dfd0aea5acdb8a86f0529531621b91b86f0a5b0374aaa65e6f64",
          "sha256": "68d9340eb8de19789b0dd0337393d1d0e5ed3606d03c1bae52bed07c57dc0262",
          "sha1": "43cd398a952eb87bcac4217465660e1bdd66d0b9",
          "md5": "2dd4ad2733987cd848c6092ccd85ac7f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5985,
          "sha512": "cf5e55881644533d8e0cdfaa887d082ccd70bb7c3737e9e99b917d53a4e9eda88ee9035cb7f41dd6f6c2231366ccc3384f3d40cbb4fd6132fa744c3f770f6a02",
          "sha256": "2f29bb5f7aa34c35aafc3d247cc464609aeed6d48fff43dcb692b366112cd802",
          "sha1": "9a7842fa1c337590083133de2b942d04a9a18443",
          "md5": "751ada0de83d11f274b3cb63f7836ae4"
        }
      ]
    }
  ]
}
