{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "1baa360691445662982a1d1257ae31d397cd4af60fca17d380209ec362f98674e1d02f933514f60c07c5283de9829e7dd5f50cdd5332e969ed9e181f094ec666",
          "sha256": "b360b7267df372b208827cdc25a317e6a8d962e847e78b7b3eb4b2d39f043fe2",
          "sha1": "d5b50dd7a5f66cab0da9bffefaed6f1ce45e748a",
          "md5": "1f9849d18731740d508a58d8bb4cd484"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT.jar",
          "size": 12212,
          "sha512": "1baa360691445662982a1d1257ae31d397cd4af60fca17d380209ec362f98674e1d02f933514f60c07c5283de9829e7dd5f50cdd5332e969ed9e181f094ec666",
          "sha256": "b360b7267df372b208827cdc25a317e6a8d962e847e78b7b3eb4b2d39f043fe2",
          "sha1": "d5b50dd7a5f66cab0da9bffefaed6f1ce45e748a",
          "md5": "1f9849d18731740d508a58d8bb4cd484"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117160,
          "sha512": "d45f966b7ff37602c2a609ae4c6c8d5f2d37193420e8f5a9e8d1d1979b98e31a2510ab6ad6d3b2a4a2ebfa249bb5a7c8b5c82c71774ec5915657e6988241859e",
          "sha256": "cd72dfad917ce6801e9167c81eb3213e976da0d1bc9d8284dbe3ac8db72ba9bc",
          "sha1": "4bd33b33394e95cee4039ce2bfd71d5269670114",
          "md5": "abdd7fa992cc9eac5219241b96018a93"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bemode-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 5984,
          "sha512": "6c7fb17e1358fe2c8659ea8846950fbbb579d91633ecab2a8ad82e0ff26f719ea8a9ae3d64377c9448ca48c86dc481d72588cec67d08e2c7b917b399a7f282c2",
          "sha256": "795e81e0d5ec6689f1e93e91951b4b629168c26bd40dc54770c46af0648ae81b",
          "sha1": "81d79fe47d1967b261d7e0aa28ac35da4591ecc9",
          "md5": "60e1387cd98a57f275d4b5ba8f5b9d27"
        }
      ]
    }
  ]
}
