{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-api",
    "version": "5.1.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-api-5.1.0-rc.1.jar",
          "url": "box-api-5.1.0-rc.1.jar",
          "size": 63503,
          "sha512": "b898d7443e3d15a7940c97df695dd0c1aa7d1e91b27494935d8d11e91b05a37d00c73788073feac7aabf17396bdd3381a6449ed101d1eea1cc31426bd160cf06",
          "sha256": "6cb03c96e94576a9c2b756354bba354e7b0a5919212ba4367a31ac674cf9470a",
          "sha1": "a32cf7310112557cb5bd30d96d46176ba00ce1e4",
          "md5": "c5e03ca459a4b212673535c95b05c3fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-api-5.1.0-rc.1.jar",
          "url": "box-api-5.1.0-rc.1.jar",
          "size": 63503,
          "sha512": "b898d7443e3d15a7940c97df695dd0c1aa7d1e91b27494935d8d11e91b05a37d00c73788073feac7aabf17396bdd3381a6449ed101d1eea1cc31426bd160cf06",
          "sha256": "6cb03c96e94576a9c2b756354bba354e7b0a5919212ba4367a31ac674cf9470a",
          "sha1": "a32cf7310112557cb5bd30d96d46176ba00ce1e4",
          "md5": "c5e03ca459a4b212673535c95b05c3fa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-api-5.1.0-rc.1-javadoc.jar",
          "url": "box-api-5.1.0-rc.1-javadoc.jar",
          "size": 355747,
          "sha512": "b303e227c83a3440e5c76e94b22bbe67406d4d2df1e05a306b1b3e4f7bced92a2be258684d2fe8e4be3a57deb26491a9e8a03dac9ceb3297279367da7cbfdeec",
          "sha256": "42eb543a72ed29375bd42d0db4d44a68023a1f614b86af8860e71851906fd201",
          "sha1": "adbb3ab187f97b93ed2f02a2f06e22fd43bf2b98",
          "md5": "7cc05feac87bd2e6238e3d72e2f56f23"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-api-5.1.0-rc.1-sources.jar",
          "url": "box-api-5.1.0-rc.1-sources.jar",
          "size": 50621,
          "sha512": "ef239c1ee986db918bcada19f417ea956f5f32fc1c3bd95c9a731776aae2773d96fd9a40e8e795ccb680aaca3880ce1071be0f9b018ac3d7fb8c7b1a27d1cd1f",
          "sha256": "c53c77c14c66aed71d76533d24e3d980ddecaeb429cc96459684470fb12c308e",
          "sha1": "3938289f123151d7936a2da9a5a0bd3c5c3c38e2",
          "md5": "9c6eda3dd4ddfe3953612c821c41129a"
        }
      ]
    }
  ]
}
