{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "5.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-5.5.2.jar",
          "url": "box-bemode-feature-5.5.2.jar",
          "size": 13945,
          "sha512": "65ef0f8c8a5edabdfc2b24a4b9415fa80f78d291aac53ebbe4bd1b7cd02bc7181e98fd05cb7ce300ced595a27fed3a470f395a3283f534aaa77aa2168e2d9671",
          "sha256": "8dac4cab95f5f0c759ac0980032a0db96f3b6562d9b5ba3ae7d59ecae02cbbb8",
          "sha1": "0216a451fd495729765d318280dab797ded2697b",
          "md5": "227a8e67062fe9387720ffd3e937f239"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-5.5.2.jar",
          "url": "box-bemode-feature-5.5.2.jar",
          "size": 13945,
          "sha512": "65ef0f8c8a5edabdfc2b24a4b9415fa80f78d291aac53ebbe4bd1b7cd02bc7181e98fd05cb7ce300ced595a27fed3a470f395a3283f534aaa77aa2168e2d9671",
          "sha256": "8dac4cab95f5f0c759ac0980032a0db96f3b6562d9b5ba3ae7d59ecae02cbbb8",
          "sha1": "0216a451fd495729765d318280dab797ded2697b",
          "md5": "227a8e67062fe9387720ffd3e937f239"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-5.5.2-javadoc.jar",
          "url": "box-bemode-feature-5.5.2-javadoc.jar",
          "size": 116514,
          "sha512": "9930cdf4f3232ffd37588e4dfe96ce51e1c990f9c408c6a3e920a4a18b139cff2bfe88adb88e91873e0f6e4910ec170da74a88b47c2f5cff6fb01535d8a32da2",
          "sha256": "bf3b651c69df4dfabf7806184d7b30fc9a637d507cbe641dece917b8cf74bc3c",
          "sha1": "937e27867501aacbe641a88aa52a0feb69319906",
          "md5": "55f6c19eb39730bdd7a869ab969343fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-5.5.2-sources.jar",
          "url": "box-bemode-feature-5.5.2-sources.jar",
          "size": 6727,
          "sha512": "3ee26138bae363d048e569b4d40fe672a88900c1eefda7a0c8081d38e267b5bfe1909be4d791bd925f33c6fc5ce7fde4b7b5cf235c99beedc2736adf950bf1c7",
          "sha256": "fdacc88be179281b4208a2d582fa623534855e163ddb68748e7e8c843992f223",
          "sha1": "97ecee441610704986cc8d5f2037e34d65d1d348",
          "md5": "2364f41306c914c103eb95d588a658a7"
        }
      ]
    }
  ]
}
