{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "5.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.2.0.jar",
          "url": "box-storage-api-5.2.0.jar",
          "size": 22674,
          "sha512": "df9df87e0939651fb6ea710b5d5fe088a185af942c59feee293dd07670c3df5c448a9564dd8b079d2097704a014d41c35cb64dae223b74b8e4ac6c93143855d4",
          "sha256": "4a0331e89cfab1d3690a747bf6509ce3a3b5d0b10423d9fb30c6926a8438ace2",
          "sha1": "a054d796badd559bcb72c2e2f1e2bbecfb743f45",
          "md5": "61319e66f4be5ef0117e1125f6cab6a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.2.0.jar",
          "url": "box-storage-api-5.2.0.jar",
          "size": 22674,
          "sha512": "df9df87e0939651fb6ea710b5d5fe088a185af942c59feee293dd07670c3df5c448a9564dd8b079d2097704a014d41c35cb64dae223b74b8e4ac6c93143855d4",
          "sha256": "4a0331e89cfab1d3690a747bf6509ce3a3b5d0b10423d9fb30c6926a8438ace2",
          "sha1": "a054d796badd559bcb72c2e2f1e2bbecfb743f45",
          "md5": "61319e66f4be5ef0117e1125f6cab6a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.2.0-javadoc.jar",
          "url": "box-storage-api-5.2.0-javadoc.jar",
          "size": 148151,
          "sha512": "1b415f3f7e98ef6a666f2bf466086248bc36e7803e8657e5591ff5cbae48046d435904b21a6ac9f66ada76b70f231d1ca944e0eaef79c8b58afca60c497b58b5",
          "sha256": "9f9388c5f8844d52eeb80a149ead627139c0f1149f02ff62d05762ae414cabad",
          "sha1": "0d6476943d29c7def1ca6243cda6c07da8760dcf",
          "md5": "89942b2b1b1c7df44e4d678ad2a2679a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.2.0-sources.jar",
          "url": "box-storage-api-5.2.0-sources.jar",
          "size": 13105,
          "sha512": "208eac6ddac1a253203e976a8167f2805307ae373411828fe93e28a41f838eab5b20c3d52b9b37653dc5fe11e3b569a506d27364bc3edb3e3191dda9384e57f1",
          "sha256": "edda9a7e305c62306cb72bf31be8282a1af4913ccdd0dec00a4c4eea46940e35",
          "sha1": "a934849405a40225d43ceb3af672fc8fbcf9ae08",
          "md5": "949aa402f561a433a0a137f8d725c8e7"
        }
      ]
    }
  ]
}
