{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-migrator",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 17847,
          "sha512": "8c62a889309242900cfd5c0fd2364a91ddab3471ebb38b03007fe8eea5389455d21c2341ad6b4ebecb4f49b5634b615ffe84b68217a61e68f27310e0bcaf06ee",
          "sha256": "4cbca55eebd60134996d4970c281247ca5c11f8cbd563d8ee8385137ecedac7f",
          "sha1": "89509fd99c529b607e6329511d550c405cb6405a",
          "md5": "9865914a8d7f56d18988c64f468d32c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 17847,
          "sha512": "8c62a889309242900cfd5c0fd2364a91ddab3471ebb38b03007fe8eea5389455d21c2341ad6b4ebecb4f49b5634b615ffe84b68217a61e68f27310e0bcaf06ee",
          "sha256": "4cbca55eebd60134996d4970c281247ca5c11f8cbd563d8ee8385137ecedac7f",
          "sha1": "89509fd99c529b607e6329511d550c405cb6405a",
          "md5": "9865914a8d7f56d18988c64f468d32c0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 119787,
          "sha512": "5c6327d270f16727648d7c857adc0e2b237354acfee3c12542a16914031591a70ba927a29e4411ac617aa96a47ea06d903761ad22699cd84461438c6907ef563",
          "sha256": "fb2ba60156dff4238b44dd9ce5c1ba4b120aca98c18ef1aadde6c19025f124c4",
          "sha1": "ed04e678cd5e417d625af845088af5144ab1f83a",
          "md5": "1320107010ca495c50398dc39db6aeee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "size": 8454,
          "sha512": "fcc1a0894e7263cc0d53ab0ac19fedbb9ea4c0a58f009c30d3b0ba290729eb5990f9283326892432165720495c00a66324382683baa1f05d7aababdc0f53f63d",
          "sha256": "1eb39c8ff6551aec3d37b6f7a8772391d9fc301227968ad13c4f296b2bba4e60",
          "sha1": "7453f5d291661ed7d751a4c78d84dab60cc1a4fb",
          "md5": "e0b773688bf0fef63a958018e1be8650"
        }
      ]
    }
  ]
}
