{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-migrator",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 18431,
          "sha512": "aa48887f66e7c4a450b0ed6b83ce49495b3ef20351560f6e7cf092e1cf747cf9c48fd1b0edf856a34b85f37b79f82ca5c13aaa37a934c58fd0f0ec20712c285d",
          "sha256": "b2091be9d9fccb217b212b3440eae559db500c61321f182fc6db968629b621b3",
          "sha1": "96bbe24acb414ef2b98001a5b4d5d60b6e4f0596",
          "md5": "54af373a3d311e06b8f7ad326188935d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 18431,
          "sha512": "aa48887f66e7c4a450b0ed6b83ce49495b3ef20351560f6e7cf092e1cf747cf9c48fd1b0edf856a34b85f37b79f82ca5c13aaa37a934c58fd0f0ec20712c285d",
          "sha256": "b2091be9d9fccb217b212b3440eae559db500c61321f182fc6db968629b621b3",
          "sha1": "96bbe24acb414ef2b98001a5b4d5d60b6e4f0596",
          "md5": "54af373a3d311e06b8f7ad326188935d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 119784,
          "sha512": "154178111eb7c54ffd3658ea2cf56a9b86675ebf13dc4fb1759b73085bd9b5f84a38364d1da7747c4d22728f9a4b528a01524fb5ee8c5119b6585ede90bea932",
          "sha256": "297d68bbfea5c3737a3f6713a0f6cafc88314900923b9286075c3dbf49dba744",
          "sha1": "aca8be84cff7f312f9064cfad2daabce048741ba",
          "md5": "ac46bc175118e1482890d2914039455e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "size": 8635,
          "sha512": "a4cd72f78d3035a3ab1b7d5114f37ab0cc1702acdf516cc063783a40bf1fc9ec31bd3760a459b081914d6a17f33e7190ee449733a1929390c4f9959556715060",
          "sha256": "7029011c3abdea91ad30dda6506f7fd58adee11cc5789c2b3a9d606946b4cc2f",
          "sha1": "5908053193c1a4a39a3fd4dab7236b1c273ffc29",
          "md5": "c67cf887fae71789daded48513496972"
        }
      ]
    }
  ]
}
