{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-migrator",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 20231,
          "sha512": "a483137325f7d2c8ea4846eb132cd0363d6e61cea30e651a9e20dd93b79b267bb032e0159749e729b9eb3e064ab3b7ad99d38c82184da85d73b3e7a65c72661c",
          "sha256": "f6141dc934812dd587c2b61616b38da0b53cac4b2faf8809355f0cbbdd13ba48",
          "sha1": "91e887d1d3b9149b41414a2cd1bc1621c3b253c7",
          "md5": "1656e9944682fb54f506c980748a07d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 20231,
          "sha512": "a483137325f7d2c8ea4846eb132cd0363d6e61cea30e651a9e20dd93b79b267bb032e0159749e729b9eb3e064ab3b7ad99d38c82184da85d73b3e7a65c72661c",
          "sha256": "f6141dc934812dd587c2b61616b38da0b53cac4b2faf8809355f0cbbdd13ba48",
          "sha1": "91e887d1d3b9149b41414a2cd1bc1621c3b253c7",
          "md5": "1656e9944682fb54f506c980748a07d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 119509,
          "sha512": "2b7b089ef9827f94198904b0429ceb8161490189b385613fffbb0c96d75c5121cb5afa8fbec46f7019f9e45b98ee9fe6d859ea8968805174b9df70eeafb2619a",
          "sha256": "87535978a985d68de47e5fc1c6bffd0d5ea6ae60d7496dff2703e25817319ad3",
          "sha1": "1ccd78dac4c6d2f9617f39a541cb6bc0c0a55db9",
          "md5": "5fab260e2690aa0e9102c63c3d3c0e37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "size": 7845,
          "sha512": "f88beefc1c77822d6ce0448527d1f5c59bfa57594f21f59ef092a3afcc3dddaebad8acdedbcd97c63c3943e4676df8c2bbc0da64ce4efc199bbdab7a62b092cd",
          "sha256": "78901c77e61fd88660f2ecbbabd07365aa0b7a5133985f11d3e62e5d008a4e1a",
          "sha1": "2be799c0a91238f852d4c4cc17c997e05e134f93",
          "md5": "4e6d3fbf3d88af9c48d73ddb26e675c0"
        }
      ]
    }
  ]
}
