{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-migrator",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 20631,
          "sha512": "cdee6e9f1294bace72bbaeaf02d986fa1992becbddea6f580e2685ddef8ce64e07254c3f2a040a3914c0d35bab9f93351e45c5fc24f5f22c295c395664e603c0",
          "sha256": "0acd5cc5501ead8554517bfc983481b9416f1946a806839f66489fe253205953",
          "sha1": "4118a5c70128bdc08778d696c911abada41f710a",
          "md5": "d9cf972682adaadf6f50d90106b2fc81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 20631,
          "sha512": "cdee6e9f1294bace72bbaeaf02d986fa1992becbddea6f580e2685ddef8ce64e07254c3f2a040a3914c0d35bab9f93351e45c5fc24f5f22c295c395664e603c0",
          "sha256": "0acd5cc5501ead8554517bfc983481b9416f1946a806839f66489fe253205953",
          "sha1": "4118a5c70128bdc08778d696c911abada41f710a",
          "md5": "d9cf972682adaadf6f50d90106b2fc81"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 123301,
          "sha512": "992096348c8658544fca91017e70f9a948336c56de808e43f8bbabb27293cba86299d917d3280502930f957f35383e032c8a45f1198b3a48b999ceb53333f487",
          "sha256": "fe329b2a45fe94c17ff94294861cf3d940c15f4159743e493f89ab0c6d2f933d",
          "sha1": "31a701acc627aa83304fbf6ed2e69d77db156f2e",
          "md5": "dbd5308fe11fd6d4c19896f1557a90fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "size": 8324,
          "sha512": "90624efc67eaf9580870e668be96ca733ef2f33729f14667c6efdaf2611c3e593c4c7a12963496c0dd0664da8b016873cea62f10d4a23cae216f8659731052c6",
          "sha256": "5fe931804f92e24a3de0c7cc8adbb4d592c7c5edfa2be4c4b46a7c85575eebb1",
          "sha1": "ecb14e9a6e9b3a0a26c8c91ffbad4012938689b1",
          "md5": "7c9ea5be76cb6d0db55c3aac69861abe"
        }
      ]
    }
  ]
}
