{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-migrator",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 18541,
          "sha512": "54129a967ee81ecaa8a2acfb5992ea70283c73f3ceda262861bd69eae499a4d471a3682d705b6473a728a5aef661c13a710b72d919bcda794fcf3086703b9a13",
          "sha256": "517c25d4b577865579b6553ba9cb4e96293f07f476e43a23ecef00d9d4c061ba",
          "sha1": "bcd201e047e4041aa295c1eb765b1a33ac9d41fa",
          "md5": "a303b7deafbc9e9c5125628510bbebd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 18541,
          "sha512": "54129a967ee81ecaa8a2acfb5992ea70283c73f3ceda262861bd69eae499a4d471a3682d705b6473a728a5aef661c13a710b72d919bcda794fcf3086703b9a13",
          "sha256": "517c25d4b577865579b6553ba9cb4e96293f07f476e43a23ecef00d9d4c061ba",
          "sha1": "bcd201e047e4041aa295c1eb765b1a33ac9d41fa",
          "md5": "a303b7deafbc9e9c5125628510bbebd7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116531,
          "sha512": "8aa9011e5ff58e1739241877f1a5f9340426b6c8f7bd4e8386c15d175c123c9c40ae15a0a5803e3ff2126f7968483b2afee32d9e98e31beb5bfa3f9c44e9ca6a",
          "sha256": "ad7fc5030a6f576e5363954322035ae24b22540f3993f89a24f5b190f4325e11",
          "sha1": "f60b13ebcc296874d5628b25cd6df6aa2ba6d23e",
          "md5": "01eeee416e340c5976dc4b783e8a10b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "size": 7556,
          "sha512": "b43752ae51d6a95c66a456e994788a07d4883d1ac20b325d746c9e7b7f66e43ec799e6b53607bc33be608bd9510bad23b1014b7a57a85704ac84b59c7cb562ab",
          "sha256": "3a119617fca1dfbb1f8bf16433e74ef17c1f282302bb7d45bd37b376e84b540b",
          "sha1": "04f2ab41d0792514dd3775cce70afbc420aa3db6",
          "md5": "99bb15d630f819439212fe67dbeb6766"
        }
      ]
    }
  ]
}
