{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-migrator",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 17847,
          "sha512": "2f92d61744dadc77675766b3f3242d04eafdd02c765dd518e4eb96a3cb7bc7b3a6f6fccd5ea16840bcc20334f579410e6ee16ed71d77e5d1046f3723f5c1952f",
          "sha256": "dda51cd4ee1b2e035de154f05b6837734460af195de925f7e4cbee50d0c14989",
          "sha1": "e618b473e1371fcde06881f777278c586f9ef4ed",
          "md5": "3d91519d1d40d5686972e97802bc25ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 17847,
          "sha512": "2f92d61744dadc77675766b3f3242d04eafdd02c765dd518e4eb96a3cb7bc7b3a6f6fccd5ea16840bcc20334f579410e6ee16ed71d77e5d1046f3723f5c1952f",
          "sha256": "dda51cd4ee1b2e035de154f05b6837734460af195de925f7e4cbee50d0c14989",
          "sha1": "e618b473e1371fcde06881f777278c586f9ef4ed",
          "md5": "3d91519d1d40d5686972e97802bc25ae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 119787,
          "sha512": "7d7e60fa72838b5efc4fa29f7094d313d75ed7c2712a885a773098bc36dabec7606afe771456029b74c67338e33304f018463bc36234b07fc51f8af72f0ee6a5",
          "sha256": "db2c32b815ff01f0285ea6962c597c0455d28550851fb8c8eb14fa6b2d8aed7f",
          "sha1": "c9cd025b12005b5bd2b6a13c71034dfdd978e6ca",
          "md5": "fb589f2d923016dd98db1c63e991a068"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "size": 8454,
          "sha512": "644f333e6d8c9141ec1eaa25db96be2a549f9c611231d10c046ac8b3753d5b49f52e6d959589d8a285534f4918089d04160a033a4ef9ceacdf1f9675972eb2d4",
          "sha256": "95ebb8b928a8bb9c3de6ad9caaa103c1cea3b9e214141ad65068340f28c9ceba",
          "sha1": "a6ac0957b6ef525667fa97811e27b170f5c4bb8b",
          "md5": "1bde1274725eddf9317c43075d5465a0"
        }
      ]
    }
  ]
}
