{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-migrator",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 20476,
          "sha512": "9c04ff6e358d9d994e76ef351b99e70ed3e33db74148e749f2f8d797cbb5c2bad5db2fa8f1bb32077964dee50b5556255d4eddd539364b1b3f8d910c07a77b17",
          "sha256": "91abb7340f4bcb2689656b125b000ef7a9178e899a52066414e9db60351cdbe6",
          "sha1": "900590da707d0eb17310119afebfbcb4f940896d",
          "md5": "3abfabd157cce83c0aa71c06ce4b60e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 20476,
          "sha512": "9c04ff6e358d9d994e76ef351b99e70ed3e33db74148e749f2f8d797cbb5c2bad5db2fa8f1bb32077964dee50b5556255d4eddd539364b1b3f8d910c07a77b17",
          "sha256": "91abb7340f4bcb2689656b125b000ef7a9178e899a52066414e9db60351cdbe6",
          "sha1": "900590da707d0eb17310119afebfbcb4f940896d",
          "md5": "3abfabd157cce83c0aa71c06ce4b60e0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 131486,
          "sha512": "ccfb6d53baf445c06d69d293e885aafadcda3b2f0a5a395ad57d54f27743279a3185282e9df6b8cbf2761bccbf5341d61c8d7a017c1a3df67d18a95ab295358d",
          "sha256": "5d62cb6526b891d9b0066812b33bd46f4df4a7eee1c9aaee87689268b0383210",
          "sha1": "638b8f9ac3b10b14874ae6574aa1aa75aa7bc2b7",
          "md5": "2a9db35de41212001e87458d979c877a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "size": 7897,
          "sha512": "47f90251964642a166ff1a31b9e012c301081269dab8275b30fab92ba19b93e0439778e693ad7a279b8e7c0878034a429a5ac5bf8c17f849ed126db566b6e831",
          "sha256": "b7efc4eafb5fa6c9dfca8e3124c24938ed556d6afc95bd389c11208f941d2218",
          "sha1": "4a6b11ba5d2761f460d36fa122a9baffe8d3dbe0",
          "md5": "0329e4efcfcffb16cda771312e1765ea"
        }
      ]
    }
  ]
}
