{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-migrator",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 20631,
          "sha512": "704e6dfc0b729b1d5eae441b16b0f96a53f4217854506c2d55d0ed47d50687c218f0393187450ccf99acd1c4100c8eadea8c9d089167f526922799af73a84007",
          "sha256": "549a9aae3d6b9a609a92e61fa10fa8bf1f6512d1ff1c52fd3a1d3d1d2f8e55b4",
          "sha1": "88b3457992568bf0382e24a7ca931b07392c8984",
          "md5": "0b76ae208c29fc451e9961e7b0513b24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 20631,
          "sha512": "704e6dfc0b729b1d5eae441b16b0f96a53f4217854506c2d55d0ed47d50687c218f0393187450ccf99acd1c4100c8eadea8c9d089167f526922799af73a84007",
          "sha256": "549a9aae3d6b9a609a92e61fa10fa8bf1f6512d1ff1c52fd3a1d3d1d2f8e55b4",
          "sha1": "88b3457992568bf0382e24a7ca931b07392c8984",
          "md5": "0b76ae208c29fc451e9961e7b0513b24"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 123301,
          "sha512": "945d81dae38fa97352825cc096a37ad8280aa0ac555b03fd5a02d78c751861ccdefb7a863877ebf7dc23fd5270331faa388113419110b624f0e28cd9bc9facc2",
          "sha256": "ba81df490be50f9b46d7b5f382cac1bbd2de113ba21f0a9600e2a5b108850fbb",
          "sha1": "97b39bcd7cd5a8bc12fa3cfa45682cc9885507d9",
          "md5": "6f419623ea3794103b5dc7bc3d5a1ddc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "size": 8324,
          "sha512": "d00f7d3652dec8c6960a755a00718aa77cbfdf491d41415cad1076894588c159be5c653bf7249b104cac23730d1ef4e9a4c6ca433e202c3beb0c7c0ff972d322",
          "sha256": "0d722f485bb40dff9b72130406f7e5757d10bdbc7e5b61db6df7253f52774b57",
          "sha1": "0e3c05c4e05dc14b5083f2dc4cd0e51f278a7a10",
          "md5": "705b93c60c4c1a31859a3efe88fcd1a9"
        }
      ]
    }
  ]
}
