{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-migrator",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 20476,
          "sha512": "ff56feda4cf9caa5c52b600c88f54c6d577a1c194bc4ddd55bed844c3c5f2648b00caf2a15e348a986e502b644be983e1bcc4ac32721df20e47628e608880b5c",
          "sha256": "a939bba0a19e91cbaadeee3df692b8c9ff263d6a535f22114a0b22c1d32216bc",
          "sha1": "ec47531476fe1383faf462ce3a1ea0be3b086818",
          "md5": "e49c962cc0aa36507bc7f5a3ad3c19e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT.jar",
          "size": 20476,
          "sha512": "ff56feda4cf9caa5c52b600c88f54c6d577a1c194bc4ddd55bed844c3c5f2648b00caf2a15e348a986e502b644be983e1bcc4ac32721df20e47628e608880b5c",
          "sha256": "a939bba0a19e91cbaadeee3df692b8c9ff263d6a535f22114a0b22c1d32216bc",
          "sha1": "ec47531476fe1383faf462ce3a1ea0be3b086818",
          "md5": "e49c962cc0aa36507bc7f5a3ad3c19e9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 131487,
          "sha512": "73f1c6279206f80fba2960157ed733b5aa4b3bab7505eec1a1103d7a8dedf9d9e0da59c129128382dcf2f925d135dfa4bbeb04a2ab22bb97338ce7e31bd2165e",
          "sha256": "398786d468ff74d15bc85b9bb5ffd4910b44326e4536b5255a09f2243b0f3fd1",
          "sha1": "c95182a42f6d915b1cf8de143592092b194ba482",
          "md5": "33ec52eaed6cf229758a11d855d9b0ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-migrator-6.0.0-SNAPSHOT-sources.jar",
          "size": 7897,
          "sha512": "63b2a83a2ff2d2c9c5b23f2064f621accde0d91fe856f5623d3c763b861c8a1028d622b32f8f21fe1eca3a45c707ae0615fac486fe968e7cc97ffdb7532602e0",
          "sha256": "c2d3f0a39b1a07921aa6f0473c62053dfa35de4f608e1b55f10869299ae95b5d",
          "sha1": "466c0ee4ff81227edf1e2182ad995fed5e6e8721",
          "md5": "987163a9aaff72a1962c18a96849147d"
        }
      ]
    }
  ]
}
