{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 73238,
          "sha512": "160a0f3f64efd43fafed55da2cac4e5e0ddc31c0493d116ce11e361eaf1f7094ffd487c34f75b1e5aa6f553917fe7a86e52a6cfaf066c0be25e1d931962d82f3",
          "sha256": "bad00252cf87e36a5689b845e731d7da6621508173c0d8a243ef06fe9e84b95b",
          "sha1": "b2d20dfd7bb6e3244edb7843ffe6a7a678bada38",
          "md5": "5aaa4b12ae93efc330973ab76ed52eee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 73238,
          "sha512": "160a0f3f64efd43fafed55da2cac4e5e0ddc31c0493d116ce11e361eaf1f7094ffd487c34f75b1e5aa6f553917fe7a86e52a6cfaf066c0be25e1d931962d82f3",
          "sha256": "bad00252cf87e36a5689b845e731d7da6621508173c0d8a243ef06fe9e84b95b",
          "sha1": "b2d20dfd7bb6e3244edb7843ffe6a7a678bada38",
          "md5": "5aaa4b12ae93efc330973ab76ed52eee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 135735,
          "sha512": "57c2c01a78964704f3b5eba2a910e6ef541fc59eabb3bbaf2a868aacb54411039a715f399339e94c19698ac406f41aa7c1e413443fba111780d44745f17568eb",
          "sha256": "185fcbd98a0736dae0db4a4af2f5e29cc58179689adebd5114d744b4155cc71c",
          "sha1": "54dfc06cf7f191cda20e5a12f4462111937e09ad",
          "md5": "1855b7d3f8ce2c3a9fab26e927d91e49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 35361,
          "sha512": "c8213677b5805ec89adb5b30a64bb8697734fa2530d2e616676eba9d71393a04f813c3fa7392aed25b612cd946a17b85b632ff269ccae07a6084eac058080df5",
          "sha256": "3ccb0e473fc393f696ada80cd1d9960164838cbd54c4cc036e73e035e9c0f195",
          "sha1": "54709eb9c86cb751d5a7092ef71c91da9b0afcb3",
          "md5": "380f64f6d4dd753d4788d8676d4aeb37"
        }
      ]
    }
  ]
}
