{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 65313,
          "sha512": "e85fe39b2d44a5ffe646a7719b765da214c4e6dd1bb52adef2da69e68d0cb4aa13f7a595d775ac1e15af5845d8643f64d54d16cf852cfd52147e8c1332023372",
          "sha256": "3905ba257afdc962dcca7716e0560e6fa2e89994ae57bff5850efddb24eb90ae",
          "sha1": "9eb4dbf05f529af592c8a1604e53fa9000697806",
          "md5": "65604fbd011afe95c2b2ce8b0ddc399e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 65313,
          "sha512": "e85fe39b2d44a5ffe646a7719b765da214c4e6dd1bb52adef2da69e68d0cb4aa13f7a595d775ac1e15af5845d8643f64d54d16cf852cfd52147e8c1332023372",
          "sha256": "3905ba257afdc962dcca7716e0560e6fa2e89994ae57bff5850efddb24eb90ae",
          "sha1": "9eb4dbf05f529af592c8a1604e53fa9000697806",
          "md5": "65604fbd011afe95c2b2ce8b0ddc399e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 207034,
          "sha512": "76ffb814e3892d70c0ffc4ff1bb572d45944e89895b1e52087b29632bd4b27b7e1a279267598484451c1ef5ea56ed31f5b5254ba9a1ee791dce7dadfd5a4d8be",
          "sha256": "536b904c31755350142f3975253b649e2cd0e6ca2854ce7f95871f65f2fd4d4a",
          "sha1": "ede620fd1378e4213a4040adf896e0d89f2018a1",
          "md5": "68049b2997c697a5a585fd70eaab686f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31149,
          "sha512": "ad825264658db7d5011735a962fc69e9916a0bdaeec70c8ef87488d219fec099a492d3323cd46e9125fe3acc8573782edfbce3a558c61187a52155a9cee60f59",
          "sha256": "f35e1b4104f7fe1fd1839736d85684baf25891340fe9d42d82d22ec09fab3db8",
          "sha1": "d827b51bc6d75c6b9405216a8fd748ed9429c0f4",
          "md5": "91f011991d7fd85d81b3e0ae8d9b67ab"
        }
      ]
    }
  ]
}
