{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 73238,
          "sha512": "9795cdbcf6b3a8525fcac67252da3e29cac61a73b2cbf76dca761b7c3afe7823bbc853aa665f40410379cace506a5191537716e8e303a2394c58ba2597a626e9",
          "sha256": "a50a69a0e5af4b0f1b9bbf1c412d5e0cdd4d5ae30146444a036f383cf7d25f13",
          "sha1": "e68605c2a8b29c39256b5211742b29365afefa51",
          "md5": "67a5fe1d69892ebf5e3ca54ba4a70e74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 73238,
          "sha512": "9795cdbcf6b3a8525fcac67252da3e29cac61a73b2cbf76dca761b7c3afe7823bbc853aa665f40410379cace506a5191537716e8e303a2394c58ba2597a626e9",
          "sha256": "a50a69a0e5af4b0f1b9bbf1c412d5e0cdd4d5ae30146444a036f383cf7d25f13",
          "sha1": "e68605c2a8b29c39256b5211742b29365afefa51",
          "md5": "67a5fe1d69892ebf5e3ca54ba4a70e74"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 135735,
          "sha512": "ae879957c5743b26e09ca840010eea9d198e5d85dc2bbd5a8d904b7ccc310823db16ddd450b608461e7248ed7ca119e79f912dd982ceac59f4820a724330dbe9",
          "sha256": "0f7ec144f44d779e1499851fd6c6149fdb1f1a8804d57d86e4c03509d6543245",
          "sha1": "fdd8e1dc23d95ed842f1b2433af9b178e7d66069",
          "md5": "f8f5e36959f5fb980bc24cf67e1ae953"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 35361,
          "sha512": "52665b7e2af3c8e9c227cd056ae04e981b059f7219af39ce62b9d4b7af67ae6dc93b2dbbb3a921e4971b670cff9a3ed477c4aec9ca17f989e1b62013308f6f37",
          "sha256": "303e795f32d4cf06bd47b7d4ef08c886b92fdf225716a74f7d2b7ac31a6cf56b",
          "sha1": "29decfe2001decf14fe539ad9e99fe693370ecb3",
          "md5": "cef5631b62f636dda60d17d1efba01f6"
        }
      ]
    }
  ]
}
