{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 65313,
          "sha512": "49b94890fce19bbebcdce4f838a96716508e092ff99342e63c5817e5c58142e9771349c4fea7020aa176bd87681398823bd5f3c995d42da1d57c985614b9600b",
          "sha256": "1cd8ac9c7c988b19d3810ff0e378e6cda776fc2bbacc22e3f7b11260252009f4",
          "sha1": "432891c2d231c3e1da6ed0cda97cbf1292ad0101",
          "md5": "fff65430dff0f149ef7af4afcb3f23a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 65313,
          "sha512": "49b94890fce19bbebcdce4f838a96716508e092ff99342e63c5817e5c58142e9771349c4fea7020aa176bd87681398823bd5f3c995d42da1d57c985614b9600b",
          "sha256": "1cd8ac9c7c988b19d3810ff0e378e6cda776fc2bbacc22e3f7b11260252009f4",
          "sha1": "432891c2d231c3e1da6ed0cda97cbf1292ad0101",
          "md5": "fff65430dff0f149ef7af4afcb3f23a1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 207053,
          "sha512": "130987c3255493797f1a4b06f10da0374a53079426e6ef1e8d4e67af7c5af112c7448839d540f39fbb74fe9d1197b0e49c5e3e08bd3ad6e22cc3fa6ed699ff02",
          "sha256": "1dda710ee3005161d1ce502ccca061a054f67672b3b0c8e51d8135e9c3f416f7",
          "sha1": "c0ba925365e5a38f02b49c99cf386fbf20e7d060",
          "md5": "117c51cdef577c5fec2e0ccb69a8c755"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31149,
          "sha512": "e4a6c578e454657fe779fa6fef6e2a6125a3545dd581d1f80bafe7e3189fa2b8d563284d6e634fee636889615567f3af7b04c59d4b4b3d4bb92ff161763d2dd7",
          "sha256": "b561b3ca66a9a81f31ff49550bed11efe474e4e6dd450cb0a38c9134c8bb298e",
          "sha1": "e514a382ce5695ebdcd600f0dfe4a1cc68233655",
          "md5": "697eb61cf1e30d5f7c8b56d906182a06"
        }
      ]
    }
  ]
}
