{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 65313,
          "sha512": "fd39e58957ed6c22b44bb254cc16160c0b9d05822410a86b1b58446e8d7aba2bdbf40cfb09cc282c229a57d5c16ab038c3ed00ce52646bd30a9f7a6c6461a241",
          "sha256": "45a2430af43e5bf89cdbeb48e2493f0609103555be118f3b76b1688fee72c855",
          "sha1": "4cf7211fc102021a243baa01ac0eec2bff697c7a",
          "md5": "f4718c5700c708accaf25820bd9859d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 65313,
          "sha512": "fd39e58957ed6c22b44bb254cc16160c0b9d05822410a86b1b58446e8d7aba2bdbf40cfb09cc282c229a57d5c16ab038c3ed00ce52646bd30a9f7a6c6461a241",
          "sha256": "45a2430af43e5bf89cdbeb48e2493f0609103555be118f3b76b1688fee72c855",
          "sha1": "4cf7211fc102021a243baa01ac0eec2bff697c7a",
          "md5": "f4718c5700c708accaf25820bd9859d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 207053,
          "sha512": "475aa373fc9eba0f85ce42e66f54814d443dabf95c11cfec621d7176fa510e96c69eb86d55b03920b0e874047148cbd5fe00c762166d2cea7ccffc80343c1d61",
          "sha256": "789c0367b6a06aa06c1638a385ad775f96de229f5b487387449138ab77067836",
          "sha1": "3076434bc6fb8e1e9bcaa252a9e45ea2e8fe78e9",
          "md5": "3dc602d4b5711ae5d727ecd6ea6b8cae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31149,
          "sha512": "69938f50c1752ad19e683a95405215d4e72f57d73f08fb248a11e745c656f3aec006c9eb94a4454263341d648eb4cd85e5c452f0ead7eec9eb7d50d96955d69b",
          "sha256": "ff3fecb7be1f9e8e5bcf7396a764324be43315f618ba0db4746917c0b90e33e1",
          "sha1": "5de9a13db3dbc79c22b513b490757dc652882f7d",
          "md5": "ae51d2c951f4d93939ba41052398c009"
        }
      ]
    }
  ]
}
