{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 72065,
          "sha512": "4703d9c9416d738b4d95eb13be93b693421725cbfde638547cd2cbd13e9202f284174481e820cce5b4c26add1fe71116b0e753aa8b4f888f09a2100c0b0f9cc7",
          "sha256": "13b92ec7abd8cbbb275bac994b076897c44571fe83cbff0fa6c61f7f089c275e",
          "sha1": "3987b89605314b1bf85cdd79a1565afb654f87b1",
          "md5": "c8c5c7d256c2a10bf5eb9b2bb4b1b490"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 72065,
          "sha512": "4703d9c9416d738b4d95eb13be93b693421725cbfde638547cd2cbd13e9202f284174481e820cce5b4c26add1fe71116b0e753aa8b4f888f09a2100c0b0f9cc7",
          "sha256": "13b92ec7abd8cbbb275bac994b076897c44571fe83cbff0fa6c61f7f089c275e",
          "sha1": "3987b89605314b1bf85cdd79a1565afb654f87b1",
          "md5": "c8c5c7d256c2a10bf5eb9b2bb4b1b490"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 135534,
          "sha512": "46763d44339128b70421d46c50b8b1c8e6156d2f8165ccb3c0f11c79727354fd7130eb20c339ef7014671be218843fd52c76ddf3fa54816e6cc71662912b1d0b",
          "sha256": "38a583afb119faa98e33dde71cd96ca015744d13fdda4215934943f407ac6bb0",
          "sha1": "fa7737368bc71a7c9470447bb2edee84561e69de",
          "md5": "ddb175a39a210995d98bbce3c952de8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 35107,
          "sha512": "61c5cdddcf18b78975c648c0911476552a1cfbf3e0ddc819137acb0251d3d61f41410278be34b44d5236ede34c801d949c6599132fb4492cc1e677286efb61e9",
          "sha256": "0d3c54378621ca6c3e9cf71fed9a6b21164a1f47646f0650288ecf5d8d913e53",
          "sha1": "aed71d57a0e7b819336bd1cdc7d03d695c0120ee",
          "md5": "44d4aa89d4b98b3d0522e22be6aaecdd"
        }
      ]
    }
  ]
}
