{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 73238,
          "sha512": "2d1530138cbc8c37182e04367bdc6ede846cfe8ade52da55004b1f3bbdf46f432fef55294df32c9c6d5eb7f20b23f62f5b529ddfa0176d7671dfb16e2eea3a00",
          "sha256": "b1c9a25b1da4fac2aa4881f6d945dcfaa2b0f53c582ef668ab7566eaa43323a7",
          "sha1": "17324f9c682335f21408aaaffb955f8ab67a1387",
          "md5": "e4125dc3684c0984839a49f7281e7981"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 73238,
          "sha512": "2d1530138cbc8c37182e04367bdc6ede846cfe8ade52da55004b1f3bbdf46f432fef55294df32c9c6d5eb7f20b23f62f5b529ddfa0176d7671dfb16e2eea3a00",
          "sha256": "b1c9a25b1da4fac2aa4881f6d945dcfaa2b0f53c582ef668ab7566eaa43323a7",
          "sha1": "17324f9c682335f21408aaaffb955f8ab67a1387",
          "md5": "e4125dc3684c0984839a49f7281e7981"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 135735,
          "sha512": "e95bca3fc95210295b0883ea4a427e6e1d86c651f0baa9cd2192d2c800f689932d31088e15215fcb5374c234134349b801b1b1c66b78e735c47e0f5703997aad",
          "sha256": "e4432dc7d31c1ed76c380b85adece52d889aa3c469794946dce46f63279436dd",
          "sha1": "047c9590f75534b57f5633786e4a110121c9c336",
          "md5": "895366d4f126dfbde15a998de21e2179"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 35361,
          "sha512": "29260588ab51b296fcd1ac1c6ee998703cab7ce25f9f4b27cfebc75b484f1c7f2f45f48726ed29caa537c886353fb7acf007cf23ea8148532b2178f463e7668e",
          "sha256": "7b01eba1f522f7c11c6c1d30414c8ca465eb5c219c048c0f4334e5d56d2690c1",
          "sha1": "d66b114f4d62ffb66863d185d1668e331a2ff099",
          "md5": "f4e292a6b2eadabaa2a665e2ec1d8b5d"
        }
      ]
    }
  ]
}
