{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 65313,
          "sha512": "5df45005bb122d6da3070d9de76d06b138a909348e1c0378865ad8ae3cf344a591f5a583a916a102f7cc042fbb479833437dba91f0c2a76dcc431b90cb0d5b00",
          "sha256": "71b7d2a72f6bc8c2c67cd737a59016d4c6a7cda87f34e02023174b41446e97c4",
          "sha1": "610b6be22bec697428ce25e97569072e6313525b",
          "md5": "460692d76b2b3e0236860b592a061ce9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 65313,
          "sha512": "5df45005bb122d6da3070d9de76d06b138a909348e1c0378865ad8ae3cf344a591f5a583a916a102f7cc042fbb479833437dba91f0c2a76dcc431b90cb0d5b00",
          "sha256": "71b7d2a72f6bc8c2c67cd737a59016d4c6a7cda87f34e02023174b41446e97c4",
          "sha1": "610b6be22bec697428ce25e97569072e6313525b",
          "md5": "460692d76b2b3e0236860b592a061ce9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 207034,
          "sha512": "dfd645509ce3cc23114da2d2b07944d7522572b22660cd850f231bc28e1908a2343f32f6913b1d84295660cde22c74a877773bdb0fabd127883c124c0bada458",
          "sha256": "18c31d7e7c752b1a81f583c932ca0697d64f911d548edce822fa1081ad88af72",
          "sha1": "9447a517def595d7132f34a87ae6807710d27dbf",
          "md5": "1b08376c9109d01ad2c932687d2de243"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31149,
          "sha512": "8f581ae42687779138bcb46a60c3a4fbcb64ba887b81bb342c2141250d8670cf3f183966f97259cb79f9b8e7283c00e62f0bd5f06571e2174e148c178c8f47a3",
          "sha256": "7d0ac28eb63cee4d74b48ab4c2290e7f565552586d71d885f239444b61aebb99",
          "sha1": "46c533aa779bda23b447cb122dff93aa27caf5d7",
          "md5": "adc51eba4f29bea9ec6c30cc02513246"
        }
      ]
    }
  ]
}
