{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 65313,
          "sha512": "b3799bfeae8ab2ecc4e76e087f666d431a46c8b3150d0807f1701733f195f72462fc40abc9b937893e491025c9fee3eed173c7f2c2a5d041ce744d25ad4b1561",
          "sha256": "b03545139f6d176e8959d4da57bb880b7ac3c98c5d95de2283ebd59f37e244e6",
          "sha1": "df5ec0a64757abdf7f3a40102a0d79124caf48ae",
          "md5": "6d134d1d7aea6a4b14cef59c7078a29f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT.jar",
          "size": 65313,
          "sha512": "b3799bfeae8ab2ecc4e76e087f666d431a46c8b3150d0807f1701733f195f72462fc40abc9b937893e491025c9fee3eed173c7f2c2a5d041ce744d25ad4b1561",
          "sha256": "b03545139f6d176e8959d4da57bb880b7ac3c98c5d95de2283ebd59f37e244e6",
          "sha1": "df5ec0a64757abdf7f3a40102a0d79124caf48ae",
          "md5": "6d134d1d7aea6a4b14cef59c7078a29f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 207034,
          "sha512": "73a3421a4cd95cbf04415a5d1e871dac99fd8a8ae9d4fd947db3a981e67c51decb3ade477fccd7d489fcefb18fd1a44574603983128d54660b17ef805b7e1c5e",
          "sha256": "c4004277c191a242ef47eb691f19f930d474ae6ef0ff6fafffabdeb16ae87f5f",
          "sha1": "bc998cdd522c4a4a1b3e7530c35a4d1259572b43",
          "md5": "1025d90bac3cd4e4a2ac1c9b005b7b25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-craft-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31149,
          "sha512": "07655b8a717ee5800db292a66bc09e514cacb9bea6be13c395f133c13a879c7e045d10bfee0f3e50eb9ec6fd71845f15c57b07ef76e7a23659fef6769fdc5b7c",
          "sha256": "5636cf5fc86273dd86ed6dd602654c6161525854325ad66d1a804849937866a3",
          "sha1": "e517332d247ebc7cc447a2410f35f438d8c53721",
          "md5": "3dcdcbcdb05cdb14845979717ca76bdc"
        }
      ]
    }
  ]
}
