{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "5.0.0-rc.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.0.0-rc.5.jar",
          "url": "box-notifier-feature-5.0.0-rc.5.jar",
          "size": 7510,
          "sha512": "c1dc8a660e55210fa2ea5f9b8563252fe8e4e4c2782848d855c113e5517ef446a7ac8406fa37ab211d2aead11822bba963ada30d3b618d73567a6136f789373f",
          "sha256": "694c1c55ce6cfe393494449aba1a4749ce3a1879fa25de4050167e240b35278f",
          "sha1": "1b011347cefba8450b04e3520ec0c2a2718c7a8b",
          "md5": "ba7ee3c96331ca0cf47c317a465015b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.0.0-rc.5.jar",
          "url": "box-notifier-feature-5.0.0-rc.5.jar",
          "size": 7510,
          "sha512": "c1dc8a660e55210fa2ea5f9b8563252fe8e4e4c2782848d855c113e5517ef446a7ac8406fa37ab211d2aead11822bba963ada30d3b618d73567a6136f789373f",
          "sha256": "694c1c55ce6cfe393494449aba1a4749ce3a1879fa25de4050167e240b35278f",
          "sha1": "1b011347cefba8450b04e3520ec0c2a2718c7a8b",
          "md5": "ba7ee3c96331ca0cf47c317a465015b8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.0.0-rc.5-javadoc.jar",
          "url": "box-notifier-feature-5.0.0-rc.5-javadoc.jar",
          "size": 131645,
          "sha512": "014f2c73937e3df44925717754b3a4559c2beaa270e9b5c0d90928d0e4cc3f1b36c2f1bee4c270daebba256905b93cb3e3982a8a025a6601e1148a3dbffb59df",
          "sha256": "f6966e7e5837b0e4095d08e6e7a81c86267cabed615552e6589ef4208b821cf3",
          "sha1": "64b6f5afabadc54db597d15ae3eae77a7117a2b7",
          "md5": "ba757767967e0e6c5d45576173513940"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.0.0-rc.5-sources.jar",
          "url": "box-notifier-feature-5.0.0-rc.5-sources.jar",
          "size": 3874,
          "sha512": "0e9b0a154bc68a9f53a851e47376ee9e1adaa84c264a63ca2823d260bea704f9cdc3c1bd7ca83824a97786827f73ae0da8446de3b55935d844a7d157e1bbbe8d",
          "sha256": "ab0743c83519a98efaf60ada7ee3025ab0fa950291686c3a151c034f650739cd",
          "sha1": "0e6e5836b36e695f47f6770e413ee397f28936c0",
          "md5": "02fc2210d10e86239a2ff2470d98eb8c"
        }
      ]
    }
  ]
}
