{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "5.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-5.5.4.jar",
          "url": "box-storage-yaml-5.5.4.jar",
          "size": 17598,
          "sha512": "a6874681acbd5550362d3b4c51e5e9077e07647e2b969a4b0bfaf7278071f08d4c9face4172ee02507de5e8231df57d99fb52b41b5955f7012c17ef84df14764",
          "sha256": "13e03ed442154b8aa8e4da66e7e0d110b41aa8672c973609482899439745d0a8",
          "sha1": "aeb2da35d292073c958f35777602fef10cc056e0",
          "md5": "3b4cb1fbd41dea6b405d3aca43750737"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.5.4"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "5.5.4"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-5.5.4.jar",
          "url": "box-storage-yaml-5.5.4.jar",
          "size": 17598,
          "sha512": "a6874681acbd5550362d3b4c51e5e9077e07647e2b969a4b0bfaf7278071f08d4c9face4172ee02507de5e8231df57d99fb52b41b5955f7012c17ef84df14764",
          "sha256": "13e03ed442154b8aa8e4da66e7e0d110b41aa8672c973609482899439745d0a8",
          "sha1": "aeb2da35d292073c958f35777602fef10cc056e0",
          "md5": "3b4cb1fbd41dea6b405d3aca43750737"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-5.5.4-javadoc.jar",
          "url": "box-storage-yaml-5.5.4-javadoc.jar",
          "size": 88058,
          "sha512": "f096af0c6486364e5e8ade79eb0eae6badf6b47e2dc70b51313a7f60304ce46945a61397bf125e519d36263b44c2871ce44202a57a7a7c5c0dcb047929e5d5bd",
          "sha256": "8f5d94de83cc483154473ba0ca5f2e6d56221cd32b4e4bfc454d7ba5b3465c7b",
          "sha1": "482e0077a6095ae3eff63b197e91377f9a081a9f",
          "md5": "29d46bbd7c5389187a37e1d19a24a160"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-5.5.4-sources.jar",
          "url": "box-storage-yaml-5.5.4-sources.jar",
          "size": 7496,
          "sha512": "576ee5d99d961fa74cb80de0b5087ac9fac63abba9fd8431fd70aa0bd87a7073c3b64402e5dfa8f74ebafa2dfe0150e8f43d77ffaa29b58b22a7ddceb59868e4",
          "sha256": "f3e83ebf76e08e3d9175b2b31d01f575ac4d93befcdc981f5cec12e92990c505",
          "sha1": "3a1d8cd737bac361c7db1d47b48866edc317b2f8",
          "md5": "2dc0ad0edf7ab5a5fc6e15c3cb495a52"
        }
      ]
    }
  ]
}
