{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "5.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-5.5.1.jar",
          "url": "box-core-5.5.1.jar",
          "size": 59843,
          "sha512": "d722472f52cda40def79d384bbdec1cf96786b2759f56255bad53daf3e39977cb39b50a3fc3ec1b99203a107b8baab2bf5b355be95750925ebebf141c2b1143c",
          "sha256": "82ba9d657eb5d8a3c609e864417f56261636094445c96fb8f54fa4fc6b8a5e4d",
          "sha1": "b77951e1e608b610d4850cb60bdea0e3cf6aba1f",
          "md5": "f891cbc9671023c4d6a9a7228264a8b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.translationloader",
          "module": "translationloader",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-5.5.1.jar",
          "url": "box-core-5.5.1.jar",
          "size": 59843,
          "sha512": "d722472f52cda40def79d384bbdec1cf96786b2759f56255bad53daf3e39977cb39b50a3fc3ec1b99203a107b8baab2bf5b355be95750925ebebf141c2b1143c",
          "sha256": "82ba9d657eb5d8a3c609e864417f56261636094445c96fb8f54fa4fc6b8a5e4d",
          "sha1": "b77951e1e608b610d4850cb60bdea0e3cf6aba1f",
          "md5": "f891cbc9671023c4d6a9a7228264a8b6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-5.5.1-javadoc.jar",
          "url": "box-core-5.5.1-javadoc.jar",
          "size": 192652,
          "sha512": "3672f9eff163cd8cdfa96483647188f98f2052ed9c045d2621400ce7f64450f8813f7d4409f2e15d5f91e2d7cdd44de09c409f80641a0884eb4c831c1ab64e46",
          "sha256": "e09a740b1f23e2a4c479f82b3862fcc8c7b093eb4205db1ae2879e6c7914e7d8",
          "sha1": "32061269fd4a39e6f8d64a05222a678e34ab45a0",
          "md5": "c3e1a999529b977ba465445554f6312a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-5.5.1-sources.jar",
          "url": "box-core-5.5.1-sources.jar",
          "size": 26728,
          "sha512": "141067905e6f764c8281dd9a547f6eb93f06b1a5cf1641bbee3c78a2fc51bcda072beb8fde03b950dfcbe78c066c99b34c95fd1b7a757684df42be768b17dacf",
          "sha256": "46d7be7dc697141e69ad441a26a170f161f86ae0d01e600f472f9b84970652a8",
          "sha1": "1e74ab8010f2d4ea318829448a0c61ad65eb6918",
          "md5": "389c66fa934ab43a31e8bdd52ec086ad"
        }
      ]
    }
  ]
}
