{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "5.0.0-rc.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "box-category-feature-5.0.0-rc.4.jar",
          "url": "box-category-feature-5.0.0-rc.4.jar",
          "size": 52732,
          "sha512": "55103d882f46503cfe96398f42b42a3676e4310c167586d1d80078edca1a21d7ada1e9ce964948f06d67184a9fb2d58d01c0dac1c9df65cdead78aab4565276b",
          "sha256": "050dbbe091c7e19bbf5dcb107d97e06f45d63a6f58481408dc1bcfe408a022d6",
          "sha1": "66db83cf94af1e92e9d8693917326c4cbacde78f",
          "md5": "b8a61ac9e292b22b0790d96ff30c5564"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-5.0.0-rc.4.jar",
          "url": "box-category-feature-5.0.0-rc.4.jar",
          "size": 52732,
          "sha512": "55103d882f46503cfe96398f42b42a3676e4310c167586d1d80078edca1a21d7ada1e9ce964948f06d67184a9fb2d58d01c0dac1c9df65cdead78aab4565276b",
          "sha256": "050dbbe091c7e19bbf5dcb107d97e06f45d63a6f58481408dc1bcfe408a022d6",
          "sha1": "66db83cf94af1e92e9d8693917326c4cbacde78f",
          "md5": "b8a61ac9e292b22b0790d96ff30c5564"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.0.0-rc.4-javadoc.jar",
          "url": "box-category-feature-5.0.0-rc.4-javadoc.jar",
          "size": 165509,
          "sha512": "7337afca436c047fbfed98a18a2492ac9dcfeef05ad9f3aee235f6b3a0b94838cdca0cb8f766d82bf8dd4769645396d3a7212537b23f824c1eb279082ac0f000",
          "sha256": "fb199fcd01eae32cd9974425576093abb86ecae982cefa80669548d85485675d",
          "sha1": "685749ad17b1ce0e7cd8dcac59e7576530cf287a",
          "md5": "46651c58e1f4fb52c11123daa7335704"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.0.0-rc.4-sources.jar",
          "url": "box-category-feature-5.0.0-rc.4-sources.jar",
          "size": 35176,
          "sha512": "676512fbaf6123888aaf0f7321d66ae26f89b4f320cf650d4a84d26c734a60de1133d585969646cb55d2b69b2827b958e7a3333df610d8cd0a9fcf0e684011fc",
          "sha256": "ce2b1d10ccc7cf4edf6e01531d3f66726b22919e4512e8f428ba6a5c9b977833",
          "sha1": "661b94e0825f287cbb2bb3a957bc60eeb0964e6f",
          "md5": "84f158c246592aa4671668c545951742"
        }
      ]
    }
  ]
}
