{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "5.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.5.1.jar",
          "url": "box-storage-api-5.5.1.jar",
          "size": 32779,
          "sha512": "05d396c884f4b5f288ce864e1fc392062ba1ebf32576bfde3ceb1241111a1b287bd2f94a55de4bb70b049c2fb0a80a34c4cef6e8033e7d094cdb1993cd344e78",
          "sha256": "80a2eebc8e6fe2b7f6041d78fe6906021f257e0082b3fdef3e8e2b0dccacf874",
          "sha1": "72f00e2f0501b5d3163b18623ce8042c000c021d",
          "md5": "2ebe991eee9e3189cf0a8d8f245d0195"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.5.1.jar",
          "url": "box-storage-api-5.5.1.jar",
          "size": 32779,
          "sha512": "05d396c884f4b5f288ce864e1fc392062ba1ebf32576bfde3ceb1241111a1b287bd2f94a55de4bb70b049c2fb0a80a34c4cef6e8033e7d094cdb1993cd344e78",
          "sha256": "80a2eebc8e6fe2b7f6041d78fe6906021f257e0082b3fdef3e8e2b0dccacf874",
          "sha1": "72f00e2f0501b5d3163b18623ce8042c000c021d",
          "md5": "2ebe991eee9e3189cf0a8d8f245d0195"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.5.1-javadoc.jar",
          "url": "box-storage-api-5.5.1-javadoc.jar",
          "size": 175930,
          "sha512": "96d81ced65a1c62507d1d56f2e6195cc4a7dd3de21d7c68ab8c1950cab81eb9f95f46779d1eebee5f19d450a9f3b1ee97dd40ffed03fadd0be269672f03197db",
          "sha256": "dbf53fb04bf54a0e06c13ff7831acd21e7ad21ca5989617967c6acdfc9242df1",
          "sha1": "643727791c21975c9fb677631089f5500ee95676",
          "md5": "988129aa57fd8e80958851846f914575"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.5.1-sources.jar",
          "url": "box-storage-api-5.5.1-sources.jar",
          "size": 16903,
          "sha512": "c88c72f5192aeb8d91c8a0f33d58481a06bd2247e14e6db4d9b6136f1893158aa1e177e0dfdd50de06a88e1cbc402d8d2a11f27aba6ba375bf540753fa206bd9",
          "sha256": "b25163b4c069a74b655937485ad71c9d49ec13bf3f712de6a768a408d2bce19e",
          "sha1": "e00e83f8b5b5b5f48713266cb91bacc3423a9a6b",
          "md5": "d3b604c2c4715c1648004cdf1dbefe73"
        }
      ]
    }
  ]
}
