{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "68524e59f1d0ef0a21a754ea1518f6ecbb73e3227f935edc33742d21d18d3359da24dc4444c47f31f2cf88c5939e56daee46eab42104b6ec32f5e4ba3e96e65b",
          "sha256": "3be3ba20fbd6ea4a8ac63859bb83a7a519436668dbdeb30f6e09930cd50c577b",
          "sha1": "2e68311b135fb30922ac9845634f392aefbe91ac",
          "md5": "6c51b577a6a4b248d17a5b1b0af29bfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "68524e59f1d0ef0a21a754ea1518f6ecbb73e3227f935edc33742d21d18d3359da24dc4444c47f31f2cf88c5939e56daee46eab42104b6ec32f5e4ba3e96e65b",
          "sha256": "3be3ba20fbd6ea4a8ac63859bb83a7a519436668dbdeb30f6e09930cd50c577b",
          "sha1": "2e68311b135fb30922ac9845634f392aefbe91ac",
          "md5": "6c51b577a6a4b248d17a5b1b0af29bfe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 82351,
          "sha512": "e694b248ee8ecb932c0c48adb19a7b62814ac90166a8e5ec25da0b98a410aa6c0b47acd70817025e3b607f682003ad34e98071055bd27cbd6ac71e399cf48d21",
          "sha256": "f17a761064c3d5991cb66071bef6910197c4447be7d004397ed89966cc3462c5",
          "sha1": "75653e047362965112c5fff2bb8fa92dd7a4b664",
          "md5": "228a3cf9b474dd839852fd7b8f6ac173"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 12687,
          "sha512": "071f44eb900908415d07fe8ce38c4ba9757874eefc00ef2db381bb2a4f0413c6e2e1175323cb404ab2a42c5d6a6f28380bf711085d2d05eaf77f64e73902a858",
          "sha256": "90ebf1ffa1c60783be19aee40df7e791cd1b2c568a6363c963d9d39b79008449",
          "sha1": "1814716147af18bcd9df120e1949b56dc5ff6b83",
          "md5": "ef46d8b245d69a1bec2f1479c1d9af40"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 905682,
          "sha512": "b7086bcad912cf155f41e30858afa3e93bdc54111b2d3528b71aa9b34809be99670ee14ba16b2eeca8f072881135c013a3be6702599518002954215baa0daae8",
          "sha256": "5e265751b2732ee8740ad2e80903f9ebe13c1e7c5c8f172a8b1359a36018d71c",
          "sha1": "eef34b81ed6b87b780aaa99e38bd92c04138edba",
          "md5": "d956621ecc1ca0049240b32179c345a1"
        }
      ]
    }
  ]
}
