{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "0e35b863856c273eaa063179b46ecba2a300bea396745d12c5265f37a5c53732a6584b710e0a0c2197e5afbccfa27ca85119f0cd29e7621603b5b7ae1959f016",
          "sha256": "e276a8e007537b682b4911e75092c5c17e20a6e9b604ae08f4c80f7d102783b0",
          "sha1": "c792496dfbec29ba039420f79f0b44d477a58537",
          "md5": "500a33f1f79e7063c9df8c171faa16a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "0e35b863856c273eaa063179b46ecba2a300bea396745d12c5265f37a5c53732a6584b710e0a0c2197e5afbccfa27ca85119f0cd29e7621603b5b7ae1959f016",
          "sha256": "e276a8e007537b682b4911e75092c5c17e20a6e9b604ae08f4c80f7d102783b0",
          "sha1": "c792496dfbec29ba039420f79f0b44d477a58537",
          "md5": "500a33f1f79e7063c9df8c171faa16a8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 82351,
          "sha512": "b4949a37c8b3583e5ffde8ce80b65eddcbb85196c7be2c7ddad793eea70537bb627e01f6cdd663c74499823b4f43e35b0f3f77dfd044e6fd812c9908adb7ec35",
          "sha256": "27785cd3fd355bb92629b667327761577c3f94d922eec467ecd14532f766c113",
          "sha1": "407b6a38762181c09f39cb19359ef017cfd2d51e",
          "md5": "b6d2ebcf33479108425f70f06964fec1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 12687,
          "sha512": "84f6fdf6a2d68e3963fc013e85ab66b62e9addd47edf802680df575f53c4c0c9cf8237e65efcdc789174c0d6581f23c1013767319d3e85c38bae58925e7235a7",
          "sha256": "016e3e5c14d62c55eae936bf8879d9ff6f03a6f95d468a4df393c1926e9b9822",
          "sha1": "7b9762f162ef7571add20f9b38b2965fe5cb29d7",
          "md5": "b644f02344fb54b9f42f17374fc54ca3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 941232,
          "sha512": "17f11dd41975453086f6fa7324473b4e46a9e5d162aa9185ac82e64e9e2f879a018c8b830467343c9daa87512bef6f01f0843f46b4a898db069353666a72ac99",
          "sha256": "aad54b46a0b245dba2f73c1abd25310c2eb6a52c0ddea7bcb050f36a46bd9a67",
          "sha1": "37bc8b31adfe953e28382e01357404404784e054",
          "md5": "bf2e6400a68ad7ed091bb8a8c4af8b7d"
        }
      ]
    }
  ]
}
