{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "c9ec28e2b81cd46fe2a3dc14732bdc515c508b3dc5ffc149f2cf34b9f269384a784aa272ea95ed6754e9d733074acbdca81137dd8b562b593a5f75cebf30abd7",
          "sha256": "738144f393ac8aa8a6b993c4d962dd9ae3cba7b37975cbe8917ddfa7caedd137",
          "sha1": "5a2ae06f10a23db7178ea89eb4aee2eb081406d4",
          "md5": "cf8dc623a72aac455b53cc1f2126cd06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "c9ec28e2b81cd46fe2a3dc14732bdc515c508b3dc5ffc149f2cf34b9f269384a784aa272ea95ed6754e9d733074acbdca81137dd8b562b593a5f75cebf30abd7",
          "sha256": "738144f393ac8aa8a6b993c4d962dd9ae3cba7b37975cbe8917ddfa7caedd137",
          "sha1": "5a2ae06f10a23db7178ea89eb4aee2eb081406d4",
          "md5": "cf8dc623a72aac455b53cc1f2126cd06"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 82351,
          "sha512": "abb1d5b4ce8ba2ac1ce0c10194bdb14170c96199328356d087da6380ba011248f425dc96e1956017028c8692bb8ee036d4128d77088066e2122b1e9cd46f06cc",
          "sha256": "00bafae2b06b7b2cb67dcfb95d6622b08c29a27bf733b20984abcf9f61f215bc",
          "sha1": "9513d1a40e7ff4a5923fa332d0e4766a201b2a50",
          "md5": "e6983e1e44fafdc5ba3f0ac4c98dcd08"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 12687,
          "sha512": "97b420aedd391258a6479b6576c5ab5bea8d075719973ff45a6fbaedf3e58c44c592a3534ee972170e6188d9e67571d200245989c264d5d2445f82b1c58a74fc",
          "sha256": "52903e4f3d9ee0d85a73cc84d120bb227447fd768eb3f0e1334746e41ea2e461",
          "sha1": "88ddb81b22f2d54bdd0dad0c3defeb2eda155413",
          "md5": "0a9de01619e27a81fb3badc75b7582f8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 910649,
          "sha512": "fe295871b157d48a9ea07caf972afa11fc46a6f62d956faec86fdc056ff12e9efd7ba2cd4383b87a80106d03b69acb4d5808d9e13948feb7616227d8bcb45f9d",
          "sha256": "1e5ac25d8adf01dff22a68c34e0587b5a389d8d12b98ebad8255236dc7a75fe3",
          "sha1": "32a8beee61b0cc7fc23aa3d99ee4ae25474b34d0",
          "md5": "bdba64c0682e4bfe9ee8c867e0e8cd16"
        }
      ]
    }
  ]
}
