{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 28578,
          "sha512": "1ab7b184e3c6494afa1f76a28a0fcce3f4e2adb45ef9b665376eb13724906619ded4290c2fd43e9512a20a94ad4bebce20b1584688dc9579e6928649f2154af7",
          "sha256": "e24d8df202be9bac13914484c583227c29f8948f2bacf837e598f0d563f64e48",
          "sha1": "2c5465e8a4108a1313ee84457ff1eb0a41467a87",
          "md5": "0df98fb9f1a0a9eacc8ecae6e8fa6af0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-paper-1_21",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 28578,
          "sha512": "1ab7b184e3c6494afa1f76a28a0fcce3f4e2adb45ef9b665376eb13724906619ded4290c2fd43e9512a20a94ad4bebce20b1584688dc9579e6928649f2154af7",
          "sha256": "e24d8df202be9bac13914484c583227c29f8948f2bacf837e598f0d563f64e48",
          "sha1": "2c5465e8a4108a1313ee84457ff1eb0a41467a87",
          "md5": "0df98fb9f1a0a9eacc8ecae6e8fa6af0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 138312,
          "sha512": "a07e801b0d1d8bab22982c45fd218a7d6cfb1df5acdb19d54a450d9e0644caeeb1001f3d89bcebd8d5b3b83e7b50d3c11caf7795a0549225a506ad445ee6d01f",
          "sha256": "8416ca881f0a00c484a577d7c85714911b0ad959435e0dd4183f9e94f0c648e8",
          "sha1": "d62f58af491a34908c36c5974cd55a79ed6a17b4",
          "md5": "835c8578b09729ad9a9ad4cbe279f602"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 14424,
          "sha512": "8eb575f09a96d98710d66989e4a0a05e04aad0cbcd5180b9fa74f70697e9e21784bcc01568d11598e994636bb2ebbdcf3a5fd1896fb4dce90aa921863ea73aba",
          "sha256": "dc3306de21aa2c155e20af0598b6e717782880336aebcbd4de795aa5636b06f3",
          "sha1": "1a0cbedf1e7d60e117a14f62a71fdb1cf62367cc",
          "md5": "9d0af9c2dd642d051caeb6a4d72bfe66"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 1212483,
          "sha512": "a11c620afd613403a5a7015f9b09959e30481d4f3949675e2a4fb2b34e7045f9179d0c34b0a5261615cfa8059c3255d993cc3c4638e2712cb528d00c69d3bb73",
          "sha256": "800f77f19776951da9772bc606e5c58dc87031948f6d46f7ebbb3c64bcfaa45e",
          "sha1": "8b1042561c09e3d52a993a25ab2bbe8667d4c4bd",
          "md5": "95b24702394a444a5e80b40e183a464b"
        }
      ]
    }
  ]
}
