{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "747969a3b1a6cf6faa561be78e07fbffe447c43da936b75a553b1534eaa28f9ee47e34f395c2e448e5cbe515ab9c14f1ef70db1cc80825af58e8e4aeaed6e92e",
          "sha256": "861d6b7a199c0f4119c92708eb6fd702f2c0fd82de1656774d2b69dd2dcabbfb",
          "sha1": "78100ca8f03bb5d64d0b1782a2202ea07cf41ae3",
          "md5": "97a0b994a9d8223d597f0b5a2d96896b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "747969a3b1a6cf6faa561be78e07fbffe447c43da936b75a553b1534eaa28f9ee47e34f395c2e448e5cbe515ab9c14f1ef70db1cc80825af58e8e4aeaed6e92e",
          "sha256": "861d6b7a199c0f4119c92708eb6fd702f2c0fd82de1656774d2b69dd2dcabbfb",
          "sha1": "78100ca8f03bb5d64d0b1782a2202ea07cf41ae3",
          "md5": "97a0b994a9d8223d597f0b5a2d96896b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 82351,
          "sha512": "fe5245d09237210039f4b50ecd4e15137dea1d59d38696ff2307685f61c7bef9d308bb08bac4a7e401ea190a6b797d5bf169f18aae6c6a625ec396fbd2b3447f",
          "sha256": "044481f60bf515fe3f7200ad5e67d4209c913b58921732fea26b934a85fe1ab9",
          "sha1": "06c3cbf7ee25bf8b3e3ce6f99e8d429b1a62a087",
          "md5": "59b7b4954267cedb750e7289f62497b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 12687,
          "sha512": "d3b0cf18616500faec6cf70c61a66f84e3037981cf484ff4a2e7be2613c144cad7f4a547229a9c0139b85646b1410ed7b7fa0467bbbd8a6b82426c7716069cbb",
          "sha256": "94ed4da9c3120a408de14f3b3a9d8246895edcf229deb9a0ebc2a1a39e099540",
          "sha1": "3a7e35ee0e40df687c3efef6b4c155736a9cfe2e",
          "md5": "42c38aed79804a579773b0f5fcab1a26"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 946979,
          "sha512": "20cc098df6190e2ea34c3d485f77ade2780ac9b2123651bb87daedb1ec67a19b2502d63b606e00e8de5cde0ee4e925b49a285e16f0a635c3c4ffc3e8895ef218",
          "sha256": "fdbcec1eeca477073136507197478c92187c5d63a2ddde7aefc971bd35868167",
          "sha1": "5e5c2c14ce2943086a7071653dbcc4ae7b0ce1db",
          "md5": "de508ab80cd249acffbb8f9227f1d134"
        }
      ]
    }
  ]
}
