{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 33712,
          "sha512": "b0a60f97df36befbc9262907228404fd59f67cce9dc9bd6f5a481ff40724956de64ef1c02bb78352ac114d682c1cffe4a36289ed85562ea393d14d3b75a0c2b6",
          "sha256": "ab45b474a282a346da42b59815abca2482043965cca6f5c5c8e494d542f62ecb",
          "sha1": "3a3045f5eccd093f7e5f185cb878a30a5c97e0ff",
          "md5": "11106f6f7a79371aa850c168a27892e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-paper-1_21",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.translationloader",
          "module": "translationloader",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 33712,
          "sha512": "b0a60f97df36befbc9262907228404fd59f67cce9dc9bd6f5a481ff40724956de64ef1c02bb78352ac114d682c1cffe4a36289ed85562ea393d14d3b75a0c2b6",
          "sha256": "ab45b474a282a346da42b59815abca2482043965cca6f5c5c8e494d542f62ecb",
          "sha1": "3a3045f5eccd093f7e5f185cb878a30a5c97e0ff",
          "md5": "11106f6f7a79371aa850c168a27892e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 126686,
          "sha512": "258596ee8fe59da2a99e5ce16c64eb63a364e21ae69462a9279883116cc08ab1194dfe6279f108e0ac9952ef7163708a0b555ef85f913ac08b9a3a55473378cb",
          "sha256": "39ddd6f2cbc70330fa0e5b890e9e7be5618dc81336330406ef9da7901e3296d8",
          "sha1": "b7c1137ac3148b6340b31ff18ae201d2d506fc33",
          "md5": "1b1985a22a6eaa23c201cb3df9f9e579"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 18664,
          "sha512": "bb5d3c7df1fc0d9b8ad9d823eb4c9bad1738f3cecd533aa9af001111a920dae11f15efd8f6eb7b792f38da932ef6b666e7f43da70a8343b6172674417e7c3676",
          "sha256": "8fb96c97cb87f15e1777bcd8563b61509f9fcebd1c65a4cfec8fc5b702f0079f",
          "sha1": "8a27597c6e3fecd7e6a777021128483dd01fad8f",
          "md5": "5523f23a01ca3d646c413c8728a4ec73"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 974214,
          "sha512": "0b0bb9ac2d4ad7372372b750ead866f15c37e3998713fe8767521453fd7f59a59ad2daf00b00e9dcb1ad5f9e304be597c487bb018f7885d7f0134268cc966abb",
          "sha256": "811d1070b7886e271b0dd538e92ba7ca0236854047bd36470c3e1034fc2b8ef5",
          "sha1": "4cd1bb2ab573dad9b367591a55a042baa3e1796b",
          "md5": "c361c674d6dd9ccc7fff8da0f5412714"
        }
      ]
    }
  ]
}
