{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 28555,
          "sha512": "d656c84babfe95e0460b42e42029968f12c25ab518cef92d24b58f667afd26dad135c61458ebc16c903c94973e1556aef12e55b9ceeba5402b1ebd82db2c2ee9",
          "sha256": "61ce4fd534c4537c464b20d5ef7c13b8e3e9b67df8e1393f52644701dc921781",
          "sha1": "2a9090f6c32a07ebcd172e83938aa6c5bc60a416",
          "md5": "84bf173f2864d2623c252adffffff808"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-paper-1_21",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 28555,
          "sha512": "d656c84babfe95e0460b42e42029968f12c25ab518cef92d24b58f667afd26dad135c61458ebc16c903c94973e1556aef12e55b9ceeba5402b1ebd82db2c2ee9",
          "sha256": "61ce4fd534c4537c464b20d5ef7c13b8e3e9b67df8e1393f52644701dc921781",
          "sha1": "2a9090f6c32a07ebcd172e83938aa6c5bc60a416",
          "md5": "84bf173f2864d2623c252adffffff808"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 125969,
          "sha512": "2e9ce0b6421fe35332852fdb7edc89f2afdf7e31c8ece066fad2c25965ab9e20e523c2f9ed78edf61fd020b5f7d3fdc10088bc5b993809f574089fb58c6a4469",
          "sha256": "7ea557fa36e59520bf7fe168aa44578a889f5092a2718f30d4798c4fef232264",
          "sha1": "a26bb8e1bef59483f684517eda46b40da4096cad",
          "md5": "889d261edfd3e9c4fbfeeb56a91f29d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 14424,
          "sha512": "68fb9fe7c2df760f2af0338c8c070489f59058b3927f16f83eb21d82952b1973a79a1a6e4c656c9cb08be3dc8034bb98b860af18fc062f2caa4550f7ea79be32",
          "sha256": "f9ee2aea2a9ba343fe272533624a72ecceb7eb8044f3cbec20e7b31edd9ad9f5",
          "sha1": "a4a1993dc20a6f9abb73634759d691fec6b71c9c",
          "md5": "3d2046fcc6064a8c76d46d1f98cb9fc9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 1210243,
          "sha512": "fa27663d87abaf174a97ff403129d377df906c37ad17c6471b5bc18cccd40809b19ef4a518280966ec518346206446ab423822dbbf938146c818f547b65e0780",
          "sha256": "4b31acf166212d2eb15f3857d924404dcfb3a82272f49a75096c7b444d6b4390",
          "sha1": "aff182ad6fbe2c299a3c89e0e48bf3953285fa6a",
          "md5": "7218ef615542053a932868bbd7b8c4b5"
        }
      ]
    }
  ]
}
