{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "6ee61a90f11c4b8cbd2ad7905f0af1c5607e34156176d660c1116cfb82672a0d44ad5bb413993f3fc52d5972d9d09627056bb3f758f1ab8541cd14050027b90c",
          "sha256": "bff656e7f29e69afe9246de15ddbe5f6464a5fb893191e02caed3306448acb1c",
          "sha1": "acd989dece5cbd7e4f363b320bba2d88385007b1",
          "md5": "edea4fd293faa252aa7cf561300ddb2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "6ee61a90f11c4b8cbd2ad7905f0af1c5607e34156176d660c1116cfb82672a0d44ad5bb413993f3fc52d5972d9d09627056bb3f758f1ab8541cd14050027b90c",
          "sha256": "bff656e7f29e69afe9246de15ddbe5f6464a5fb893191e02caed3306448acb1c",
          "sha1": "acd989dece5cbd7e4f363b320bba2d88385007b1",
          "md5": "edea4fd293faa252aa7cf561300ddb2f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 82352,
          "sha512": "44bb373b71e15fadac76da366fdedf5631bdf044f1b9dba356f5cd6c05432d44b7d07a0a7fffa3946fb53782fbaa849a421a5637801aa01a84d46c4064e91b3b",
          "sha256": "8cc5171772a1ab448ebbe3d1dc3e4e6c20507200c0cb68fe095b1e629d212758",
          "sha1": "093c55b3f49dc2d7cf4f240e0894b620cdad2f5c",
          "md5": "f2e60072fba97862724fc02a5dab25a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 12687,
          "sha512": "2d9f08c8c06c6bd11307886599781bdea3e6c61f31fae1383543b17f42068f677b17563b2b7d8e2cbad4bc2172f175fb86c03f1ef39b37782cdac25b3bde53fe",
          "sha256": "f1495150ef1d2a911479ea4728b56063ab5de655e6cf6445c862f31300a96a5e",
          "sha1": "62f722f27c2b8935f307dbb712d2a623aad21df6",
          "md5": "7d44c9a09a1b41b9e0e984419639dfa9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 940678,
          "sha512": "d8b35f1d5856ce254135930a09954ad7ca8c43a972d9accb7e3ae9bb86b678a3fda28a8c606e761b3f68fcaf661c3be740c7e91176a1fe1112ccaf4cacee4cb0",
          "sha256": "12333f9f30204fdbc40aeac2d330e33c5dfa77dc442cd1a66cd701d080b3fde6",
          "sha1": "c3b2fe651ec1847c0231c4055e1dbb851637938b",
          "md5": "4c1c30143fba1d6ba9750682508f2e48"
        }
      ]
    }
  ]
}
