{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 28578,
          "sha512": "3e8eeacc7d9f50a45a71a290617a3a3699c71c4ddcd0cf862873067ccb5693c7f5bbf6df8f7e23df30c4f2cf8b06d4fc14e1eb291fec0dc6686db503cdb903aa",
          "sha256": "dedeeaf039b8a222bf98f00aaa44cc10b5909bd803de2495255b9bacf8629c5a",
          "sha1": "b7132835bb168d38876f07e11375e88f1c003dca",
          "md5": "7f379109849ab15df120f0c5ee8d1f7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-paper-1_21",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 28578,
          "sha512": "3e8eeacc7d9f50a45a71a290617a3a3699c71c4ddcd0cf862873067ccb5693c7f5bbf6df8f7e23df30c4f2cf8b06d4fc14e1eb291fec0dc6686db503cdb903aa",
          "sha256": "dedeeaf039b8a222bf98f00aaa44cc10b5909bd803de2495255b9bacf8629c5a",
          "sha1": "b7132835bb168d38876f07e11375e88f1c003dca",
          "md5": "7f379109849ab15df120f0c5ee8d1f7e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 138312,
          "sha512": "bbfb4ddf3d4d2b268698aeae07c06525bc3cd4ba65f95c477bff552f666c0534a9b0d1f1cbb3bc593888c1414a7c94dd927b48c9218bc80a549e6a16e28b33c4",
          "sha256": "c2d3d49065e8bb4981e28bf8df81714e9783099a3ab5e3522cf6565a934fa47f",
          "sha1": "d6667e81880ed1678b4889f60a1321e032341165",
          "md5": "f3cfa6d0ce15c59daf80f7c261398355"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 14424,
          "sha512": "65fd75638083a589a6ff5dcdf521f85b142e4ec78679910a75156741906b00c47260f1daa6188405746a060702220916357cb0aa35c0943b4f96fa0696f587db",
          "sha256": "8e4c5479dfd58813413562879f5e1cc7c08311c0b3944e01a3c4a40cb1cd1e93",
          "sha1": "673465a792bb7a06da94eb45e2a42081b5b72f81",
          "md5": "1e5a3f18ac533c2a28eae21093e69a4b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 1212483,
          "sha512": "2f6eda2454bc2a55ae76efedc7cb6fd11115785cfadb9f304224a0186e374387de6a717329084ea023c69f679eb0e36594aecd7c1ccbe001d1a89e808ae04c57",
          "sha256": "f270c6603b7e085566be5fd64041afd394f8902488e3243ee0bbf056f5da3d03",
          "sha1": "81744d1af1486eb628b6ba620abd23cde3435229",
          "md5": "a248a91e31a8e1c1e34f39f3e0eb6ace"
        }
      ]
    }
  ]
}
