{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "bce6c3202463bc2eecefb5a6855b2530fe3b6f54564907bb564955fde0a6e350ab0269b22aee3d0e5413f1307472cc2661f9df8f383965a6e17b0d0551f99f62",
          "sha256": "c8712c4da33d2d347463f3a3022354ceb83fa895e56be60659ef49c4e40f9500",
          "sha1": "dd3bea94c72d5bbd92febfcbcad18c883e08a216",
          "md5": "c8bfd1b8cb2c57d7865d0c6e898ae179"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "bce6c3202463bc2eecefb5a6855b2530fe3b6f54564907bb564955fde0a6e350ab0269b22aee3d0e5413f1307472cc2661f9df8f383965a6e17b0d0551f99f62",
          "sha256": "c8712c4da33d2d347463f3a3022354ceb83fa895e56be60659ef49c4e40f9500",
          "sha1": "dd3bea94c72d5bbd92febfcbcad18c883e08a216",
          "md5": "c8bfd1b8cb2c57d7865d0c6e898ae179"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 82351,
          "sha512": "16b0ef7e8c50b9dea4b74303edf19e05c489aea28c428d2b56717634a0ec51056c1559dd6a7f17392133eeea32c3b842cf4510aa71ce15f1120ecf1982ac975f",
          "sha256": "f24d53eabd4ae0f8f631fc43ee67c9e7f20fb88656479099e4489c90be9e715c",
          "sha1": "e8e4ea0db4b65818517502aaa3cd3e3db1cbfb44",
          "md5": "aa1a515c4a502ee62806436da54037a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 12687,
          "sha512": "bcb8b912750bbdf3ceffe667de5fd1a73b620f0a32268c9d6fe1e0bf238e6f3f3e14fda7c4341e24692a1593d09ff468fbaea55bd825f337353d32d536ddd3e8",
          "sha256": "251d8c99a01720f1066e3fdb1bd9dc4fd29d488c6b855cd935432a27aeb96d76",
          "sha1": "8170e5399148fa7d8384eacbd48a3862e07c13ab",
          "md5": "be16d2272bce272215ed6b12e8cc3e10"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 942252,
          "sha512": "d4685a4045c9796e2304759c60237ea174482e884c22d7ff3ad1268348fd64c2eaf6b5e100bf38464490c3c1efc1e0e8c4016f50d046ffe36ee670b69b8e9a8e",
          "sha256": "60885f8ea908a15799aa44c67eb711ac7efc7fa4d52aa46bf273b25e85931781",
          "sha1": "13e8cd18fed5c3c07f168b92243e98dbf5ea27c5",
          "md5": "59c53952460ff318ce7ff8e0921d3009"
        }
      ]
    }
  ]
}
