{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 22924,
          "sha512": "9056a3183357f4b5504ca5dfa6621403e113e846ba0083c3f651c67d848819d29376c911c143d3887fd50e037e9aa58d045cd44ed0023bb6cbb6d84e3743b0d1",
          "sha256": "d7428f59f61c6a64dac786e1085f31bcc2bf15a50cdab36d71a6427fd4e5f58b",
          "sha1": "edb72e2c5e3eeb5fc2ebc267af30f3c3926b1ce5",
          "md5": "1e680b5e7ad987c18fdd9c2c8c713075"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-paper-1_20_5",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 22924,
          "sha512": "9056a3183357f4b5504ca5dfa6621403e113e846ba0083c3f651c67d848819d29376c911c143d3887fd50e037e9aa58d045cd44ed0023bb6cbb6d84e3743b0d1",
          "sha256": "d7428f59f61c6a64dac786e1085f31bcc2bf15a50cdab36d71a6427fd4e5f58b",
          "sha1": "edb72e2c5e3eeb5fc2ebc267af30f3c3926b1ce5",
          "md5": "1e680b5e7ad987c18fdd9c2c8c713075"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 122959,
          "sha512": "b7550def0f3926d9e22d798595679e03b6afbd4a5a2ff619491f27092a15ad772d9903091b385bb467cb6705e781b3ec3258f7f43d9c52e427938e1cc6062ad1",
          "sha256": "06d3bcad147bf395b66879c760f8e2ed7dcda593f6e0e554b420a9e3c421aa72",
          "sha1": "ac45c13b2ad9879b29d973e6f18d49d002fd2671",
          "md5": "e3c4b4001ab952adddf20b5743fa7a1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 12493,
          "sha512": "1b49f7eeb077c147ba13af3062c1985338b04d059f908b7c619fbc58759cedd239b35c9236cf1c6206d53542c9f3a542e7ec991e27550b12e0d5f2b3b310bc45",
          "sha256": "4b483fe8a414daa7ec1db10c54cf729eac5fc6dbca8eefbb121eba435721460e",
          "sha1": "a459ea46fbfd52b4b84662214cf5ff2e7b1dd3eb",
          "md5": "301a5abcc668f9093c10f1e812218cf5"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 1282096,
          "sha512": "2179af62d856c0f1319c6084f2d22e389e76d7f74a64831a76e282133a697471e8e78c6776522ae8e9c48676812f9c4a9f276681434497723a5d39ee29a75aff",
          "sha256": "9331a3e2976f1eb14330913308c33d98837c0d08bb5f8c052df7bc5f0e49eab7",
          "sha1": "9d9562401259c2e0470ff33623579ebbb2de9765",
          "md5": "6dbf8f7354f1f4ea2bdf5d6740baac1a"
        }
      ]
    }
  ]
}
