{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "93a94dfa48d0e52e6f21539ebec48c68a6c3c9942ba5457553186afcfc5cd97417346ac948791a3f1c24f5b51da5ff97705cfd3156430bf63f9e5c724670940a",
          "sha256": "29eb53caa449cf850ab7034cbc0b395d1c5f797d6eee3f30408363c917a1afdf",
          "sha1": "fd10535e36958939efc78762adebcf636da4af99",
          "md5": "210f4fb10e73135b307649f17e14209a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT.jar",
          "size": 15593,
          "sha512": "93a94dfa48d0e52e6f21539ebec48c68a6c3c9942ba5457553186afcfc5cd97417346ac948791a3f1c24f5b51da5ff97705cfd3156430bf63f9e5c724670940a",
          "sha256": "29eb53caa449cf850ab7034cbc0b395d1c5f797d6eee3f30408363c917a1afdf",
          "sha1": "fd10535e36958939efc78762adebcf636da4af99",
          "md5": "210f4fb10e73135b307649f17e14209a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 82352,
          "sha512": "bbb6c5590be794aa20d5abc092e22f7941b827f20fc45d4186fb8e2e8630068d8b4cae3a3b0a4f2fdce456a971dcc76af73593653b2f6c9171c71066ba2fa222",
          "sha256": "42d8cf83ab4a8d6f3ba96094a642b5187d4ac6726618b0bb1a60d17c28f55fb9",
          "sha1": "1553b1e2e74a15934c5f689e6ef80ff21cbc1937",
          "md5": "a40e648d8d78c5b1348ba059985ee7b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-sources.jar",
          "size": 12687,
          "sha512": "997c2229ea5c088c37b159af98ecd59e8951bf52e4e04088f99baceeea620608d9f23bfab5d4857f64cd7fa7be0df759559967fde6d7a26bad9faf1d9fbd43f5",
          "sha256": "241862ef746ac12f45e3c210bf702b79f7904889c7f16754793a0ba626a502e7",
          "sha1": "2394e672403e422385e2cb37b0880a162e526aa0",
          "md5": "40ba55f60e97cc1644da3d9c73770c0a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "url": "box-bundle-6.0.0-SNAPSHOT-all.jar",
          "size": 940678,
          "sha512": "d8b35f1d5856ce254135930a09954ad7ca8c43a972d9accb7e3ae9bb86b678a3fda28a8c606e761b3f68fcaf661c3be740c7e91176a1fe1112ccaf4cacee4cb0",
          "sha256": "12333f9f30204fdbc40aeac2d330e33c5dfa77dc442cd1a66cd701d080b3fde6",
          "sha1": "c3b2fe651ec1847c0231c4055e1dbb851637938b",
          "md5": "4c1c30143fba1d6ba9750682508f2e48"
        }
      ]
    }
  ]
}
