{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "5.0.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "box-core-5.0.0-rc.1.jar",
          "url": "box-core-5.0.0-rc.1.jar",
          "size": 54780,
          "sha512": "be7bec4d66a3b1667ea300169f0ea73b2a0c72fd9436bf22dc6596085a9faecb1b0bad09840ff5d99bc19940b6b315cca20e7af1285682db92e86635ab2aba29",
          "sha256": "b99458e419941fec0cf6e7a7279fc483972ccd7758b1b4a7333e6111b7402fa2",
          "sha1": "9325e73375966179e3ab3e6b50aa8660d895456f",
          "md5": "e7d15346ae5ec1d7feab00d2cec492be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.github.siroshun09.translationloader",
          "module": "translationloader",
          "version": {
            "requires": "2.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-5.0.0-rc.1.jar",
          "url": "box-core-5.0.0-rc.1.jar",
          "size": 54780,
          "sha512": "be7bec4d66a3b1667ea300169f0ea73b2a0c72fd9436bf22dc6596085a9faecb1b0bad09840ff5d99bc19940b6b315cca20e7af1285682db92e86635ab2aba29",
          "sha256": "b99458e419941fec0cf6e7a7279fc483972ccd7758b1b4a7333e6111b7402fa2",
          "sha1": "9325e73375966179e3ab3e6b50aa8660d895456f",
          "md5": "e7d15346ae5ec1d7feab00d2cec492be"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-5.0.0-rc.1-javadoc.jar",
          "url": "box-core-5.0.0-rc.1-javadoc.jar",
          "size": 220277,
          "sha512": "b46ba7c2f3c2dd657bcd16d91bbd03743a0b48614d8aa8fb71a3dd3fd3cc5d86a3f6022ca911622f62ff521a37590f78b0ef5b468daf18d447be0b10cbcdc987",
          "sha256": "5be7161d6be09f23d586cffaec551d8e65f9ec0064b138d24556dfd8cb1404f1",
          "sha1": "757efbe87bfdcdbe2cb844865da56da36700baab",
          "md5": "d03ed4011b83c7e4dae1582cc1708f65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-5.0.0-rc.1-sources.jar",
          "url": "box-core-5.0.0-rc.1-sources.jar",
          "size": 24212,
          "sha512": "e885e1355395c361147d9765efb214cbe0ad987d5a91a5889df6a0970fa9bba44f6656281bc74706d88823f42f65348f2e3040818927294ca3eaced4468f6502",
          "sha256": "d02e090019a511c18643f4787cc5dccaee5701ce230ede76626c21f2b2fbe61c",
          "sha1": "79513c4b6e55ddf38db959f341bca9c75ba2ed70",
          "md5": "29ff676f7be4ad0d97907dccbd8475a8"
        }
      ]
    }
  ]
}
