{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 31536,
          "sha512": "1591cc0ef713542b6234fe23da69202e3dca17d17a353603e097d379e4a6ed3adf1bd9b3a2af240ccbe56c56d6f771f7b11e5b85fb165530b4b815c116e954cd",
          "sha256": "e58ce8a48adbc1ff5bc6b8ce744bc362ec21506bf869847dd7b5bd7e9720b8de",
          "sha1": "976c2fc1c185d741498bd036538bc1d97921063d",
          "md5": "2e519d24bac19df6d7853db46986c420"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 31536,
          "sha512": "1591cc0ef713542b6234fe23da69202e3dca17d17a353603e097d379e4a6ed3adf1bd9b3a2af240ccbe56c56d6f771f7b11e5b85fb165530b4b815c116e954cd",
          "sha256": "e58ce8a48adbc1ff5bc6b8ce744bc362ec21506bf869847dd7b5bd7e9720b8de",
          "sha1": "976c2fc1c185d741498bd036538bc1d97921063d",
          "md5": "2e519d24bac19df6d7853db46986c420"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 195960,
          "sha512": "e82fb1fc93f2aabeed374fb4ff0d029763e407f9bcf7382da65d733f6bcd9b694bea0bfa9fccaf2df7e5c2ee22dcb164a4f53d8c58870ef71e21024cb6abcb26",
          "sha256": "e400b0b404962180366e5a8a6f18b146df085282f7d35429d71fca837505b361",
          "sha1": "7e79b366657515919cc716ba657bc9cccbe81bd7",
          "md5": "b469b01cd737788d84961f985ab6cb4b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 15870,
          "sha512": "28b406b85db6481065d2d39cb169bd39130cccde38bd1faf2838f0b9cc2d9b0744c095d816491277a74697b7bbfa87e945d2b3184fd7d4526136cf5eb8b214bb",
          "sha256": "9e6fa980be677f474384e31ca41046f44810e8a5d591fe2ee87b4807ee89aecf",
          "sha1": "aed78544d3e5cbe9274b221b9d9c432ad68676bc",
          "md5": "b269c35d68995fe17071c021687608e8"
        }
      ]
    }
  ]
}
