{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 32741,
          "sha512": "a5fe485c1c8c7985b1630ba321ec379aacee202ae019be96af4f745372985d0d9708a40cdd98b4dfd3d90e4beebb2dee768bdf416161416f4035b83e55790ee9",
          "sha256": "9e8306dfc24766f89c1fc09dfc80187910ce9913e839db6e24034ee664ba4dc2",
          "sha1": "2e201a3dc9db2dffba963bcb817483ba9bf5dfb8",
          "md5": "7da932e9ef11b3de89bd31dda6f7b341"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 32741,
          "sha512": "a5fe485c1c8c7985b1630ba321ec379aacee202ae019be96af4f745372985d0d9708a40cdd98b4dfd3d90e4beebb2dee768bdf416161416f4035b83e55790ee9",
          "sha256": "9e8306dfc24766f89c1fc09dfc80187910ce9913e839db6e24034ee664ba4dc2",
          "sha1": "2e201a3dc9db2dffba963bcb817483ba9bf5dfb8",
          "md5": "7da932e9ef11b3de89bd31dda6f7b341"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 176368,
          "sha512": "50543241a8b5ac7c8ab57b94a9135f6e1643ea19c2f0e8aaf857d5191ba615efa24baf0f8c3a0ae19be4855d6d335ad6174ae32649a224ff70a866e92baa7c95",
          "sha256": "17b89ee3c754bdc55f06b8e78e565fd07b09a5079468aa356b1f5575b56238d8",
          "sha1": "5086206e5a9a95937ab82a1ba129321fc2786bc7",
          "md5": "35c90d2d776f89577b2fa0d0197659aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 16881,
          "sha512": "4a86a2fd3be9f8dfdbbdd093e3e4c7f12b255869531fa00b00fd09bdfe86da8df6c0b83ff477d64252501140bb4c3842c6fdf26301d5642b860bebe7110e95cf",
          "sha256": "706526b4e55c0534956f802525c8b9935eed209cd31b795c97a262e1fcd7fb3d",
          "sha1": "4b999519106e0d93c46a7d6c1d6460ff9ac2bb57",
          "md5": "e866588e9bcc61f0c337679c043e8322"
        }
      ]
    }
  ]
}
