{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 44212,
          "sha512": "34d1a1756b7a1e5c29629141771c0c6c02222b84f5e9d389ac9b8cec404f3364d14b95aab45ba395d4d9f415e3cf1712ed24611c154f8fa968ab630ffa3df2b7",
          "sha256": "43a7e020084b26c89b9c21e6a77d2ab436fde389b7af6c708aa3aba3e79ac198",
          "sha1": "d541f1d73f0405d6a3dfec484fa0055187d0009c",
          "md5": "52121d7860502cc22b09f0bc18a9fbdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 44212,
          "sha512": "34d1a1756b7a1e5c29629141771c0c6c02222b84f5e9d389ac9b8cec404f3364d14b95aab45ba395d4d9f415e3cf1712ed24611c154f8fa968ab630ffa3df2b7",
          "sha256": "43a7e020084b26c89b9c21e6a77d2ab436fde389b7af6c708aa3aba3e79ac198",
          "sha1": "d541f1d73f0405d6a3dfec484fa0055187d0009c",
          "md5": "52121d7860502cc22b09f0bc18a9fbdb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 215114,
          "sha512": "8eb3b4b03e234cd5a4b6ae877d749d9b6e698df2c53d109f6b48bef80849c66d0709d4e0aa475a3bced4605c21514f9bf449743b3645948868a1be6d91a07746",
          "sha256": "e615bb145e53466ded705888717d131416b93352ff60b03c2eff7e7a8b9be553",
          "sha1": "951f9d5321421fb7c3962ae390a6d88b23142f06",
          "md5": "77998cad3112822b689bfa3028ff0c12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 20216,
          "sha512": "ac2013565edba4ecc0085e2048760c62e1acee713da84e95f03dbe8f846afed710d4e84aa257d51265e477d494f95f3f4ac4ed03442c68f0f64b7932e02fefbb",
          "sha256": "15afc7f5417b83d22a2491e5dcf87a5489e1a9b746f423e6c21bf2401cf773c7",
          "sha1": "1b1afc09667962c1e49882157270582887a8a952",
          "md5": "3b1452ad1f44f32f8e538de459268fa0"
        }
      ]
    }
  ]
}
