{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 32741,
          "sha512": "d9ebf875b948ba377446a0a1e71b682cb2b4cf71fd2106bde0faf29a6d235b8d7c7c93ce99cbaa86db7a41bee15eaf5b960ec5b3eb88cf67c9e1a977da06ccbd",
          "sha256": "e132d977c7e6c8feef900026b80bdc99de22f8780ec417ff2e1585b7450abdef",
          "sha1": "ad8bb7a27109a6c5d6dbe0f249ffbe7856d241c6",
          "md5": "832b742fa8a1c61d9fca1023a2be8bbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 32741,
          "sha512": "d9ebf875b948ba377446a0a1e71b682cb2b4cf71fd2106bde0faf29a6d235b8d7c7c93ce99cbaa86db7a41bee15eaf5b960ec5b3eb88cf67c9e1a977da06ccbd",
          "sha256": "e132d977c7e6c8feef900026b80bdc99de22f8780ec417ff2e1585b7450abdef",
          "sha1": "ad8bb7a27109a6c5d6dbe0f249ffbe7856d241c6",
          "md5": "832b742fa8a1c61d9fca1023a2be8bbe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 176368,
          "sha512": "509441c92e085f4bbbab11d34eaf519fc36c14c9cd6fff055f77f6d59272e96b100dfbe900be4929b43cbf8c276f6bbda44ed1b440e3b314fbfc66ce0bc6ba98",
          "sha256": "f06f2f7e2d3806bc46e37b0a5ec0332303e0fe7bc75715ef0825a378db2e587f",
          "sha1": "6ef9f0a4a748f8b8bf1e848b56ac2960242c9300",
          "md5": "14d1992618989c972408b173545a7a69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 16881,
          "sha512": "08b825c1df7629a0d89a48827a1f2f118d787e21847cb804e662521f255148d7f53d5176e3748ceb6d01e67fc39646c40b44fae6d061473dbf449efa3cb4b0ac",
          "sha256": "a0113960fbc50edcb62b30c72c32641356aacc373e6e1e393a71de923231c499",
          "sha1": "c67635e84961c8a4728305362c1d6a7026d88058",
          "md5": "dd0a64ec40dfe2dece43ddd83b1f626f"
        }
      ]
    }
  ]
}
