{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 30774,
          "sha512": "bdfdada65b7fe0fe2aab88b20bcff9e3c252e0d0bf0e821fc053558b162a0bb9dcb4d102883a8e5ab75f2c9986d6cded1f089d9ba949150e66ec4c8d98708697",
          "sha256": "c8eb4962f44ec533b0030a38537b56391de41461f8a86ff1377b52cdf6f776ab",
          "sha1": "a670c65691ba6fd59cad71a4898ca8ec7c1db7bd",
          "md5": "9d1a55c3e9d14b1451a063b971e7bfcf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 30774,
          "sha512": "bdfdada65b7fe0fe2aab88b20bcff9e3c252e0d0bf0e821fc053558b162a0bb9dcb4d102883a8e5ab75f2c9986d6cded1f089d9ba949150e66ec4c8d98708697",
          "sha256": "c8eb4962f44ec533b0030a38537b56391de41461f8a86ff1377b52cdf6f776ab",
          "sha1": "a670c65691ba6fd59cad71a4898ca8ec7c1db7bd",
          "md5": "9d1a55c3e9d14b1451a063b971e7bfcf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 173382,
          "sha512": "3a7d7a12a13a2c88609b5882fe7b637660172b98a8bb3bbb291897df32c0bf633fd748f3eeaf1045381e4dce9c1beb8db95ddcc624111479f3b694b81024ea7c",
          "sha256": "35ddcf50e5a4a7835b21d4988e27cf644238ff3381e170f55a85ac939cc8eb3d",
          "sha1": "10bef9ff393b0f567231cf3fb2091f0d7b4bd161",
          "md5": "f1b5f5c177de39a6971f8dd6bbd61411"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 15998,
          "sha512": "6394a3894e96369013963cc55aecc93c0449cffe98a0c189b8abdbda0224be29ff082906b1da8923e3990fc9a7d6a9b47a1c666f9e683cd1681768c27e5fe494",
          "sha256": "0f503af5ee4255dfeba8641bdd04203403132b3590d9d47d5fe9de27f3ca6973",
          "sha1": "2338af4e873285ebb45e2da73e874a71a53a7426",
          "md5": "98a1e1ee087fce4c0a1b96fd31570a38"
        }
      ]
    }
  ]
}
