{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 30774,
          "sha512": "7ad695ae8c0d4d9ee5bd94a7217d2284bd0d59d126dbac95506852767349f40bd511749df6fbec5bb737620fc1a822b623627300b5227424c0daa8555c1792e0",
          "sha256": "495dfc1b4c9ecc72c3de640094c2115954214c71a117a969f48b8485af6c40d1",
          "sha1": "dfa4809020cece5527d73f691c9d17d4b61cad15",
          "md5": "80309be9bb72b852244761ede0a582f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 30774,
          "sha512": "7ad695ae8c0d4d9ee5bd94a7217d2284bd0d59d126dbac95506852767349f40bd511749df6fbec5bb737620fc1a822b623627300b5227424c0daa8555c1792e0",
          "sha256": "495dfc1b4c9ecc72c3de640094c2115954214c71a117a969f48b8485af6c40d1",
          "sha1": "dfa4809020cece5527d73f691c9d17d4b61cad15",
          "md5": "80309be9bb72b852244761ede0a582f6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 173385,
          "sha512": "74bc6c045759dd11d492c2283d7f7e0dae9d046950b8d850e048d28c9ac5e343ea0244a5f920de8fdba1217e57c2e4b379f50323f6ee3dcbb682f3945931046e",
          "sha256": "24b75d1a13602497d8dbdeaabe710f177e6a8b29ff77fc9a7befa18c27739a62",
          "sha1": "f06327d063eea062daed36c47822713a7dc2bec8",
          "md5": "0822164280295461f35eebc707ce863f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 15998,
          "sha512": "b7d8c8443377269e35f5b9cf20a3465a52ea64b6be8fca2e4f15c32c051a7bc2f2ae44bab072463bda4383b1740838670c9766a3e63c14cc27f65b68a76da762",
          "sha256": "83e0cb5d102c0c9b41ce11475d6d1ff1aa62c5f95982972902e4b1633dc66da4",
          "sha1": "393810ce19274435b1e132cc5bd0635f00881e5f",
          "md5": "a781b17f4c1f71e9ec51427d959599c1"
        }
      ]
    }
  ]
}
