{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 30774,
          "sha512": "7def53e389441f576aa533ba7595d12ca93e069bf8d97f8a3c0bde09e503e46f026b1df1eb1bb071f2f415e78e033e1b3ce3f5b6e1b58e734897d0769712a5f0",
          "sha256": "3679bbb57dd8f5ccddaad296f045115cf8129390e050c1fc68279356e541c4ee",
          "sha1": "c809d6b5ab995905c6f7a529f6879b3b2911a470",
          "md5": "2424ba35ed53d6a9c44a98fd8a23ac9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 30774,
          "sha512": "7def53e389441f576aa533ba7595d12ca93e069bf8d97f8a3c0bde09e503e46f026b1df1eb1bb071f2f415e78e033e1b3ce3f5b6e1b58e734897d0769712a5f0",
          "sha256": "3679bbb57dd8f5ccddaad296f045115cf8129390e050c1fc68279356e541c4ee",
          "sha1": "c809d6b5ab995905c6f7a529f6879b3b2911a470",
          "md5": "2424ba35ed53d6a9c44a98fd8a23ac9f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 173382,
          "sha512": "60135bfca7e35630e1e0ac4ec598e4ee0e99d97f016c419dfc1a358dc495b1786cf1a9d05f479be90338b6b7f8707215fbf1f85d4576802d84b856b535713935",
          "sha256": "47ea2a8fd9fabc6f1f3fa6275309f8d43ab1cf723e581cb5bce6cfc452f9e940",
          "sha1": "0e8a35bcaa0ba81807a657d53b176fd2b607071a",
          "md5": "8b168cca69cf78bd314870d2e53c2139"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 15998,
          "sha512": "3c2cd0944f252598812ee9b6a927f868335258c9d7477f65339c456839aefef74b08900f92eeb87a4c426428c09c60abd3ccaa9526769c9860fc674d48fccd2e",
          "sha256": "616bb6e566850f247b59a5d1d887556fbe81fbf0b2207e044c0eae0d685724dd",
          "sha1": "17f6d06613abb2892b500d5d9e1ebfbcc2e80c02",
          "md5": "407be367c695ccc87d8d7b68c13510b2"
        }
      ]
    }
  ]
}
