{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 32741,
          "sha512": "61e27aeb014572aad31cd5e1079140df05854214bda2edddbe0a1a1a9d9ba6945229c030a89b42df97760521f8e422f91367b1eee2669ed528f4bf7d844e3ff1",
          "sha256": "31760a972ae40db12d978ae42d11e3b428001c0760e121bc9b153591c89aef9b",
          "sha1": "9e624e235a380d72d1271b278ce0979a514bff82",
          "md5": "bf77ef5fbc0b332b5c2d8266364f41ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 32741,
          "sha512": "61e27aeb014572aad31cd5e1079140df05854214bda2edddbe0a1a1a9d9ba6945229c030a89b42df97760521f8e422f91367b1eee2669ed528f4bf7d844e3ff1",
          "sha256": "31760a972ae40db12d978ae42d11e3b428001c0760e121bc9b153591c89aef9b",
          "sha1": "9e624e235a380d72d1271b278ce0979a514bff82",
          "md5": "bf77ef5fbc0b332b5c2d8266364f41ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 176368,
          "sha512": "89ca9a1e32bca98658aa2f5cb213ca8ced7d8fd50a7994332a4d7b9cc787428f179d3280c22c20f0af86836e117139874f35c29a846c67a3cade492e272e1021",
          "sha256": "663b871f800bc3aeeb0c7f1c2385e7e244f15dfd93beab89de4ce0427227cbc8",
          "sha1": "c3b444f69e55b6f3eb6c9bc38731696617ef6e02",
          "md5": "6d219af7804aee7bd69812cf8132a0cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 16881,
          "sha512": "c19b83128ca10c0c74e38c164ad25cefba3cffeb5f850d35dadf541e49690114de0696a50330c039bc61156b596d297b321c5725fc0a8c1a0f23d2cf4591555b",
          "sha256": "5c6b37419c258cd4117703eb70bfa94f5b81de8ba54e7bba8d449edabd79098e",
          "sha1": "2b59dfc88b7562d1ca1cef432f035a3444d3354c",
          "md5": "25b1802304e56b948076d34256e05c72"
        }
      ]
    }
  ]
}
