{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 30774,
          "sha512": "f03d3ab1ef4c957d586ae29420affb49d3ee3cae9e2d36456fdab680014548b94ef04a58f2d24b291e16329ac57457cd442c9fbb0e3bf6f062663362ff060831",
          "sha256": "3b7c9455eb11b8156975fa1ab9e0a5902ec731532787ddd9bb90928bbf8f831a",
          "sha1": "50956cbd24d5310e714ae72cc1eb7e5707063fd9",
          "md5": "2815d9cc7eb072176214e84b63459abc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 30774,
          "sha512": "f03d3ab1ef4c957d586ae29420affb49d3ee3cae9e2d36456fdab680014548b94ef04a58f2d24b291e16329ac57457cd442c9fbb0e3bf6f062663362ff060831",
          "sha256": "3b7c9455eb11b8156975fa1ab9e0a5902ec731532787ddd9bb90928bbf8f831a",
          "sha1": "50956cbd24d5310e714ae72cc1eb7e5707063fd9",
          "md5": "2815d9cc7eb072176214e84b63459abc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 173386,
          "sha512": "c31af9f3672b725effb31d21b340c58e42aa4fd8d3fde1318a89ee0d866a9f2aa668d7c3f548b363d6fea288020ed0ea04ff2cf4e68d68ed7f889af3382c5b00",
          "sha256": "ef6a93626ba868b92ccf6922c0592ccadb17414cfcf0095005a913db0e34e58d",
          "sha1": "fd6737cbe82fc83f2ab7b349e0083e660ef0c8e3",
          "md5": "295e8270bb9114beabc0e723337e4ec1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 15998,
          "sha512": "2f84eaf409e6c8e7f1e8c2b8e416f88fb8cab8c8db066cc418f10d1969d5f3600d978eeba5fdafe50f120b709d1a78d2f7f46a8d903a1e03a5ca575c6411e6b3",
          "sha256": "ab54dcb9fdd2912a8b7e647f9ece32264050c8e0810cb5639788ccba40971ac5",
          "sha1": "6a1de562a83a5b129afd782ace55a85a245c3e15",
          "md5": "40a87019778e53ae6192bdd9be9fea95"
        }
      ]
    }
  ]
}
