{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 32742,
          "sha512": "51d7cac117518f441e3d35cf631fbad59969653bf7008d6ab423639703bf702ae6132feb84b645055ecb6d4fbc8bbd9679a15dd3108f6304dbd44402f86df419",
          "sha256": "8b73c246478378a16f112d52708d379a7d58ab3b3d61a9f80f27c535cc6e2cb2",
          "sha1": "db5c24b0e791f8115b5c0d873bd62a3c02100e45",
          "md5": "20a98c5a66ddd78cfeb8a5afccffd9c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT.jar",
          "size": 32742,
          "sha512": "51d7cac117518f441e3d35cf631fbad59969653bf7008d6ab423639703bf702ae6132feb84b645055ecb6d4fbc8bbd9679a15dd3108f6304dbd44402f86df419",
          "sha256": "8b73c246478378a16f112d52708d379a7d58ab3b3d61a9f80f27c535cc6e2cb2",
          "sha1": "db5c24b0e791f8115b5c0d873bd62a3c02100e45",
          "md5": "20a98c5a66ddd78cfeb8a5afccffd9c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 176305,
          "sha512": "3cc39d40be1ee7fc1455b34a04ad69d58bb9c2503016928e5a159186f08d217019d45c7842ce92f9a99e9ca67a2c9268c5e82fb013f8e29000caa5d7bc11c5ea",
          "sha256": "b86c8de5c21334934e2dafc7eda5d336129cbbac09c1a3a946b0b168f461790f",
          "sha1": "92c2f4e5bc088ddaa568906bd4a59eecdeb35ca4",
          "md5": "1bcc88cb3de421533adab5baafebd649"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 16877,
          "sha512": "1fbecb124f4f07016e9a6fbc4f17fe4827acd153b10a6e626c311fc384989349a3eb5d7538da23702a76a649397430529b815798fd0c350c32c1a398b58137de",
          "sha256": "051badefe6d95599c6d53d11b73f0d992ec6da640f320cf264be38e9da9a8197",
          "sha1": "1a9102eafbf61e69dc063ca16e7c408cfaeb35e0",
          "md5": "355f4f7bc60a20651c9b99b523893247"
        }
      ]
    }
  ]
}
