{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "5.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-5.4.1.jar",
          "url": "box-gui-feature-5.4.1.jar",
          "size": 78922,
          "sha512": "c4e7b7163d9a028954f50502446150b9d9dd8d5706d1bb047fd7930c6724e7ecbe5c58fe6cefb7befcbef3a0d5e0431998dcc4f9d4cf6cc426220f2be755c612",
          "sha256": "536b433e2abd108ae08aab719274e631678d41fd867135b71eeaf86179aca082",
          "sha1": "0ba7488cda0332d8108c727f81c3135369079213",
          "md5": "d3a71fd1cdec5b8c732d2815d181c672"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-5.4.1.jar",
          "url": "box-gui-feature-5.4.1.jar",
          "size": 78922,
          "sha512": "c4e7b7163d9a028954f50502446150b9d9dd8d5706d1bb047fd7930c6724e7ecbe5c58fe6cefb7befcbef3a0d5e0431998dcc4f9d4cf6cc426220f2be755c612",
          "sha256": "536b433e2abd108ae08aab719274e631678d41fd867135b71eeaf86179aca082",
          "sha1": "0ba7488cda0332d8108c727f81c3135369079213",
          "md5": "d3a71fd1cdec5b8c732d2815d181c672"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-5.4.1-javadoc.jar",
          "url": "box-gui-feature-5.4.1-javadoc.jar",
          "size": 274040,
          "sha512": "1c16c6d03a0a8e34841cbc52dc682a21e59cba05fbd5d04b696add162d6b1d7c50b8cffdffd2745bdc37f132c16747a86b400e378a921fd6580026c8bd61af9e",
          "sha256": "193477afa26cefa12748f4c63f21ec0339e40af7a31b71d739add62bf5cd6c42",
          "sha1": "8094dc188163977248e852cd66094804b3dfd093",
          "md5": "5ac4b5339f838ffe434ea8c79cf12797"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-5.4.1-sources.jar",
          "url": "box-gui-feature-5.4.1-sources.jar",
          "size": 36787,
          "sha512": "421906b1ff3b0164f350eca02c2d7aeef2a7050897e4cb798b127b02e1083b9af6f1f41d19ed02c799c6665e049b7906c118cb521ace1e21f2dc9be75e1ee603",
          "sha256": "52fd9593c91267e2b943b8e344eee03a5da0ccf49007e3d525c3645befcd5354",
          "sha1": "2917b29b2fc9041094c729ab1c090e9946c9bf7f",
          "md5": "94e6dc938d1d8de7c0ffd2084cb80e36"
        }
      ]
    }
  ]
}
