name: Box
version: ${project.version}
api-version: "1.14"
main: net.okocraft.box.Box
author: LazyGon
commands:
  box:
    description: Base Command of Box plugin.
    aliases: [box, okobox, okostrage]
  boxadmin:
    description: Admin Command of Box plugin.
    aliases: [boxadmin, okoboxadmin, okostrageadmin]
    permission: boxadmin
