{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "5.1.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-5.1.0-rc.1.jar",
          "url": "box-autostore-feature-5.1.0-rc.1.jar",
          "size": 52934,
          "sha512": "27d1bdc53a86d60c2a81c06e39f7db7d66372a1f70bde8305cb2f7c8210d3665a993d58667c281ccba408b0fa97c7df4267f0c299eac49efa46b173150c4f98c",
          "sha256": "4b1a36d1ad49f3234dab4456281793455cf479f8e12427ab7c864b02dedbc999",
          "sha1": "5007e57a1337b4cda7645874876f87019f5ededb",
          "md5": "28389ac4a78b131591067b620ed2e0af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-5.1.0-rc.1.jar",
          "url": "box-autostore-feature-5.1.0-rc.1.jar",
          "size": 52934,
          "sha512": "27d1bdc53a86d60c2a81c06e39f7db7d66372a1f70bde8305cb2f7c8210d3665a993d58667c281ccba408b0fa97c7df4267f0c299eac49efa46b173150c4f98c",
          "sha256": "4b1a36d1ad49f3234dab4456281793455cf479f8e12427ab7c864b02dedbc999",
          "sha1": "5007e57a1337b4cda7645874876f87019f5ededb",
          "md5": "28389ac4a78b131591067b620ed2e0af"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-5.1.0-rc.1-javadoc.jar",
          "url": "box-autostore-feature-5.1.0-rc.1-javadoc.jar",
          "size": 165930,
          "sha512": "322a6d5fa8e12b7d93316674a7c14604c0e99fbcbd9d51f5ddb994328d0d2c0c2d5431519f7eeb3dbb39e6546927d12b9876c705b890b4434363528b66d91981",
          "sha256": "c4278ae3e3f162a28c46647150e85bd3b8785caeccec809c8df5d052aef99f66",
          "sha1": "687d959bbbe522cdafed25790b670664f857700a",
          "md5": "003c59c29aa77e31c488dd2ef2e837d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-5.1.0-rc.1-sources.jar",
          "url": "box-autostore-feature-5.1.0-rc.1-sources.jar",
          "size": 26250,
          "sha512": "0c4c2bcf8065ff1fb85dd5e2232fb6a4567ade671007352683c1a8250571c8bc74311ef81651db1a948a9b57f17fbbf9853f8b25b6b6833f58d8684238bd9602",
          "sha256": "3b6c0d635bcdbd438b9ca3810bee66938bfbf7c415359e59dcf4ba2fd24c2f94",
          "sha1": "eb8466ac50284c284323afccdbf1538651e9d84e",
          "md5": "1a85f70bd9a1902d172afa817ebddd86"
        }
      ]
    }
  ]
}
