{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-rc.1.jar",
          "url": "box-autostore-feature-6.0.0-rc.1.jar",
          "size": 54265,
          "sha512": "3f7dd82539bb96a922bd0690e5534093fc7ef55d8a8e7a6971798834066565bbf6582bced77025684d228047652a1ff19ba8b06734c17a89ae253fa0e2403c9c",
          "sha256": "3a0c6aec25f95e7f4be69d9b45951a89013a05000190d0e372bf1826736706b1",
          "sha1": "b1178fa38617640d5f00e90480b224bbe58c14f8",
          "md5": "3060d7c9f5a86a0a999539a0d321dbbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-rc.1.jar",
          "url": "box-autostore-feature-6.0.0-rc.1.jar",
          "size": 54265,
          "sha512": "3f7dd82539bb96a922bd0690e5534093fc7ef55d8a8e7a6971798834066565bbf6582bced77025684d228047652a1ff19ba8b06734c17a89ae253fa0e2403c9c",
          "sha256": "3a0c6aec25f95e7f4be69d9b45951a89013a05000190d0e372bf1826736706b1",
          "sha1": "b1178fa38617640d5f00e90480b224bbe58c14f8",
          "md5": "3060d7c9f5a86a0a999539a0d321dbbf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-rc.1-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-rc.1-javadoc.jar",
          "size": 110258,
          "sha512": "6b42e131b432d694cc85b584b515dbace88e373f5cd5a0f2a44ede2a105c7ef9c1ed09fcd49b89bc8691957082d12ba06fe7573459000f0e42214aa598043d08",
          "sha256": "a8ee6ffbeb932f49312c1b0c7301224dffa90ccaac1c412bcdd0fe6a12b47137",
          "sha1": "108c26e8d48b530d2c710a6a3714b42001e970c4",
          "md5": "621d5d40fc327fa5faaedbfdb042c499"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-rc.1-sources.jar",
          "url": "box-autostore-feature-6.0.0-rc.1-sources.jar",
          "size": 27459,
          "sha512": "b883e69b646e500ddaa8ed52ec68688e12de60c0fdfa44e91607fbde34103dcdae03ffbc1efcf2c34021d33f86ec7e6b4fc392fa67318593fb114de22963b8c1",
          "sha256": "0812ed170eb3e61be5e48bc14c74af6bb68d8fc33e991a58528f05b464bb6edb",
          "sha1": "ec3fe528231f601506a5a2b5f410085c4bde0db1",
          "md5": "acf877bbb3227359ad173e704a621a83"
        }
      ]
    }
  ]
}
