{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "5.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.4.1.jar",
          "url": "box-notifier-feature-5.4.1.jar",
          "size": 7505,
          "sha512": "7f87953333aa94659154fe35d9d734f58f4b2af305186e8712b26e7b6cbd4ba1eaa5fedfc2ff8a9d40792eceb870474c17f4b90ea3a75039feb3785548303c8f",
          "sha256": "3d65a88702bd21a0f5a89567be8861ed9d456530cf024eca509530ef3650356a",
          "sha1": "d7467405cf1260baabebaa71630a4a6af967f313",
          "md5": "3607ed5dd47363a32c9157a0fd831a50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.4.1.jar",
          "url": "box-notifier-feature-5.4.1.jar",
          "size": 7505,
          "sha512": "7f87953333aa94659154fe35d9d734f58f4b2af305186e8712b26e7b6cbd4ba1eaa5fedfc2ff8a9d40792eceb870474c17f4b90ea3a75039feb3785548303c8f",
          "sha256": "3d65a88702bd21a0f5a89567be8861ed9d456530cf024eca509530ef3650356a",
          "sha1": "d7467405cf1260baabebaa71630a4a6af967f313",
          "md5": "3607ed5dd47363a32c9157a0fd831a50"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.4.1-javadoc.jar",
          "url": "box-notifier-feature-5.4.1-javadoc.jar",
          "size": 95702,
          "sha512": "08f78e98c784788fb3505ff4e82ec3c22f5739c391729defe358b7d251e2c4d9d9ba5deed46df7ab1cb49956581f4daaf12c5ac05d65c8dad083eca221d74fc4",
          "sha256": "55b0e7d20cf16c932a0e31d4365e4e824806f1778eb91d1f9a6eb3ee06552273",
          "sha1": "f97118a86c79eef37b735161189bced0c2df1c0e",
          "md5": "a69d343eb305026a0dc20526f3e2eb40"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.4.1-sources.jar",
          "url": "box-notifier-feature-5.4.1-sources.jar",
          "size": 3874,
          "sha512": "c701f367869fd8e5273e19be85f3757da44ec27e2950a92109e2d1ca7f18ff231e1409d8506861a832b51c58d289d7eb540328563ddc2a83d76b239101eedd80",
          "sha256": "890716fadc6d34085e67011a10a9521127cbdd824332e262bd607b78757b5a8c",
          "sha1": "ce7e9da35aa90d6611bbf6ee66a744b929fce7ed",
          "md5": "f90bc1b7dca4508d3feef744488a6025"
        }
      ]
    }
  ]
}
