{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "5.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-5.5.1.jar",
          "url": "box-craft-feature-5.5.1.jar",
          "size": 64409,
          "sha512": "9a598a6fa518da0416a3a54592421d9dcc1a832da159837ba0237bc2827076f5a47bbdb21205b309c9d2d28bcda9862658262a965b6838b83a5c5a2b62ab6918",
          "sha256": "2e54755844a7f4a37e1cf6b0fd5ca6879ea2d13da637259bcb9ddcdfe09b70cb",
          "sha1": "0c676dc1686766b4e587215b8e89b6b4f8afe7f7",
          "md5": "6fe40d23b7e2ed9d62526861f589cd14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-5.5.1.jar",
          "url": "box-craft-feature-5.5.1.jar",
          "size": 64409,
          "sha512": "9a598a6fa518da0416a3a54592421d9dcc1a832da159837ba0237bc2827076f5a47bbdb21205b309c9d2d28bcda9862658262a965b6838b83a5c5a2b62ab6918",
          "sha256": "2e54755844a7f4a37e1cf6b0fd5ca6879ea2d13da637259bcb9ddcdfe09b70cb",
          "sha1": "0c676dc1686766b4e587215b8e89b6b4f8afe7f7",
          "md5": "6fe40d23b7e2ed9d62526861f589cd14"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-5.5.1-javadoc.jar",
          "url": "box-craft-feature-5.5.1-javadoc.jar",
          "size": 208169,
          "sha512": "fe1a84abc638ebfa7a96029f734556ad8f25dd77ec409761a82095af951b77e4b84bcca28335771b5b438d8fa792dbfd081cdd45955a0234f2d0dae7d62a6fd9",
          "sha256": "7a3df1e9f501bdb2d6308d77bc3a45928f94324ea26e55d109d9143b790f76a7",
          "sha1": "71880a7ccbff0b16f193b948ce209403fcff63d3",
          "md5": "7542c7169fe0d32304198cef0788b28e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-5.5.1-sources.jar",
          "url": "box-craft-feature-5.5.1-sources.jar",
          "size": 30339,
          "sha512": "d1b1582fa3b15dfb849e48dfbfa0cf62d379231e61e3e8582869b54d188f4e84c693d5444f7b822963090daaca2ee168b05da0a4123bfceb5037452ade1262cd",
          "sha256": "d08bdfe713efcecc9c627e58752d6c649fc0c2d6a6c8823be7e5372617de4a34",
          "sha1": "84f918b2a97914388c924c9601ffa590221bdccf",
          "md5": "359eed681761d5e784622a178b195a3b"
        }
      ]
    }
  ]
}
