{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "gui",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gui-4.4.0.jar",
          "url": "gui-4.4.0.jar",
          "size": 73962,
          "sha512": "7f433f7c93d423e25cb58e0ab69205a7a6875a0408dd153e22b0f1b83e146de7beec5ee4b9b392ca1728a71744aa0ed35162b18552087849f13590eb3fdab4de",
          "sha256": "6018a22a83febc53531a864709ab5912378280f69b29a26557ffabfaf09c6b10",
          "sha1": "4166a701de15afd0a3e2b14de02e93541208b9e4",
          "md5": "c35d8f8a84d46f5940cdb1766dac8cda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "gui-4.4.0.jar",
          "url": "gui-4.4.0.jar",
          "size": 73962,
          "sha512": "7f433f7c93d423e25cb58e0ab69205a7a6875a0408dd153e22b0f1b83e146de7beec5ee4b9b392ca1728a71744aa0ed35162b18552087849f13590eb3fdab4de",
          "sha256": "6018a22a83febc53531a864709ab5912378280f69b29a26557ffabfaf09c6b10",
          "sha1": "4166a701de15afd0a3e2b14de02e93541208b9e4",
          "md5": "c35d8f8a84d46f5940cdb1766dac8cda"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gui-4.4.0-javadoc.jar",
          "url": "gui-4.4.0-javadoc.jar",
          "size": 281232,
          "sha512": "b1c9d62679e03e43fcf0f977390d2181d37fcbffdcc8728e024f4cbf0c3ade2ec9e00e702573f93935adb624f1a9bcf6709df1472f4cda8cf5b7f877efbdee7f",
          "sha256": "4f885678d3076d451ea52783ce1005dd321a46092f47c73141721b1ec5de36bc",
          "sha1": "ed3092d1b8fab4f3bcec55087617bb505aafd395",
          "md5": "adfc02538830926ec961b42fbb148308"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gui-4.4.0-sources.jar",
          "url": "gui-4.4.0-sources.jar",
          "size": 35408,
          "sha512": "ba2de6d35e6d670a805916552aa17f9a1da2a1c8402822cc2348d6bf11151d1a4a668cd7a8195c265a4b7528a0fab2577923f98d830b5bde6a004ff9f9e36bed",
          "sha256": "0fcbb29ef767967b953d06c43e38abb33598104d24c7e61c59a01dc2dff8cc83",
          "sha1": "e33cc0ea91e8731ef3851987f66aa50985d64ea0",
          "md5": "71ca8d52a8ae38a820e1e6d6b3b8df56"
        }
      ]
    }
  ]
}
