{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bemode-feature",
    "version": "5.0.0-rc.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-5.0.0-rc.6.jar",
          "url": "box-bemode-feature-5.0.0-rc.6.jar",
          "size": 13663,
          "sha512": "1fbd950faff5bf378099c1be65d364e7c2b62fbe81929df5482ec8b5f2c5fd67c8ce108d2c4054140b1b93358789160b3575ad3e08ce8156ab1a53c8bd254a1b",
          "sha256": "371fc4427a1d821b7ce548b9a1fee40768a808e89c1a7f0281366a4716793483",
          "sha1": "f03aa77a3c2d420bb613ebd613f21f0942a93049",
          "md5": "3beff05c39ed70f4e7618ee7a7a6131b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bemode-feature-5.0.0-rc.6.jar",
          "url": "box-bemode-feature-5.0.0-rc.6.jar",
          "size": 13663,
          "sha512": "1fbd950faff5bf378099c1be65d364e7c2b62fbe81929df5482ec8b5f2c5fd67c8ce108d2c4054140b1b93358789160b3575ad3e08ce8156ab1a53c8bd254a1b",
          "sha256": "371fc4427a1d821b7ce548b9a1fee40768a808e89c1a7f0281366a4716793483",
          "sha1": "f03aa77a3c2d420bb613ebd613f21f0942a93049",
          "md5": "3beff05c39ed70f4e7618ee7a7a6131b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-5.0.0-rc.6-javadoc.jar",
          "url": "box-bemode-feature-5.0.0-rc.6-javadoc.jar",
          "size": 152460,
          "sha512": "4665bd3f5ca4a7bda7452e67fccb24ca1f795bf9400d85c1f9cf8d7850022cc5ec6fd6963270b10fe2dbdbcb7f3d31e40299aa965078f92801dead5395fa5a63",
          "sha256": "d24d6bec4242b6831892c037634a9627e96bcd0cb6106a813cf1ea229e3dfe5b",
          "sha1": "701dbaa4f0515bc18456630c03c7a3bd20724ccf",
          "md5": "a60bd98e75beb8eb4b631ae70b220f77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bemode-feature-5.0.0-rc.6-sources.jar",
          "url": "box-bemode-feature-5.0.0-rc.6-sources.jar",
          "size": 6675,
          "sha512": "3354e092ad9f3f768ef4729e9ea722fca1f48d6c5b7fb45c99ce1521e769296490b453324c97cda40445b5f497cdcd26c3603bf6c9222fd3e4d33029911ba079",
          "sha256": "63b03895b7217509972f26258bff03297033c8f04e49735557b4f84cf23e29b6",
          "sha1": "9764997998c14bed5c636b62ae212f8362731694",
          "md5": "96f5fa4b2b330ca1f27a628ae13dce91"
        }
      ]
    }
  ]
}
