{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "5.0.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "box-category-feature-5.0.0-rc.1.jar",
          "url": "box-category-feature-5.0.0-rc.1.jar",
          "size": 52706,
          "sha512": "607688612e385be6e934566653036b531da6ece1cbb45f3502cbeb975c03babd728bf119fefed78870780e1bc6fc4da88746eca78cc8d0b49ade21ad6f7b429d",
          "sha256": "9b7dd541de3a22fad3291d3c91f49846282bd462657f43632ffe3853c1a5f203",
          "sha1": "c937985ebd3d2896e1ded9e1098a43069f2efe09",
          "md5": "0915bd99fc9bf0d2cdafeb62f3c01979"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-5.0.0-rc.1.jar",
          "url": "box-category-feature-5.0.0-rc.1.jar",
          "size": 52706,
          "sha512": "607688612e385be6e934566653036b531da6ece1cbb45f3502cbeb975c03babd728bf119fefed78870780e1bc6fc4da88746eca78cc8d0b49ade21ad6f7b429d",
          "sha256": "9b7dd541de3a22fad3291d3c91f49846282bd462657f43632ffe3853c1a5f203",
          "sha1": "c937985ebd3d2896e1ded9e1098a43069f2efe09",
          "md5": "0915bd99fc9bf0d2cdafeb62f3c01979"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.0.0-rc.1-javadoc.jar",
          "url": "box-category-feature-5.0.0-rc.1-javadoc.jar",
          "size": 165500,
          "sha512": "4f237ec063ae68df9b3c5db0b63c92d9cd3c137dd315d7e3c53457116db886958db9d5c7d5d36e186b8653465ff8c4e11108a2dd2d755d2f4e00ce734db7b1c5",
          "sha256": "36d1be2820e5c14d006a060660513d907ffbad72578ec06a17c98fdef3cd2fab",
          "sha1": "d1a708b1aaf68a12857d9d6fa918f7383017453d",
          "md5": "e9604f94ed753dbfe456c0967d142a28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.0.0-rc.1-sources.jar",
          "url": "box-category-feature-5.0.0-rc.1-sources.jar",
          "size": 35176,
          "sha512": "3223b16b370c23c27e8180c15abffa5bd1d97ac8544fce0c4fb43099137dfa25631aa305e0ab02df9fc8a928b834bdeaf2963578f7f2a9af7e6b3f5dea04739a",
          "sha256": "0e2c493320b5dc2781eaa8d4e0b5f77fd9bd19232c41ad1d9c68f30ac8febaf3",
          "sha1": "f361f68852dd4c768b027b749fa16aca4df973e1",
          "md5": "b837450d8c12a85161f27554c8117ce2"
        }
      ]
    }
  ]
}
