{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "5.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-5.5.1.jar",
          "url": "box-stick-feature-5.5.1.jar",
          "size": 59019,
          "sha512": "edef0aa4448aa4ad74f2c1db379fe4fa73ae63a16a6fff101c50b37495a27a22a83977b7c67cfc007146af4428eb623be8e1eb4b1565f8230b9ee374f9c0cbe4",
          "sha256": "829a0505610859c98c3d214d6d36bd3f5545a780ada6a033b370cde4fe7b74f7",
          "sha1": "be10d8bc3db36d4d021bb66f7ebe41d9b08fc655",
          "md5": "c52ef8290e18e14a8aac2d6d5f5340be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-5.5.1.jar",
          "url": "box-stick-feature-5.5.1.jar",
          "size": 59019,
          "sha512": "edef0aa4448aa4ad74f2c1db379fe4fa73ae63a16a6fff101c50b37495a27a22a83977b7c67cfc007146af4428eb623be8e1eb4b1565f8230b9ee374f9c0cbe4",
          "sha256": "829a0505610859c98c3d214d6d36bd3f5545a780ada6a033b370cde4fe7b74f7",
          "sha1": "be10d8bc3db36d4d021bb66f7ebe41d9b08fc655",
          "md5": "c52ef8290e18e14a8aac2d6d5f5340be"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-5.5.1-javadoc.jar",
          "url": "box-stick-feature-5.5.1-javadoc.jar",
          "size": 203136,
          "sha512": "0d52158c74036b167dd8102f1de4261920bb5dd13eb17fd9ee394c58e801f601846dd25dbff22be02f0b9a069a3e45def6e86aed722e7409f55235325bc2aed5",
          "sha256": "ad3c88220c84edafc3d7292a61d00e2993cccae27a7da0e2474c8293ddc0d1c8",
          "sha1": "9e0563079d4c6fbb3d2423d7aa4a539bcb574405",
          "md5": "df3966574fc7bb9ecb7c46937394f419"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-5.5.1-sources.jar",
          "url": "box-stick-feature-5.5.1-sources.jar",
          "size": 21889,
          "sha512": "b5faea457cedcdb72ef374bc625b4de9a05a3ae608fe5baa6ff5d8568277eb3908b0b99c9259c54ba5d17cd18a9a44a0db559742a4d4c511e4ec574bdced07de",
          "sha256": "a300e9b89236b0771d110e19f66ad4e0d2c9254539c974909d0c0bc79bcfe2a8",
          "sha1": "4078852adada84caad1789373f273c1ac57977c9",
          "md5": "a8316e9084eb1d499e883ea73f9ee5cc"
        }
      ]
    }
  ]
}
