{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99956,
          "sha512": "4ce2597e29b75855279ee49c3631c0b9f45ebe5a761a1243fbbfb99068d5716bcf404906671377138bcb1a265d97da111c164e6a6612fea30edb99a00b2c9b2f",
          "sha256": "55651f96189234c45ecf39fcf8bf776e7fa32c7ee301378ad239fa0196e6d48f",
          "sha1": "6f0228fce0868c149c7f0cc8be7aabe4fa191016",
          "md5": "a227aa6583b05b00a760fb3d46d729bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99956,
          "sha512": "4ce2597e29b75855279ee49c3631c0b9f45ebe5a761a1243fbbfb99068d5716bcf404906671377138bcb1a265d97da111c164e6a6612fea30edb99a00b2c9b2f",
          "sha256": "55651f96189234c45ecf39fcf8bf776e7fa32c7ee301378ad239fa0196e6d48f",
          "sha1": "6f0228fce0868c149c7f0cc8be7aabe4fa191016",
          "md5": "a227aa6583b05b00a760fb3d46d729bb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 241441,
          "sha512": "6e491cef06394ad8e7ec6e5c4a31444962a30ade1fcfb469a87694daa9c61d86b0e58e0f42f0168bcb92ccb6c8595d18dfb8de17b73aa0d966b86111d6b8645f",
          "sha256": "3b2d367a2cfdd20332333ce221cc257f17426cf5c5b7b8e6500d1621906ed8e2",
          "sha1": "9ffd5fd0ae6d45e5279c9054ebd3da1b29fb93b8",
          "md5": "f61d4ba1152f3b5393508bb482a026bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42871,
          "sha512": "006665a8b98235d3ce0af008b14a7e6df85cf0ae3182ad4722f4303fb27e977b92dee3b21971079af6ccad701ac6ea04f72d63a11f778e2c822f27a90afa688f",
          "sha256": "d0560060bd348f6d8bc5eef2286ff06bf6437d91d501bf5e85fea4226ad7a17e",
          "sha1": "511a3c2b79ec691b40ea46454abc8be03f524afe",
          "md5": "9afe90facfb6ccdcd48a6c0ed1845285"
        }
      ]
    }
  ]
}
