{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 93691,
          "sha512": "9483b59b40c241c87941de3db72be13a2ac0de330a2b80619e69e344a118ff0e25582e5e716f6083cdac583028cd06cccd9d45d916696d59a6fa485455ac4773",
          "sha256": "93981a1c0f3a15073f032b3442aba4557b10391c2d0f9b8f1454eba42d478243",
          "sha1": "69aaa9381e8c1190dc5adc3346d2b1afab070776",
          "md5": "c673716b3dc46f064a7822a7ffa3dfde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 93691,
          "sha512": "9483b59b40c241c87941de3db72be13a2ac0de330a2b80619e69e344a118ff0e25582e5e716f6083cdac583028cd06cccd9d45d916696d59a6fa485455ac4773",
          "sha256": "93981a1c0f3a15073f032b3442aba4557b10391c2d0f9b8f1454eba42d478243",
          "sha1": "69aaa9381e8c1190dc5adc3346d2b1afab070776",
          "md5": "c673716b3dc46f064a7822a7ffa3dfde"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 221596,
          "sha512": "ba3ad79ee5796f2fd94971ab056a6bd5c5dcc8f2e9469b7b0d37719d7788493119f11be5900a1f41075ba833a7636318bf9c82d71666bc04270e8841313aeb59",
          "sha256": "439c58414391de743b4b79b63cdaf1df8ef3ee5fe26b3fa777c2dcf1b482b953",
          "sha1": "991877cdd8b1ef691c8cf3ef2ebb361bc26d1a4d",
          "md5": "6c97f2355363f10ffec08792d5d8a8c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 39973,
          "sha512": "fcbc6f2fb6317dc04946d9d83d4259aefe5cc4feff7b4f328d5e45839a66da3eef4ce4a338314df96d254bb0f62760296860255954ff5bc7cd2b1f899c4f2058",
          "sha256": "52d8b9d936c5e4a8a0a9d4b6c3c47acd47683f5e4c5160883de0844487b24f52",
          "sha1": "b5c54b532f93cd51d581b58a1c996f05b54c73d5",
          "md5": "4553c64f87b381c8560ca3a47ba77da7"
        }
      ]
    }
  ]
}
