{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99956,
          "sha512": "82b3ec41ce0cdc444001768a28bdad383018f05a45eff195cf65e864ab7392bd68c65d6e01bfc8d53f5499fcb25c25277b0efe330e14a6be18b0231508fbe601",
          "sha256": "b54f724440ad2d2adb71e958623e7885b92e855703022d0941bcc5169473273b",
          "sha1": "778ce3bff2aaf3e6943011bebab191e8f0c683b3",
          "md5": "319600cb84e4820de19cf300c233e618"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99956,
          "sha512": "82b3ec41ce0cdc444001768a28bdad383018f05a45eff195cf65e864ab7392bd68c65d6e01bfc8d53f5499fcb25c25277b0efe330e14a6be18b0231508fbe601",
          "sha256": "b54f724440ad2d2adb71e958623e7885b92e855703022d0941bcc5169473273b",
          "sha1": "778ce3bff2aaf3e6943011bebab191e8f0c683b3",
          "md5": "319600cb84e4820de19cf300c233e618"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 240487,
          "sha512": "86fad7c931cae86bee99e3b8bdaae172545517b429aea84606f933aadaa66530467bd7ea0b0789f71226d77271f5c6d3771e8b462395b2178c6afcd4c5c1de2b",
          "sha256": "7e404b38fe863ce2e6e06f835689c7328c5d088b454de2219fc43ee8fc20538d",
          "sha1": "930208fbe6d24b350fac67321e5b634024a43cff",
          "md5": "c74a10b1b55bde040ed14900fa002c45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42871,
          "sha512": "375e08893e30b127fbf1b862408667826db32442e4511e09a97b7b2e1de51eaf1d86e389b97041fadad574c9a9aa2daa1c625cfbef261fb8cf766be3949c719e",
          "sha256": "4b74d9bf34cfa58e3fdfde4c376be3145ce64515a41360464228d9d5594a369c",
          "sha1": "8fc11d2d3e1b9a092185a9a000e1c74160a04ecd",
          "md5": "37419d406720619dede8b0162de5f68d"
        }
      ]
    }
  ]
}
