{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 95591,
          "sha512": "f2ab63d56189ecbb8e234122dc59c41b365ad638a41f15d6dafcc333518f556e48956a6bd12919facc993c531be1058b04c0567c706e7ea0a4b57b6bffe4f256",
          "sha256": "404aef0be5efc62e047c60ec145b8819c71e2599b8f5c92a60feef5dc3504b2b",
          "sha1": "83fe02c0459152cf39110fb7647f418f76c7d9da",
          "md5": "6e64f679f1cf28b8cdf14adec90c7ecb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 95591,
          "sha512": "f2ab63d56189ecbb8e234122dc59c41b365ad638a41f15d6dafcc333518f556e48956a6bd12919facc993c531be1058b04c0567c706e7ea0a4b57b6bffe4f256",
          "sha256": "404aef0be5efc62e047c60ec145b8819c71e2599b8f5c92a60feef5dc3504b2b",
          "sha1": "83fe02c0459152cf39110fb7647f418f76c7d9da",
          "md5": "6e64f679f1cf28b8cdf14adec90c7ecb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 235667,
          "sha512": "c6fe8f420aef7118029fab296f39ddadc28b63a4f5f1c79c1f31f35aa6873334b31af3b05129a95a7c5e734dfc5c2590d29a89fa50c740228f1323b439496e51",
          "sha256": "e4641ae2db40a79c6a408b43474254d69503726cb5e323e157f8c079208232f9",
          "sha1": "9651019e280f43d3cde4eb273f3d78d29a2581cc",
          "md5": "585acf876667b36fb7e9fb1b6c28c8ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 40481,
          "sha512": "2d56e85790bd4acdc21a85fb98c2f7c198efb0c6343a9d29afafc10a7d015ff7d530d7172bc1d6c9a7afe3a94308bfc7c2714b84c44ab2175ad4b493498341f3",
          "sha256": "f783d712ba849d978f60f0010c61e7da91e1beb5ffc57e2526d12eed1ed32605",
          "sha1": "65515204efeb98fe084b2105192fb6e139ef56d5",
          "md5": "de6469494ef9c360f10e782a613f0455"
        }
      ]
    }
  ]
}
