{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 95591,
          "sha512": "351fea47eb30bee839cbce21605b76c9896a6110c36a8356574f488bf632d203accac0e390819e6a65561f4bf38a3f4de9eba1b26a60af48d9f8e55275fe6da0",
          "sha256": "ec5c76fa629d5cf28b7ee9def8dfc58f888a3371970b96ae6794a91faa716e01",
          "sha1": "647fd643587216ef600a034a52fd02df5d19de75",
          "md5": "f36b18103311ebd2c16d870e5dc94640"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 95591,
          "sha512": "351fea47eb30bee839cbce21605b76c9896a6110c36a8356574f488bf632d203accac0e390819e6a65561f4bf38a3f4de9eba1b26a60af48d9f8e55275fe6da0",
          "sha256": "ec5c76fa629d5cf28b7ee9def8dfc58f888a3371970b96ae6794a91faa716e01",
          "sha1": "647fd643587216ef600a034a52fd02df5d19de75",
          "md5": "f36b18103311ebd2c16d870e5dc94640"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 235667,
          "sha512": "b7e46492d2bce8ff92aeacd3ac5368e96c28772bcc7e4dcd28c99e5f8e5c14aee423a5077536aed166dda3a8ea4131a5bccab8a5c16200a4fa3f56fb3d9c5ed2",
          "sha256": "a8c1a3f5cd64e8e57e2a54b3b84e6474ade90a087a8ef5225b3f0ba407dc6989",
          "sha1": "bf23b3398fe4e715731b834a42587cc2195ff7e7",
          "md5": "33a5ab87781bbcba7e8376bc25c462ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 40481,
          "sha512": "b35826419cc012236618551f750545604a39216210abdf5522365caa3a77aea80103de1cc6352622ca38d1c40e69280910f5b30dc488744c11c9660099da97b4",
          "sha256": "aa59b546f2c9a822facb254302886f7324d714b570cc877dbef57cc70b9a6aaf",
          "sha1": "2b04ca154975fa3dffd968b03883d15346f95904",
          "md5": "56628dcaf4e11cb4ecaf80dd02cf494b"
        }
      ]
    }
  ]
}
