{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.siroshun.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100297,
          "sha512": "17f1f4087355fd3274c6a0defd7ffb1a30c08c1081ba571eb9950491274746574a55a5d967b06e87fdf8b3efc2ef85192d6452be81add75fc92afea2d089d120",
          "sha256": "47f841182f2db312e9921e336c7289a650d28333ef2fd5cb9a19212493f2a952",
          "sha1": "5d7216d7f97d7e67ad06d33815e0319bd0789b64",
          "md5": "ddf61fe712b05d2217f12e2dc671c3b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.siroshun.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100297,
          "sha512": "17f1f4087355fd3274c6a0defd7ffb1a30c08c1081ba571eb9950491274746574a55a5d967b06e87fdf8b3efc2ef85192d6452be81add75fc92afea2d089d120",
          "sha256": "47f841182f2db312e9921e336c7289a650d28333ef2fd5cb9a19212493f2a952",
          "sha1": "5d7216d7f97d7e67ad06d33815e0319bd0789b64",
          "md5": "ddf61fe712b05d2217f12e2dc671c3b5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 240319,
          "sha512": "a7a342e4b59d1b4fc05bc14dda76da5ab4487e6d64edb78453b63ffe0536fec3199d9be81020c6a07e4562fd44a6fd98cc0321f4268967bf2949ea030875aa11",
          "sha256": "4940768e9eb1767de7ecf12da9a6715518a2f8602b55eb3fb0836727549a5714",
          "sha1": "028dc570acb6a7b0d303532611d05cf1b8ef577d",
          "md5": "3f571d501d38d62dec9adbe2b671b699"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 43092,
          "sha512": "3a8191e3bea1be6d5ae256292975a1f23a62a3c094e504168399cda074817d610d84156f438d5e171eef4c5de8e4a195425ab5749ce2615e4748053127f334e5",
          "sha256": "27d5833aac810c797b4062387632cb813569a35e0cca1b11eb5d09e29c9998af",
          "sha1": "a04e319ef6cd477e10e3277ffb2b4f9da2d60758",
          "md5": "054645215876da7a4914033334408eb4"
        }
      ]
    }
  ]
}
