{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "ad9c24696f50c327d9da1072f5f0e5435130650e1a233125bdd969bf10c376b911a9a55d354226ab9392cfbce80c009e59dff1fe0b8ff480b109bc95f304f83a",
          "sha256": "11ab43acb450311a9a10ffa816b2245821d62139e1749f672f31148437bf30c8",
          "sha1": "83c43e319ad9e01adc092a640fc0a092ab251150",
          "md5": "08bd6971a3a5c9b3adfaec82287be3ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "ad9c24696f50c327d9da1072f5f0e5435130650e1a233125bdd969bf10c376b911a9a55d354226ab9392cfbce80c009e59dff1fe0b8ff480b109bc95f304f83a",
          "sha256": "11ab43acb450311a9a10ffa816b2245821d62139e1749f672f31148437bf30c8",
          "sha1": "83c43e319ad9e01adc092a640fc0a092ab251150",
          "md5": "08bd6971a3a5c9b3adfaec82287be3ad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 240487,
          "sha512": "8a4721c0fbb95fce719d594343ea50ea172227bd0f6c25a6f06a08536611d1311e70bbd1aae94def8c4e4b0d0441dae94ef4a91ed4c2ffd1b304855f43527b34",
          "sha256": "84de4ad8bd06cedae982d4dc69f70be6197814d224ce0f4735af632ae7ebc12d",
          "sha1": "57985d4fa6c8a5549a91b7c09ee2e0201c9b1a10",
          "md5": "a619fdce79af288b7a8bece612eaae79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42929,
          "sha512": "af76d73f7b79245ec83e8ba20835b489c7e0216804a317dff2ecb2c38cc25a70bb5e9c70bb979d237f252d562601f3e0a627dbf2142ed06fdb899fc3bfa2711f",
          "sha256": "4a71315dc65cf596fb629fbc36f098f6a6ee1939d930adfb70b07a5521f2b831",
          "sha1": "d7bd59f64a265a3035b0684bba1233c85b9602d6",
          "md5": "3f3fd19a421c0c6b80c7949dab440410"
        }
      ]
    }
  ]
}
