{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "e446342bf31f6a51f44834d73b5e2e1289fd2419ad4034b82789bbdfddf5374d13562ce8d0c2d9bc64d993ffdfb11c5c0ec481499da4e25bb93b174dae0cd1cb",
          "sha256": "2cdb0545690d16dd755d867a6a05aeb9c0d79a3ff07fec8f53a83594ed69839d",
          "sha1": "7e373e0ba79f8a71c572f2ce197a3c7e94c4bb08",
          "md5": "173899898c588ea2239125465f390912"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "e446342bf31f6a51f44834d73b5e2e1289fd2419ad4034b82789bbdfddf5374d13562ce8d0c2d9bc64d993ffdfb11c5c0ec481499da4e25bb93b174dae0cd1cb",
          "sha256": "2cdb0545690d16dd755d867a6a05aeb9c0d79a3ff07fec8f53a83594ed69839d",
          "sha1": "7e373e0ba79f8a71c572f2ce197a3c7e94c4bb08",
          "md5": "173899898c588ea2239125465f390912"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 240487,
          "sha512": "8a0e82a557e70b9f49a65c5f79c5297a6bd0edcc2969faec2158c6802a7b7d3d600f70aa164589966811010052418f7ba060dd943af3f82a84bf3c5dda353aed",
          "sha256": "12556cb5855948cc6d915c3717bc6f7b839dd30fc3a45cc784fc90bbd3a65e6c",
          "sha1": "44019a495abd5380ad4e276126fd58f551924bea",
          "md5": "b64279b588a7487a3e6a507f365451c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42913,
          "sha512": "e20301feeb78546689221857c3a7f96cacb588cfe2f6b265a6753b179c337357021fd8e731f0d0d0dab6989c0288234ab1da62bc1c895d0a3b8e4e10901e7a77",
          "sha256": "532475c3869e62ca09df5c2bf622a001c82e6c95af59e13c17c7d2dab1d5d51d",
          "sha1": "d25b28c6dbd515722b496dd78838753f6fa3c496",
          "md5": "ad10d7451618845e806c82542bdc7d05"
        }
      ]
    }
  ]
}
