{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 87963,
          "sha512": "ace38f60f6d1f901dc306b1f45c9caa3910cfb128f80c01a6341ae27e92bc6f6e4fa30b126e6e636971a21fbe434056a8d7db683523fb00628509dd66c6d4a8b",
          "sha256": "3b865d7bcfa104be79955d9ed9a5ac7fc51cc3a6359f4782f2e94cb9c53dee6e",
          "sha1": "67c265246c67dfffc5defc8ce80f5879ffab2583",
          "md5": "85d38ec2887db8936efbc0158439cf4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 87963,
          "sha512": "ace38f60f6d1f901dc306b1f45c9caa3910cfb128f80c01a6341ae27e92bc6f6e4fa30b126e6e636971a21fbe434056a8d7db683523fb00628509dd66c6d4a8b",
          "sha256": "3b865d7bcfa104be79955d9ed9a5ac7fc51cc3a6359f4782f2e94cb9c53dee6e",
          "sha1": "67c265246c67dfffc5defc8ce80f5879ffab2583",
          "md5": "85d38ec2887db8936efbc0158439cf4a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 281212,
          "sha512": "cf443763911105716117cd94e956b9bdcd6d9f6cc0c493ef59b878741a7d67eee47407251e9a37b52a26f9544960862d23adc7607a27b3fd66cd0d00a2ba82b0",
          "sha256": "352fa19e32493b7866f60e66728570749335fb00fb5acde364903f159ba0a225",
          "sha1": "8ae5beadaabed8e15e6923d77cb7b34d2eb04ff2",
          "md5": "aa761ee173c1956f0eb1eaa2112f7233"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 37656,
          "sha512": "217d3768c8d3650a88cc35a57cafc6cceb6659533c7de585d06e1b2fc148a0dd62550661ab9c4f41b443367a3b6b073b3573e34d00ce51502505a49ce72c85e9",
          "sha256": "e7638bf29f0edc3055958a01f0ac6a4710d4e43b38ddf07f536bda9ef6688645",
          "sha1": "433ba86d8805aac191d8e707dd58759ded9ab2ae",
          "md5": "d2c9b205fadef7e27e21373ac2630a6d"
        }
      ]
    }
  ]
}
