{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 95591,
          "sha512": "2bf19cecb348611608971ff5132f6e7f2cfa56f6b1755b9c71b732efcde00d440230aac128602bf5567958c2c1a30a072881d9204a1ed626bbafc2756b4411c2",
          "sha256": "500180869c44fb9c169e97bb25eef3afda73dd2f1e57063ec79f25f2f8fc398e",
          "sha1": "25d7609502972d9a157631543b4c83ab0f9702f8",
          "md5": "26842abfb403b08bf65455220fe45d59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 95591,
          "sha512": "2bf19cecb348611608971ff5132f6e7f2cfa56f6b1755b9c71b732efcde00d440230aac128602bf5567958c2c1a30a072881d9204a1ed626bbafc2756b4411c2",
          "sha256": "500180869c44fb9c169e97bb25eef3afda73dd2f1e57063ec79f25f2f8fc398e",
          "sha1": "25d7609502972d9a157631543b4c83ab0f9702f8",
          "md5": "26842abfb403b08bf65455220fe45d59"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 235667,
          "sha512": "fd50f060de82cf31724bd529b0e6531fc649bb4a22cfd3d3e9dd3e22ba96137a5437f8c7f2eb7fb74f1d128151a188c29c8a722aecd015759555849be5cae064",
          "sha256": "0418d374dd725302d1ad397349c709fce3954c05a8f484c8685108b92af838cb",
          "sha1": "f9d8d527d87257d484cbf09605b8e44c54249f73",
          "md5": "b198ffcfb60b19a78504e17bb29343b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 40481,
          "sha512": "1dd95f3cd4e9d257a4cb9a64b38fb96c3447417437b8f54a148a64b4c2501c7333fef52e5109cc8680c9e65c41fbf993b7ec60dbf27bd30e3f8fd13437813ef6",
          "sha256": "f043aed63b894c12ff69a8b130a7ac6d69761aaa7794d07a955dd2554175cfd8",
          "sha1": "6e8fd1072133a125e677f6effc3c65324e1954fe",
          "md5": "ddae254f65f94fbb16029fa08c34dc82"
        }
      ]
    }
  ]
}
