{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 95431,
          "sha512": "cfcf2dee3d01efdd5a112fcfdf4df8d3e2c4bd793cdb425afa028277e22805a0b2dabc46a0b7ab4cac22e5227e148593e697fde784bfc5e4237eda6b17d3a26f",
          "sha256": "d50129cd36cd13c474ccc5818e780e6343fbdd4994e52041e56078c5518ac13a",
          "sha1": "87d7d1c15d9104addbc4a057c720870d51a1f475",
          "md5": "f7a2d3d53850426511d4727b58de2467"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 95431,
          "sha512": "cfcf2dee3d01efdd5a112fcfdf4df8d3e2c4bd793cdb425afa028277e22805a0b2dabc46a0b7ab4cac22e5227e148593e697fde784bfc5e4237eda6b17d3a26f",
          "sha256": "d50129cd36cd13c474ccc5818e780e6343fbdd4994e52041e56078c5518ac13a",
          "sha1": "87d7d1c15d9104addbc4a057c720870d51a1f475",
          "md5": "f7a2d3d53850426511d4727b58de2467"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 221747,
          "sha512": "a411cbfc02ba7ec2ab49a410783a5a35c6d665d233e7d95222c24460c4b8f6e0332f199ca6f7335617b83c7c86bbc1ebeffaba5dc63fea65ac31721854c3bd2d",
          "sha256": "665738617c38e28d66fd69299123a9fe7f18a885a5cdacc1c998089179d7bb20",
          "sha1": "98fead243d99bd20f96a8f45e3d0427898e33ee3",
          "md5": "43b55f368165674af95ed3126246fafe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 40478,
          "sha512": "37d64368cdd68ddc201dbbc975ae52c3afa559d4839ca21b6a055c881e91c21776552dcb03d3db57e4dc5b7e6be3fb1a68ed8790c60d7a2d5993076e7fa795f5",
          "sha256": "a63e05cc32471fc194086c241c1297dc40cc6468e5931a274938ee40e63ab593",
          "sha1": "11ded9cadd29a0fe31cf40d126c1b7c40c4d4a80",
          "md5": "b54c979f7b709a3c9b204fb29f792759"
        }
      ]
    }
  ]
}
