{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99956,
          "sha512": "293437669be5c98c11d0a2a4a931d2b27f90ddb334fbe956a7a52af3dc76e7eae3027159fc75f7d4255199a4d918eb592e5a1fddd13de8fa2210bd3de9d1d789",
          "sha256": "347e7dd5fb33c90653da08a020895169c6dde19e90747ec7f727da30eed2be2f",
          "sha1": "b3d128a721a0313159c72857b698ef2e6b904b3e",
          "md5": "7aec259c202512305a352745311eadff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99956,
          "sha512": "293437669be5c98c11d0a2a4a931d2b27f90ddb334fbe956a7a52af3dc76e7eae3027159fc75f7d4255199a4d918eb592e5a1fddd13de8fa2210bd3de9d1d789",
          "sha256": "347e7dd5fb33c90653da08a020895169c6dde19e90747ec7f727da30eed2be2f",
          "sha1": "b3d128a721a0313159c72857b698ef2e6b904b3e",
          "md5": "7aec259c202512305a352745311eadff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 240555,
          "sha512": "a6b542f9a4d98a81f8ccbe97a15e8a02aa89040b3de74034f2329f249d11a6cb77eeaee47f65aa7a06e475585575d3c8171751920b5e644d19b206198b1a6222",
          "sha256": "c818a0dce9d56eaa12b5acbb49cac8cfdc20a390de031c60f6385d4ae5a62d88",
          "sha1": "5d8f6de628b892e0d26acca8fa9f7acbbe7b308b",
          "md5": "2cf870a7c574413e0499a4840916e010"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42871,
          "sha512": "3c34e08f9845085eda9ff0c8215277bd72fa8e825917ab2fd817922390f7a5b7076c50a1c269494d95a15461cb74880b98214b0bb68b92abfd8de30a49d8bf8b",
          "sha256": "b869a3104732f6f900a7cf8179b5489e54900fe04b71119c8fc205289c802b06",
          "sha1": "14d66b8403f2b15f5a0979829ee26ef62a094805",
          "md5": "27b55b8c3bb5b6c25cf367973c3f4741"
        }
      ]
    }
  ]
}
