{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "ca70936655dc8b4169eb2f56aff356d23133f27091bf18ec4d5aa77da94855eddffa4e7efa38f457044489f9d3643e651d96bacf3d26659e073cc039a349c1c2",
          "sha256": "76c13dcbed22b03ce0e3552a30c636f691a47b428a54e4afe8348d56d3f42429",
          "sha1": "643fb327d9ea450c0fd40089a66d858dbc840788",
          "md5": "78495f29dda61bc8b9fd1a3b1383a30c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "ca70936655dc8b4169eb2f56aff356d23133f27091bf18ec4d5aa77da94855eddffa4e7efa38f457044489f9d3643e651d96bacf3d26659e073cc039a349c1c2",
          "sha256": "76c13dcbed22b03ce0e3552a30c636f691a47b428a54e4afe8348d56d3f42429",
          "sha1": "643fb327d9ea450c0fd40089a66d858dbc840788",
          "md5": "78495f29dda61bc8b9fd1a3b1383a30c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 240487,
          "sha512": "6c0a734bdf48c90cd59d914bf15135d90c36c53798474a64a8b1f27c8554ad5e35917777d77ad21f6d12cb7c2e232df9866213d7585fff6fadc205a19559aa46",
          "sha256": "8f6f56489bb9abc16ed904646d5fc199b7b1e6543b2149c442a6ac44407ef738",
          "sha1": "6fd9ca33045258e491a19e05a15b3e81f830fb7b",
          "md5": "d144aad0f20d4e3cb1263a7f89d12962"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42913,
          "sha512": "8844ea29c844bb1fc53c4b7f8194745f3faa132445deea2283d48f984d173827b2480a29f56b43e4cd526ead88610d98c05234d7b147060181aab6a8f8ad6c0d",
          "sha256": "a0a7dd68c2248e67332a047ed5c50d58e05854448f2a514fb68acd29567c5e19",
          "sha1": "7062a9ed65836d269f2bc8ff725ffdb3f6dd6320",
          "md5": "e7a06ed7b6e4fa7aff31019f776f33b1"
        }
      ]
    }
  ]
}
