{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "c4a413f28dcd66d95789629d08b888e6dbeabfae13af214ef483a03ec1cd8c4d804f30ba6db90dec5041ab4d9d7d5736a7b4926007eea5d93019d890f478e663",
          "sha256": "84befcd50f1922271b692902170d52647928236439f3cbbab10741cabab1f3fc",
          "sha1": "d573b3dc4046ddd5f6b223b9ef3f2ee02422b75f",
          "md5": "f0a838cd27d2bb4b8660171647984cbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "c4a413f28dcd66d95789629d08b888e6dbeabfae13af214ef483a03ec1cd8c4d804f30ba6db90dec5041ab4d9d7d5736a7b4926007eea5d93019d890f478e663",
          "sha256": "84befcd50f1922271b692902170d52647928236439f3cbbab10741cabab1f3fc",
          "sha1": "d573b3dc4046ddd5f6b223b9ef3f2ee02422b75f",
          "md5": "f0a838cd27d2bb4b8660171647984cbe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 240487,
          "sha512": "6f645840439bbbf0f598314a4cbf5a1bded8b984670c6e60cc1fd53d4d506c7ba548ace7deec7b54e43acb978998ca9f4efb91737ce32b75cf666a036ae77579",
          "sha256": "326de2a82766db5514665ac6cac89837d39052ed82a4e016110628698db7bae1",
          "sha1": "eba5e4c19997e2dbd90ecbc94715d3e32a527404",
          "md5": "889bb4e285746af8bb211afe363bf035"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42913,
          "sha512": "f4467350e54455a62e8c7d1b43987724a12353a83203d270c2666a7aeae1ed10a7b7497a823e62151045145dc5400a8673188d724c6fc8862c08961be6792022",
          "sha256": "e3dca7c845d37cfcdbd34164b5c17a21696a24675b1ef1f070bee9913b04c710",
          "sha1": "c86bb90d0a49b494504ab0c16dac188ebabc624a",
          "md5": "315f1d05e78d5ccce85d2ddb733a2bba"
        }
      ]
    }
  ]
}
