{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 81579,
          "sha512": "90a5b1b84ed1737e38eef84956773731f64475a03793fa8a3d4a8fb0af76fdadcc23b1994f9f922474d0359e0c35d34caf98b866a85d87e7a6b5a8e01dd42ad7",
          "sha256": "c8b02ef132960b52cbce42ce4fc5ac0dc6df0ac80e96c5536897f360ea6caf1b",
          "sha1": "44772d7cff84f99dbb9e800fc9003fd53d74f800",
          "md5": "42709fd0cfecad9d08175e8bcc34e0a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 81579,
          "sha512": "90a5b1b84ed1737e38eef84956773731f64475a03793fa8a3d4a8fb0af76fdadcc23b1994f9f922474d0359e0c35d34caf98b866a85d87e7a6b5a8e01dd42ad7",
          "sha256": "c8b02ef132960b52cbce42ce4fc5ac0dc6df0ac80e96c5536897f360ea6caf1b",
          "sha1": "44772d7cff84f99dbb9e800fc9003fd53d74f800",
          "md5": "42709fd0cfecad9d08175e8bcc34e0a9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 275796,
          "sha512": "c7cd0797452b845463790f3f6f5cd99d62df7d97f880cfae5a484409df80946f134066a1d71f51f407f6974ba326968541cba83b7d91090d0402ec0e1819230e",
          "sha256": "220364d2c7569a4681ab114abff186591c3c524839f016e4c64e3eaf35561ec2",
          "sha1": "bb67920299ba69f5c98e2fabca9f1d782a74673a",
          "md5": "ba812378b6a946c512d18b297d6ce3c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 37817,
          "sha512": "9b37726043aef84d589961714ff26e9c556989004447ef574a7729894b2595248c60f5a8266c1d47a66b11c621803432c31bb719f3199b361a5cb2d2d5e42524",
          "sha256": "03a93fd5f73d26dff0a323fc6648698f13bcfc7396db5358982aace710af1b9d",
          "sha1": "cff8f1c57d67eade3da3a8d2fcb0572f5d58cecd",
          "md5": "0edca9b012db0dc900266eeeb61c18a5"
        }
      ]
    }
  ]
}
