{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99617,
          "sha512": "b890b4ab489e7c67697546ad7dabd1db00e40d4685dbc6eab89c1d9e44263943eb629af79e47b23cb382b479a73e9e84f6debcae8ff58e3d538ed2fef5e4b7ad",
          "sha256": "d064f4f238ce16e3ffbc3484d4e4828e890c927bb7cf689d4bc01df18a98d9fd",
          "sha1": "d0ec186bbc50910c2d74161a90640de1ebf1bdd6",
          "md5": "32bff4f19f24132420abeb137799f08e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99617,
          "sha512": "b890b4ab489e7c67697546ad7dabd1db00e40d4685dbc6eab89c1d9e44263943eb629af79e47b23cb382b479a73e9e84f6debcae8ff58e3d538ed2fef5e4b7ad",
          "sha256": "d064f4f238ce16e3ffbc3484d4e4828e890c927bb7cf689d4bc01df18a98d9fd",
          "sha1": "d0ec186bbc50910c2d74161a90640de1ebf1bdd6",
          "md5": "32bff4f19f24132420abeb137799f08e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 244333,
          "sha512": "c84de8873eaf84fad690d901330744820381b8064029f4049aeab9cd561b2196791c925433d9344223522a6e3c3777ee530007dbd67f34d2317b769bf2dee7e3",
          "sha256": "2ec18748ae9f32c992894c9688897c515ce185e9ba9fdc7dcf96fa0b791030ee",
          "sha1": "4a5898eb5c4269f00f4b5f46528a25933f251eae",
          "md5": "a829a7b2a3b883df7b5ef47da88cf8cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42551,
          "sha512": "151527fb5a4b5714118831b67e1930ad2c4abd76abe5edfd5f61a7bcf22e863e9dc0dad31c9bc7c7ed7b16ef66777aebe15f5fa5a29a55b4e2d598f54708c3fc",
          "sha256": "8ba17921934b345fdd1284c6063108257ad0773cb0525a8375204a26e1d4bcd7",
          "sha1": "8f138f5d66589c56ce943debeab3e13c22206a7f",
          "md5": "3ba99adf9dc28dffb2fce879fcb6ae69"
        }
      ]
    }
  ]
}
