{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "72a5d42ac4c6eb287684f82fc7cda17b41071ee83406d7c751dbd3407eb700f3075ba4ec6655c7d9e33d2a8a6c7557a0f48520d0dd21819e8c88ddc22d72708e",
          "sha256": "aac1b0e4c60058f8243256d99dd05ee46b31501b1d7d3585abd4fe5b32403be3",
          "sha1": "f39ada2fb1fb19a4ae5bc094bb47dc3815382d0e",
          "md5": "98b8424f707e169854e694e84495613c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "72a5d42ac4c6eb287684f82fc7cda17b41071ee83406d7c751dbd3407eb700f3075ba4ec6655c7d9e33d2a8a6c7557a0f48520d0dd21819e8c88ddc22d72708e",
          "sha256": "aac1b0e4c60058f8243256d99dd05ee46b31501b1d7d3585abd4fe5b32403be3",
          "sha1": "f39ada2fb1fb19a4ae5bc094bb47dc3815382d0e",
          "md5": "98b8424f707e169854e694e84495613c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 240487,
          "sha512": "1706b8416b2ece36b212ff0e0f68cc2d812a9c0ff59ac829c961c024eb0710619eb87b67d657a47a34b9e209a859aafb44d20f5e30fd4ab1aeda7ec1a5eac3c7",
          "sha256": "4f5380be2aef08271f9f4f747699faedde963f9ef8a616c8825eb49f5e555423",
          "sha1": "34f4587f59d34e197b816f02b6b72b237bf97beb",
          "md5": "8ec29097a818b7056230d2baea2dc2ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42913,
          "sha512": "7ede656be14ceaa69573bba39fdea391f5e3ffb4fe11650429c05d7d9947057d1067cd9c6cf7c03d14f5ab2f137b4c94a82e21b87cb16d17c9446bc6bf294f24",
          "sha256": "f8c2e34f0a1ec0556c670e16e5d0f77b24a967e2115204aba6d471c591d837aa",
          "sha1": "90a17f703f8c7d14055e0f578068f595d5bb8cd4",
          "md5": "2f22328807f6e519419a8b139498cd9c"
        }
      ]
    }
  ]
}
