{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "524d52f7e303bca0cb6001ec06307cb671eb32d40fd470d527b1a82dbec24ef797c6f08778a0f93b0a4cb588f4679a8ef124cfc9bf9a84ee6b53ed128557e18b",
          "sha256": "4525ef3b1b25116a6144a597f1ba60af4b145e306ba598806aecba38cbe1045c",
          "sha1": "b538a72ec44492ff70ba9a8dfab6b7a768575448",
          "md5": "2f3c2623767edb6ac4429a0610d776d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 100075,
          "sha512": "524d52f7e303bca0cb6001ec06307cb671eb32d40fd470d527b1a82dbec24ef797c6f08778a0f93b0a4cb588f4679a8ef124cfc9bf9a84ee6b53ed128557e18b",
          "sha256": "4525ef3b1b25116a6144a597f1ba60af4b145e306ba598806aecba38cbe1045c",
          "sha1": "b538a72ec44492ff70ba9a8dfab6b7a768575448",
          "md5": "2f3c2623767edb6ac4429a0610d776d1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 240487,
          "sha512": "ba9b9b65a88bfacf24fb672410796cc128490b3c923f92aba8ce96e321cc22ea7e8bca2f9d4c657415e1ab45a1e5ff962078d7406e38af3f2ac3a1844b7b5c0d",
          "sha256": "dec7e3b16537bb4996ce24f5e3e3c4628624f9cff9b4e92edf04261f19b85af0",
          "sha1": "9503dfc06aa7d0895052bfbbd0f33b71a39c83ef",
          "md5": "e89df9fac7a24365070cad404c53673a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42913,
          "sha512": "8a5fceed98471d6fad4e2d6b153b3b02f7aa2922af10c22a529ee85e53745798c141b347836506b98e0c80c5fabb36e4fbed5325effe31d8347129498a4e86c2",
          "sha256": "2dbc9a425dab5fbad481e4d2dbfc804a38d08e2c9af86e3e4e2d32b620c945f9",
          "sha1": "a05742281c2ee25dd7077e30e067bbcc63928185",
          "md5": "f5e01c1ecc04a9075b28bafc9a56e05b"
        }
      ]
    }
  ]
}
