{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99956,
          "sha512": "9f8e3d0f2d420e5a27c391e7b518189b269b743b63c30679638da764ce9aaee93becd110d73f81b012e2f647a99c423e029c3cd2095469781f79e7754711d6de",
          "sha256": "62bf0070603814ccf45899c8ecc82659a87a9e44407e01bea2e028c498c51b6f",
          "sha1": "bebd75d726152a50ae631ff0498f9b1b9629c6c8",
          "md5": "a8e8f49414a80a2712b8ef32f087ffab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99956,
          "sha512": "9f8e3d0f2d420e5a27c391e7b518189b269b743b63c30679638da764ce9aaee93becd110d73f81b012e2f647a99c423e029c3cd2095469781f79e7754711d6de",
          "sha256": "62bf0070603814ccf45899c8ecc82659a87a9e44407e01bea2e028c498c51b6f",
          "sha1": "bebd75d726152a50ae631ff0498f9b1b9629c6c8",
          "md5": "a8e8f49414a80a2712b8ef32f087ffab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 240487,
          "sha512": "048cdb6e1be8261c572410c2ea7580e80da0aa262146ba2c9277c529532a58fba2978de2abe8bff01b04e29fa5c8c2961a31fe53679a6d5238ab025afa08ec71",
          "sha256": "e6af1eef42921edf236b20a6eec4fa9069a3fb72d2b3f2958677dea9b0646e6b",
          "sha1": "b757b9f670a856cf17c77da2912e5b6e4e092a9c",
          "md5": "0dc65f8642d448fa4553c05149542573"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42918,
          "sha512": "e457cea4e03e2d24fa7739ddf52a79f61e48380df84c85eb45cd7f6e9b809cf78ad3e7b96d62460aac387ee48aaefad37e8e8f9f3ab8c28da54d6bf623638c7b",
          "sha256": "3cdf0e36cd088e0cca59d87e3d6038f5e1d49dd229c122a6463e580fe6b68ec1",
          "sha1": "89c8126bb8ad1286818f3eed0ac959ee5d1fe6dc",
          "md5": "b3460fe19a14c4d5e76b922ec5f78cac"
        }
      ]
    }
  ]
}
