{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 92640,
          "sha512": "d2c7e9ba9fecad45c627a62c1546f1fcd5030c857841bd9f75a0829314ac3c2f5763de1e5c6b79cdfa406f73d6268096f63527e711168dc989d36e070c76abe1",
          "sha256": "e8b92a292c35b6e1c433d3a4b1016afb09bd87a9de015e22732da02fce7300e7",
          "sha1": "c769f732d8ac9570fd1daa5d602aab184216c050",
          "md5": "531213a07cc9cf5f840802f3002de3c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 92640,
          "sha512": "d2c7e9ba9fecad45c627a62c1546f1fcd5030c857841bd9f75a0829314ac3c2f5763de1e5c6b79cdfa406f73d6268096f63527e711168dc989d36e070c76abe1",
          "sha256": "e8b92a292c35b6e1c433d3a4b1016afb09bd87a9de015e22732da02fce7300e7",
          "sha1": "c769f732d8ac9570fd1daa5d602aab184216c050",
          "md5": "531213a07cc9cf5f840802f3002de3c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 221894,
          "sha512": "9b2764873fbf3ca76b265d637ced7248d3366230d066de14ab3eb043068d88a16182cf5b8eebac80e4a5d5fe581901538badd0391da6ab5ae2eb0a58f25b046e",
          "sha256": "311c6032360ada3bdcfded4abaab6ed73eeffaef9e6c1afe2a4f0fa220d16f89",
          "sha1": "397cf7bcdfaf6cdc38774e39e630dc59e3eceb84",
          "md5": "1a1498124d0ffe8f5c98236c7703b99b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 38641,
          "sha512": "d30a354b5b9c4c070ed4b9387cf476a6cf8f6f254d5f6ea66b5d04ca3e7cdf23fad408476fcae64a5d27484907734103a708a342893c802c7553d75742a8e547",
          "sha256": "0506fd0abb72da96c626f4778c62a24699bf4fb40be69d7d9ef431c5ab8bbcec",
          "sha1": "6ef6589f7585fef22a8c2d7ecbcd7de25cdc51fd",
          "md5": "e2743612a0e6b99730a68397272fa11d"
        }
      ]
    }
  ]
}
