{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99956,
          "sha512": "17f2d99328237752d341a52924f9b708e6276840f5e95214912906c182eea389bbb8acd277d69ef96e6a6b3454d10a2e1fd9a224a47bb6281551edd5e2c1bbf1",
          "sha256": "8e8c1adaff3f065c2421bd673d975bd6548bac698a860a7301ac7282149404b7",
          "sha1": "68c65cd856562c95a756295e5ca49487cf1a0b24",
          "md5": "9841422f10b57d8495f7fd7fc0b8364d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99956,
          "sha512": "17f2d99328237752d341a52924f9b708e6276840f5e95214912906c182eea389bbb8acd277d69ef96e6a6b3454d10a2e1fd9a224a47bb6281551edd5e2c1bbf1",
          "sha256": "8e8c1adaff3f065c2421bd673d975bd6548bac698a860a7301ac7282149404b7",
          "sha1": "68c65cd856562c95a756295e5ca49487cf1a0b24",
          "md5": "9841422f10b57d8495f7fd7fc0b8364d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 240487,
          "sha512": "f1d9894550b4a7b1adb6ee16e5657351fcfba8b93a2c583de5a13227a100f306e8f8921831cb6a774e077071a5962cb7691009f14b7873865a4059c084c66b6e",
          "sha256": "642301581b9babf536ea009988748297a892bb418828995acf29400b3ca8e13a",
          "sha1": "badeac4120c1750c91e0446514a2d41a78a0629e",
          "md5": "4bb8fd4f8f7ac74dfbe0e581f80ea168"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42918,
          "sha512": "da79afb0bcd0bf41ac8511ff407f1e8c69e9c4a56639fc08a2b32e50494bc3e285036dbc97e9d1e881bdfa5f0a0b5a15d829b3c3bbd82a2929f0a71d0241917f",
          "sha256": "e8c94d4860648da20976021a03919932335f8505a367afe77977679b35ae14cc",
          "sha1": "5b8e729351f96ef05875ae9c732341f2c91d13d7",
          "md5": "2d92f84b71aca87ce93a2d62a0c653ef"
        }
      ]
    }
  ]
}
