{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99617,
          "sha512": "f234bac8230f77a868bf0dae552fae62e89c90339f3a73856c11a0d36cf369ff5dd3b5a2396a494de03a4dd710f1b1b303bb4dd2ac42c3e10e19699f00a44051",
          "sha256": "273cf7e94b33b12644db1f4d54a0b0609d410bb8a677ddd2dc015437807c83b9",
          "sha1": "459da89af677c9a74afcec09080e884ba4bb28af",
          "md5": "56b3b377fc77daa17d97361c05488176"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99617,
          "sha512": "f234bac8230f77a868bf0dae552fae62e89c90339f3a73856c11a0d36cf369ff5dd3b5a2396a494de03a4dd710f1b1b303bb4dd2ac42c3e10e19699f00a44051",
          "sha256": "273cf7e94b33b12644db1f4d54a0b0609d410bb8a677ddd2dc015437807c83b9",
          "sha1": "459da89af677c9a74afcec09080e884ba4bb28af",
          "md5": "56b3b377fc77daa17d97361c05488176"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 244333,
          "sha512": "e8254a7d78f9edfff5d07bb10866ba12035f192e4b18e28aec928a8bc3b78f1bc3980aab527dc8d5a09438e695be5ca8126d30ff72866b4b137e7f2cb5555ee9",
          "sha256": "3d05d4c146c969ec5a334dddf67c1f323304740514d115d455146c1b56f94f3d",
          "sha1": "85fdc3ee4e57ad2bff6a340d2a2007bda00d5c68",
          "md5": "d788a4a1a8a0e941a9513dfb313156a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42551,
          "sha512": "bd37ba53b0aa7d7029cfe5b2aa8b9d50442e45795a69650a7a58c2e1bb755afef177892c440162d94240b24441f2eaf7d2cba1ecf9b2b9ffd22ddb9e2576f362",
          "sha256": "dfc793415abef978f058a5fd26e226ca66d963f9efbe5a7268c49818cdcaeef4",
          "sha1": "5cfef6922849aad6eec066d83585c77a02d5ee31",
          "md5": "52ac40257c14e572342b095f32c888a2"
        }
      ]
    }
  ]
}
