{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99617,
          "sha512": "926c28c74067630e2c0881b0c64a6fbadd9c90dca72064d2bbe6fe3db626a374a6cee7dab736aa5ab1ef27bb5b76df2fee65791ca9a4ddee477a50a9967d8b3d",
          "sha256": "05f5c8f1ebe23a18effd906b5d42c71e26d0acbdc697dab24b89912e2f422ab2",
          "sha1": "2058cc29f37a4761a2ff14b751aa95d9dd727061",
          "md5": "853ffb45420e78c8ebb40806ba21a6b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 99617,
          "sha512": "926c28c74067630e2c0881b0c64a6fbadd9c90dca72064d2bbe6fe3db626a374a6cee7dab736aa5ab1ef27bb5b76df2fee65791ca9a4ddee477a50a9967d8b3d",
          "sha256": "05f5c8f1ebe23a18effd906b5d42c71e26d0acbdc697dab24b89912e2f422ab2",
          "sha1": "2058cc29f37a4761a2ff14b751aa95d9dd727061",
          "md5": "853ffb45420e78c8ebb40806ba21a6b8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 244337,
          "sha512": "d3e10f7089c53c9909da46a176b5e12b5891a40a25666e7a036163c33d1ae96827a7a07ba57ee99ad543d09b09fde9bbef4324b7a804eb4e48bf359ac5bd40db",
          "sha256": "dad09a70743eb2c23b593d707049f7dcc66ed28f54eeca9fb0611ab7f71366a2",
          "sha1": "cd2875d4f3d16a79a71721ecfcb0e8b9e6719136",
          "md5": "02c52d71e6fc19c96b2fa48eebcfad87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 42551,
          "sha512": "0d7a87a5b3d89e3b737fdf77dd89059e03c278bc607ea25ffc94ebb20d8232e5e6282e44f2ca22a10af6f83f101d2a9eedc71036d7d482564270b91d3cde15e2",
          "sha256": "e46de931c754a380bcd05e8ad45a5ad5e8205a792e2e786020b4221e3df682d5",
          "sha1": "c62baf98f483cbe73784ddaf6fc95c8e26519fd6",
          "md5": "4703e223d4317a34f045cd66432d0a67"
        }
      ]
    }
  ]
}
