{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 87963,
          "sha512": "0a888db64adf3afc99b9d01f073a809b16168fac1114ce29abc4b9c16ca476982e85bef7b72febf53d47561e8355c9c3a6be8d58578e72161de47f47530be495",
          "sha256": "5eadb019e2753a04ca11484f88f00f6fe2398e5daa0017d1356a2c0d5d0df628",
          "sha1": "a1b4a60f74441cb372f62f33c273e877b0e1be2c",
          "md5": "25563ffeaccfad9367bfd1595b9a60da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT.jar",
          "size": 87963,
          "sha512": "0a888db64adf3afc99b9d01f073a809b16168fac1114ce29abc4b9c16ca476982e85bef7b72febf53d47561e8355c9c3a6be8d58578e72161de47f47530be495",
          "sha256": "5eadb019e2753a04ca11484f88f00f6fe2398e5daa0017d1356a2c0d5d0df628",
          "sha1": "a1b4a60f74441cb372f62f33c273e877b0e1be2c",
          "md5": "25563ffeaccfad9367bfd1595b9a60da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 281212,
          "sha512": "62ad479f3d77b27623174b32ced536209c1393ca49675841519bdcf371cbdf2f9026ec5bb9e1ac5deca9814eb44188c3e711109c715bdbb8a9ac8e27e5375886",
          "sha256": "a9e8cdefa7298f6e0e8e3fa447b4f35cc6f8239929c735bfd86f3be82e01853e",
          "sha1": "0cbc7065cbfa6924b286407f8d4307f3f6bc4e39",
          "md5": "306f7001894b3ff27b659a2d237402e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-gui-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 37656,
          "sha512": "f40553dfc7a8ac73646a4d086c923ee7153cfb1b84bbec912e2a984e86a28f14bc72c4a54523ca1fc30c06ec994b57c4c848f19dd58c10b9e31f4acfab43a9ff",
          "sha256": "a7c1923ef9515755ae01ecb29d2d0d77ec0cc323b6b5fcc7e88d8eda41ee6b54",
          "sha1": "622fa6486f60db302b63f3761d5667a40bc4939f",
          "md5": "14715afb20f66b0e0dfffefa787e210c"
        }
      ]
    }
  ]
}
