{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 26232,
          "sha512": "4772bcad52f7345df9fa1254632c0943fff3831883096097896e6b8e52dcc48c8c0c5763e7d16eb5a30d1d812446d0242197a27575a1af0136da7ebc3cd63131",
          "sha256": "5326c2ec64e19d91947fa0901b5be6203ad6591d8a991d49cbe35e3cbdeb5b05",
          "sha1": "2f9626053042f35ff91f9f07fa80a4a1bf69e038",
          "md5": "405217102962fcd637274063b9ecaa7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 26232,
          "sha512": "4772bcad52f7345df9fa1254632c0943fff3831883096097896e6b8e52dcc48c8c0c5763e7d16eb5a30d1d812446d0242197a27575a1af0136da7ebc3cd63131",
          "sha256": "5326c2ec64e19d91947fa0901b5be6203ad6591d8a991d49cbe35e3cbdeb5b05",
          "sha1": "2f9626053042f35ff91f9f07fa80a4a1bf69e038",
          "md5": "405217102962fcd637274063b9ecaa7e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 103994,
          "sha512": "3133c3abf7cb773b3acd079c543022be3aa0d612ffee858e1883860ea04179db1d2bd719cc64e997fa8f1930782dbf4af39d971c4b3756c67e115bdd729f83d8",
          "sha256": "ac8d19e5b601c3c7d880b042fc1a1c9a7e9cbbbd56ccb63184c2c7c8ee4385d5",
          "sha1": "e89458f87dcf7ae2893eefc129ebb6ef006eaf86",
          "md5": "cfcfb8d065b8dcea68b687594da48b21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 9433,
          "sha512": "8b48bf84cfa981e09457c710388f917c9034573c505548968b215c25bb6841227538be9554efe00cab2519580afea755a6d5d6adc68360b12ed461149b3780e1",
          "sha256": "db66e54f4cf367ef86861ed7dfa82d263dc0a96023bf45ea6b99a8f7093bb926",
          "sha1": "d14fe8e53f6445d057bdf69e114af53246877a85",
          "md5": "627848aeb6f96e22a021a8386fb58a73"
        }
      ]
    }
  ]
}
