{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 22710,
          "sha512": "6324b789094cf931b3abb2e48993dfa7f198b6beadc09ada228f30526243d05696d1b9fb9d99adfc944d0b8ef61692d769af84af6f2ac25f960957da151e060a",
          "sha256": "fde257de12de372e3e9b80375cf3b33e2d31b7f8469cd93530a4cbedf4ed7eaa",
          "sha1": "fba02a82051ca9b73cadc514f2f50f30562de213",
          "md5": "8b8810a12bb2c3ce5bfcc912cf591714"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 22710,
          "sha512": "6324b789094cf931b3abb2e48993dfa7f198b6beadc09ada228f30526243d05696d1b9fb9d99adfc944d0b8ef61692d769af84af6f2ac25f960957da151e060a",
          "sha256": "fde257de12de372e3e9b80375cf3b33e2d31b7f8469cd93530a4cbedf4ed7eaa",
          "sha1": "fba02a82051ca9b73cadc514f2f50f30562de213",
          "md5": "8b8810a12bb2c3ce5bfcc912cf591714"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 88148,
          "sha512": "09779adaebfa4c3ac8c86fffc697620f47d2411f7f3751249166adcbe6bfdef4c071c1100a93264b890f21cfab531d5c6c073d988b91b54c69791d69138649fa",
          "sha256": "d19b5eee83c1f8696e1e302a5658e3f27f579cfee547a6ff660c661ef5b1182f",
          "sha1": "787effa16dcaac544614c8388fbfa95aec4b6f3e",
          "md5": "4a992ed47a915be064db8ded2b3683b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 8509,
          "sha512": "d2350b8c83d1d2f7fefeb207c2ded948d8486819b3838371009a5f04239cf3a32a5c49d60ae5a36000829bb15687a55747e449d0ef09a493220fbc5e8a609ffe",
          "sha256": "be491a452e3e3cd29b6862b823380e3e42ba2a122f45a822a12d47f00559650b",
          "sha1": "f4fe919ccd9f18016696a23c2b5511e252138d5c",
          "md5": "e86b2e7dff1cc59647f85e20ccf76deb"
        }
      ]
    }
  ]
}
