{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 26175,
          "sha512": "e496332b93b763cc517e28736dbb08a9e46f7108016d3559d4c98837ad184690c2f19f341277bbc66f32430f3a7d936ee73b0f1f27647121ce5ecdb0475456da",
          "sha256": "9c1a880f052fd06222f671023061dd48ea2a577dbe90f27d1a65be9f5ed67c8f",
          "sha1": "11567eb772ee5872dcfa87c9f208d9d0dc599bcf",
          "md5": "26d7eb52e49431e90e1d0d5add6d0a90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 26175,
          "sha512": "e496332b93b763cc517e28736dbb08a9e46f7108016d3559d4c98837ad184690c2f19f341277bbc66f32430f3a7d936ee73b0f1f27647121ce5ecdb0475456da",
          "sha256": "9c1a880f052fd06222f671023061dd48ea2a577dbe90f27d1a65be9f5ed67c8f",
          "sha1": "11567eb772ee5872dcfa87c9f208d9d0dc599bcf",
          "md5": "26d7eb52e49431e90e1d0d5add6d0a90"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 92570,
          "sha512": "cd633fe350f00a4c76e1d3ef1bd7ade1f669acc1baf44b59048433db62c365a9f00462db79761c600e650808f87ec7f952db9e9a6c7c89d74c41b5d7dd76d9bd",
          "sha256": "72960a9ab91bf48aaf1a5ff151d9a625aea0c24d75dff67e45408d0451d8fa7d",
          "sha1": "78715fd05c1cfd35bcc6303d32d96b0cabdbf6ab",
          "md5": "2e548e8f7d8470c878fa062864251fe7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 9363,
          "sha512": "adcba4b9d00e566c16e6ae191f466dd9197d71728457621b0c35bc1a7d092fd2268d0667914d48de73ab7de40f4ca1a1042022e6a048188696454851d8c77259",
          "sha256": "33feef79b1c20326aa7088d7157795ead48a0b8e1bbeeed0d595660bae47cb12",
          "sha1": "b274da64630d264c121e4d8313aa0cedb7023962",
          "md5": "e6573670387575b131a450ce0961b722"
        }
      ]
    }
  ]
}
