{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 22961,
          "sha512": "3a3c6a4decdc556f9907d67a065fba4cde2637faeb4d23121b83a6b2813d5271176a7690202a275951ea01c233c0f7cdc7a3a23eb7322c6e04b361cec6119840",
          "sha256": "9bcc1b28422027e9a1b19fb440c30ebde35627830200f40c88c28adfef17e44d",
          "sha1": "d737cc3f8df48305a4bad4a8fc50e7720f4ce230",
          "md5": "0578def5730323297acd5539ecd5f1a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 22961,
          "sha512": "3a3c6a4decdc556f9907d67a065fba4cde2637faeb4d23121b83a6b2813d5271176a7690202a275951ea01c233c0f7cdc7a3a23eb7322c6e04b361cec6119840",
          "sha256": "9bcc1b28422027e9a1b19fb440c30ebde35627830200f40c88c28adfef17e44d",
          "sha1": "d737cc3f8df48305a4bad4a8fc50e7720f4ce230",
          "md5": "0578def5730323297acd5539ecd5f1a8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 88149,
          "sha512": "e17658a8dbf2a2e24df5a4b0b83c6e52f71888ec637df30280e2c67de87a432fbadea21c60f33c995fcb106d73b7cb1511c2fd91a40e3b7f6467e0d4935de38f",
          "sha256": "306ef288aea8b0c31a83d4bb5b843a458d7ef399efdd734c9d2c3f5dd10d7a4a",
          "sha1": "0ac02d26fb685cce4332018f4adf366ce5dd7ea5",
          "md5": "9d0bf43804e085228eebb669d11a89e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 8610,
          "sha512": "5462070e21066200d507d3ede119d75a14d5d5e645a7b2edb5ef0656e9124a7c5e572603807df25477c29db62ee97118c09933b5ffcb5869a48c8e39007a307b",
          "sha256": "9a77baf9ef3f3a967cd9e99a1236743fd2e8d5e294d9f7f3b1b979e46649688a",
          "sha1": "9444c71a72ab7c70ca2bb63befcc18aeceb4f2f5",
          "md5": "995285b016886d7531d262d52a85abf9"
        }
      ]
    }
  ]
}
