{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 39097,
          "sha512": "f963abddfcfeee83706dd50f007110f2e6fe2cab6e7aca59fb4c1df12b8f9f59789f6a7462a434cfbc292272b051a55eb8c3db9641e2671530faec41fc07ca41",
          "sha256": "f6f66f5e79dd58327ac333481244e0100899142b627f2e76d4f286d7b59dc619",
          "sha1": "4b65ed8a4b855937bbdc9ba08a14b38bcdfc49f9",
          "md5": "b8fe4ea4271c78be69e8318897aed8c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 39097,
          "sha512": "f963abddfcfeee83706dd50f007110f2e6fe2cab6e7aca59fb4c1df12b8f9f59789f6a7462a434cfbc292272b051a55eb8c3db9641e2671530faec41fc07ca41",
          "sha256": "f6f66f5e79dd58327ac333481244e0100899142b627f2e76d4f286d7b59dc619",
          "sha1": "4b65ed8a4b855937bbdc9ba08a14b38bcdfc49f9",
          "md5": "b8fe4ea4271c78be69e8318897aed8c2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 107558,
          "sha512": "d5b1ec2d699e436997ff42f53ef37bbf30237409a6ba8b5b64aac5baf8ebe81b7dbec7c876cedcc254040d693d45e20003ce89caf0724fdb37c1cf535f547b59",
          "sha256": "6f43a88ca267fe28d10f7306892d1c7fd48a644a1ad202557780d272f9a2f9a8",
          "sha1": "4e4a6996372ce92a3294dba971dfee852b3f1d38",
          "md5": "16385dfadc51cfc9b0dd4de80b37d25c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 14487,
          "sha512": "2bc33c747e099b4d2e82b708b0358e60976c24567a0af290ccd238a2a6dfe9041fac89672146869e7d99b420b89eea292d33d6d1460c35393e05f2c4db97ecbc",
          "sha256": "0c15b63f91fd6b1a8411e02d2f48d79e11f01ea0c5006049978fb08fbab31673",
          "sha1": "34b417f6b0b1ed204d7f5df05c972bf83192e078",
          "md5": "4bafb63a01383e6c794fed1c1de55287"
        }
      ]
    }
  ]
}
