{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 17607,
          "sha512": "f9ee1d285f8cc3503762d598c5a4714cf256a390d24c17e0a0073af337ee14e56ab242c9a5db4b2d98e1785f73a521abd16730bf2b51c501e6c04a0249c3bf84",
          "sha256": "f6eb85a6b2d73f1a0b8ab52d32950a80a844d10998afb9f3d681de47bbc6bc0b",
          "sha1": "65a62201954c9d7f37934b0627d19694b48d335b",
          "md5": "acc8e0de684ced26e06bae79d2faf0bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 17607,
          "sha512": "f9ee1d285f8cc3503762d598c5a4714cf256a390d24c17e0a0073af337ee14e56ab242c9a5db4b2d98e1785f73a521abd16730bf2b51c501e6c04a0249c3bf84",
          "sha256": "f6eb85a6b2d73f1a0b8ab52d32950a80a844d10998afb9f3d681de47bbc6bc0b",
          "sha1": "65a62201954c9d7f37934b0627d19694b48d335b",
          "md5": "acc8e0de684ced26e06bae79d2faf0bf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 88148,
          "sha512": "6f95cc587ef67333e564075e7ddcc98aa04a010cad1f4646305ad2ead526165384b6d8bcdd6047780cc8f142beafb32ec86b8b37b56d4190e074ab9212db6deb",
          "sha256": "45edea27f4d144999fea5f99ed652eb0f39d06fb2f7032cf738bf9f8bf11aed1",
          "sha1": "9a071ffbc59aadd15ef97876ce2293a04aafcd8c",
          "md5": "d4507fdd7cd62dce86f6ce8c89a20ecb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 7496,
          "sha512": "5d6edc860ded975f98c09e5d16b23b78bbe113e53c6fff1fb84d103917fa0dfd1957eb870e0bc7ac8dcd22a9dc3808254c20225938d0520cbccf86a41350a6bc",
          "sha256": "9b97203094cc539557379e48d07e20f8e219b441f53f4edf4998a0ad913b8be9",
          "sha1": "d035005580127792ff8de8f9a92ed4923481bc6e",
          "md5": "a7617ebe46020223696e8353ac39d16a"
        }
      ]
    }
  ]
}
