{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 26232,
          "sha512": "4a7402749c2fad945082e6fb2990c92711613d0cebf4b1358a84a7822df006e85f999f32b8a27c5c07e273c997d000c8322542d0086ffb0e5ea462bce4b0bb8c",
          "sha256": "9277b9958967622975cdc938e335bd6514e7a1dbd7e8f4b068b82810ffd54f05",
          "sha1": "8dd442c6967ec21e2e1a30c9cb5a1588220b292e",
          "md5": "e2ca01669aeda64eb8b28b1af656af18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 26232,
          "sha512": "4a7402749c2fad945082e6fb2990c92711613d0cebf4b1358a84a7822df006e85f999f32b8a27c5c07e273c997d000c8322542d0086ffb0e5ea462bce4b0bb8c",
          "sha256": "9277b9958967622975cdc938e335bd6514e7a1dbd7e8f4b068b82810ffd54f05",
          "sha1": "8dd442c6967ec21e2e1a30c9cb5a1588220b292e",
          "md5": "e2ca01669aeda64eb8b28b1af656af18"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 103994,
          "sha512": "725daf00a35c7f30fe3fd9aaf618089b2fbfaf1998a0eff9b258255d9256095abb7f8d7232f1cf14b4a598bf88b30b5baf8adb5fa0027068f0f7a4c9ea681e6b",
          "sha256": "bd102c52a1d90475c85574f36fd1c1b9f426ba563bdf3561cf46bb82f8d571aa",
          "sha1": "1c4fa9807dede724640bba3b364f3b5e6eac8894",
          "md5": "93efe91bae96de0928482bb7ec7a4048"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 9433,
          "sha512": "bad8d724584bafdd72d02d9825b06bb4468d57640faa2708338185b6df4617cedbe99222fef5de2628d921fb6651d6a6175d671418f8474e39b3e619e363f186",
          "sha256": "134d148b46d4ef6efdc782d34a7de935d853cab547cae73d0fc317eb5c2cca70",
          "sha1": "7f32c87e4bb1eef25dbe44f12a54e1367e74b654",
          "md5": "1b4647512523b37b97c876492e183103"
        }
      ]
    }
  ]
}
