{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 39097,
          "sha512": "e20fe4d00617bb4a8c54b973a5cb5370593da088465a7e7e50c0b3fe470bd30ae856a6fbeb09a428f00058e59acd04d5a0d789dcd448e71d8978fadca1b4196f",
          "sha256": "366250a89ff7cf61a729de86bd880290137f40eac2c42b1ccd33fd1378284985",
          "sha1": "285cff9f6aac0108c55df850eaa1be1746ee86c8",
          "md5": "15f0ae8b00fb1dc09a44ad6e56942cca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 39097,
          "sha512": "e20fe4d00617bb4a8c54b973a5cb5370593da088465a7e7e50c0b3fe470bd30ae856a6fbeb09a428f00058e59acd04d5a0d789dcd448e71d8978fadca1b4196f",
          "sha256": "366250a89ff7cf61a729de86bd880290137f40eac2c42b1ccd33fd1378284985",
          "sha1": "285cff9f6aac0108c55df850eaa1be1746ee86c8",
          "md5": "15f0ae8b00fb1dc09a44ad6e56942cca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 107558,
          "sha512": "5addba34b2d7c32586acef0287cb2780d34d15f348e973c17b548ea8beb541bd9daab3738c164930ed5a2a34c09262e0197ff5bbaa9a495fb9c63a9e2028426f",
          "sha256": "215633f9ebf1fd70949327592acd61ba41e02bdda7556e78ad6fd789048feec8",
          "sha1": "94bb24660afd78b81294068c5b48541fe83ec88c",
          "md5": "ddfa6ca0b00afdc44b90eff44cf34134"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 14490,
          "sha512": "1bd304974e5d3d971450cae8ab1f99294e885ef5f30364bce3c0d77a95380385a370cc91735979edc59dc69fea927590a882c444c993c7821a9dd0b156e982da",
          "sha256": "060c80716536bc04354c322f6aa2e83fa15f39ffaf0598a791903e461c37416a",
          "sha1": "b0e2010339b5ea49a9198fd1513192088bc205f8",
          "md5": "a87ed205411566a18273344f75f0aab5"
        }
      ]
    }
  ]
}
