{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 17517,
          "sha512": "786fef8dd302bec68cd9a0b9e4011e42dfa8591f75cf9841657179321228680a76aec27d694f09be3860f20184709511f9c9472b80a02c39a2a34c2e69fd0454",
          "sha256": "5916e48a95639c16b61bded03ce5da49f9a73b76d9ba8cf0dba36ebcb73b2b0d",
          "sha1": "1cf7af6dc00e11b85da95e3d7264b0baf7ef6977",
          "md5": "78c876d1caa8a8fe935f04dc37fac830"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 17517,
          "sha512": "786fef8dd302bec68cd9a0b9e4011e42dfa8591f75cf9841657179321228680a76aec27d694f09be3860f20184709511f9c9472b80a02c39a2a34c2e69fd0454",
          "sha256": "5916e48a95639c16b61bded03ce5da49f9a73b76d9ba8cf0dba36ebcb73b2b0d",
          "sha1": "1cf7af6dc00e11b85da95e3d7264b0baf7ef6977",
          "md5": "78c876d1caa8a8fe935f04dc37fac830"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 88148,
          "sha512": "98ab807476e33e74f0f4188aed80c80729b04f63849adc68bd820c5aea0b308c1b395bbe6b8905c9b536403b784e8f9506825b2b91bcd97f5e8be00f0105bc5c",
          "sha256": "2d13ed0c8916450166a23987db2193bbbdf95bb0a8444f668781d25c75aa1f14",
          "sha1": "4c59427cd5f2a697b6c83b39df1c2183fe2268a8",
          "md5": "c853a511976980e46fa1f5f5aa73a2bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 7472,
          "sha512": "3cb514a812658b3ac3216b220402c9c2cbede792a1f6a5203cbd80eb4fd26556d75a3d1ea654d581cba32ade6ebd7b4166e8cb8fb254d191c42e6d18900059bd",
          "sha256": "038557199ff2fd6fd9a329c580c471a92cbf1eb966b4c0bbbd4f8a18af511ec9",
          "sha1": "2596d06d199732a9dbfd54333f3db3671c2e4939",
          "md5": "7d10dcbf88d567e807f260a19c49919d"
        }
      ]
    }
  ]
}
