{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 39097,
          "sha512": "58520c387b9149935460f830c5cfb4b1c93992cce5b344f225000c5c1fc1fd65e1797fce1951ef2f094eb5787f0d3252444332c472bb6eea74178377272c2622",
          "sha256": "07ff0b25d75a4915882c07353d7164250da39e242072f6704af5f6b0112bbd31",
          "sha1": "c3fa233cae5f3ca38151b34527d22baf92d091ca",
          "md5": "922e86b8ab3abc7f15c2eb16a9bdd6f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 39097,
          "sha512": "58520c387b9149935460f830c5cfb4b1c93992cce5b344f225000c5c1fc1fd65e1797fce1951ef2f094eb5787f0d3252444332c472bb6eea74178377272c2622",
          "sha256": "07ff0b25d75a4915882c07353d7164250da39e242072f6704af5f6b0112bbd31",
          "sha1": "c3fa233cae5f3ca38151b34527d22baf92d091ca",
          "md5": "922e86b8ab3abc7f15c2eb16a9bdd6f5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 107558,
          "sha512": "e5509255d7362df02fce4ce0978ebaccaeb290d8d3410bea0b946a62a548d82922c3019a763c96d890e133ce3462e765cd72a918b10c36f73dd8cd7e9eda3470",
          "sha256": "559241104ec012f79482c1d71e9476655e613bd332b740b2a083b20bf9b31b00",
          "sha1": "db8160311f9707038417e22323f0dd61c356aa3d",
          "md5": "d715e185c73ccf0a37855278a70deb92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 14490,
          "sha512": "af5670dd47eaa403379a6b7525a39cca6a59f31a2c50673b5a197f65f74aa1d94b039176da6cfe9dc7923df76e30c3e48b6c20c1bbebc38d656afda4a8fd8aeb",
          "sha256": "c28271fdbea231deb98c128520506cf3a403cc74e25851897274dd2f6e64f4b7",
          "sha1": "b24b652ad714120d3553467360ca037ae122cbf7",
          "md5": "0ddafba0f14158b3c6dae7fb67ed418f"
        }
      ]
    }
  ]
}
