{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 26195,
          "sha512": "e04ab7ebf641e090896322be88dc027c308ff86d4d3556c30035e92d15fd00ef5600cb86df8ed9ad150d5fd3514be0191c41b89fe5d17cc5dd0efb78a15b8ecc",
          "sha256": "45a20936ac627dbf03289e288c8057b04afea9affd883b7fa2fce55e4c127046",
          "sha1": "129a45c76ee5afae1f84a75ebfa2c219615c12a8",
          "md5": "d6042879b6c72ca32a79eae3588a89dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 26195,
          "sha512": "e04ab7ebf641e090896322be88dc027c308ff86d4d3556c30035e92d15fd00ef5600cb86df8ed9ad150d5fd3514be0191c41b89fe5d17cc5dd0efb78a15b8ecc",
          "sha256": "45a20936ac627dbf03289e288c8057b04afea9affd883b7fa2fce55e4c127046",
          "sha1": "129a45c76ee5afae1f84a75ebfa2c219615c12a8",
          "md5": "d6042879b6c72ca32a79eae3588a89dd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 92570,
          "sha512": "593e47d47ec60f122a2be9bc6a82b17de0b8f9dc4d33f66fcd48cc97b8feb6eff1415c52b723abb6076a81981677e3266e7677e3567bc05844c35e06ebb2fec0",
          "sha256": "99e90b4fe117db8f3c556671a8a246721c2bc417ee0db3479b435e098b93d148",
          "sha1": "f219d9bd0af6061db0f1c567bef011bac1cc02e7",
          "md5": "ed576b40b8e35df625afd0c2ee1774de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 9439,
          "sha512": "e413e8cbde505bfe885fe151d26df0eacf2be8b435317357775d93fdeb6dfeea8c917c5766c48f7f0992005782750b01de2b5c5c9efdc37e89da9a6a70f1e174",
          "sha256": "2a01cd00387430ff93ac3cce738c56c825cf1aba49f3035f08bd830591b89b59",
          "sha1": "a262b9a556dd1b1b33a64c4178907656e550d963",
          "md5": "a730f44b1ab457810ae5b1d05df3bccb"
        }
      ]
    }
  ]
}
