{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 22961,
          "sha512": "b93feff8ba9453bb54654b2cf3cebeae0798f13865a567c86233f9757e559e4b69b8a359e37517c5e67e047e83eed26ff8e044b4cdd9872d25bd63f1698002b6",
          "sha256": "bba88f678426b35bba656d261d875844df9adc56d9506e40bef196338acab6c5",
          "sha1": "d0f69ef62a049cda24d35eef426639c26ae96e89",
          "md5": "0ef4de0483fed296d11dfb6040068b18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 22961,
          "sha512": "b93feff8ba9453bb54654b2cf3cebeae0798f13865a567c86233f9757e559e4b69b8a359e37517c5e67e047e83eed26ff8e044b4cdd9872d25bd63f1698002b6",
          "sha256": "bba88f678426b35bba656d261d875844df9adc56d9506e40bef196338acab6c5",
          "sha1": "d0f69ef62a049cda24d35eef426639c26ae96e89",
          "md5": "0ef4de0483fed296d11dfb6040068b18"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 88149,
          "sha512": "cbd4c13e36065e071c0ee6d2128b93c5f1d11a0b6d21de5cad2ce633e9de8ee9997233b9786761cc18171ec907136fd8dfdaec8585a84c4feaed7e80bb8aff48",
          "sha256": "5c107fd88fedbb78c5c11bda72f9f230d45599d984bdcfd3526f5c67d4987ee0",
          "sha1": "2643170e070c5dac85a2fbf7183dc6d03f47d2e6",
          "md5": "173f5cd69556a08aeb1d428c4f6c9fc3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 8610,
          "sha512": "2ff096a1b186d23d71a559b51077382e86e8be5f3da1c84e49b9dcc237fb90f6ac4d1527e1e578e2be6b03a93b3850d89b5b239377c30a369f8607b95a9eec79",
          "sha256": "8351face0c1a0e9a432cc8cba6c7cf2bcd86f335291248bccd76c709a66dd454",
          "sha1": "ce5d1601a1a451a4e74454f42ed18c001d82de55",
          "md5": "144ddd83648cbdaee5450285f249f3bf"
        }
      ]
    }
  ]
}
