{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 26232,
          "sha512": "a0165dd28d93ab35acd7c8730d278a692a7f76f02680137e170a3f7adba8e6ab91f0a81f28b923f2b221e025ecf34be03f645fd14fd07fb7849a14315d067392",
          "sha256": "6632c7d1165e38adb05479b798d716db8891fc2344163f388ea2d0480b20f60e",
          "sha1": "2b1c90391e87ed61c3b87e60bde0231d15aff57d",
          "md5": "3a94d92d0da945a3706e472e48b75f97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT.jar",
          "size": 26232,
          "sha512": "a0165dd28d93ab35acd7c8730d278a692a7f76f02680137e170a3f7adba8e6ab91f0a81f28b923f2b221e025ecf34be03f645fd14fd07fb7849a14315d067392",
          "sha256": "6632c7d1165e38adb05479b798d716db8891fc2344163f388ea2d0480b20f60e",
          "sha1": "2b1c90391e87ed61c3b87e60bde0231d15aff57d",
          "md5": "3a94d92d0da945a3706e472e48b75f97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 103812,
          "sha512": "2357f04ccd7233272a3756dc9ca11a5b46c99fa383612045693ca8f826801021694f3178cdee15531290855d163de23b2fe41f829df1000cc2b2051178c773d8",
          "sha256": "6d1096f62aeed4a7258b5a2c194a14b35ae184e59c9486ac1037646bb8dbeba8",
          "sha1": "e57f01ae5c582c3e3cd0345ec878857bc669be8e",
          "md5": "6644a46260820b7697ba5ee9c4e5e9b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-yaml-6.0.0-SNAPSHOT-sources.jar",
          "size": 9433,
          "sha512": "798bab8e19450211207a792ea91202834f4d7f97e9d58ee1effa3d4651c88914973d75c470ca3f553bd2bb1684c58eaa5dae7b0caf2facb645fbf1922d2b0836",
          "sha256": "cd54496c4587b8677aa4c0539322f54bf21c4ea537184bb062e26ca3381db684",
          "sha1": "c68aee0a7167a457643e49396c1595d5ed93d20c",
          "md5": "d3279ab53dd5931ffacc81fedd0a8654"
        }
      ]
    }
  ]
}
