{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "5.0.0-rc.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-5.0.0-rc.5.jar",
          "url": "box-core-5.0.0-rc.5.jar",
          "size": 55024,
          "sha512": "40b93b2a287d8258e3ac096c95d8ec042f056815632335f18abf945fdde82e4971aabd019877d8acaae43262d5e6a77d8c0632e0cbb45313cc93dca24c8f0bfb",
          "sha256": "5f562549d466630f50b04871d03ee5548f88dcfa48bdde5d37fb0239185a8fb1",
          "sha1": "522fe3efd75c95c49bf1c4d21928dc99fcc5420d",
          "md5": "427fa8c9f63548e21d8e488bd01b2356"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.translationloader",
          "module": "translationloader",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-5.0.0-rc.5.jar",
          "url": "box-core-5.0.0-rc.5.jar",
          "size": 55024,
          "sha512": "40b93b2a287d8258e3ac096c95d8ec042f056815632335f18abf945fdde82e4971aabd019877d8acaae43262d5e6a77d8c0632e0cbb45313cc93dca24c8f0bfb",
          "sha256": "5f562549d466630f50b04871d03ee5548f88dcfa48bdde5d37fb0239185a8fb1",
          "sha1": "522fe3efd75c95c49bf1c4d21928dc99fcc5420d",
          "md5": "427fa8c9f63548e21d8e488bd01b2356"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-5.0.0-rc.5-javadoc.jar",
          "url": "box-core-5.0.0-rc.5-javadoc.jar",
          "size": 220381,
          "sha512": "c024c3b89d01a12675b20530c0f3f52aa98e1b90739a51d90cd692431d84a7062aeab9d42e0b3773baf1d18f550530012f50ab88739783094864ab57337da5f7",
          "sha256": "4d92a0fa4f06eb1069146a4bfd3a864f5a17d6d44d8f70569a22196f492251bc",
          "sha1": "3c46f458527b4fe0522168a640c6d5a8758ca1e2",
          "md5": "84d7c070db1509f40a051d8770a92fa6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-5.0.0-rc.5-sources.jar",
          "url": "box-core-5.0.0-rc.5-sources.jar",
          "size": 24330,
          "sha512": "95e9ffba8366de8cd212101ccf33a71acb3733eb7479d208f5dbbaf058ce72074f585c8a333ae3274eeaf53fd66808721488bcac483011a0c14605e64ce754fc",
          "sha256": "cdf164bc7f291290d33f3c119a7d39529df1daf8acda6ea3d10ea366b617f239",
          "sha1": "6b84526c9dfbfa41f0f896cc1bef9505ee085761",
          "md5": "c11c0c0063f82debfe3d054bb8d9f407"
        }
      ]
    }
  ]
}
