{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "abd440547402163bfbbee07ac8d20f9b7868460f7b80bcfc8f0e3c098bed6e663477dc6ee5f7fe4d2f0486200505d1f3200eab825f316a54bf92ac212108d644",
          "sha256": "7912932fcfa14daa881f650bb152e0bf82fd8986c1ecb32e942c01e166438d72",
          "sha1": "36c8adbeb916fd29ff79ec4eadbb3b53c67a8209",
          "md5": "782753e5fae63ce1474d915b2e837f1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "abd440547402163bfbbee07ac8d20f9b7868460f7b80bcfc8f0e3c098bed6e663477dc6ee5f7fe4d2f0486200505d1f3200eab825f316a54bf92ac212108d644",
          "sha256": "7912932fcfa14daa881f650bb152e0bf82fd8986c1ecb32e942c01e166438d72",
          "sha1": "36c8adbeb916fd29ff79ec4eadbb3b53c67a8209",
          "md5": "782753e5fae63ce1474d915b2e837f1d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "c40473a8669fe26cf34e634e04c74ab3b64c4828bfbc6429b843a9edf6fb6fe3290cb703be98957d86f404e5316f9eb0103761bee416d0f3d1b79b03c4c56a77",
          "sha256": "ebe5d706ad53299f69db1cb28feb6f255efffba7a1e5e7cf1894683b8fff767b",
          "sha1": "a1c92753e856ed421a8ab13c5fcaa1c407647cc8",
          "md5": "653b9b884719957392bb4aaeeb4cf2ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "2ca2db07d210abcc0d25a2d1e7b2a84ded696e6bdba7e5f448d64bf8aab0f7f0cb6e44bc25f9b4bdb94d23cf03bad33c13bb39b0362ef792c76bb0f72f00477c",
          "sha256": "5b09500bc140c891e954b42a141d71e0f3b19e8d64a7fcd397c865a5fc27d694",
          "sha1": "e1836753da0f0c109d51ce4ae3c1e3d158874f54",
          "md5": "d32a96906fa31a140a3a0d1b36acb54f"
        }
      ]
    }
  ]
}
