{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "0db3d09c8501c700249403159955ff4bb95efc74bb57c2338eba011e0821b0b1169d9a4f3e81825d0d9ee484cdb399862a8ca1b625316b7795d9e528b3b287c9",
          "sha256": "be9a97ac000ca9fb182d50b66109800b76cb451bea3029dca52715be6666196c",
          "sha1": "cd38ce083a66efabe3f6ab7ec81e1909e90b2818",
          "md5": "98f43c0d0e6a6981fe9b5f7e193bdb9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "0db3d09c8501c700249403159955ff4bb95efc74bb57c2338eba011e0821b0b1169d9a4f3e81825d0d9ee484cdb399862a8ca1b625316b7795d9e528b3b287c9",
          "sha256": "be9a97ac000ca9fb182d50b66109800b76cb451bea3029dca52715be6666196c",
          "sha1": "cd38ce083a66efabe3f6ab7ec81e1909e90b2818",
          "md5": "98f43c0d0e6a6981fe9b5f7e193bdb9a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "8eca0c9d1e56a300ac7fd099e1cd0d74b386fdba5fdd384fc0d376e2d43696528946be90cd2d5ca7aa2f366f81d59e20864b6cde15c72c801bde7db26950fe7c",
          "sha256": "5932fc1228e98e08cc1aad7c32061d6473a71526560cd1de2cf349143dda1c07",
          "sha1": "7904d25f66ac4ea50d4e14940ad5d7888ed036c0",
          "md5": "3cd9f5dd5e0cc211259460f210591330"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31703,
          "sha512": "a3e85cd92c29546a9d03c70de257bbef807b602f2768b7f496c07657f76c6b5124317d8cdc4c03ec5e2664d8f3ed7eec52c578913c7f8f3b6bfb8a497f30d662",
          "sha256": "db491d2bd11483512d7aa78169aebece1948682f9bc53ec470edb6b511d3215a",
          "sha1": "4fd1c1aca3605e6f5ce4d01e15b4893b67bf48a8",
          "md5": "65803b298989b6543838eeeb48a9357b"
        }
      ]
    }
  ]
}
