{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 80590,
          "sha512": "d5ff77c6c8f3e9c14e9c5d118686f1253cfa6b5af3c433e24a0815150c558b77e21b6d4885526678e3064ae04e6f365c73d4083956335d03363b9810ee3019d2",
          "sha256": "1a03b652448dc9f416cad22a931e8c3221529856ea9ff3658a34690292fa1dcc",
          "sha1": "56ec91f43825ab2e43970f490963dfb64c25ad3c",
          "md5": "b4847afba96496a83fd494194a501ce0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 80590,
          "sha512": "d5ff77c6c8f3e9c14e9c5d118686f1253cfa6b5af3c433e24a0815150c558b77e21b6d4885526678e3064ae04e6f365c73d4083956335d03363b9810ee3019d2",
          "sha256": "1a03b652448dc9f416cad22a931e8c3221529856ea9ff3658a34690292fa1dcc",
          "sha1": "56ec91f43825ab2e43970f490963dfb64c25ad3c",
          "md5": "b4847afba96496a83fd494194a501ce0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 190648,
          "sha512": "05cb09e38bdbf7e3505fe70dbcd80091e18946e932a8411a1d928aeb117e992dd9abd9b29b4572c0118634963c30c51f53f336a8ac02647321f58cc857409fcb",
          "sha256": "5f424f22df7923f843d61d25d2d3794e7cfc9f3c31f556760efac8cb5b5b2255",
          "sha1": "830b7f8be9d17c4ff73afffbf67dc60549a85296",
          "md5": "704e0b0c8c5ccdd94a40bd65aeffe844"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 29036,
          "sha512": "d876b6b84f377f3f19379ded5b4fb56bd6527c756d5484e152faee3c6b4026ff1014ee8dc29857409c4f1897cf8e025de4d6f7cc23c939819f6ab5606f3759e0",
          "sha256": "5b63fff37fcb95c40f5e99fe6956f07d6c4f564bc672d30d71932498547009b0",
          "sha1": "f061be833047515c7e2b5460679c3f9a72f2c7e3",
          "md5": "d9c072c4ea0b180bcca2a93b058b8e2d"
        }
      ]
    }
  ]
}
