{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "4891ce41200dbf60ff8a3e73a018c56dd9ac380c36b878f542a72ea06ab0c49edde4737fc07a3e8205e02869e53a089f66937b04320dbaac87d9b86706d88fd9",
          "sha256": "5f65bae92e38fb8b357e27b5fa1ead55213d72ccddd4ce52f611d35698b1ba5c",
          "sha1": "12019ab52dc8eff8425a4109e197a71296eef7f1",
          "md5": "9d4472fa43f393610fb64dd695b16cda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "4891ce41200dbf60ff8a3e73a018c56dd9ac380c36b878f542a72ea06ab0c49edde4737fc07a3e8205e02869e53a089f66937b04320dbaac87d9b86706d88fd9",
          "sha256": "5f65bae92e38fb8b357e27b5fa1ead55213d72ccddd4ce52f611d35698b1ba5c",
          "sha1": "12019ab52dc8eff8425a4109e197a71296eef7f1",
          "md5": "9d4472fa43f393610fb64dd695b16cda"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "7ff1ccdac29d2708d9781f1eace86013d431aac4ad5af24d09b5159bbe894e8b5b0ef50fa77d7c20852065ace7be62eb976a9860cf73533d4a5428c1c77d9007",
          "sha256": "e8a91650cbe9caac5c1a6c4f847c5ae6a010f240fb585c9db6e80286065c15d4",
          "sha1": "e5956f9605aa0449794a06efc8e2f37a48d0df13",
          "md5": "391ff958dd3fc131db3be7381264c0a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "c3bbbdd147f48fa5b7544b0c353fe941f04703f574383dabc56ceb97f3ce48234e8e6f34e2ea7016f9311f89dec5813c1ac7fb358eefe7e68acc0315c3b3fbf1",
          "sha256": "3583c6c338ccd7a84431810a5d73aec4922fa296ee638082c7d0a9a0443ac517",
          "sha1": "42a47499ea9113115a899ee3e8cd589e2a9d9a49",
          "md5": "3c3a09703975640411bfce8ca4867d27"
        }
      ]
    }
  ]
}
