{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 81532,
          "sha512": "fb2c8eabad672de45456b1dd13c435b7d1c7508babfdb9dca29f87772dbd191776d9fbc33ff25658e79cc21054c3e03074274a097760a389e99113cdeb11d7a0",
          "sha256": "04a9221cd00c1b63c52695df64bae5098c4d12be225da4d1b981a5edca949034",
          "sha1": "89d84356b4a7cb7d28ba181b27f844c63a0145dd",
          "md5": "7b4a935405b2de436a4a0614f895b324"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 81532,
          "sha512": "fb2c8eabad672de45456b1dd13c435b7d1c7508babfdb9dca29f87772dbd191776d9fbc33ff25658e79cc21054c3e03074274a097760a389e99113cdeb11d7a0",
          "sha256": "04a9221cd00c1b63c52695df64bae5098c4d12be225da4d1b981a5edca949034",
          "sha1": "89d84356b4a7cb7d28ba181b27f844c63a0145dd",
          "md5": "7b4a935405b2de436a4a0614f895b324"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 190647,
          "sha512": "676ebf281f249199e8dec217d1f20af3bd10cd9df03eaa08f1cf9b7fbfd1eff1066a1ec0afe066fc2220187f0346b362e54c750535d46f9520d36df6a00d9654",
          "sha256": "330d81dfab2961e7b719fdab82514bd40e5b7d59d420bc7fde5bce301a6746ff",
          "sha1": "57f385afd5b5e388d67edd3d6f57d52574c6dd73",
          "md5": "8c4d781ebce4c424ea7d7b05832e57f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 29114,
          "sha512": "4c3e48623ac119e5b2cfe96781cace6a7ef937fcedeae79af1193de64bfff65d26ba8c4a4900637fb7ba8057ed11266ca363fe1a0a01e48bc9d4f42aad8144ce",
          "sha256": "af99f3f1cd6307c5304796a158bc13846f0196b4690dafad590f27626b9fd5dd",
          "sha1": "ce8960e2e782f02486321b9f84c16acdd6c66be4",
          "md5": "4f8568a7be43c446b382a5915e984af7"
        }
      ]
    }
  ]
}
