{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "1078ffba9763bfc388a2a56dc0b882f91d0dc0679c9699f0837df0721aeffbf5b24a0bda32e6fe1def63f66ca9d314b5b713fdb6f3794b89f42a170f41db8370",
          "sha256": "3448c0efd85097807b31b9ba5047711b491e217a16298350b60377cbfc52873d",
          "sha1": "c42e9ff7f2d856aec076d00e2e4b8a950136f38a",
          "md5": "5b04c9c990dfe89b13d6088b7a43d6f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "1078ffba9763bfc388a2a56dc0b882f91d0dc0679c9699f0837df0721aeffbf5b24a0bda32e6fe1def63f66ca9d314b5b713fdb6f3794b89f42a170f41db8370",
          "sha256": "3448c0efd85097807b31b9ba5047711b491e217a16298350b60377cbfc52873d",
          "sha1": "c42e9ff7f2d856aec076d00e2e4b8a950136f38a",
          "md5": "5b04c9c990dfe89b13d6088b7a43d6f5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "5b4a4d39c9555599658b6a97ed34f9b391693a834bf77e5107d6c470af9901c9b2c77e8b462fcc77e383b08f756da7b02a55b2f959c50b1fc7921d03eccba649",
          "sha256": "2030c08693df93e4dc17ef90b514532261857143ce81e41f92c33966e835df1a",
          "sha1": "c82e9ad1bc79302b7ab1e9bfe9159d2c62a07e84",
          "md5": "8e3c335caba94ac4c5085c9c5d05bceb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "65ec5a8bc3f51fa6b466106e0198857112fff30f4e0bf0d3c5c1be1e182e28c24f6a8b45c52f52c541e7019a6263718b5d2ca179e689399ca85d320a8e3b705e",
          "sha256": "bd4c90b63e89a4cb0cd509e7321e08d225a15e355f046bcaafd597a00587b603",
          "sha1": "a4eb01f52e4b323389dc459b9be289e46a71fc3b",
          "md5": "13342ff5c21e643b42a9633fae533911"
        }
      ]
    }
  ]
}
