{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "6599ed1b1b2e17ec10d961d340dc9b31205219316a6d2239fa50fbac5e6b687cc47a0b7ad471ca5c2245da42ed9dd90adcb664375ca727224e28a0dc64263a8d",
          "sha256": "0816eb7db9348829d467294c774a913b2e763e7ab16b943de148bbe9f528a55d",
          "sha1": "8aec497bea3eca4e13354315520a6aed057c63e8",
          "md5": "4f681749d0a9e44a45a5d2975120e5cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "6599ed1b1b2e17ec10d961d340dc9b31205219316a6d2239fa50fbac5e6b687cc47a0b7ad471ca5c2245da42ed9dd90adcb664375ca727224e28a0dc64263a8d",
          "sha256": "0816eb7db9348829d467294c774a913b2e763e7ab16b943de148bbe9f528a55d",
          "sha1": "8aec497bea3eca4e13354315520a6aed057c63e8",
          "md5": "4f681749d0a9e44a45a5d2975120e5cd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116717,
          "sha512": "a94cc312216f351a33d80dcb3912d55f1ec1d301097abbeabc28d8548b2c2cacba68d79367ea7d895285103ccf5359642a447b521d454619ff7c48fe07694d7b",
          "sha256": "4e7146380141747cf17fc57655e19a57353dd85cdc3296bd683c553555fd5392",
          "sha1": "00d19789ff899dc7ff41ae8f0ebc04dda6c71f9d",
          "md5": "e282b6fc6089206c837b66c3d4ca4c1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "34db945934de2b4c6d8620c8171abffafd574c5e81126dbf50f448a42d8759256f7fd507f15882adb105a4b4ebec48b7a01f2a9cae89ef61b9277ac807455a3f",
          "sha256": "f51f26eb22ff18de45de6677f181c26550f0dffb85100d147854845d4a198df8",
          "sha1": "337e7a60c3f9e78c5a3de8c68db68c232aca336a",
          "md5": "6a00299c9d1194af6c4a895a5975ce57"
        }
      ]
    }
  ]
}
