{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 80590,
          "sha512": "760b4a23eac0baf9615084f8165c28439f8ab840ecb9d6c3856c93c405cb931a826f05c9f4acbf6d79b7cbb1bc62b25a928ab812c72f2970e17a73bfa39d495f",
          "sha256": "8c2de9dd5d7e1d1151d63ef9cc6a680e4503ece83def9a4ea5f519cdbc64447c",
          "sha1": "89b5f14edf62ff46c8ee67de2526752e98010658",
          "md5": "10644b88e9527f2d6eb9bf1811e6ac71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 80590,
          "sha512": "760b4a23eac0baf9615084f8165c28439f8ab840ecb9d6c3856c93c405cb931a826f05c9f4acbf6d79b7cbb1bc62b25a928ab812c72f2970e17a73bfa39d495f",
          "sha256": "8c2de9dd5d7e1d1151d63ef9cc6a680e4503ece83def9a4ea5f519cdbc64447c",
          "sha1": "89b5f14edf62ff46c8ee67de2526752e98010658",
          "md5": "10644b88e9527f2d6eb9bf1811e6ac71"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 190647,
          "sha512": "bce57e6700e188db9a6937d7495d886ccf7062c3da1d9d173a31ce875698920de38a7f5305b5fa1352e00de7bacc8c82ab02b09b57a7f732d36d0423416619ee",
          "sha256": "c1ce5a0d19040a490f104e622cb9664ffdb4a9d3ef0d2e624c0da6a08e437c29",
          "sha1": "907c35fb24cf777ea85f6c4605dff4dd7fbcc6ca",
          "md5": "942601222c58b00b12a1d53869773dd1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 29036,
          "sha512": "7f46791090a5077aa40abf8421486f5332f6d761c21cc8f86bd45d7ac1364619a91a2f8013897536065ff50774068b05fa3bfafbf14d5f47ef8a57aa9db49aef",
          "sha256": "703e7fd332ca76b40641a35b08668352486fe2cae05f59c88ec6b2d35f568237",
          "sha1": "274fcc89816b28509e825bc23413f3f72bb26bf4",
          "md5": "d442b2555585f76faca82fea74e034dc"
        }
      ]
    }
  ]
}
