{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "1a3d0168ed4290ef8a9c4db328ffd77bc368dd7b81ec2f745096b073b823e7ad2cffa8d543bfd08e98902e75b0d6809b9c8881ee7905a2680ea00c1f460a6c22",
          "sha256": "d8c91838f73d417bd6e829236904bc0a45dd88e961da5031a06b8971f9f3d984",
          "sha1": "c1bffe3be581dc41efb6fba2d6f6cd832e08d94c",
          "md5": "4d28f4996e26f88da5a5b4910f969716"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "1a3d0168ed4290ef8a9c4db328ffd77bc368dd7b81ec2f745096b073b823e7ad2cffa8d543bfd08e98902e75b0d6809b9c8881ee7905a2680ea00c1f460a6c22",
          "sha256": "d8c91838f73d417bd6e829236904bc0a45dd88e961da5031a06b8971f9f3d984",
          "sha1": "c1bffe3be581dc41efb6fba2d6f6cd832e08d94c",
          "md5": "4d28f4996e26f88da5a5b4910f969716"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117552,
          "sha512": "34eef1b3df4c708ff08ce3b15c01e4dc6f1c71d496a549a75e67fea55ed041350289fc669eee188115dc899ffbfa5f74ef5e6d388fd3db77d15ed1dfd0c88351",
          "sha256": "f1774d32ecdffdbec9f26c9500a5b8b3c8f627fc92d78cf8a8bcc2c9128fb1b9",
          "sha1": "d0abed452a1caade7216bc35a17e44b4e4c5c388",
          "md5": "2cb533c51e99619c85f1c2e13b8348f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31680,
          "sha512": "4a515b1efc62c1aab83b0e42fc88b226a65bed7f9f82bdcf5d4e676ae3c005692f31a5134278cd7ca0bf5b2ca43415bf736a79b4cb9d05bee2d70249dd6362ff",
          "sha256": "d696f20215ca04afbedf6c6dcb349520c95b54d367945b7fbc60141d3c03429f",
          "sha1": "cc68c133ef2cee30983be42cbfd6820334146c8d",
          "md5": "fcb621ff08495e193b236830f13afb3a"
        }
      ]
    }
  ]
}
