{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "2b3be705552bde24076bd5ebae774c4ea5bcf519d32c4036e719ba92b73f7fe193a805d41a1ce43345b5c82058e6f77ccec574f0cbda0601cf9cb7aa973a5504",
          "sha256": "848da5a157e321034e3d22cfc579588e0d42866fe7e9848c2f78b517a1354032",
          "sha1": "398f8bdc0b3d5cc3b3d4fbbdcf4c1875421206ba",
          "md5": "5a19dc5195c9a03a2f9338f8d55db2cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "2b3be705552bde24076bd5ebae774c4ea5bcf519d32c4036e719ba92b73f7fe193a805d41a1ce43345b5c82058e6f77ccec574f0cbda0601cf9cb7aa973a5504",
          "sha256": "848da5a157e321034e3d22cfc579588e0d42866fe7e9848c2f78b517a1354032",
          "sha1": "398f8bdc0b3d5cc3b3d4fbbdcf4c1875421206ba",
          "md5": "5a19dc5195c9a03a2f9338f8d55db2cf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "62ecd73679888695edf19bef9435d6719e5f4f1722ea63858ed3cd135917852644582393918037178fb07b4fdd6d58941b8b3de29a1845dd1969fccb020bf6a7",
          "sha256": "2876b46c88e1335003de9e50d4214e0786e47700b47ec63f6fbcb12382daf039",
          "sha1": "3b0f74c91c91393c5bfd3f9e2a0057da779aef0c",
          "md5": "1d5a4f76012773f71634c75c928cccdf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31703,
          "sha512": "0265c8f7d82cd030fa1efa1f2e02313e9db435b78ab309fd342e9d169d0c2832aebfa1a1d8ad200ea53323a11514dbabf097cc674c1dff40ab51eb7503ddce0b",
          "sha256": "d8b1f088cb6faee2350d9724f1222f29cde68e6321c17b9b0599114fc8bf32dd",
          "sha1": "57be1f18416313cefe5d0a9cd5f025d8ff92d24b",
          "md5": "f9ed0c3216142823b090f2f76ec36d4a"
        }
      ]
    }
  ]
}
