{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "56763264052b4c50444bd70bcf313030c69d1a0949b2ffada46966b12e8a3bda6dedececbd471fdbcccae3a347b36ef2147a057cbdce324a0b9fafa9f9cdea54",
          "sha256": "c08635cb91ae0ed84dbe7f1c1d6ba88a23facdd433cf9cc203ef41fe8995d7cb",
          "sha1": "4f8008fa972856a00002a25ab02db108e2716d4b",
          "md5": "b287db2fe329868494c5cda5b0e5569f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "56763264052b4c50444bd70bcf313030c69d1a0949b2ffada46966b12e8a3bda6dedececbd471fdbcccae3a347b36ef2147a057cbdce324a0b9fafa9f9cdea54",
          "sha256": "c08635cb91ae0ed84dbe7f1c1d6ba88a23facdd433cf9cc203ef41fe8995d7cb",
          "sha1": "4f8008fa972856a00002a25ab02db108e2716d4b",
          "md5": "b287db2fe329868494c5cda5b0e5569f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117552,
          "sha512": "f683dbe5623eadcf449f8ffd7991d93606763d1a276d62e7662da23763ce7f83ec7daefc6aa65609200583e4757f3be7c496c83e560b05ee1897cfe194519847",
          "sha256": "592481710cf48db10fe121be40ebd99e4255793eb328842496c049b8308ac4bf",
          "sha1": "aa3668583c5bfd59d6469eb465846cc8e9824baf",
          "md5": "23a1bc5bcbbc1687c371eb09ae34a756"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31680,
          "sha512": "f59ef4928e6afa42520f6f4d8e977c2e0d97d1eea1e7a09ff48e788d2782cea8166fe3da13156a5fe40b363e5478383df793719ef1f09153d39ff42b5d1b0f48",
          "sha256": "9d0e4b86bd0187061658460ad39e4f917356873c323eee4f0ef1be529ed71a07",
          "sha1": "5587db5a72d28d6ff36698c69e23b746094a1d73",
          "md5": "9c6fba0b33fa3191dbb61e01831da453"
        }
      ]
    }
  ]
}
