{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "a9616af42fdc9f66c6d78130e81af4dbc6953c980210b8f421cf35f4a0690487a720e3028bb5b94c7a05b195ce601968358bea3059b78be17c936b7651625e03",
          "sha256": "d39c32a9c6c1976b9830fa2ba28b8691d8e846495c8d259838d33a995e21567c",
          "sha1": "38fb804de809be684986948a491f8d49ee7d54f5",
          "md5": "5eeccb49a266d8fa609dab7f16fdb81c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "a9616af42fdc9f66c6d78130e81af4dbc6953c980210b8f421cf35f4a0690487a720e3028bb5b94c7a05b195ce601968358bea3059b78be17c936b7651625e03",
          "sha256": "d39c32a9c6c1976b9830fa2ba28b8691d8e846495c8d259838d33a995e21567c",
          "sha1": "38fb804de809be684986948a491f8d49ee7d54f5",
          "md5": "5eeccb49a266d8fa609dab7f16fdb81c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "65f36affeceae776cb4525bcdc75aa8c7143c2f71992019c66345a79ef2bb7a3e42c17e8cc4927c18f6086c6e20212ae724ae707eab47ec1980e42400711784e",
          "sha256": "798df916c12c3e1899bd82e2fe83fae21752ff3594156f118a67f2629b37575e",
          "sha1": "66f9a1bf09335025d4c2ec8a2b4ca6f2e4cfe439",
          "md5": "79768a564e6a31b02f77b1734c05727b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31703,
          "sha512": "c4d1299b3e2fc5c3d237ee8f993f05bafb4af9362527c4e5c15964148ffc7a3c9bc408901c1df0ad3692d025307a1c601926e471e0f16e393f129c46784f411d",
          "sha256": "a977b021db9a2b818dcf73974b971eec3c579cf21e7dae4143bde7a1ae8cd3b0",
          "sha1": "dbe83d5b43663aed57cf2813b111530cc46ad68a",
          "md5": "8636dd1fd603f4e2d193981048ddbba7"
        }
      ]
    }
  ]
}
