{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "59eba964fe9ee1d5db6fb1899d6d345940c61b5aab55ef3fc60991d218449d6cf24c7c49465a1b76d6b4d6a3b42c9ec1c47b31e29dedf42c0fcd1fc44fb17259",
          "sha256": "b1c04528fbe813c67b00b771217accefe207c55c6e53d49a53a8b700c7bc8ad3",
          "sha1": "2df19f7e811d6220c060127002a4110c940b6f46",
          "md5": "b8ebd161c8ae2fb2cc1bfec184cca0d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "59eba964fe9ee1d5db6fb1899d6d345940c61b5aab55ef3fc60991d218449d6cf24c7c49465a1b76d6b4d6a3b42c9ec1c47b31e29dedf42c0fcd1fc44fb17259",
          "sha256": "b1c04528fbe813c67b00b771217accefe207c55c6e53d49a53a8b700c7bc8ad3",
          "sha1": "2df19f7e811d6220c060127002a4110c940b6f46",
          "md5": "b8ebd161c8ae2fb2cc1bfec184cca0d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "7bb45e262414922ec94134a5a154690ecaa5a6ce253a459d6385e25f57eaa8917ab4d3ba02f42b7e253d18bb30390c224fdde7186e379e18b472c5dad1af38e5",
          "sha256": "7197092caedc2bfe41aa985cbfdfe29bd8d1732dee7f3de14936734686d53e8d",
          "sha1": "cba8b149e425395870f1417093e6dddb93e596f7",
          "md5": "1528876e6d18bdd8dadf57dee4403292"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31703,
          "sha512": "3f113f9baee946d9d36183ade2d49272fd93e0cc63133a14f35640f39abf94e0efcdbfaef3d315a1368adab165ceddbaf8740f8a4ab470847e12f2100e064b30",
          "sha256": "d214a6b016cda6f3cac97e0de85e1e828883c9c3db529a804f52a4c0ce8f0051",
          "sha1": "0b8d3904562f82259dfd937a46ebab8dc76796cb",
          "md5": "78fc3e8d33b87eec56ab0f274b2a1abd"
        }
      ]
    }
  ]
}
