{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "50f59e596f57d70b70b6d9b0da14233c5fd552292630d1c4460370eef829cab21f0986c2b4a12cc5b9af958212198015635400ef33cfc972cc4c54c4bb62857a",
          "sha256": "5476044613c63c8945ed72e2c4f1f44c0f55fdf2f02fc775614998ddad3ff817",
          "sha1": "7e307332a99595ee4320e966700d05397b02c903",
          "md5": "65deb5f439edc33ec01811654989ff93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "50f59e596f57d70b70b6d9b0da14233c5fd552292630d1c4460370eef829cab21f0986c2b4a12cc5b9af958212198015635400ef33cfc972cc4c54c4bb62857a",
          "sha256": "5476044613c63c8945ed72e2c4f1f44c0f55fdf2f02fc775614998ddad3ff817",
          "sha1": "7e307332a99595ee4320e966700d05397b02c903",
          "md5": "65deb5f439edc33ec01811654989ff93"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "7ef0697f96e63f718113b690953f65aad065a3b992014df46ffd6bd95be9bc21f04029c6743f7899e991159490a81cad4e93689890323b2239a96850c126251f",
          "sha256": "1a42bf07131e90420826b6d1d3c81a9fefb7c014f0efa0e9f9a19b1f3681ea6d",
          "sha1": "d1b779732aaa7b8f091c97f33257e59e04500bfa",
          "md5": "41d0e83c1f13909fc790d6e26622eb8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "38923181bbb052ef34d7ca009d5f16119c19f5123bc9c44fedf724f07d5270bc9167b13fda5e0ba6ea406e89b5b4202337443a567af72faac6aa700c56e4d71d",
          "sha256": "94e05dbc2319249656a960cadac4baabb9349612ac9aab35c9ae89ac70de20bb",
          "sha1": "60831b02281f4c712b58844f50f7498f184e5892",
          "md5": "3a4afc182f8c7dc44bcc18763e697ea7"
        }
      ]
    }
  ]
}
