{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "c1e450bf70ee0ced6e85525e4c6f2099759d3856622147f36a8186f0d5a4088c94131f6fe1746774bdb5b6ae001c0dc3ab110f22c1e349d1dba2087211dd02e1",
          "sha256": "dc4fe73d925b50b7220c4fb482d039594c36da7ef299845caee4b4dcb1812c1c",
          "sha1": "0f51bfda04ca8fd92c68708c2e4e1fe55c0fc807",
          "md5": "258fb08fa69262b9daabac14ea2af49f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "c1e450bf70ee0ced6e85525e4c6f2099759d3856622147f36a8186f0d5a4088c94131f6fe1746774bdb5b6ae001c0dc3ab110f22c1e349d1dba2087211dd02e1",
          "sha256": "dc4fe73d925b50b7220c4fb482d039594c36da7ef299845caee4b4dcb1812c1c",
          "sha1": "0f51bfda04ca8fd92c68708c2e4e1fe55c0fc807",
          "md5": "258fb08fa69262b9daabac14ea2af49f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "9ee351a1be10897f0700880e037111fec4a82c539a41afbef93fc34bbf6c811823aced039778b1b4e2cab86790f3b3f277100571cfe4b24357e2535ebc1878d5",
          "sha256": "d8ec5b5a6b4009292a3916c463d799b33576460063634695bc5d0f0f2f4c11cd",
          "sha1": "129606c286c3b0e51b63ce9d57fe1204852c52ae",
          "md5": "aca64673aae0789d72ba16fbf2d03d7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31703,
          "sha512": "6bfd363a1cff645a88e161f57f13cc63e2ac7222ce6932d473c6efbbcbb689aa9b8b1603d6e906bde4a0fd9bf30d47b050891d649f5315fac8f181b7f467d171",
          "sha256": "d5556d2ed204013ad64ebdc66974dbcbc6decdc9c19de1bd5185017247ad3a09",
          "sha1": "12c99bb36028ad9db1487d251abec5581cbf0e61",
          "md5": "553d9b6a1f41efe31d67a68184e4325a"
        }
      ]
    }
  ]
}
