{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "345436f9e09e6da058aac8f6b93593aefbaf5a319d6bf3c698bf6605af4122e2c4dad6ac3355964e82cd0b91cd9de44c11c63963d6cace016d4d82491329c00b",
          "sha256": "15cb9bc149dba93509cfa1f43e15b352f9be0f830de00710dd668132998f7658",
          "sha1": "41d8510a0705de4ce3d8b83e0d1af5c036d0a64e",
          "md5": "b35b48533459475de4de822d54273c1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "345436f9e09e6da058aac8f6b93593aefbaf5a319d6bf3c698bf6605af4122e2c4dad6ac3355964e82cd0b91cd9de44c11c63963d6cace016d4d82491329c00b",
          "sha256": "15cb9bc149dba93509cfa1f43e15b352f9be0f830de00710dd668132998f7658",
          "sha1": "41d8510a0705de4ce3d8b83e0d1af5c036d0a64e",
          "md5": "b35b48533459475de4de822d54273c1f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "bbc4710ab9f79eceafff14ea56e0aab05fb8ea4fd76f9c1eac89e9ed3674184c8f102f588ab5f566780ae777d8a72e472baac50c19b7b17bfe836a36abe0006d",
          "sha256": "86346f7160d9b231c05d84d8ce0e590ae858edf7ca9dac9b659f9841a914a9c0",
          "sha1": "d626cd765c948e16e226fe3adafebf7df2c4479f",
          "md5": "66338da614f63bd2315b4da21a36a76b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "df385622df3b911815d026c949461d0fdc2c788d11bd6a936e848a25d4fa02a68737ac3403141ce4035f53e61ba4ffedf0653291d9baad8c1b269489a9e50c1a",
          "sha256": "5095c1a74164ef3b9b6deaa9be463d39afb72141fc46746c40690ba81021c95e",
          "sha1": "0f43a2f7273cca119c1f59a3922d5e6e0c6e8fd2",
          "md5": "c8062f544a3afb797d10c2dd55463241"
        }
      ]
    }
  ]
}
