{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "8ea5def5fe80a1547cd1f0066fc2a963ac1689cc5e44c6c3f8f18577ea42fff4cd8e24bea64fe67d4a266a2df4c3812c2cb8d19cdeb78ea76946e234cfa14d31",
          "sha256": "2eb2bfda88a04e12ad7e0096c336cc9797118cec9f3a8a93a0eb7cced5a96d47",
          "sha1": "7b47e91b4556a25b739d346f937ae75042eb8154",
          "md5": "490f0bd3eac671bca071d8538c23c5ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "8ea5def5fe80a1547cd1f0066fc2a963ac1689cc5e44c6c3f8f18577ea42fff4cd8e24bea64fe67d4a266a2df4c3812c2cb8d19cdeb78ea76946e234cfa14d31",
          "sha256": "2eb2bfda88a04e12ad7e0096c336cc9797118cec9f3a8a93a0eb7cced5a96d47",
          "sha1": "7b47e91b4556a25b739d346f937ae75042eb8154",
          "md5": "490f0bd3eac671bca071d8538c23c5ee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116882,
          "sha512": "c5e07dd89a99199a10cec2c5c8728ca40153cdb814c7042694b7549b4f996e4ea9ccbfe561ccec022f6616a847ce2054b7514b3604811104a0d17d99ad2f1884",
          "sha256": "dc563420defba2622f0651a97009792d6b13d4bdb809c3f0484b93c02e4e5b26",
          "sha1": "7321d4420e76b6934ac4f1e2de66dc6dc2cd533d",
          "md5": "dd6dacac893ddb2fb44ac1e702f9a173"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "df462ba9e881efa1be1d800d9321402e1b7efefac23cd84f5c7940bef22ffc945c4e58480f0ee94c526243d4eb714671f2988f7e8870ed404c89ac7b617cea69",
          "sha256": "a399174930b4d0315a5d8cc5cc059304ec3cc4493fe405ab88b7f6a60afdda56",
          "sha1": "50ace9093b56f2e63b1acdca46e4bce6b3a3718b",
          "md5": "0433b07a31c2585ff38368b1d9eb7326"
        }
      ]
    }
  ]
}
