{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "a1c0bd7bcef0624a4ca400b9e3dae2172b211b0a9f95c10332e933c532b0f5f26914c57fdd3e8e7d3c3e830845c5196cba83ceb925f364bb3928b486f3b53940",
          "sha256": "913f007f93614ef0d8daaf77cfd345382f4b5b95101827005e1f7b2dc75df5e4",
          "sha1": "e981502ea7cf543dfc3cec92eab1142ab4f63d9a",
          "md5": "8d453f188ab5e497df2a2eb9711474c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "a1c0bd7bcef0624a4ca400b9e3dae2172b211b0a9f95c10332e933c532b0f5f26914c57fdd3e8e7d3c3e830845c5196cba83ceb925f364bb3928b486f3b53940",
          "sha256": "913f007f93614ef0d8daaf77cfd345382f4b5b95101827005e1f7b2dc75df5e4",
          "sha1": "e981502ea7cf543dfc3cec92eab1142ab4f63d9a",
          "md5": "8d453f188ab5e497df2a2eb9711474c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117552,
          "sha512": "2004a743310302936efbf47b2d0acae0a386c147edeff503697686e2896b4e81801c7de8882937786873d4688ac5c7c333024863d151f86dd75d6e394dc38332",
          "sha256": "513808c2caa1a9ac332ffef19dc23bbbb659d2bd91d4f3019866e6b54713ea88",
          "sha1": "600088b1aa5a2e521f37b9efe17da9fb8511fd80",
          "md5": "ee135ddb2fb50671f20ea5402868cc92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31680,
          "sha512": "82ad1104709d114a12518c7bfb8b1d81eddfbaf46877d63cdb726c08d1c819648202601c713cbb06601ac6bb39516014a920e1ff0eca434084e66ffa443b18cf",
          "sha256": "8a80d4a67dc1da957d4f29f38c87db99c604651faa72164040b1650da23c5452",
          "sha1": "09840494cfa41baef37059343fda2fca4c64959d",
          "md5": "0977333b23e7c32cc39695291792568c"
        }
      ]
    }
  ]
}
