{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "3e2ba31a758bfbc0c00cde8a6ae13c1ec0355c3b680f4bb5a773ec7f4c3a7092e363c102a724e1eb23c4c97c4d95acb404734928948da10a53327a39f6670345",
          "sha256": "b49a4f23b3866be14aa2245f9728cd71c9da42e7045ec025e08640c844226fbd",
          "sha1": "37a229e8decf6f2fe982dd2cc5e7092f572a84aa",
          "md5": "6ddf70c0465c52c225fb7a1f734ea895"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "3e2ba31a758bfbc0c00cde8a6ae13c1ec0355c3b680f4bb5a773ec7f4c3a7092e363c102a724e1eb23c4c97c4d95acb404734928948da10a53327a39f6670345",
          "sha256": "b49a4f23b3866be14aa2245f9728cd71c9da42e7045ec025e08640c844226fbd",
          "sha1": "37a229e8decf6f2fe982dd2cc5e7092f572a84aa",
          "md5": "6ddf70c0465c52c225fb7a1f734ea895"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117552,
          "sha512": "9021fbb47f8a0c6c87cfac7a6a3c29313e82b624a0b11f04db45885ab83903894c89fa67fb9ce1c4d6d008a8424e555114435961f628b94c51a522838c8c64e6",
          "sha256": "039924fc0039a1d4a62df2eb4de4bedf1e95620660fad61f8176b87b61889e16",
          "sha1": "10c31fff4d8e49d7b9133747724782c2f3fa999a",
          "md5": "c35f55784b6d62271c71d41f039029e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31680,
          "sha512": "cef1bdb5784735c9b587649d581aa0c81cb8a199213107b7bdf73e7878269e82695975d771f36a5d2fc60772457b3d21f84c807e405f57645c7d9b0f0ed9f595",
          "sha256": "32b6e7704e4bdd1c4968f08299b18cbe148e6bb4afbe6ae8b10b0e8e5c8b681a",
          "sha1": "1ea9997a2392929d964ee1a6b971b6fc6e2ef39d",
          "md5": "b6490311f90ed91d5f5aae684dc91458"
        }
      ]
    }
  ]
}
