{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "7afc1b77e8c8d4b2da3601e4e08c293691ee08c47f3b40004a51f3f578b4b5ee138e62c090976371993b1c9c0800d2ff079112e3802353b457e5dd7f3094706c",
          "sha256": "ef6400382f18cae1d36fd96f5579d01df08c8ee52caa61a91fdc532cedf85f17",
          "sha1": "413cd6570210b3fd4b1d1a68cff39563657341cf",
          "md5": "53f5ac3b3a2720c43ddcba4ef479fe06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "7afc1b77e8c8d4b2da3601e4e08c293691ee08c47f3b40004a51f3f578b4b5ee138e62c090976371993b1c9c0800d2ff079112e3802353b457e5dd7f3094706c",
          "sha256": "ef6400382f18cae1d36fd96f5579d01df08c8ee52caa61a91fdc532cedf85f17",
          "sha1": "413cd6570210b3fd4b1d1a68cff39563657341cf",
          "md5": "53f5ac3b3a2720c43ddcba4ef479fe06"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117552,
          "sha512": "ab2baacb63b5f5000ae626dd9fd5661becf0c1e5d2398c10c4660f9271824bee53e90fcd7748fd6d69d7dad55091ee0bd469295c56a903d86df656c7639540c9",
          "sha256": "20500083c37cc75b31385052253da219e2fba5f79c4e7530935a5ee78e6d4e7b",
          "sha1": "25fe69426e41c91ca7f0af1be991c63f02c4b3e5",
          "md5": "1b85370293b6eb5617aaf96384788119"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31680,
          "sha512": "b35245ffd63fdc389f55ac6c55cf3391200d5faeebd315544cc8d95301b451af67023ec952b362cce70b5d0f6cb330e5e724cdb9d96b8d1630a9a0161a9d6833",
          "sha256": "3cb30a62c10359f8d4469b8f3e0deaf068b6fcd15de472c0f5652b178cfb2569",
          "sha1": "7a4b747aca7aa2ffeddbcd63e7ffb3224bff9d4f",
          "md5": "a5d81ad057db1b8678dbc242bfa68abd"
        }
      ]
    }
  ]
}
