{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "b84c58da70c50ff43e67a8db09137f40d0854a3233e8bdbca37f022f39c93a28ce2fad9cbfec130d4e4c12715006472aafa934d66445c2de2c7e1d1da7d00591",
          "sha256": "70008be1c90809f0e83b5afde0819ed888843a7a891a17d378c105823c9cc345",
          "sha1": "e6e2d4311c8dc3dbf136929cb6a03dc6bad8ccc7",
          "md5": "88d4e5b266046adfa97109657d0655cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "b84c58da70c50ff43e67a8db09137f40d0854a3233e8bdbca37f022f39c93a28ce2fad9cbfec130d4e4c12715006472aafa934d66445c2de2c7e1d1da7d00591",
          "sha256": "70008be1c90809f0e83b5afde0819ed888843a7a891a17d378c105823c9cc345",
          "sha1": "e6e2d4311c8dc3dbf136929cb6a03dc6bad8ccc7",
          "md5": "88d4e5b266046adfa97109657d0655cd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117552,
          "sha512": "a84095c50e1fc5a2331553fcd9a336be9da98fbd8a3acf3a3c913934d5eb09ca71fc7ded31d9a386ca1d82e18443a644f3298f447884f12c160287fd97dcc65d",
          "sha256": "c3f17f6cad307e01fb7b47a24e388c03c256fef290e0654eaa75683faf4293a5",
          "sha1": "6a4a90c42522b60e2339f47642bad21ccfd1c6bd",
          "md5": "9b99cb8a3049de32315517d376007219"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31680,
          "sha512": "cee1ed6d0a7bedcebc4e7856ac9f7d5816ef54e30f522c52ff5c94134edb15d9b905c59af34feac8e6c7e1a35abcd6eefa765e95b75decb46cb076e20e15c07e",
          "sha256": "6a48b0e98349b1a9efc8590f5b9dbead2e29a5cd6ea420dd8471f8ced463bb45",
          "sha1": "39bf2a2fac9da43dc7aa5cb1ebca41bcf1ec385d",
          "md5": "e5148688be7992b38547421b18cbad31"
        }
      ]
    }
  ]
}
