{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "64ee935d575968b39eeaa6f35e89b93e38e9a4c7b9ffd1b1873fd1f093afa9871fe34eb6d011f2d12b30d834aada72ce71eb34913d4b50beb04c4c2741143081",
          "sha256": "98ac519700cb0dfb629c48eb6eca3c47dbbab5dd46d5dac4d15fcaa0583d86e0",
          "sha1": "cb9cf6b2e5962b9c4fe453aa9eec63ece777a4dc",
          "md5": "dd372316b46a266f8d930b62e746ca21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "64ee935d575968b39eeaa6f35e89b93e38e9a4c7b9ffd1b1873fd1f093afa9871fe34eb6d011f2d12b30d834aada72ce71eb34913d4b50beb04c4c2741143081",
          "sha256": "98ac519700cb0dfb629c48eb6eca3c47dbbab5dd46d5dac4d15fcaa0583d86e0",
          "sha1": "cb9cf6b2e5962b9c4fe453aa9eec63ece777a4dc",
          "md5": "dd372316b46a266f8d930b62e746ca21"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "d7b753b104e2a4b57f2efbe28fa232c2688f4f65224bf0ecc9b1b7d56001b15609e408bcb79ba8caeb45150ba1aa928c40a85957a663766a772263f2b08c27c6",
          "sha256": "71e8954c42187960fa4ad8f34d33261ee2636072e289c0b1966ef53be4f33f58",
          "sha1": "333f41c30435dbd69cf7d1b3069e446d2b15279a",
          "md5": "9d1257f775bfcd3597e6f795ce062294"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31735,
          "sha512": "82050305803d31cc3649919fcd14f1b6066dbd70c0a5764b3c06a78a6504050d3265bb19e375d3abac41bae0ae140cabf4801aa8c42819c1d348e122b1cddf26",
          "sha256": "068884df6286678f84a21b49dc1ed2fa479f0072e90ee02d40d31cbb2f23ea09",
          "sha1": "d3f857e3173c1772f8d4ea38a1c2fcd47a4f11f0",
          "md5": "32ac91060e186549a9f59b6ed23d01ef"
        }
      ]
    }
  ]
}
