{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "89748ac47acc12b7c21df02eb988c3b99a6f79a66cf5976675b140deb54066def0290a24aaeb4bffcd0a61dbd4c84d6e42b483153c5f76d16e7a8008c6df5caf",
          "sha256": "fb2493079af539c1c6c34bb95c43846df768cc88904d47a2d13fe66662b3cfde",
          "sha1": "12ad3f5b70eb766159ee9f78cb766cf8d1f71961",
          "md5": "3c1194410fd531eed961246c948a841c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84741,
          "sha512": "89748ac47acc12b7c21df02eb988c3b99a6f79a66cf5976675b140deb54066def0290a24aaeb4bffcd0a61dbd4c84d6e42b483153c5f76d16e7a8008c6df5caf",
          "sha256": "fb2493079af539c1c6c34bb95c43846df768cc88904d47a2d13fe66662b3cfde",
          "sha1": "12ad3f5b70eb766159ee9f78cb766cf8d1f71961",
          "md5": "3c1194410fd531eed961246c948a841c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "f572bfe7bc49bc506eb8691d2b604796cc0eab95f6d56a455114c180b82be658e5b686a25a608fcd41d845aa33a97b92f1c8efb29855ced94d4534a6b90bfaab",
          "sha256": "5ca5c14d17ffb99864626b600c1e8e4850821cb0c0a1b472f49a0f079db898b6",
          "sha1": "50c7f3c73a5b95b1ce7c77eae45473473751c74d",
          "md5": "d9ce1fce0e11c12623d266c67ed7700e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31703,
          "sha512": "ba8636fa6e7843c32c170e02686c37af3059433fe3ca89a1e06852e8ddf88f7f842fcb8660d6d3e9a4b33a0cce19f3ca04fec7fab3f36ca8b266ca0300e6c9b5",
          "sha256": "fdef77f98c8ba8030201dff2005545530d55ed9768ea7e37449582a025c681d6",
          "sha1": "be04f6667db7f7eebe24779c91ee5a4e0b43bb1d",
          "md5": "a4b9ec90af2f9e3ed0e240bb2f4eb87c"
        }
      ]
    }
  ]
}
