{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "2831fc2ed58b6e1d607835fe9efefaf7b102cc41541872ae1ff12486a5e54d0b5dad340d8ad28d32d313af6e33effc24e45f8281320c7b5b07f1748bb872997c",
          "sha256": "bae9856082a8fd1dac94fd10dd22c81a20a6d73a4904240b8a55b2431bb6a562",
          "sha1": "5f7253ced7d56e2f002f695615a621f79007aa09",
          "md5": "862b66bcbc4a24606c30d1ae50f8baf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "2831fc2ed58b6e1d607835fe9efefaf7b102cc41541872ae1ff12486a5e54d0b5dad340d8ad28d32d313af6e33effc24e45f8281320c7b5b07f1748bb872997c",
          "sha256": "bae9856082a8fd1dac94fd10dd22c81a20a6d73a4904240b8a55b2431bb6a562",
          "sha1": "5f7253ced7d56e2f002f695615a621f79007aa09",
          "md5": "862b66bcbc4a24606c30d1ae50f8baf3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117552,
          "sha512": "e445f7af7eea3f35f8c22a09d027c59ff862de1b554ff1190a6d5fecfef346f7b4bd1a6c04935f13e68725dba75848f3ffd0edfb2cd12ca6dd45eaafdb65a2f6",
          "sha256": "3db4875285fbc679735aa4d4055d01a949830704e07a706c8520f221f2ebc7cc",
          "sha1": "f1e51c396bc9efee6937eff329c324298225eed4",
          "md5": "d8ebde537cdb649b133f1132fca462de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31680,
          "sha512": "695a1f4b996a73bb55241ce7464c9d8b53060d01cb951b4f73d353bb6fcd0a4b4b2f11d9005f06bbbe0a1d974e33b6e6a6c9c08700c018dc6ca998c932f72e97",
          "sha256": "ceb7494c597ec31d6df2df7c091d48d108ba6f2acff0ec40168a93097b213a91",
          "sha1": "259d2832f72a2dc4b359f47f81271b9b28901375",
          "md5": "c2b91643d77b013379ed083de03a99ad"
        }
      ]
    }
  ]
}
