{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "bca7d4bd1b630eca6e52cecc9a4fe2ecae39568eb6729c6d94f425dd8e378a7f7caeedf0217944513ab0f011c827af43af037886beead8a3adf2a59741447d11",
          "sha256": "87ab4fff2d1fdaad2dcd91b3810ab32949b31ed4ade57a58caceb9d905c1f6ec",
          "sha1": "771e8ea889d44bb393cb1c548766b63e3911b7b2",
          "md5": "6f62e662975d9e8eb542d9353686ea6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "bca7d4bd1b630eca6e52cecc9a4fe2ecae39568eb6729c6d94f425dd8e378a7f7caeedf0217944513ab0f011c827af43af037886beead8a3adf2a59741447d11",
          "sha256": "87ab4fff2d1fdaad2dcd91b3810ab32949b31ed4ade57a58caceb9d905c1f6ec",
          "sha1": "771e8ea889d44bb393cb1c548766b63e3911b7b2",
          "md5": "6f62e662975d9e8eb542d9353686ea6a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117552,
          "sha512": "f29f7b89b5f953f9a2e1968163e5694142e6efcf4dbf45f1e8a72d24d37a775cb786ba2e22f2a1d80f955c92f03770d797a33adc51db4a41776a8dc05e064bfa",
          "sha256": "8ebb6d869538a333174c4c0d7c0e8e8464a9eb19252f7ab9f013d3e4605982b5",
          "sha1": "c05787d508e7e0b96ce4b159118ab9e718a7efe1",
          "md5": "efe6854526a6668557812091e2c90051"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31680,
          "sha512": "12843a0c86b118c910781bc98767cf62f7881edf0a82b89f9f8fedcfe79ab06744c219250f4a4e161db64a521df2017e70ea9f96f7a9f696230ceb2cf71c1e37",
          "sha256": "9954f0643bafa88f0c0f7a3823959f282c116ee5cde6f8f8bc52d291f5fcbcf7",
          "sha1": "be1726c75ad3c48c5ca049c2eba1d69831187b55",
          "md5": "fc09fb0f69940dbe4d43c3b67a9b8a77"
        }
      ]
    }
  ]
}
