{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "7e1715c18e61ccedf64887891a80bb6a3801a1cc35aae021d9eef10d08e02a067c018e88e705e780019acda21825c08cc8d0fb0b06bae4443248180db53858e2",
          "sha256": "ebccef5e30c5877e54eb35231d5f0e7b8e39c5440c4d6139dbdcfc98cf515ff0",
          "sha1": "e071a5c3952b3d34ed35524f5d4c844e48fa26bb",
          "md5": "603dc986d8a4711f745f384bb150e981"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "7e1715c18e61ccedf64887891a80bb6a3801a1cc35aae021d9eef10d08e02a067c018e88e705e780019acda21825c08cc8d0fb0b06bae4443248180db53858e2",
          "sha256": "ebccef5e30c5877e54eb35231d5f0e7b8e39c5440c4d6139dbdcfc98cf515ff0",
          "sha1": "e071a5c3952b3d34ed35524f5d4c844e48fa26bb",
          "md5": "603dc986d8a4711f745f384bb150e981"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "88221bc8efe797e1af47f38462e13d2f6d94fa1d82a67abe7599145a1634f457622af7fbf488e74003fa9415db1364a6bffe1de04c9c7b622926f151f37bf483",
          "sha256": "1778d4dfc9fd9967de3d56f4612c7d289bcf277eae11c052e68042e55688d6ef",
          "sha1": "9a9a424b2912beb060ffcbdc5972efa26e68edd1",
          "md5": "dd40bb7470ee8ee771737c074482c4bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "9ef487c061f949af56db57b2dff7a7bb15b1199bc3efc6574c09df4f81368f911ebc62c1d344ab339d5c0a67d17c8154e9a75445655ff1e8a57aacc0e1431530",
          "sha256": "b39c77ab7aad3546d19976160c0daa0f90c489e6fe80faf5a17046347ef3a46a",
          "sha1": "dc09b6dd24703f3d298fe2f7c17b8e30d2200f4b",
          "md5": "bd4f8405b4cf421e0b3311f5691dc3cb"
        }
      ]
    }
  ]
}
