{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "99be249feba5c71c2d344ce37f964000f5a53530cb0d6e545f328dafbdddddd4b2cbc48c04dc600e5e3374d700b0354b376fb1205f3956610fa50fe844a5215e",
          "sha256": "4554e282bcbe8148dff5f9cae599cf6d8169ccb3383ff49b91be14c84737357b",
          "sha1": "075b6acf1d06d894970fcf1b8f43af65152793a1",
          "md5": "b12cc80757d152fea7c27edf730724fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "99be249feba5c71c2d344ce37f964000f5a53530cb0d6e545f328dafbdddddd4b2cbc48c04dc600e5e3374d700b0354b376fb1205f3956610fa50fe844a5215e",
          "sha256": "4554e282bcbe8148dff5f9cae599cf6d8169ccb3383ff49b91be14c84737357b",
          "sha1": "075b6acf1d06d894970fcf1b8f43af65152793a1",
          "md5": "b12cc80757d152fea7c27edf730724fc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "9f2fd178894adbe8b393b709160921e6ea15fd773e17ec759932c00286181b90adc4bef0da674d795303166661d85b0e87c4f9822454852bad0cd7e6d472fb6a",
          "sha256": "54d3c8211c5c8fc680b8e70edffbd54d9fa6e7cfdca5ab62b6a81a7e81d3e11d",
          "sha1": "6b65fd5ca699cd69a2ea16b6bd2fb7daa765b7da",
          "md5": "8b2334927cc7b785f60126e7e294a8a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "885f8b836a125e2e3e4b442a0382d2052cd8952660c55a57a0283e51c82d1c428f25ee572118f6a7106505709e32cc00bd8602ed16ecbcb56cedd607b638ec9d",
          "sha256": "d6573e196f03a06ee1ae511e5ba512b1436f818c37db7d86403dff3e9a4f95e3",
          "sha1": "5dbc26da425b7be64ff33a5a0753aecc7ec31cf6",
          "md5": "3738f0da7963469c2d3c028829f5bf1b"
        }
      ]
    }
  ]
}
