{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "2a4558fcfe4aca001ba35251743c676beabdd117e1cfc8497c3247597bc2b211b014f30a77d7d708b74735f206aaa248b56a319a911ab284587076adfd57b06d",
          "sha256": "113698a3fb9fa82fd0d87c68e78133bf71ec6a78cada0a3878ba164412fa1d38",
          "sha1": "04c858c4874cdf5fe9beed1475514d1bbeffe5bb",
          "md5": "4181dcf8e699d62a31bf9f46730a3ad9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "2a4558fcfe4aca001ba35251743c676beabdd117e1cfc8497c3247597bc2b211b014f30a77d7d708b74735f206aaa248b56a319a911ab284587076adfd57b06d",
          "sha256": "113698a3fb9fa82fd0d87c68e78133bf71ec6a78cada0a3878ba164412fa1d38",
          "sha1": "04c858c4874cdf5fe9beed1475514d1bbeffe5bb",
          "md5": "4181dcf8e699d62a31bf9f46730a3ad9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "f0cca6667270309e6c58e8b907558110bbd7c3ab5cf26293a5d1f583a0b8061b9dee9f50295fe6afacc16b31903b0f3f892c0cd8cbe8f057621765722006795a",
          "sha256": "ab7c610c447c85a86f5632371c63ee75f5dae3838b86b85b94091a61cf0312a3",
          "sha1": "33e37b6379d933038adbabf854e07559371529dd",
          "md5": "0f7830c1967afa1c0baa863d7a52f50b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "611fd737d78c40fb1202b1e0ab5032f9f74efddf327d7b1dfb4c162312eafb82f6e06ceed4be60d448446f287cce6be167c16b82a4fbee27440b4eedad2fb535",
          "sha256": "aa327e0413a5ad4b1a8a2f01aeeec0ce2676402562156e711e04a77d27f40491",
          "sha1": "06a7d021b08fdcb11f4f828640a36539ae6fe536",
          "md5": "027408769bf7648468e0c8335efe3c74"
        }
      ]
    }
  ]
}
