{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "550a9471ed9eea4d255e1b26b28600741c8aac625ab219ec8a92692b1db8c8d4a40a0ae9c3430d0117edd922fb005ef54302fc851088aa52c3fa3ad60561c1db",
          "sha256": "0633f220dcf5cbc20b32fb027f3ad4bd674ec4e5b28b3d1a96a08347c4c77892",
          "sha1": "97cb034a5f184107d1be1fbc7e69ad552af8c784",
          "md5": "38c91078b4c4a91d705d77a7731df33b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "550a9471ed9eea4d255e1b26b28600741c8aac625ab219ec8a92692b1db8c8d4a40a0ae9c3430d0117edd922fb005ef54302fc851088aa52c3fa3ad60561c1db",
          "sha256": "0633f220dcf5cbc20b32fb027f3ad4bd674ec4e5b28b3d1a96a08347c4c77892",
          "sha1": "97cb034a5f184107d1be1fbc7e69ad552af8c784",
          "md5": "38c91078b4c4a91d705d77a7731df33b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "e7ec9b3bc711d50cefe2f16ed346257b77f7ea737f25cfdc590ed26de9a89fd21e65abc3016ec489ea3149f4d92d8273719137ae36af225e79c5ef088e5fdb68",
          "sha256": "c0e2187f8bacd6e671ecce5b16087f048fa7a5abdcd5f07467e53f7073292641",
          "sha1": "e164a0e8ef528236759412b5a19f80dc9bbd1947",
          "md5": "c8ce64a91c077fa8b7f67cdda344ba3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "8373eaba52c744663e7bc1061cf58a95824f8ed0bf83a31b389fc68daa31a33e2ca0b4e97ca8075c4be47fc5f57e5b7565819ef76a75ebc78164df79d6d4375f",
          "sha256": "fc5e37f83dbf7630415fb21e22cd8f4a6e2fa78c63715e7d7d0b947634e7553a",
          "sha1": "12e05e87cc8c87ac9de68e8c983f6c8618ee28e7",
          "md5": "305e7a882ecd11105c8c0d2d2ca29ba8"
        }
      ]
    }
  ]
}
