{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "1f2bf01ade486aabf80794b4caf125a9a82dcca09ae7dfb6a12525d978c3c99dd0f9af455d6e1fc35d8f18af92f3d10ed91517beb6aadf9a89897eee89e000cb",
          "sha256": "cc6db4e3ffa6d51c3ca47a51beb65ed47be14ba5d1a634ceca1545bc220261db",
          "sha1": "4411e28b81de407265ccec6af0d068a62c34a1e6",
          "md5": "6879c640bf6fad474526cf69eb7909df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84651,
          "sha512": "1f2bf01ade486aabf80794b4caf125a9a82dcca09ae7dfb6a12525d978c3c99dd0f9af455d6e1fc35d8f18af92f3d10ed91517beb6aadf9a89897eee89e000cb",
          "sha256": "cc6db4e3ffa6d51c3ca47a51beb65ed47be14ba5d1a634ceca1545bc220261db",
          "sha1": "4411e28b81de407265ccec6af0d068a62c34a1e6",
          "md5": "6879c640bf6fad474526cf69eb7909df"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116703,
          "sha512": "6103f98e8c530336a0e6245161ae18bd98f9e624068cb39f2210f76bf7facf4a6324c02328497f472340b0089d0d88a9ebeddbcf5abea817039e8f4bbb2ffea8",
          "sha256": "7b210ab8ccf0fed655c4f418046056d206c5ab8de83b475b0888eac5f708fa4d",
          "sha1": "53cc4301e2bf39046b4265303cf99b83ab7d13ba",
          "md5": "0b80d52424adce2bdc9c122a23a9a830"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31721,
          "sha512": "15777de0506f1c923446f0530d87d40c49d2aa1d440a35074834d3ecd696e7efe5190eb74c5fe76f26162cd61cabf2cf8e7f395524516f2cda50c8e03914e4fb",
          "sha256": "bf1eec20a8b529e58ec8a01897bedd7a8afb0cf9d0d490befdd27440335287eb",
          "sha1": "2fcb0e37804e7ba5e09b26a12800b503804cac17",
          "md5": "501d6e4abccf466a33ce8de2b22f2ebb"
        }
      ]
    }
  ]
}
