{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "3e4fa5f109c19a38b80cc9d718262273b6926d64b4085e3b90f5a12b12fe4fe2d3eb7ab5302a2aec8154e073799c9da595ab566fe6114f0ec6ba38442ca296fd",
          "sha256": "71013eefc7cb5cb31128d46a26d75e1fcf5638fd61d523a7e538584c6ea727ac",
          "sha1": "41f05f9af8f8c7af4a311bf0f97959f56477bd08",
          "md5": "1556ec2613fa24313a3a305530c0d6f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 84613,
          "sha512": "3e4fa5f109c19a38b80cc9d718262273b6926d64b4085e3b90f5a12b12fe4fe2d3eb7ab5302a2aec8154e073799c9da595ab566fe6114f0ec6ba38442ca296fd",
          "sha256": "71013eefc7cb5cb31128d46a26d75e1fcf5638fd61d523a7e538584c6ea727ac",
          "sha1": "41f05f9af8f8c7af4a311bf0f97959f56477bd08",
          "md5": "1556ec2613fa24313a3a305530c0d6f4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 117552,
          "sha512": "cbadbfdd7a91bf6644e1f7e0ee04a54faec75cccaee8647357bffdfb0b462f738ac9504c74326526e1619193da57a882dd7b52dc34ab3b2973f874ea69a2de69",
          "sha256": "c51709d3d4bae13860bcb115520a2adef6e6354a51a9684a5228cda659db3df9",
          "sha1": "403971d45a14c43e5a4e0c4ab14332a9967f0b32",
          "md5": "42cf5c52c69cb3289b32d527f571ff5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 31680,
          "sha512": "9acadfa3d749f958219902bdadbb9fedac247085991ed5314ae0fa4073da3ccf364bdfb2f5210be2fe88cff5db74fd069ef8249f4681e901d2a91df823045c40",
          "sha256": "3635c466864d427315b57dbfe7da885e74ac88639c6a781befe95d1ec5894571",
          "sha1": "3f0fbab9a0fdc895f2cf78273a119d7f2698f3ca",
          "md5": "0e45dc37a1d2c52474d91de709c94aee"
        }
      ]
    }
  ]
}
