{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 81532,
          "sha512": "88af6f05f488d32edf5197fa1eb3218a9c06053ce92e9537386d558420046c2b7e13713cadec90cb61f644eb300cb8ea58b7e7726555abfb19fe0ceb3dc448e4",
          "sha256": "ac6b851cd30f013c61a47816a0e928f6370cb4e27ef4cda19dedd4ce1c331027",
          "sha1": "e46a6ddb29e3cbc1c17a8b5f08c0285ebc9c21c4",
          "md5": "b0e6abacce5c9888f96f9c051515ebd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT.jar",
          "size": 81532,
          "sha512": "88af6f05f488d32edf5197fa1eb3218a9c06053ce92e9537386d558420046c2b7e13713cadec90cb61f644eb300cb8ea58b7e7726555abfb19fe0ceb3dc448e4",
          "sha256": "ac6b851cd30f013c61a47816a0e928f6370cb4e27ef4cda19dedd4ce1c331027",
          "sha1": "e46a6ddb29e3cbc1c17a8b5f08c0285ebc9c21c4",
          "md5": "b0e6abacce5c9888f96f9c051515ebd6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 190647,
          "sha512": "ba02ad640e4538f127cddd8c03c8e938ffab94e5f34bdfee229df84e686972b418949017a9dfecc942a8a510bcb3fef92e87b0e97c68b2c4cc4700b3de61e0e7",
          "sha256": "959eee3a2f4862aed81a731d2dea116863437b1c68c6ea19b9510ae118aef2cc",
          "sha1": "d89fce74d6b4129a576507e0bba21a11becd72b8",
          "md5": "52b44c0bfa1f0dd40923495880bcf7a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-command-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 29114,
          "sha512": "5c881c9bc54bb3e404f6f414f5ef9d5c174d3d46dd45a196be713791961093e62a327aace5966597004691e5b845ec3a5c79d01ccafc2e85bf0959d9ec70954a",
          "sha256": "d07640d5009e6084a1dfb8af5921861cce100fc0666000d710acbe6703130853",
          "sha1": "66231b749f4f85deb1fa534c6294a1401235c5a8",
          "md5": "3a799fc0d5b029c6310cb557bc5caf95"
        }
      ]
    }
  ]
}
