{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 52722,
          "sha512": "6713fb38d92a38f43e4c4421a09b15022fbc2ab13b2882b4648071b0e2e3198c13fe93d6a542d068eb6cfdb40639ddd3c76b92a68d107ad5cc113d40d6e1cf29",
          "sha256": "e941c535bcc240c335fa235a4a0efa9639f816b1e7f6477090dc6129cbcfdd0b",
          "sha1": "b925110ba387eca06f21ee36786cc734b82c0e33",
          "md5": "95f98f3bbcd24675b789701b893c3452"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 52722,
          "sha512": "6713fb38d92a38f43e4c4421a09b15022fbc2ab13b2882b4648071b0e2e3198c13fe93d6a542d068eb6cfdb40639ddd3c76b92a68d107ad5cc113d40d6e1cf29",
          "sha256": "e941c535bcc240c335fa235a4a0efa9639f816b1e7f6477090dc6129cbcfdd0b",
          "sha1": "b925110ba387eca06f21ee36786cc734b82c0e33",
          "md5": "95f98f3bbcd24675b789701b893c3452"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 102605,
          "sha512": "9f327be0f7471e9ac8fb67b6d53441c59bea7301998c0e4cc5a96b52f4486688044522a413679f2d35434c3a399007ab46d75457adc2f8c15f98cd3001af900a",
          "sha256": "1b7148f021e6e4d6d967501440be14580897d01a234b7a6ee78e505bf6a95a4c",
          "sha1": "cd833badd0f8a0cdf5a31af7005ab7020947e5af",
          "md5": "b6f2c2886b6dd4924a848f3d9cc587c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27787,
          "sha512": "f6ff3a394477f9a7eb53e31bec1a1949722156a8b59c8a3feba543902527621cea852d07ecfe40c5fce85b65da13aed7fb572500f8bbc17c02b743ad81d4684b",
          "sha256": "8454b9b58dcfd2daa047ffdcd3406dc560668ce3c094285b0a1ad0c0c7f33331",
          "sha1": "4bb286d417aa9c8d9a6cc956e54af13b9c44e9cf",
          "md5": "e8384bc7e694a4ede8171ec85ae35a82"
        }
      ]
    }
  ]
}
