{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 68034,
          "sha512": "41f148c79ca5f50ced38465b9fa1d4e699daad9d8b4ebf89b47a42813287ec2f966cd636cf218ec95c653aa76a08f6898b38d5eac92d3123603d0377b003b43a",
          "sha256": "c3bc312d7fe6c65d61d8ca70799c07c616fb51fbd22adec386279a29bc32e123",
          "sha1": "2845cff715d8b4feb084abaf5c736e20f3916cc9",
          "md5": "43a94977fa00c0864a3f753cf2d75b71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 68034,
          "sha512": "41f148c79ca5f50ced38465b9fa1d4e699daad9d8b4ebf89b47a42813287ec2f966cd636cf218ec95c653aa76a08f6898b38d5eac92d3123603d0377b003b43a",
          "sha256": "c3bc312d7fe6c65d61d8ca70799c07c616fb51fbd22adec386279a29bc32e123",
          "sha1": "2845cff715d8b4feb084abaf5c736e20f3916cc9",
          "md5": "43a94977fa00c0864a3f753cf2d75b71"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 148719,
          "sha512": "5127d424fffff793b0bc65ef1179fe438d971768b153eabe38bf29a84b17a82e3f9fb13bc908b320e90b3408ab8f4a500c8de2577394a3129947dfb157148c50",
          "sha256": "cf157fa89b698804689c1deccd197331a2c0e7e9644f86baf7d570deed1490ba",
          "sha1": "314b42b26e1e911ce8266f2080562eb765545df4",
          "md5": "7051fc2f4e2eb0a0e83724b7a142d6ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 50875,
          "sha512": "4c132a73d4aeaf169ef051b136940a1e693de2787664edee72044714f9892979a260a51f3caed2eab53c30f0a3031baf3832406900b5208800aa608ca7178ffc",
          "sha256": "ed65fad5cb7bd503422abb29aee594ae337e9065433147f54282e28d5dbefab5",
          "sha1": "a6be604c8b2c8a55acd8560d1edfb075b20f6b29",
          "md5": "d5e59e22d10159f4400c05b1f396c91b"
        }
      ]
    }
  ]
}
