{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 68034,
          "sha512": "0db773a9fa546b8d0bec74fc70a7cf85973aeddbb8e30b94f9002d8d9a17e18a163beb42fdcab035a11fb9169fc7664ede0d5af16400b2f8ab8260808419be18",
          "sha256": "8112aa1d593d328bfa659324542a4324e705805c1bd10a9f3f37cbebc315456a",
          "sha1": "fa40e2f027a9fb82a4ed14dc4117bedc9a01c910",
          "md5": "80cf7f43a882f47e232926c9a74e2295"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 68034,
          "sha512": "0db773a9fa546b8d0bec74fc70a7cf85973aeddbb8e30b94f9002d8d9a17e18a163beb42fdcab035a11fb9169fc7664ede0d5af16400b2f8ab8260808419be18",
          "sha256": "8112aa1d593d328bfa659324542a4324e705805c1bd10a9f3f37cbebc315456a",
          "sha1": "fa40e2f027a9fb82a4ed14dc4117bedc9a01c910",
          "md5": "80cf7f43a882f47e232926c9a74e2295"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 148719,
          "sha512": "ea968deb0377c08dcfdca4b23b3acf3db6fce7775b8409544c12420edbf4cc4dfa23cf0d06b49bce1493e3b346ab136b6ed033328f17537d929f9ae3da7a83a2",
          "sha256": "e2f3b47993403931f84a4d6b1d947a39e8140ddcc0d870b19a882239f91bbe42",
          "sha1": "a50b67ae2f51b4a6fb1e2c0a86cdce944805435d",
          "md5": "0b8eb7655ae859ac91e781e52f335c26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 50875,
          "sha512": "c40c54b3459235289865234c578f0d05fea17d4d938fa24f09ee45a59bedadafa8e63e2f2278db328f4dd199072fb169b1fc562a328c7442502ff2c1b2dbfb2a",
          "sha256": "358b1ff94e4f95542bf7b6752111e700c8b1ab185310f5c754c7fe78cb4ffe9f",
          "sha1": "ff4bc3137f90c632196e159c7a4e9ee2f8cc2267",
          "md5": "c49d0bf0deace99046265bb22a92ee42"
        }
      ]
    }
  ]
}
