{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 68034,
          "sha512": "43ca5adb1f507a0ae3604abd96e6ea93f4011a344a30a6ee1eb2cf38619d786e50baac406f02ab94372079209e588949d4568db39cd1427d4ad0c698b917100b",
          "sha256": "078053a24e6a383f6d8ec7b54007f499ae41483bb3e92149cc8d6f60011fd345",
          "sha1": "38ed5cfb363d011e23ac1e06b233b42ba8f0e325",
          "md5": "e8a1566b9c5240f2c0e06384827e8dd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 68034,
          "sha512": "43ca5adb1f507a0ae3604abd96e6ea93f4011a344a30a6ee1eb2cf38619d786e50baac406f02ab94372079209e588949d4568db39cd1427d4ad0c698b917100b",
          "sha256": "078053a24e6a383f6d8ec7b54007f499ae41483bb3e92149cc8d6f60011fd345",
          "sha1": "38ed5cfb363d011e23ac1e06b233b42ba8f0e325",
          "md5": "e8a1566b9c5240f2c0e06384827e8dd8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 148719,
          "sha512": "5795f57c24ea1dea2b424e9cc21509b1a46e93052bb490bbf57b495dcd742624b517f8bb0585efefde9232e9702e9252fb64c001302c098843a4207f74258202",
          "sha256": "135522a6b9200a7fd9ff99ac02c9ad29640c5edbf25ed9b3f84ea104ec8c006a",
          "sha1": "1a905d8aab4c8b8cc66023a2641c341b9566214a",
          "md5": "ebfb108059cbbc53ac71daac7e2491aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 50875,
          "sha512": "a34d7f1d40f1ea23a062c2cb23e59a31728de555d208d095650bc9ced152f97e1a917a1a46ff0206aa2a4393b2a746d2c89641abf3186c854680d72abb4d3df3",
          "sha256": "91bcfcd71504e237c79109a155e15be4a8fa0825d40ad7fe808e9ed8c784e418",
          "sha1": "1a53083e7a8a511377146e8df30a20ec10fa8451",
          "md5": "64ee83b616c2df1eba0730fe6e9c3003"
        }
      ]
    }
  ]
}
