{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 52722,
          "sha512": "163850d052b3808e3034ea503b01ac33a81d6d92996ccafdf87f0e8231b6e6d26127126b49b5eaa04c199df26ef1617e2da46e90a12e49a3b2af7fce5e422bf0",
          "sha256": "ab7e075a8326eb3bee966255d3b2683b2d3c1d0edd9dc65e56e80eb41b190385",
          "sha1": "18492a7a15277bf36bc26dc438f7be485df0099f",
          "md5": "3d76a48f1142a238a92c8da4d6e6855d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 52722,
          "sha512": "163850d052b3808e3034ea503b01ac33a81d6d92996ccafdf87f0e8231b6e6d26127126b49b5eaa04c199df26ef1617e2da46e90a12e49a3b2af7fce5e422bf0",
          "sha256": "ab7e075a8326eb3bee966255d3b2683b2d3c1d0edd9dc65e56e80eb41b190385",
          "sha1": "18492a7a15277bf36bc26dc438f7be485df0099f",
          "md5": "3d76a48f1142a238a92c8da4d6e6855d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 102605,
          "sha512": "528802474a6fadfce85efcaf23d06370d12d67cfefb284007d6df2f840dbaa6a6f0b9d8d1ccbd2db8709a8bf10118a2e43b489931391e1257bdbb0c3fadad72b",
          "sha256": "fc1c1b6232e677c4adcca65b2c6da3b1a7e4e0e1413d28a3feff13fbd44ab472",
          "sha1": "098261d92e0b09916d35555b25cf768e12881903",
          "md5": "e260044e6fde10e3fb92c2594e4e9c69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27787,
          "sha512": "e882d26ea6e98184bf225ae300d04139ea785110c2edf3161a878b0d8f0e31401709ebd50ee655faa47c674de7f1b0e093f66605b9d9b0630458222a8820505f",
          "sha256": "1e6d10cbf5ff311b35ec8ca6e1d2fc06dc15f37ca68a66a95aa5c77efee72999",
          "sha1": "5e4ac8f2c0b74ddc90e8bd08704d93584f70751d",
          "md5": "72f230e3efaa29b2bb63fede69dcecd3"
        }
      ]
    }
  ]
}
