{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 68034,
          "sha512": "5e85edd1242368eef402b1c05c97f9105ffb8a77b739da7fca80b300c5eecb863d95d0385c72d47301e555bbdd917bfc5d4b4f06cf5f2afb9aed2d034d3c877f",
          "sha256": "adfab080d36447ca2ea516a556bfcb3c081bb50891c7d9f6051cf18a80428ea7",
          "sha1": "7c94cf95b4e12060bb32dbf22214b92e4140ecc3",
          "md5": "24edd8de9ce5cf03aa9f1a42339aa1a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 68034,
          "sha512": "5e85edd1242368eef402b1c05c97f9105ffb8a77b739da7fca80b300c5eecb863d95d0385c72d47301e555bbdd917bfc5d4b4f06cf5f2afb9aed2d034d3c877f",
          "sha256": "adfab080d36447ca2ea516a556bfcb3c081bb50891c7d9f6051cf18a80428ea7",
          "sha1": "7c94cf95b4e12060bb32dbf22214b92e4140ecc3",
          "md5": "24edd8de9ce5cf03aa9f1a42339aa1a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 148719,
          "sha512": "2cddf3434ea4414d0325ef539b3a307efa521b163e6e14e5cf4c0232c64a24433f61356559f1d86a8eb7544b7802543ce6496814b9cb420a007c56939f21af26",
          "sha256": "13d660259ae3b860401512f47ab87d8597873d9c7e09d2a48e8ba2b522d82f98",
          "sha1": "17969a9231ddf048d711bee7f44698957fd5894d",
          "md5": "9c26bc2cf454cf803ff9e16a37ab6326"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 50875,
          "sha512": "d8cf9ad7f6eba1f7722238db5cb583ab941b27d068106923aae96e6b3f7040981050229aa206b63670e72b0825ad5a68cdec605128c029db9210be7563c75514",
          "sha256": "16f907dee5500154cb48341d872d0e1c77b2ea97c19abe0d232b5b732765a04f",
          "sha1": "182408b2b200ff24e65b4fd42dc6149b02ac9789",
          "md5": "5287284a4b202265108eb4a685985eb0"
        }
      ]
    }
  ]
}
