{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 51165,
          "sha512": "a3d18a11dca85c1b94ccd05af63862f1e1f364bc57e818f01445b2a672dada590cea822f762956b8da6867b50d618f141c9fdfea1b1426f38775de91efb31319",
          "sha256": "6ebe2dfb45e218a2fbdd79ed8109445eada1da1aec027bb1396032345482bfd4",
          "sha1": "0a5ce76ecf9e26bbae008e03584b0bacc950203b",
          "md5": "b2ad72ade372f261ba3ef9b57d4115ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 51165,
          "sha512": "a3d18a11dca85c1b94ccd05af63862f1e1f364bc57e818f01445b2a672dada590cea822f762956b8da6867b50d618f141c9fdfea1b1426f38775de91efb31319",
          "sha256": "6ebe2dfb45e218a2fbdd79ed8109445eada1da1aec027bb1396032345482bfd4",
          "sha1": "0a5ce76ecf9e26bbae008e03584b0bacc950203b",
          "md5": "b2ad72ade372f261ba3ef9b57d4115ee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 91327,
          "sha512": "599f7877438cf4b9754a0b0f4d94a9600f279bd1d01553a6ad4eff1657a307dbba2ee25b0405affe6025daedbc65bb8e398cfb5f0eaf34933e77bbcbd432967c",
          "sha256": "aead7ca3e61d480102474417d85a6d4da2bea3fdd7c4a0c16391ca91b3461bce",
          "sha1": "9a8c8e5d0bbd0c610142ebe3da85264f572d587a",
          "md5": "66dd750c7e441dc7bb6ea98b7b043bdd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26862,
          "sha512": "71136437d3f91d57be78db3a358a0c7040c6c7aa77a7175d37c624027b76babe706d4d24aa296f563b5df29cbf24ff89f5eb8fe1497e07c4f14aaaaed978bd06",
          "sha256": "49fbf4a3c975ff5efb94687a042597786c30414fa412108e4d074d982a307ca4",
          "sha1": "dc9599d0bb72790ade1d51c935706eef7429fd2a",
          "md5": "d3a019f0f475bdd87001a02486f9aaa3"
        }
      ]
    }
  ]
}
