{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 66912,
          "sha512": "48b7cc151c71126e5948bdebc796868892bf2db9fc2f804e61c9902ea5cbec30e2b81dec405480c0b48aa16ade202eda550c7187fb46888330fba7f8e6de830d",
          "sha256": "bd3aed865ed8d445dfe8f57d65ad97f12e2e8995cbce36488616e684369073c0",
          "sha1": "c955500c63661f1f677d0151ddd2da6007d4dade",
          "md5": "dfb26502eb374f538be23a95e24ccda9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT.jar",
          "size": 66912,
          "sha512": "48b7cc151c71126e5948bdebc796868892bf2db9fc2f804e61c9902ea5cbec30e2b81dec405480c0b48aa16ade202eda550c7187fb46888330fba7f8e6de830d",
          "sha256": "bd3aed865ed8d445dfe8f57d65ad97f12e2e8995cbce36488616e684369073c0",
          "sha1": "c955500c63661f1f677d0151ddd2da6007d4dade",
          "md5": "dfb26502eb374f538be23a95e24ccda9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 143132,
          "sha512": "b065092c959c902cfba708084524890fec4006c8eaa516d9d920eab78bd8a0d5b8625bd296b7f61b2ccc4a72d7d6026b0aa8c1ebd95b939e56417429ca42a42e",
          "sha256": "e7d32436b6daab0ff6437590447503fe367ffacdabeef699c87ee89e1bc9c660",
          "sha1": "e4bfb725b855130f53b46e4572fe98eaf9ad44af",
          "md5": "345bbf39bf2a4deb0a5e7421b8020780"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-category-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 50513,
          "sha512": "dc40deeef17d126ccdeacb9dfccda0b1e15800ec9219fb11636469e579adbef62ba7697433fa93240c2cc69a52f00d97c230a2afc9041fea523f344dba2b1afd",
          "sha256": "ac4a5e6dcae28252d02e4e831eae94aed126183693cf80ea43657cc78cf0ea01",
          "sha1": "70b7c342e907353fd59bc2257c2b5d9faf68c5e9",
          "md5": "415cc3f9e33a792e7a29d6bb1db72067"
        }
      ]
    }
  ]
}
