{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "5.0.0-rc.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.0.0-rc.5.jar",
          "url": "box-storage-api-5.0.0-rc.5.jar",
          "size": 21732,
          "sha512": "b66780257f291d99b56afb669e830c5a0be55513d079e5cb99b31e3e5571cd88969b89f6b77d01ea8671d66ebc3f16ea787635902e6715b7c896a2c8905f0ee9",
          "sha256": "b835347851e323b88d8443221c719fa44db9e92b02c54f756f9ceb1dadd1fa01",
          "sha1": "4466386997d0914a0523c773d9d713b5c5d21f1c",
          "md5": "b504c09876c7d4add8db64859521b8e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.0.0-rc.5"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.0.0-rc.5.jar",
          "url": "box-storage-api-5.0.0-rc.5.jar",
          "size": 21732,
          "sha512": "b66780257f291d99b56afb669e830c5a0be55513d079e5cb99b31e3e5571cd88969b89f6b77d01ea8671d66ebc3f16ea787635902e6715b7c896a2c8905f0ee9",
          "sha256": "b835347851e323b88d8443221c719fa44db9e92b02c54f756f9ceb1dadd1fa01",
          "sha1": "4466386997d0914a0523c773d9d713b5c5d21f1c",
          "md5": "b504c09876c7d4add8db64859521b8e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.0.0-rc.5-javadoc.jar",
          "url": "box-storage-api-5.0.0-rc.5-javadoc.jar",
          "size": 178438,
          "sha512": "5572b95ba40ee51080f989724d3eb5b42b4521df8572faf9aff6d5341b72ec32dedf3d544da54e4c49b81d7c2ef14d2888bc5f3bd17d832ae207fb3718df2ae8",
          "sha256": "1b32c0b1bbca570026e539ef9557740424b996201cf3b14bda7c86ae6a0067d1",
          "sha1": "fb0109e5090a0572d098824956948c8ebbbaf679",
          "md5": "bcf1630fbaae7a629bf3a99301e8fc91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.0.0-rc.5-sources.jar",
          "url": "box-storage-api-5.0.0-rc.5-sources.jar",
          "size": 12453,
          "sha512": "79aabf29c95d23cdddc5ebb41a6dec80f245cf75d561da82afbcd567f6fd630689ea08b05954dc683669f65454912b87f43c4007a8e26c12b7cf982ffe99061a",
          "sha256": "1659bec3a9a9d1cba534f610f47e7d8329f9798f6c7192b121ba9db4d1addfa9",
          "sha1": "fb4adacfe16234ce22a9cd6aaa341a6240bc0832",
          "md5": "1242025030d4afcb6611e5bc9ca84176"
        }
      ]
    }
  ]
}
