{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-5.4.0.jar",
          "url": "box-craft-feature-5.4.0.jar",
          "size": 64943,
          "sha512": "42c6baf6b6f7fc6d81ee7460d3925e93d6b86a556c8d14977dbff352778fdd728ad3628efcbeab59d9fd87cd952c90d8f48f218459a9c6135f27ea40078fc224",
          "sha256": "40f28f9803f54cd5492b13becca2a26ffd6f63572e5de81201234e7bc1e88021",
          "sha1": "4b30f10c02acf9fe5ade7b9fca63996d787af61e",
          "md5": "846b4037450dadb861f54d9bf1da1168"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-5.4.0.jar",
          "url": "box-craft-feature-5.4.0.jar",
          "size": 64943,
          "sha512": "42c6baf6b6f7fc6d81ee7460d3925e93d6b86a556c8d14977dbff352778fdd728ad3628efcbeab59d9fd87cd952c90d8f48f218459a9c6135f27ea40078fc224",
          "sha256": "40f28f9803f54cd5492b13becca2a26ffd6f63572e5de81201234e7bc1e88021",
          "sha1": "4b30f10c02acf9fe5ade7b9fca63996d787af61e",
          "md5": "846b4037450dadb861f54d9bf1da1168"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-5.4.0-javadoc.jar",
          "url": "box-craft-feature-5.4.0-javadoc.jar",
          "size": 208184,
          "sha512": "17564b695dd1c771cf72bdcdbe03c7329381b2ab8f5ba8bfc283254f620b656203c9f77df135b955f17025dd3e23b07970f9476a42b770eda90bb8bf4d9c88aa",
          "sha256": "1d27fd76cae3fde483a9bea962a7b54f1a168b3dee35ecc6e46f400fce7cce32",
          "sha1": "8d3868ea3c2871c17cba222435690c3198d81479",
          "md5": "e6b3fd40029753cc8acd24dc3e6ced47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-5.4.0-sources.jar",
          "url": "box-craft-feature-5.4.0-sources.jar",
          "size": 30418,
          "sha512": "6fe29aea6a80b015d63335a1f72922a9816f20a85a9460fc830c6295de81539ff7e1105d15ac12c7fc44fe8d2ee066198581407ad284906f6d3326a49584b297",
          "sha256": "9d0315177226136f18017ff0e794b5618392129602caba0ffbdca8c6746fc133",
          "sha1": "8ef510cfdd88e7fcc337af1565a3d4fe77b2646a",
          "md5": "21abd61a986e9e565e5b223dfca38f73"
        }
      ]
    }
  ]
}
