{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "5.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-5.3.1.jar",
          "url": "box-bundle-5.3.1.jar",
          "size": 15440,
          "sha512": "29722fe70716b39a942af496e265f61f2e28050cd1327ffab21a6566cd927468273fd45334eb691b8703299b19044491780d47155fe7b1ee9d1569eb04194948",
          "sha256": "384f91a0819d5bac39877f3fa51b7ef81d04b48d6d16baf709031da99ed74fed",
          "sha1": "0d4fc1db0de1045337bfa8bf039b130a1ef2fd84",
          "md5": "d4de4d5fd84953ff000387e54a0f48be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-5.3.1.jar",
          "url": "box-bundle-5.3.1.jar",
          "size": 15440,
          "sha512": "29722fe70716b39a942af496e265f61f2e28050cd1327ffab21a6566cd927468273fd45334eb691b8703299b19044491780d47155fe7b1ee9d1569eb04194948",
          "sha256": "384f91a0819d5bac39877f3fa51b7ef81d04b48d6d16baf709031da99ed74fed",
          "sha1": "0d4fc1db0de1045337bfa8bf039b130a1ef2fd84",
          "md5": "d4de4d5fd84953ff000387e54a0f48be"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.3.1-javadoc.jar",
          "url": "box-bundle-5.3.1-javadoc.jar",
          "size": 82244,
          "sha512": "fcf091c3a076782c2698b663da4df383751b370ff17aad1d7e5a30bd3239bf897a7554350840b7c8e59b7f0868d16c434d35c6bb30ab60f70acf5a54a2fdbada",
          "sha256": "56b05f3809d38c8b7deeac760be16cab87542d449c0e752c8d589d2ec4226cd7",
          "sha1": "504ebd906235ea799385e5f06d073702a9e8f2ab",
          "md5": "c932ff327a3c7821afd5b4be2331cdac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.3.1-sources.jar",
          "url": "box-bundle-5.3.1-sources.jar",
          "size": 12577,
          "sha512": "bc75658f781675f2750995f52fe36aff32cca071979f6792e2620ff1977b3643073e4c0e25f9fb2af678b1b11c6325386c2a886ca5a1857f85a54cbe7615d720",
          "sha256": "c367d7040039b4ae75e824e98f1167bb2ed65917dc029ffcfea87e71ffedde69",
          "sha1": "c4ff25b35aeb2f708f3ba84b711bf771231626ea",
          "md5": "64822d7061e3f336230bc9fec0757388"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.3.1-all.jar",
          "url": "box-bundle-5.3.1-all.jar",
          "size": 881475,
          "sha512": "ff89d3315765ece00c0d5e4684a3cea8b5c66688a6b6d99028d827d4ed2f78cdeebe20cee6e1aa43bc2b096412b12e87e9300deb8c709a41d08857a2227c9606",
          "sha256": "6ef0467e4bc3b7bc11ca789a8a60b82cedbcfa428f00f0b15f02293fba05f439",
          "sha1": "9e09e4446623025f185eb479bfac5ec6246fefd4",
          "md5": "8e686e41cc9d63158ba9890009548d55"
        }
      ]
    }
  ]
}
