{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-rc.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.siroshun.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-rc.2.jar",
          "url": "box-stick-feature-6.0.0-rc.2.jar",
          "size": 58291,
          "sha512": "229080be14a5c49aed92052ec32c7c6b93f3d194d99b967790cc89c4fc4a6b758c0eeb14c8ed7dfb7f789714be573e014e76885362f3dee71b901fd58b0a6b90",
          "sha256": "4cd2414588b0b701cbd2b6572acd08ba8a766cc92ef3edde35f3db482ecb340b",
          "sha1": "0926937409c6b0417321fe5f5a0ff93047c606aa",
          "md5": "0fa37649aa1e55252fc3d81a8fcdafe8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.siroshun.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-rc.2.jar",
          "url": "box-stick-feature-6.0.0-rc.2.jar",
          "size": 58291,
          "sha512": "229080be14a5c49aed92052ec32c7c6b93f3d194d99b967790cc89c4fc4a6b758c0eeb14c8ed7dfb7f789714be573e014e76885362f3dee71b901fd58b0a6b90",
          "sha256": "4cd2414588b0b701cbd2b6572acd08ba8a766cc92ef3edde35f3db482ecb340b",
          "sha1": "0926937409c6b0417321fe5f5a0ff93047c606aa",
          "md5": "0fa37649aa1e55252fc3d81a8fcdafe8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-rc.2-javadoc.jar",
          "url": "box-stick-feature-6.0.0-rc.2-javadoc.jar",
          "size": 155654,
          "sha512": "32dcce7f79f8070ff6ed3999d5b179c1890bb31778d687d978b7e900cd6f19748ddd2cb4fcaee26d592dca8d6cfa9589e5ad1e228fbd821e8206b11d272ccd3d",
          "sha256": "f1d9dbf65feb31c9691068ef6a684ee9b218c808471c085ab2aad40fb0d1a215",
          "sha1": "d33a32fdd6862dcd477336ddee375af9b5d6f086",
          "md5": "ede985063185067f4c8c25f9f14a1309"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-rc.2-sources.jar",
          "url": "box-stick-feature-6.0.0-rc.2-sources.jar",
          "size": 22137,
          "sha512": "e55217ad710bdab9a563eb331b285e3f7d739f87fd88c06e8cab74750a1a6b203b54da66bc2e1816ab9928d7fd48269fe940712bcaff1428e61b918df76c6486",
          "sha256": "bebe018c97769116cba2e571c5d867464a8508d5dd951b0f025be7e40778957a",
          "sha1": "e86a40218c44143e8d688b1b821fd108210a4131",
          "md5": "04b216da6b0cd3f89aeb85234755931f"
        }
      ]
    }
  ]
}
