{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "5.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.4.1.jar",
          "url": "box-storage-api-5.4.1.jar",
          "size": 30742,
          "sha512": "540558cb9d852ae262dc796a7526fe141f43a6fc7958648d278f08b5608c33acd1ac334c3f396302797ca1407f6d1ca321b9b576aa6878d94108bd00d2229ea4",
          "sha256": "72afb6762f47115392eab8c2c1938654a69ca607ce5af1dd1766b694c4302089",
          "sha1": "37cc71310c863fb1263aaeed941b62489ec67160",
          "md5": "954e6e2b4f56859250926c830921af67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.4.1"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.4.1.jar",
          "url": "box-storage-api-5.4.1.jar",
          "size": 30742,
          "sha512": "540558cb9d852ae262dc796a7526fe141f43a6fc7958648d278f08b5608c33acd1ac334c3f396302797ca1407f6d1ca321b9b576aa6878d94108bd00d2229ea4",
          "sha256": "72afb6762f47115392eab8c2c1938654a69ca607ce5af1dd1766b694c4302089",
          "sha1": "37cc71310c863fb1263aaeed941b62489ec67160",
          "md5": "954e6e2b4f56859250926c830921af67"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.4.1-javadoc.jar",
          "url": "box-storage-api-5.4.1-javadoc.jar",
          "size": 171719,
          "sha512": "7c328b01541f156d275397e5e3f927c1317b9f6e31aa3aa7dedf6b4755e01551c67e77d19cf1e41f084064ea08e74dbed52cf32596b91f5ac074facfa17ca734",
          "sha256": "4593ce763ff00e6b973932136c3115e1681701ef46e938f7201ca6c0a18f2632",
          "sha1": "70149586ca0a2b9f92b616cfe20a89751a34ec52",
          "md5": "3cea5f15ae127ff3d4aa56399a30b326"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.4.1-sources.jar",
          "url": "box-storage-api-5.4.1-sources.jar",
          "size": 16176,
          "sha512": "68b94f70a8b48749bd0d4cbf7fce11fae85a650f10acd297a6901a5e1170f94baeee8d40440059f16562c46ab3904811ba6caa17c9539d192a817fb9b073106b",
          "sha256": "8a7bbbca7b9ad1b4eb9585693d22f4e6f685849bd58dc806368842e7088936b5",
          "sha1": "9cef47833b11bd3c2edec96bcae2425e6bef659e",
          "md5": "cffd95150f0a51eee8235045fb5e8f5d"
        }
      ]
    }
  ]
}
