{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "5.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.3"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.3.0.jar",
          "url": "box-notifier-feature-5.3.0.jar",
          "size": 7503,
          "sha512": "631e73f443532c0d61802b29cad8990ed1cef6a7d13ac7719d14f14e2b2e58099b93b1a81235d060baabfd7a5150f66b78e4269aa72df2ca90662ce497fe1ad4",
          "sha256": "4711a3156195f1ebea93e5593f9bf8dfe601d2dccd9a3df097acf4728a11f5ae",
          "sha1": "0a40143a426b5a4279793a2ce1f6769888007a09",
          "md5": "e49c27e08d9804b7fb90139b37270836"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.3"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.3.0.jar",
          "url": "box-notifier-feature-5.3.0.jar",
          "size": 7503,
          "sha512": "631e73f443532c0d61802b29cad8990ed1cef6a7d13ac7719d14f14e2b2e58099b93b1a81235d060baabfd7a5150f66b78e4269aa72df2ca90662ce497fe1ad4",
          "sha256": "4711a3156195f1ebea93e5593f9bf8dfe601d2dccd9a3df097acf4728a11f5ae",
          "sha1": "0a40143a426b5a4279793a2ce1f6769888007a09",
          "md5": "e49c27e08d9804b7fb90139b37270836"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.3.0-javadoc.jar",
          "url": "box-notifier-feature-5.3.0-javadoc.jar",
          "size": 95635,
          "sha512": "22b3c37834853661a0c94acff6142b2edc19e5180d3a5c253e797b45dc324271b3108ba738b441064c08bc6e0186fe6dd25b3ab88bc12e2e79c58dc2b751fa35",
          "sha256": "2fdbc32aeeb349e64215e22b3f36028286788eb7b2f27e109e9976c1ab74f997",
          "sha1": "29382768dbc6ff0ab9cd5bd44f71b3637b1c8ca0",
          "md5": "55e91eb4b95642b61cca2d75a7c6efc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.3.0-sources.jar",
          "url": "box-notifier-feature-5.3.0-sources.jar",
          "size": 3874,
          "sha512": "122fe86de60146baea70771810e4d92f141d152b5b413812d7c4838728001b0ee14b7ba8e0744445860871704c891f26b8904a47134528f454d0fe9370979cfe",
          "sha256": "3cb16169cafdac39a7982fbeb09d2d104e0d43a314bc62372b406fffcc202e64",
          "sha1": "d9c5e7898bc9ebaa7ec64efbddd1270802bfc303",
          "md5": "45741530d57f8f34c6840881108cd8fd"
        }
      ]
    }
  ]
}
