{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-5.4.0.jar",
          "url": "box-category-feature-5.4.0.jar",
          "size": 67799,
          "sha512": "c8ee5843783386bd5cb61dbc355efc20c73e282f68477d93d02dd5d5bf8f901a4b623941ac3db36088f909c1c63e2b1eb87f924e7c9b3686ff9d67af91be16ed",
          "sha256": "643e72b9ca2c77f466b8de67d46ac07c4f3919ccfe4e70d66905ee0c12f10e49",
          "sha1": "ec96aaa147aabbf8ab174f24da27358c002f6720",
          "md5": "3f116ef479460be0fb2e27e21edd96c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-5.4.0.jar",
          "url": "box-category-feature-5.4.0.jar",
          "size": 67799,
          "sha512": "c8ee5843783386bd5cb61dbc355efc20c73e282f68477d93d02dd5d5bf8f901a4b623941ac3db36088f909c1c63e2b1eb87f924e7c9b3686ff9d67af91be16ed",
          "sha256": "643e72b9ca2c77f466b8de67d46ac07c4f3919ccfe4e70d66905ee0c12f10e49",
          "sha1": "ec96aaa147aabbf8ab174f24da27358c002f6720",
          "md5": "3f116ef479460be0fb2e27e21edd96c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.4.0-javadoc.jar",
          "url": "box-category-feature-5.4.0-javadoc.jar",
          "size": 148077,
          "sha512": "379d8138de5f4271efd50e16584581e5099d571889e5e2c75d83647c1d5f71670f739eeac845b45ecd56fc0fdaa890169db2895e1c53204c87afe3de83a9a597",
          "sha256": "49583184245d3e74e01434fb1a9a1cca57f6ae4da3881ea83a5089d41d292b9f",
          "sha1": "fcc0da876fca0ea8c34282136c0313bd13c91a6c",
          "md5": "acb5485bdac986e75fd7b10a552a3fd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.4.0-sources.jar",
          "url": "box-category-feature-5.4.0-sources.jar",
          "size": 50720,
          "sha512": "091bfd6470ab8023ec317ad1461cb31ced3c1eaf75be6aa2526f236d8963e9fcab7e93020cb2758be8e7a6756281b93a173ee1ed01d469558b0382693c7b357e",
          "sha256": "1f4d3fb7fcab73b136422de7eb1a22e5204c630916482988d613959220adb11b",
          "sha1": "3e0d769db6a77ae4ea4753b2c7da1928da5afcd8",
          "md5": "5ad14ff94d8bee61b797267dffee69e6"
        }
      ]
    }
  ]
}
