{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.1.0.jar",
          "url": "box-notifier-feature-5.1.0.jar",
          "size": 7502,
          "sha512": "eeba27c9c63367f7b403c836684c7666cda1270c2a5f628152529a7837df4f531d6082a63cdd1ca13615808c363262fb8459b474cfdb93743c917419aeb0a5b1",
          "sha256": "d682e3af93158a861dc762535d5307858ad34e9805e3242d7436cf8e9d72171d",
          "sha1": "bdf4bcb0f673d672684839a2f6972e6c5730a92c",
          "md5": "85b21c5386c2f4c67101f7d4c6e6d117"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.1.0.jar",
          "url": "box-notifier-feature-5.1.0.jar",
          "size": 7502,
          "sha512": "eeba27c9c63367f7b403c836684c7666cda1270c2a5f628152529a7837df4f531d6082a63cdd1ca13615808c363262fb8459b474cfdb93743c917419aeb0a5b1",
          "sha256": "d682e3af93158a861dc762535d5307858ad34e9805e3242d7436cf8e9d72171d",
          "sha1": "bdf4bcb0f673d672684839a2f6972e6c5730a92c",
          "md5": "85b21c5386c2f4c67101f7d4c6e6d117"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.1.0-javadoc.jar",
          "url": "box-notifier-feature-5.1.0-javadoc.jar",
          "size": 95625,
          "sha512": "888eb32d2dfe81ec8819434d90a3d569b811f2d13525b2b93418c6d2c14f49e2afed9f37e21a8f90ffbda413c52eb09ffdad80a579ff488846a6d8fb05e96688",
          "sha256": "9dd098b6f68edf67d680f201e1bfbaab989fb03752f31e5fe661a3c1682fccf4",
          "sha1": "8c878cae96a865347acc953877452ffe79ae55ba",
          "md5": "0975e49b06d1874ad6648b172410c761"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.1.0-sources.jar",
          "url": "box-notifier-feature-5.1.0-sources.jar",
          "size": 3874,
          "sha512": "9c5f756f555b17ad209d76b2c8f4cf3eedca11197deabf0d616d83829f2bd62e297c2c7e40a721147a01998539e857c70303abde312fd6efe46d633dc76496e7",
          "sha256": "1492997ae1dc77681055b95ef9f99c969d7a9ea91556c67c9924cf8d716bcee6",
          "sha1": "274d35bc4f06afa92a1b320ea6f2bf99ab54b86f",
          "md5": "138f2bb8d0e05af11341025616ba5c2a"
        }
      ]
    }
  ]
}
