{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "5.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-5.4.1.jar",
          "url": "box-stick-feature-5.4.1.jar",
          "size": 56158,
          "sha512": "1d41e5b3e06556c88396106c1325a6c66c37346d183224ef65f7ee4132fdb10ab9a5d48c265605742af9ba1fe478028bbd2b9406f18ba4906f978ced14e5499d",
          "sha256": "626b38f5a0f9638708fb893cec8c6a03f822d2258cd3953e74034badd63061e3",
          "sha1": "24f1222e4f8ad8c32effc9dec7c68fc826e5fce4",
          "md5": "16ba925eda4223d4945f2ffdb3e80efa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-5.4.1.jar",
          "url": "box-stick-feature-5.4.1.jar",
          "size": 56158,
          "sha512": "1d41e5b3e06556c88396106c1325a6c66c37346d183224ef65f7ee4132fdb10ab9a5d48c265605742af9ba1fe478028bbd2b9406f18ba4906f978ced14e5499d",
          "sha256": "626b38f5a0f9638708fb893cec8c6a03f822d2258cd3953e74034badd63061e3",
          "sha1": "24f1222e4f8ad8c32effc9dec7c68fc826e5fce4",
          "md5": "16ba925eda4223d4945f2ffdb3e80efa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-5.4.1-javadoc.jar",
          "url": "box-stick-feature-5.4.1-javadoc.jar",
          "size": 203277,
          "sha512": "c6891243dddcbf5bc48b05120ea4cdb249c45fd143492677a39728188e97fce271c8002ce76d8ce749b736816a44fc5c22cce7e3b5f3ef4528333f3aeddf6161",
          "sha256": "06b564bd13ae9eab13e28c40913b98416c345761e13b1900bbb1d1f71bcfa2a3",
          "sha1": "c82884e0b71cbe01066b337f6fdfc7569e08a590",
          "md5": "2c973719a808bd466315361b881cd79c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-5.4.1-sources.jar",
          "url": "box-stick-feature-5.4.1-sources.jar",
          "size": 20645,
          "sha512": "c41b6e232e00de8e4ded665b099b75f9ea7592f71f78b308ca3931eb9e5ff82303526ca0df9415912c349dc3112604d0573f996b1b91580e0314e18c11c50b42",
          "sha256": "46f5e27311974353a2c54677cd9a51f0e7cec589ae3af1abff041794a588e820",
          "sha1": "0a6201dc40f28eac97a23d0f5ab6daa7d98d6ad6",
          "md5": "3ac3a2124fb50337a128c060f7339d6b"
        }
      ]
    }
  ]
}
