{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "notifier",
    "version": "4.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "notifier-4.2.1.jar",
          "url": "notifier-4.2.1.jar",
          "size": 7552,
          "sha512": "becebaaf5f7ae9e4b593285614ce8ec27573142a3a2a550024a7c78c9fa58d67574dcdb50dd8f29fbb5fca1cf9905a9aadbd014b3c87483f99ee79be6802c07f",
          "sha256": "9e2d8605cf7bd14a2a3de56fed8bf79cd34fc2999f08e78d446351376b2099eb",
          "sha1": "34683e9a78ba77dc0d1fc999454f5561f547a413",
          "md5": "3f1d14cd04ded6fcb3630ba113d16a1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "notifier-4.2.1.jar",
          "url": "notifier-4.2.1.jar",
          "size": 7552,
          "sha512": "becebaaf5f7ae9e4b593285614ce8ec27573142a3a2a550024a7c78c9fa58d67574dcdb50dd8f29fbb5fca1cf9905a9aadbd014b3c87483f99ee79be6802c07f",
          "sha256": "9e2d8605cf7bd14a2a3de56fed8bf79cd34fc2999f08e78d446351376b2099eb",
          "sha1": "34683e9a78ba77dc0d1fc999454f5561f547a413",
          "md5": "3f1d14cd04ded6fcb3630ba113d16a1f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "notifier-4.2.1-javadoc.jar",
          "url": "notifier-4.2.1-javadoc.jar",
          "size": 118665,
          "sha512": "4413f3418eb19f020711272085cb222e877e475278cbfcf4c253987da147b34b4cc66c253c8f1d7b9ad2f00ee2dec744824fd54d2601ce7cee1acbb2edf759c4",
          "sha256": "5e775fa5f38000c1a1da2b6c03d7af9d9bd9db2f8c0747ac608920a5a9abe4f1",
          "sha1": "0a424bed5d066e892c8045c6c299d7f2d08c664b",
          "md5": "550c6de078f65c0d024af94d0a3eb42b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "notifier-4.2.1-sources.jar",
          "url": "notifier-4.2.1-sources.jar",
          "size": 3874,
          "sha512": "b5aecfb1f950a7486a35cd1939c7d041d5935192e1b8bfe85b199ade791c95959ccc73ad4dae9d52744ee476fe08f11c7f730a4339c684e98be44a3be1076d6b",
          "sha256": "e47d9312b67261866bce2a1f943cfcad301ae03c54de5cfacc868645622254b7",
          "sha1": "84fb13c27f5d4da1f2892c1e866af1b1786877d6",
          "md5": "fcc09d2d65174beb3b2e082943cc6489"
        }
      ]
    }
  ]
}
