{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-core",
    "version": "5.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-5.3.1.jar",
          "url": "box-core-5.3.1.jar",
          "size": 56661,
          "sha512": "c5a7e8001f7eda50e3cce72d979ffbde3a98d8b26e3d0edcbbe5f7b4418d8402c4cac036c6a55608d48965fa9245bdc322badef229faf2550694cd09abd1d675",
          "sha256": "a566b15c904d6240fd261d706d694119c22ac05b0c15599e0a989cfd412d147d",
          "sha1": "19bfb88910024a7639e770cf135888bd940a3ded",
          "md5": "4a2a22570c9aabbd7e84632021e8f485"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.translationloader",
          "module": "translationloader",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-core-5.3.1.jar",
          "url": "box-core-5.3.1.jar",
          "size": 56661,
          "sha512": "c5a7e8001f7eda50e3cce72d979ffbde3a98d8b26e3d0edcbbe5f7b4418d8402c4cac036c6a55608d48965fa9245bdc322badef229faf2550694cd09abd1d675",
          "sha256": "a566b15c904d6240fd261d706d694119c22ac05b0c15599e0a989cfd412d147d",
          "sha1": "19bfb88910024a7639e770cf135888bd940a3ded",
          "md5": "4a2a22570c9aabbd7e84632021e8f485"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-5.3.1-javadoc.jar",
          "url": "box-core-5.3.1-javadoc.jar",
          "size": 187528,
          "sha512": "0f47d4cff43bcc7608fafe5ab772b0d7f12353efc58746f8833b94711f5c6e2836e9bf3e3e608d53cc2b96bf09efbb55f21d9ff0015d4500dc37747b440c223a",
          "sha256": "ac8bd2de17a7f0cc6fe6d6c605994016445af65e0c15d7367db49ed58adfd1a8",
          "sha1": "d5535e7259b72b57e452cb3f640aa4771ce05add",
          "md5": "c3794446bbb4a514fb80f0f3a749d8f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-core-5.3.1-sources.jar",
          "url": "box-core-5.3.1-sources.jar",
          "size": 25415,
          "sha512": "c21fcd1079226820fa44aec8db6887c092e99954797aaa1e492d1049ac081b72c8d0b8ceb6c8be2b41aea0c417e7939f5a0991bd5c2529e32ca98f2fa1a3f301",
          "sha256": "a8647617bfe04bb0de3c1fef8e6c44cb2afe0394e451a344893c8bf685ee4682",
          "sha1": "b4aabe5c6bff5d6044fe946963d1935db6b8f400",
          "md5": "a1655b3af6218c4f2ccbd405536c8319"
        }
      ]
    }
  ]
}
