{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "5.2.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-5.2.0-rc.1.jar",
          "url": "box-gui-feature-5.2.0-rc.1.jar",
          "size": 77148,
          "sha512": "a4792a99d8e391fb4748ffee7bcd9ad9850053fbc0ddf44825629acd6c3f90c87b009204c9cdfb7c04df2eaaef06b0901cb6b3c9e526840d3da404288000dbe0",
          "sha256": "e8504ab3d5bfcea2b20a91f187fffab2009b46a28f71e1150a521bf052643e42",
          "sha1": "207b76e9560cb51a828020e33ee35d4eb0986a0e",
          "md5": "6b647ae884ba5371fe5e96ad4265abad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-5.2.0-rc.1.jar",
          "url": "box-gui-feature-5.2.0-rc.1.jar",
          "size": 77148,
          "sha512": "a4792a99d8e391fb4748ffee7bcd9ad9850053fbc0ddf44825629acd6c3f90c87b009204c9cdfb7c04df2eaaef06b0901cb6b3c9e526840d3da404288000dbe0",
          "sha256": "e8504ab3d5bfcea2b20a91f187fffab2009b46a28f71e1150a521bf052643e42",
          "sha1": "207b76e9560cb51a828020e33ee35d4eb0986a0e",
          "md5": "6b647ae884ba5371fe5e96ad4265abad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-5.2.0-rc.1-javadoc.jar",
          "url": "box-gui-feature-5.2.0-rc.1-javadoc.jar",
          "size": 274311,
          "sha512": "ac8afbd5c3a21af056b1302c10c97cfbb04357e5071816311f9894cde18bc7113a9804657fa774b43c9254d1108f016da36166cf2d68e03c0286c6f1d392e5fe",
          "sha256": "d4559e375a7d24af78ea0e2080d4e437f7fd247591a7202e76e40b9292ff456f",
          "sha1": "1819637f7ad45372ffaddf577aa97f304990b739",
          "md5": "61d533a12925d8441001136c1ac72c9b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-5.2.0-rc.1-sources.jar",
          "url": "box-gui-feature-5.2.0-rc.1-sources.jar",
          "size": 36122,
          "sha512": "a080c0a4552c143b31206b3827b32476e7c0fe207b139069105aa431435649baeeb9dc9e450efbb83479aabb122a877e42be70b61a4ae835080e108d2c5d044f",
          "sha256": "761f773957a9b39bc7adfc8186b76201ec7decad9deb808509ac9664702ce429",
          "sha1": "6cb3304722d38608988e8fc8aa61faea70d9096a",
          "md5": "c40255186aeeb69a50e8eabc1b543e97"
        }
      ]
    }
  ]
}
