{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "5.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-5.5.1.jar",
          "url": "box-gui-feature-5.5.1.jar",
          "size": 81570,
          "sha512": "c0d16f53505681e0013a796e63ea0f9142bd373c7354843c65711ffab96e4776038ad2d8e86957abccfe005c78d34c0122ac8f5b15e6ab8b34b2e1189266870c",
          "sha256": "3c95d333f5ab995075904fcf2d786d7a43469bd6dfd7f10de085f213b8240a56",
          "sha1": "019c26bafce1a4064430610d6a33e0f2de9f8ba5",
          "md5": "230e7434c343288d2af02bbff0432473"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-5.5.1.jar",
          "url": "box-gui-feature-5.5.1.jar",
          "size": 81570,
          "sha512": "c0d16f53505681e0013a796e63ea0f9142bd373c7354843c65711ffab96e4776038ad2d8e86957abccfe005c78d34c0122ac8f5b15e6ab8b34b2e1189266870c",
          "sha256": "3c95d333f5ab995075904fcf2d786d7a43469bd6dfd7f10de085f213b8240a56",
          "sha1": "019c26bafce1a4064430610d6a33e0f2de9f8ba5",
          "md5": "230e7434c343288d2af02bbff0432473"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-5.5.1-javadoc.jar",
          "url": "box-gui-feature-5.5.1-javadoc.jar",
          "size": 275000,
          "sha512": "e18f79b84a4d239288de2ac31a8d6e8a4da2212ee998d74748e0b0a36b9b64b8cd8637b68527685a4cd1c9c0066e31ba73e5d2946229351c13700f1bb1b971b3",
          "sha256": "d3e31870c0cef896aca959f1eebf960ae91a285500a7a78d06ddec5217207b13",
          "sha1": "6021539857563ebe3c52a404d26f9502d8368ea1",
          "md5": "472057069a80968dddb5b8a273e5629d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-5.5.1-sources.jar",
          "url": "box-gui-feature-5.5.1-sources.jar",
          "size": 37817,
          "sha512": "424e96ecf9654f159714c4092232411de006aa549ad6006850337f92d9be1da4e6abe77fa64788acaf4c837e4eeb20db0f014dd8318ebe52eae6d0818f736d79",
          "sha256": "3190bfbcb6c8bbf1364097e4cb7cd9f1b8728127b8dda4a99f7e94b698fce580",
          "sha1": "4c796b08ea96f5d9c6514a2931b2248c14eafba9",
          "md5": "6d4ab585e16fc15c8414a197ede856f2"
        }
      ]
    }
  ]
}
