{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-command-feature",
    "version": "5.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.4.1.jar",
          "url": "box-command-feature-5.4.1.jar",
          "size": 79639,
          "sha512": "018afd3a81b035a87510f3579e3633cf3f506d27e3be0170a0d4589dc14ecd32dbd847d71c9bfef74776e8fbc09d5cfab8f4e4c6ac33dbd2adf2a1bef7603123",
          "sha256": "7fb542f59e2f8f6aa5e2b734000f2523b4fd946530c953f582902c443d3fc810",
          "sha1": "e110d1e1ed0d0c0725164a8bc5a3f70112bca706",
          "md5": "a57347d46b7052b5f82dcd0bd302476b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-command-feature-5.4.1.jar",
          "url": "box-command-feature-5.4.1.jar",
          "size": 79639,
          "sha512": "018afd3a81b035a87510f3579e3633cf3f506d27e3be0170a0d4589dc14ecd32dbd847d71c9bfef74776e8fbc09d5cfab8f4e4c6ac33dbd2adf2a1bef7603123",
          "sha256": "7fb542f59e2f8f6aa5e2b734000f2523b4fd946530c953f582902c443d3fc810",
          "sha1": "e110d1e1ed0d0c0725164a8bc5a3f70112bca706",
          "md5": "a57347d46b7052b5f82dcd0bd302476b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.4.1-javadoc.jar",
          "url": "box-command-feature-5.4.1-javadoc.jar",
          "size": 184005,
          "sha512": "32c6e8f678d06eeccff147de77c0b9f58e873c28ec2c59b2e1ec674ff42946470e17c6cd6f116259f437368bd4efdc3e446290c2bf7027c217d3cc6041fe77c3",
          "sha256": "5e176dd59e84d867498f131753f5853f482f1bac470fe8d98968f38651ce303d",
          "sha1": "19294e196aebc7a4d9b8c5f75303652a7db61ee0",
          "md5": "c2dc4740d6165b3432906793fe16bd33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-command-feature-5.4.1-sources.jar",
          "url": "box-command-feature-5.4.1-sources.jar",
          "size": 28533,
          "sha512": "6d85351553f1e89f039dcc4ad18a58b9d58f3f079633dffbda331a1d219a9aee60327a25e6f60871de0870fe56b8c2ea2fe8a3d8bd213992069aa9d2f2b1a96d",
          "sha256": "9111291013fa83f09282925911ace7272862d6790fc85a77c41262da673e48f9",
          "sha1": "292190406ef73b6d209e9e30272fcfb73a1be964",
          "md5": "fc874d9d2b1cbf052758b597aeb5b3f0"
        }
      ]
    }
  ]
}
