{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "5.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-5.2.0.jar",
          "url": "box-category-feature-5.2.0.jar",
          "size": 66537,
          "sha512": "477c1db36ee5c610bc73e07210e6491516456bdddce751e7e16ff056a3ddb0ac5e4fa0b6d785f5c60d22ac04f2ade5139d90fc973710c7a43577fe8f3fefab4f",
          "sha256": "8d89419489e9e1d7f17b6af6ce272ef25ccdcf1b7990dccfc33e24b01a7c6f0f",
          "sha1": "2253ac5f6f11f642dd2997d32071d675ff5cfcec",
          "md5": "2919b3a06dcdc329d6abf568b131aa05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-5.2.0.jar",
          "url": "box-category-feature-5.2.0.jar",
          "size": 66537,
          "sha512": "477c1db36ee5c610bc73e07210e6491516456bdddce751e7e16ff056a3ddb0ac5e4fa0b6d785f5c60d22ac04f2ade5139d90fc973710c7a43577fe8f3fefab4f",
          "sha256": "8d89419489e9e1d7f17b6af6ce272ef25ccdcf1b7990dccfc33e24b01a7c6f0f",
          "sha1": "2253ac5f6f11f642dd2997d32071d675ff5cfcec",
          "md5": "2919b3a06dcdc329d6abf568b131aa05"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.2.0-javadoc.jar",
          "url": "box-category-feature-5.2.0-javadoc.jar",
          "size": 147190,
          "sha512": "b20cc359a49f2040f026546e96978c376a47d9ac3df2afcb050e2a94d9bb164cb94dd651b2ed50c292a4218f0bc6e6f513c4c6d03ba24fef7e3ee18ad2f8f44c",
          "sha256": "2ef2a4ea7ca0894beb4a320cd115ff97405b3e12ccb251d704ee685eef6505d5",
          "sha1": "31e3bf068469cc41cb74b384de11b419bfcec968",
          "md5": "51097e393a9f475e8155dc442c450646"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.2.0-sources.jar",
          "url": "box-category-feature-5.2.0-sources.jar",
          "size": 47072,
          "sha512": "3cfaebc017500d0d6241287e07637dd022122b51c7f9ecee495253ad7c5076d3351866c8103a362f00dedd0ca599eb82822230fbfe048a0f02f4a921d5b6cc1c",
          "sha256": "e41db394e484d1830f1a40c3dae239b44dcfadba6cc036393485c75bf39c1303",
          "sha1": "367ce3b4112e0d9801d73358bbad967f3204a55c",
          "md5": "b2cdf86cf119819e564ad1a5ea9e5a65"
        }
      ]
    }
  ]
}
