{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "notifier",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "notifier-4.4.0.jar",
          "url": "notifier-4.4.0.jar",
          "size": 7459,
          "sha512": "60d896a2fc9f899c5605024b500378f68a2666b231e2e43fb903f728738ba47e841cdeb61f112c936bb873482da537b7eeee08810fc4ffdfefeed49fe02c0f04",
          "sha256": "3809e13199c358854666b6594972f4ec75c540f2e5fae80e047541a33f43bf95",
          "sha1": "9342fa20f1b82d16ff625fe405e99fd63ef7cd9e",
          "md5": "28dc72fcaf0b3f54f0469a09ae6880d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "notifier-4.4.0.jar",
          "url": "notifier-4.4.0.jar",
          "size": 7459,
          "sha512": "60d896a2fc9f899c5605024b500378f68a2666b231e2e43fb903f728738ba47e841cdeb61f112c936bb873482da537b7eeee08810fc4ffdfefeed49fe02c0f04",
          "sha256": "3809e13199c358854666b6594972f4ec75c540f2e5fae80e047541a33f43bf95",
          "sha1": "9342fa20f1b82d16ff625fe405e99fd63ef7cd9e",
          "md5": "28dc72fcaf0b3f54f0469a09ae6880d3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "notifier-4.4.0-javadoc.jar",
          "url": "notifier-4.4.0-javadoc.jar",
          "size": 118779,
          "sha512": "02ade110af2601135276ff4a7093a8e21df394fea681365a5b8a4e632b40da1a75926e19df32896bf3d18b326915603efe73a1d4799c7a0c430e5a27f1d29972",
          "sha256": "e3379e241360bae73c873e3f905dc4670cf560e111ce397c7b4a32bec952a101",
          "sha1": "e3bdfb90ec05e43ff4fc8bbd2ee667cc80d45801",
          "md5": "ad7bad59aca8ebd9f5aaf4df2d5b2db8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "notifier-4.4.0-sources.jar",
          "url": "notifier-4.4.0-sources.jar",
          "size": 3877,
          "sha512": "569bc2f17c5cba62885c2a900888b6f549b47cf82a8818f891b1034eeea9a3a03c452963fef8aa915cc35fbb35ba7462b387631f8deb3fba3e8ff9a0416dbf34",
          "sha256": "09e7691efb0c8d212d6762513696bd36820f6609ad2e23e66acf4580a19347af",
          "sha1": "de94be11ed73588f5e859eab27df4bf780d28652",
          "md5": "40add0eadb89fbd976755273ba7596bc"
        }
      ]
    }
  ]
}
