{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-test-shared-classes",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-beta.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 39575,
          "sha512": "71a95febef5ca4698782ff3d23e291399f28dcc839db7e6bd2ad14d46a99498c7d0354a9b2b406d8df0a0bd1baf86f5eb6af0d50e06c52da77edb34056898af8",
          "sha256": "1b9500291e3bc6c577b17cf5e027332bb8484b36855fcc61cc50f896275444c9",
          "sha1": "12f8599d478fa72a57ae68079bca2f6bc3a98a1f",
          "md5": "4e5df0cb87fa8a045ca385167ee24093"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-beta.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 39575,
          "sha512": "71a95febef5ca4698782ff3d23e291399f28dcc839db7e6bd2ad14d46a99498c7d0354a9b2b406d8df0a0bd1baf86f5eb6af0d50e06c52da77edb34056898af8",
          "sha256": "1b9500291e3bc6c577b17cf5e027332bb8484b36855fcc61cc50f896275444c9",
          "sha1": "12f8599d478fa72a57ae68079bca2f6bc3a98a1f",
          "md5": "4e5df0cb87fa8a045ca385167ee24093"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 217681,
          "sha512": "82e799367aa28e477f5a94c3a5fcfa552a31253368b9ed0f66c5f80a918637ae62251e078833221dfe05373922b82b94e3b9ec514258a920af56dcfdc2e2fa78",
          "sha256": "5503474f37cf966e4780655ca432da95080e36ea0ec6e5372c7e56f3e5f7e142",
          "sha1": "e25cc5ab7d43cc6748b554b22023985e86e8b1d8",
          "md5": "0ea079e9d41ceb3080fc9199fa7c134e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "size": 19986,
          "sha512": "07c9a37a1f7535fd5c9d9bd0556898fbbdda055570681eefdc20309589100213dedfea42f84868f15387e304937ae96eb2a01e6550c6617a65e0dff381597dd1",
          "sha256": "82cca43e9392513ba3aed80babcac739f3f48bc0df42ced5d6e6e0a122094fb5",
          "sha1": "6d3dc3a25d3d6e5d6631bfdc36e3259cbe49e13b",
          "md5": "b322325a3126f01fad71849b8ee6d614"
        }
      ]
    }
  ]
}
