{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-test-shared-classes",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 27834,
          "sha512": "d7040b008bf0e6a66f336f616fcd3043c85680aec959ffeeb637641b9edbc82ba01a141aa01e6c692504c609092cfd0ad417f51420a2503e23ab1392e7bcd84b",
          "sha256": "9133d2f686705c4477f5929e770a000242fb383454ab40da0f27ae10a0213e21",
          "sha1": "2fde33bc287bc02165fa12c0cbba0b317f833620",
          "md5": "3f0acac72161f5717239368ef2930124"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 27834,
          "sha512": "d7040b008bf0e6a66f336f616fcd3043c85680aec959ffeeb637641b9edbc82ba01a141aa01e6c692504c609092cfd0ad417f51420a2503e23ab1392e7bcd84b",
          "sha256": "9133d2f686705c4477f5929e770a000242fb383454ab40da0f27ae10a0213e21",
          "sha1": "2fde33bc287bc02165fa12c0cbba0b317f833620",
          "md5": "3f0acac72161f5717239368ef2930124"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 175137,
          "sha512": "df596196e51c41d3ee472e17d05df0fd4f0ef6702d5f710698c5ad042c677c53ec255b206ad845a54ae330bf7651fda7dc813728eb7f7d2fa54dbbb78b8fe466",
          "sha256": "200cccc58f98bcf21e337bf8ae641d2ecf04806ed39562989089b6083e37e4af",
          "sha1": "521e3fde526810cd22938fc9f14a20f6faf8fe8c",
          "md5": "ff2b5769502a37bebb241c596cae46f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "size": 13771,
          "sha512": "9f1d6b6c72dd8bdcbdc674b90f6a7dfd4c2f08a275ad31e8ad4e8c99987b52900ab462b6c872f75658b5dfb5efe7134530ff2f0ee1a3cb222f10b840bdf9205c",
          "sha256": "9b5f46e340c39a48cd7108e351d1f3c5d78dc1e25f0d8bc98babea67824ac367",
          "sha1": "5c94bb285c7ca883444c1299f8de0af64f9aebf2",
          "md5": "8a8cdb914b526502dbed6064a3d2c39d"
        }
      ]
    }
  ]
}
