{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-test-shared-classes",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 34120,
          "sha512": "9536346a2b9d75e6632183b2e37a9c7f56f1e1d2ff0c76bc023f6682a0f8099f29e92eef345d95271887b8d951420807a2c43694c556441911d3bb654029609a",
          "sha256": "fb816519d66402e253faa4e604aca3c56ca8722d3ef19fd9adbf6528eea8d16b",
          "sha1": "e777dafb1e0c2eb0da5c48a6f5a6cfebf7b8f4d8",
          "md5": "4ee37ca67d2a3070eb4a9ed8a29ea74a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 34120,
          "sha512": "9536346a2b9d75e6632183b2e37a9c7f56f1e1d2ff0c76bc023f6682a0f8099f29e92eef345d95271887b8d951420807a2c43694c556441911d3bb654029609a",
          "sha256": "fb816519d66402e253faa4e604aca3c56ca8722d3ef19fd9adbf6528eea8d16b",
          "sha1": "e777dafb1e0c2eb0da5c48a6f5a6cfebf7b8f4d8",
          "md5": "4ee37ca67d2a3070eb4a9ed8a29ea74a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 201097,
          "sha512": "f8c10ffcd15a271e124aec69fa9aec1ad43795e3fc09518ffff09a6741c6ba196d0c3d9b146227d09b4cee0c3b6e8130c9031da931b868f4db3a5b6701575818",
          "sha256": "595e74d5765f9a7d614ed55babdbe7d865a15325439ac5baacaaf6fc56fd93c3",
          "sha1": "cfbeeb771ecac018246591022a0856ead028edcc",
          "md5": "4629b54f5759609712ae5288ee835fd4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "size": 16860,
          "sha512": "4cfa910b0790c0c3ea5c3b642dbc78e5b41cc1387b600a81f3cf0848ec86c0c8b366fbdeae9ba8ab5edc938f179b0c5b8dc28e630fdf65e638987fd39de74b47",
          "sha256": "122107815c706796e3273e0d6f17ece48f56f90430074c802707ebb2454a5871",
          "sha1": "b58977a11d3fcfa8c8a67e5414109f84bed8fb93",
          "md5": "ab0ad8c146a04ea7f14e01589ab688e2"
        }
      ]
    }
  ]
}
