{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-test-shared-classes",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-beta.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 60663,
          "sha512": "91a9c52027b3f60be2e20908c9410e449c3d6324a4a686ebe6276b832bd729ea72fea452f1d441f3ea2d01a16d3382cf5daebb75b6ce23e4835c0bbc5dd66844",
          "sha256": "b66756733d97f3bbb34ca62dec28f6fa5949922dc315d61e442ec016362c9041",
          "sha1": "760fb315cdece22a6d23563ad673a9964cb7976d",
          "md5": "e513f57a3b74f69aa8a54780aa003161"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-beta.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 60663,
          "sha512": "91a9c52027b3f60be2e20908c9410e449c3d6324a4a686ebe6276b832bd729ea72fea452f1d441f3ea2d01a16d3382cf5daebb75b6ce23e4835c0bbc5dd66844",
          "sha256": "b66756733d97f3bbb34ca62dec28f6fa5949922dc315d61e442ec016362c9041",
          "sha1": "760fb315cdece22a6d23563ad673a9964cb7976d",
          "md5": "e513f57a3b74f69aa8a54780aa003161"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 239880,
          "sha512": "6a479cc4de7e5af8906fde354365fe3db056db5b07cffc9ee110085139c42b95f810105a1edccd13553c79b3fa550a917e38e484fa45b2338d9edc296119a6ae",
          "sha256": "2e04d80c2e0ed93c97d48a24ca86b0e1a3f33a843c44f223d4e8e4824d502026",
          "sha1": "88e4faf7764bf93c7867610927924a95b0007fdd",
          "md5": "22df38bbe5c302391259309d8dcc68a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "size": 26899,
          "sha512": "95b3d175eefd6aaeda7682199cdeb27045bfbeaa5577011c02ca3758288932d476b08a9cbbf0d080acbbb5b96c21eef37aca6fea4127557201985bfd140157ab",
          "sha256": "eb557b9f9252993aecf13346af4270b44bc4fd0eb7c9bbaa9cbd5476963efa3f",
          "sha1": "dfc7caa6db4d13f8d034cf98883729a48d8e3c54",
          "md5": "885a0e1c9fc46c6b30b714256d91ed38"
        }
      ]
    }
  ]
}
