{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-test-shared-classes",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 35247,
          "sha512": "b52f7d972ab5d206ad2e1e09b0872b6cf3cf83fa3b891e0983cd5d1ba820eede3eaf7b306449fa3a6d6c3d09fab5d168b555c2c816631568e7ea194e417df4fd",
          "sha256": "18e0b93e4415cb8a026c322d4fb8f2db782bd094c8ae2da6c796297d37bd0ca0",
          "sha1": "098b495a5694f79c14360c5828510a16b07b6688",
          "md5": "1fce2b2e553620fd22897f5a195f6661"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 35247,
          "sha512": "b52f7d972ab5d206ad2e1e09b0872b6cf3cf83fa3b891e0983cd5d1ba820eede3eaf7b306449fa3a6d6c3d09fab5d168b555c2c816631568e7ea194e417df4fd",
          "sha256": "18e0b93e4415cb8a026c322d4fb8f2db782bd094c8ae2da6c796297d37bd0ca0",
          "sha1": "098b495a5694f79c14360c5828510a16b07b6688",
          "md5": "1fce2b2e553620fd22897f5a195f6661"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 203846,
          "sha512": "6167022a9fe80830387d596bcca9a5dbeebd7ebe87db59bfe04e697a0e6c068f12e7d7f2ad1b1a4a683f371762a3d0272a84cf05c18e470a5bf15b49c179df50",
          "sha256": "0b1cbbc569862bb69b39f9d85927021acc7f5239f4607ea9ca86c93c7aa3811e",
          "sha1": "234c8edcd87d9d95e9d5463278fd6d1aa6cb14bd",
          "md5": "2e6dbf29b807ef32cf6d42bf830570d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "size": 17542,
          "sha512": "2a6088b58dcc2c5a1b0347c411acb8064b1f5f622a1207eafc9d0620c668915f3515ec1825005cfcf789fefb7cb119ba082aeaedc76b4ba604c55d0b1e93aea5",
          "sha256": "d2ebf9ad04a717be9201fb226df6cbba5f0dae0ddbfd54735e7998614c234af3",
          "sha1": "598556d5963689742f029f3cb60d7da6c93672ef",
          "md5": "667e483c2204d19905d517a3136dc448"
        }
      ]
    }
  ]
}
