{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-test-shared-classes",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 27834,
          "sha512": "14c8703b39c51b3154d390cf723eae800962a4a80b76d2caa036545a12ae5d0113a6332227ce251196126372980d52d209a094039b16358b37c4abb88618ef2c",
          "sha256": "5378e4e526d75ed921ca55a05ae980224f5caf1fa3ff81bcd8bb1d080334b341",
          "sha1": "478c7f21b7624a670603af2a1e4e8478712d2ab6",
          "md5": "d928edb4215f0ef9206fe3e76a58b338"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 27834,
          "sha512": "14c8703b39c51b3154d390cf723eae800962a4a80b76d2caa036545a12ae5d0113a6332227ce251196126372980d52d209a094039b16358b37c4abb88618ef2c",
          "sha256": "5378e4e526d75ed921ca55a05ae980224f5caf1fa3ff81bcd8bb1d080334b341",
          "sha1": "478c7f21b7624a670603af2a1e4e8478712d2ab6",
          "md5": "d928edb4215f0ef9206fe3e76a58b338"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 175137,
          "sha512": "e7e8e5a3fe835fbf72eac61b7973a58315bb1d4391da883612b2840795503c0c95358a346dc6967f8fa17bb13d3d9d5dfbe78c06fa9fb9cc9cce8c3e31681b08",
          "sha256": "30cebc1e6cd8ea6bff7cf50dea8ad049ca4f3f4fe77bec47f3f3f82bc0203439",
          "sha1": "bcb9e6cddb86ff86c6458ff6e035aa13246effbb",
          "md5": "97333c65b65f8fa5fb65b58569b0f4a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "size": 13771,
          "sha512": "ce6c5bc347f8f601993e8b7be39425f689b817398bb6b036317f02149a21b72adf4827aa5860c108dedff913b36a46a0c42d68928570bdf9c5c4ff432aab52fc",
          "sha256": "33dea7d870016a4223197f6a7799fc3cf13bf9ac20d8149eebf2b7c9a0b80bae",
          "sha1": "5b77452a05964eb3958f516e5e32835c3e1ad4c6",
          "md5": "c502849b26f577eb8dd884611c2a2823"
        }
      ]
    }
  ]
}
