{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-test-shared-classes",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 34120,
          "sha512": "a6f23b8dac06daf29ab702d2c6b12c0b0f21217d8dd0090389420fbd56c0ef0ae7e7267d297f8a009e6e24afbd4f1c8f5a244730d440eab7fad06b2be99bbe3e",
          "sha256": "f88007c7e65d4e8c278eee8d3445ced1fa0fd927ccd54d97b5e11eca88e06dd9",
          "sha1": "17cdc47dbd6cb956aea92b8e7f0a9b53f96be159",
          "md5": "5dde4ad3f6f810926e187bb2f43bd1f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 34120,
          "sha512": "a6f23b8dac06daf29ab702d2c6b12c0b0f21217d8dd0090389420fbd56c0ef0ae7e7267d297f8a009e6e24afbd4f1c8f5a244730d440eab7fad06b2be99bbe3e",
          "sha256": "f88007c7e65d4e8c278eee8d3445ced1fa0fd927ccd54d97b5e11eca88e06dd9",
          "sha1": "17cdc47dbd6cb956aea92b8e7f0a9b53f96be159",
          "md5": "5dde4ad3f6f810926e187bb2f43bd1f6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 201097,
          "sha512": "1446bb2b81dc09b426019e9bdd084df45e9f1c03348e4038093155fe959ee5064aefdba0a32b08f4a7c22ed03e861fea417f04f4604cf84b1b6fcfc7c98eebd2",
          "sha256": "8aa6bc39c4d093569ff531b8374952694e676aa5f88dbb395f5eb242f1e7fa9c",
          "sha1": "5b994abbd043c5535b17ca8214617a915c04b417",
          "md5": "d2fea49c3ccf8a51dc9d2b9e30fafbc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "size": 16860,
          "sha512": "b34f458db37546b41eba4e9c640b696acb106fe696079711b0d41097442ed61fbc6554ac9c073969fd733551932c63d45e8d4776b5e358ad4c3e4e54a5ce2060",
          "sha256": "099e82ea6f524f9160d866223faef24f61c9a4bd31c85337dc3300d8ac335120",
          "sha1": "b0da6bca34636962953b85b90b53351ac8ed8235",
          "md5": "ce67e1a4e4c506dd15cc9947447585b4"
        }
      ]
    }
  ]
}
