{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-test-shared-classes",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-beta.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 48113,
          "sha512": "5f2bfed1f01267ad2eade5c7c955590ec603a1f2769cbc1b644a47b827c9523c4ae298a9bb5c67897e4ab15dc0828c832240f907f1c6120bf571a3689ef5def1",
          "sha256": "617faf41b56bfe5cfd3281ca5c96dca79ec64457b7562b1da9ed03c0893094bc",
          "sha1": "561482a11b7ea194d0eb6ebe93a0a496de644f7c",
          "md5": "5e9c42d99cd95a5eda3917ac967a6b2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-beta.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 48113,
          "sha512": "5f2bfed1f01267ad2eade5c7c955590ec603a1f2769cbc1b644a47b827c9523c4ae298a9bb5c67897e4ab15dc0828c832240f907f1c6120bf571a3689ef5def1",
          "sha256": "617faf41b56bfe5cfd3281ca5c96dca79ec64457b7562b1da9ed03c0893094bc",
          "sha1": "561482a11b7ea194d0eb6ebe93a0a496de644f7c",
          "md5": "5e9c42d99cd95a5eda3917ac967a6b2c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 229496,
          "sha512": "c3ce853887ebccf9a25d882a5fae0ef137759f03ee476f119c0b7414bf9572064c9886c356b1ef8fbab7a9dc5bc7cd31db9601ea2352e3487c78cd249aaa77e4",
          "sha256": "537e51a6ed10992e58dff9dc66eb4342809269554a96c2374ee319125db1edfb",
          "sha1": "ba99cd499a438fc2dc41f269dff4831928813b9f",
          "md5": "d209c26bc03a9881d4da3ab5851052b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "size": 22910,
          "sha512": "0195036d7a6415bb91596d171418498d22a324d5e69d3d9c7fb345e8903d13c186d3cc12c08e4507732839056e43f106e1639fcbd290997f375e00062a0b38cc",
          "sha256": "cefbe6fb538e61cb88b1326dfd1c5029a6ee9447b2ff176ac375671333ad1a6e",
          "sha1": "778048ca3029064437f0acd90825a55de8bf17c0",
          "md5": "6b5b0377a6edb8422aa644b8a56eb044"
        }
      ]
    }
  ]
}
