{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-test-shared-classes",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-beta.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 48113,
          "sha512": "91e0669560beff88542a5866679645a07b0af1fee09e1ae61513678733e706514bde77dbbbc346ceca941ce60551d4bb2227b600c75a632e3db6279f29f820da",
          "sha256": "f65fd676c6762f54d67b894c8c22cc743531418f5bc81ccd9897a431408afb83",
          "sha1": "10169ee0fbe00a92c011a8c9f4001eb4bf045667",
          "md5": "a2879a7515740a885aaf72e22036faa0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-beta.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 48113,
          "sha512": "91e0669560beff88542a5866679645a07b0af1fee09e1ae61513678733e706514bde77dbbbc346ceca941ce60551d4bb2227b600c75a632e3db6279f29f820da",
          "sha256": "f65fd676c6762f54d67b894c8c22cc743531418f5bc81ccd9897a431408afb83",
          "sha1": "10169ee0fbe00a92c011a8c9f4001eb4bf045667",
          "md5": "a2879a7515740a885aaf72e22036faa0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 229496,
          "sha512": "812a3215995aaa68991419d85983bdba3f66c84c0a7b337227f4a08da38903222e2e098bac16456e89666cb46aa3594944121412b0216d72b725af71aa61443b",
          "sha256": "75caee60ba85fa92ad8b27b35c0cbf90e55ffca3f8ed44fdf1070293ba244e8f",
          "sha1": "70558545dadfba83881f2aadae1cf83933b2dc7e",
          "md5": "c8b6d916527307ce9879b6d255ec48a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "size": 22910,
          "sha512": "698b3a7a6143f7cfa65e079e6e96fb73d10d4a1d47473f54cb45ce14863dc8a012c53c636b6a57fac0b2633197d6273c1351f9f7a6d68221b1a3cfc8c930b4dd",
          "sha256": "d85432a6e8fdbd529345afc46928a1af79711f402b24bd0e95f4e75649b161d7",
          "sha1": "385fe1c91eaea4c16e8bdcdf21b15a2a2418f27f",
          "md5": "635ad55e2ecb7353952bce21fbd99c37"
        }
      ]
    }
  ]
}
