{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-test-shared-classes",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 27834,
          "sha512": "9190143ace8dcc0d57ec8e3c48a68e8628cd4a19fa9e802dc394b74adb50a69fecc8b9353a791992d3d321e665f2136bae0063a34cba9d0adc38661b45719220",
          "sha256": "7671b351a89307e271d1733e0b6bd45f932193c43841071f6a9a736cdaf88eb4",
          "sha1": "9383b6877f7a8ee1c901b27badef63f1634ba40d",
          "md5": "a891065222b4ee8ca46d33ce9b0746e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 27834,
          "sha512": "9190143ace8dcc0d57ec8e3c48a68e8628cd4a19fa9e802dc394b74adb50a69fecc8b9353a791992d3d321e665f2136bae0063a34cba9d0adc38661b45719220",
          "sha256": "7671b351a89307e271d1733e0b6bd45f932193c43841071f6a9a736cdaf88eb4",
          "sha1": "9383b6877f7a8ee1c901b27badef63f1634ba40d",
          "md5": "a891065222b4ee8ca46d33ce9b0746e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 175137,
          "sha512": "70198b7620b5b70dbfd49600c4522978722ac9f0ad7827d0444a8ceed722667221d0c2bc3cd2ad96a454345c786da7a1a52149dee8f56e8da0c6969e14e8ba68",
          "sha256": "abd9081a7822ec8f648c998ee21ed29b223b0b5c00ae051cfd10465ab3cc66cb",
          "sha1": "2ad074af63c4440c95649e05004212c116ae9033",
          "md5": "f2aa78ef7609860871c5eca2d73615cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "size": 13771,
          "sha512": "140f8ae6d355e4a66c012253732f22a5f451fd6d9b89bda164402742f9633dfadfb2a6e0ed4f145391f75140e97a16ab81d2996b401a41c564b02075f3ff1f9d",
          "sha256": "98d2b2a41048492050cf46d0739590dc6f227199d67c7ae8005ca9874ce33fcc",
          "sha1": "059a5aba7474357860089f92bb95afcca068cc79",
          "md5": "53c2f9afb980085dccd1d262e21e085a"
        }
      ]
    }
  ]
}
