{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-test-shared-classes",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 34120,
          "sha512": "661610e07cbe40c17485b7299b8f3aac12e0aeb350ac4f7c5f75b1ba2ca08ebfe2227364c7632fe7fc79f64b91b51606f4eaa73146562e8ec9d28363208ecdff",
          "sha256": "810ba1c484194bead4058725e230ec212d6dd03448bf2e7d85c8058554940985",
          "sha1": "b3eb54f7581e7ec7284c8dbbd2122ca5717cf7e3",
          "md5": "1bb25dc2da1727ea2d9d4824540961bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-test-shared-classes",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        }
      ],
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT.jar",
          "size": 34120,
          "sha512": "661610e07cbe40c17485b7299b8f3aac12e0aeb350ac4f7c5f75b1ba2ca08ebfe2227364c7632fe7fc79f64b91b51606f4eaa73146562e8ec9d28363208ecdff",
          "sha256": "810ba1c484194bead4058725e230ec212d6dd03448bf2e7d85c8058554940985",
          "sha1": "b3eb54f7581e7ec7284c8dbbd2122ca5717cf7e3",
          "md5": "1bb25dc2da1727ea2d9d4824540961bf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 201097,
          "sha512": "c837b13b6c95980f34d7d6c00635ecbc74b3ed281b478a256117cf085e191c1d185242bbb777f292c30fa5bc72d9ab0010277402b4911b75292d75942e9252c9",
          "sha256": "9fd846cdf191b8eee314b36de50fe89de9deb3441b1a8be991ee004d7af6f71c",
          "sha1": "ff56bf6c6d2033d18de00f42444f8bcacbc9e230",
          "md5": "35130e3e29d25c68df458184498490cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-test-shared-classes-6.0.0-SNAPSHOT-sources.jar",
          "size": 16860,
          "sha512": "a3e9162dfbebddc328e7f1109640fd250b45d3c09a0514a6f48787dbc40d4931b2a499406b86e5495b0b7b1a28f4ed77d1cbf380176ded339c2e9a7582e39423",
          "sha256": "86a7c3c1f7a3f4bdea9f1403635ca5ea77dae21271493ca98d5b0d98a52fa2ae",
          "sha1": "ca73811bc6ea54ac788ac140c396852a1f6c337c",
          "md5": "45d3afc934be8e0fa0ebf0139ab3d175"
        }
      ]
    }
  ]
}
