{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58299,
          "sha512": "b7b2adc931655eba392588933983fbf8018b59466a3390d3cc6ecc316342210b1fd92f44b7db8d73e6e9d9501e98f4f6dfed04ab316153eb8d2202f5d25e85d1",
          "sha256": "9e7071631e5b82b24f04779f949b0abd9bd8c765f160690bfb788f7808382eae",
          "sha1": "d65f23487a24f706aac887754e2b37cd08ecf2fa",
          "md5": "7403cd87720c5d27bac872b7c3e8b9e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58299,
          "sha512": "b7b2adc931655eba392588933983fbf8018b59466a3390d3cc6ecc316342210b1fd92f44b7db8d73e6e9d9501e98f4f6dfed04ab316153eb8d2202f5d25e85d1",
          "sha256": "9e7071631e5b82b24f04779f949b0abd9bd8c765f160690bfb788f7808382eae",
          "sha1": "d65f23487a24f706aac887754e2b37cd08ecf2fa",
          "md5": "7403cd87720c5d27bac872b7c3e8b9e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "f0b01782a7c9a3de6602ec96bcb18de5bf65b018a8c6e23756214a0105b61cc14da82c603b7e8b4846544d7a64677646a091b021b5889126a0285aa2a4fd6a6f",
          "sha256": "6020dcaa8038790ec6a9d7f002d79e5de89bad4319a85926357b012234fb33fd",
          "sha1": "dfda2f66c3ceaa9ddcd98ac2ca919d99bd64272a",
          "md5": "3fe7c811f77548ce1b7c34b270b76c59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22138,
          "sha512": "990ff3ce11540130c9202e5508c094c87399943596ba43741b221fe564d1839a20889bb7b5b2b851c07ce76fc0b30b4faf65a406d6f0fea97928eb2634136a10",
          "sha256": "5e489af39edb783c15a33acc2964b295177caaa9b7d308d99ebb3e7c502ffd77",
          "sha1": "4b1260485f54f49d62468e187f547bd1ff2e1e33",
          "md5": "80be502ea1969f171ab48d34efff58be"
        }
      ]
    }
  ]
}
