{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58261,
          "sha512": "07f9146956b8b4f86110db3e9080f493f6dadcab95e4b67e39893dba99a30f1cc2e92c2de79de4bd8d2e5beac2f1dab20e3cf6c8242a51f4b8b87a74a1c68280",
          "sha256": "0151dde947302942bfa64d9b767a356a6aa6c7cdd4d482a42f1b4499083ea6e4",
          "sha1": "bfcf41e3e9202bec6b9bf10e546e6cee5a83eb03",
          "md5": "10f0827de9ab053bbbb4de569ca0757e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58261,
          "sha512": "07f9146956b8b4f86110db3e9080f493f6dadcab95e4b67e39893dba99a30f1cc2e92c2de79de4bd8d2e5beac2f1dab20e3cf6c8242a51f4b8b87a74a1c68280",
          "sha256": "0151dde947302942bfa64d9b767a356a6aa6c7cdd4d482a42f1b4499083ea6e4",
          "sha1": "bfcf41e3e9202bec6b9bf10e546e6cee5a83eb03",
          "md5": "10f0827de9ab053bbbb4de569ca0757e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "88d5257e1f62c61d908e2133d2e1c9b5dc605d9dcc5f762f410bee728269579d9bba031707691ec5d90a0fee21fdf50daee7d84c8b26889f72b25cfd436c36f1",
          "sha256": "13c09fa73d1f77b90e7cb95c79b9a254c6937f53216ae234b7da00060235520d",
          "sha1": "79742fbac4a65785e3c41e23d2b21a2722b8ea46",
          "md5": "66f1873a692fb680c46a246c4d86f21c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22142,
          "sha512": "1b6bbdff5800411382fc2fedf464e6f7a0764c45a5ad054d93ada99df35262340f9aa79abba4db25d81902b93ce843b3fcb68b71cabe9010a7e032e833b8323a",
          "sha256": "0a3c7da153644e3d74e9835be3f3178014e44d0fcd889455cb8ac93dc97a5ef4",
          "sha1": "6673c2894e4e2523db7fece82dc84a6bd1fad99a",
          "md5": "e7213a50bf045832f4692ef0adb76e27"
        }
      ]
    }
  ]
}
