{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58299,
          "sha512": "116d9ea1d8820f2bfe8077c9b3f34d06e1f268f0be1e2b189179068402462a50967eec3138402e9e4a05c86a5821e8a50d2a87fc421aee878244752876604f86",
          "sha256": "a4c2baeaf96bf8afaa8ae175ddafaf4aefac07d4b8652dfcf20c6fabc2c2ff03",
          "sha1": "a30e2766998b21eb82fafa625bd6237b78891ed0",
          "md5": "b7123977189e0d4933c01fdbba2957d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58299,
          "sha512": "116d9ea1d8820f2bfe8077c9b3f34d06e1f268f0be1e2b189179068402462a50967eec3138402e9e4a05c86a5821e8a50d2a87fc421aee878244752876604f86",
          "sha256": "a4c2baeaf96bf8afaa8ae175ddafaf4aefac07d4b8652dfcf20c6fabc2c2ff03",
          "sha1": "a30e2766998b21eb82fafa625bd6237b78891ed0",
          "md5": "b7123977189e0d4933c01fdbba2957d6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "da113ebed6151c9cd645e9b0dac51a4bd5b2ff1d4f57e0a319d7f990466ab21ea013518d02e54fddefe726010a673996e3b2a31a2c66771144f8632b61fbe3f2",
          "sha256": "4ae5828d186d3ac98b07d1ad12428280331e4ceec18e2e63f7d197182d70760d",
          "sha1": "061ccbf122bd2c5703bc4b47a068fa5113e74fa8",
          "md5": "4354123da21447dfd836253dea2eb527"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22138,
          "sha512": "83218ecdf0029cd4632087c412ce15862a008b165d550ba6537ea5e13e4ea7fa0ee4ea9b72f67d755a6c93dd2147875f95bf5a2090a59d3c12496c8651b77794",
          "sha256": "04f53f9c7ac92fc0885f669ff076bfb05a8177d4dd73b608ce8d7ccc82725992",
          "sha1": "cba2c7e46a95a9b0e47497ce09ac98ce47ea613b",
          "md5": "7b1b6b4872bd34e85c0a50c053984e4d"
        }
      ]
    }
  ]
}
