{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58207,
          "sha512": "b4a1e9ea89adbf92feb71760a987240e33aba8f5263b42e870e2b20434af91c719e0b64c2036fc2f0fd0ba02b25ec7a5811f7b9b610b15913fc5f915bf350331",
          "sha256": "2403aa7956dcae629dc8b6155a76e4516407b5895f24fcb5df939aa9904df68e",
          "sha1": "1f03d5dd9e8a9c10aa81ae822b017aa0b9f0fa5d",
          "md5": "9a14abed1d204566bf3deeabd0b05127"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58207,
          "sha512": "b4a1e9ea89adbf92feb71760a987240e33aba8f5263b42e870e2b20434af91c719e0b64c2036fc2f0fd0ba02b25ec7a5811f7b9b610b15913fc5f915bf350331",
          "sha256": "2403aa7956dcae629dc8b6155a76e4516407b5895f24fcb5df939aa9904df68e",
          "sha1": "1f03d5dd9e8a9c10aa81ae822b017aa0b9f0fa5d",
          "md5": "9a14abed1d204566bf3deeabd0b05127"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 156384,
          "sha512": "23d83c2ff103316981a94f69c5bc598edf4d88f65f2015facb07d50b2baf2f014691a6837f6d312e4de145789ef8f24397dcfcb449bc28cb8b66498267e87784",
          "sha256": "056f553e671cbf348318984ae9567c7bb69d0fccab895b1f2b8adf7640e11062",
          "sha1": "cfc49dc3582bfc12e99892b52109fc889d2b9902",
          "md5": "7849f8311786bcef57f1d37c55e324cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22121,
          "sha512": "a357a6d85f1ebd7125598a439ba82598cd2f1a3f6d4490a758f5136708204cb5bd6553f4ac2df1429b7d15a6d6145ef8df0ed97890b2e8d1f31988da5aa85ac4",
          "sha256": "8d01a45d3bfbef8a5159c2598ba82a093221af387d76c30cd4d79d9c0807ed66",
          "sha1": "c8d25ea4790ecee07f0c6248c5391f18cd0200d5",
          "md5": "c009d1cf072a13c17b1e7ff127a9e466"
        }
      ]
    }
  ]
}
