{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "9fc0809375f4cded09a8f5fd98d5a3b26119f4a1e43e75b46c1ff8c5ac512f9250ebb4ba82cf28e06388eadadbde7b56c9fc9f7d54cf806987b81a18628bc6cd",
          "sha256": "edb42b7ccc53321ad8e0d00156977e567914c97cedeee60505a28319f49da86b",
          "sha1": "f907c17bf9cebbe789f7398e1be4f882237f18aa",
          "md5": "18a5f5bf188cb36e4ad3c16519a40ccb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "9fc0809375f4cded09a8f5fd98d5a3b26119f4a1e43e75b46c1ff8c5ac512f9250ebb4ba82cf28e06388eadadbde7b56c9fc9f7d54cf806987b81a18628bc6cd",
          "sha256": "edb42b7ccc53321ad8e0d00156977e567914c97cedeee60505a28319f49da86b",
          "sha1": "f907c17bf9cebbe789f7398e1be4f882237f18aa",
          "md5": "18a5f5bf188cb36e4ad3c16519a40ccb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "a6f7e3e9f21f1d1ffff3c69b5fc733f130f707e45570e5567428c544f2ec2acc1816ba31b44de5c7ebca1b103981ea54aee60bdda92f7e4da0cf53fc3516a6f2",
          "sha256": "5431373851884e9ce4c339fa898e0d2d4d9cd87db4cf416e7d58b2f8604eb1c4",
          "sha1": "b5ee494377e1aa4010a6fbbe754d2879c45acd51",
          "md5": "6f31800e07c7f95a5a6c5f00d0b4a514"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21912,
          "sha512": "da1e351e71289b53d5c77d152189c1c32033143eeed52f779195d9fe1e9fa53476a2ed2ba8aa1b072f889446322a95080ca5b5b8a79bc273aab8bb81a68bc878",
          "sha256": "7556dd8884d0535084a87d10710e335890e5f63bae42c4e3b8e349b13a70b4dc",
          "sha1": "d3cf2005ada1687ccac6f46cde281183c1aece79",
          "md5": "18ed744b817a07c4c067aba63e13d18d"
        }
      ]
    }
  ]
}
