{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58317,
          "sha512": "cc351777cc600a4a3c1974b504146131f32574917641ad84c773fec4eb79a141fdd4ff40badb327821538ae322d346d2b1cf24d5758937ee2cb58fd1406f9384",
          "sha256": "4e7c31544e34f58b73f05e56be4a65eaa370d38b57204cf3a4a576d59a3f642f",
          "sha1": "715fdbd268302478bb11ba9c886b99c496653cf5",
          "md5": "ec2e2ce0de2064c19162fd80262a76e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58317,
          "sha512": "cc351777cc600a4a3c1974b504146131f32574917641ad84c773fec4eb79a141fdd4ff40badb327821538ae322d346d2b1cf24d5758937ee2cb58fd1406f9384",
          "sha256": "4e7c31544e34f58b73f05e56be4a65eaa370d38b57204cf3a4a576d59a3f642f",
          "sha1": "715fdbd268302478bb11ba9c886b99c496653cf5",
          "md5": "ec2e2ce0de2064c19162fd80262a76e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "d84a83d301831987bb60a57f7fd091f8e40e493db994be4c11a87cfc10e123b6b839ded003555e4c8f82c09cfaa6b5dfa26e4ee60848ee8f00c50cbcd0f7f53b",
          "sha256": "f6d203e9f8c7c85d9f5aa7e4c29d86ef65d6f0235ff71dbf91d06a9784c4fb98",
          "sha1": "3f66af8e26c14283bec871cd6d9cd0edd6b25866",
          "md5": "65129fdaa3c03e5a69fcfe19533c1474"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22149,
          "sha512": "147276504fb4e5fbe8a8e8b15d052a46096731f7ca4221b13cc896affdddf83d397ab7354607f5fdebb27aadff5db5dffb5cf0f634e79c18a76fa3420fd28f89",
          "sha256": "1d52efac7b7e58104089963eb3505656b232e70e94b24ec516770ff5cede66b8",
          "sha1": "14d1ed5f4f5ce16f44a1440cd758b423f1104196",
          "md5": "d77c46625d8e7032a74e969a9b0122a5"
        }
      ]
    }
  ]
}
