{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "fefec34831e679f3c90dee9661d185b7f3c9d48c6d6498c61b8d46c3f8551d3ffcc2d6e05037f05b0cf8b299a51ea1ce81a67ee6cb62d27c7f0e806cffcdefad",
          "sha256": "8b2b6a34b21892d6dde44ce1e498e7a78cd23c19741330be688d019c132348ee",
          "sha1": "b7b943d2b68160688f6635fbd98c3ef778a95a2a",
          "md5": "4de8941876d8a640c58820fd38303be0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "fefec34831e679f3c90dee9661d185b7f3c9d48c6d6498c61b8d46c3f8551d3ffcc2d6e05037f05b0cf8b299a51ea1ce81a67ee6cb62d27c7f0e806cffcdefad",
          "sha256": "8b2b6a34b21892d6dde44ce1e498e7a78cd23c19741330be688d019c132348ee",
          "sha1": "b7b943d2b68160688f6635fbd98c3ef778a95a2a",
          "md5": "4de8941876d8a640c58820fd38303be0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "476d90b8138240855228345d40e6e66a26d70c75d9c02277d5c9d6a82f5e06c48e029944a33e1f87e5b287d2d15a2b6f51bb4dd32d81a689f8eb6a23f89abc4c",
          "sha256": "f078fafbdaeec2742ed0ee526ede607988ad7feba20d3af8d3a78d4463311ccf",
          "sha1": "2a258d88d406e32d1c02be0d74e340086cfbe944",
          "md5": "c743d7847d4a775b00c940e03adb5f36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21852,
          "sha512": "ce55c05d1f457bb4e39036166427dd660cae281edcab4ac31e224c48e8084fd39016ebc5d604e165091d16b72937be4ad4614cee2d841f797eacc4043ef467e7",
          "sha256": "1a146dedf4de0acf82cf147288bf4522df174b2968bc98fb2c1de01de9db8b16",
          "sha1": "212dcbf39bf8338ec9d47419f765658172061487",
          "md5": "a64eca83807a49b64b6ec9c21c67edd6"
        }
      ]
    }
  ]
}
