{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58556,
          "sha512": "46e5a26c8afe32e8adea698a36aa521a740cb13ec477f088fe322c6c4af91484d575706cc4ceebbda25110aacf4465b7dbea7e4ab9d8c953086d36c1d83f2148",
          "sha256": "523d5d7d3f5deec9461161357da6e67235891a99ea682932c21a70fa2156f173",
          "sha1": "e420bf45a55cf9f754b024715587a24005c40f54",
          "md5": "187a1ea99ac31ec2780c6add38c111da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58556,
          "sha512": "46e5a26c8afe32e8adea698a36aa521a740cb13ec477f088fe322c6c4af91484d575706cc4ceebbda25110aacf4465b7dbea7e4ab9d8c953086d36c1d83f2148",
          "sha256": "523d5d7d3f5deec9461161357da6e67235891a99ea682932c21a70fa2156f173",
          "sha1": "e420bf45a55cf9f754b024715587a24005c40f54",
          "md5": "187a1ea99ac31ec2780c6add38c111da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 203571,
          "sha512": "35f65ce61b72ebd3ba88b1aef849e3c9db3e070fafd8a952cd0af5371f2fa4cdf865bcccfc0d443d973e576f3bf971a438f3658d1e506fb337fc683c8219abfa",
          "sha256": "33b6b2ef611613ad6182c194cd3f5320df3a37ead73536a7699588cfb3ac97d1",
          "sha1": "aa6980e0c140d215b4e5195511d2c45e49a12230",
          "md5": "2cba65a20122e163aa52d29a21b98114"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21917,
          "sha512": "cb4b6c01ac94176720802acc2ccd5995baf6ac38ed65ef2534c968aa89bd85b103566f5f3d8c21600be4df5a7bebe265f39dd068a1bb7c286c123ea3f5229403",
          "sha256": "868fbfe9b8fe9b60bdc74160c10c05480d9d0b32b645a70994e21d58b32f3912",
          "sha1": "9edaa1954c5d2024f8a32bb85d551b3638fad3f5",
          "md5": "2416d7f304d1cb8dabf0768704f3c8b4"
        }
      ]
    }
  ]
}
