{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "08b322cba295520c736c9039fae583e087ba8514e9d4482796a52cc6ab7d0e4cbb5a13a0fad78e46bf95923d038dcdf6a0f54efe0688e04599fff5094560c875",
          "sha256": "5f6acfcad73bf27c2db54846bf67d77859c62e900d25f4afd3f1723a7a14c793",
          "sha1": "5ebe92ba0fbaf25ec43bf934f9deca7b7566c82d",
          "md5": "3579dd241c41767ae5c2b07ff881e920"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "08b322cba295520c736c9039fae583e087ba8514e9d4482796a52cc6ab7d0e4cbb5a13a0fad78e46bf95923d038dcdf6a0f54efe0688e04599fff5094560c875",
          "sha256": "5f6acfcad73bf27c2db54846bf67d77859c62e900d25f4afd3f1723a7a14c793",
          "sha1": "5ebe92ba0fbaf25ec43bf934f9deca7b7566c82d",
          "md5": "3579dd241c41767ae5c2b07ff881e920"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "74e8160dff6e6747948de0f8b1454c8e99ee5a3df2d4d875c478a36e8218a7ed9f9f3dc3eda56b99a154832d22acca7993d4e9e02405f1182bd96c735584a98f",
          "sha256": "7523b08fa66ba40c82b28909680a5542e59caf4437c267fc2bdf36e335ca2c98",
          "sha1": "3912398b10b3bb58b836a64414ba860d409e0001",
          "md5": "240af143483d06729ce1a6590cfe22c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21932,
          "sha512": "b74e6badda12a044b844054d2b7e6f92a86fdf6cbc2db01a7a65a7bd04d4f91fe738a1872ec102ce60e9d302ef5f4af296110061c96db31fdab13d46137f87f0",
          "sha256": "00848d141634a511e6caf11e61f24389dfd2059d224ecf9b927a1bc4f3178abd",
          "sha1": "d649c9913702c9e561f877df5c80188218dbedae",
          "md5": "5c10e42f493613863d4bda5d0b91e0da"
        }
      ]
    }
  ]
}
