{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58317,
          "sha512": "de758a33e6a2163ef7dae98d60ca46b2a8575571a702c2d77d33a4d0bae7bf00f8b7805b3070bba6f845c3aa9b82a8fc4abea5cea2faaed838dd1ea726275c07",
          "sha256": "c593595243d9ab57e37b0e01bcb9a6b3c93b713f9a9034ef528476f25bd48c93",
          "sha1": "3c3614b8099c214ca9d07f95e54f5a1aaf1ec449",
          "md5": "afa2a77a0fe60540c7b01e8d6ce1cde8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58317,
          "sha512": "de758a33e6a2163ef7dae98d60ca46b2a8575571a702c2d77d33a4d0bae7bf00f8b7805b3070bba6f845c3aa9b82a8fc4abea5cea2faaed838dd1ea726275c07",
          "sha256": "c593595243d9ab57e37b0e01bcb9a6b3c93b713f9a9034ef528476f25bd48c93",
          "sha1": "3c3614b8099c214ca9d07f95e54f5a1aaf1ec449",
          "md5": "afa2a77a0fe60540c7b01e8d6ce1cde8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "d73c39eb778eac055c391b0f16b2752a587898e43673b88ff34f6c308665adfcbf6db735aec1fc28e1ef5697c7f89bc0e5cdb3a0271ef0b28e46412479c4125c",
          "sha256": "2afff8d9d1089a41a459f5e61f60e8d236eaf6f3ef57234d667b5b49d562a16e",
          "sha1": "f750fe44fd6d837c2708442c34ae4ceae63255d8",
          "md5": "ac2691d48499ddc39bd9589db256ea67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22149,
          "sha512": "94857c03b14e635f0505a547272c5b4ed02c50de4cbbfbfe4fc255dc6e20971fe1b58234426fa7acc0a1a2fa9cfe90dbcb1e1aa8f616739303f3602306bbfcc1",
          "sha256": "ff444845f5f4e585f5a39c99e9e8bfec6385fb4556cd6dee9392a606852f3972",
          "sha1": "d3f47c0a4b4512c0c25e8e9e872bdd363f9a5fe6",
          "md5": "a32b79d6f2e958ab3d9a4dc951cba131"
        }
      ]
    }
  ]
}
