{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "9f3f1f1326ac67d4ccf21f880b9d46cf2d40d2475458061bc337745970c06032f4d9f957fcda85597957d1c3fc27d67509307e8b765630461aef0c4cad8b7658",
          "sha256": "52bd445957250e06f6d00dc0d774c05b4a3cb55f1209e18e76e209df26eb7fc7",
          "sha1": "8abf2f49fda7414690b367b5cd283d4325a3942a",
          "md5": "1cc252b96d0552106914267e2b44a62a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "9f3f1f1326ac67d4ccf21f880b9d46cf2d40d2475458061bc337745970c06032f4d9f957fcda85597957d1c3fc27d67509307e8b765630461aef0c4cad8b7658",
          "sha256": "52bd445957250e06f6d00dc0d774c05b4a3cb55f1209e18e76e209df26eb7fc7",
          "sha1": "8abf2f49fda7414690b367b5cd283d4325a3942a",
          "md5": "1cc252b96d0552106914267e2b44a62a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "0223c3e4e6118f85c60091efe814facf1598df12a9066ff3c8d955e82a9557c03f964a6f197f9f9d5fa933aa4992566e083ac4b54cc05dad7f0fb09c935fbb85",
          "sha256": "cb52df77e4ae9854cfc469c55ddf9d1306deaad2a5a36e262c6e41292f1cee37",
          "sha1": "2551ab2acb33985f2fee632f44d42069bb16156a",
          "md5": "186b4db5192802d73be09f2cf766ac25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21852,
          "sha512": "e507f3b4c5f7e150132b6375f51dadca8c4589e4ff3243037ab6d1206cb155a279b8ff244988ffef49b630b1e93613b293ecda188e01234d7c1bcf220628e227",
          "sha256": "5644422a082917fc57f3541345f8b6cb87ab2f75162adb3f7a198aa11c486c67",
          "sha1": "36eb4fffea86e0e0d1268d728b128fd4a8bbfe37",
          "md5": "86c5f234ec3acb5f5be512ab299b3277"
        }
      ]
    }
  ]
}
