{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 57992,
          "sha512": "e07d5bbf58ab90095ac68a19a29db3b58177c7728c92dbfe5b2b96f19b7d0e7337cb3bb845cf304e5b7fd816648b80e4181dfe33e5d3977f6295d67c45486ce1",
          "sha256": "f3900ba72ad2d4c3b8dcf20c73a5a255301a2df02ef90825a0a0bc780ce3e832",
          "sha1": "7ac617963e32235ec622c852e9562229b860184c",
          "md5": "1e8f0f83e1e5b943c251b2e201fcca2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 57992,
          "sha512": "e07d5bbf58ab90095ac68a19a29db3b58177c7728c92dbfe5b2b96f19b7d0e7337cb3bb845cf304e5b7fd816648b80e4181dfe33e5d3977f6295d67c45486ce1",
          "sha256": "f3900ba72ad2d4c3b8dcf20c73a5a255301a2df02ef90825a0a0bc780ce3e832",
          "sha1": "7ac617963e32235ec622c852e9562229b860184c",
          "md5": "1e8f0f83e1e5b943c251b2e201fcca2a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 146125,
          "sha512": "136908a879c8ce7e0a1108178bf28e87967f138700adcb50cb2ff292cd02964f2763fbfd3aeeb93c029e8e8f10e5d47049f4786568ad025dbbe5e4e5a1d4764a",
          "sha256": "c882158f1b5a29d02c19b5c698abd9c7a093610b906539b95c1498e7d56d7dc3",
          "sha1": "f24853cb859f618ebecf1f824f92701d68b9f0da",
          "md5": "127236f9918d44ea7731169008b3ff05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21909,
          "sha512": "e18aa4778e720ecbfa7f492354143905eb1a80936894596791fa539b745930bd5541b963e2c4ae6c019fe0dcac9c3582f732b43002058ba264044ab66416f938",
          "sha256": "2e0274a2a8dc0a4ad73df298de04e6221162e4fa64b1e6f66f6d5f05a88a2ece",
          "sha1": "ff9b449fa4ab0c2a145d79492ff2f030cfb270e6",
          "md5": "5accf103214b970e69c0f94ac35e38f6"
        }
      ]
    }
  ]
}
