{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "73d3b97cb27af0f9f4eb2837a8e9f8cb4329352bd87980e2f49fb8bfc2e350888c2bb2f0f4d751a1e5bd7c4ecd4f85962231fb294a37bd64c792270839f93bac",
          "sha256": "20bbb6ed5923449bd88cbc64df2f1e6878a276d810258f60b8f8f881bea58a82",
          "sha1": "e281eec28c7272a97ac1d03107a67564cb1181c9",
          "md5": "c82355420b20f7297ca8c107a91ccc61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "73d3b97cb27af0f9f4eb2837a8e9f8cb4329352bd87980e2f49fb8bfc2e350888c2bb2f0f4d751a1e5bd7c4ecd4f85962231fb294a37bd64c792270839f93bac",
          "sha256": "20bbb6ed5923449bd88cbc64df2f1e6878a276d810258f60b8f8f881bea58a82",
          "sha1": "e281eec28c7272a97ac1d03107a67564cb1181c9",
          "md5": "c82355420b20f7297ca8c107a91ccc61"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155817,
          "sha512": "8ddc3cd821446b28e270574ad4bd229a1fb4b10394a8bf73e8b54fd5f21e1dd7aa04cc3a6ad1ada6a989e2a31e66eb4e29f3ddcbb6ced2640df4ebe499dbd331",
          "sha256": "722bed3d6e158fd28d54355b5ea63db236b2aba9e556e0e81962d91a0671930c",
          "sha1": "65d7c3b437f239861cf149f0411ef57e568ab4c9",
          "md5": "5460c7ffe49c2b9485c70d1f90d07e11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21912,
          "sha512": "ba310a307014d1ce434de62d9b5d050e1f4368f1062c86e2796aff88dc49aef18a7cfd7f946c9dd0422722ffa50da9d1ca16055b94e05950cd3fa00372ee2073",
          "sha256": "22eeffd79e1b65ad357f62f987aed57ad5154b317f126f3b6335fe9b2fbb1402",
          "sha1": "61416ab1db38dd0578e5dd94e701ccc016460222",
          "md5": "e3bca535c583e3306e37a32124e47b28"
        }
      ]
    }
  ]
}
