{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 59028,
          "sha512": "eb4023e495c82e1dc5b892ee494dc5ead8e1ad4ad67f0e7088f4e7cfc8cf44d8af355c6aa4bcca1a1c2e6553d372676e3ea242056ad1eb52c89649c963237a03",
          "sha256": "0a7ad6fd9d7d62ea967706b3b68caecb689ffa1701b0efc6340bb1ea19855db5",
          "sha1": "d0a7cd16c7d42fd34f776c234095366de1c21980",
          "md5": "bb8d86468e105f4474a08a453ddb55c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 59028,
          "sha512": "eb4023e495c82e1dc5b892ee494dc5ead8e1ad4ad67f0e7088f4e7cfc8cf44d8af355c6aa4bcca1a1c2e6553d372676e3ea242056ad1eb52c89649c963237a03",
          "sha256": "0a7ad6fd9d7d62ea967706b3b68caecb689ffa1701b0efc6340bb1ea19855db5",
          "sha1": "d0a7cd16c7d42fd34f776c234095366de1c21980",
          "md5": "bb8d86468e105f4474a08a453ddb55c4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 203591,
          "sha512": "771e7ccaf690383db22a7e40ed44121dff7ad2964f9a5e8010b04e71ebfbc9ab4b7cb8d02ac188f9c97717a79f2f3d5414c47af040412d5f5293e12f06aba8eb",
          "sha256": "85470770a4d88b13df24fde8dfb9e9f583aca66bb0bb9040e0617be099aedf3c",
          "sha1": "eaab0e94010cedcd2a8aed4013f18085bc34a9cd",
          "md5": "429dc5ca4dda1c55bd39b0100f1ffe7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21889,
          "sha512": "e8dfdb4ff1bdad06d98cdea1c6e141123e91cce3619289988291859ab8a46d0c836604cbd99e26fad1f909b280c7c692cd4a749e2acb184d2e627c255bd5f7ae",
          "sha256": "27aa02cbc4af741437aaa849a785563d22367d2d587532b1abc8352f21f26b63",
          "sha1": "6641fdef4580caae42f1eee79636266995977ae3",
          "md5": "2a5a4456e7fac74cf538ab15f5806d36"
        }
      ]
    }
  ]
}
