{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "c08c31c48563012fc148e03d2a26a8754a5cc4e0725b963edf3737893b5820199b117eb3584ea5afa85c1cb812166260aa97ca7a3e8d48714eb18c6ede054b79",
          "sha256": "bc771f111bef95dcb430f0654fe3b8273906dad09035168642a5a4e8cd29b5d3",
          "sha1": "8b7d332e05563eea2eda0afdc104370c96528b47",
          "md5": "9a0f84726e5315d4a2b186e87c05bc05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "c08c31c48563012fc148e03d2a26a8754a5cc4e0725b963edf3737893b5820199b117eb3584ea5afa85c1cb812166260aa97ca7a3e8d48714eb18c6ede054b79",
          "sha256": "bc771f111bef95dcb430f0654fe3b8273906dad09035168642a5a4e8cd29b5d3",
          "sha1": "8b7d332e05563eea2eda0afdc104370c96528b47",
          "md5": "9a0f84726e5315d4a2b186e87c05bc05"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "e15d5585c735a74154d52761cd41bbe350194246d75e45668e28dd21ac2519f064a05ff68a6bb4747107e4a5091352b9489a755d24e91a881e41c498b60fb922",
          "sha256": "1d969bb0732415714f0196ac2392940181fb1074d1e5a47d440155a12c67a3b1",
          "sha1": "3f0927d6e7c433888173b596abe8541c99b3dd11",
          "md5": "c6c86d5fa9ddcf4ccccb61029fae82d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21932,
          "sha512": "da4db4f4b669a2596f73528338695a077c9ab004a30cc8396078372dbca418dcb152815b956b9a1ed2a6e5959e996e56f6df455b3e55433290b2480254528548",
          "sha256": "33fc14c705f80c41e5fa1e5fc134a083a6bb3017c03296c1b17c88411fda0ecd",
          "sha1": "39fb2db8d83c081fdcb4b56ee6da21c4c3531ebb",
          "md5": "cc38fa973406dfd6200de061c6383e0e"
        }
      ]
    }
  ]
}
