{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58629,
          "sha512": "5636dd65caeaf57bd33842b3f9920375ed24b607b742eca32bb5d5d2c0d10c465aebf80f69dcf2d248a7c1b0a514de096bfd97bf4cd34ec1aa9db6b8d5fc30b9",
          "sha256": "8afc7480b88662a03b2143e55ef1168dc62f248e5d7d6cb725e000225df38b0a",
          "sha1": "a0aadc13927a7f00f35113a84f298b18ac18b6a6",
          "md5": "d82e8208cce9c4c2a2e024431ad6c36a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58629,
          "sha512": "5636dd65caeaf57bd33842b3f9920375ed24b607b742eca32bb5d5d2c0d10c465aebf80f69dcf2d248a7c1b0a514de096bfd97bf4cd34ec1aa9db6b8d5fc30b9",
          "sha256": "8afc7480b88662a03b2143e55ef1168dc62f248e5d7d6cb725e000225df38b0a",
          "sha1": "a0aadc13927a7f00f35113a84f298b18ac18b6a6",
          "md5": "d82e8208cce9c4c2a2e024431ad6c36a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 203591,
          "sha512": "584cff115391f28317c3d88cf394bdc381b71ecfd68a9c191af688a4c23452933e2e1d50dfd2183f2903fb7fb7b0ab8f31b2f74c3db2e3b3205d810dce5757a6",
          "sha256": "1f467ed7cd2dcecebe00ceb87d26e6c9eca7339c814c26dd50761d7d1282fcdc",
          "sha1": "44bcd43580ec208c641e8608f08a2c52e35b64f1",
          "md5": "e6e751820345a445c2df6b80906d56eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21920,
          "sha512": "9469cf8cb13e9edaaba79833dfbb861d3c9901884251b580717a7f8a3ca79bcdc57bd1116aa38d28f93b5fe640a0b6e7531bcd4decd1af7bddfa86ec7be24092",
          "sha256": "0130ff7790b75fe7e9a879e8168c1f0937f8a6dd7236da5b8b42148059493951",
          "sha1": "eb1d2b29055a2f7263ba0e6c75d9e3028938f437",
          "md5": "5ce57b4b23285b316b27605b425dd1b3"
        }
      ]
    }
  ]
}
