{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "0d063c988ca1567b150c39b766238457c2391b055c0b70fb760b1f495be2f09ffaa43ecccf0ef72d79524ae118c287735fd8f6bc6e456496126ab02c7ce265ba",
          "sha256": "704cf1cb063cc21dedb89b22e3da88d287cb0b40f2603538eae93cdc2b4342c6",
          "sha1": "1a00359797b9c2807d0c7dff0856b63e87088032",
          "md5": "3a98f412764772948b8f4eb034a53813"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "0d063c988ca1567b150c39b766238457c2391b055c0b70fb760b1f495be2f09ffaa43ecccf0ef72d79524ae118c287735fd8f6bc6e456496126ab02c7ce265ba",
          "sha256": "704cf1cb063cc21dedb89b22e3da88d287cb0b40f2603538eae93cdc2b4342c6",
          "sha1": "1a00359797b9c2807d0c7dff0856b63e87088032",
          "md5": "3a98f412764772948b8f4eb034a53813"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "348135d5526889a85e1361d56671e2ab5a7030f9c5f71260df6c10f4b28ae6086dab76819d2b69a8e4c5f3216f3b35f00aeb77721556d15e03c7ded55670f173",
          "sha256": "784bac3ce51adc7d02a6eb09ecde489c1f4d9ee6f01d66e568a991dec83341b8",
          "sha1": "20837e8cc8fc20a2cd11b2884f56a5e8891e2eda",
          "md5": "8a180a7eb817a7b4e97aaf3c285171d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21852,
          "sha512": "a017286ddb5665d07610564c67d32ea90896f52700fd9072d79cc9afd288c41cd09ddde96c495d0aa158358dcc07147a44679553f208437fe9b4229077fbcb9b",
          "sha256": "ac7c1dd69a84aa92fe1e12abc02e79f920ca0c13aa68a1467b27dd8dc166bf5e",
          "sha1": "720e437f9d10f2c62f76459d65b5e5946414aeb7",
          "md5": "d76d025c14bba0a4edea386bec9377ee"
        }
      ]
    }
  ]
}
