{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "8048b337e3a564cb5705b0d1db55332c984873f004fc8e19708b31f908b448856d58887e55d019363459b84db4aab3302ff5e22fcbd5ee65d473386da43ae7e2",
          "sha256": "7f303fc735ccead13291dca011f3e316304357982541a1e2fecf610e8ae7e941",
          "sha1": "a982e6a95fb77525bbef74eb5e9e1899c347bb02",
          "md5": "890e8f5cf5861e07f0ea6e5bb8a83be8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "8048b337e3a564cb5705b0d1db55332c984873f004fc8e19708b31f908b448856d58887e55d019363459b84db4aab3302ff5e22fcbd5ee65d473386da43ae7e2",
          "sha256": "7f303fc735ccead13291dca011f3e316304357982541a1e2fecf610e8ae7e941",
          "sha1": "a982e6a95fb77525bbef74eb5e9e1899c347bb02",
          "md5": "890e8f5cf5861e07f0ea6e5bb8a83be8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "d4dd30496c2b55d6ed418eb14edfcc0973eac792009cb48fba6762aed4e962016cb84c11dbfe5fa4d6834a8f4c8b1a6c675f73290333349983a8e7f453338b92",
          "sha256": "173fe7ee42cb05a88e39da8958d8ade11a6afde5de6d9432391d554b8fbfdfd7",
          "sha1": "ce5b5926231cb9e57521dd6d805e392b82933368",
          "md5": "2aa7ceae117f49f224d9979675f6d5ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21859,
          "sha512": "1b98b5c4b027a40143147b7328d7d4c482374237f1f6b3d5c3a553abb9c305e79e8e53f5096c7355ce5737a6067de2db9ff6b46835ddd3ecbd018e9aa7226fb4",
          "sha256": "93c42683d6deed277170385f2191d032774eb8ce89f8fd64b6af053d7781f805",
          "sha1": "25455ea8f4ed531c4a0209a833cf8660b8e46b8f",
          "md5": "d88afbfd575182cd7ec00a4e02b340a1"
        }
      ]
    }
  ]
}
