{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "613956fd5bda5b0b9cae65e71d8c639eb9845c3d1ff56b1abdbb0ac1fa9d0c464b684994dd3ca4246f5b76ebd0832fdb08369de983e3c04dd358a33719815f0d",
          "sha256": "b59ca11426bee65ad400f679600c0490420c8269b6be9dd3ddcd26fb656b2aa0",
          "sha1": "0c42830076a2575787c1d1298bd57733bf4ee429",
          "md5": "8cb3e215c281cb574e87b0a21d0adc8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "613956fd5bda5b0b9cae65e71d8c639eb9845c3d1ff56b1abdbb0ac1fa9d0c464b684994dd3ca4246f5b76ebd0832fdb08369de983e3c04dd358a33719815f0d",
          "sha256": "b59ca11426bee65ad400f679600c0490420c8269b6be9dd3ddcd26fb656b2aa0",
          "sha1": "0c42830076a2575787c1d1298bd57733bf4ee429",
          "md5": "8cb3e215c281cb574e87b0a21d0adc8c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "9c77fbd6a42f65426a38f4a7792091fd3871f0aa8d8dc62106245d383daec04ec33f98979b806fa01d08ca2113d419275a360ebb2daa40549f8c33edebbb383a",
          "sha256": "5c84fa977b0f646d0f1dce6f8a6b9abf1f7ace0411f6e552518e453e8f10d5f9",
          "sha1": "f8fa8485f0953bddf1e889fa681cd1e656457591",
          "md5": "1389442517a963a302079edeaaf1ede7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21852,
          "sha512": "3a43e4cf095cbed193bce7e8a756afd492a5218029470c50482cb34828bd1506f12cc6a92383f20b0b49475f4a703a6361a05bca9ef9b5e114773a7897f5f91e",
          "sha256": "78cdda626ba81fcdd094b0f43dc2165fe36010440743ade38eaadc3410a83412",
          "sha1": "7b63ac3c55ad4bdf74e4528160eb5a6b712f3fc9",
          "md5": "d5080ff02fa4d50bfcebe604239fafa8"
        }
      ]
    }
  ]
}
