{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "7ba2ea95608aa0fd1daa875bced9f37400f22305c30da99f71a7a50d201db5bc4257043ed7fa4ca1375a6ee6972627fb95a60460b78c2e04912e97481434879d",
          "sha256": "de5f05ffbd6d1f45f98de42c4c5b726e42875c039f80cfeb8014f0b830ef9194",
          "sha1": "bd19bbf5a6facd20647c0d7e5a110c2f2323c0c5",
          "md5": "ba51577bf50dc47ad5f03c652bd59758"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "7ba2ea95608aa0fd1daa875bced9f37400f22305c30da99f71a7a50d201db5bc4257043ed7fa4ca1375a6ee6972627fb95a60460b78c2e04912e97481434879d",
          "sha256": "de5f05ffbd6d1f45f98de42c4c5b726e42875c039f80cfeb8014f0b830ef9194",
          "sha1": "bd19bbf5a6facd20647c0d7e5a110c2f2323c0c5",
          "md5": "ba51577bf50dc47ad5f03c652bd59758"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "47730077a659006d9a84ab8b4173dfe8cf9ff3649456546571fcb874456a68eae2f0a50b5ee83124e7c372d28c6d548572df76fbebb2401af738c83a12a07d35",
          "sha256": "fd3a2b3b618d91e33a9188f5312854cab7fcc0fc5b9e6233532eb8afc2a2790f",
          "sha1": "9a3cbe034f56591538cd09e9fdd5aa9af751edab",
          "md5": "53dc8669001a5ff273491f4a99ca1623"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21859,
          "sha512": "a67748ffbcbbb0c8fa8fa1b5ea4c9d910307247c54d9403a2e6acb6acc9bb48b91815af16d4d39e79d14adbb3cd03d647815facbd7f6006317d93bcebd5d039e",
          "sha256": "29c684b993e6c72825f6abd24092f7e2ae28563cc459bc39d20b0778adc24189",
          "sha1": "968859a41bcd6b1567b725b09c8b4fc65c594d70",
          "md5": "c346282f31956e24c0ce0782cc62f83e"
        }
      ]
    }
  ]
}
