{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "5b50c240613df3d1c5ff4886f27d88b999c74c3e395e931ea54b6007ba7937f7c2d6e3d212f6784b44d60695d1ae5c86bf7bd479d181d1452f7a0ddad2927ede",
          "sha256": "3efdb82b517bcc66ab607917f83ecbfed08af336572e31ad2669d4cce1ffc959",
          "sha1": "c6f000c96699bb6cbb766ce8a91f31c9a4430ab2",
          "md5": "9f10e4fa31a03e9f0a24e6715d611167"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "5b50c240613df3d1c5ff4886f27d88b999c74c3e395e931ea54b6007ba7937f7c2d6e3d212f6784b44d60695d1ae5c86bf7bd479d181d1452f7a0ddad2927ede",
          "sha256": "3efdb82b517bcc66ab607917f83ecbfed08af336572e31ad2669d4cce1ffc959",
          "sha1": "c6f000c96699bb6cbb766ce8a91f31c9a4430ab2",
          "md5": "9f10e4fa31a03e9f0a24e6715d611167"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 156423,
          "sha512": "7b0608dd7475d5e84731dedf79dbf298d5c7cbc5513b4e77ac89ede03835634d6635e55f745f2c8f87ce254addb663f664b1e9628ce34f73ac9416fa8bdc1df1",
          "sha256": "8188448bc5635ed4aa0f7d581e96ad84724ba0d6e96f5e146f9b30a53578d96e",
          "sha1": "0be487853b770459873a712cdb8d7746b0e1981d",
          "md5": "0aa18ab055ed17a6afd46632c348b475"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21912,
          "sha512": "0233a09abce204fbae07e8469e37d1d521f2159a0cb06343a75a7d4a70d938fa67723f0e21dde9d964ee25a52d77f6922b28931a25839fe9b8c71a026bc68889",
          "sha256": "d8abfad380dccec1e564b9328246ba6344e79754334cc5f0471c393e542c2b93",
          "sha1": "a827b5870870ae68ff21669fdcf20a5c30498ac6",
          "md5": "80e3382253883797cf7aa7c385ac705d"
        }
      ]
    }
  ]
}
