{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "155d92267454958df11f3b6ab751ba81e8400b4acebe33f6ffa882f6ca42b0294eecf877582f427833d43934352b5ca59d2dd3f0c083300d3eb950a3fb2bbc3b",
          "sha256": "9dc4f76a0055376dac0935bc239f44627f406ac1144f9dfd95ce4591d1dd1233",
          "sha1": "5df3f8e23bb3c0a23494343d305ceac7843d9112",
          "md5": "79f0bdb2fb0d678067c8e20d5c208bc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "155d92267454958df11f3b6ab751ba81e8400b4acebe33f6ffa882f6ca42b0294eecf877582f427833d43934352b5ca59d2dd3f0c083300d3eb950a3fb2bbc3b",
          "sha256": "9dc4f76a0055376dac0935bc239f44627f406ac1144f9dfd95ce4591d1dd1233",
          "sha1": "5df3f8e23bb3c0a23494343d305ceac7843d9112",
          "md5": "79f0bdb2fb0d678067c8e20d5c208bc2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 156423,
          "sha512": "f02c4bb7d4c8875e11c136ac03cd243f70622c4a1e5035639d0735e5d40b806bd961bc141077ec48795ef4f1944051705752e43d9b2849b9dc7ee8ab10e59191",
          "sha256": "d00057c7657f036b0d6d4cbe1ab6507c682c761bc3ef70417363b1afe2eb9159",
          "sha1": "5dc8d733eb210f0d69fcd0d717701ad7393ddaf8",
          "md5": "a4444e89d0402bd922c02e8f4be970e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21912,
          "sha512": "0b1c3bc56a0740d88e09273a29873d8a9148b7d3158a57e84fa0ebebcd688350f2c8a876f785059b117c5c56ee5af9ef6499081d706510a4016a4e9d00a70b6d",
          "sha256": "a139302c13249fe9f2bbf7f998949d1e6d78d61eb2043121009ed39f34e6bcaf",
          "sha1": "bfe802978bc9f41ab55b2ec72075814114bee671",
          "md5": "52ac9b571a93c967923cdaf2a7a41adb"
        }
      ]
    }
  ]
}
