{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "a43d895a7e0fc2584d01e0f54ca24a26681026523355d4a7474f6e544656a42f4ee79fceebb1bded393ead2892f9a9e502fa6c1a47c2a8583447ab8b6594e2c1",
          "sha256": "3e80dc4f56bd4aeac21df7e2496d6bd0ed84b3cc978a2e1c7718ad2980ab0cf2",
          "sha1": "667dd86d794168ae3e7e825f4973d2bca2b0273a",
          "md5": "bc72b36e693c31653e27ee0bce7f96f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "a43d895a7e0fc2584d01e0f54ca24a26681026523355d4a7474f6e544656a42f4ee79fceebb1bded393ead2892f9a9e502fa6c1a47c2a8583447ab8b6594e2c1",
          "sha256": "3e80dc4f56bd4aeac21df7e2496d6bd0ed84b3cc978a2e1c7718ad2980ab0cf2",
          "sha1": "667dd86d794168ae3e7e825f4973d2bca2b0273a",
          "md5": "bc72b36e693c31653e27ee0bce7f96f4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "f2f9d369dcbd59b59b7f2ec109608ed9012165abcf379394148ab983d0db220bfdb56b9944b1fbda7f6ad749bab06bcf9525fdad1641fbfa724cd4de8ab30839",
          "sha256": "7e4100f82b8de0b677ade984843452ec2a224c3e02541c2c85872aec511d7e9a",
          "sha1": "f1e4196c7364d395f1a3e9f93f076ef7578afddb",
          "md5": "f52e49756cbdd752fa1cc20788e589bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21859,
          "sha512": "88a58f994d2844ab659065c8ee89026a7b7b3fc5bb2cbfc9c8a73d4304a01b959c65a4d6b258cfbaf814f2c805fcd1f32ac3778ba987588dd32e06b7b08a6aa4",
          "sha256": "ded5bb86b741ac6994e7aa299d1f47d9a078766c779e74124cf1e0e39b949d44",
          "sha1": "d725d7d1dd52bd05d7f73a0494d635f91e675cd6",
          "md5": "94c23e082778a33fe45207abec9c8c55"
        }
      ]
    }
  ]
}
