{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "9fe3a84a88adbc792f3aed1774ad2fba03171e3df9b886aedc86fc8e371b0bdec2d2f62669ea853314966507987063c5d6ef23d62ab97d9588c744449b319357",
          "sha256": "64551115f54cfa0463daec125c872803c755ae5a89ab8ea8dcac1c776d770206",
          "sha1": "e6e979088faaada6a64d6be953c3f6d63a427a11",
          "md5": "16c4688c12c53994c93720467edf3202"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "9fe3a84a88adbc792f3aed1774ad2fba03171e3df9b886aedc86fc8e371b0bdec2d2f62669ea853314966507987063c5d6ef23d62ab97d9588c744449b319357",
          "sha256": "64551115f54cfa0463daec125c872803c755ae5a89ab8ea8dcac1c776d770206",
          "sha1": "e6e979088faaada6a64d6be953c3f6d63a427a11",
          "md5": "16c4688c12c53994c93720467edf3202"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "fceb9cd7d8909fb22abee31b8c16383af1b55e33f0b46515bee49c30f0a3de4c65ac48c385ce0512cbc573c558401fabdaeb965d4e632ab8a9df82620409ef3f",
          "sha256": "99449f5ef04598afc6e15b2a39f10f1f9ace0251ad2b6a83138d3b5de9bb30b3",
          "sha1": "5e943a641c5d0831ef68a103271b528205e77ec8",
          "md5": "cf24f315f6d97a5993205cfd1fd969f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21932,
          "sha512": "30393c0a533f8cbbcfc20d23bcf709cfabbe8004aa6af78b45c57211ff54548eb0dfdd16cc4fa7ee75bbf6c6ab06e31730cbde9593e70a518214e3b55875337b",
          "sha256": "01817158063f953cc6a4ea67115ec16856a2dc724d6a6c45e2a0a4807f1f5ba3",
          "sha1": "20c2a8846d368585852f0736f9d1b09ebeb7beba",
          "md5": "7efcdfffc379b37d070b7b3b2c9f4316"
        }
      ]
    }
  ]
}
