{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "b14df0bce777d19a56be146add7effdaa24b0f748e1ea19ac4008cc40aedf1a56963dbcfa28cd02520f3433adf7e150bb3fae26b8fa15a257a156d693e7ac300",
          "sha256": "c2f428ebf8410d661e084095b96bdab6edee399e8fd26b84d1600775a4d1bd43",
          "sha1": "064ca93daff9e07c277d2e0ba430b2eee68a315d",
          "md5": "ecee744aca54cd6ea6219ad339fb18f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "b14df0bce777d19a56be146add7effdaa24b0f748e1ea19ac4008cc40aedf1a56963dbcfa28cd02520f3433adf7e150bb3fae26b8fa15a257a156d693e7ac300",
          "sha256": "c2f428ebf8410d661e084095b96bdab6edee399e8fd26b84d1600775a4d1bd43",
          "sha1": "064ca93daff9e07c277d2e0ba430b2eee68a315d",
          "md5": "ecee744aca54cd6ea6219ad339fb18f4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "3a64adefa1706fe3c6575ec6aaf730a9688a23757d2bb6aa1480ffba7cc7957716c62dc3bfcb8cc4fd20f9411b7af50371e827c25e4f0c2ad251a0f725f91442",
          "sha256": "b4fd02ee5fabf53c529af6f2da46e75ed8259dd365fddcd8e56be4d64677b240",
          "sha1": "5893c20687bbfb741abad7710de09d2eddcae414",
          "md5": "bcde0d09636bd8968154641797501596"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21859,
          "sha512": "11a09050ab62351ccb9708da1e50af6d61c8ce8a4155dd0be03e820b84b7836782e6336683096ee51d17e0b96cbd17a602e4b9b9219740850e64b1baa3908314",
          "sha256": "0b09d4a92ed92dccd4f31b01c571273c67f168f9d83f7e9e2a977a046b5afc43",
          "sha1": "5e89aff7e4d9a8092ec7682160bf292d05777c64",
          "md5": "d4cc91edbce0ddf452ee7a80de6daf32"
        }
      ]
    }
  ]
}
