{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 59028,
          "sha512": "d4be773aa7632c3cf52c2120f1c54ae4db535615e876d005c2af370b74f7bf76ed49a0b06a0ebd5dbe099ea1d78bdd1f981cdad85b00221de15fc8aa85abc9aa",
          "sha256": "c11858552fc8f6aa0d4fa52979e71645f50bd083aed4c7377241964e28f01986",
          "sha1": "7b69eace9d8396e79d5f5d8aa98da103fc457e5a",
          "md5": "82d24f184eacfc28bfd7bfef61e0fdf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 59028,
          "sha512": "d4be773aa7632c3cf52c2120f1c54ae4db535615e876d005c2af370b74f7bf76ed49a0b06a0ebd5dbe099ea1d78bdd1f981cdad85b00221de15fc8aa85abc9aa",
          "sha256": "c11858552fc8f6aa0d4fa52979e71645f50bd083aed4c7377241964e28f01986",
          "sha1": "7b69eace9d8396e79d5f5d8aa98da103fc457e5a",
          "md5": "82d24f184eacfc28bfd7bfef61e0fdf2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 203591,
          "sha512": "c826c9356e4a88e9b47c6d426d71b4899bf3f1e57ea3ee6fcf831539f2b6c50a1e89cfce2cf681e7b3b30fd2e2af7729da9611eca392f2039c7fe44ce891bd09",
          "sha256": "785fa2075f81fb4ad55fc0f5eae997c42787c47ac846304c64e2c34104c34c58",
          "sha1": "14f611dc7c362b2ca1a6a53f99a1ad979541c161",
          "md5": "0116db11a1e74cd537b0a089d9e6b5b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21889,
          "sha512": "6560514ddb0193ee09f025f513bb571651e02cde69cf36c18654ef29378ffe5eca2eaa92cfca333fa50bc634a0f7d953746f2579a2841de5b5253786535ea4cb",
          "sha256": "7577986b3a860444a43a22513ee46fea6e8c1daa4e7970b772535a40d496cc4d",
          "sha1": "5b900075f410eb6ee4bbfa64041e55050ac192b9",
          "md5": "23ef7ef41e3047215c0eb0db3c24d89e"
        }
      ]
    }
  ]
}
