{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58207,
          "sha512": "2e14589a6ac2e0425e5777199680bb34a562e9f76bd8d77a2cbc53b356abd6ae1fcd62136e830adeada8349ae2274bc24b1d0c319e8fc7ce72a72bc321c333af",
          "sha256": "84e1ca1f627476e0defd86499ea70453fae659ef9ecaae0d27b61a3a6b2156af",
          "sha1": "785eaf613c78ea0bdac896ccd74b442729f1cb53",
          "md5": "18aee9f4b642ace83bf6daf8e9971a1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58207,
          "sha512": "2e14589a6ac2e0425e5777199680bb34a562e9f76bd8d77a2cbc53b356abd6ae1fcd62136e830adeada8349ae2274bc24b1d0c319e8fc7ce72a72bc321c333af",
          "sha256": "84e1ca1f627476e0defd86499ea70453fae659ef9ecaae0d27b61a3a6b2156af",
          "sha1": "785eaf613c78ea0bdac896ccd74b442729f1cb53",
          "md5": "18aee9f4b642ace83bf6daf8e9971a1f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 156384,
          "sha512": "8562f1f085ded5f1b06d457edb47ff30179327e08ee04b257ec65d0a9b404920e06d2eec3a47453f8d24ad87d5e360e6506f5e7ce84f6eab4603474d568223de",
          "sha256": "0c9784ffee3028fcaa194864429906e3f46a9adcbdb7d43d2aca654e54fb46e4",
          "sha1": "7ae8af96458036a4f657ec1be31155e11714c638",
          "md5": "2fcc46f69c8e43caf238056c528d47dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22121,
          "sha512": "92fc740a46b94188d80d2bf868fc7e3aa11b2e2226e649c23f6073c9ecf8c7ed94b536ae2e6e2f345e5f1d78b07802668e88081cc6bd4d05b88628102733d067",
          "sha256": "abf29ce504f6c821e25dc7fa7025b4768fbf35f93e9a82baee16c8cf615cc9d1",
          "sha1": "ad09b7be4433ed586d05765d4135510b21b1a4ec",
          "md5": "25264197402dbb4750e475f490668c16"
        }
      ]
    }
  ]
}
