{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "447c6393e6103776bf991542164cd46b664767f75f501b5604b26220b813a8dc4d583685ae403252e0e1b6e1f156ad74d5c75e54367b78657163101dc785d02d",
          "sha256": "268052eb82a8ec8373a89cdaa34f8a185f9c7d0a1f6c1b9d3a908637ca27115f",
          "sha1": "f08dbebae753e4bfd8822b2660469bf7d723c510",
          "md5": "946fbf4c0b98180db5807cda0eb0ee81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "447c6393e6103776bf991542164cd46b664767f75f501b5604b26220b813a8dc4d583685ae403252e0e1b6e1f156ad74d5c75e54367b78657163101dc785d02d",
          "sha256": "268052eb82a8ec8373a89cdaa34f8a185f9c7d0a1f6c1b9d3a908637ca27115f",
          "sha1": "f08dbebae753e4bfd8822b2660469bf7d723c510",
          "md5": "946fbf4c0b98180db5807cda0eb0ee81"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "853c3117255bfe99ed2f460b3d33f4803c1079b11ff97c8ea29be9bf308d071a61a6caddb1c6f6ff47e74b401677e33e00777c5a211e0fa45fa7f8a494e52dcb",
          "sha256": "e2e3f690ae766fdffdf69c6d469360ad41b0427593721e9627629982fe4fd1bd",
          "sha1": "420b7d1e01f3f2482fde77e191bdf43583b60b6c",
          "md5": "c8c3cf645c5643670d4b2a67bf04a8ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21859,
          "sha512": "52fb79d630fce9cad906414b89f5649e8d655268fa832585a79be6792ddf9d7837b2f2d04f0d34728f407a046328099c36aca38ddbf466b0348c009d9b7a213b",
          "sha256": "a6bca1905a06d4b315713d2b039110a89edd23cb463b23fe0ced780417790a46",
          "sha1": "3d5ed1e3eee435ecc6ade47322877f2a14aa8a59",
          "md5": "f8fc8dbd9a5b4e4eabc7835213127535"
        }
      ]
    }
  ]
}
