{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "8c2c297f59f9d61f6ffee6f9239f6654a8d605a65a19c7713ad921b7c8026593a7dc497287cb22bf3da3069a5c90878d075dd8d55b9a164586da927a518e91b9",
          "sha256": "680c538443e628ad72e0ad751938b69e15c933040b1640c35bb50959e8b3dec1",
          "sha1": "499a5bbc8cd5e5f3269348439d714192117c898c",
          "md5": "9fb7968f23f349d38b639f9c4f7cb7ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "8c2c297f59f9d61f6ffee6f9239f6654a8d605a65a19c7713ad921b7c8026593a7dc497287cb22bf3da3069a5c90878d075dd8d55b9a164586da927a518e91b9",
          "sha256": "680c538443e628ad72e0ad751938b69e15c933040b1640c35bb50959e8b3dec1",
          "sha1": "499a5bbc8cd5e5f3269348439d714192117c898c",
          "md5": "9fb7968f23f349d38b639f9c4f7cb7ea"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "291853b696c28c0f8c8286db89ef5a62b2654612409756799bf125bba59634a02ac989efe16b26dadc814d02a4697e7ac838d01666fff1bfa815686989e5da85",
          "sha256": "c492b4fd7f138c24f3212bb0ba7d836b313113faebf5d20cc0f45f62da2a23e9",
          "sha1": "9f5d079f48cf5bb5ca4ba896b4e545c034ef6875",
          "md5": "9bd25417d12219f8926452aca9b276f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21852,
          "sha512": "b11f3e11c5d6be77d67016ba6364205acc419820ba69978a1d912a21545474460ad9ea25d50def39956c6512115730355f848d29a6acef286235d46bcb1414e8",
          "sha256": "ede40a53d9045e733d8703ff4ae2f2bdc13d75a8b6dd2c2f3fc0eb2ef54b9b97",
          "sha1": "b974e67bd9a81fd3f0930c9dabcf539830a13ede",
          "md5": "e4f7026675d71a191e1d2155df64d899"
        }
      ]
    }
  ]
}
