{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58261,
          "sha512": "ba35caf0ee40781e115360d394fe6c7dadde139492df2ffcaf3bba3d7fc13b2b67d9683e61e6bdbe4af45557b2500433e9ce81d2fcff923f6160c4533662bccf",
          "sha256": "5f9826b07a874c574d0f09ef25e377d8d2b663a9d474daf768a8a4f28c2e25b2",
          "sha1": "7fa73833fafc72dce588738866d3bba5fd1d602b",
          "md5": "97d363ca03145a521d608d89e960943d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58261,
          "sha512": "ba35caf0ee40781e115360d394fe6c7dadde139492df2ffcaf3bba3d7fc13b2b67d9683e61e6bdbe4af45557b2500433e9ce81d2fcff923f6160c4533662bccf",
          "sha256": "5f9826b07a874c574d0f09ef25e377d8d2b663a9d474daf768a8a4f28c2e25b2",
          "sha1": "7fa73833fafc72dce588738866d3bba5fd1d602b",
          "md5": "97d363ca03145a521d608d89e960943d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "a1a357cffd3eccbb7eac73e7a509f7084441441a07bf0e0182e5419c36afbe3b5eb1e8a38adadffe0dc961ada5d52a6e0112c3649aedcaa85a76d6a169a17ea2",
          "sha256": "6b1d5d90843f605a7203b46edc5712f2d03a59ab226b233bc0663b942c4bb17f",
          "sha1": "5bdbbe5b52f747477730cca8098e8621a0e3f6be",
          "md5": "d707fcf93d76ebdae06a17a9fb43ada7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22142,
          "sha512": "97edfc156575ab85bf17e027ee34442c7b079c17317db64eb3ba11bc4a0574513be1d4f5c38748b081b224fd8e9e008171847ff2ed1aae3e05c191b9079b3303",
          "sha256": "42f51904584125d44c43e83753a8067b41d2115a3bcb7d9d9603b857d7aa833b",
          "sha1": "1d46adad6c56592bfdd2b4510d54ab89106c52a7",
          "md5": "eb45c747137e687d2ddc3a678d133ec6"
        }
      ]
    }
  ]
}
