{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "510fbb61c4d2c024083a14906f8ccdd8b941519b6131089b65b945c39c09c935e4d6f6d1d7085a226b5e3d301c5307e415497a17af7728d5686c541923faa882",
          "sha256": "ad77cd93fe05e2124cccecc1d86b1a273c2bb0fb1f27cb1b9f0a4bc87b299f67",
          "sha1": "1a189d9fe112388f0ce70bd28e47c9e96b0bcd13",
          "md5": "e6c61170cd1d9eda2a408286aa87a6f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "510fbb61c4d2c024083a14906f8ccdd8b941519b6131089b65b945c39c09c935e4d6f6d1d7085a226b5e3d301c5307e415497a17af7728d5686c541923faa882",
          "sha256": "ad77cd93fe05e2124cccecc1d86b1a273c2bb0fb1f27cb1b9f0a4bc87b299f67",
          "sha1": "1a189d9fe112388f0ce70bd28e47c9e96b0bcd13",
          "md5": "e6c61170cd1d9eda2a408286aa87a6f2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "b66b44ea93f49883f66227cada67c8fc845f4242f8a69739b025f7c227f299206b16c397957164e68dc2a985e09e7f82d9e5afa18e1dc953898e3768a2797d5c",
          "sha256": "ea57be541b5dea66ff008192f60ee64a715d32c478a7afff9fad8bfc415a8720",
          "sha1": "4c6b724a0b9a7796012e3db9741efbe565a3d234",
          "md5": "ae0085060beadfc817c81e7771aba0db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21852,
          "sha512": "9a793269e3bdfe87c820bf5f73b767521f07802729c903990f6360182a8afd0290b91314d3f4327a909f1df86e7e791aa897529f5e19f407dc4899e220ad6415",
          "sha256": "773fde45a8ab8428400064597a11ba96068a0d504346779f14d07afa1306a885",
          "sha1": "1c8098cdc75088b67a49046f24eef23bed8c84a3",
          "md5": "c02218420f1a59c119003d1998f718c5"
        }
      ]
    }
  ]
}
