{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "df49be2eec8901c10ef8aacfd0fb4b6b2cd98074c9d917a4f0fff8358e86a5c8048087bdf757232140cb610b5e51ab91fc57cb46e5c88939a7188b2c03fc0110",
          "sha256": "87931b281106d4ac32d95e009075b269b3f7936103794b1f30f3ba4b7e7f2651",
          "sha1": "5278cc1574ffd6c3f206ba8ecfd50a9c4d0a49fb",
          "md5": "917471a059872a9ae4464bda04aa7d71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "df49be2eec8901c10ef8aacfd0fb4b6b2cd98074c9d917a4f0fff8358e86a5c8048087bdf757232140cb610b5e51ab91fc57cb46e5c88939a7188b2c03fc0110",
          "sha256": "87931b281106d4ac32d95e009075b269b3f7936103794b1f30f3ba4b7e7f2651",
          "sha1": "5278cc1574ffd6c3f206ba8ecfd50a9c4d0a49fb",
          "md5": "917471a059872a9ae4464bda04aa7d71"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "f17b3fbea60364bef4d55382846d5815f4bb42951e181e98897f4b62613862c0f8a7d2ad035317c2da4a270b614ab3acf4eb62ac9eea673dbd7bcf9f6f492a10",
          "sha256": "cd1e71c676a59ffa7e963ff2a1ff8d251b7a19222366641f78c004ed8ee2098b",
          "sha1": "cd439cc20b634410b2546f4524753748fc406d37",
          "md5": "0bc57a49b8bce0274f8e4f2a80367ee2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21932,
          "sha512": "9d280656e74581c1eb41b85fd73897c1284af07e699c530469a4b5c67e982ddf168a45b531ff28b6b89a8fe75fccd177ed95ee751704f91be2d1464b32598ac3",
          "sha256": "909b38f20f423076d9fba21491aa8333fe0b7edaa575017ebc5f71c8c5c1dacc",
          "sha1": "8bb8b129c2f8409ea2016053324bde0e23bbe050",
          "md5": "f209c14efa07873518e6a9ad335a0ea7"
        }
      ]
    }
  ]
}
