{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58121,
          "sha512": "e0eee29746c581dfe355ad1bc553483f0e15eb0faea9a06a0334a3553ec9b80180df481dd97653bb2d79edc23d5a339bd667fa791cd1c482435b0bb103d28637",
          "sha256": "16e593e21fb7400051308fb22a4a32e3b53d6d0ce0d6ae8f6be8ff9191d7ed3b",
          "sha1": "15fdd757dfd435a2906e81d17360b55225a2eea1",
          "md5": "36b8d8645c036aeedd99f2c38700beb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58121,
          "sha512": "e0eee29746c581dfe355ad1bc553483f0e15eb0faea9a06a0334a3553ec9b80180df481dd97653bb2d79edc23d5a339bd667fa791cd1c482435b0bb103d28637",
          "sha256": "16e593e21fb7400051308fb22a4a32e3b53d6d0ce0d6ae8f6be8ff9191d7ed3b",
          "sha1": "15fdd757dfd435a2906e81d17360b55225a2eea1",
          "md5": "36b8d8645c036aeedd99f2c38700beb7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 146125,
          "sha512": "539615d679adb4979e22283da6b1cd221ee1e845cba4151be845958b08a7233e183da24aef6a4eb9ee113534591ff8a55fdfe6b3c6d46b4cdc5aa651290d8d79",
          "sha256": "b2491d969be505e9fa0042b84d704fc772cfa48e7307076425706ca0b4b990bb",
          "sha1": "3996c301ba272f730bbccc66cf01e1533b1c5bbd",
          "md5": "a175d4f57f7382d78f45f55946c75541"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21941,
          "sha512": "4abc65db2d7b0336b678e3df1a5bff9b79d49be781caee3478f214ec7a9b1e5b6a5a95c32ec005d07d9e1668e71928d75d7ddc25f115f9c33eb7e4ce3fa11011",
          "sha256": "75dfd9fe5b98589cae68c7bd5b4e11306a85046030c7d398c773766975e2286c",
          "sha1": "47410c41d0409e29b3fb69ef32fc1d682c507d4d",
          "md5": "fef4aed67c9de24035910537f32de939"
        }
      ]
    }
  ]
}
