{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "c049848df2c4998cd9ce72407ff96cc27b95090e4a5445ed3aeb7183ff7baa80bda40bac244629aa257dff9f9f98aa4256e2a2a6d51d52ecb1383cf9cd45c3c8",
          "sha256": "90666f47c848781c743f61d6cb1430fd1c72166c07d94dbe214632528f55c90c",
          "sha1": "c3f5f96fa5adcfd382874d912646674f3a3aeb9e",
          "md5": "228fac9ef61fc636b2f881dcee5ebd1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "c049848df2c4998cd9ce72407ff96cc27b95090e4a5445ed3aeb7183ff7baa80bda40bac244629aa257dff9f9f98aa4256e2a2a6d51d52ecb1383cf9cd45c3c8",
          "sha256": "90666f47c848781c743f61d6cb1430fd1c72166c07d94dbe214632528f55c90c",
          "sha1": "c3f5f96fa5adcfd382874d912646674f3a3aeb9e",
          "md5": "228fac9ef61fc636b2f881dcee5ebd1a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "b9db98e96faf8923e476c8f5858d5ae62ff2184dfded0a736c98af7679e4ac10ca3e481808f275518b000a6b92508d1d4e5f1c852df9b4ffe6428e66e3e0ae11",
          "sha256": "b168814a5b02f8a8fbb38be7dbc45e73514bd96f735aabfe02ffb0ff088eddaa",
          "sha1": "64f2ea63a90fb0211e904b494efeae956aed286b",
          "md5": "f37431a71a3972a109d04077af30b9fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21859,
          "sha512": "92f3223a524856e8c780682cf2c102843a6cba06ae7e83276b379f89a77866ac7e976f79db5bab0f105b6e511841a2a1cf9063634f1aa6ade5137896c7572f53",
          "sha256": "fcd295b0c7e4e7f2d85e11c38c95d25f3e9b10c684517b0e9643b684b0715bdb",
          "sha1": "99bbd5681708d7776519b857cf9fb3315467a97a",
          "md5": "b45d53ae02cc835d6e8184409e4891c2"
        }
      ]
    }
  ]
}
