{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "707c3315769e7a920c00997c825011afb18a8020c7fd7d560c43a8fa198d18b3c26295f92c54a4b617f28f1b40ff37629c948ff2297ceab8a01f10c0b66c95b9",
          "sha256": "4b137fc231b3e20425fcd9493171c8d477a18a7a46d8b8efaeb27a53297d6c3d",
          "sha1": "5b1392eb6a5810daa516599b94ec24d3aa02512b",
          "md5": "d81e6a7a28185e02df82f0db00be79a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "707c3315769e7a920c00997c825011afb18a8020c7fd7d560c43a8fa198d18b3c26295f92c54a4b617f28f1b40ff37629c948ff2297ceab8a01f10c0b66c95b9",
          "sha256": "4b137fc231b3e20425fcd9493171c8d477a18a7a46d8b8efaeb27a53297d6c3d",
          "sha1": "5b1392eb6a5810daa516599b94ec24d3aa02512b",
          "md5": "d81e6a7a28185e02df82f0db00be79a6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "b6e3ae56173a16810139bed7e09dfea1842bcc51621b118f25c77593d2f0e00a603a9a447928a27aa4594b186e4663f5952cd49768c9a32e4b0fc9f206c9049b",
          "sha256": "fe815485cc761b8f706ebbaad69c3e02e35cdcc098e1047800b07f2d8b99d6b6",
          "sha1": "396178879add3fac4e19a0e5d49a29d7d08ede3c",
          "md5": "62efd6fc011e110828a85d344b71ed42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21859,
          "sha512": "7b57c6e5f7d8308a50d8a45d28b5c67f63b2a6b47483d74f6e5c6cf4cd94c9d2425a88ec48e19e22114f866a91bf4d029f5da41cf1972d1288f296753f345388",
          "sha256": "5688b04a8e8797de3fb1b10ff863a010f0f3312bf007439452a0d8e2c0939f4c",
          "sha1": "ee26751bbaaae84ea81202349c95a9ef5e78e204",
          "md5": "ddec656d066d23cc65a8716d83dbd26a"
        }
      ]
    }
  ]
}
