{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "c10297918bf31b81ec084b772cd57fdfad7bbf736d0db815bf4f6e807ddc8a00026e0c4b95be7cfbb7d27f080d52031ced3c42b48c200460fee5fc657535f294",
          "sha256": "4be80040847e9077cd3e7d25a9c244214daa26fbe8362901e6a10ada33ca166b",
          "sha1": "ed3c565470c94c013d57ff19e7f2815975170459",
          "md5": "13894fc4defef178d5b2bb0d90e6e345"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58115,
          "sha512": "c10297918bf31b81ec084b772cd57fdfad7bbf736d0db815bf4f6e807ddc8a00026e0c4b95be7cfbb7d27f080d52031ced3c42b48c200460fee5fc657535f294",
          "sha256": "4be80040847e9077cd3e7d25a9c244214daa26fbe8362901e6a10ada33ca166b",
          "sha1": "ed3c565470c94c013d57ff19e7f2815975170459",
          "md5": "13894fc4defef178d5b2bb0d90e6e345"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "97cda0b6b3007a8fcd537675fe5c539fd732efdfa1a562b7bf1a924fa330d0532045ad4a2c671adce4e59dc90e5de502d4d1313215a9e167c47da8e96d623f36",
          "sha256": "3cdc779ca6118f5ee0c8720cb17484991efd0bb13ed5132f53afcb991d44d6a6",
          "sha1": "92908beb0345a582e4ff92d3e33952961699f5b5",
          "md5": "efd248b74968fc151aed98cba2c9fd87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21859,
          "sha512": "2deb5fefd3136f8ac7816d86c69b53a843164a9ff1c6f6283f4b254a879d783c187c4437e938051673ecfdcfd9ea607aba1b4f0055ffc9e1168b13dde46decd2",
          "sha256": "53fd31dcf95de1b08f8a1f5abedd1a891e9f6703bde073af7abe1963641aac4e",
          "sha1": "aeeb98d3a5c5449833a26cce5d07533eccb6c0ec",
          "md5": "cb36931c127e684f3c22b28d061e1926"
        }
      ]
    }
  ]
}
