{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58207,
          "sha512": "d6813afd1fbfb7319e66c57429043c95d3fdbdd10c70d600136c982d77f7798d61180dd21522ba71591b590a438683ffcd88e2aa2503fad1837211de7fb9eace",
          "sha256": "5c9e3aa31283ddc943d79861ebebeb8d5d389f7e80abdb6cc7cd79b8d9dfe091",
          "sha1": "a0703b45e93cc7c29f630bca5203fa7da0dea86f",
          "md5": "b2301eb9e0a6920094d1517a2d3693a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58207,
          "sha512": "d6813afd1fbfb7319e66c57429043c95d3fdbdd10c70d600136c982d77f7798d61180dd21522ba71591b590a438683ffcd88e2aa2503fad1837211de7fb9eace",
          "sha256": "5c9e3aa31283ddc943d79861ebebeb8d5d389f7e80abdb6cc7cd79b8d9dfe091",
          "sha1": "a0703b45e93cc7c29f630bca5203fa7da0dea86f",
          "md5": "b2301eb9e0a6920094d1517a2d3693a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "ef76fbb7efbe3230888fe3b562cddadc4e9c9c5946c88978a59563aedfcfaa93763b852757615eb9d7e1fec109e5963ed0b42126c6a32787e9804f9a44a08ed8",
          "sha256": "0d69edf5c45d5cd7f51bf1eaf6302c3a881cb32dfcfe5056cf345b9a93c7864c",
          "sha1": "35ca37381572b953e3453084e71b8f818220e755",
          "md5": "b900c73ffb70360763a4e2e6ceeec07a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22121,
          "sha512": "f1d140bd121c11fb12e9d9f13c776236d213b21a62a72037200032a22ed425fdcb8ef1c21d03801043a129fcc79abcb9de9c389c002e489e00c2865329925d99",
          "sha256": "1a83d7f357de578e4fc3602ac58ed8f967a44527089ad7bfc48f1efbd6f7f5e1",
          "sha1": "f879c21e4f47d15534c42292da578e534b002727",
          "md5": "d68c3f68374c0b88de6b9c072ce9d83d"
        }
      ]
    }
  ]
}
