{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58556,
          "sha512": "ae7772a821a759aaf89ae87d737b4f651b0bfbc3437aa740ae25336d2d6549ff7d959cb608959249000b8e338eeae271ae8993f9a7941b95c25f1f7c16f3c972",
          "sha256": "debb349d11cb46febe6be2877ba6510b7b417f47c7573416815351a436cc071a",
          "sha1": "5277c6d0bb95af4351c69892c8f3202ef74e44f7",
          "md5": "28899e26adb9a859075977b8e6e2ec92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58556,
          "sha512": "ae7772a821a759aaf89ae87d737b4f651b0bfbc3437aa740ae25336d2d6549ff7d959cb608959249000b8e338eeae271ae8993f9a7941b95c25f1f7c16f3c972",
          "sha256": "debb349d11cb46febe6be2877ba6510b7b417f47c7573416815351a436cc071a",
          "sha1": "5277c6d0bb95af4351c69892c8f3202ef74e44f7",
          "md5": "28899e26adb9a859075977b8e6e2ec92"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 203591,
          "sha512": "a70a98dc73e222d401caba927f7c6c142fea39a0900c94086809cdf06cfb153e56894ff1b6e268d479d4f710c2f83d398eb76559184a014cfb685cf8ddb63927",
          "sha256": "2ab0956cd9b70491a2af6c308e8aedb2119c907a283c860b81f3e01d837db510",
          "sha1": "7ab42cf225022639c5a091d92a91d6ed7186f838",
          "md5": "1d0c35b9bc65e005e97de736b3f3d1de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21917,
          "sha512": "f6612845f5aeb441c8bcd833caf2f6de8bb5a35b78a15211bca22344770df328a57d8ceb425e50ded226db874c0513ad5734c363af6d33b902f89a3e9c1c122f",
          "sha256": "f597dfa32e0700aa32a7f3d75ced46b3e0bba7ac400fabe2131379560b0095d8",
          "sha1": "e31238dc04023a91887bf9d29981350d3f3de2d6",
          "md5": "a8112f2f0706ddbecc2adddfc803aa93"
        }
      ]
    }
  ]
}
