{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58299,
          "sha512": "c02c44a176424247d1015133edc3a58660c9f61fdf5883146b1e8366be4b0b0b8bc40017c6bdee8d6d2b97f49de4b805b277a8e7f9faaec590448e3a8e5383c1",
          "sha256": "2b22ee96999bb7a29b28b7ffc1b54de94fbe60606298c8302deed150507a5591",
          "sha1": "2a36b2f41c3bcf99c0f212985fa9183c6c205d06",
          "md5": "81c0dfa4bc7b2c88d44bc3958aa3a238"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58299,
          "sha512": "c02c44a176424247d1015133edc3a58660c9f61fdf5883146b1e8366be4b0b0b8bc40017c6bdee8d6d2b97f49de4b805b277a8e7f9faaec590448e3a8e5383c1",
          "sha256": "2b22ee96999bb7a29b28b7ffc1b54de94fbe60606298c8302deed150507a5591",
          "sha1": "2a36b2f41c3bcf99c0f212985fa9183c6c205d06",
          "md5": "81c0dfa4bc7b2c88d44bc3958aa3a238"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "2026c0dba3aea4acb28c38d34a19ce7354a29d194062ed9b9f6f27ee509b60a6f68aea643ea89fc50c77313cc0b51310f25af6323e97a1e2b8de63561995ecec",
          "sha256": "730e0a191c90a6849921dd0a07ef5a2d5379bdc208af778813974bd1c1e83420",
          "sha1": "f61f4db62bb6688be608d546b10ddd7909decd20",
          "md5": "b6573777409817babab244b7ccd5162b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22138,
          "sha512": "e2d7c726c894f12b1f889a350ac5543fba26a40edac565c9874dc3e74f32098ce8e02d72e0bcebcdcbf1cbb6f9850c75fe07a1282b6aa245fc64582793f101f8",
          "sha256": "0ab24490cf6e08787c05b7137068e6c3ca44851c00e0040817cfc7b8a28a5c6d",
          "sha1": "abf54354526f780db8fc135d78757bb5231fd4cb",
          "md5": "d3ab8b33180041d228b0d2cb363693ab"
        }
      ]
    }
  ]
}
