{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58207,
          "sha512": "5ee33fe99ff020507158101bb020e96064b25ce93bb94fe3e4c516fb5ad8f4eff498522ff87ddb0d4a138b2c9faaef5f2d71db20c7c720894028ec51164357ac",
          "sha256": "5a9c96c7d6856ca6d2856975e330eb178f5ed7649ce4797d95c3ad6b4c76c1ad",
          "sha1": "96cb5454765201e4681b719b98cc8fce1cc12f65",
          "md5": "7122a4ab5892b5dd9db47bb8115647ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58207,
          "sha512": "5ee33fe99ff020507158101bb020e96064b25ce93bb94fe3e4c516fb5ad8f4eff498522ff87ddb0d4a138b2c9faaef5f2d71db20c7c720894028ec51164357ac",
          "sha256": "5a9c96c7d6856ca6d2856975e330eb178f5ed7649ce4797d95c3ad6b4c76c1ad",
          "sha1": "96cb5454765201e4681b719b98cc8fce1cc12f65",
          "md5": "7122a4ab5892b5dd9db47bb8115647ee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 156384,
          "sha512": "f74d01e92525f8de9421f3fb698fcce9d82435d623ab8ab06f2e18de3fcd21834454aac0587d994a73bd7d5c93622f503b0919b88e6536a956cbd92c8c076f56",
          "sha256": "6dcdad7055f46e86f91a00db52cf78159d7dfe8091a9a5465279998ce567af81",
          "sha1": "d2cf4219f0227719b4c8d7e7d8667547ce6041ea",
          "md5": "46eeb7d318e8a4b9d11b786b997204c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22121,
          "sha512": "cf1ce4004dc53b4bbfe730887795d7a61d4dbbc7497ad6ea5f2fc404b4a41b3d40d4897729b938602b2679e6b15c471da127dc095dec64511790c6e35c707f96",
          "sha256": "9a541d358e200b928a13dd0e935622b185e009ad097561ff7a501f2342d8f3a6",
          "sha1": "76b73537b24300eb0f6a53ffb31c177a31110bdf",
          "md5": "5c1f1a5ecbb33abd50e219c4cb67983a"
        }
      ]
    }
  ]
}
