{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "23832660d72bc22cc723f6752b1a861a8fa5a6e9d5d40e709f345cda0971b259a5e8e2f9676547ea2a87383d3911a2946c4fb3f7857cda120ba74163f352d5df",
          "sha256": "721038155fb5677a9e0eef902dfe951cb6e3c48c5d1c7c9a92472bce29dffeb7",
          "sha1": "9c1584bebc70e5c2e77963b349d6a48c942b8d23",
          "md5": "eabb52885b4b696ec1651a97d9c7d494"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58300,
          "sha512": "23832660d72bc22cc723f6752b1a861a8fa5a6e9d5d40e709f345cda0971b259a5e8e2f9676547ea2a87383d3911a2946c4fb3f7857cda120ba74163f352d5df",
          "sha256": "721038155fb5677a9e0eef902dfe951cb6e3c48c5d1c7c9a92472bce29dffeb7",
          "sha1": "9c1584bebc70e5c2e77963b349d6a48c942b8d23",
          "md5": "eabb52885b4b696ec1651a97d9c7d494"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "c7e5ba69760e4879e0e7e38d12a9e904d63831d57961ad35cf827d246cde19418f90596bb3463b39f64ae61d1b68a2f5cf700b4843c2d42d5c869362eae327eb",
          "sha256": "1ea6e19fef2f618817a56fa60babb5345ac2af1ce79bb92eabd3f06ef7815a72",
          "sha1": "7c21ea6e86e148658d596184071b5efac74c604a",
          "md5": "0001496910cc99f551b4526877bcad84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21912,
          "sha512": "8c0ad1c1adfa09fd96a129d1209a94300b97fb64a0dcf72391006c88e176ef14a858f53dec0d758016b94832042c2245e9f975692e423736d779175de5740764",
          "sha256": "986897cf45f737671913b4106f2cbb03f5be1c1d515335741be6940b9d72555e",
          "sha1": "1870687f4be141d6920b7a07580cdfbb2385c2ee",
          "md5": "a77199f03eeb7325ba9d698ad5ec98dd"
        }
      ]
    }
  ]
}
