{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58007,
          "sha512": "88124c9785743453437c402994c06765bb3791e526b7cd9a8ad080d1c0494eb7f913591641752e6f0c50f2acfa7a221ed6453c5f9efab9ed5523e0a16c6bb840",
          "sha256": "c869bcd254af1312f8b38cd0f07ba00cb9afecb14f96063d6fe6d9e9544c0ab0",
          "sha1": "33f2cbb27d2888d57bb6acdf49482d4c9d9e7968",
          "md5": "3a9c0891382fd477dbe10d75a032522e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58007,
          "sha512": "88124c9785743453437c402994c06765bb3791e526b7cd9a8ad080d1c0494eb7f913591641752e6f0c50f2acfa7a221ed6453c5f9efab9ed5523e0a16c6bb840",
          "sha256": "c869bcd254af1312f8b38cd0f07ba00cb9afecb14f96063d6fe6d9e9544c0ab0",
          "sha1": "33f2cbb27d2888d57bb6acdf49482d4c9d9e7968",
          "md5": "3a9c0891382fd477dbe10d75a032522e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 145541,
          "sha512": "a2e8f0a65571dbb5c758e130c75915bded099668cb4a77c8e89e7952624c8c8d357c9364691aac95ce729492e4d2730c89f4ae5d1dabb730d7db1276dcc7db93",
          "sha256": "11c19443b5275ea575c3fdce327481bcda00013b1178377386d0ae31fcb9d5a5",
          "sha1": "d420c85c1074510ba294637cf8d21638ee7f8b8c",
          "md5": "88458c9ab7a54ecd66d43e1382e31bb1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21859,
          "sha512": "976a6f80a6d283db29bf9a7948d6e49fbc3588ab279e73dede7e0a59d8caf18995b271e110f19f7ace53649cb7eead1ebb6f5bdffc605d29ee54bc3334693f8b",
          "sha256": "3bbfa36a369d05c3b044842b06e57fed30d25f253c18ddce1f8ba3f13a152bcf",
          "sha1": "a1bde2b327bffb0216829ff514cd4903f2256b85",
          "md5": "87d0f647d6865f495b176fbe99559802"
        }
      ]
    }
  ]
}
