{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58261,
          "sha512": "376fae116787428534db284e8bdbcf9a40ca836d0538d705937651197b61afb6dd4d6a49bc5c040c71eb7b5a4588551030604dd53de20988c69e968671d02f09",
          "sha256": "c4d0e81c1f22e1317a6f63efa16079e2db3f6b847a714e22d8249932b6ac6630",
          "sha1": "2ffc5607a3493a7d330ac955fb4121b7ffbc84d9",
          "md5": "e2e7941413e4002d60385b2576485ac4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58261,
          "sha512": "376fae116787428534db284e8bdbcf9a40ca836d0538d705937651197b61afb6dd4d6a49bc5c040c71eb7b5a4588551030604dd53de20988c69e968671d02f09",
          "sha256": "c4d0e81c1f22e1317a6f63efa16079e2db3f6b847a714e22d8249932b6ac6630",
          "sha1": "2ffc5607a3493a7d330ac955fb4121b7ffbc84d9",
          "md5": "e2e7941413e4002d60385b2576485ac4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "69c8a42df0d0f605cf7a9b210c7c51cb2d513ecfaf0e2aef88221d2998d751ddd01b5f5c5a526a46636be5adbac6d3057824d547356388de9812dfbaeeb47d52",
          "sha256": "f4d0b53ef65a19fd5a01f86c83ee3ee475839f76a9b4f1748408bfcc2aba7193",
          "sha1": "4f616fbbea64bc60a41267735f0729deb2ef3cf3",
          "md5": "8e93379f4f19ccdf405c0da877f191d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22142,
          "sha512": "e75f10ba3f32fdd4f5ead32c41cfefc46f33de1d6d4b5ba2a7852bd6862f87e489e0478af099ce5e0d93094a05b812659e0aa27874e9504f45d1927d88b88fc6",
          "sha256": "45f1f2c761b6231c6559d2071e794510e0fcae57cf1bca71518625a151576af1",
          "sha1": "b364f4db72c9c0b977bc22a28068aba1874520bd",
          "md5": "c49b66cef72dbe58cba9b0f3a468b458"
        }
      ]
    }
  ]
}
