{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "a3a0984d96136a6b226d81c4200ecc592175d6e0117c938c3a2600f897fb7a1276276c35cbf66cc4182cb6daa104fbf463e421138114a4ac45ff6cffd6d96123",
          "sha256": "70fa694ab045cbdb0f8359f4047183f70bd2bc43ddbaf1eea121330e1fbf5860",
          "sha1": "ac9b80aa08bd7c9baf3d61b1bccfdd4758a9fbcf",
          "md5": "77f5d490bd88701f877d11eaeb50053b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58114,
          "sha512": "a3a0984d96136a6b226d81c4200ecc592175d6e0117c938c3a2600f897fb7a1276276c35cbf66cc4182cb6daa104fbf463e421138114a4ac45ff6cffd6d96123",
          "sha256": "70fa694ab045cbdb0f8359f4047183f70bd2bc43ddbaf1eea121330e1fbf5860",
          "sha1": "ac9b80aa08bd7c9baf3d61b1bccfdd4758a9fbcf",
          "md5": "77f5d490bd88701f877d11eaeb50053b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 157727,
          "sha512": "d3f346267743d98dfd1044e1eef215b908dc73d30c6bf6025f76cd0f0553b7309ddb76b4de6c29b6806b0e70ee05736addaae69d6a8bc3aa1c0bbbc70238fea5",
          "sha256": "2abe7da57ea5af096d2a261d09cd8be65ac824110427edc03bfed8babc80030a",
          "sha1": "808a6cf4c7551f08b3bc4618caabf6c8dcc88fbe",
          "md5": "03ef033b1b96546743381313c81970c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21852,
          "sha512": "9a0a05db3fdb83f8d7c8cfbc1bf9cc1b8acc4ba8f2c2111d55dc97768d2e7ee861700778bc0049a654989a0252ad551cdd2a3d9230acd4cdcc384aed135fdf08",
          "sha256": "cdfe82bc1f2de70368887d345bbc13dfb748c34b94525e395f3302c0c3b80ea6",
          "sha1": "868d0b6094970d8b2907058b8c36db78eb4bf64f",
          "md5": "9ef643d9ac4d4534a3b5528b50cb842d"
        }
      ]
    }
  ]
}
