{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58556,
          "sha512": "2b4a73961b196740adcf36851fd5eefb9d9b42ff7d9bb61752c835f784796452ea6f31c553ba900dbdade932185b8d42dea04b87cdd6629e07738c0638209d45",
          "sha256": "db959a9fd8e45333bf6f9df557655dc5bc6653497af7b3a8145a93bacd70c498",
          "sha1": "3deb8d92f37b2c54d1144153b269102f41c71ec0",
          "md5": "1ee106f51b8b4c809a6484cba4cf5667"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58556,
          "sha512": "2b4a73961b196740adcf36851fd5eefb9d9b42ff7d9bb61752c835f784796452ea6f31c553ba900dbdade932185b8d42dea04b87cdd6629e07738c0638209d45",
          "sha256": "db959a9fd8e45333bf6f9df557655dc5bc6653497af7b3a8145a93bacd70c498",
          "sha1": "3deb8d92f37b2c54d1144153b269102f41c71ec0",
          "md5": "1ee106f51b8b4c809a6484cba4cf5667"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 203571,
          "sha512": "62192b530b91c98a83119c7f2ed396475fc438bd3fbfb0d94ab9cbe62f0181ad147a687eb31d1b9a7c1c5da5770deb8d351ee3760ecbf0d1e25690606e0f90bf",
          "sha256": "23d97963d73a3ea8177f61371c34a34b693aade5c3c5bdaed578130778acedfa",
          "sha1": "3b700e737e069e2f965d24f9a56061e18998f875",
          "md5": "d588bc97f6678562a0e1aeabff3d0550"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 21917,
          "sha512": "b4ea1c7ba04358160f75d4624a792275d2095b06dc22d603496e0361f943060fd72d54363ff2caecb83526d40af55da75c13163fbd580ce7c50bda8198e35479",
          "sha256": "e0a3fb096a79beda31bd9ab21290a8fadbfd55531f3361e7f4c111fd71dee2d9",
          "sha1": "f01d40700bce0dc0837bce889e304ca8aa2ec190",
          "md5": "67423dee2f04f672e839abb3c1641612"
        }
      ]
    }
  ]
}
