{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-stick-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58317,
          "sha512": "0630d383f47cd02087340643a5a50e73c01d5c65b535960c31d1e040aed5b9d7583dd3bdcfaa1328e2ee1728420e3d020906a2318a0fded1b52f13eb0322705a",
          "sha256": "fcf0d9267e6d454d8269f15d86a709697d4e9037757a6961be27e0a406024afa",
          "sha1": "6766c3de0410335132ac5b4f49d48f6b5ee1a04c",
          "md5": "376b491ce00196d1a6391c2ecfeb17f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT.jar",
          "size": 58317,
          "sha512": "0630d383f47cd02087340643a5a50e73c01d5c65b535960c31d1e040aed5b9d7583dd3bdcfaa1328e2ee1728420e3d020906a2318a0fded1b52f13eb0322705a",
          "sha256": "fcf0d9267e6d454d8269f15d86a709697d4e9037757a6961be27e0a406024afa",
          "sha1": "6766c3de0410335132ac5b4f49d48f6b5ee1a04c",
          "md5": "376b491ce00196d1a6391c2ecfeb17f2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 155785,
          "sha512": "e1dc1bb446347c8fc5eeb2e528b6eb788d1a413c50370eb27a67999738da428c30c67f4307b23477882810bc315ec0b51c91757a46fc414c50cfa0fa34f9df7c",
          "sha256": "3c58197fedf5758df354ed20f04475a513828048ab7910d8be1779c4a455065a",
          "sha1": "850bfbd44b68caa4b7520bdf214cbecaf42ccca2",
          "md5": "f3a73ab488027cd5ea6f2b58992b3637"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-stick-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 22149,
          "sha512": "dc8edd7a65846aad4a95a3402da2bdc7d8384b21a27f915ae9a30b6834bb58a9b1cd53a1eba5a399c1e45673882dd84c7586ee96d5563a67cda63c67d5c16285",
          "sha256": "13595e3cb337d492406f112edf451139b03bced109f5c65614c7f88f31e85659",
          "sha1": "1f3baf57094070f44a7c2ed70b13c916a9c69b86",
          "md5": "89c3ff36616730ce79d6bc3cdd8cee86"
        }
      ]
    }
  ]
}
