{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "5.2.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.2.0-rc.1.jar",
          "url": "box-storage-api-5.2.0-rc.1.jar",
          "size": 22681,
          "sha512": "d1f495fb88d68a4c21f8df2eda5f849a4c62d1ebe668ab11d5d1867ba0c106c0743d423953f09dc6ad8b6449c5180ca0d1a17ce815f03758d233bf31bb4bbe02",
          "sha256": "ba2e5192fd2a8e3e04a1cf90983b03dbcb0aebc98ff26dd9f614bd78d676233b",
          "sha1": "ebac2c722806f675d016a96529937896663a2d65",
          "md5": "cb02059bc1c9800318c7164de02842cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.2.0-rc.1.jar",
          "url": "box-storage-api-5.2.0-rc.1.jar",
          "size": 22681,
          "sha512": "d1f495fb88d68a4c21f8df2eda5f849a4c62d1ebe668ab11d5d1867ba0c106c0743d423953f09dc6ad8b6449c5180ca0d1a17ce815f03758d233bf31bb4bbe02",
          "sha256": "ba2e5192fd2a8e3e04a1cf90983b03dbcb0aebc98ff26dd9f614bd78d676233b",
          "sha1": "ebac2c722806f675d016a96529937896663a2d65",
          "md5": "cb02059bc1c9800318c7164de02842cc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.2.0-rc.1-javadoc.jar",
          "url": "box-storage-api-5.2.0-rc.1-javadoc.jar",
          "size": 148305,
          "sha512": "7084d26ec39f4e71951ea3152113311f27c311c97423aae81c93eb8defcdd195dafa810c17102dcde25e56c9bc0cb43a6333c9cde9f84fc1ae36f9b5008c94f7",
          "sha256": "ddee4c1ced373a12bd9eb92bd6247615403f3986a46293c70b865bd050725166",
          "sha1": "0cdff27321eab3332ce7ebb906059f5946016af5",
          "md5": "d53b26eb2df754478ddb923e5378efe9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.2.0-rc.1-sources.jar",
          "url": "box-storage-api-5.2.0-rc.1-sources.jar",
          "size": 13105,
          "sha512": "b61b8658ac926ac5155cbe6890d5d6aeacd6835ae6e810d1f6056cdea087e44ab21f4f241fe75745a826458f024a80cb5a7a8d5d981a67c4e730720451d8f7fe",
          "sha256": "f4075a81a9705cf35e3874beceacd952c3ef68f0a9c2faa8ec19184da50bd156",
          "sha1": "57d40932202236fbe1749dbe6f13547750ef23a3",
          "md5": "26351e508eadafd90010ee9da8923c03"
        }
      ]
    }
  ]
}
