{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "5.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-5.3.1.jar",
          "url": "box-craft-feature-5.3.1.jar",
          "size": 64313,
          "sha512": "ad471be0ab42d566d0db9efc6b1413d3c5059c17404b5621b027ba2ca60ebe4f4e3b753d4c7b7b6a97c8d66b73facbea61c200610ab1abf535751869234186e3",
          "sha256": "e42e5feafbe1811473f58f2426c4bd5817df9ba3ea4aa14c019912fe9c562cc5",
          "sha1": "1c0bfbea5d6af79e83da7476ca973cf3f2cab217",
          "md5": "9320aa530964042ef3c90e3dde700b29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-5.3.1.jar",
          "url": "box-craft-feature-5.3.1.jar",
          "size": 64313,
          "sha512": "ad471be0ab42d566d0db9efc6b1413d3c5059c17404b5621b027ba2ca60ebe4f4e3b753d4c7b7b6a97c8d66b73facbea61c200610ab1abf535751869234186e3",
          "sha256": "e42e5feafbe1811473f58f2426c4bd5817df9ba3ea4aa14c019912fe9c562cc5",
          "sha1": "1c0bfbea5d6af79e83da7476ca973cf3f2cab217",
          "md5": "9320aa530964042ef3c90e3dde700b29"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-5.3.1-javadoc.jar",
          "url": "box-craft-feature-5.3.1-javadoc.jar",
          "size": 204771,
          "sha512": "fac8e55bf4fd95f0218903c840292544fac8081b19fbf613f3b97a0137d1ea1f30be063cf8e343f1897f20807262b7bde39e8e620f20c676aaca3e1499c7c1fb",
          "sha256": "98b2d1a55fafb6c9698075987bda29b1a6af16dfd4852acd5c35dc7a0b9bc325",
          "sha1": "425566c319957a9c3feeb3ca9fb213813625165c",
          "md5": "3cf09fe0949301691122b5c32571507d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-5.3.1-sources.jar",
          "url": "box-craft-feature-5.3.1-sources.jar",
          "size": 28808,
          "sha512": "c040208445074ce176da8269ea6c4ec026f60ab714d99f835f898fa5d9d3f32a6e3e48ce81732f21bed5d0171b57f1260d11cbd01ad8bc49f26e3a60e32cee18",
          "sha256": "f6bab02af16884029a7d7a606cdb8d8c6f260447586deb9bb09c8973bc4ceb15",
          "sha1": "18033cc0f6513bbd92457f7177e04315341a73c1",
          "md5": "94535d81f4b06af6b602afcec4cbc8f1"
        }
      ]
    }
  ]
}
