{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT.jar",
          "url": "box-api-6.0.0-SNAPSHOT.jar",
          "size": 91419,
          "sha512": "a4d837c32bbb50a6cb68851cbfd6196e2fec71c7b498c74236cbf9983050e5eec11c9ac347f229d4729b756748a2fad31b6afa69c64188d3838e941d47c6067c",
          "sha256": "400a0b458f52ac6825699fdbf3f8f680bef48f60fdc002fdc7a915e61dbd80ae",
          "sha1": "49f369c7655780e226ee22e8773ce619dc1901b0",
          "md5": "6a104114cc36dd197e9801a7eaffb7c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT.jar",
          "url": "box-api-6.0.0-SNAPSHOT.jar",
          "size": 91419,
          "sha512": "a4d837c32bbb50a6cb68851cbfd6196e2fec71c7b498c74236cbf9983050e5eec11c9ac347f229d4729b756748a2fad31b6afa69c64188d3838e941d47c6067c",
          "sha256": "400a0b458f52ac6825699fdbf3f8f680bef48f60fdc002fdc7a915e61dbd80ae",
          "sha1": "49f369c7655780e226ee22e8773ce619dc1901b0",
          "md5": "6a104114cc36dd197e9801a7eaffb7c6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 445129,
          "sha512": "09a9735923da06b7380c48b9dddd345c90b914c8c37f7f51aa703b0d240bf41db566d708bb3a99d137427336709e14843cca8f99697d5c1b67fd3b569e5a053a",
          "sha256": "45fd3227fa099148398e03c06838b7dab52c27d12503b001dfb771234816b705",
          "sha1": "e89f1658f240486563a719d5d2ba3d0a3057b3c4",
          "md5": "399269d089b719da6ea5c1b6b513cd44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 61006,
          "sha512": "d1cd6da1b1735f71892f9160585b1c8db0dd05681ba6d63cb5522b433a569722009bb6df2354b106645b5c74fdaa9f7a2ba562889dbd0579f55c4a6e26ec5ac1",
          "sha256": "0cfada24b10fa981bf5a7355b3f59690a2882c848b992b4fd19523140c983377",
          "sha1": "1e8b2424328e72c66fccfd36ed7ceebe81e7c1d6",
          "md5": "ce6d0407c5b9493e493cf473b0736bca"
        }
      ]
    }
  ]
}
