{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT.jar",
          "url": "box-api-6.0.0-SNAPSHOT.jar",
          "size": 84683,
          "sha512": "be3149e15fbd1527b7f8be1ed15c831ba466b7499c97231bef9ce31a4be3db64d83e0bc77525285f49f1b7261f954ed34c12c18bff41f36de16b8904982fe403",
          "sha256": "cb993a677eba3f26e7be83c1c2834f098290709ebba4062ca27cd3fedbd90a60",
          "sha1": "a01f931018476b13bc42a42da294b24eebd9e971",
          "md5": "7205f5d3d95ff423228dbf54b38e764b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT.jar",
          "url": "box-api-6.0.0-SNAPSHOT.jar",
          "size": 84683,
          "sha512": "be3149e15fbd1527b7f8be1ed15c831ba466b7499c97231bef9ce31a4be3db64d83e0bc77525285f49f1b7261f954ed34c12c18bff41f36de16b8904982fe403",
          "sha256": "cb993a677eba3f26e7be83c1c2834f098290709ebba4062ca27cd3fedbd90a60",
          "sha1": "a01f931018476b13bc42a42da294b24eebd9e971",
          "md5": "7205f5d3d95ff423228dbf54b38e764b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 406690,
          "sha512": "3bd1eb57e8aa1b9e0fd4be09e3934377485b9da8b6ca297cab975ea79653b5a5849db6ecf50c6c4bae6462b6e08e5d0fe38fe4979cf06060dcdd960df18a0cb0",
          "sha256": "94def9b183a3e2c9ca50110f16e519956430502108d1fb6c11ea5182aaa0c62e",
          "sha1": "4063c21f415834e60ddd17946e77ea4be5c589a2",
          "md5": "1159524f0731136e97addb7d372cb0d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 59525,
          "sha512": "8bd407f9e4151455e7e0dc7cebd36537e7f0390f48cbbf446b7c04152c5b388b5e806957969e9f924a94483c5617076928be2a59f2fece763782b770c65656c2",
          "sha256": "ef0c42f33602c6ebace76fe0851b419f760fa09a22adebd78aaf96642c795edf",
          "sha1": "71e2dd9447d7bfed3797c55a26e168cb9c6363ed",
          "md5": "bc00cc9978ffa135e47aa07b793ce586"
        }
      ]
    }
  ]
}
