{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-api",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT.jar",
          "url": "box-api-6.0.0-SNAPSHOT.jar",
          "size": 89637,
          "sha512": "70537c544a2af4d07a70642695060b22e78eb5c2154581f91af8ad74ad6a7860a6af3f77a716afb8668d20e59ff2e64b09fb46582b91b91db400c2499c1d1c53",
          "sha256": "beb9f7e5b5bf5949d42ae0ebfc90a908b62daf974fb00c72dcd7bd14e71dd033",
          "sha1": "a1b78625c7395549a22215fd1a8c9e6d24b0b6bd",
          "md5": "3876a824dbfb22622ec671b9e91b3a13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT.jar",
          "url": "box-api-6.0.0-SNAPSHOT.jar",
          "size": 89637,
          "sha512": "70537c544a2af4d07a70642695060b22e78eb5c2154581f91af8ad74ad6a7860a6af3f77a716afb8668d20e59ff2e64b09fb46582b91b91db400c2499c1d1c53",
          "sha256": "beb9f7e5b5bf5949d42ae0ebfc90a908b62daf974fb00c72dcd7bd14e71dd033",
          "sha1": "a1b78625c7395549a22215fd1a8c9e6d24b0b6bd",
          "md5": "3876a824dbfb22622ec671b9e91b3a13"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-api-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 418590,
          "sha512": "9e87ec6be7770fc135d3464371a410afeead99a1a737d6d05134e7a668abe67a8dc16f533f5abc00b3d1711dbed50502335ea4a2f6845ec80c58c1c9b55a2c5f",
          "sha256": "a21475bf8a21f3c203b003742b1f00d8dedc539a5a20a9efbda321176356b3dd",
          "sha1": "3f0e2ee43e8be9b83fc366649242577a79455831",
          "md5": "30965f58626263fd6eb613d4d89400d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-api-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-api-6.0.0-SNAPSHOT-sources.jar",
          "size": 60216,
          "sha512": "195e2b857971943b55faee0721178db4646fac8793662f2a3cd0c7c71469a473d46ca1f9364708d6a769ee2f56c616c48594bd330b11638f37b2f4f7a65cdd8c",
          "sha256": "e457470a80fdd26b0cc7164e5b949c4af46880508b1a3aea40f0d83652e1844f",
          "sha1": "516653c935f3632837da91c61113fda9625bb0a3",
          "md5": "189ebd33cf7bf3e6e0064d5d32745eb7"
        }
      ]
    }
  ]
}
