{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "bemode",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bemode-4.4.0.jar",
          "url": "bemode-4.4.0.jar",
          "size": 13646,
          "sha512": "20d56535bc56b1d5d77112b55f38a41c3a210ca655162759ee832521b15dfe4fd038932157fe34ad8d1832601ca67cd0f4521129d0cf9054f98234e09786d142",
          "sha256": "358adfa10c470788407513b6df5614d31bd7d0dcb1cc953cb2209a5522ef60b7",
          "sha1": "b3917ff3d42d2d4776105be753dcc2bfaaa4e84f",
          "md5": "e22c76b20149c9898d76ec1b93ee1c39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "bemode-4.4.0.jar",
          "url": "bemode-4.4.0.jar",
          "size": 13646,
          "sha512": "20d56535bc56b1d5d77112b55f38a41c3a210ca655162759ee832521b15dfe4fd038932157fe34ad8d1832601ca67cd0f4521129d0cf9054f98234e09786d142",
          "sha256": "358adfa10c470788407513b6df5614d31bd7d0dcb1cc953cb2209a5522ef60b7",
          "sha1": "b3917ff3d42d2d4776105be753dcc2bfaaa4e84f",
          "md5": "e22c76b20149c9898d76ec1b93ee1c39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bemode-4.4.0-javadoc.jar",
          "url": "bemode-4.4.0-javadoc.jar",
          "size": 139109,
          "sha512": "e4ba3bb6206ad8846f82151dcd953fc90701a47a0356bc8e4218e88b93eb414c32273c29fad3199ce62df7cfb819261dc35b04ad8a4a831e5479b404f64e7214",
          "sha256": "ec8880a519b0a5593299a3b87f56fdfb74d45a1202bb210a35b7e7d430ff6293",
          "sha1": "6bbca117826d0d39d8bb1f7ccb3e1b7137d2e128",
          "md5": "4ecb25735ce8998312ccb8f3c61d8a6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bemode-4.4.0-sources.jar",
          "url": "bemode-4.4.0-sources.jar",
          "size": 6679,
          "sha512": "6241e01addbdbf66010082787a2ddeb5078132ed3a4472463d97f05e639c783e0803865a5e54259d2f5263869ce85d9864f5b722a563f89c292ed8cea55327c1",
          "sha256": "0a9b49ac1f966df7f8c7b16250a46091d40c9c005408d44ffc8164fcd5520e2f",
          "sha1": "87bced0b97cf630a0e0d2398e32dcfaabfbe834b",
          "md5": "e6f6e752932be6d4928d8f5b76bdf9b8"
        }
      ]
    }
  ]
}
