{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-api",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.4.0.jar",
          "url": "box-storage-api-5.4.0.jar",
          "size": 30740,
          "sha512": "0c1f44d39bc220695c58c6863585a0f2a251e42c739a44a1920d5c75957cec1b27a42f4888108b4a51459d5721eaebf4def93612bb869bbcb44b930e1450a787",
          "sha256": "c8ebbe507898dc589d400bd382ace417fee7efbe0d1ff7d5b6eccc7fa29ffcdb",
          "sha1": "c09687dc9173d8b29e285962277035325ff8bacf",
          "md5": "73b30c115d826c7ca3f8c587cd1d2873"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-api-5.4.0.jar",
          "url": "box-storage-api-5.4.0.jar",
          "size": 30740,
          "sha512": "0c1f44d39bc220695c58c6863585a0f2a251e42c739a44a1920d5c75957cec1b27a42f4888108b4a51459d5721eaebf4def93612bb869bbcb44b930e1450a787",
          "sha256": "c8ebbe507898dc589d400bd382ace417fee7efbe0d1ff7d5b6eccc7fa29ffcdb",
          "sha1": "c09687dc9173d8b29e285962277035325ff8bacf",
          "md5": "73b30c115d826c7ca3f8c587cd1d2873"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.4.0-javadoc.jar",
          "url": "box-storage-api-5.4.0-javadoc.jar",
          "size": 171739,
          "sha512": "8184051f0bb03bd549b988d9c3228f8782672711f31d317773240c5ae0ef64874dae11665c6213251137f8dcbba20ba361c838b4f03b8905e7cbcdef7f73c5ad",
          "sha256": "dd200f8269259bd1a8e12bf4bd75b378848ba8c3bec1884766cea82f13d99019",
          "sha1": "48cffa82714c0b8527d62f82a83c51260e7437e8",
          "md5": "1050492c4aa39c9b9d53daaad1699650"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-api-5.4.0-sources.jar",
          "url": "box-storage-api-5.4.0-sources.jar",
          "size": 16176,
          "sha512": "b46416cfa688a2b9e6b4bdf6d3e5b3cae4531dcc551ab4d3d1eac1dd14a560576abc1204299df3729952b0e9d9c739daadab94afe9d5ff530b593464c8af840c",
          "sha256": "3ca85c5d8d76c6c11641b5361b3dd12ebcdbe937b04f5ddaaad998c32d89d0f7",
          "sha1": "7163134505cad02ac76de9e11fb579bce22e0825",
          "md5": "a5f420c6ac3ce7bee880fb038ffabda1"
        }
      ]
    }
  ]
}
