{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "5.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-5.4.1.jar",
          "url": "box-category-feature-5.4.1.jar",
          "size": 67801,
          "sha512": "17e1a5ebbda3be9c77b62741608b803b351fb801a8d6593cc6a3a8d9b17b87c261eb6a1569f7af9e02f3dc683207d39923c56562075ef8aa47f41083198b21c3",
          "sha256": "ba130e4d93f2d5525d80de9ad820bf620dcf4757b3c991ecd296081e7e5f3fe2",
          "sha1": "140a0f8a0f01fca29dfe7e0ead175b508ca4e140",
          "md5": "1214d062f8e829f71f4572992afd0ee8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-5.4.1.jar",
          "url": "box-category-feature-5.4.1.jar",
          "size": 67801,
          "sha512": "17e1a5ebbda3be9c77b62741608b803b351fb801a8d6593cc6a3a8d9b17b87c261eb6a1569f7af9e02f3dc683207d39923c56562075ef8aa47f41083198b21c3",
          "sha256": "ba130e4d93f2d5525d80de9ad820bf620dcf4757b3c991ecd296081e7e5f3fe2",
          "sha1": "140a0f8a0f01fca29dfe7e0ead175b508ca4e140",
          "md5": "1214d062f8e829f71f4572992afd0ee8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.4.1-javadoc.jar",
          "url": "box-category-feature-5.4.1-javadoc.jar",
          "size": 148066,
          "sha512": "7ff6de059916b5673350ecbb92bc9b4259270b40f1f6c98240c8c7e76ae6708d0169ac6ff3517ae0f8d993539c7f5fe97b6a3dac86b5a5a391166d8a0a271444",
          "sha256": "364b889ba204b33383941b2a2f64a081e9d7b125c064091db7e733b80074dd52",
          "sha1": "37b0b75abaa24d8529237d4a9751750a66a205ce",
          "md5": "ef63a99b06cbb466ccdc290ab03c1316"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.4.1-sources.jar",
          "url": "box-category-feature-5.4.1-sources.jar",
          "size": 50720,
          "sha512": "856f72effd0c8edccc588c3582693f4ef3e98010c121786fcd5d68124b58038737d3644490493acd1e2af85d44706cb3a3584e5dc1bc60cfd9f9406dd23847e4",
          "sha256": "d630ade3f6d346c7e90621186891f63737d6d8033574b0b1c4ccdf0d639b06ff",
          "sha1": "e10c852c0b0c71631356a3670252ec233693ff96",
          "md5": "c75fc1de3c785889c61c7b810f232c87"
        }
      ]
    }
  ]
}
