{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "5.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.3"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-5.3.0.jar",
          "url": "box-bundle-5.3.0.jar",
          "size": 15422,
          "sha512": "71775d822512be06a75ba2ddc67b5c35ca5744e5b5f76e2fdedd031a091933230c5cef47773cee5198a7b2600e47ebb7364c66fedddfbd90015746bca5902a3d",
          "sha256": "244b36812085f8d98b12237f6008cec5ac7817dea9388742876dcc65a4e6e232",
          "sha1": "18f0c5da6a7cdf7993fd3effc4f234035457958d",
          "md5": "47fdc91fb496735c7415b2c07eb89a54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.3"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-5.3.0.jar",
          "url": "box-bundle-5.3.0.jar",
          "size": 15422,
          "sha512": "71775d822512be06a75ba2ddc67b5c35ca5744e5b5f76e2fdedd031a091933230c5cef47773cee5198a7b2600e47ebb7364c66fedddfbd90015746bca5902a3d",
          "sha256": "244b36812085f8d98b12237f6008cec5ac7817dea9388742876dcc65a4e6e232",
          "sha1": "18f0c5da6a7cdf7993fd3effc4f234035457958d",
          "md5": "47fdc91fb496735c7415b2c07eb89a54"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.3.0-javadoc.jar",
          "url": "box-bundle-5.3.0-javadoc.jar",
          "size": 82246,
          "sha512": "912d74f92d00d44ba7d77f913bffd5caecdb19e7793e3668fd87fbd404a656eb05ddf6a7191fb82008aa316f68aa86007a6d1289c7bcb64c39d89924213dded7",
          "sha256": "1aa122729dcd397d104ea27d2a9179ac5abbb9ef25ae044fb49caaf7a64b156d",
          "sha1": "dfaf78ee4ae6db94cde5b155856a7dd509ff7719",
          "md5": "7fb69601dede6420701384643891c79f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.3.0-sources.jar",
          "url": "box-bundle-5.3.0-sources.jar",
          "size": 12564,
          "sha512": "ce9400277b8cd053c514623ad4459b85df04529821e2bf6a84de1c58f1de7305e227cdda9ae798fcbec536d25921fb3add9d9d92c0471461ea6208391dbe7d26",
          "sha256": "ed02f40b51f160118eb91b048df637749733ba5255b61eb06e0ed49fa9dd25d8",
          "sha1": "a57d94ea9446b12bb6097cbf2c4226520543e445",
          "md5": "da0b7c16e809f64bb66d90020710bd20"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.3.0-all.jar",
          "url": "box-bundle-5.3.0-all.jar",
          "size": 876049,
          "sha512": "39932a7faee05887a22679b92514bed66c46766e5b92ae66a427f7f9375e8efaae08ef75361be5d7efecaba873e0a008b5539d7bb8e3da61774da42f725dcfe5",
          "sha256": "86beae6063dd1a87e6bb0a0aeabc0eb6eb5db50177183674c9932477fa37ae2e",
          "sha1": "b7fcd9d0cacf92a09c172418c2d1e80f08b0f3b3",
          "md5": "6137d3c88ddbeb48ec3eeb3a9b1ba6e7"
        }
      ]
    }
  ]
}
