{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-5.4.0.jar",
          "url": "box-gui-feature-5.4.0.jar",
          "size": 78920,
          "sha512": "baaf956d69f22e25865ccc571766260a965966f73a9794334c4b06c4af87554ae198b8d2b098283a39ec3e504ee24917fc67855acd013cb951ee6852cab8e0d4",
          "sha256": "be1c129b3be3f5950d64727b10dcbecaf30ce515f8cec6c57576c12901d8683f",
          "sha1": "022132742ceedbaba02c09e255358a53b85d4914",
          "md5": "39a3fee961ce1d56d0aea2eca125b4de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-5.4.0.jar",
          "url": "box-gui-feature-5.4.0.jar",
          "size": 78920,
          "sha512": "baaf956d69f22e25865ccc571766260a965966f73a9794334c4b06c4af87554ae198b8d2b098283a39ec3e504ee24917fc67855acd013cb951ee6852cab8e0d4",
          "sha256": "be1c129b3be3f5950d64727b10dcbecaf30ce515f8cec6c57576c12901d8683f",
          "sha1": "022132742ceedbaba02c09e255358a53b85d4914",
          "md5": "39a3fee961ce1d56d0aea2eca125b4de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-5.4.0-javadoc.jar",
          "url": "box-gui-feature-5.4.0-javadoc.jar",
          "size": 274072,
          "sha512": "f86dd2a7ae6db5c7a9e107604b67ffd9c16a0a1d1d8d9a53688a3ee4d18981a3ff8c46b738aece6a0b332c357ff603e5acc5c783ac641b6fd5acb9faaa390164",
          "sha256": "26fc9b4d21de32177a34db2c50866d9e4bea75edb707fda6968e846c582c7ea0",
          "sha1": "924725bae679c94a98cfebc89a771d78466c9cb5",
          "md5": "1302119f1c19b7e9625a9a41c76878c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-5.4.0-sources.jar",
          "url": "box-gui-feature-5.4.0-sources.jar",
          "size": 36787,
          "sha512": "693b6b920fbea651c7b1f10eec8c81c6ecd6d44c38cab5d97262ffda55207906838ee403ab2db5de76b7efda0d3ac4f2dffc29e790c85400da945cc0f952da99",
          "sha256": "66781b85be20f2cda2045405ff584772eedf930b1b23e9e3385408a292ad8699",
          "sha1": "02cfcf4e0cbeee1a54828233984caaaa0e7f5fcf",
          "md5": "9f8f0dd7c81904c6cf7a08df1dd9aed3"
        }
      ]
    }
  ]
}
