{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "5.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-5.5.0.jar",
          "url": "box-autostore-feature-5.5.0.jar",
          "size": 54336,
          "sha512": "3a6840b8da90771576cc417dceeb7428763c02070cd957f4f4cea1b0215e4ef0d5e10880f5956d7bf22ceca5cbd3eb041e1235fc2b5c59c0462333fcc02d0698",
          "sha256": "79562997c6ec77349c03ea0e1ea28bf56e8edcede891d3bb9e012bf330414163",
          "sha1": "36ca38c8efa0f641b3e911598a28ee29b49c7630",
          "md5": "cd937671b67cac9f22834df434075a61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-5.5.0.jar",
          "url": "box-autostore-feature-5.5.0.jar",
          "size": 54336,
          "sha512": "3a6840b8da90771576cc417dceeb7428763c02070cd957f4f4cea1b0215e4ef0d5e10880f5956d7bf22ceca5cbd3eb041e1235fc2b5c59c0462333fcc02d0698",
          "sha256": "79562997c6ec77349c03ea0e1ea28bf56e8edcede891d3bb9e012bf330414163",
          "sha1": "36ca38c8efa0f641b3e911598a28ee29b49c7630",
          "md5": "cd937671b67cac9f22834df434075a61"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-5.5.0-javadoc.jar",
          "url": "box-autostore-feature-5.5.0-javadoc.jar",
          "size": 170936,
          "sha512": "7952492316d07786f9535168aa764b94ac29ee22337b25b4b8fe0a7450378d0f42897ec3e98d014eb97fcb4adf9c6b57ce835fa252d6addd2ddb8e51cc1b4a59",
          "sha256": "4e3d6863720bef5454832426c183571de68ba38df39358802167ed1352befb92",
          "sha1": "2a56212ca80c3cb403cc087783f94dcd912823cb",
          "md5": "77b9056c5255b3a89f62f37fe449ce89"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-5.5.0-sources.jar",
          "url": "box-autostore-feature-5.5.0-sources.jar",
          "size": 27086,
          "sha512": "5b8a8ed9014ee713a61b6e71f4672f55d1ccc1822e82cf27ecda4c74557fadb98783499148631702bdd413468d37c9f7c8a4252cd548086d955753961fa5453b",
          "sha256": "3d295b67ea159d71edca88e0b006e9fb0ee2b0326ba1fadb510c43092a97b7bb",
          "sha1": "37bcbbf23721699045295d6f3289587428518eea",
          "md5": "82684c0b46278185c94a178467093228"
        }
      ]
    }
  ]
}
