{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-category-feature",
    "version": "5.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-5.5.0.jar",
          "url": "box-category-feature-5.5.0.jar",
          "size": 68015,
          "sha512": "4363841fdaf0b219464a2f24b9f74ca7dc6a55186df55d59b84e19b188f335493af3b4f611ddfc2b46299bb3e0c922cdbe40f24b6175e5a00b18f766882db3cd",
          "sha256": "8c442b579390571a668916f69e1e9ee0342fb8ced7335d7397bd21ea2e489298",
          "sha1": "3541a8e38fe416826464b2b4b249c0656e17d2ec",
          "md5": "c1d6a098286c9e32193f26fee19dfcff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-category-feature-5.5.0.jar",
          "url": "box-category-feature-5.5.0.jar",
          "size": 68015,
          "sha512": "4363841fdaf0b219464a2f24b9f74ca7dc6a55186df55d59b84e19b188f335493af3b4f611ddfc2b46299bb3e0c922cdbe40f24b6175e5a00b18f766882db3cd",
          "sha256": "8c442b579390571a668916f69e1e9ee0342fb8ced7335d7397bd21ea2e489298",
          "sha1": "3541a8e38fe416826464b2b4b249c0656e17d2ec",
          "md5": "c1d6a098286c9e32193f26fee19dfcff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.5.0-javadoc.jar",
          "url": "box-category-feature-5.5.0-javadoc.jar",
          "size": 148423,
          "sha512": "5085eae5bf398ddfdda315983ddb1442fc008b765f1cfee8c1ce9dbd68207836b24f6387a72640f3871ccc0030f33047ebf9a5b51631d3908722e953d4319af5",
          "sha256": "a5f983f800c111540e85ed8fb5d9d62956361e2163f745f859359207c4a34900",
          "sha1": "ade38f3d4b5f5ffbe6396593832da7c3381d6a20",
          "md5": "00867c2b9cd3ebb56128c75dad35df49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-category-feature-5.5.0-sources.jar",
          "url": "box-category-feature-5.5.0-sources.jar",
          "size": 50849,
          "sha512": "870fb06f4bc9944f62334869f514ce97d663410b0792ace7695962234c5e8ad25acab23a9f1d67b54b3e7068c07a7890b4f89fe9dc22ac541958439af0fd3751",
          "sha256": "e18fee0b5669a11e9e5781aa7035eb96b70f051c164a6b3cc04b086471aba7f9",
          "sha1": "bf0c9e0238521673511ea27f4339c6d7071f28e7",
          "md5": "88c68122105b493fde92adf93061f7d9"
        }
      ]
    }
  ]
}
