{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-api",
    "version": "5.0.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "box-api-5.0.0-rc.1.jar",
          "url": "box-api-5.0.0-rc.1.jar",
          "size": 59117,
          "sha512": "93e3bf8f7a1322de428f91e4327e828886a315f26fb86a2b0dd53a838e31f5dd67d9235ffb36660ce9b89f4455a2b624a49e20129afce4af7effdc345249dfb0",
          "sha256": "2f3af0ac8a9444bb68c290d270d00c07ec28e7800f8a4c3ed5cf520d14de1a13",
          "sha1": "3204fa9bfd8bed300d186679a95a0e64759545db",
          "md5": "b6715a4f95e5ad40c041c4e6f0ad6b79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-api-5.0.0-rc.1.jar",
          "url": "box-api-5.0.0-rc.1.jar",
          "size": 59117,
          "sha512": "93e3bf8f7a1322de428f91e4327e828886a315f26fb86a2b0dd53a838e31f5dd67d9235ffb36660ce9b89f4455a2b624a49e20129afce4af7effdc345249dfb0",
          "sha256": "2f3af0ac8a9444bb68c290d270d00c07ec28e7800f8a4c3ed5cf520d14de1a13",
          "sha1": "3204fa9bfd8bed300d186679a95a0e64759545db",
          "md5": "b6715a4f95e5ad40c041c4e6f0ad6b79"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-api-5.0.0-rc.1-javadoc.jar",
          "url": "box-api-5.0.0-rc.1-javadoc.jar",
          "size": 374785,
          "sha512": "25c163d3469aae65a6afebfbd45683aa66b9aba42f77f62f90996995b9ab1041ab6ee823ba04c69ae28d7d6a77ebcf046a4f0a429805102204e8ed9b34a7c7eb",
          "sha256": "c4cc87501457d9ed4ec857a0e8c9ce844d5bd1bc5f5d1cb250ce3159d33e035c",
          "sha1": "8a0262b132bf807a7aa1029ee5772fed163e86b4",
          "md5": "e636519def27978b8f6f9c049acf4545"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-api-5.0.0-rc.1-sources.jar",
          "url": "box-api-5.0.0-rc.1-sources.jar",
          "size": 47441,
          "sha512": "d7b310e82aab82f8eb2c0d91614b1be35fb964019fe378cb38b230df697b94528b72ffc64baae1cef7102db8a88e693e49af63f377bff1231a57370cbca3758a",
          "sha256": "7dd5db7cb955149e71ffd18f54663a91074a0f40885b730fcf6972e32ccd7e1e",
          "sha1": "630fed3c2b741f33b07fd1ab5725d61698f47711",
          "md5": "9ca3fa244825427f0454c35c702d8e71"
        }
      ]
    }
  ]
}
