{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 57634,
          "sha512": "1fcb5f65fd5d940b8ff72573f7f54eaf509d5f4253ccfd4a8bc15ad4b3debb8de9730493a37923681347101ff39a99423c00b2232bbf185a43df1c750ae74ee1",
          "sha256": "7ece0a8f1ac57af75947d7d7e38f196a69aa78f1332ee3fb11c688e547d97e38",
          "sha1": "baa75138f45fd6c0a770cab169f6e7e8962ec3ea",
          "md5": "b4e496bc612c6f93592a5d78911ad4af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 57634,
          "sha512": "1fcb5f65fd5d940b8ff72573f7f54eaf509d5f4253ccfd4a8bc15ad4b3debb8de9730493a37923681347101ff39a99423c00b2232bbf185a43df1c750ae74ee1",
          "sha256": "7ece0a8f1ac57af75947d7d7e38f196a69aa78f1332ee3fb11c688e547d97e38",
          "sha1": "baa75138f45fd6c0a770cab169f6e7e8962ec3ea",
          "md5": "b4e496bc612c6f93592a5d78911ad4af"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 169315,
          "sha512": "146db29900b8e3d9d2ad15450b1204227b543c680084a53f402ad45554e7e97c84e95e0c71625f9d74ea5608c750bdc90aa9d39d7cb26f02a629fdf9e87ad7be",
          "sha256": "edf1f5af646eb93543e5283a1e082ba47dc79b6501e3051440072b3165cacbf0",
          "sha1": "e4440c97caa1a988c20a5b32f7d284b973cdd914",
          "md5": "3bba4219604830f87ac82d80fb73c91d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27486,
          "sha512": "4f39bfe089f1d3f846f8297850fc85f0e35f33778c746577d1856d9d8f6ecd373c1a3db16cdee1f2996c86e13da1bc41b0278405f8b086ada38b43a619f6080b",
          "sha256": "0983659c8eaec57176486a7bd9b7ee7a4e2e688022688582ab15ac22ec57363c",
          "sha1": "366922b93793f2d2c1ac7ddd7e0a7f5afcde4b63",
          "md5": "c8aa10b8ea85ec6a2578bd3d548126e5"
        }
      ]
    }
  ]
}
