{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 53019,
          "sha512": "a4d581dea1c0e739561214dfeb4e1a63cda5a8779fc535645371eb0d5f37aa715d852326454b86bdfe72d89d36031ba8d9d81f36ba62d0f903780e6fa40db6af",
          "sha256": "dbf4e60df02eba25bfca2bf21777e5d712132ea9686705e4c6cbaeb1f6099b85",
          "sha1": "b37e1e1a85056378d18eb041eaae56b72ffdbcec",
          "md5": "46a96feb1f2cbf4f4c9eca8e451d0d8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 53019,
          "sha512": "a4d581dea1c0e739561214dfeb4e1a63cda5a8779fc535645371eb0d5f37aa715d852326454b86bdfe72d89d36031ba8d9d81f36ba62d0f903780e6fa40db6af",
          "sha256": "dbf4e60df02eba25bfca2bf21777e5d712132ea9686705e4c6cbaeb1f6099b85",
          "sha1": "b37e1e1a85056378d18eb041eaae56b72ffdbcec",
          "md5": "46a96feb1f2cbf4f4c9eca8e451d0d8f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "8fb003bf0da09bb3705d8aac4b0bb756d48c69adaf4ee00105580d6c9a010cbbfdc1cde7adeb07ef6ac468f2114e4e221ca3b04c3392d63feb8de5c6fd512814",
          "sha256": "069e333cdf53cf98c0517c7f60cb8186a1eaf0f3fa461d478f0cae48705bdc33",
          "sha1": "f01263b298426e57aa2801a4cbc52cd0bf06f72a",
          "md5": "49af217a4d8912ca7b680a819e9b71ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26618,
          "sha512": "444d201fc58dc3a7d426d937ef41e9a226252ee435f27ae278c9869cd17ec41f3f1f24219f81e68d45c8bf92b1a3a193c3d42c157b8fe74feae46e43f1206e73",
          "sha256": "925a4bc31fa4b8434202871bc931b599cc2d6b50835b139a2e8f4a4fac11b218",
          "sha1": "634785a4ea8cf8979717c8d42c97a73cc33f1435",
          "md5": "7edb91eb77c5abedbf3e0d830421112a"
        }
      ]
    }
  ]
}
