{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52664,
          "sha512": "a52bf2cc6236eb8d38c2e7bd29dc1964034a619b481bc141c5acc1090f21f61ab156f1219f1e0d4234ce9612f59c8a012d4e44a53f19df3082ef1a42d21380f5",
          "sha256": "8ca8320657ae29b2312b08d00eba379f8341e1346d494d08a47e289cc98c43de",
          "sha1": "55c31d0439939a5a04df07b906cd2d8716c2f7f9",
          "md5": "1ab34d8f9312c90e3b275d99c0e07fa7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52664,
          "sha512": "a52bf2cc6236eb8d38c2e7bd29dc1964034a619b481bc141c5acc1090f21f61ab156f1219f1e0d4234ce9612f59c8a012d4e44a53f19df3082ef1a42d21380f5",
          "sha256": "8ca8320657ae29b2312b08d00eba379f8341e1346d494d08a47e289cc98c43de",
          "sha1": "55c31d0439939a5a04df07b906cd2d8716c2f7f9",
          "md5": "1ab34d8f9312c90e3b275d99c0e07fa7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "b30615cc31662c1cb9faa09971b7f44c9a06e0ed250f3643f952c20bf9aa3c002d5e3eb65730d2407648c6c29c897cd618a16212d50c5cb917b54b41a867ac38",
          "sha256": "53fca47c918ef0304951ca51d8e1a60ee25ff56ed1558f79e118997d25e27094",
          "sha1": "708ffed50b5491d43b96987628a0b274b8735e4d",
          "md5": "b269fd4066e1ccc5fc78d767de127299"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26634,
          "sha512": "4f8c55f11363289399b16a075727b39b67d35f5e268f36f3372be6a61ed85916006116605032a402c251dc7f7019bd7e84b1b1d707e5a42dd66753b9ff383557",
          "sha256": "024bf53028409be5a5a236909cc2d80aa32c480410f739f0215671cf5bf1a968",
          "sha1": "d186a143cbf93d5434db6ce08c017ae9ed591685",
          "md5": "fea1550c91beb7da0721fe2a8c95cd89"
        }
      ]
    }
  ]
}
