{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "a1bccc71adedcb440ebda2628103ef006814538f1828c5daf265de2b57031f5fa9fd38d8804a808c37ce93c1eec135400c4485d808a507405755eeb5cb0afb0d",
          "sha256": "814370b2afd035363f2e16221cbb464ae87c40eb22fb611e7213a8a46741481d",
          "sha1": "201bf128963742e1c784a7b3c0c8836931b27e19",
          "md5": "8d714476eaf2f7ff76eafedaebe5d38a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "a1bccc71adedcb440ebda2628103ef006814538f1828c5daf265de2b57031f5fa9fd38d8804a808c37ce93c1eec135400c4485d808a507405755eeb5cb0afb0d",
          "sha256": "814370b2afd035363f2e16221cbb464ae87c40eb22fb611e7213a8a46741481d",
          "sha1": "201bf128963742e1c784a7b3c0c8836931b27e19",
          "md5": "8d714476eaf2f7ff76eafedaebe5d38a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 99265,
          "sha512": "251e52103f15b0a4da7f8105b0154d6c2dbaf2fe52cbbde486ff8830f3eabb7110e87b6c1c138bed7926d37d1e9e09da6bb2384027b7d8c612b8446f8d521457",
          "sha256": "f033ca444b6676392d2a916f3afa25b508286e1b46eba12c578de153e45e5935",
          "sha1": "7adf64a515cca7b43e7c534762af8f6eb35e2930",
          "md5": "5c909b5b81e501b71c6a222ff9b7ee3f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26441,
          "sha512": "82da00816686104124d95bdd0273b8069c2bad030569931f1df52e986d98a3d64c94e95420aca3690b50ae42e8d40954af287ba732a40a1683c4d8ac6fc42a5d",
          "sha256": "d85081943d411acac7b1ad0ff2fb40d9da27325359bf9915a53ea6d7c0612afa",
          "sha1": "2a8b1519b61c40592f1646990881c1e228b8200b",
          "md5": "5550b5a09083e876e623796b37ceab64"
        }
      ]
    }
  ]
}
