{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "9c5791b32f555ca9de67af1f17e0d1ef5f4f98087996f431b5f979988797cbe9f46e67af40d3f71004f77e2efcc6b9558b29e9d58a58fadee614578ce1b5439a",
          "sha256": "7432c92b5e831a42d743cce34a77f664fd1db41a4d64d660a194b119d9cab566",
          "sha1": "7648a02bea6b3f7c13b6e28b6c633d7290955e8c",
          "md5": "b8331e55d395faace7e00710f3644c48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "9c5791b32f555ca9de67af1f17e0d1ef5f4f98087996f431b5f979988797cbe9f46e67af40d3f71004f77e2efcc6b9558b29e9d58a58fadee614578ce1b5439a",
          "sha256": "7432c92b5e831a42d743cce34a77f664fd1db41a4d64d660a194b119d9cab566",
          "sha1": "7648a02bea6b3f7c13b6e28b6c633d7290955e8c",
          "md5": "b8331e55d395faace7e00710f3644c48"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110786,
          "sha512": "34c440f0381facb2df6f5c853c59c6ca421dadf0f5d3a0377edd87ac6c1d64a432cd721e2633c029a5b856bcda4e9f8a7fea86a14f3c27eac007966c712b1417",
          "sha256": "ca782272185232a78498bdbe71195d2c4fae3183551119eebf83214768eb49b9",
          "sha1": "2d4c529733b233c4c9fd12b2a297c772ccf8e3fd",
          "md5": "b5694ef411ee563eaf997ebb64eef7f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26459,
          "sha512": "e57f299dfa44098118038e7f4fc7b59a06b9df3b147e5fa82addd44fda807f1004189e3f5431cba565581ba0b7d909cad92e85d1c1c3c74c5bd83463d1168d38",
          "sha256": "e3d130088f4e1b2b444b982b4526fb6014d4bf3032c680343af44de098b72784",
          "sha1": "3fb9279beb4459d24ced32ef3b922fa814376c25",
          "md5": "a737a42943a26b21fdf97f73cf7bbc5d"
        }
      ]
    }
  ]
}
