{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51849,
          "sha512": "78f4ffb9605577fee2cc8e935b5dc74c86caf40c070f1040fecdeea32300b6f554dd9c08b717a070b5f1dd71c8ccaeafbf5ed6acbc5a8050e5a3025642b986fe",
          "sha256": "ed65b23d44ba6c70f459d9175584a6e2ea42bcadcb23b5da3303ce11ffae6717",
          "sha1": "b6eb511f78792f54b1402a5aec32e9d7105e3172",
          "md5": "2634514141abc5d7e9a639fe16a27bbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51849,
          "sha512": "78f4ffb9605577fee2cc8e935b5dc74c86caf40c070f1040fecdeea32300b6f554dd9c08b717a070b5f1dd71c8ccaeafbf5ed6acbc5a8050e5a3025642b986fe",
          "sha256": "ed65b23d44ba6c70f459d9175584a6e2ea42bcadcb23b5da3303ce11ffae6717",
          "sha1": "b6eb511f78792f54b1402a5aec32e9d7105e3172",
          "md5": "2634514141abc5d7e9a639fe16a27bbb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 99265,
          "sha512": "87e42019f4c38587f05d3808e11472d427e86ade7c0ffa8ce5faf7c93d9a616bfea40cca3ce75162b08655c7e6a53729af5472903960cd487e95ff6a3021c900",
          "sha256": "a65af0b056266d8472055a13ba044dc8d8a56a3db0e3a75b1eac4be94cf2015e",
          "sha1": "8da82e342780604fb2dcadfcb125c5951624199e",
          "md5": "161b658f8e1f242e8ecaa46d786dcad2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26413,
          "sha512": "93228c2364b4ce951ce54f9565edf18ccd1aef84cef69751007b4e91aa0cc6858bf70045ba18e4263b0c751d5e4abc0fd3bab1e962149a73f39fcb19c80e034e",
          "sha256": "d9e32503a4b76aaf54fbadde7a02fd67a84779f6b94fe7c76a81cac2dc43f976",
          "sha1": "c5acd85c5fbc21fe5a9bc14df24a5d6428ad18d8",
          "md5": "6926e7ad4804c8d87722a8e711b2a98f"
        }
      ]
    }
  ]
}
