{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51940,
          "sha512": "5f99953447b83f6490fd774fcdd2188d5db648d4fca1d40954ca824947636367498804de1bb6ee225c1a0c3a9dbb184802ea54e68c089e3abd61f36222b3295d",
          "sha256": "7b67b8a2571c70d65e9c826414bc0250a46fc26f608a19808f02b26dcb378b1a",
          "sha1": "c9f4e444cd65d438dc5f0aadbf636181246fa43d",
          "md5": "279b072b6296280195cd3a8a2e4db121"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51940,
          "sha512": "5f99953447b83f6490fd774fcdd2188d5db648d4fca1d40954ca824947636367498804de1bb6ee225c1a0c3a9dbb184802ea54e68c089e3abd61f36222b3295d",
          "sha256": "7b67b8a2571c70d65e9c826414bc0250a46fc26f608a19808f02b26dcb378b1a",
          "sha1": "c9f4e444cd65d438dc5f0aadbf636181246fa43d",
          "md5": "279b072b6296280195cd3a8a2e4db121"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110782,
          "sha512": "cb0365d8701f9b07b3838a738b0059c11dd5d32ece7f64c0c3ed16fe037a6494e89bd6285972b6f7400c49e63faf741a10bf075a6112503ef7ff189805b9d8b6",
          "sha256": "c3a424146373c743e1fecddca78200d9eaafe4aac4c4ba5538f363c040411bc1",
          "sha1": "b92b3c4769ac2a8eaccdc6bb98469086770be59e",
          "md5": "4da95f489260c82f1ea04f974ae7281b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26413,
          "sha512": "cee7e18e8ac1eecc8313810a1591ea15132b6545c4b00b5795d873cbd7b110901e4f0089304fa703d31455b080173a6704c333f7e96066ab375c595f9fd3dd69",
          "sha256": "c0411a31ea20bb1542de460030e8186bb448e05ebfa74b0f422900ee2a85117c",
          "sha1": "2b0b721f9c784cc0c0a48baa0d6596af142fdef9",
          "md5": "ae99762f118310063c6e792a06b13bb1"
        }
      ]
    }
  ]
}
