{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "5d9bb39729a4e77e3a909f81c5d11b5ec579c97203be94cb6e15e5216415aa45eb4efac12ffec643b11c10a3a678f780e748f6a2706516dc9ecd8f3412bb0450",
          "sha256": "e82cb730de31590a968888dfae2cfb06ee62e33f9113cf433ce7e329bc362cf7",
          "sha1": "7483c7c3bb7f958b7771aafe147cc1a693b9085c",
          "md5": "cbeeff0b1905cc62b982b07db3cefc85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "5d9bb39729a4e77e3a909f81c5d11b5ec579c97203be94cb6e15e5216415aa45eb4efac12ffec643b11c10a3a678f780e748f6a2706516dc9ecd8f3412bb0450",
          "sha256": "e82cb730de31590a968888dfae2cfb06ee62e33f9113cf433ce7e329bc362cf7",
          "sha1": "7483c7c3bb7f958b7771aafe147cc1a693b9085c",
          "md5": "cbeeff0b1905cc62b982b07db3cefc85"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110786,
          "sha512": "30ac80803412b25a715861ac6731418bb0cb34aee1a3dd26968d5fe1294b584cfce03780192c894780473eb0566a82c63bdc498d1cfd278de4b2088b362d326b",
          "sha256": "b1e0dac94b0d619f01cf56832dba7eb828d454a99a101c74685f7fe71f0d26d2",
          "sha1": "dd5aafc604bbc36cb26596ba54355a9078c3d29c",
          "md5": "d7917b4af6c6574737aa56e842a9cea4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26459,
          "sha512": "67309ec7cce3418e2571d6bd01c165ee020ff9c0faf0c1cb61fa679a7f50df44cba0b26da7ab6488af7671e6bc6165a225ba2a3e8547ac2ce9be785e140e5a77",
          "sha256": "97537f03afb700188fcca95b5e59af965322c01e6c7eb2040f33b6341b928926",
          "sha1": "8532612f45eada7fa8e47b409d43da1ab359c740",
          "md5": "146c49e7303237f961a6cf83ea2e0539"
        }
      ]
    }
  ]
}
