{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51849,
          "sha512": "abf62a66f165f2782ae40024d742fae1805583a57f436176f78c631232c22d1d66595d99615b504731fc7c18ab32940c643c9f65bfa37c3273f4ba928a3ec19d",
          "sha256": "3a8b8be27e91f4be1402d8b6638c2708877df106f5a46afdb3cfff0f2c65a71d",
          "sha1": "f825f87fd3512ea57aee841df8388bbce2ae21ea",
          "md5": "69eebbd450cdb16b9c8acfcda19130b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51849,
          "sha512": "abf62a66f165f2782ae40024d742fae1805583a57f436176f78c631232c22d1d66595d99615b504731fc7c18ab32940c643c9f65bfa37c3273f4ba928a3ec19d",
          "sha256": "3a8b8be27e91f4be1402d8b6638c2708877df106f5a46afdb3cfff0f2c65a71d",
          "sha1": "f825f87fd3512ea57aee841df8388bbce2ae21ea",
          "md5": "69eebbd450cdb16b9c8acfcda19130b6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 99265,
          "sha512": "f4a744088fcc1a682f0cf23436a2ccd9b012c1d043db9a8f2fe2242b159357758c080f8277a5d4ea9d88383e2224e9657e9650e93485bf9d2226ca5c04b74feb",
          "sha256": "06fcc6769f882235458ad7b31246c72f2053ac143b64c56adf3dfeea4e757ef7",
          "sha1": "06a8de3f6efcc12c9d37330bf1cce0fc413cbca2",
          "md5": "2a0b6504f0c67de36a0433ecd477a095"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26413,
          "sha512": "2ee4aad5e3001de12b65428f1b8fa640283d58d783c2034df3de09337969c309a04f9583891087fde19fce9685604bc82bbd2205ab057396f9afeb340001c57a",
          "sha256": "7161a1a64659cf5adf736cdab6558da4dae183d0a962d4143a1ab5b603222fe9",
          "sha1": "e74c39f215a781b9a490f55c2ce57ca71eaa78eb",
          "md5": "7da2776048b3f9ad551a606cd4f3a274"
        }
      ]
    }
  ]
}
