{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "3ea728e12ef69d2141ddb98d568fe137b35a3d3e641d93ad498ff079862c8a3634dd34d6a3a663f985a85e264dfec0fb845e9f3fd3d6206f31e1c0143cf2329a",
          "sha256": "d1e0499653b05eb4dc9276148a79e42a520950832e44e8ad2b61270bd29f45e0",
          "sha1": "6df1da9b01b017f453f09bf46ecfaf633fffaec1",
          "md5": "d532554f18c91cf194c6a9e0e7e3c484"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "3ea728e12ef69d2141ddb98d568fe137b35a3d3e641d93ad498ff079862c8a3634dd34d6a3a663f985a85e264dfec0fb845e9f3fd3d6206f31e1c0143cf2329a",
          "sha256": "d1e0499653b05eb4dc9276148a79e42a520950832e44e8ad2b61270bd29f45e0",
          "sha1": "6df1da9b01b017f453f09bf46ecfaf633fffaec1",
          "md5": "d532554f18c91cf194c6a9e0e7e3c484"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110786,
          "sha512": "accb7d0fe9d253f1623be61829a75cf8a849a25a45e1a425ef51be22df8f7a2c55afee5e08e3bcb899e9a65a0968e6ffc0e4f38147be8a55102c8e27593d972a",
          "sha256": "ef238699e190913907b9c485f8fc62cffc651302b0db81b67b5d4f2f6c0d1b6c",
          "sha1": "c4fe440adb6239b22515f048f758aea040e3e96c",
          "md5": "f1ce5b5a3911e6c50b5cc309f1cda939"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26459,
          "sha512": "54378bb9eca5066c9c393e5cfeb16871c46da51c9b5ce88f11440eb79e85921e7d4e8930a91fecc261fbfd36bdda02844ed48b3b1d06b298abe3ffd4850ca45a",
          "sha256": "09fd2865f1624f91f61794443181184b7d711519bf2f519235691cfac05a3746",
          "sha1": "f44677f15539c30f46b0a347ff3bb0989197c663",
          "md5": "d7933def9cfbe01f52595f81a40cdd86"
        }
      ]
    }
  ]
}
