{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "a7161d361947475705b03ab7b50b425ff11f0449ed0aa4829d897e45b4b1b0a32403f36a88201fe85711782d5257b6a26fc3b65820158344128d7f53d38d6004",
          "sha256": "6262f1906aa0282ab74de9104ddcdfa2c3ee85292b602c03c4bb97e489a3078d",
          "sha1": "4d10d8b52a0e1746ca91285b9824035542c35d1c",
          "md5": "8d0bdbcc2e1503717b18b0e6258dc93f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "a7161d361947475705b03ab7b50b425ff11f0449ed0aa4829d897e45b4b1b0a32403f36a88201fe85711782d5257b6a26fc3b65820158344128d7f53d38d6004",
          "sha256": "6262f1906aa0282ab74de9104ddcdfa2c3ee85292b602c03c4bb97e489a3078d",
          "sha1": "4d10d8b52a0e1746ca91285b9824035542c35d1c",
          "md5": "8d0bdbcc2e1503717b18b0e6258dc93f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110786,
          "sha512": "a1662b7a11c431bf2121fc98fd4d4cf899926e52baa4c911fb3af53fd3cbecc30741ee180bfd97936a781f58b6a2c4bbffdab821d855da4d1e15ef783af0223c",
          "sha256": "009c80b7d0eb1a62abcff195edaed19693d527d4060af651fa23a2fe2ae4f2cf",
          "sha1": "2f1b3cd34128016bbdd59a8ae1a8471d6874f07b",
          "md5": "2fffa8f3389256c1860df82ffaf75689"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26459,
          "sha512": "7943140f0b62a13b58acc6808900b8a2f2cc67c2aec88b9fb244e386d3e876afa8066ac4dc77599604b24df7a37f4ec67135f659b3c666a44ca26b3cc52d3c47",
          "sha256": "93ce16e8997cb2d7549f9f7352e0b10cb14722b88a671caea9c4297453b29a51",
          "sha1": "a8ad1eb42e8caf13d647c6ffa5dd36594f622cdd",
          "md5": "2d58817edd4914a34965f41f981e442e"
        }
      ]
    }
  ]
}
