{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51849,
          "sha512": "01e0a837bd42157f677ea313ff4302a503e41a1791928de281477cb807df62872a07d35727b525660ad534503fa2cd6670d38c2188a4b0a13409cd1d7142d8c7",
          "sha256": "bafc1a29044dc76bc2d6eacad60ab64adf73db2f9cf48d71f39155a66f90bc1d",
          "sha1": "fd42eee4c69772646cb0df8ee53270af69b81493",
          "md5": "2735b58ed8b26d8b4bcdddcb0367f002"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51849,
          "sha512": "01e0a837bd42157f677ea313ff4302a503e41a1791928de281477cb807df62872a07d35727b525660ad534503fa2cd6670d38c2188a4b0a13409cd1d7142d8c7",
          "sha256": "bafc1a29044dc76bc2d6eacad60ab64adf73db2f9cf48d71f39155a66f90bc1d",
          "sha1": "fd42eee4c69772646cb0df8ee53270af69b81493",
          "md5": "2735b58ed8b26d8b4bcdddcb0367f002"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 99265,
          "sha512": "825acdb58de7c2ce9bb5e16fb8b8cd605e6a31d616abc0b38d61c9de724202b2702eeced615a512f566ea547ed284a4e14a2940fa748e509d9dad38c7a461704",
          "sha256": "37951852aa1fbcb63df3554ffae8de95a1c80a9e71406e400d2d39f4cca39e6b",
          "sha1": "fed6cbd18ead0c8e80f5198418c066523cf6b522",
          "md5": "847c4db1edf2f7cdd729608693ac027b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26413,
          "sha512": "137a342b1e01978b9b09562d74c7b39a30c3bd97f35261dcf5961fb7d85b7c225e1c05abaf1eb453685ca219c87420baa4e590dea8645c1716ecd82df7a394d8",
          "sha256": "ba0c385d238c06dc2900de0af6e3d22a3c1f4ca317af42fafcef7880d91f08bb",
          "sha1": "3e8d7dffde276456884f0c8c518fb6dcd9a5146e",
          "md5": "3c35265f5951cf6da264b62c81bd3b3b"
        }
      ]
    }
  ]
}
