{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "dc1e15e5d36f5f23d0d787b67e252550e4e65537280565021832c9254bc6ef2ba3a27a7c40dfce807fe51850fd442e9575ebee83f5b74bc179ae41847a175bd4",
          "sha256": "b65884383e19006bd0f783bbd61db605df0193fa5d17d69241f93c9d0b482138",
          "sha1": "817c1642bd293e4d07fa58ca9464bfacc980cdc7",
          "md5": "0f0f10f7ebc39430ce442edab39d95e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "dc1e15e5d36f5f23d0d787b67e252550e4e65537280565021832c9254bc6ef2ba3a27a7c40dfce807fe51850fd442e9575ebee83f5b74bc179ae41847a175bd4",
          "sha256": "b65884383e19006bd0f783bbd61db605df0193fa5d17d69241f93c9d0b482138",
          "sha1": "817c1642bd293e4d07fa58ca9464bfacc980cdc7",
          "md5": "0f0f10f7ebc39430ce442edab39d95e3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110786,
          "sha512": "1e24d3297832b67e4d1ea487e9b7ffd4c8f1aa81820c910fec6f2c5d26db439c44620b611ed0d971083b87f22c02373631924dc0f2c9c8c1832208e498f0666f",
          "sha256": "39c552b796e4f2da6467ad0b8a33bed16da6d867f54175ba021e012d00157609",
          "sha1": "8f629ec0356a60fd84a5420331035da8ae3cadd7",
          "md5": "d81364952e02c6c246e65417fd6cb580"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26459,
          "sha512": "b5ffea083af5e1f04de321965986733b4d42aa96035ca38d6c4a23356b9a0febf5e4cae4570f9197411aa3b1e341ca2b9d219ee8ee83df9bf7c7553d72590296",
          "sha256": "97fad685d93b5a90e2a08c10031002538c7f0a05f790a154580bef7a0ee1beef",
          "sha1": "df63e4da5ccc6bae2207cf52cded408429187a3d",
          "md5": "15051bdce0ce62999fa39201b57c2721"
        }
      ]
    }
  ]
}
