{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 56773,
          "sha512": "84b63e586e003d8cc30c009745270659476a382464592bba74a5af6492ef3c1fd17cdf1cca6692d390921d1d828a844059b23186501bb1a4ed3fa4271bf3a5d3",
          "sha256": "3f531580879a18e542cbf1d537a8c74ef3474353309e4d84eb1e05f0cecbb858",
          "sha1": "61e3bc8bdc75d367e74f9073c774ee0e25d8f5ec",
          "md5": "8ee71215b20ea6ecfb60a03180a93ee1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 56773,
          "sha512": "84b63e586e003d8cc30c009745270659476a382464592bba74a5af6492ef3c1fd17cdf1cca6692d390921d1d828a844059b23186501bb1a4ed3fa4271bf3a5d3",
          "sha256": "3f531580879a18e542cbf1d537a8c74ef3474353309e4d84eb1e05f0cecbb858",
          "sha1": "61e3bc8bdc75d367e74f9073c774ee0e25d8f5ec",
          "md5": "8ee71215b20ea6ecfb60a03180a93ee1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 169263,
          "sha512": "d09e12188d3e4e58b3977a9d3a869f6197f47d71b8fae3a72f7587a7b8445066720f84cc0ad465f3d515001d901b0e629a5d1728ec1b66a5a256ee9b83cbcf09",
          "sha256": "6f1f84e1ffe369c6693a4ffcf0bcbc0f5b143b8bcc8da136fc784c687dfa7e60",
          "sha1": "657e4ac471f4c53d4c70c1afaecd7a77309d381c",
          "md5": "6bbf36dc9ce8b4620ffa9476188be4f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27504,
          "sha512": "ad1eddd6230ae66b68e43348460ab007edd7732485ab4b3f0906007cadef3c90d5ce4ec82f11f1c2d0badfc978a6d92cabad7b3c24d6fc0ae9647b34f42c0f90",
          "sha256": "7d5cf325bdaa6b25a2234c49daafd2ac9dddbc929471376285c49632d3c17bdf",
          "sha1": "9ff7141c313227444274d0dd11c066f2e949cc00",
          "md5": "309aaa41519a170c2d000dd9bca310fd"
        }
      ]
    }
  ]
}
