{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 57634,
          "sha512": "7b21f4018a3edb9500f73ba6a17259655d0e0edee60a40004055a0f0e8bedf20904de2d47c66fc71a8ca65265f91bcf4073eea03ffde97cfd3b37937ed921de0",
          "sha256": "c935fd05eeec2dd347ace9a68230e2cacae404e754054bcc05e8b6aaa2d26881",
          "sha1": "c11056d92edcaa89f235e7204858eb7e986ab902",
          "md5": "0c4d248f40609b248ebdb76d6164e7fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 57634,
          "sha512": "7b21f4018a3edb9500f73ba6a17259655d0e0edee60a40004055a0f0e8bedf20904de2d47c66fc71a8ca65265f91bcf4073eea03ffde97cfd3b37937ed921de0",
          "sha256": "c935fd05eeec2dd347ace9a68230e2cacae404e754054bcc05e8b6aaa2d26881",
          "sha1": "c11056d92edcaa89f235e7204858eb7e986ab902",
          "md5": "0c4d248f40609b248ebdb76d6164e7fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 169328,
          "sha512": "a76923754efaf7499521948c2d5af1385d0280d9b5aab0258bd14a01baf168ca5a360031b664f4223618276b51258fad47b4108ced0d635fd3bf1a1b9d976a7e",
          "sha256": "f9ae4bffc07515aa7cb6446b579ac4c654bece8c58738fb708721d8398bdbeff",
          "sha1": "4374be677060edc054cf88811f8c86d0e4e21936",
          "md5": "f41e847e8529f22e87f253deba72ea4b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27486,
          "sha512": "c6498ebb6b17b0e2c427314e762a838b18417f551397dea6ec470aa297f16c0a2cc8c87a68dc5b3b568c3297e29e3371a356dcfc8ccbc87227f5cfc33f5e6b1f",
          "sha256": "55217ae9dce118d907f3cbcd33087bdd1f0877845af5fbbe117e9daf09cafb46",
          "sha1": "dc01b09c819228fa80ee4789d6207e5c6d54ab82",
          "md5": "60184f0f1b85ce4f8f9e80ab1fb40e88"
        }
      ]
    }
  ]
}
