{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 54269,
          "sha512": "d997049a0601d9b0a29db4669080160e4ea4188a6a665a70e92b241a46041cf63fceb9d6c3ac2ca0e39ee590377e61a0ed9f78a77d1c17f8dc11acecef103c2e",
          "sha256": "5fbee42f15ada23003a63b91d3d4ba90067352409267106aae84a7dcc2aee888",
          "sha1": "90d3d7042a6411b18934c4241ba3b9d04167d186",
          "md5": "84d9daeef48c399e3d986bf368c4d9a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 54269,
          "sha512": "d997049a0601d9b0a29db4669080160e4ea4188a6a665a70e92b241a46041cf63fceb9d6c3ac2ca0e39ee590377e61a0ed9f78a77d1c17f8dc11acecef103c2e",
          "sha256": "5fbee42f15ada23003a63b91d3d4ba90067352409267106aae84a7dcc2aee888",
          "sha1": "90d3d7042a6411b18934c4241ba3b9d04167d186",
          "md5": "84d9daeef48c399e3d986bf368c4d9a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "1f8f0e6c78ec50dc0e11e3b59426377947ab50c9c15679bc3312441bcd554fa780ae98eb35d62909f55e02f057988fb16d09d944d685792e117d9786c66f43f3",
          "sha256": "b6e38ce293c8095357983b48efd2923e2b975670c0fe8228696881e52c341653",
          "sha1": "0c23524945e19be67969772595c111934bb8a74e",
          "md5": "4ce8ca7ffa23d520795863da22908889"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27459,
          "sha512": "7968ca30ce23ed0db63cea9e18af1a78ade995715cb7e8d2abab24bc992a148608e80f5fb7978da90515b97e3c9bf23c474d1dec57db3ca1d4262b38e62191e1",
          "sha256": "360547405623d9eaf6731e2c0189b936621f2364ff0d6cf1066845bb9ad73f37",
          "sha1": "48a05c9c2257fc5b6614f12c98200c723bc4227f",
          "md5": "f49381b9e711764c613bc4c41ba3b2c9"
        }
      ]
    }
  ]
}
