{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 57634,
          "sha512": "2f9cbda7ab91310175ac1beb35e45d6a77b746e27d52de769008742c32332f16579db7534ab4ac5bae69b9a4d718f94ec2362a70c7b939f230f7728cbc7b9f17",
          "sha256": "4949904101b356794a3fa2bc091e4566d1d77fc3ff6b77b30cd7b907676954b2",
          "sha1": "8631047b57da5ea8ad78713bd2a5887267b147e6",
          "md5": "5d6a75ea19fe6dc1ecdb0cd52bca4d30"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 57634,
          "sha512": "2f9cbda7ab91310175ac1beb35e45d6a77b746e27d52de769008742c32332f16579db7534ab4ac5bae69b9a4d718f94ec2362a70c7b939f230f7728cbc7b9f17",
          "sha256": "4949904101b356794a3fa2bc091e4566d1d77fc3ff6b77b30cd7b907676954b2",
          "sha1": "8631047b57da5ea8ad78713bd2a5887267b147e6",
          "md5": "5d6a75ea19fe6dc1ecdb0cd52bca4d30"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 169315,
          "sha512": "76693cfc5a7454c6ef01bbe35bcc0df184a08d003a0d3839c2afe971b6f917dabb04ef7551242b2d97b535565f85518988b9af40858db7f9c5920993ffaae123",
          "sha256": "5c3a06a00a638d2890154cd590dda2e4d30086e29b0bcf0f26a102874ddb8708",
          "sha1": "b6d4cd5b468ce60f6be08fb5781c1133b218e78c",
          "md5": "307a222ce2da0b6a9284fca68bf62d7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27486,
          "sha512": "75f8983dd0a2c47263f9b4939506adb87aaeca3ca4f431c1ae475de1fbc9b4502c5ebc1ff5ee2f717120f686f6eea23b3f48e60a7a570dbe37a1d7b9e84b63ce",
          "sha256": "3b1bc62307721d33faa075f376dd71c1be8f13515ddcbef091c961b66d8b1620",
          "sha1": "1f790aa8a69c24dcd729cdf2fc0ec7e28c584935",
          "md5": "97991ad72364c40c959c4a97596db8c5"
        }
      ]
    }
  ]
}
