{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52083,
          "sha512": "c5d204b6f60bebd6db58f63e2002755701a42057eefb14e43b1ba50fc53e828b9259623b14b14c793e87fcc0ba767db49543086837ef701650929fc032ab3f95",
          "sha256": "6ebb8359c6d44b86b26ea5fd843e8c2069d3a353aa0304db41d89a5dae5a7792",
          "sha1": "3a55cb050ce07fcc7c65d2af5b0c444496c1287b",
          "md5": "19e79ad846154c090bc49eb8ce611a0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52083,
          "sha512": "c5d204b6f60bebd6db58f63e2002755701a42057eefb14e43b1ba50fc53e828b9259623b14b14c793e87fcc0ba767db49543086837ef701650929fc032ab3f95",
          "sha256": "6ebb8359c6d44b86b26ea5fd843e8c2069d3a353aa0304db41d89a5dae5a7792",
          "sha1": "3a55cb050ce07fcc7c65d2af5b0c444496c1287b",
          "md5": "19e79ad846154c090bc49eb8ce611a0f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 99265,
          "sha512": "5b46e258b833e3a672d6f47e2068d29da529c91158788a8e193931f0698c9ecec62ce1d3c15712f946a98268e55709b5769276af0fa9e2be53643e2df00369a7",
          "sha256": "25c1640854a258c7d56478e0eb7942cdccceda1be0c7a3cede2d1ce97472758f",
          "sha1": "898537ab0886d9c682154202ea30bf9f664e5fc1",
          "md5": "73b2e0cbeda3f343510967700ffa49b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26441,
          "sha512": "4bfad34f6acc5d57fd908d3525c0f05bf6cd65a385c634cd13e58376e887b2a705c87bfad4f3744b971b651b82c46b3c6f59121735dde3a4e0b7da0a8059c4eb",
          "sha256": "8f49f73aa93613462a9dba835f0d5272f3134d9bd3afd913d6884b7efee5d3a4",
          "sha1": "e9676769571bbcf667acd30a6d1cfff5e3eea950",
          "md5": "850bfa7a3a43aa0527ba110642ef82e1"
        }
      ]
    }
  ]
}
