{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52664,
          "sha512": "7e967d96e1bc08ca0b393daa2de7d9920510060a3e7517a3c6fa4a62b2617a6c7f1458726e14bf04f89170089c04398632656dc59332a044320195ff93f3ac4f",
          "sha256": "906e3b0267aa605540f65eda99ae2bf7a8cc8f85c85cc62678253c61090c7877",
          "sha1": "22887abfab277539268200fba0f2076a5b703a5a",
          "md5": "0a03265ca751cff272ddce177edf272d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52664,
          "sha512": "7e967d96e1bc08ca0b393daa2de7d9920510060a3e7517a3c6fa4a62b2617a6c7f1458726e14bf04f89170089c04398632656dc59332a044320195ff93f3ac4f",
          "sha256": "906e3b0267aa605540f65eda99ae2bf7a8cc8f85c85cc62678253c61090c7877",
          "sha1": "22887abfab277539268200fba0f2076a5b703a5a",
          "md5": "0a03265ca751cff272ddce177edf272d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "a74e8a5b99fd043f4e9296d270c07b95bce78fb5a90fc8a99fe4fb3fb2469ab3e008e55dc92032c9ac0b08a1cddbe90298bafab47519649f025c1dc551e12946",
          "sha256": "fb71ef62fd4ca90e53faafbd7fc5f06ca2bf4e74c1189c2615c5378d11d9f451",
          "sha1": "eb7da7429d72e13bd8896496ae785e185b2c00d7",
          "md5": "f183f2e55f0e0d2bfea61af7aaa8046d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26634,
          "sha512": "c52585fcc78735a738104a3692adacefa56e351189a02979bacd54cbd3f61ca6bb05cfedc80e9e76d626ad514d2bed74835e6213174bc5133718bf745a860907",
          "sha256": "8ee1ef8958a83a7b1e201c524cf87ca1f9a5f57163b5d73b64d9f8f4f9922609",
          "sha1": "7aebac6dd56e0ac371d09250d598e0781892eb92",
          "md5": "e778204179078350455e411a1802bd75"
        }
      ]
    }
  ]
}
