{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51940,
          "sha512": "efe025af8d32952fac71bdc87b6ae02a0c67f48492d9aa1065cb542a5de2454d2d7fed124daa7c655a0d3b4c71692beea3ff067c5b5cb7a02fef8236e753d860",
          "sha256": "efd222db4f1023fc6650a6323213dfd95d5ae6ffc3f747acc6c8a03f7508a93c",
          "sha1": "e17cd206ab3fc102d05b67f4ae7a66ce61abf1e5",
          "md5": "e45aba19813c93063c9b7bca4bb33e0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51940,
          "sha512": "efe025af8d32952fac71bdc87b6ae02a0c67f48492d9aa1065cb542a5de2454d2d7fed124daa7c655a0d3b4c71692beea3ff067c5b5cb7a02fef8236e753d860",
          "sha256": "efd222db4f1023fc6650a6323213dfd95d5ae6ffc3f747acc6c8a03f7508a93c",
          "sha1": "e17cd206ab3fc102d05b67f4ae7a66ce61abf1e5",
          "md5": "e45aba19813c93063c9b7bca4bb33e0a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110782,
          "sha512": "5538e80743693261c13a5ac7266c125f1187078b3758a1f5d58cd1d831c2e08bc96a937a8af5a1ba5132e7fa16a3e3778bd016769cad47564a57e7457aa06e05",
          "sha256": "f8f38a7af18f6f4851a2e37effa2129018330cc2ff47b3a5263b23505e13ae77",
          "sha1": "a2156421fba57730e56b91a553d9b6c34b135246",
          "md5": "5c80115b6bd4d54795f7db43ee89403f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26413,
          "sha512": "c67f718ff5e84602c73d8de9cfc70540b9a1349c5e15d4f20c87e6ea88e2d2e4e50c644f6893e75226c28821f24500ea5c6ac9e1c8d27ecd67e00161da373bfd",
          "sha256": "33fe968df01001654f3a6647f187b2b333880600402af0877201d91ccf242bef",
          "sha1": "bde78224fcc775ca9183e4fcb51a339e2994406b",
          "md5": "70a403b6d5a655619de04021ba2e22e0"
        }
      ]
    }
  ]
}
