{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "fa72c48e36f270191cc614d0fb46616dd35fd12702a459ba460fe4f071083952e39b8a2cfb247c069791ba824747f679f0cbea753ddfdc06f240e896c280b705",
          "sha256": "9b7b3eb8aabf6406638583cb2b08976c9afbc57b22479ddcd4be12a94a35a94b",
          "sha1": "34ad9a3947e610e124a78bc3d38e83d022da153d",
          "md5": "e6adf3898d8577d1b93130d6a10bca48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "fa72c48e36f270191cc614d0fb46616dd35fd12702a459ba460fe4f071083952e39b8a2cfb247c069791ba824747f679f0cbea753ddfdc06f240e896c280b705",
          "sha256": "9b7b3eb8aabf6406638583cb2b08976c9afbc57b22479ddcd4be12a94a35a94b",
          "sha1": "34ad9a3947e610e124a78bc3d38e83d022da153d",
          "md5": "e6adf3898d8577d1b93130d6a10bca48"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110786,
          "sha512": "28b02cac8c7229e73932723e7ef30e599f238e71c79d40dab04718e3424a1956aac158959ee1e92649da3f90cd7c214ec9747ad4d5e0994c644de118e17b2790",
          "sha256": "668e6989de032e764dd883699e9e3faa40acd1eff1448eef672ed089ed8b2c12",
          "sha1": "204e25e8272553745a36f2689a6866e47d81f47b",
          "md5": "5f4fdc1ef7773e23aed658f14415320e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26459,
          "sha512": "bafd1381e636e6e23b34cb14dce8de0928f21b435c2902f037ab6b819914c1f82119f11f4d4a75cc0a068b7b4e2946af293d9ba3b05f5e32b2fe2040f95423ff",
          "sha256": "a37bd7f132daed30ac762f6ff88e4112ba45638c9c2fddc2f8bbeac96c7eeced",
          "sha1": "a122071131f3886e9544bb9548689b6fcc729b76",
          "md5": "c7a59e51dd001894e7153c3bb3d95f61"
        }
      ]
    }
  ]
}
