{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 53019,
          "sha512": "dfe679262a4411935fbc0f7bb5b0f85ea0dd058a8f75625e8ed9456ee6a37b0bcc785c7556ec0fd75a0a0a5b92760c52adfe0b1ec042934a1ff86eeffd76bca9",
          "sha256": "373de82e564ad15121fbd26b193182a7e700e49ec401413d3edc0d1781bb03ef",
          "sha1": "946b65ed6e9eef64d33323c454331c0a4c2bf1f6",
          "md5": "2c082dca7f196a037d89bea6a1421ed4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 53019,
          "sha512": "dfe679262a4411935fbc0f7bb5b0f85ea0dd058a8f75625e8ed9456ee6a37b0bcc785c7556ec0fd75a0a0a5b92760c52adfe0b1ec042934a1ff86eeffd76bca9",
          "sha256": "373de82e564ad15121fbd26b193182a7e700e49ec401413d3edc0d1781bb03ef",
          "sha1": "946b65ed6e9eef64d33323c454331c0a4c2bf1f6",
          "md5": "2c082dca7f196a037d89bea6a1421ed4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "2155aee64aae9fed4be51303c9a7713e1d56871136456e1d81ff759e3e6fac522d3da18365ef6d33791383b850280890dac0d7577c7dc4d62a8cd68c917abaa0",
          "sha256": "de683a028646747e45b968f1bd6e659116230721adaab4402b5160664b136a6b",
          "sha1": "846d4c62bc4ecfa4a379a723ec860022e9fdb600",
          "md5": "31cb809de09cea3214a0ae5f0658d906"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26618,
          "sha512": "f652e0ab6232925e0771e2a7911ebb6255233a1e72b3f73e050d4c87640b10bbb874611e39f86ea366eaee8ebdbd5ee4e036bbb3a265ec416628ccd42c95fc4f",
          "sha256": "6485405c8b43697f991fb9015e0e8ac874ece9e5a002e12ef330a08fa571eb0c",
          "sha1": "a3346e5bfcc3be1508f0a31e3922e29b439d490e",
          "md5": "18f06c41256cf314251bb0b825ebdbf1"
        }
      ]
    }
  ]
}
