{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 54269,
          "sha512": "55fb4df738838ee52d863b67ae2231602358ee9c09b1d34b9c43b54ab8f584ded5e0598f6bf2c16ae5b8c73d1c4c570e5f1a99caba92762e1d4728f3c24dc9f1",
          "sha256": "429f082bacb524ba30ed8c8ba711f77697083a3bee85770332670acdd6432e7f",
          "sha1": "b01ee39f1bec78bfc8f5c8c2fad14e7d30769e23",
          "md5": "0bdeb6380c3a2b18748c1748d0838d08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 54269,
          "sha512": "55fb4df738838ee52d863b67ae2231602358ee9c09b1d34b9c43b54ab8f584ded5e0598f6bf2c16ae5b8c73d1c4c570e5f1a99caba92762e1d4728f3c24dc9f1",
          "sha256": "429f082bacb524ba30ed8c8ba711f77697083a3bee85770332670acdd6432e7f",
          "sha1": "b01ee39f1bec78bfc8f5c8c2fad14e7d30769e23",
          "md5": "0bdeb6380c3a2b18748c1748d0838d08"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110445,
          "sha512": "f752db89fa1ec4d6c9b243f0eb460243bb1d59c4cfa1f69fdc073045dec659d28d7b0980f4c1139be82db7048a7b3afffa18d06da6ca0ee7c8a62565f4836d6d",
          "sha256": "6cf6a1af36dcf87a1de0e783c9757bd9480212ca69158c1da039b103499af9cc",
          "sha1": "ed562529330fa858af0de791d46976b57efe4d90",
          "md5": "4facb0b1f080b1771322abf09244bbcf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27446,
          "sha512": "5efa813029ca977623ff29ed453f0a1dfaa3de9b512bf82e816dc65abe8af9103c82f4ff6a96f8777e84158bfd866a02b2341ae3d0c4416dd1e6caac7ae2a05a",
          "sha256": "bb8bbba39733fad0acb178aa3154e420622ea664dc0f01209ded7e4ed699f341",
          "sha1": "ff785948857573216cabc38e3cfdfb0ae2d88628",
          "md5": "c324d283ee6dce28ceff1c55e60d1eff"
        }
      ]
    }
  ]
}
