{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 53019,
          "sha512": "ee504be7058e562354e419dac5ad0a10572e6485418d25bc1d211f8e0ed355e5f45bb56486ba8da0b5bcc6827fbd535d0d8a1df15400a373399ac1486daaa806",
          "sha256": "dc01c10e460382dab48bb31cae445d29ff1448fe2e3fad5d51050b74acd6571a",
          "sha1": "c906e1cb66b185dfa7edb63ede2a074ee340a887",
          "md5": "7fa9b494394e7f4ebefae3aa5329f283"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 53019,
          "sha512": "ee504be7058e562354e419dac5ad0a10572e6485418d25bc1d211f8e0ed355e5f45bb56486ba8da0b5bcc6827fbd535d0d8a1df15400a373399ac1486daaa806",
          "sha256": "dc01c10e460382dab48bb31cae445d29ff1448fe2e3fad5d51050b74acd6571a",
          "sha1": "c906e1cb66b185dfa7edb63ede2a074ee340a887",
          "md5": "7fa9b494394e7f4ebefae3aa5329f283"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "19f6db16053a871b84ee9c84694a393cdb8658b5e5d767f5ca9ac34b92a8d729ed5ae2118422ed78cb94bbdef5760b679b5a8e161c090821ca0b738befe784e1",
          "sha256": "ed1e780ed3a87b19930a71da31428dbfde88d959d0eb902d43e890d911f3013f",
          "sha1": "c304b21a2c10fc10ae162ba6863fb74951934677",
          "md5": "c450cda4c88e4bfa597f087337803aeb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26618,
          "sha512": "5ba0e03319e862ef80131af5b42d03a67d4118184dd91b38a0ed78313398b6f876f1e2e57f88381b99e2776af533295c26f5c8aff20894fead4af9469a033608",
          "sha256": "d4a6618460f2c227075dccebb05e6bca2fc92d4251c30f3b20c2956b035f732b",
          "sha1": "7a2ccb13567aed0629f8813f7cdcc84f2b59b2e5",
          "md5": "767cf6de59fd4ba52ff8e6a6bca15fa6"
        }
      ]
    }
  ]
}
