{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51940,
          "sha512": "0a59434b7cbfd463b5996cf013559e89e92e17cf63eebd61e324276ba832623f9b5dacf6062a82bbff092a02fc76b107a63201d11183cc142ec971fc02c9d7ea",
          "sha256": "40fd45da8e3993f8e9ee5ba23dfa073d073ab2e1ca5dece8cc4d24df67ceec6a",
          "sha1": "2ef8afdce7d124b255efc237ded5eafa4de5265e",
          "md5": "97f20a7f1ad40a6718e33afdf6798cda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51940,
          "sha512": "0a59434b7cbfd463b5996cf013559e89e92e17cf63eebd61e324276ba832623f9b5dacf6062a82bbff092a02fc76b107a63201d11183cc142ec971fc02c9d7ea",
          "sha256": "40fd45da8e3993f8e9ee5ba23dfa073d073ab2e1ca5dece8cc4d24df67ceec6a",
          "sha1": "2ef8afdce7d124b255efc237ded5eafa4de5265e",
          "md5": "97f20a7f1ad40a6718e33afdf6798cda"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110782,
          "sha512": "a16532365e25e7788821badffa4b0126b4c6e2881311a11660d89c1a034ac420a528682a52976137e6320ed8a5c5a5ed18b8daf32388cbecdaff8b181dc42a32",
          "sha256": "566fb1777bd67dd3b1c099f3b480711614268b430b338e90412ad443b6d198fd",
          "sha1": "3e6d4b5dd424136dcfd6c2740a8909e763fdf35b",
          "md5": "668253689e6753fa66adae810995139c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26413,
          "sha512": "ee718676e6fc6812370479534cc210c5b6f5d6db8929cab1512bb72cd0caa01c87582201ceb523f71125ee606e8f8cf7339016674b4f3122f232ba47b6e66282",
          "sha256": "3022c874e2f8f6fb3cd921130f98c3cd943c5647f7075e148182701bed9d9d7a",
          "sha1": "e635f2896f8b4c937230dd2c82cc5f65415dd573",
          "md5": "ce8d9fd6e613da48ebf3bd11fb22e901"
        }
      ]
    }
  ]
}
