{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "500482f142045361f9b96b428659bffc86d01a8a84e7935b811291c3ba3416335cb171552eed3f46ec788c613f7b714f3c08252ca70532b8a0979dda1d892376",
          "sha256": "13de9702fd2378874d4b330a20d515c539060ab7c4e49603838bbb1d19833515",
          "sha1": "f9f200c10a3e1c66d90e4bbcdf8a6481239e6bf9",
          "md5": "d595001d08f60bf52f38f0579961505d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "500482f142045361f9b96b428659bffc86d01a8a84e7935b811291c3ba3416335cb171552eed3f46ec788c613f7b714f3c08252ca70532b8a0979dda1d892376",
          "sha256": "13de9702fd2378874d4b330a20d515c539060ab7c4e49603838bbb1d19833515",
          "sha1": "f9f200c10a3e1c66d90e4bbcdf8a6481239e6bf9",
          "md5": "d595001d08f60bf52f38f0579961505d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 99265,
          "sha512": "87cd2c83836c46e45107748405176e66c60fa7e25ce3b7a7d675488fbc3ddc600280f45084b627837d0a935aba0ab759db7e1ec10ad8aa8438037093e988a743",
          "sha256": "cd8ab658e382f5d693666e5e920c0402e60b05f88ac1bbfced16366119c6561e",
          "sha1": "d099b24e83a72d54d15f7bb2686520b84ea34839",
          "md5": "bc07a40b7d943afd575ca4db2443d578"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26441,
          "sha512": "1fc93368da90ad6692b511e784f94c8c588b1e50a011b11a975db2fd19eb6eba577826597d40a91201a87efb2f932341cf3fae6a541ac630773129ba58488bb5",
          "sha256": "00cc993835e53feca6f1a0b032e96e2d850654d5853fbbc7217079fbf9e49ab1",
          "sha1": "d3ba82065f5ce8ec509c59302d22e4a4ae38b663",
          "md5": "09e154a15afc6b3b8357ac6c35699821"
        }
      ]
    }
  ]
}
