{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 54269,
          "sha512": "4319b64a70b56f29d0724371eff8f51011fafd7c6480652903adf52de8581b71573a6ae1fe4682a5eacfae4fb20b2cb02cd316f01c1dfdf2301f165b049a151d",
          "sha256": "3439a2c930c4a2e9335ecbb0dcdae17da2dc0216027934fb3aed60d539bca795",
          "sha1": "45f9a60bc989ae841de0dd19dc421a848d807d7b",
          "md5": "f45bc4a0af20cd1d3ee0d40b34b34468"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 54269,
          "sha512": "4319b64a70b56f29d0724371eff8f51011fafd7c6480652903adf52de8581b71573a6ae1fe4682a5eacfae4fb20b2cb02cd316f01c1dfdf2301f165b049a151d",
          "sha256": "3439a2c930c4a2e9335ecbb0dcdae17da2dc0216027934fb3aed60d539bca795",
          "sha1": "45f9a60bc989ae841de0dd19dc421a848d807d7b",
          "md5": "f45bc4a0af20cd1d3ee0d40b34b34468"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "400ba0f0d889dc89c13b6de9ea30cd67670e30c63e2726b6e864eb4c671a30e170a95428a47fdd9446e3b22e644df85caabaa7e46a7b11f250f5d7af62a7e862",
          "sha256": "2e8f51089bf6135c741a9955e0a8f0ece59ddb6999aff9d2988cee128b2c79bb",
          "sha1": "8318d0be99a433ae67ee7f89688c99e702e6b6fb",
          "md5": "9f2cd895b330e0392f332afa65c66f57"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27446,
          "sha512": "574780cb12b61f741529b4ac8c6106e36fc77ac15ace507af010308656189aecb0b00c72c227c48aafe52d0e41990f6c44a530e0f2001d15b4947e84d158a06c",
          "sha256": "4a9501c52b88224ff2b71a0426350df1209a6e63040a1aa0db811133ecbfd865",
          "sha1": "21eecff372f4d9bedaca61d7f611549b3b875b7e",
          "md5": "30322113f2b462c307e02841acdd1bd9"
        }
      ]
    }
  ]
}
