{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 53019,
          "sha512": "8fd811142b1f6eb4ae8201da829ba4d172ad4321351698123312ce73b6594c445e5737ee9cc0da6143f0e02e807edd47df28ea9a8199ea1ae8af8e7569bcccf4",
          "sha256": "ce2e4e6597172445010201dddb67b8c4a89f62a3de173e76545f18833d5a92d1",
          "sha1": "920b187bde969a8983194de65e540d6dbdba7f22",
          "md5": "588b0fbdf0e91cb2bc49d5e305f1f5db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 53019,
          "sha512": "8fd811142b1f6eb4ae8201da829ba4d172ad4321351698123312ce73b6594c445e5737ee9cc0da6143f0e02e807edd47df28ea9a8199ea1ae8af8e7569bcccf4",
          "sha256": "ce2e4e6597172445010201dddb67b8c4a89f62a3de173e76545f18833d5a92d1",
          "sha1": "920b187bde969a8983194de65e540d6dbdba7f22",
          "md5": "588b0fbdf0e91cb2bc49d5e305f1f5db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "9c2dd07cd2ebe23da1acd51fcbfe096d21f3aca3dc40eb314e17a1e512f82ced4628f3d57b76d1d72f3e044d9758d39ddad25633924837d244e79aa61ad120f8",
          "sha256": "1af949e89aaa18d10431403a5b9e70822f129393b4f0fe0822094bbb7b8cd589",
          "sha1": "9ec89014eed5dbd3713bc7520e1512700cbfbf60",
          "md5": "07b4fe93e990cd52fcecabc6b3f4d883"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26618,
          "sha512": "47aceadee65a124f387ea6e757802320d3edb662273f49d1e9fc77119cba0adcb3cba2ada2d016f16f9411f9523aa21876a5b0fc86b8bfdec6fb29db9f82f0cb",
          "sha256": "488383043fc34fb45b27b2adb41ce09c8238ab7ec5f171292899e22ecb3aad06",
          "sha1": "361d2bfb73b527473dfb4727cd6deca1f9c29e91",
          "md5": "140a6b1fae15af9ab9e6c1c7273ada5e"
        }
      ]
    }
  ]
}
