{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 54269,
          "sha512": "27498eb56ed84653da4374b05dad9e8804bb9baa65517ccd205dc7a8bb64a568072d129e4e5791e951bcca1d2bd619088d37ac193a602641649778378a82ce6f",
          "sha256": "54be181fac94619d440ae0feb425a7a0bb5647d292bc7a07142ce203b5227166",
          "sha1": "ba6d2d5791acd3b67c3723c6e025344fbb687818",
          "md5": "aac6ff3d1c2e7583407d94a829bfe961"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 54269,
          "sha512": "27498eb56ed84653da4374b05dad9e8804bb9baa65517ccd205dc7a8bb64a568072d129e4e5791e951bcca1d2bd619088d37ac193a602641649778378a82ce6f",
          "sha256": "54be181fac94619d440ae0feb425a7a0bb5647d292bc7a07142ce203b5227166",
          "sha1": "ba6d2d5791acd3b67c3723c6e025344fbb687818",
          "md5": "aac6ff3d1c2e7583407d94a829bfe961"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "b6d0732b275274ab40ef7e2f1fa0428a663d5c6d824d6662d0002dabde2e5b20fb9a38d73b9e87949cab021da1a13c3bbdcc2219905e55847cc7fdea566c2572",
          "sha256": "e24e348cd2b8eb4b82e271bd7cda75a1b2a43c169c6d759f72bbe66649e16be2",
          "sha1": "a825bfe35703ef2497899d828ad92f7ebe49189c",
          "md5": "9a97523cf0a1efa35443790e4c9195cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27446,
          "sha512": "84ef770a10b65006de9bc22c1e28372dce3a69f8a259871c797a630e9f89da63595a8d6546f299893c3909b3e8d6a0dec7ec337de1b06f5dacae31d31d4932c1",
          "sha256": "56cfa7ee8d2ed04c690d5719ab51964e86f0a969132471450f023282999e9f88",
          "sha1": "d78ba91405c878bd5f96491b4256257cb67689b1",
          "md5": "04963cfb9cc3b06d65285ac9dfe6677e"
        }
      ]
    }
  ]
}
