{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "5de5c3b8e6566cfa19b12d48e38b54c8e8c5ac277fe66b9566af775f0c787384113c59c282ac48fe88a7b8c92f8a5e403e51956fe8e656cf68d52088fd2e94e7",
          "sha256": "7a400a78ae1543a512de24dbb67d112f92eec67783a724ee177367176bff64f6",
          "sha1": "c6f41883ef477f11a0782cca6931f4f203bc50a0",
          "md5": "9f6134272933c4aa8a67b6bc09de71a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "5de5c3b8e6566cfa19b12d48e38b54c8e8c5ac277fe66b9566af775f0c787384113c59c282ac48fe88a7b8c92f8a5e403e51956fe8e656cf68d52088fd2e94e7",
          "sha256": "7a400a78ae1543a512de24dbb67d112f92eec67783a724ee177367176bff64f6",
          "sha1": "c6f41883ef477f11a0782cca6931f4f203bc50a0",
          "md5": "9f6134272933c4aa8a67b6bc09de71a1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 99265,
          "sha512": "3fafccc607baac20502f79db7ac5f971c17d8a0f4df99802cd3c63cc787b48f025fed9b7f0b06dd03a76f2feb692a06f4962a877ce3f08751f09f4c0957bd74f",
          "sha256": "a4cf9698070ef123501429fb34cac97a8379342d9287b8060595baa7f8fee88b",
          "sha1": "777618a128b99fbe81f49ec8c00ebe0b05d1e85c",
          "md5": "82e16c4d90d60238d81be2500b4854fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26441,
          "sha512": "bdfcc45930699b23b9da6a9335e0e0b269fbc7054f0f4d7630a4877e6a75900b4ff4c45949344a7af3aae8e3e19cc25228b544b77f44572fa1f2cd8495e375e8",
          "sha256": "3ebfe25a1b69ee37e4ca34ecc94cb4476486542bb09049a26214be6d4093723c",
          "sha1": "919721588018f08fecd3b960462249f45f02c9ed",
          "md5": "82d506f7b48ba88daec64605b10d76c7"
        }
      ]
    }
  ]
}
