{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "42c9bbf5ba507fe2d6fa0be7d150934d4333360d60b7b1c2fe5c5237805071e8fa224638b8f1fe5df478117ec080b08e91e2957f0133ccf048a2095e7fc7f855",
          "sha256": "3b1357d9b216a5dbcb7d01ba116e1c3ed335a9683ee9c65c42393ec7c370bc77",
          "sha1": "881682a3d92a67b402b737df9d403a9d807f329a",
          "md5": "626865ae5d5def18a58e185158b72548"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "42c9bbf5ba507fe2d6fa0be7d150934d4333360d60b7b1c2fe5c5237805071e8fa224638b8f1fe5df478117ec080b08e91e2957f0133ccf048a2095e7fc7f855",
          "sha256": "3b1357d9b216a5dbcb7d01ba116e1c3ed335a9683ee9c65c42393ec7c370bc77",
          "sha1": "881682a3d92a67b402b737df9d403a9d807f329a",
          "md5": "626865ae5d5def18a58e185158b72548"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110786,
          "sha512": "208650db661255a3cec12c37e58810482c1eee2f4a4cb011cd500f213b9230a43b2c2f49c7f90d67a47fafa099ece15917a346af3e9b9de9f18eb7a8456f1c22",
          "sha256": "a8ca01719d09ce5a213c7d52e6c4c9e12602d25c7d62d4758930940d1bf61f51",
          "sha1": "c939260519274d82eda4f8ac397a7db2b004787d",
          "md5": "ed239ced739d6ebffb17faa532a2dce1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26459,
          "sha512": "4c506c71eff37f583027a850d841a7ce59f033b775158a77e6ffaf4bba318f5688fdf8d68b2982da216264f9354f00d0c7ddae258e0ef74a7aef6e964b57db44",
          "sha256": "1178bb0d53a01a3daaf1bbcaa7f90fa7717ae0435d1cb43579acb6f95e609248",
          "sha1": "bc6c4c553e64a1580b3c7a74419b508937bf5be6",
          "md5": "cfacf491287c1b505edb2bd9264ebe1b"
        }
      ]
    }
  ]
}
