{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "b8739be82bd940670a5e42c9239e3f48123eb66dc2c5929b922de00f6a8ff459c7da30901de41e5e4c2e5557b9ca50f008b8536944d1dae712f22e7bddca0148",
          "sha256": "6e99471fc5d96e22997fa766a93ecd8e83bf977568dc9caf3b8bc9446bc84177",
          "sha1": "9e43ee9ea5f4e000ba1dabe6f287da3da9cf7e7f",
          "md5": "1a6ad2798e6db30340c68cee4e5d3d22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "b8739be82bd940670a5e42c9239e3f48123eb66dc2c5929b922de00f6a8ff459c7da30901de41e5e4c2e5557b9ca50f008b8536944d1dae712f22e7bddca0148",
          "sha256": "6e99471fc5d96e22997fa766a93ecd8e83bf977568dc9caf3b8bc9446bc84177",
          "sha1": "9e43ee9ea5f4e000ba1dabe6f287da3da9cf7e7f",
          "md5": "1a6ad2798e6db30340c68cee4e5d3d22"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110786,
          "sha512": "972cf518f792a3ec3aff7737beaab9f6e1b03c7376742b6618e7a51547716b1a0ba8245c52c6d5d51ab54da07d23a13f1981c09d0db128689cf67b75a0e3a9fd",
          "sha256": "1e76973a0ec55b813053b6b655ee9b92bdf707eac1ddb37cad3746cda0016821",
          "sha1": "374e079a1bf52f38458c29b0d831759b155eaf0e",
          "md5": "f693b82e11c193628a7689e1419e1bb5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26459,
          "sha512": "7e76ab3d75dd111301191616dedb921ef389191e05819761f107404b52304e0e3f094158e1eb315e45ec9588bea55f96e1ca91ecd6d556c603c9b63abe5b597b",
          "sha256": "4237a28a62b0f6311f8bbbef494e962da93ee61082afaaad698ad6dc34c6e05f",
          "sha1": "c3b1ade8c37f882d03e999617df703fd16d171e3",
          "md5": "b6baa560f7f47a62034a03903dd4f8c4"
        }
      ]
    }
  ]
}
