{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 54269,
          "sha512": "212d7ed78e478e76b69ae92bdda7ea6c8f95727c9106ece01a2d5488a171d7d7ee765e25aa48a80a068fbc9b738302caf42388638d901318777a97d9763504ee",
          "sha256": "a514ec56b7e7cd0ebc0cff7df61cf8daec98a9c6d911501ef4425a941ba04390",
          "sha1": "38c9bd8b93bf6baa936e66c05cf234b7c7ed51be",
          "md5": "669189d6b89e9c89bc125182a8eebc5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 54269,
          "sha512": "212d7ed78e478e76b69ae92bdda7ea6c8f95727c9106ece01a2d5488a171d7d7ee765e25aa48a80a068fbc9b738302caf42388638d901318777a97d9763504ee",
          "sha256": "a514ec56b7e7cd0ebc0cff7df61cf8daec98a9c6d911501ef4425a941ba04390",
          "sha1": "38c9bd8b93bf6baa936e66c05cf234b7c7ed51be",
          "md5": "669189d6b89e9c89bc125182a8eebc5d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "aae9a8548689dc7de53742a95f70406a70cd30dc96d59957766f83f1f16af1c6544f06149eefde98340538a9e9f2996317c5fa6a490ace16b5e266a14aa8e4ce",
          "sha256": "9d83d9c8f77c5226a7461ba648e7a3c2b6ab6ab9ce9e1f1b787163d274156dad",
          "sha1": "0105dff6bd4928d7b2700c9a8355427006bef5ab",
          "md5": "812b7bc39dc367c027c111435fe4de51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27459,
          "sha512": "ca2f73d19f1f1cac63ef78da45270898c7de3a8fc0db10e961b55362440c7d0ead917a32e2917f9247385d5cddd18085883c07f3c540203d6410410a98046235",
          "sha256": "4cbc9846a1f30413194284866d689cc4dd222f35cb3b5766dd1b91452a31836f",
          "sha1": "16b7743ade3b644bb89838755b5d0a6fc291452f",
          "md5": "5359a5f6f11a048b6f5173365366c0e9"
        }
      ]
    }
  ]
}
