{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "68e8093f7f7754f4438e6514d5830ecd38b81f5bdcee097866ec0926cae7973e192f9cf2a39bda1cff8c0c3376bb88b012925382d4dfb4a1927704bf22cbac4c",
          "sha256": "577c230f59321b943048452fa47c112eea1000f57c64a8e655cd6bef2418d953",
          "sha1": "dddc6fc617bc0b46a8f3f04d3557939f50f04c17",
          "md5": "a700ca1de0d5374ebeee607b3d7fbf14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "68e8093f7f7754f4438e6514d5830ecd38b81f5bdcee097866ec0926cae7973e192f9cf2a39bda1cff8c0c3376bb88b012925382d4dfb4a1927704bf22cbac4c",
          "sha256": "577c230f59321b943048452fa47c112eea1000f57c64a8e655cd6bef2418d953",
          "sha1": "dddc6fc617bc0b46a8f3f04d3557939f50f04c17",
          "md5": "a700ca1de0d5374ebeee607b3d7fbf14"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110786,
          "sha512": "0fa9f13ee3a438d952c4f683448b348319a9612dad632ea70c2806b690a5523d7aa21b910df6f87fc2b859337c4a6ee523292fbff4db6d6454d809a5549173aa",
          "sha256": "54643d269a3fe99cbacb902b0281d35d9f6c4a91160eb89467b412161525a9b6",
          "sha1": "3ef8e83cbecf8151e988540bad84d965676a6aeb",
          "md5": "98c409ff9e26a9e301836382ca5b324b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26459,
          "sha512": "a675468be02358c000fc2c94a78fca45d844a313b06d9e5ffd7ec288c65eaab6e9f27a2d50051295bb888ac01b37713e59908669358a62e82b41a93c59bdf5b6",
          "sha256": "b1e1a5c40cd5a7f737a59b764807e5790fd6c77a39cb2b83adeea58754df7838",
          "sha1": "aed3c91e7c4e7168f647d0d4145c552e93cac7bf",
          "md5": "de989fdf2014ea6b68f0fa3aa6d907cf"
        }
      ]
    }
  ]
}
