{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52664,
          "sha512": "ebe5898e103f0ed49c524ff3118d7a54dcfa8295d170478aabe48cb400320181707a8545719fa3698d22364067237277c7e66ca2c2b83f01fc767f6bbc216fa2",
          "sha256": "09f4f7f7f3f03d80e94ef104ea8943191abacb393c8521d71619a1e5d4c07ade",
          "sha1": "37d84bfa4215738b4b716ea3dfcd9c0c08255bbf",
          "md5": "cbbdb525ee8064b48b1efb831e7f633b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52664,
          "sha512": "ebe5898e103f0ed49c524ff3118d7a54dcfa8295d170478aabe48cb400320181707a8545719fa3698d22364067237277c7e66ca2c2b83f01fc767f6bbc216fa2",
          "sha256": "09f4f7f7f3f03d80e94ef104ea8943191abacb393c8521d71619a1e5d4c07ade",
          "sha1": "37d84bfa4215738b4b716ea3dfcd9c0c08255bbf",
          "md5": "cbbdb525ee8064b48b1efb831e7f633b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110432,
          "sha512": "9702b0cd84453faa7eaa8cbe7c6fcd91af4134e6452202235a193b1b5208ad9fb1b126b712984a648f096febe034a27eb487cb091d87971a7cb9009d8f0d49be",
          "sha256": "dc475f6254a0b59cb224f24b09e01f393954711387cd7ec22e4f15e3d7209632",
          "sha1": "8b0956d32a7453ce587aac1fd6323461f2f092b1",
          "md5": "a1f54e9896c42f3d39f7680c72343d1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26634,
          "sha512": "e1fc5832cf2c3c8df7a4ced491ffa29d3f6d6d04dc457376e823107f438357c42c9278fd1f23f52ad1834bffcf641546f79275f6d24ed85bc1058370c642027e",
          "sha256": "c96de4cb5f20a4e9bd7124e388b0712d148731964a22f7b87e9026ef8016b8f4",
          "sha1": "3c3db7fa9188376b315f08dec2871c0c5dd9942c",
          "md5": "eb2edcc8185300ef1153088e691d12e1"
        }
      ]
    }
  ]
}
