{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52664,
          "sha512": "9fdeed05ba498b34990a40ad73fde5c0660be3b7c222e215fc459c8f406e7f0d8e38aaa4437f377a60b5ec44ca1be898116f8bf1af1559ec2aa17f88f70dde70",
          "sha256": "c8d94b83fe6d886652c0a12de3c135c4fb7a602560e332b381e3ea26772e8c24",
          "sha1": "4f8bd7cf2ccbc9d213fd59f0f431139df3e68604",
          "md5": "9be894b9a66482a6c500824a707eb46e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52664,
          "sha512": "9fdeed05ba498b34990a40ad73fde5c0660be3b7c222e215fc459c8f406e7f0d8e38aaa4437f377a60b5ec44ca1be898116f8bf1af1559ec2aa17f88f70dde70",
          "sha256": "c8d94b83fe6d886652c0a12de3c135c4fb7a602560e332b381e3ea26772e8c24",
          "sha1": "4f8bd7cf2ccbc9d213fd59f0f431139df3e68604",
          "md5": "9be894b9a66482a6c500824a707eb46e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110432,
          "sha512": "77f3e891453a389151ba3064c14cda674d43099ae4c4b8318fbf15381acf4408b50742ea57fd1c9b701d6d351cdc703ebbb35338316731ac21ccdd65a17d2e5e",
          "sha256": "efdf579d8722f1c073f78e7e9b766dd32433eedb3a34badb8c540e7a012b00b9",
          "sha1": "f2f701ca41661b9a8fb8f674f4867f8262eca8ed",
          "md5": "35f02868ba889d2c1efd9b668aad18e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26634,
          "sha512": "9f1d9663be35eb16084c94de97913501bc7b6ac3c8116100344f61dd56a2bc07d893c53f7e0f72625f64657057264f3e05db625819c04eb5bbf58e4635e20904",
          "sha256": "66ff06922336de1b338ab37f9f04d96ed188ffa2b0caabb2db12491891144d5e",
          "sha1": "9bcc672c3567401917d44af6cd129653959fdfa9",
          "md5": "bcdde1751b87f3700ad919963bb1dc61"
        }
      ]
    }
  ]
}
