{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 53019,
          "sha512": "f2f4e327c86b6e3ebbcc269753dcf1f914439902336c27d17976f269a118f1ab690a91f774f4915ffd7aaddd23564627d920a157e81e773692f94e485b0b8b31",
          "sha256": "849d39da87989d4a58a2ed5b1a808a16e52ecdafb87a4f8fb0aa0542cb11fb70",
          "sha1": "a072b50396d5c559038a48f784ef56aba1727159",
          "md5": "d0fcc2cc4568b7bc2bc2fc11ec6d59d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 53019,
          "sha512": "f2f4e327c86b6e3ebbcc269753dcf1f914439902336c27d17976f269a118f1ab690a91f774f4915ffd7aaddd23564627d920a157e81e773692f94e485b0b8b31",
          "sha256": "849d39da87989d4a58a2ed5b1a808a16e52ecdafb87a4f8fb0aa0542cb11fb70",
          "sha1": "a072b50396d5c559038a48f784ef56aba1727159",
          "md5": "d0fcc2cc4568b7bc2bc2fc11ec6d59d2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "bc0c9ea0cc967039eda3fe55481db82125a21f244d33d0825cee5c923fc5ae0651bb966a9e63acbeb90838611fc1ded49151b4eae12c09f4c927e95979691a6e",
          "sha256": "aa26a37cfa40f12b968d83b1155e7ff192b93ac77f68abdb1692bcd4710d075e",
          "sha1": "9ddd27b080d992b66873840af70630d5991f6dfe",
          "md5": "f7aea759d59dceda2e7a8e1b2004de69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26618,
          "sha512": "910c8b440aeb4afa483e7e3db399f5bf1674b98aad116e1e91db520276c9103e2181bc894b6f5880bae0616b8d049c64e297e4c90c82b5bddf37b75c12a56b56",
          "sha256": "80f4dcbb2cc35c090dfa49cec3ab0253e9c0e5bc57280913b92b04ff4ccb7a3a",
          "sha1": "491180848b1d467efc0d999f8c8012df9c7c1bee",
          "md5": "094770039ca382e49d72896696f5772c"
        }
      ]
    }
  ]
}
