{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52664,
          "sha512": "4e510e2d79b5e65cf791e3346ab8a5c05b98466796d28ef73f0b323da489af8b7dbbda4e91ec2c471b93a68a017ada7a86b00b700b4bc3d7e72c124dc3959dbe",
          "sha256": "3af2d9956265495abd005bd4d4bf53d6910620e949d0793fb54b623fcc498d46",
          "sha1": "7a7dfa6acd9e85532205146c552e28a8df69ccf5",
          "md5": "10127fc3cdb894b663812d195c407040"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52664,
          "sha512": "4e510e2d79b5e65cf791e3346ab8a5c05b98466796d28ef73f0b323da489af8b7dbbda4e91ec2c471b93a68a017ada7a86b00b700b4bc3d7e72c124dc3959dbe",
          "sha256": "3af2d9956265495abd005bd4d4bf53d6910620e949d0793fb54b623fcc498d46",
          "sha1": "7a7dfa6acd9e85532205146c552e28a8df69ccf5",
          "md5": "10127fc3cdb894b663812d195c407040"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110332,
          "sha512": "b742fbd68d10ec91a2780376def625a38ce57cbc652aa3ac713c59dd822cfb5714222b9a42479c3ab563d1570ceea82a5a9ffe8ecdddb5c0d01f865359deecd1",
          "sha256": "9300838dd136800df225973e8e551858f611eb667e2457d975d3f1c416067fd1",
          "sha1": "5904c1211921c16e83072abaac59a0fb0f1ba231",
          "md5": "77e9446b6f2267a5e7edde4095919cfa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26634,
          "sha512": "53c0fee57e3e6b187879312591c7e1627e4d2da3b3a0115315041f213afc8d332fa5e3754caa15a5ff0b59e8a3927491b3d61aa7d122e036c91da43c1c23a1c8",
          "sha256": "1274c347ba90c8ea91b4aeea412842f5c3bab2153f85afa5d64ecea344eb7f82",
          "sha1": "8eeb8163f9a9bfda549470a4c220883f39561cd8",
          "md5": "98b57ed77d5b4ea8b4557e8466eb6549"
        }
      ]
    }
  ]
}
