{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "8065dec5114428efb181ebfb75c0a0eaef135c5e8a718efbc40b72ce266f47e843ee53db92e10d2e39f13b1d91a662d6fd08049c7b48fa330d66108fac258172",
          "sha256": "7903927a05032b3588586d03e4dc08fc7e7fe13880bf7a1269724a72af18369c",
          "sha1": "0a00091a8da36fea9dc1a62bac93bc87207d5001",
          "md5": "d1c0503f4e361f91b3929ea80cbba6a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 52084,
          "sha512": "8065dec5114428efb181ebfb75c0a0eaef135c5e8a718efbc40b72ce266f47e843ee53db92e10d2e39f13b1d91a662d6fd08049c7b48fa330d66108fac258172",
          "sha256": "7903927a05032b3588586d03e4dc08fc7e7fe13880bf7a1269724a72af18369c",
          "sha1": "0a00091a8da36fea9dc1a62bac93bc87207d5001",
          "md5": "d1c0503f4e361f91b3929ea80cbba6a6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 110786,
          "sha512": "fdd992cb406c90af21b945550c68234715135094d1d9ac9bb9f3cdfc0307129b412a55ec5ea149755adf3373d1cf5b9f85afe4f1e9009d50351c0a8807793d38",
          "sha256": "f1893204dfd961a6dcd3d3ea272c7c199d805a831f6e092fc7cdfbe0551040c8",
          "sha1": "960ba12c1b3c6b0aa51ad26d032fd50e47516b59",
          "md5": "a8560043fba4e6bc94c968d60913bc56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26459,
          "sha512": "bfc9bf84557762db4136663d2ac834c8357301153f883c9a5c5957098dc5bdf18c1d80fcbdeab089eef49360e9fa3d28b84f7bf09860b9ae96b73b98f63c9d73",
          "sha256": "d0280a45d5277dec7087e7b40b4a1a7e56bbe31530c17133638bf3cc5f5de7ca",
          "sha1": "44c8a029e504caed6308ac85abfbca707748877b",
          "md5": "4e6420a6a14b3af11a300d6390a0f2e4"
        }
      ]
    }
  ]
}
