{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 57634,
          "sha512": "f0e6b5f75cf84c0e83a735759a18b2d82042bf7bad528751370658d4c821d325ddc06ba602c4d89f454c6d85d0378fc635faa1f884881024e081c545125b90a5",
          "sha256": "f3feebaeacd21cde688c6475463d47422d6b454ba93aa0a4c5abdccf37e07023",
          "sha1": "5abecf5bbd31715f46ccd367efe8da6275035eda",
          "md5": "5eb014be14b882663fbb57d0518e1745"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 57634,
          "sha512": "f0e6b5f75cf84c0e83a735759a18b2d82042bf7bad528751370658d4c821d325ddc06ba602c4d89f454c6d85d0378fc635faa1f884881024e081c545125b90a5",
          "sha256": "f3feebaeacd21cde688c6475463d47422d6b454ba93aa0a4c5abdccf37e07023",
          "sha1": "5abecf5bbd31715f46ccd367efe8da6275035eda",
          "md5": "5eb014be14b882663fbb57d0518e1745"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 169315,
          "sha512": "0cfb035ceb7e285d79d672fae1988a2ce86b61a83ca65d761474821c5fbeb425abd2676e7ac4a7eed2e896bb5fccadea3467c16188de8b1143fb497253ed2c2c",
          "sha256": "3c62aea9963d1881bb2adb98beba3373d0babe7470150aa15645631c6205eea8",
          "sha1": "8e320107425651278e46badaac50ef7985b17726",
          "md5": "ed7669d455940b25aafac44300539f8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 27486,
          "sha512": "20a230fb630819ec79a54f6ed1f5469f72ec509c321cca51f605f9d47109b2f3a9883f30ef853aed70c4571401eb3996b38177c9b3a620b30e622d6826d779d9",
          "sha256": "f673f9ee208e6a1750deda7125f8faef8eaa8cf942d4bdcbc64393e217c20cc5",
          "sha1": "a155395c0d9a66d8471f94137f83d2f93306e1d5",
          "md5": "31c4aba2a10050a44df9f320d25eaca8"
        }
      ]
    }
  ]
}
