{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51849,
          "sha512": "d05483fde40e5edf374ef10740c421642c8f72a1d63a178a35f6e998f7ce680ffa261650104e9aca873f8ddc9929566316079f4333b08f32f4f578a59eb5d8f9",
          "sha256": "be8d361bd12f35608e5c73c3793805e8c7c2f7022ee309945967c002a73a3ba7",
          "sha1": "221f2c371ed285586462d9537b8d17bfcb396dba",
          "md5": "11eed2d3c989b16da8a0791dea502933"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT.jar",
          "size": 51849,
          "sha512": "d05483fde40e5edf374ef10740c421642c8f72a1d63a178a35f6e998f7ce680ffa261650104e9aca873f8ddc9929566316079f4333b08f32f4f578a59eb5d8f9",
          "sha256": "be8d361bd12f35608e5c73c3793805e8c7c2f7022ee309945967c002a73a3ba7",
          "sha1": "221f2c371ed285586462d9537b8d17bfcb396dba",
          "md5": "11eed2d3c989b16da8a0791dea502933"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 99265,
          "sha512": "eae2b348a5d8df1f3f9724a3e3467b4865e9e5909353901aa058851ca61259a52f9cf88a8fae3330a54e75eda3ebfe554c68b99e8bc399c443d9c3627ab36fdf",
          "sha256": "8739ff6e10646ed3ee2842a0eccb705b878b3ab58880fbfeb216b42d77dc8cab",
          "sha1": "f71c1aaa8982a87ef73b10736d9f1bffdf642044",
          "md5": "4323ca474e10c1256b9c214e8a30513a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-autostore-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 26413,
          "sha512": "f6668385caadfd71e6597ea8db4e155aae50cb15a970aac5d18c26c0753ea00d0c0f8642b31909d24c225789f637e5bc67e963dc8779e99ce99ec1ec7e2e1163",
          "sha256": "fd0964a602b453aab1902006caae775d91cb2eb82ce4e2f30d01f8b7c07b48f1",
          "sha1": "afdcbe0277b243e0a404a4691db9167b582ad24d",
          "md5": "dcba03bbff8bcdc1a0e580aa7eca860b"
        }
      ]
    }
  ]
}
