{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "5.2.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.2.0-rc.1.jar",
          "url": "box-notifier-feature-5.2.0-rc.1.jar",
          "size": 7510,
          "sha512": "9f07407245918b78ae775f20c18c91440263c4d62649e367f12b3a9844ea19c37df57fc0a9862227b8f419a786e0e19e08e3ad4600e0620422c4f2e082d9ee2b",
          "sha256": "6520b1385684dd229e81005e80457ed545e293389b5f16edf10ca6955f398d79",
          "sha1": "9975ce67a1a6273dcb259abc344aa17e7ae4156b",
          "md5": "fefe57a70a0d9d549d61895e18f545af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.2.0-rc.1.jar",
          "url": "box-notifier-feature-5.2.0-rc.1.jar",
          "size": 7510,
          "sha512": "9f07407245918b78ae775f20c18c91440263c4d62649e367f12b3a9844ea19c37df57fc0a9862227b8f419a786e0e19e08e3ad4600e0620422c4f2e082d9ee2b",
          "sha256": "6520b1385684dd229e81005e80457ed545e293389b5f16edf10ca6955f398d79",
          "sha1": "9975ce67a1a6273dcb259abc344aa17e7ae4156b",
          "md5": "fefe57a70a0d9d549d61895e18f545af"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.2.0-rc.1-javadoc.jar",
          "url": "box-notifier-feature-5.2.0-rc.1-javadoc.jar",
          "size": 95692,
          "sha512": "727269a2bbb611911f3f291b0142b5bfe1e2e2f81c84577bf5638485f4d81766bc1d8e9fbe822bcbc0d13d11722237db282dd2f7d409450bc7f40d82eb5b93b5",
          "sha256": "e557a75557912adee5597549e638741e611a685eb644955f5876062965ff4fd3",
          "sha1": "2f0b5b25318c96e53685a7f2d411d1984df1bb79",
          "md5": "e8eb4ebadc3a1b7d26775360ae873f8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.2.0-rc.1-sources.jar",
          "url": "box-notifier-feature-5.2.0-rc.1-sources.jar",
          "size": 3874,
          "sha512": "f02db86366e9c038e380845f09e881847194f3ae67dcdb11e6faf5848df24e49e985c104349a55116f12fa6a639771fd553011035bce5315bd95c1260b2bf4d1",
          "sha256": "faea318ccc10e19656c1a56d84b7f78304751eda30de02b1b541afb7fe3fc944",
          "sha1": "4fad711f7ed5bd8a17ab5d06300c006a6fbf986a",
          "md5": "9f2c010061eaf2eb4d073406db27c084"
        }
      ]
    }
  ]
}
