{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-common",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 15543,
          "sha512": "f43731bd5cc7328e622bf14926299200f29d3b2954a998fac7b475149c14e1d89123dd90e961e6420422e93b12a5061c01b3ea40b35d51467f04532387e66915",
          "sha256": "bae10f09004b1f0e85588682a0d4a4137d1ff63fa77a96a10c1d18683e3f5b0b",
          "sha1": "5a80c6c84e04dc5536560634b9d7a0828332341b",
          "md5": "3499788e4f0eed830e09212af3a5cac3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 15543,
          "sha512": "f43731bd5cc7328e622bf14926299200f29d3b2954a998fac7b475149c14e1d89123dd90e961e6420422e93b12a5061c01b3ea40b35d51467f04532387e66915",
          "sha256": "bae10f09004b1f0e85588682a0d4a4137d1ff63fa77a96a10c1d18683e3f5b0b",
          "sha1": "5a80c6c84e04dc5536560634b9d7a0828332341b",
          "md5": "3499788e4f0eed830e09212af3a5cac3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 113804,
          "sha512": "91908f42308aa236f9c6a2103de171f0b63547dd4068abd409d3b5101ad4a6d661673b4b736d0d8642e6962263e562112078c333f112781891f2f4767c4bec05",
          "sha256": "c487a8596230dc03bf324a56ec78400abbc4b9465c416e914594ae83ea678fdc",
          "sha1": "2c53aa9e48cf11b061f1dba77dade0c877b3c66f",
          "md5": "9e282d7149e1c960aadad5747bea938f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "size": 6726,
          "sha512": "1c9fd22f0d4b69ed48b476a63afc3a1b19105fd56a843e7cf82a7e3b89d9b9c95919ecba8f399868b4a906dea08e2ea73f47c61453cd759bbd58f4023b63b945",
          "sha256": "078e551e4ed448644a63f0d0f8140c5bfe928f0cac0e46f092c30de520cfd373",
          "sha1": "8deebb30fb7e2e4919660b3d0867f31f52e972ad",
          "md5": "2eb14c52383e803d5ac692228b3bce5b"
        }
      ]
    }
  ]
}
