{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-common",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 15973,
          "sha512": "1c154f1b809c1ece457fc3e009c7ea189e6aa3887faae60edb7d176a0227446910240bc77f8a06d7d43c0c0c2add800a12005b3d9afe37c7fe7bd58d83a2e120",
          "sha256": "47219f6a9609ad13f19a8b54af8289d896997d009db6339e241bf0c412364255",
          "sha1": "68af0f644d8517854db6089a2fe01717dec84452",
          "md5": "0510330990ffa6f237eacb63c08da03e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 15973,
          "sha512": "1c154f1b809c1ece457fc3e009c7ea189e6aa3887faae60edb7d176a0227446910240bc77f8a06d7d43c0c0c2add800a12005b3d9afe37c7fe7bd58d83a2e120",
          "sha256": "47219f6a9609ad13f19a8b54af8289d896997d009db6339e241bf0c412364255",
          "sha1": "68af0f644d8517854db6089a2fe01717dec84452",
          "md5": "0510330990ffa6f237eacb63c08da03e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 115986,
          "sha512": "b5f6d08d2397045dfd6c221b65f106bcc8d252190531aa118e6ccc49ab602166a60792e1d8c98367706b6435c67d55c4476f6b0e6380ea85e878939405943785",
          "sha256": "c86fa7f32fd33dada6a0b2b787e789d47808099acf90457447384725ecafd1b2",
          "sha1": "3153c280b95c76f45653876b65313296339fedda",
          "md5": "49228686502397d7f26096e4d5f74759"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "size": 6447,
          "sha512": "e4e03f91eece410b45bc8bb95d63d9ac117d7b5198bcf834b93ae8ee904d62ab6bd6cbfcb354ef0a318c7b78fac757eaedda77ae995c8d2d4f4984c58ced6181",
          "sha256": "63574ecba24c153b3d586d0703764ce06116fabf19a14961c52c6b86654a2c87",
          "sha1": "7d11b63d560c4310bcd945721748011870432e67",
          "md5": "a25d34bf20987333a4c6a6b71cc1b8c8"
        }
      ]
    }
  ]
}
