{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-common",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 16268,
          "sha512": "d6857325589d9fa7fb3851244aece58fa21043b4204dd2788e769a18c472cd309efbf346f7286fbc95527a88a9e0e2052b415761794979bd9dc4c571cb7b70e6",
          "sha256": "aa9623d427e11e5f2434fe72ea9c6898b4929f64b314fee1e447db84945dc176",
          "sha1": "ab1406b4454988148d96621dd8e70e9e6514fd6e",
          "md5": "cd744fc1bbe83908d5add244367d7e11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 16268,
          "sha512": "d6857325589d9fa7fb3851244aece58fa21043b4204dd2788e769a18c472cd309efbf346f7286fbc95527a88a9e0e2052b415761794979bd9dc4c571cb7b70e6",
          "sha256": "aa9623d427e11e5f2434fe72ea9c6898b4929f64b314fee1e447db84945dc176",
          "sha1": "ab1406b4454988148d96621dd8e70e9e6514fd6e",
          "md5": "cd744fc1bbe83908d5add244367d7e11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 119398,
          "sha512": "cdb2ed32a5c819fa623e2a6e212295385c84a79613e0eb09e12d96a9109fa9ee000862327762b3471fc1b2aa41c1813ddba56844ec3fb56351a619dffb86ff5f",
          "sha256": "ba627c388f613f7f938460b9964eb26dea81350f226e2b8e5f7cfc8382520a0f",
          "sha1": "2a22e8cae5cbbc4a5b79e0b3c9e8a16a7f582c9b",
          "md5": "eb8585d4330bf7601e13b16138e14b26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "size": 6968,
          "sha512": "402c4fc0bb62f2ef05193c69c2c1dd1a757b9851e1f7cdfcdedc59163239bb3d09e870b7e32b50aaa416ac78a083e514b7608d44e07ad4f63460c3547a1a3c93",
          "sha256": "dce175ded66202dc5d9bfe7c2d4b65677282b009e88e66c225bc3e95c94d7048",
          "sha1": "d598cd3388ee2bc965ffc160f94d3598fd5334ae",
          "md5": "0d0b2953d61894b817fba8f5d71aa32b"
        }
      ]
    }
  ]
}
