{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-common",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 16339,
          "sha512": "863db4653d3b18a0ededa92cf93c33f13026256e82ef6611364e7f049bca4722831c7643044974e806dd09ba6ce75347ff157e51b14aeb5807c7f19d0dd1dcac",
          "sha256": "973e20e47cdb537070157a47261c1335dd2b166ac713092f410aa3c1fae32637",
          "sha1": "14a64c00198a9419acdc316ec9ddf35ea24f5e1f",
          "md5": "43b304af5ebc4f5a6476ddf56755f087"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 16339,
          "sha512": "863db4653d3b18a0ededa92cf93c33f13026256e82ef6611364e7f049bca4722831c7643044974e806dd09ba6ce75347ff157e51b14aeb5807c7f19d0dd1dcac",
          "sha256": "973e20e47cdb537070157a47261c1335dd2b166ac713092f410aa3c1fae32637",
          "sha1": "14a64c00198a9419acdc316ec9ddf35ea24f5e1f",
          "md5": "43b304af5ebc4f5a6476ddf56755f087"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 101824,
          "sha512": "949d584dbc47935126a561723d369ba1c035bf4625d9a6e4c13098b7bd6d0b066cd0807f4b8675e03d76f34c6f7dc43e4f5c4fad529f38a945e1a5bdfc49fb34",
          "sha256": "c9fb3e9a0a01598ccb51eebc47c7b4368f4a5816391b037fd3d5f96cab5f7d10",
          "sha1": "8102b6366df455d1f45f3148f12941330a8b3765",
          "md5": "13aa5845b79650c4b0b0873dc1b346ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "size": 7276,
          "sha512": "9a20aa049f6c6454be730aa59bc3ba1c8734c1771259fab526dafb43b48e61f095679c4a3b27e8ec053c36ca85af78790f3ca884e1c6a4c1b5dabdd1ae3d84b7",
          "sha256": "3d88794297755d6bed9c2d16ee878c1a23034be6cd859375540e3ac7e9b55f68",
          "sha1": "7c22132dfb1fbdb6f31c8010e5dda3615360d700",
          "md5": "0a15c87abce0839d50230812bca11c35"
        }
      ]
    }
  ]
}
