{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-common",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 15257,
          "sha512": "8a07f43608671c760414fd334762a697e5015d0f5341d7d0999fc6cce74453aabd886525b4645e1b7f1a79dc98da5adb4cd0f68b082c0a4b321f9732bf4500f0",
          "sha256": "242ead8ffd790591fb4da332f8c8a47cd1ccdd8c5961b4b28326e2060cae3d49",
          "sha1": "453c0c9ef8c456463f3554c39a562202ad1d996c",
          "md5": "5dbb6351725339660300692d9b6194bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 15257,
          "sha512": "8a07f43608671c760414fd334762a697e5015d0f5341d7d0999fc6cce74453aabd886525b4645e1b7f1a79dc98da5adb4cd0f68b082c0a4b321f9732bf4500f0",
          "sha256": "242ead8ffd790591fb4da332f8c8a47cd1ccdd8c5961b4b28326e2060cae3d49",
          "sha1": "453c0c9ef8c456463f3554c39a562202ad1d996c",
          "md5": "5dbb6351725339660300692d9b6194bd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 116455,
          "sha512": "b3737c72f6e96efdabbf4d6b1321255d7eb4d2ec13c374a19ff19948177affe887b4386cf71ece98c5302fd09e16e900de7024dc4989f650a76bb7dc453e0377",
          "sha256": "9e8e82905371837a27620c847a95597331240a49b7dc3d151a509ab0b41fc97b",
          "sha1": "7941b1171281e0e6bd0477c6a502cadd2fc6affd",
          "md5": "431f34be5a5d9bd9e325955cecbb1ac0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "size": 6217,
          "sha512": "38c0345633d8a4ed7279fce542806ab7efb5ba05b37fa8550d00b9778668b08ce1ff7ab443dcc605c6986bf3a9ceefff35b8ff6180118c73869c17fb57b59acf",
          "sha256": "06ddffcbee3930e664606cee4c39d93196330f8591bc72d1ee8bf2d0170ed5d1",
          "sha1": "964ba38c2a04d9e6514c15be284fd375e4f0594b",
          "md5": "ffa09d8fda4be817fd76cdec6d3e8d93"
        }
      ]
    }
  ]
}
