{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-common",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 15543,
          "sha512": "be78a14681383789feef8cbcf88ba3f65757730ca3fdcc0d1002dad8472ae3b41073e0a9a90c1973cd97ed530ad6193a1ec14066f62513c12bbac497562834ea",
          "sha256": "470ac0d8f8f25eaaf0ad0fda51b8cf9e5dc3b203c0a79b5ac76fbef0b163ba41",
          "sha1": "055d0c247a200ca8d6d5e6f26eb718ae9eda5be9",
          "md5": "0f5531e5580d397568a467d41239480a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 15543,
          "sha512": "be78a14681383789feef8cbcf88ba3f65757730ca3fdcc0d1002dad8472ae3b41073e0a9a90c1973cd97ed530ad6193a1ec14066f62513c12bbac497562834ea",
          "sha256": "470ac0d8f8f25eaaf0ad0fda51b8cf9e5dc3b203c0a79b5ac76fbef0b163ba41",
          "sha1": "055d0c247a200ca8d6d5e6f26eb718ae9eda5be9",
          "md5": "0f5531e5580d397568a467d41239480a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 113804,
          "sha512": "f351b87200bcbcccdb5e0d9cb8d8216ca9415ae16de5329e0a7c11a480de95f058d9f38acd3e250512cd08eaf17eff08256f7236102bcccab0587c7e109fe693",
          "sha256": "742c09510d292c511a9bdaef40543855297f78610c1784df5620ce55161310b9",
          "sha1": "f4a777b262c7c613496600d9d92f1cade266d6cc",
          "md5": "7ce847a983c55b5fa60cf04be27fad66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "size": 6726,
          "sha512": "25011ca2a1509135cde389ad510b205f5688ef5de0c5ab4d80fe30fa0087da6de24dbe61ec16ca14818b06c8fcea6662b04acf408b2a015772ad55b9894e5881",
          "sha256": "7889929e865c9d142d047b836c09d2ec10a41c5c750139884e3fc78718e53e02",
          "sha1": "7a1a254cbe8e4ba7a42db07fb66198102d9b77fb",
          "md5": "6249b258eb7b80da5b119a1c8e5e36e0"
        }
      ]
    }
  ]
}
