{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-common",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 16339,
          "sha512": "860857cd64fd1d453d270edb895bd73f8c08b1e07f4313fba782cc6574816b1b2e92eaf039876bff17ce395e03abfc1cd8fd085fdb415f5bcf4c22dd3a7eedc0",
          "sha256": "abecfb5aa224bca493c413c210ff2a0d645f9ef2293cc59618e69d54448e2f98",
          "sha1": "f6929a41de41849f718c0225e94dc495b1aa86df",
          "md5": "6a3bc41d28733ede0cc03229f9930bc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT.jar",
          "size": 16339,
          "sha512": "860857cd64fd1d453d270edb895bd73f8c08b1e07f4313fba782cc6574816b1b2e92eaf039876bff17ce395e03abfc1cd8fd085fdb415f5bcf4c22dd3a7eedc0",
          "sha256": "abecfb5aa224bca493c413c210ff2a0d645f9ef2293cc59618e69d54448e2f98",
          "sha1": "f6929a41de41849f718c0225e94dc495b1aa86df",
          "md5": "6a3bc41d28733ede0cc03229f9930bc2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 101824,
          "sha512": "dfb8e07c70c7b5cbe10d7e5cf2800fad3dca86622b00e226f193999a5f0b2f9452e14adab76df6be6fc07c6511e99dd39e09a2224c288aa37f394845f18f64e5",
          "sha256": "43cac793333dd1626a8f4bbf8745b63a10ab1dcce132d580d681c1fca643a8f7",
          "sha1": "94bcb1dc0927ad6599daa833ec1dccdb598b00f1",
          "md5": "9c5b493167c69436b5b71d8133317820"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-common-6.0.0-SNAPSHOT-sources.jar",
          "size": 7276,
          "sha512": "16e1f83b8687690479453935381357ed7c5fc750062a6d2c93790f6a53e42c49ae3aeeb091d4041ed96f4af2be55e8d3928feb551f11a0dfff9a8ac38be1daac",
          "sha256": "268ae18ce4b2453ed903434c2a89fe92b331e5a3857c9dc578b862904359326a",
          "sha1": "a42714efaaa2be74b3b68f57bb2917f09b42e6d1",
          "md5": "eb9976f66313299a252159bc5ad084b9"
        }
      ]
    }
  ]
}
