{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "gui",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gui-4.3.0.jar",
          "url": "gui-4.3.0.jar",
          "size": 68480,
          "sha512": "07bf1e37912c6826f08fd986b5c4c9cce548da155ee8a9137ece21262a188fc534a00cbb13af4bb139183d01e8c25eb8aeb1d605209794846ea4ff73644ae16b",
          "sha256": "7826700b7a36cfa2ba0d0dbdbe27f778482930cc26ff6457c9dc9c26e36a3f7d",
          "sha1": "4c408ecee8538f077e3f18c7ec30de8f66a48df4",
          "md5": "3dfa0f24f718f084330384c13d01da66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "gui-4.3.0.jar",
          "url": "gui-4.3.0.jar",
          "size": 68480,
          "sha512": "07bf1e37912c6826f08fd986b5c4c9cce548da155ee8a9137ece21262a188fc534a00cbb13af4bb139183d01e8c25eb8aeb1d605209794846ea4ff73644ae16b",
          "sha256": "7826700b7a36cfa2ba0d0dbdbe27f778482930cc26ff6457c9dc9c26e36a3f7d",
          "sha1": "4c408ecee8538f077e3f18c7ec30de8f66a48df4",
          "md5": "3dfa0f24f718f084330384c13d01da66"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gui-4.3.0-javadoc.jar",
          "url": "gui-4.3.0-javadoc.jar",
          "size": 267447,
          "sha512": "2d3a05f0f424c8f9742f398ca5e744a726ee67b549df27963f677fa50d067577c7e5fd64ded22bcb33af84b6ef9004de52aba4906b320410805a6316efe3a27b",
          "sha256": "3ca2057f0d975c13a99e1dfe3ef224734a77d9a4ca389b6ab9399bee6f82153a",
          "sha1": "b8d7e1f78092dc27b0e00d7b94776579f83ccdd2",
          "md5": "2b36aa0b43a306e37faccf9424724d98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gui-4.3.0-sources.jar",
          "url": "gui-4.3.0-sources.jar",
          "size": 32825,
          "sha512": "d9d54b73629ce0a7e594de6d0b6737dc95200b78a7b44447a55df61470529030a450b10d987eed0dab5aadb9d5c49aa6b12c511852549fda37efeebf61e0b449",
          "sha256": "a6f1d4e8ba6454fdcf09af244fa0289a23d9ed8b851b4d4e8420153ba79bf16c",
          "sha1": "71a2f472c954b9ce33fa6ec3fd94514a2e7bceae",
          "md5": "4489a96d769db23278da7e775383f269"
        }
      ]
    }
  ]
}
