{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "f90e25d612b3a4a13a23dcd836927e0fcbeba45fa6e5dd6da14ee571a84581b77b64bae22f8e836201d6f043e09af78566ea52b49b6a34fbebf62e243970e184",
          "sha256": "9997a52d58ea013c980edd51d8bd92374ef7782c278096880da1a09e23f5a2ed",
          "sha1": "08a40e90125fd399323cdf4f73e7c63d3d9f1e79",
          "md5": "1d5253eaa054d84ac97fad6af3ea8187"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "f90e25d612b3a4a13a23dcd836927e0fcbeba45fa6e5dd6da14ee571a84581b77b64bae22f8e836201d6f043e09af78566ea52b49b6a34fbebf62e243970e184",
          "sha256": "9997a52d58ea013c980edd51d8bd92374ef7782c278096880da1a09e23f5a2ed",
          "sha1": "08a40e90125fd399323cdf4f73e7c63d3d9f1e79",
          "md5": "1d5253eaa054d84ac97fad6af3ea8187"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106550,
          "sha512": "f3592e0ab9049d248268499e2116c617dfade5906429856ea67aef4a65dd3c58099963109e687b53eb8f78a00b52b1b43c8dd9c1d13672f2db8f482203dd461c",
          "sha256": "405a86260da2355f7a79d2bebc4169b487ae8f092e8f23a289caa271f85882b6",
          "sha1": "91a165b9acab2c7e38d604af644e7f7da0df0815",
          "md5": "c64e5ddd817a29a57abe275bedd9f304"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "18aeb38fb9aa9aaddab5dccee8383f83f0837c1f49396f03ee04d78cd29d0fcc7b32cbed9702d1cc3d9c47428464f7a65ed45bc016dc6872402e67f173945ae4",
          "sha256": "6c29aced9b2cb72926d5662dc4a51b798568f48ab4e9c73947c357fd151e8ccc",
          "sha1": "2afb26761434cddefde0a4ef09342da287a6acfb",
          "md5": "78efa4ce00e3bd6673baae5d170d2dc5"
        }
      ]
    }
  ]
}
