{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "d49ebf6f713e3d9974956b04f73e934f69e4bc0694948f1a787fb06c878a59e940c95616d1b7b725b76a083b1cc9274eb8b8a9559ba506eb7e94c2de46431322",
          "sha256": "639561cc3cd49a1bf83affa476d564c92c17c6db4ea0123c9852be3939de43fe",
          "sha1": "f4297574a839b0bbe54e1c59c89485e6196c6d96",
          "md5": "fe874399539e71b6a5dcf9cb5ed5c302"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "d49ebf6f713e3d9974956b04f73e934f69e4bc0694948f1a787fb06c878a59e940c95616d1b7b725b76a083b1cc9274eb8b8a9559ba506eb7e94c2de46431322",
          "sha256": "639561cc3cd49a1bf83affa476d564c92c17c6db4ea0123c9852be3939de43fe",
          "sha1": "f4297574a839b0bbe54e1c59c89485e6196c6d96",
          "md5": "fe874399539e71b6a5dcf9cb5ed5c302"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "55cabc2cf8d94c36cc7519d31655fca4d72089c63f67443a8d73f271e93b96fad80d44e758028d4c45e4d01487811782371da6fc5278f4ec80429a06fc8f7472",
          "sha256": "9ca8b593b32b1d8d1e6a40c101d851bdde9d0c376e263d9c7a015bb460160204",
          "sha1": "907c150f9fa11cd30a86a9263990e5f7b9765e44",
          "md5": "6942b33d05b5f8831f79db5eee19e8a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "1b7b0448d7a0800c36cd2e7d0e369e17c7c8942ed038700c56149356d40733b9187161daae7b1bfe2a85ea18cb3e74eddd722f5055ba6d61a8247a740c3510b9",
          "sha256": "c85db0b617d8be3c22d342a488d1ed9544cbe886449430855f0f15fd966750cf",
          "sha1": "8fb1e7f66ee0742500458470ddb69e49ee76cb73",
          "md5": "c5aa3b71dfb203256b01365ad39d244d"
        }
      ]
    }
  ]
}
