{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "ec0a98c38eb99d7eb67a4077bc943ae5871b49091f93fb9f534d4f6dbd5cdc5ba7df216a546cf092b2d2751547b66c71d05780ad81921012986f42c5b71d2e71",
          "sha256": "aa838392176a99c1293c47e62cc944fc81c21056f343a56479b8fb10c9019aed",
          "sha1": "014388f07f80010ae0718b8adad5e80668f4735c",
          "md5": "cc9c76a16434aaacc3c6eb9ae9589a87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "ec0a98c38eb99d7eb67a4077bc943ae5871b49091f93fb9f534d4f6dbd5cdc5ba7df216a546cf092b2d2751547b66c71d05780ad81921012986f42c5b71d2e71",
          "sha256": "aa838392176a99c1293c47e62cc944fc81c21056f343a56479b8fb10c9019aed",
          "sha1": "014388f07f80010ae0718b8adad5e80668f4735c",
          "md5": "cc9c76a16434aaacc3c6eb9ae9589a87"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106550,
          "sha512": "b1cd08a78c18dea3bcdd7ce274c14a253f2dda8293d038bbad63b53fad44126c05fdc5ae8d2c5bab17527b671a7b18c7f54c4c611f3b6fc5ff022840885d418e",
          "sha256": "da91bffaf09b847fcf93ea9272d6cf618ede712fc85539294ca54147953230c1",
          "sha1": "f92a6e07a23ac32656ad0ff0a37013a5e138be3b",
          "md5": "8e556c15ccbb784b1c8758be8bd71803"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "e927959594c1d285dd5611051ea9d25fcf514c1c4f879c26511a2fa36e8f5eb9de36b17066f5b2eb0dc9f66b3a68dd74af37298abefa3cdd3f7dbe226db7336c",
          "sha256": "78d134b998bda37a0517fb0c7ea19eeb0cb531e50ea1af500f45519a0f28387d",
          "sha1": "6f253e48573b5a391999506a38de701d954e9b1f",
          "md5": "1ac457f4b45f8a57914ea9aac5656fdf"
        }
      ]
    }
  ]
}
