{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "d0d5a7b1594c096c055aa35c40e939be8bb5cda723dec71edbd15991440f44daf19b88f544b2cdbaeed9336159550431d479019bd0d540ae42d4c86f5edd8037",
          "sha256": "2c627bddfadd606c2e2a20785bc6b26bbcefd958994839c5256e2ff1678202e0",
          "sha1": "56203125dd39151d1bbd1761c176a830a3f8c2a6",
          "md5": "721658c9586d65be6805d01726537cb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "d0d5a7b1594c096c055aa35c40e939be8bb5cda723dec71edbd15991440f44daf19b88f544b2cdbaeed9336159550431d479019bd0d540ae42d4c86f5edd8037",
          "sha256": "2c627bddfadd606c2e2a20785bc6b26bbcefd958994839c5256e2ff1678202e0",
          "sha1": "56203125dd39151d1bbd1761c176a830a3f8c2a6",
          "md5": "721658c9586d65be6805d01726537cb6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "e2fb0660a3f3a55a72d9781c953aaa9da7957518de7d86d39b95f45cd62007d476fee5f80c1cff9da58f791c4716abe8d1797685ffe66a6506c3b289d27e3d02",
          "sha256": "ff37ce094f239b62887c2b753f2cceabf7b77962332d1beed54bdabd83d58c2f",
          "sha1": "cf8cfb2d146102510c51dafbb8f258accdec1459",
          "md5": "0eaf46feb2ebd5be7ed904e31166dd71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "3a7671c3702bf6230c473d570e916a26f1c4c07bb8844200aa286f499cfe81f5efaf2b557a830da966ba0d4f396ae958e6b9765fe808fafa7360282c31a0bfe4",
          "sha256": "a961e6959300e10547e3261981596d94b00dae7976d35dd1107287deec1fbddb",
          "sha1": "8824ef3822cfb6dcd3f70bea3fcc45bede736c16",
          "md5": "1a0cc085db7867152a2151273fa76ce2"
        }
      ]
    }
  ]
}
