{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "df54db5369161f78a9dc9195c1df0c5e00c8eb0d242ced0c249daaa6b54c5d6414a59dd8a75e5c84f2dc5e556da4eca8aad7fdcfb21a508ee392efeffcddd8e1",
          "sha256": "d3ddb332b57264c48ac64e499118558b2b0a5208a69d1230d1a5837667c65e79",
          "sha1": "daf14389857c4bef5db4806f1ae094657b4a9b34",
          "md5": "caebd26e22d358a362d4aebd60d9dddd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "df54db5369161f78a9dc9195c1df0c5e00c8eb0d242ced0c249daaa6b54c5d6414a59dd8a75e5c84f2dc5e556da4eca8aad7fdcfb21a508ee392efeffcddd8e1",
          "sha256": "d3ddb332b57264c48ac64e499118558b2b0a5208a69d1230d1a5837667c65e79",
          "sha1": "daf14389857c4bef5db4806f1ae094657b4a9b34",
          "md5": "caebd26e22d358a362d4aebd60d9dddd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "0e1171d07b174b00f70bd213d9f4042d2f91c74f6cbc6fa70040a8c282dfc98f4c809c15409711ed488b96ea630077630e300acd6240885e65d6ed0d7cc89122",
          "sha256": "4ce06a7ac5f53c60def489dc8983581b5c244d84fa0c3b3e0faaadf85a6a6afc",
          "sha1": "1a5d4553de2a95515e0c5f5744f6980c4c64284a",
          "md5": "f4d26f438845f06119f2e446cfb7cae1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "2d58b19882f020c33bdd0180039c406d69958bbedeee55e438cb0efc030cfb26d162df0d0778e121ee57dfc53aa4cbdb2457b9708c87313bbca7d31503637822",
          "sha256": "7d38eaf4d371350eb3a80d336e0ff048fbe5390ae1db13d29f4e5b5ee406cf3f",
          "sha1": "a7dce5050f6a8909f10a1601dc099ad3ec24ccfc",
          "md5": "c62445469f321600980f025f4cc48c73"
        }
      ]
    }
  ]
}
