{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "6266e60eb23919743339c13e5d1fd4816dc0b8545a1e3d95adf351a752f6ccae99ad644f3833f4d97ee86852bb258f77910f5317cef7cb876fa1244fc5035b5c",
          "sha256": "145cf8ffcc748508ec58eea657892b2be4d318066337129e40d4bd6205948707",
          "sha1": "a54134950d17a66e14596194805e232b3075053f",
          "md5": "3ec3aeb80ccb3a71a60c825fd2034a2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "6266e60eb23919743339c13e5d1fd4816dc0b8545a1e3d95adf351a752f6ccae99ad644f3833f4d97ee86852bb258f77910f5317cef7cb876fa1244fc5035b5c",
          "sha256": "145cf8ffcc748508ec58eea657892b2be4d318066337129e40d4bd6205948707",
          "sha1": "a54134950d17a66e14596194805e232b3075053f",
          "md5": "3ec3aeb80ccb3a71a60c825fd2034a2d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "246efccc39720e4afca611fbaf028a1bec98ffffecec4afa0066703aefec02a58d5f83c8bc6af28e1f953567c178feec5611714b15e41d8246227a2d30c59bfb",
          "sha256": "36e5ef605bac24e0f08cc75cc8d4f8726049e337386da6364122e2ef5bcaaaac",
          "sha1": "82d53366861a728080082607b63015b41810a768",
          "md5": "f3357724abd1d4706662b698c9f92193"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "e97959efa841f0466cff9bcbe3c4d3ffb3c560ba7cc8db72438d7768d98a148586f8043624966955fd557562f361cdead5f8d341baf1aedf35291d46de5d7daf",
          "sha256": "f4b01b3604272217d72523480b7a7a9d1515c686fac77203a820458cc8025c7b",
          "sha1": "ba5462a749d855d5f8d80dfe70b6fe681f0b36a8",
          "md5": "2b735ca39ed7ff16459b3afa05dbe362"
        }
      ]
    }
  ]
}
