{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6224,
          "sha512": "ffbe667ceb5e58239721fd6d7b51c79434c5f40e6e8737fa112f88b8bccb51bcdeff69d469a2d89f2a19dd609fc5b27f29122ffcbee6bf251c0f857f06df165d",
          "sha256": "4ffb337a92dbf8e478f9bfbc637ce4ed84cf884e4dfcf6b927b47afb07971676",
          "sha1": "e7f44d1733fa178472547adbe7ee0141e06ce3a2",
          "md5": "01ee52a4c2d86ad50f3857f7dc249f7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6224,
          "sha512": "ffbe667ceb5e58239721fd6d7b51c79434c5f40e6e8737fa112f88b8bccb51bcdeff69d469a2d89f2a19dd609fc5b27f29122ffcbee6bf251c0f857f06df165d",
          "sha256": "4ffb337a92dbf8e478f9bfbc637ce4ed84cf884e4dfcf6b927b47afb07971676",
          "sha1": "e7f44d1733fa178472547adbe7ee0141e06ce3a2",
          "md5": "01ee52a4c2d86ad50f3857f7dc249f7c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 95713,
          "sha512": "daff368c22ea96359e1b8fd985f626943430d72cc521cc3f17306f5b9687a46599259030a5cf4d62fb790a5d1c0f71397ee88e24090381d219d5dcadce78ca8f",
          "sha256": "1b2c02b647c5cd841b1a98730bf1aa3b30bca03d4677a0135fb876eac165c632",
          "sha1": "cb2df5904eedce3ff95dbacde97958ce0923541a",
          "md5": "9bffca01e97684c65b243eb63fa64ed6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3467,
          "sha512": "de8b56ceba6cb9107d92cd473e91132302616a51e540428320c3c0fcbd651899097536075be48770c89b46a87ed826ec7cb6da51f090c71ab75bcc2ce75f70eb",
          "sha256": "6238222bcf01bcb0ef91529ed0871c64c796f11ffb8413860e8eeb5a549e82ba",
          "sha1": "f611f2a3df66688d54488d721ce218d770f8b23a",
          "md5": "453c8abee3b4b9e15552595c6146711d"
        }
      ]
    }
  ]
}
