{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6224,
          "sha512": "0fca8b325eb4b8a8c34a241442c14166d7a1941b368e2f75000324c24d9210e9949e9396a47359b6bfbe541dc95521fec8a6adf4ed2256361376312a0e350fab",
          "sha256": "11a7379e763e8275ffc5f5a130dff1e140aa278c3c54a1f04b206279991ddfdb",
          "sha1": "4045d0f1866958be324f6e2d0ebc2540695c2b1b",
          "md5": "cf083f42e280f81f3cd6ced76461a22c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6224,
          "sha512": "0fca8b325eb4b8a8c34a241442c14166d7a1941b368e2f75000324c24d9210e9949e9396a47359b6bfbe541dc95521fec8a6adf4ed2256361376312a0e350fab",
          "sha256": "11a7379e763e8275ffc5f5a130dff1e140aa278c3c54a1f04b206279991ddfdb",
          "sha1": "4045d0f1866958be324f6e2d0ebc2540695c2b1b",
          "md5": "cf083f42e280f81f3cd6ced76461a22c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 95713,
          "sha512": "adc239a3cc03e63f7219545e201ca124cf075833bcec222f85c0333810b3fd2ba2c32c72512f45ee867cc48b0700a46f9d1883cd0d52d16d243c625bd6485d72",
          "sha256": "d3a084e1c4a7554dd65c9ca277ecbf7a383a21ec7e6b8eed96c5a1c3a16a4b03",
          "sha1": "9f2eea939866684aea5ee84dcbf42933af80addc",
          "md5": "a37c9f840a26006c5eeee7b88a990db8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3467,
          "sha512": "e0e29a86565c318f1bd194a5d0be893aa02e019140d25d85361ac47c02e855a69a487b98071df481dcbbe7343350194d71a73ae0f53ec097f9c934557e8ea3e2",
          "sha256": "f3fd8bd7881b808c6cf5be6e20382b6d778f43ec3561bebf7f7bca0a810b0948",
          "sha1": "773e09d9905985d53c524fbe1471a0c8ebbe564a",
          "md5": "c8db63730a02893cfcff741e25a1d0f8"
        }
      ]
    }
  ]
}
