{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "527d0c42974cae27ba738efd5462d14b0829937971984ec9cb12941e109dbb85ff9ec0fb706987c0d4c2355ad2457e617ffc4408e34e3c9bb3d4cb0a57980483",
          "sha256": "54f221414b4a41b64b1a9f2e870e07a665862949193cdf01f108ffe7004ad808",
          "sha1": "53e8d6a102290b0825ce1d7a55c8a88787f89e8e",
          "md5": "112c38921995d052c5f77c7cad4968f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "527d0c42974cae27ba738efd5462d14b0829937971984ec9cb12941e109dbb85ff9ec0fb706987c0d4c2355ad2457e617ffc4408e34e3c9bb3d4cb0a57980483",
          "sha256": "54f221414b4a41b64b1a9f2e870e07a665862949193cdf01f108ffe7004ad808",
          "sha1": "53e8d6a102290b0825ce1d7a55c8a88787f89e8e",
          "md5": "112c38921995d052c5f77c7cad4968f9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "0fcd49077c8e02423252514cd04e2cef8f54a8889061c6064e5b2bd7ec18e36b1770d2ec08218f2867ae5500afb7643b909a422096cdae21789f262f74e513aa",
          "sha256": "0e8621799cdb93a3352ea367ff5122522981c62cab4f1241208aa7e359d07e26",
          "sha1": "f00846ebd783df3333e035b57de948a0d8158390",
          "md5": "f8395d692ed7f2dbd9a01177d7da6c56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "336bc0c1464b276ad268865f9e31382d2e4c7fc597cf42cc15017d2a7f693ee1105bc9ec12ec53b3cdd76fe188a71a8586b2774adb9ecef7f8f63f6c7ac71d97",
          "sha256": "8161268c5907dcd77c68f5c69e02bf5bc7cc517a4bb32e6d30cb0aef84491585",
          "sha1": "8a2037c0d2d9f7c87a0255a8c4565b70aadb9f34",
          "md5": "80f3ec2eac75c8f4487092e915114516"
        }
      ]
    }
  ]
}
