{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6224,
          "sha512": "bbaabe4eb4a167fd0c5eaa12c16e20882c7a5e95d043461af91005eba203e57498711fa0d630977fe843369fe5b07001ce6535675c1aa46a3be8068a353fd4ee",
          "sha256": "416ddfd55f08c43eceb60509574349193eafa7f1824b3bacf9f7d8147ee1defe",
          "sha1": "a42abc230c13b9dadb6c6ed6ec917d9257de633c",
          "md5": "c8bfecf1877ea2540964fcda342a6a01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6224,
          "sha512": "bbaabe4eb4a167fd0c5eaa12c16e20882c7a5e95d043461af91005eba203e57498711fa0d630977fe843369fe5b07001ce6535675c1aa46a3be8068a353fd4ee",
          "sha256": "416ddfd55f08c43eceb60509574349193eafa7f1824b3bacf9f7d8147ee1defe",
          "sha1": "a42abc230c13b9dadb6c6ed6ec917d9257de633c",
          "md5": "c8bfecf1877ea2540964fcda342a6a01"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 95713,
          "sha512": "07f27f045604e8f40f1e230fd27cf948740d3ce648006603b73c1abae243b82d912348f459d5c2402a1841880d1b8f97a7efda32825aba159d35419d2f7f5d9a",
          "sha256": "b7e04fbdd152c0ca04c0c76f98604460066732b0d4eb4ac5e93140ce7334fb0b",
          "sha1": "48b6f2b1a9d6d638d8e2bd5d3ba7a58ebb43d303",
          "md5": "8b1766f0ab697ef42d31cb682ada74b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3467,
          "sha512": "fbb1f389731f14905e982806f89a76bfacb80d0ab7400a1fa784cdcec12f873f0da2ec93e3ded395e8cee60461f84af77a7d93b6d5634cfba528b218f1e10d71",
          "sha256": "c99866389b70119c29baf2235871c3bc4ff7688e5ee1c99d4f2853afd3aeca92",
          "sha1": "81dc74108103de07b6bc4752b72cdf4e4788d950",
          "md5": "538eeea6e1b8a8341ccb1e219e98cde4"
        }
      ]
    }
  ]
}
