{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6010,
          "sha512": "b6bc4fc0ef852bced07f9f90f8522be9441bcbc57beea55cdbd397903adb157decdef9f107c829a15eb91ff10461dfcb8a5ab61bb945e379749d380799c09148",
          "sha256": "e844f3663bd17a350eaea12a9561373863becfc56ded51d716856cf6284a6f5d",
          "sha1": "aaa0f8670c00fd10d94e64dc1e61599203f40444",
          "md5": "f4371a69165a7c516c79815fc76214f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6010,
          "sha512": "b6bc4fc0ef852bced07f9f90f8522be9441bcbc57beea55cdbd397903adb157decdef9f107c829a15eb91ff10461dfcb8a5ab61bb945e379749d380799c09148",
          "sha256": "e844f3663bd17a350eaea12a9561373863becfc56ded51d716856cf6284a6f5d",
          "sha1": "aaa0f8670c00fd10d94e64dc1e61599203f40444",
          "md5": "f4371a69165a7c516c79815fc76214f1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 95635,
          "sha512": "142a5c9ebd1ac09830ce60b859716cbfb2e781c6c6e45315ea589654a057071973ded43573fe8beb5db3421afdd13f6573595b71b110ec4524d450f7e69bf7a6",
          "sha256": "0766aa1a05d93ac657396eb3f68562ed9a9b3acba0effb0fb5ee163b611a6fa8",
          "sha1": "10368767693bdd3b071e66866e3751b1fdb92f82",
          "md5": "af34c8e4ef58783d4f3eb33e580e3d8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3351,
          "sha512": "a0ad05b35258a4cfbf7c31b4648df623cd27d9b20556a3f7e37d81ea0191a9057ce6eb2732d956bb6b4dcbe29e8ca73f208ed7bd0c177a86bac7278d40739446",
          "sha256": "ab902feff07f6809c69e18e00118ccbc718c690b03c60e2f6bb2dce389c83430",
          "sha1": "184468eaa1e7d969fd65d8e50d3d697043526017",
          "md5": "98ee1af2c6bd5ce77b354be6f62c317c"
        }
      ]
    }
  ]
}
