{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "a338c40d489400d36de8b15971ec1077efe368ea2f56911079a5fc5a29facd0fd71532e399b6dcefe33b4bcf72880e50c8ba33e0ee1f646b75c42df3c99e3309",
          "sha256": "fd2c42ae46f338d2dd6385a689d7cf361d7403197abcea12bf3db0576aa8146e",
          "sha1": "ffebaaca04068115c8e2a44d105cfe25aa5a536d",
          "md5": "683aa8d69c8b2b56f6c9c93922ac3a66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "a338c40d489400d36de8b15971ec1077efe368ea2f56911079a5fc5a29facd0fd71532e399b6dcefe33b4bcf72880e50c8ba33e0ee1f646b75c42df3c99e3309",
          "sha256": "fd2c42ae46f338d2dd6385a689d7cf361d7403197abcea12bf3db0576aa8146e",
          "sha1": "ffebaaca04068115c8e2a44d105cfe25aa5a536d",
          "md5": "683aa8d69c8b2b56f6c9c93922ac3a66"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "03e8e11cda1b002956ed401f05ba3357911d3f0e65b61d3a358fa8c10ba3ba0aa71d9fe9dc94b024e48fd7284c81ac8a03407f9fc21598e2d995b36d45e04558",
          "sha256": "fa132bccddbcaaac07d3ef154caceef64ac4c2f3dcf8bfb2a7518eee925f191e",
          "sha1": "62463e4372324359e42419a1b2abc273c0eeb8d5",
          "md5": "10ef18249b6f34bbf75527ed13e3855d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "19b14986de49ddb8c3ad1b86dff1317134fedba2bedbb8add150e5cd1c710abd9e5e96f646654feb2c726a3df390704155238ed1c6ea00638bfb7e1f0fb4a972",
          "sha256": "1eac392afefcf83491ab2432f147e6895495f6e2abf1ad2661c55bd541368ea0",
          "sha1": "25a4808549b8d81524fbb47530a784605f1af0f5",
          "md5": "88338043824c95725c7cef72e14f481e"
        }
      ]
    }
  ]
}
