{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "abb90590fe2860f4ce004c47d60f6e13d38b70eedeaaf228a9882fe753c542b84bac44f6d7c8aa47da3ff1e2681697c4c54334ea68262df086c79183077f66eb",
          "sha256": "ebea13b0b477c8fcb265f77962a200056efb64553a2a4e3f466f3f5815fb11ea",
          "sha1": "79f29146fabb70796a8a005ba907d02f4525bffb",
          "md5": "71b620fb33a8a7a65e90117b9e7dfe64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "abb90590fe2860f4ce004c47d60f6e13d38b70eedeaaf228a9882fe753c542b84bac44f6d7c8aa47da3ff1e2681697c4c54334ea68262df086c79183077f66eb",
          "sha256": "ebea13b0b477c8fcb265f77962a200056efb64553a2a4e3f466f3f5815fb11ea",
          "sha1": "79f29146fabb70796a8a005ba907d02f4525bffb",
          "md5": "71b620fb33a8a7a65e90117b9e7dfe64"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "7085886d3b885b7d77938e3c05054a7cdcbfb4630b120ebe79118a0e3b120c4a920d7e9af9320e65a8c0f1c414765b9167a034ec8437aa9a6643c93e671d7303",
          "sha256": "15924eb366e4973e9285a6dd79d33ce10d9f512928aea852a82c87cec50dc9b0",
          "sha1": "f0d8310cdc1b0f4d440e6f32068ea9d2c51d79c4",
          "md5": "18545b2bebd7aebbc93c54719b238f01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "689b4fda0bfcdbfee7599727dfd6089445b75bff7b93d469fb0e7c7033761329782cc34727cecfe4ab87e830ef6ed4425f0c0ee071b5aa36dac2004694a8608a",
          "sha256": "b6ff99dd73cb6fb88bbb90ceca4c7e437e837a915bf79dcc40971a0db0ae153f",
          "sha1": "9b6a0caad7609d47eae80afa57887546e47bc05f",
          "md5": "06f18da9bc591cc6b1583098990d299f"
        }
      ]
    }
  ]
}
