{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "84aec3f843e26f849c2f880abc7535bf9f975a0c22267bedefb5e218bf10efc6558d1849070c975342973cd74928d353280971fa214c49dcba1edff7c800e947",
          "sha256": "9a377e69491580c50a1011e422f009a8d8c08b8fe70952d0977ba299ee40f28f",
          "sha1": "6394eeea197af9f74ef6bb02477d368bac202a26",
          "md5": "756e3efd093ee8c6a471b6b2c97a6e25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "84aec3f843e26f849c2f880abc7535bf9f975a0c22267bedefb5e218bf10efc6558d1849070c975342973cd74928d353280971fa214c49dcba1edff7c800e947",
          "sha256": "9a377e69491580c50a1011e422f009a8d8c08b8fe70952d0977ba299ee40f28f",
          "sha1": "6394eeea197af9f74ef6bb02477d368bac202a26",
          "md5": "756e3efd093ee8c6a471b6b2c97a6e25"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106550,
          "sha512": "5b245dbcdc151ca817ec6f9f6a3d68472f8db2dba0306d3721730b98328fa133bc32e1cd8db7952fb1de557cedda74b6ddd48c9a5665630dc5a35ffd4b34d61a",
          "sha256": "f44a13d6554a260f2d258f9dca637312932d068d97168a86c4a882c4eecc3446",
          "sha1": "4cb433be3302de43d8ccbdb2d72717b2998ad3a2",
          "md5": "80e7f24cc8aab441e0f50c3eca4f81f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "20e4864b6b52ad4c4cc599810efe1f34cfb32bae6ff4a3f8cac57e7e65f23d4bb6f222f9c374b51af21a938f92f5dc103d852369f3c7e24533792c62f2f434db",
          "sha256": "0799daf65b13af772d1158884c0ddb894a3c2d096775ced08209593ed85714cb",
          "sha1": "962fe2870ecf41bbbc95d4b0a4b5a25ab002ce18",
          "md5": "5d985b2644d49df9e2d6a25ea2bd676d"
        }
      ]
    }
  ]
}
