{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6228,
          "sha512": "61e7906cace869697b1cb851789c72172248bf23c2bdaf6cac2124ee35d745f28a31f426191f3e377bd46df3fdc99e56884197a930edec9fd3d3c46cbe8dffbb",
          "sha256": "578a7341308f01b73e3fafd62a742ffaf11e6769f739cdad1ed770167b1e037c",
          "sha1": "703c6c5128bc5ddbc2da94d2411be314013c55c8",
          "md5": "fd7ae83594baaf456019e5ce809cdef0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6228,
          "sha512": "61e7906cace869697b1cb851789c72172248bf23c2bdaf6cac2124ee35d745f28a31f426191f3e377bd46df3fdc99e56884197a930edec9fd3d3c46cbe8dffbb",
          "sha256": "578a7341308f01b73e3fafd62a742ffaf11e6769f739cdad1ed770167b1e037c",
          "sha1": "703c6c5128bc5ddbc2da94d2411be314013c55c8",
          "md5": "fd7ae83594baaf456019e5ce809cdef0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 107402,
          "sha512": "f25a735b23f417179068b7bf02233ee0e00a227be1ec3329ce7e2a9f4c0e148afdf8b23f43a167c7973c9862102667608ae5486ad66cdb64e126f738e4d4b270",
          "sha256": "a0480d41cdc657ed908ab9d2f9988ef8c6e4acd548c6732349830e51014bed58",
          "sha1": "5f1f21894eaa8d0c61196c3dfb24559aaa989b37",
          "md5": "f98ed24c8a13ef50ad138bd39ceefe79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3467,
          "sha512": "34e03553e96b637fdff7cf2178fd78963f8af28f3756bd6baba67bf75b3904b6826e666a988d71ef95734de4a760fe59041598b8fea9ce31f16f796dd978a1ff",
          "sha256": "25f569abe0b5acf904089e079a9e27e58cd02ee8da2cc3f70a1b67ae7cbff270",
          "sha1": "d1a65890ce15bc56c3cbd9da1a8997e0ea762326",
          "md5": "8a2d6f26610559645d413c6201ad3f87"
        }
      ]
    }
  ]
}
