{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6010,
          "sha512": "d3b51e0150e71c752feb53b5fffcfc8dc8335493fe816fff7fadb3cfce828eba1aff01b73f07a37d89fa1cda9928fc495ce7d8a03b883ddf107b39a40be58adf",
          "sha256": "e7374a30aba1ca1a49b25eb23f8a35867b521eeb1adddda8f7f980478f36be52",
          "sha1": "938e9a3d688480563cb21959c3e4789b3541228a",
          "md5": "f3ab0b847d7bd52260eecf53fa74481c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6010,
          "sha512": "d3b51e0150e71c752feb53b5fffcfc8dc8335493fe816fff7fadb3cfce828eba1aff01b73f07a37d89fa1cda9928fc495ce7d8a03b883ddf107b39a40be58adf",
          "sha256": "e7374a30aba1ca1a49b25eb23f8a35867b521eeb1adddda8f7f980478f36be52",
          "sha1": "938e9a3d688480563cb21959c3e4789b3541228a",
          "md5": "f3ab0b847d7bd52260eecf53fa74481c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 95635,
          "sha512": "2df05fc524388dce33b414435b50f1b69967f6c66d8a467b1d0f8ef146e8d1911d9755cebaac34cb9a0803f162d092e2a36152a7986c67ac7cc7e46800fb4ad1",
          "sha256": "9ebdd8884787dfef20b9aa37ea7f39e91bfcbf1ff7a24e228313e457babe50e0",
          "sha1": "825b5b0960d0915a07ca7f02a569005b59845e1e",
          "md5": "2c688b3c7db5f2ca650a239721c9bfa4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3351,
          "sha512": "8261d5a95f37f2f02d07232f8195f76e604e425c45bee1ec0f8b89230d28599e7c2cd364ae66526041b698aae17c3597d3c5622bf7ff2f7f24a053f3c6cfcd6c",
          "sha256": "ef35a6c58b29fa81012c0fb7fd9ef76328b3f446014e9316c6b7cec0ed4bf989",
          "sha1": "bbc87533c837919b894c69405a1332ab0dc6a495",
          "md5": "65248b0717fae2e448b98b2445b6e6ae"
        }
      ]
    }
  ]
}
