{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "55aac6b4225225da698f507cb3e11bffff6f84e7c27e9f4382f20ff2c56dad52601444292b3f97cd6bec6a05943597da71089f986b096e19febf13bf1848aa87",
          "sha256": "fd356e83bfd0c02b41554ede529e07aae6e9b617f7c3778f84c9b3a26346b4b5",
          "sha1": "50b44b911c7ffbf924cc7e1e12c9049f821ccff7",
          "md5": "c51c36b3177bba51f5bf19b03d41dc08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "55aac6b4225225da698f507cb3e11bffff6f84e7c27e9f4382f20ff2c56dad52601444292b3f97cd6bec6a05943597da71089f986b096e19febf13bf1848aa87",
          "sha256": "fd356e83bfd0c02b41554ede529e07aae6e9b617f7c3778f84c9b3a26346b4b5",
          "sha1": "50b44b911c7ffbf924cc7e1e12c9049f821ccff7",
          "md5": "c51c36b3177bba51f5bf19b03d41dc08"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "391da53dc39a68e6701ac5b2216044f6333989a8fc71e3bb82594709228e06eec24766d92bef36174a8355b19eeb4ec94863613144f2cc2b300f7be0461fc68b",
          "sha256": "9d2aa03560834cffd204956d30540e79445c06b2f9ada0ecc7216bdebabb6e58",
          "sha1": "c5f9740d8fdbddf8efc6d0f52c8cbf738d57a58d",
          "md5": "1c1de470ec91a3ee4c67c57c20b371c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "efc53e93a3bd76e496af7d7051c928a19b1ffe94e34bdd370a9fc8e7790e4cd56e9d9481d7faf60ada318915858b63a28678f5082b89c4d6f42b8b04663d292b",
          "sha256": "40c3970ca1babfd2dfea8df0bc8bdf9c2fb9a3537cdfb03ad39d202a174a5a22",
          "sha1": "9cc994711e770d842661d565a6dee685c20bc60d",
          "md5": "09a496c474a6573ba8e12a62f3a5f252"
        }
      ]
    }
  ]
}
