{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "4b9a5724114d2f81508300d7080fd7669ec1f048f4c168d3827d7683babb0b0fa64fb42b56fb918f8e5fb2ff5eb85b6197170c5f8f1fd0366fcbcf88cf80f1cf",
          "sha256": "b50f90540f6917433874c2d1e79e60f096127423add0c0961a74ecafda9562fe",
          "sha1": "a5a8edadc589ae6643498d4b54217972d5da94da",
          "md5": "870aacc399851743727689aabbd75216"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "4b9a5724114d2f81508300d7080fd7669ec1f048f4c168d3827d7683babb0b0fa64fb42b56fb918f8e5fb2ff5eb85b6197170c5f8f1fd0366fcbcf88cf80f1cf",
          "sha256": "b50f90540f6917433874c2d1e79e60f096127423add0c0961a74ecafda9562fe",
          "sha1": "a5a8edadc589ae6643498d4b54217972d5da94da",
          "md5": "870aacc399851743727689aabbd75216"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "319046613593f5bc2b5a944ea6dab66e74315fc8b9f31e3ad26e6ecbea291cbcc50a80f8e65ffc5449d1c6e9f73f87fbc4aadad9c51100cf86488ecb3661c62c",
          "sha256": "a92368bc85466e6afab56a990893abdaf78b357df1eecf856d8bd0123c4361e7",
          "sha1": "205a29e8ef92f509573c4c63a5920d28736c9009",
          "md5": "b3d342564758a74e2a9d52c7a8302cd5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "4a0150cc28b67ed9cc852d44ce2b872842c390a9772c5483dff85dc78f512f890fe13afb99896d43abab67c89b7c3d9cfa3870424face80ff3526f6ce3548552",
          "sha256": "99f43715eafdbaa22bad0ee014772b112d262d98cda701bb13327b0391514fc7",
          "sha1": "08d00a0a86ada3bbac919f06d38df678374ad1cb",
          "md5": "524b7617ace968d6d033fb345784bfd9"
        }
      ]
    }
  ]
}
