{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6010,
          "sha512": "1036046dbebb67b76054e2af15edc0f304efe89bfa3aee4212f1c03de076f63b7589e0225e5287215d5451a3071248a518fd3fe9223eb5e6e3c3f941c2ba45b6",
          "sha256": "f2a3bbf1fdd1f1ca2a2f1c3ce26937cd35d4889ccf27fffed9a889cf1e188144",
          "sha1": "57a8401bfbd0fb56c07cce4f2b59bb16d7274b1a",
          "md5": "a1fb4f99e932c6f56099f8f6189fcfd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6010,
          "sha512": "1036046dbebb67b76054e2af15edc0f304efe89bfa3aee4212f1c03de076f63b7589e0225e5287215d5451a3071248a518fd3fe9223eb5e6e3c3f941c2ba45b6",
          "sha256": "f2a3bbf1fdd1f1ca2a2f1c3ce26937cd35d4889ccf27fffed9a889cf1e188144",
          "sha1": "57a8401bfbd0fb56c07cce4f2b59bb16d7274b1a",
          "md5": "a1fb4f99e932c6f56099f8f6189fcfd1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 95635,
          "sha512": "8032e7a990447a5eb11b4d3de6354ebc7386ecef6428ddf897ea6278c42653d5c0f529ff26b13418438234f42deb9c28cc907f0681ea65664b5e5d32d9ab580f",
          "sha256": "276a7f24706dc6e5fca2b5b04947c36d76e4be0ecccb3fb0b30583ea51f5692c",
          "sha1": "98dc72e9031b799e619c47e1db6267142fb29db3",
          "md5": "6f027b42fc9d33942761aacbaed661d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3351,
          "sha512": "7cab3ce65b9aca2fc2721f8b69b6b2ddaf1f30753a5271d21109bd44d4a82baa82387bf50f6060d5617a58e4fcfc4bede26d9faacc7af4f2da19dc1a617ea8b8",
          "sha256": "4ed4a360912ddd1449a09a67e8a6c3e58d3d3a15a44a0b2fe94174fc9130b5d9",
          "sha1": "5aa9325bad468733cdfe1dfeb1c38465cc03e758",
          "md5": "26ce5fdc611e108e766223c2b78e7af5"
        }
      ]
    }
  ]
}
