{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "3b6d6ab281530ad3a49380d1c662359a7035c7fb1d2ee2dad62fee626100eee14861c7a1f8de6559bbb80e98cbd58c6a64902b333e3eee4c8672dc9863872eba",
          "sha256": "4c62466cfad47209228591b49dcc576ae9bab396e1e4d680201742ce8eb73430",
          "sha1": "439628c7dca0e12efe92f6a5ea6cc03324604c9b",
          "md5": "432c959e1c9432e1ebd0edafb852cab7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "3b6d6ab281530ad3a49380d1c662359a7035c7fb1d2ee2dad62fee626100eee14861c7a1f8de6559bbb80e98cbd58c6a64902b333e3eee4c8672dc9863872eba",
          "sha256": "4c62466cfad47209228591b49dcc576ae9bab396e1e4d680201742ce8eb73430",
          "sha1": "439628c7dca0e12efe92f6a5ea6cc03324604c9b",
          "md5": "432c959e1c9432e1ebd0edafb852cab7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "46387e5e0015c601b7082d67d006ff630927c17fd576c1f1343d521c1e0fbb15f4d08382810a0eef5d952a369f46555a160a93444f47871b5d8dc575b498eb1c",
          "sha256": "547070ad48d5ce0fa4e132cb24afb2409777d7c9df77b54b09cc3ef538423dfb",
          "sha1": "4b16b221e7f13be68742f6b3e959753dd4fb8c9f",
          "md5": "d6668dd11a85f138d1b7ac3775d749c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "9ef2de54bde9aa139732f9ce2ab405135835daf612d08535fc13fdb09549bbd4bd47f98a918cb4512436e1908133ab19c0a4a420ea2ea17e2a06e93061374104",
          "sha256": "ca0a604d5efdd9a8fa22e595c411e7196b98974d26e7a1ffd9720b2833ec7d52",
          "sha1": "58b7fbb35b69069a7b25e58c1c033ddf786318c5",
          "md5": "06410aefb44c9e140778b90120049b30"
        }
      ]
    }
  ]
}
