{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 7514,
          "sha512": "874cee462e609eeb894de06f2bdd61341332de949bfd53fd117b1b25fdb682c41465d5c06232e79fc93e734e40391581a9924b2df22c237c294258cc15733bff",
          "sha256": "0e4e652aef357030ffd250ad5626db0a9f87432fc0c306d45f7e58f14a0378ae",
          "sha1": "422748c9ff8d05093974015bbbe302e89be96c6f",
          "md5": "dd40886de7ce42f8f899df97ac2d19dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 7514,
          "sha512": "874cee462e609eeb894de06f2bdd61341332de949bfd53fd117b1b25fdb682c41465d5c06232e79fc93e734e40391581a9924b2df22c237c294258cc15733bff",
          "sha256": "0e4e652aef357030ffd250ad5626db0a9f87432fc0c306d45f7e58f14a0378ae",
          "sha1": "422748c9ff8d05093974015bbbe302e89be96c6f",
          "md5": "dd40886de7ce42f8f899df97ac2d19dc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 95847,
          "sha512": "741139748dae3165d40990c2f274d5e368c136b4bbf8f99990699e3656144984d56bf2ce1dae429933f498be0a8bb251a83c54b64d07b4473a38c2e1cd27b7a5",
          "sha256": "0be17565a7f3182d64d24c28ec5b5df0f662523c01c9ecd5c85cc15dfb9f2e10",
          "sha1": "97a022602d7aed4b9eba1f54141059815aebeda1",
          "md5": "4c565986107bee6dd412be7751cecfeb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3874,
          "sha512": "c4d6cf4de44b5eeae208cf386f804c77aabe42045a78b4f61de74252d3f330e05c2d05afcd68937d7de9aca2e4b3e6e50cfe5b06430801cff908d92e5f1e547a",
          "sha256": "a1916638a3f240e8c47b7b8fdfb562c4476a26615c8fa3a3a1ec8e1fa4bd225c",
          "sha1": "a7521319adbaf810a3a14370f0c5c08ded6f8487",
          "md5": "30ab58cd65705611bd2dd3eb8f5d068d"
        }
      ]
    }
  ]
}
