{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "8afe00de12f6198e385a589a576f97f9792107d65b1a1a85c9593be36e11bb9b0b848e0c8dc344f9357d90d6c502300f19d0b78271cfc5b09434382926dce600",
          "sha256": "a22d338dae64244f39b4ee84bdcb2d344c12a4dbaea93490c2340a33f5c36740",
          "sha1": "f105375b97cdf0ba1ad737e7f39a96212729db7f",
          "md5": "2d1de19c732f12bf46666b88e1836559"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "8afe00de12f6198e385a589a576f97f9792107d65b1a1a85c9593be36e11bb9b0b848e0c8dc344f9357d90d6c502300f19d0b78271cfc5b09434382926dce600",
          "sha256": "a22d338dae64244f39b4ee84bdcb2d344c12a4dbaea93490c2340a33f5c36740",
          "sha1": "f105375b97cdf0ba1ad737e7f39a96212729db7f",
          "md5": "2d1de19c732f12bf46666b88e1836559"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "7d98ad694b6315e74729ec3e3607000df814f82f1df4567f75fc534c97537132721b8daeb5e710b6699dcf4860bc08daf44c8f62212d089d1b872d0f91316c2d",
          "sha256": "1235b413338865ff37b00909dbde6ff46e039dec3d845b9f379198439a66ceec",
          "sha1": "9327dc3ca49f0bf7b099dca8d07d3abe73a6619e",
          "md5": "6bf574ae5e4a521fe43341d4ea58b92c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "d10b525c4f3c37fba1a18912f71d0b70420a947129d713133a1e27b88578cf6dc0f9498dc22557bb585a01494e90caadee112e3988b7094866321a04fc58a35a",
          "sha256": "6567713040e4d9036cbe6cb16f8695a42fdd888ff0e472fd73ae7566a3018ea9",
          "sha1": "7929a16852e1681bda4243bc0c2d8774efb80c11",
          "md5": "c3e00715383f00492018c7e4fac89ada"
        }
      ]
    }
  ]
}
