{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6207,
          "sha512": "a12a216ca8fb083c17fbe5bf6a9ef19d0d7515335b0e3f06bf27562407f211932c25810eb9fd27b19e2189792071fb10ba224762648e023fbe9035dd86f83b3c",
          "sha256": "3c0de823e84ac0e8cc84dc0c46ae008d77f47cf040b577083f750d10401fc50b",
          "sha1": "1ab71e99e79d15760237d4658f103b9c48ceaea8",
          "md5": "b2a5a907f831fb7d506af9343c133a62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6207,
          "sha512": "a12a216ca8fb083c17fbe5bf6a9ef19d0d7515335b0e3f06bf27562407f211932c25810eb9fd27b19e2189792071fb10ba224762648e023fbe9035dd86f83b3c",
          "sha256": "3c0de823e84ac0e8cc84dc0c46ae008d77f47cf040b577083f750d10401fc50b",
          "sha1": "1ab71e99e79d15760237d4658f103b9c48ceaea8",
          "md5": "b2a5a907f831fb7d506af9343c133a62"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106451,
          "sha512": "be9733342b1f99cddbaf597a65bde364dca13227ddb10b7a0ef49c37526ad75cc777c245c899436ff81409406c0b3aa39cd80e9c7866dbd90e2e11bc00221412",
          "sha256": "44a7a2e187ab28cda7b087cb0d6807ff588faced1971f834c551fac7f217e08c",
          "sha1": "da2dc5d88dacafce47ae3121304d9cb3bc6c7215",
          "md5": "03f6d6f566cdd2639a1ce6a68a788386"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3593,
          "sha512": "27a1303c881cca48230830e81153ab27e5a1c2b1eef5f442caa26d39aaf1deb3fe966c487816c091505c8a3317e74fa1b415de8b2494f129e72bc7cde75699a5",
          "sha256": "6fc65d93f6a23ff449a9e17673d94d6f9b86ce579e8ea41186ae0833b05f6c79",
          "sha1": "c2142eae3ab235dfa8083ff5dd91756585707bc9",
          "md5": "102ed8b2d2c2647ed50f242e582bfc7e"
        }
      ]
    }
  ]
}
