{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6228,
          "sha512": "942663f99e45de24b7e68960e5bdea96ea29decc3463350821108a27764c5ca24c6fde6499d42e45b4cb3b5428e7e93fa3cdc39b5b2ae9e22304902513e36d6c",
          "sha256": "d365aa9db06e45447329480a15a7160cdb9a79a7fa1de91f2c23dea374265567",
          "sha1": "d5bbfa46f00f976b3d03f67096c730ebab04ba14",
          "md5": "1dddcf2ca70b303e21780b84b25f0aa1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6228,
          "sha512": "942663f99e45de24b7e68960e5bdea96ea29decc3463350821108a27764c5ca24c6fde6499d42e45b4cb3b5428e7e93fa3cdc39b5b2ae9e22304902513e36d6c",
          "sha256": "d365aa9db06e45447329480a15a7160cdb9a79a7fa1de91f2c23dea374265567",
          "sha1": "d5bbfa46f00f976b3d03f67096c730ebab04ba14",
          "md5": "1dddcf2ca70b303e21780b84b25f0aa1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 107402,
          "sha512": "bd1ca18af8228df0d46f60d5605348332cb02e62bafda456cebe6aa3e228dc52a7b1ffe83256ef6878407d714e29d946157cb27105c03e620dcf3c2a703fba3d",
          "sha256": "cb87fd1ebeab0305a51882b853ae7a75bb3e33cb39f73e2fc1958b62cdb9b6e3",
          "sha1": "02a76881364877ed05612e2ebfdcd1bd3821ec74",
          "md5": "db63e3bb80f66c4683f605f1af348d42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3467,
          "sha512": "22f172650fa98d34f86211fc35912548084e5c64b0d63aa7f1d1e55c3de24c1933e1acd43166ff5db7dda19b1643a889a5e7faf4d1ed57f55f10455e64cae2f3",
          "sha256": "54ed9c39313cebb6d27b0272cc1bed17a992aeb137a9dcc9bffee460d93cde20",
          "sha1": "675718687606721d57ce34a5d91463193c4ecb5b",
          "md5": "4d5dd8b6f262f110181f53e1d5f08b55"
        }
      ]
    }
  ]
}
