{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6207,
          "sha512": "2cc091fbb79a82626b1e35b94960093030c24b9d5cc86ef698725e227ac05284a75396e35da5ab5a681d7500a7e122a79593d947d4bebd262b54126eaeaedc92",
          "sha256": "80a95504fa3dee2870dea7557c438a80dc67906f31219e696eca2bd49d15f60f",
          "sha1": "45f9bed97d6095389ba4b71f3f6d21071d3a078c",
          "md5": "81c7df0df00bd7508423efc00f9aa3a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6207,
          "sha512": "2cc091fbb79a82626b1e35b94960093030c24b9d5cc86ef698725e227ac05284a75396e35da5ab5a681d7500a7e122a79593d947d4bebd262b54126eaeaedc92",
          "sha256": "80a95504fa3dee2870dea7557c438a80dc67906f31219e696eca2bd49d15f60f",
          "sha1": "45f9bed97d6095389ba4b71f3f6d21071d3a078c",
          "md5": "81c7df0df00bd7508423efc00f9aa3a1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106451,
          "sha512": "ddbba800eb66cdd97dc0b7db5ab092be8f53ed5589bb4a73a02265185ced6ec6a8b536eb97487cf1e6b4cfde6a159693e426ccd0479078ae3ee4b951cdcd0b0d",
          "sha256": "47c21740b66e7c3cea723614c84c3764745cdd1f57171a4731dd2f4a7cb5f29e",
          "sha1": "f55df1c82567b36aa1de255f099ed31c97e865c8",
          "md5": "1f2f134d15830574e28aa4987bcdc6cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3593,
          "sha512": "0224250bc03bf7a1ca1e4bcbf9017bc7beaaee3349ecd6dcc4ac663de39543e9fba484117d2af3effb5790c4a99bd0fedd24cd4be7a917f02683e914c9231280",
          "sha256": "022daadc04827d530e9522ebbb2406feed9b3c330c0bc7463ec8cade63cbd64e",
          "sha1": "26ab93385b7f593dda9c6ee3dbbf4867ce5b1173",
          "md5": "ab0179a9d6b8808845f263a106dc120b"
        }
      ]
    }
  ]
}
