{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6228,
          "sha512": "bff6cb3339f263cd5046f16b0c16e316d108ea927ec233e17d32a917c2b44ae5a2092af9e4c5248f5175ae756981f5908b8dcf678162702225c80a358966361d",
          "sha256": "5946556edb0512a3f5814b73f8ee18b0075db5931f8be6f612b715ca28cd60ef",
          "sha1": "bfed9d355c4532b4267be89119a634ac8ffbe958",
          "md5": "1d24ac7ac6b42143c8e925e6870297c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6228,
          "sha512": "bff6cb3339f263cd5046f16b0c16e316d108ea927ec233e17d32a917c2b44ae5a2092af9e4c5248f5175ae756981f5908b8dcf678162702225c80a358966361d",
          "sha256": "5946556edb0512a3f5814b73f8ee18b0075db5931f8be6f612b715ca28cd60ef",
          "sha1": "bfed9d355c4532b4267be89119a634ac8ffbe958",
          "md5": "1d24ac7ac6b42143c8e925e6870297c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 107402,
          "sha512": "6566d7b89e1c40068485b288654e0500f861a6cfa234611972aee221dceeb4261119d5a52ddda1c01be71e746ac5c0f8f675f28cfe3fb0bc08f0e116c501420a",
          "sha256": "4a15e1316dd2f2d798336871dabd7083f0caa80074aaabd4172a578814c9d9ae",
          "sha1": "de2bc43a0cdf137b35dd1401080e70eff979586c",
          "md5": "827056dbf1fa351d815a132712a15b99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3467,
          "sha512": "e09708dc06ab691ef2f84c67a3f1a0b732fe12b80e811553d93a22bab939951fd57e9da77150235b131268e9cdb105df0d12dbdc3f9bb618212e1e548972dcb4",
          "sha256": "350b9c5cd0734d095cee96d1da418cb41972bd916e8ebad3ec653a4bdbbda36c",
          "sha1": "2ecac4eb0dc46a7fa681fa6e933d600c038c0ea2",
          "md5": "6dce0b2dca85e4c4927d758d9fbd9c23"
        }
      ]
    }
  ]
}
