{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6224,
          "sha512": "cc7bd4ad07aeb9676c7e04c7e700fb56f827ea6a7bedcc5e0c46655a97b52ca1cfe827580a3c4f6695c1335fe319dc6776c532e128f028caa5947c2cd9e59833",
          "sha256": "6ba245ee8e732a3afde77cbf863baa5a15f362b5c7ac6734f6dadf32bb5e7ec4",
          "sha1": "79cf4bd7cff5584becd726527e1ad808a0da9f50",
          "md5": "5c6b38ebffe9b206bda3ac8ccfffc8e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6224,
          "sha512": "cc7bd4ad07aeb9676c7e04c7e700fb56f827ea6a7bedcc5e0c46655a97b52ca1cfe827580a3c4f6695c1335fe319dc6776c532e128f028caa5947c2cd9e59833",
          "sha256": "6ba245ee8e732a3afde77cbf863baa5a15f362b5c7ac6734f6dadf32bb5e7ec4",
          "sha1": "79cf4bd7cff5584becd726527e1ad808a0da9f50",
          "md5": "5c6b38ebffe9b206bda3ac8ccfffc8e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 95713,
          "sha512": "1a9e1e0546f1d44629e2e693a50cc913e4c4d1d1bf65bbbc4b78cef391caef5642295eb31c87435adba8eb8c5a45a946e1f1c9c4c61bc5ada9962ab154462bc3",
          "sha256": "8a9bfd1210f6891801bd6e2f4ff3777d4df1db31e8d886ae0aa61a5a9723dea3",
          "sha1": "38d28b9ef898480c75e1fc84e1c34dd76c91a43d",
          "md5": "9bd86af66d28957db163832100bcc100"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3467,
          "sha512": "d2db4f4d21338fafb2bff267c3b587d3a73cd94a62bb3cbf211d1894813b2f6dc0fa478aa4d80a13f4d61c0a5465671fa3207ce133be13f826eab8044ed78a93",
          "sha256": "3cc522ab91cd8530319d4cdfe04cddf52c5a9b13bb4b68ecc99f517c51e64af8",
          "sha1": "f71239c15713709bfb3e8c6cf540b1ea3739719a",
          "md5": "9d7ef0b3bfbc18de36169fbb676f8235"
        }
      ]
    }
  ]
}
