{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "0b83a3af12165259aff1233fe1b1ee249a3c6e80892beba95666b3ec7b87ff1b616a375ffc1cb5ba20b1729851195d26630c91a743f505534ebe94e0bacdb3aa",
          "sha256": "b037dfbd457ce86a9c09bd8e1013bd874dcc33b4ebde33339656c1da96ade056",
          "sha1": "0a7885103a9bebc79f44755d06e1c262c7aa24b3",
          "md5": "2de78020f0c2748a71351d3e1bd71308"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "0b83a3af12165259aff1233fe1b1ee249a3c6e80892beba95666b3ec7b87ff1b616a375ffc1cb5ba20b1729851195d26630c91a743f505534ebe94e0bacdb3aa",
          "sha256": "b037dfbd457ce86a9c09bd8e1013bd874dcc33b4ebde33339656c1da96ade056",
          "sha1": "0a7885103a9bebc79f44755d06e1c262c7aa24b3",
          "md5": "2de78020f0c2748a71351d3e1bd71308"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "a0d720f1773a50c822bd1da02518e0db41f0e5618f8762b63e05f88d39623f42460e9ca1718ec2961c1c6ed87446f1781027adbfebca242e89d1ce4b649b0055",
          "sha256": "662523e9922997982f33118792b1674ff439685c0dc58ae0f00a1e9a4c5935f2",
          "sha1": "0cac288bdcf6a9a69f9f039e38031417bc033fcb",
          "md5": "67cfb0aee68d36efd954195869ed5086"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "52651d163a835c01cb5691c93fb688f1aa846d2e223bb04e9829068616dec8f487e528d9544bc85b7038839d947f09b4a2affa3a02047a655b0c5427d46f53f5",
          "sha256": "84a2ff809ca15f942fd525d3ad117d0502dd64e7d8753f75b380f11be4acf2b4",
          "sha1": "92b3c1f8cd144bb0faaef70c80944da4d7aa1506",
          "md5": "ab79231b5dafd672c7db2dbade4c6ca1"
        }
      ]
    }
  ]
}
