{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "186f68ae409c9331b85aecb912dad2ba65caaedce62fe1f5df2d3e665e3f435b2c9cfcac4a3a73a27159735e49f1ba94ac3a8596607a4866b68406c6e8f7db53",
          "sha256": "e5f0b7b49014c31f72e8d62dba0727b480c1ce42843a6243323750ffb7e2278c",
          "sha1": "2aea55732bbf0c6ccaef7d808784b1ca69e8b24d",
          "md5": "c25fad16d64ee2380f129c85e6935de1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "186f68ae409c9331b85aecb912dad2ba65caaedce62fe1f5df2d3e665e3f435b2c9cfcac4a3a73a27159735e49f1ba94ac3a8596607a4866b68406c6e8f7db53",
          "sha256": "e5f0b7b49014c31f72e8d62dba0727b480c1ce42843a6243323750ffb7e2278c",
          "sha1": "2aea55732bbf0c6ccaef7d808784b1ca69e8b24d",
          "md5": "c25fad16d64ee2380f129c85e6935de1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "04d7dab4b2f9ca1335bb98e37e1db272c909855c04b402726913509108c36cb7a60a1737cf1ac817bd8a63a6990f3b181c356d3ac146a18168de26071e717e41",
          "sha256": "1c6fe1fd2302311d95aff39125cf4169715047320b59a3d8f0c8e3e02fa51743",
          "sha1": "e12112c724a2338c6c1561b58383d532bc04ed10",
          "md5": "2d8f0df3b07a281a17edc45983dbf998"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "ca480e205ff24502764871521e17539d8d41e890a73bbfdc7fc416f03baab76e8ddcf14077263554516035572a76d279f2f2092e10d04ff26c16c79fcac0ceac",
          "sha256": "16634d1c34aa787feb0456ca73b99b47e3d0cd590e74646dda5dabba169799b3",
          "sha1": "ad27ec069d475df7a48553da062bba0fb5c99274",
          "md5": "1f2df7c280682ac96f05beaaf38d403e"
        }
      ]
    }
  ]
}
