{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "6767df38c0cd2024b9e35071eb24375ffd25b394756cc7ed9b17f515ba4134c8c099f98076586ee3e7fcbd3d2f97702c514ebef2e11db7dded0739e6092e303c",
          "sha256": "42763117e7409b8a8dc92584d322702d51e75ca48a5538e34bfb6d508caba832",
          "sha1": "7bead3596fdce5a2e94f6f5a5f6f865230353353",
          "md5": "a07ba6c5f5858200f93b617b7184a9bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "6767df38c0cd2024b9e35071eb24375ffd25b394756cc7ed9b17f515ba4134c8c099f98076586ee3e7fcbd3d2f97702c514ebef2e11db7dded0739e6092e303c",
          "sha256": "42763117e7409b8a8dc92584d322702d51e75ca48a5538e34bfb6d508caba832",
          "sha1": "7bead3596fdce5a2e94f6f5a5f6f865230353353",
          "md5": "a07ba6c5f5858200f93b617b7184a9bd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106813,
          "sha512": "eb84ba5005b1d189c177b52828c6cdbea5850d34a3caa53ad15ebc14b4ac177f0de34f085b0f95642578941777bb4da5cdb7074a7404a76132a915e32b9d3ad7",
          "sha256": "cefe0107a730939b27cac1341849929e98680f09519aae53b84121930ffc7d31",
          "sha1": "e3a7732830db0b226e94133e3f4bcc48cfff5d33",
          "md5": "d79bb1ce744d631fc7f9b120a92d456b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "6e360fae0b96d31e7517abd6d02737d595e4ff9f8271c70c1051fef7a2021552a96a03b791e8324b8cbf33cfd20043a5fa14c3a051bd995cebbd416d6fc38994",
          "sha256": "ba808c2cab8a9f2d20e07438d39569c64259f8d95e2c8debb332d86f7da7cf9f",
          "sha1": "7f010cd4f5757a91069404de722c484ef1f57154",
          "md5": "9005b3634e6ea2d8565b69a64a6734b1"
        }
      ]
    }
  ]
}
