{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6228,
          "sha512": "0a78ba7e2dc23b38b4b9400b00df06153b17f2072e293cc5563a8e66d1b8b7ecc24b1a30d1025fcdcb427a737713ad036605e22ea0f79fb781ce2871c717b25c",
          "sha256": "fa5e741d9315965ca7a204b37141a0e7c68242422c614d5d1d805a6640271e8e",
          "sha1": "0d5a09dfe0635c63665e68a1b68248906c466062",
          "md5": "bc4ca7eba7598aa6082663dec282306e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6228,
          "sha512": "0a78ba7e2dc23b38b4b9400b00df06153b17f2072e293cc5563a8e66d1b8b7ecc24b1a30d1025fcdcb427a737713ad036605e22ea0f79fb781ce2871c717b25c",
          "sha256": "fa5e741d9315965ca7a204b37141a0e7c68242422c614d5d1d805a6640271e8e",
          "sha1": "0d5a09dfe0635c63665e68a1b68248906c466062",
          "md5": "bc4ca7eba7598aa6082663dec282306e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 107402,
          "sha512": "70a81090b93e2920ef4bbe818d3ead470b468fa1c61cc969734cf52e879c38fcea7d6e8a977cd49bd0210cf0cb673dfd5418e439b553684a17522dba776643fc",
          "sha256": "eb5e10cc27adc0006853f72efe7156fc9bd6e0722c38cb412e60b3bffa714b0f",
          "sha1": "f0a290575fba2005f544cfa02f5177bf9fa5a3be",
          "md5": "191e3425ec811e38c5cfad1d333a6221"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3467,
          "sha512": "feda38cc931b562148875b1357263cba7c988757b9ed06df8d4b320eb0a0f378d2ef06edca2dd5d4c5880a840733cacdc6e0f5ff6337ec61a5ad1ae3858d22d9",
          "sha256": "80c5402fba249d66a32fee2e35b8437a10f868befd8093b4f14f04631ab4f761",
          "sha1": "f9d256826e9eb5904edcf649a53634be3ef63e2b",
          "md5": "e6ac8ca66141ba3bdd70da64f0cec160"
        }
      ]
    }
  ]
}
