{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "89c5248e4bb6efd79181ba455e5b8f9a7ed8270c596c3c24dbdf2292efe8e44dde79e2d08738cb1be81056d31b2c37b1c9c8278c5a34df31cc883eb77e6489b0",
          "sha256": "1c740fb667fcaaec28ed245d8b2876cff2d670b1b5e143fc43ca8e105fff2b64",
          "sha1": "cf96141cb6b205133de04c2464ac719c33f788fd",
          "md5": "987cadaef480b0678b5831e0fdcb64e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "89c5248e4bb6efd79181ba455e5b8f9a7ed8270c596c3c24dbdf2292efe8e44dde79e2d08738cb1be81056d31b2c37b1c9c8278c5a34df31cc883eb77e6489b0",
          "sha256": "1c740fb667fcaaec28ed245d8b2876cff2d670b1b5e143fc43ca8e105fff2b64",
          "sha1": "cf96141cb6b205133de04c2464ac719c33f788fd",
          "md5": "987cadaef480b0678b5831e0fdcb64e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "ac3a2b1575af2b838e721f9ed2ed3ce7083a217fa9481fe4fb62264d79bae74f6587bf88cbf9d1abf18fd337183bcb9a9d3c932b561c45ebbee77db700568dc2",
          "sha256": "d8d34f1fe024d140aa5646dfc173297dbf2c0d419554035b31889bad7e2f6ac9",
          "sha1": "6d75524fd741d44ffd09c7c20868803c682f4908",
          "md5": "4dcc566c16f04a59c93a25a9c10a09d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "cfd7e51b7eaa4a5c05f8208ca4ea2070a42596f886d97eae414b048888450b24cd67064e578ac0cd8835148b653bb78c2ba5f6c2774f72ec28de05cd40dc1506",
          "sha256": "1dca1c7cb2f3f29476ce11543fe6fd373c8b3a6bff4ad8e728e71659e2a63e27",
          "sha1": "51665924891aff0d6568f73279bd3a1bae1a32b0",
          "md5": "e1ea3f66653393be58734f8f7a5a8b4e"
        }
      ]
    }
  ]
}
