{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6207,
          "sha512": "494b7a6b432520b923e2fc9b2fdb542e6878f4427746bf0c5211c90e76fbf2ac9cd03ad9f1dbeb2c917ad0e9565bd8ab9e02df8d3d7e93d3729f078c55490470",
          "sha256": "ebfd99f4c39cbe0b71b5cd79de129fb01f985082d104bf3c0cfa4117c861702e",
          "sha1": "d402b194ff2b79624d0202e9d6d83dbfde6c1656",
          "md5": "84787aab38b05c068c3675ab5604a695"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6207,
          "sha512": "494b7a6b432520b923e2fc9b2fdb542e6878f4427746bf0c5211c90e76fbf2ac9cd03ad9f1dbeb2c917ad0e9565bd8ab9e02df8d3d7e93d3729f078c55490470",
          "sha256": "ebfd99f4c39cbe0b71b5cd79de129fb01f985082d104bf3c0cfa4117c861702e",
          "sha1": "d402b194ff2b79624d0202e9d6d83dbfde6c1656",
          "md5": "84787aab38b05c068c3675ab5604a695"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106451,
          "sha512": "393ee7790a38a224a3065a722b9ad8f0d2c2bc2a4f0bed4dc487714772d853de12b4f35916787d0415552b024cc124a7fdc39d0ad94ed429364b864ef1d50eca",
          "sha256": "64af7acdf18f1ae49b1430df70892f6d0fa0e8a5385b783b547f801a8ece6180",
          "sha1": "bc3dee592c2377117ced54a1f7ab3928b44d8e9a",
          "md5": "67e52258dde930fac0803163e18c0def"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3593,
          "sha512": "645ffb6e94c21e0f13cfd265da3d4e746f23c203e429cb8256f8009429ce64e72f0ad3e98222b08654ce711db3fde6c19616883a70be3fe4a627fe795dad51cc",
          "sha256": "85db21cbed69b727b804acf6b0e9fdf89b629602498a8f417ecb7e6a394e875f",
          "sha1": "43c9ff8c73a9ed50551d83ed61bfc51f69633c61",
          "md5": "16bf2418a3ea8bd95d644ad34a8ade4c"
        }
      ]
    }
  ]
}
