{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "b449b45ddfa889d5622a9213cf70ba6072e908ef73c2cc991b8d385df617e9ff31163aea8cda17092e71ca4068a78d6bf250e11e4055d0a94a3bba141dcb8d9a",
          "sha256": "671ceeff3e449fc532cba586bd8e440dc6cb842ba6bfcabea3f00a18c73e46a2",
          "sha1": "44094c4cee6a98954d8ab18250fda4830e7844a7",
          "md5": "15c018dab96e5696afa7dfe727ddf5c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "b449b45ddfa889d5622a9213cf70ba6072e908ef73c2cc991b8d385df617e9ff31163aea8cda17092e71ca4068a78d6bf250e11e4055d0a94a3bba141dcb8d9a",
          "sha256": "671ceeff3e449fc532cba586bd8e440dc6cb842ba6bfcabea3f00a18c73e46a2",
          "sha1": "44094c4cee6a98954d8ab18250fda4830e7844a7",
          "md5": "15c018dab96e5696afa7dfe727ddf5c7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "6422fde26c3af97fd291d53e89b8432e10f8b6d6459523ac3a310f6e38238ac8ac81f544e8917a4c306c5fd66ca832df03f4534913b8d9ddb62c06fcbdab9c7e",
          "sha256": "5c53881c77d6ac623ba3ae2c64535f2511cd33d32a6911f7fe611cf8bc34ca18",
          "sha1": "08dd992aa635d675520e127c812ba40086fc836e",
          "md5": "7bec74a1fd2fb24ae04358b183c292db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "97a88b18cc52707c269658bf508205bb09df5e47e4ad674aec3df5aa9b1d7d0b63c5e6bf9402b00f61bee4be54050684ef370603519c48fa19054720e3cfc343",
          "sha256": "fd5512c2df40406334dfc11d6c1d9d45c9771c4c57155281e8f4e38e3b976732",
          "sha1": "aecd83612171ce18c1a2e6d2fc3db5b4b10f9926",
          "md5": "c898cc8e8676c42d7282c5bf21c9eea4"
        }
      ]
    }
  ]
}
