{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "7b4044006545a7a4de234fd37c92f60545f0a00da47a3f4f7cad5a4bd04c78af3de8d21a546d409e87acfa25ed2eba1b16de3d2e7f85b90e7defd0d950133a95",
          "sha256": "5ed059743eedaf1c669675cad596a7fcb11b459f9976c9f2f37eeb0160613c09",
          "sha1": "c3054e41df30ccb72e5227004046d6d1f6ca0d42",
          "md5": "866011ecec82db6b6da5045a50f1bc69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "7b4044006545a7a4de234fd37c92f60545f0a00da47a3f4f7cad5a4bd04c78af3de8d21a546d409e87acfa25ed2eba1b16de3d2e7f85b90e7defd0d950133a95",
          "sha256": "5ed059743eedaf1c669675cad596a7fcb11b459f9976c9f2f37eeb0160613c09",
          "sha1": "c3054e41df30ccb72e5227004046d6d1f6ca0d42",
          "md5": "866011ecec82db6b6da5045a50f1bc69"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "e12b624d618721f672d27eb2a15d5440f5199b982edc2e2333454ff0c9e25cf64b0087a19fcc55c0b9771c3ce2ef0f5ef71a627c61da66f77baa5b7cfae674b9",
          "sha256": "aef170ead0fbe03b3def7484bb57e6a930928fc4543b71cce2e011b9aa1d6bac",
          "sha1": "cc661fff2a0dcd3a197a9d7ab70637838e197aa9",
          "md5": "2f64e651be229560078b3f82827fb1c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "a144cf3b0abf8db96a40ba67a8fcea8914d762394db503f97e512298d35a8a82cb620cfd9025bceead2570527ae067ce7ef716a91d9ff486f0d96f56b167e90f",
          "sha256": "daeb9d09805a94f77d7ecbaab54f0a379a3e5f8a98e8916a669e6370ebe85115",
          "sha1": "86cd11150fdce3db2d5f3f43bc5ed0af272ff6d8",
          "md5": "613ccebef5c15aeaeb5f689f4c7e0df9"
        }
      ]
    }
  ]
}
