{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "fce2e21cfd8166851189a37e93f5e596dd762fe9be60f8a6e6b83ea114adbece357d7f39a9b4a6701ea0f0a897e3ed497696796b5d37e00e91eb5c168402ccf9",
          "sha256": "c54101a08a42d9951d9e131675b2933cde5bb006dfbe62808978c561a5a01b8e",
          "sha1": "2f7e71f7760c158a72a69430b7716583f6041f9e",
          "md5": "1eb96db5334c03ab23e0f8a13b4c1666"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT.jar",
          "size": 6180,
          "sha512": "fce2e21cfd8166851189a37e93f5e596dd762fe9be60f8a6e6b83ea114adbece357d7f39a9b4a6701ea0f0a897e3ed497696796b5d37e00e91eb5c168402ccf9",
          "sha256": "c54101a08a42d9951d9e131675b2933cde5bb006dfbe62808978c561a5a01b8e",
          "sha1": "2f7e71f7760c158a72a69430b7716583f6041f9e",
          "md5": "1eb96db5334c03ab23e0f8a13b4c1666"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 106549,
          "sha512": "9596362948b53587c31e1352489712f39f3cdd9c2dab1011ee9116023f1a643b40d610d669428e2336d70b451203da741e63619cc118f166c289ca4ec8714b66",
          "sha256": "c532c19adb5c6b78b1043c8fecaacc03367c2f6cffe4fedeba77f24a8cc9441f",
          "sha1": "aa56fce584715f84e4c62a1362dc17757ea71c07",
          "md5": "90a5ded35347fd38efa630c8c4e2fab4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-notifier-feature-6.0.0-SNAPSHOT-sources.jar",
          "size": 3645,
          "sha512": "d5cbdd68cdbd5e8ca56b9d1d2c40ff72ac57488b00fc438bbdeac213d0acb89ebd5f3eeae8c0440471e5ec18ceb2216cdcfab01f7e1c0306182e04e4e7ff31c0",
          "sha256": "d420c9b90b09fbedabfcc1a49bdc3ce14852020e78c5a312b4f144e23c470ea4",
          "sha1": "50e118bf78987c67410e864cb390724171039ef0",
          "md5": "0aae24ae923cfa9f22eb71c769351cf1"
        }
      ]
    }
  ]
}
