{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-database",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 86839,
          "sha512": "cabdf55234fc23810a32ea1a01f7444bbbe9e9e17929fc4a972c1551b3c66f86d0ffe7149b0acc518075df55f04947a106827d76040278cdffe7084be9b6771b",
          "sha256": "1c59d10cf9162a0c4755fa608d16628bed31d9d893066985c882d6ebfe755238",
          "sha1": "d61abcd8b66dd1a8ccb43a4e85db1d881090bf36",
          "md5": "cf54d6aa92ab439d9129796e0470045f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 86839,
          "sha512": "cabdf55234fc23810a32ea1a01f7444bbbe9e9e17929fc4a972c1551b3c66f86d0ffe7149b0acc518075df55f04947a106827d76040278cdffe7084be9b6771b",
          "sha256": "1c59d10cf9162a0c4755fa608d16628bed31d9d893066985c882d6ebfe755238",
          "sha1": "d61abcd8b66dd1a8ccb43a4e85db1d881090bf36",
          "md5": "cf54d6aa92ab439d9129796e0470045f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 217043,
          "sha512": "f1de0b2c1a9fc09c9571acf21e96440b49ea353d24966d43e924fdf247842b67f0018a39c38bb9b121b795b1f1ffd981854333f61dba44d68ab040fd57a59605",
          "sha256": "84ba3b832b5f6ec4d2d05206f31e00573dc2900d4bbc8391cbc3411a8a6092d4",
          "sha1": "23acd1a64436c0db12c8ac11d85558a10a75c926",
          "md5": "19bc72728c7b2d75efa2cf9a919695e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "size": 31943,
          "sha512": "0097f428816bd36f1892dc30252bc22b511002a20e166628a71ad614a87bd9722794c444a14c493817665efa9af7dba1978756cd1b4a4343628fbf1516a860ef",
          "sha256": "2f0ef6033854d9899fc52b1c0d0f6263f02395928f103d9c77a0303872bd4794",
          "sha1": "840e0236fcd72821c5d3ceced4aac4008ab718b5",
          "md5": "acdab5a6c360a226e5840679ff1f2719"
        }
      ]
    }
  ]
}
