{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-database",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 55816,
          "sha512": "7453c8e8f576236617da4fd179ab0267592f3815116e76053248918600c4fb92a9d36ce06558cca36efd5039ed1a3f5dcd282221fe4f15380ffd9d357d8cde7f",
          "sha256": "37947959fa4be347f6af9a0ed32e8391565b6cafba6de6c741c71d56e8dc3187",
          "sha1": "791e3f4ff9bafe4398dfdf4555bc0a695e96345c",
          "md5": "213f995ce756a239fb39abd2607f45ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 55816,
          "sha512": "7453c8e8f576236617da4fd179ab0267592f3815116e76053248918600c4fb92a9d36ce06558cca36efd5039ed1a3f5dcd282221fe4f15380ffd9d357d8cde7f",
          "sha256": "37947959fa4be347f6af9a0ed32e8391565b6cafba6de6c741c71d56e8dc3187",
          "sha1": "791e3f4ff9bafe4398dfdf4555bc0a695e96345c",
          "md5": "213f995ce756a239fb39abd2607f45ff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 169726,
          "sha512": "99b4de2e73e7b2e65b95313043d7fb66996a8fcc30e3c42c18eb524d0c52b2554ba6fc4b58bb406ac3e18a77bc274c50937420726607cb6bdc1dcf02072a8269",
          "sha256": "9dbae1175673afc79ec3e84291dba33c30ecd016adc4af266e04df0083f35a79",
          "sha1": "b613433057c4225dc0d3c155f0b7318f45c06b56",
          "md5": "8b3df2f8cb3e1d649ba8781cb36185ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "size": 20812,
          "sha512": "6c42246d91644e246fca998d313f506431418714b7ec2454c9da1583a6b6f29cb5c27f828aac11d6d6c37c458beb447b673ae97a1bcfc9c09fd7294880f9ab45",
          "sha256": "2c4a079d0eba40be8d36727c2548e62060aa48c37089bf02bf9962829e68e555",
          "sha1": "1777ef61c09ecdba6f302a4c05dc0d5da4dad21c",
          "md5": "9dea14207fadb1d251c2a1aba2e1cf68"
        }
      ]
    }
  ]
}
