{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-database",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 86839,
          "sha512": "ababe504dbbd05158fa95f2c520bb87801e210b195bd465a182b4cc805e0ca91df3fba5aff2dbbef216859d989163981ce99d4e2387188c3f1a7d0dd80bf10d0",
          "sha256": "e7565524862d135400e26277ebad387efe80a86b45d3637084e19a009c0355d2",
          "sha1": "2dc01ad2092a52cba97977cc1307c4c72efc1d3d",
          "md5": "15e0891e9f0e79e80890b19340c49b31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 86839,
          "sha512": "ababe504dbbd05158fa95f2c520bb87801e210b195bd465a182b4cc805e0ca91df3fba5aff2dbbef216859d989163981ce99d4e2387188c3f1a7d0dd80bf10d0",
          "sha256": "e7565524862d135400e26277ebad387efe80a86b45d3637084e19a009c0355d2",
          "sha1": "2dc01ad2092a52cba97977cc1307c4c72efc1d3d",
          "md5": "15e0891e9f0e79e80890b19340c49b31"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 217043,
          "sha512": "429dfeb1f56ae83f2cd4b7f7fbc18128b5459a280536ca44fe6a3b3018d6f02eee2d8d681e44f205a58e68b38574a051b592c55b2bf74b373129538b7c95387e",
          "sha256": "e597069e92990706f050634a86dbc9710d63de1152be7d2b38a3a3963c0c8566",
          "sha1": "5548fa0e4db8428b947257fc73a9f00ad0b8c21c",
          "md5": "a512d74427a1251c3291619a45af76a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "size": 31965,
          "sha512": "5f2406e92ee1117fdd8297d788d4267e9e40e93d11f8e87ed1d0682b72e8a646ffe2584fdb2af2b8225cd5a7674864269850bf31c9b9d850c0ad8104908c768a",
          "sha256": "ef4be68e438ad7d324aad0adc971e1749afbcb945a3278de6a49ba24b3d6e892",
          "sha1": "5d7eee634ca10fe3823808590bea626f394bfce2",
          "md5": "a858fc54db6043c7ca61e8a083d0a838"
        }
      ]
    }
  ]
}
