{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-database",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 61420,
          "sha512": "0bae8cbc5cc12f5cb8051912fc43ab8b3504182b5c0c1add018d63f199e0b281dd4d994577a9868b6c6fa819e4fee5584aa785d65731685cd57c444fcd1d9b7e",
          "sha256": "c6e8cb04de3bf36749d88e291c5e60c27da9a9aa8057c5b1a8bf8d9189f0e69e",
          "sha1": "469adddf72c2298b2c16ad1f80f42bad17a2e91b",
          "md5": "8e1862326b03a062481e886a0a549b6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 61420,
          "sha512": "0bae8cbc5cc12f5cb8051912fc43ab8b3504182b5c0c1add018d63f199e0b281dd4d994577a9868b6c6fa819e4fee5584aa785d65731685cd57c444fcd1d9b7e",
          "sha256": "c6e8cb04de3bf36749d88e291c5e60c27da9a9aa8057c5b1a8bf8d9189f0e69e",
          "sha1": "469adddf72c2298b2c16ad1f80f42bad17a2e91b",
          "md5": "8e1862326b03a062481e886a0a549b6a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 190446,
          "sha512": "7554d1928353a54d772615d55a776392cf327a669766ced627b051bdd2f318f13ae82c9a715c20e665e6bd7a87b9438f830c30da707a18714936f5b08ab8c0ec",
          "sha256": "15470cae86f2a09942e21c0a1bb50a8583350e3f2ab667415cd775042d74561a",
          "sha1": "9bfd1f282230705ec1338d4793d9d3e9bda4792a",
          "md5": "5385078b70f89e5d34d0ad5279ec44ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "size": 22897,
          "sha512": "f80a151bfeff8bcb8b9a83cdeb1176e54ac33e4015a7142866e7353f5d31628e49551ebbd9cece67cd4ec68a5380c97a758217bfb0223e8071c5456fc6617a69",
          "sha256": "64bb2ccc83d04c1640a30db26f4e45cd64a40da0428f8ebf4d39b6505e7c5ad6",
          "sha1": "20cd846e412ae7896ff0b8ddce8ea9c39d820931",
          "md5": "7c309e3519f8100424b6b3443d7c5b62"
        }
      ]
    }
  ]
}
