{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-database",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 55816,
          "sha512": "35fb21a86d048bf86d60834fa10137b5807053199a032e136f9d276ff258100fdd579200644699c36aea314fa24c33e4348309d6f2bc8329293f1e446ae2cf45",
          "sha256": "f586adbb9d5b203cf9d91b51ab1409f1b86310ce0dade0a8618b737d8d35a039",
          "sha1": "9307af310f3662f5bc5f9ca98377d9e49a0c3d91",
          "md5": "2702f82241720030e9bd6970fb3e4ec1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 55816,
          "sha512": "35fb21a86d048bf86d60834fa10137b5807053199a032e136f9d276ff258100fdd579200644699c36aea314fa24c33e4348309d6f2bc8329293f1e446ae2cf45",
          "sha256": "f586adbb9d5b203cf9d91b51ab1409f1b86310ce0dade0a8618b737d8d35a039",
          "sha1": "9307af310f3662f5bc5f9ca98377d9e49a0c3d91",
          "md5": "2702f82241720030e9bd6970fb3e4ec1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 169726,
          "sha512": "2a1c7d0d348d7cf7274e93f98b9b693adfb944e5318671187aec77224f7c3961953830afe74609ccf6fa35b86f9f66e1d368958e1fb41028a9551fc184ca3797",
          "sha256": "6fc388bc1f61d78f7a548ddc8158cc0e8864e276114e6949ca80dba426b1d0d3",
          "sha1": "bf6897573fe028831a8c8fd53a80eeecd8232229",
          "md5": "c72fd6aa5cd95e9ee1a6e5d40a8f7883"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "size": 20812,
          "sha512": "6ac35796eddca0611dbc7365c291db0088df3f1d56e05fe48618fe55b3e41d9bdb2d4cf1172c0a725d1d61daee164d0262af1e5f5d3d4870dee10a4f496dc391",
          "sha256": "c4c8e140a305413471a4891b10b92476d55fc0180a966f23f38009b88489b7a0",
          "sha1": "4e79fa9932dfacd1e32db4cf1168edef7f500d1f",
          "md5": "65685bc456e6765fad205502f8888e21"
        }
      ]
    }
  ]
}
