{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-database",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 61420,
          "sha512": "dcf6df943d279600c1c157b1dd7c229fc0d2252e5bd4bc8d2013f87f9c73130a269f3b2ec4cb01b1d4047fb27a3d001e5232162119c833d5d101bd87c7348670",
          "sha256": "319d437c9a9204b1e848e0f51b4cddc0b151d32915bd911dde97c50d3a72cac1",
          "sha1": "b4e00c28084b79af26be887c8d6dbf39fa67f2f6",
          "md5": "3bc00700f359d5b3d2d5db53cc715f20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT.jar",
          "size": 61420,
          "sha512": "dcf6df943d279600c1c157b1dd7c229fc0d2252e5bd4bc8d2013f87f9c73130a269f3b2ec4cb01b1d4047fb27a3d001e5232162119c833d5d101bd87c7348670",
          "sha256": "319d437c9a9204b1e848e0f51b4cddc0b151d32915bd911dde97c50d3a72cac1",
          "sha1": "b4e00c28084b79af26be887c8d6dbf39fa67f2f6",
          "md5": "3bc00700f359d5b3d2d5db53cc715f20"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 190446,
          "sha512": "7dffdc70dcfd660448f6359ead503b7034dae6a61866adfebe9be615f236f7d3ba2ae7673accf097b4e665012989fd4b526a3b202b3b022dda26fee2701d130c",
          "sha256": "010e47fccbecadd61b0de305da6d013ca4709fab9929d26fe39999c4c101a779",
          "sha1": "db055c4f6e03b1c2d0b4fd4070b03dfa90121d2c",
          "md5": "4add87ff6f4183a054a4ba4bcf369500"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-storage-database-6.0.0-SNAPSHOT-sources.jar",
          "size": 22897,
          "sha512": "3b071bf7df3a1801e21db781e9a641998e8f618535ca894697cc01194895b44a5413f5dffa100148739eb155028192c311847f2097b45d40a62809da820e16d0",
          "sha256": "92522ba2b1e2c3787b067af15863450323155d9de49ca02255dc6b068a9d3d76",
          "sha1": "09633439a11814c15efd02489c894bc31de52dbf",
          "md5": "ae2c54c0acbc733c4f5c5be88a3c604a"
        }
      ]
    }
  ]
}
