{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-paper-1_20_5",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "size": 5967,
          "sha512": "72b0d08546e944c9cc257525e52eaea30991143408c9f6488098d9d004946208d1a91102662fabff27aa4b14dd5473129379b86f0be9d40b76edc84ae5382ef6",
          "sha256": "f1d1befdf6979851c7d25ef506fa1e4f229505174d485790047d7141c893158c",
          "sha1": "7f0bf97c31e98a8952a8632588b371b9b3570a99",
          "md5": "6918919eebdb65ce98ae35b451a1bc74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "size": 5967,
          "sha512": "72b0d08546e944c9cc257525e52eaea30991143408c9f6488098d9d004946208d1a91102662fabff27aa4b14dd5473129379b86f0be9d40b76edc84ae5382ef6",
          "sha256": "f1d1befdf6979851c7d25ef506fa1e4f229505174d485790047d7141c893158c",
          "sha1": "7f0bf97c31e98a8952a8632588b371b9b3570a99",
          "md5": "6918919eebdb65ce98ae35b451a1bc74"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 99922,
          "sha512": "2b664b7f751a7f1fc8c8c9a4aa04ae6598189fc7b89405735e78246f7b0f776430432f473b4d3fa7e150ad8a92941c0e91e3134c36a72e81d81644cc0fdced3d",
          "sha256": "f1d0a18f65111c2a69bc1bf3cd99b2d66cbb0b617df7172c96bfee22349170da",
          "sha1": "a1ad1c43d4e36cac7d02856cbe0c87cde12d4d26",
          "md5": "186050075ac5d53d655adb4d2c7b1625"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-sources.jar",
          "size": 3145,
          "sha512": "7008cad71d4d9b7c8e4599244d4221ce348331991e69d335afad05d28804cc38a2fc9031d3f311d735ebc6bda404605511bb8806ec16b9083f0f049a68f8778f",
          "sha256": "bdf309f15b79352c0e93c5018deeb66ef54bc4b7f61ba519e75fcc41f57c4e1a",
          "sha1": "427daa949c91b2ec30f5b42ced65c0349fe9396b",
          "md5": "239f22b5ef50b4f8ac3fcace4bf35e97"
        }
      ]
    }
  ]
}
