{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-paper-1_20_5",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "size": 6251,
          "sha512": "90b401c9d15b46c39fd0052a9678b5e31ce396362ea9c638dc47c6ee6b1d5f6fbc61541904ecd51ca5a9b098a96a994bef92eee8b6603241a318abc2d42c4113",
          "sha256": "5b45df5028ce6a1d1b095f45e79327da1ca3a74c5c8d5f768fbb1e9c05e50e26",
          "sha1": "5040cc4581fc571cc927398eb9c36c5a5c811464",
          "md5": "3e2831ee1f1d35da88cdc28e8a3f13c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "size": 6251,
          "sha512": "90b401c9d15b46c39fd0052a9678b5e31ce396362ea9c638dc47c6ee6b1d5f6fbc61541904ecd51ca5a9b098a96a994bef92eee8b6603241a318abc2d42c4113",
          "sha256": "5b45df5028ce6a1d1b095f45e79327da1ca3a74c5c8d5f768fbb1e9c05e50e26",
          "sha1": "5040cc4581fc571cc927398eb9c36c5a5c811464",
          "md5": "3e2831ee1f1d35da88cdc28e8a3f13c8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 100122,
          "sha512": "27c0f11fc5ff9c8adc1c25c2e537b026c3e56861521242932312c332147ea3cd52a1b8757b0c6fc1977376226da26b6880e508fbd64392808ade469027035e93",
          "sha256": "7c277e086bc8c5a40e212f16b03729a11523a118a777ad75a8a4af9129b44b85",
          "sha1": "aa537816af91888a36ac4196c737f8d49ebaa313",
          "md5": "fae1efc6b225e3854c8b5654a7971415"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-sources.jar",
          "size": 2451,
          "sha512": "61605fc242ecbb89908b37ff137f1c4b678ab49b2112e986ae46021c7b426f7b59eeb5d68614e760f31587cad14a3b0d36393e4aabc7cbb5b5468dc651581827",
          "sha256": "f405e97640ce24abd123f9307cbe372ddce561190242f4f92552045e87a04aa3",
          "sha1": "de49bd3ca5f845a26c1dbc0f0dcab72c8d14badb",
          "md5": "d42574468aa02faf66d25cea3f273e77"
        }
      ]
    }
  ]
}
