{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-paper-1_20_5",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "size": 5967,
          "sha512": "095ffd675b758165411f86066914683b17ea7a6159474bd864d9f66e889c0f527714f33c99d05b236c847c0457acd8e599608764fe3894d0ddd8750f5a2049da",
          "sha256": "405d12cfba509b0dc21d3205a0be4474c42f7a0cd540e5df84ac3496a8448dc4",
          "sha1": "fd8c17bc3eea24ce7db8281ccd15988c5651f48e",
          "md5": "f6a712c9c142b9ac0470a899e4cc8b32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT.jar",
          "size": 5967,
          "sha512": "095ffd675b758165411f86066914683b17ea7a6159474bd864d9f66e889c0f527714f33c99d05b236c847c0457acd8e599608764fe3894d0ddd8750f5a2049da",
          "sha256": "405d12cfba509b0dc21d3205a0be4474c42f7a0cd540e5df84ac3496a8448dc4",
          "sha1": "fd8c17bc3eea24ce7db8281ccd15988c5651f48e",
          "md5": "f6a712c9c142b9ac0470a899e4cc8b32"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 99922,
          "sha512": "f7175a44d314c771404e176b29dcbb7d4284bd2ba73fe699860a4419b99d02a1da77c44510a59e375e8c6fbd651a3d64a498e94d19a7f20502dae79f83366280",
          "sha256": "26cdf9358e89826412cd18f257a17fb01947557ff03ccba0b4821a1404d79a60",
          "sha1": "7a2a9e902c3cd219ced8a154474cf03d329bac21",
          "md5": "5c6d52cdbe6091362bc2ea24af07b6a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-paper-1_20_5-6.0.0-SNAPSHOT-sources.jar",
          "size": 3145,
          "sha512": "a363fb4b16a3080af6386bd0e1dc4e3963aa4185dc489730df04b259a9b3c6cd77b2c1b714e845490e2e35aac16ce6d75df047828fe528aaa69b4cf9a157a1b2",
          "sha256": "013f9b85e9a8561b9ef87330ec725ca9c5f458f0b722080b56ce7b3879f3d377",
          "sha1": "c4e98df409745043a7d88dcab6f7a7013b4cfa08",
          "md5": "ab706e1f277a2c136c06444f6b7cd928"
        }
      ]
    }
  ]
}
