{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-paper-1_21",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "size": 2131,
          "sha512": "7b85cfa4c394fcbb2ae3824d4a4a849735f3b1de3a30a5dc4af088413e0b54842278a446183c2edc64458aec998e8d0b7c9054f1a17c7465fab37d31a997372c",
          "sha256": "048ff57399f33adc02fb7b301d2e83b26fda77086a03d0a77cb572720ab02a10",
          "sha1": "dec51c5abcb3d8d9ee2c0caac94128930081c737",
          "md5": "1b12f9e076d9e317d3db6c89508b84d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.5"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "size": 2131,
          "sha512": "7b85cfa4c394fcbb2ae3824d4a4a849735f3b1de3a30a5dc4af088413e0b54842278a446183c2edc64458aec998e8d0b7c9054f1a17c7465fab37d31a997372c",
          "sha256": "048ff57399f33adc02fb7b301d2e83b26fda77086a03d0a77cb572720ab02a10",
          "sha1": "dec51c5abcb3d8d9ee2c0caac94128930081c737",
          "md5": "1b12f9e076d9e317d3db6c89508b84d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 92754,
          "sha512": "68b000362159a7f767b4811e84b11f095ef45c6e3d6a6c2881a006d0e95f74610f47f0997d857e52796dc5aee59991498f7bccd1865dda193a7e72ee6b4e188f",
          "sha256": "e69752d2fc22a88d4eb686701a5ad3e6ed9f96bc02f74d0af3a2978bf7a202be",
          "sha1": "53bdfa3d49518cc0a4e047a59b1a1d55894deac6",
          "md5": "5754caca4e406f1c7771568c16703910"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT-sources.jar",
          "size": 1424,
          "sha512": "41d398586e8a1e614289c27206baaf2c96f531f6488c652b8a06933df341aa3b9fe17e20be20cd7444ad40fb22b696cc3980e221477797f4aeddb3fee16b360c",
          "sha256": "a3f996f391128bbe9835829e865499f1cbe3951914c9d121a46efcdb4adb7570",
          "sha1": "d1d367799383804dac9428f45eaa5da637553fcd",
          "md5": "8a80a3f040a8a07b35c14755b9391588"
        }
      ]
    }
  ]
}
