{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-paper-1_21",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "size": 2018,
          "sha512": "b5e2b2e1d5929dd6f7b61d3a3972e6bcb4db10d91686d22c8963b2341794582d155270f2f7ebd63f78902dc794c073e26c8e320be9690af9c149d36294b808de",
          "sha256": "8c3302e3da956cdbf0368ac73655955f80e5ecb0301e1fc3e4093981ba2a30b5",
          "sha1": "774ba6f931d92dd4ec899fd2b6d29da6b55d72d1",
          "md5": "b871aeaf3b6dc27248b8bb4f43c4b8e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "size": 2018,
          "sha512": "b5e2b2e1d5929dd6f7b61d3a3972e6bcb4db10d91686d22c8963b2341794582d155270f2f7ebd63f78902dc794c073e26c8e320be9690af9c149d36294b808de",
          "sha256": "8c3302e3da956cdbf0368ac73655955f80e5ecb0301e1fc3e4093981ba2a30b5",
          "sha1": "774ba6f931d92dd4ec899fd2b6d29da6b55d72d1",
          "md5": "b871aeaf3b6dc27248b8bb4f43c4b8e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 81459,
          "sha512": "7a4801a787bf0eedebf801bda354c28e9e2cc965321d56ad6eb47c04e7916f89c0114cff5ed40c040d65fbc82d6fd4c1ebbf421b14db6a7b978adce373e7bd04",
          "sha256": "3e1033887e9004b08642ac8f31f31519422eb3d8302f32c8cf74b5859efefc41",
          "sha1": "a7022fead22b96d2b53f06fa71f4f523468ea7e8",
          "md5": "90cf196e61547b9c4efcd6528e0beaac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT-sources.jar",
          "size": 1360,
          "sha512": "bc7f80a6258be5b0d74efcbce0c82a73020883443f68454f581e41863a1fe1c0bdf29515ffa7d60a9c3ae5d382faaedcd390116dcc8a55697111a7aefabc0b1e",
          "sha256": "3fc4eb490db2ddcd42f600fdf8beb64c31f05c9fe9b0589fa1ff6d6d2e578bd8",
          "sha1": "afae724d9a4e0330ae07e762e0ddc9f0a10dcadb",
          "md5": "d30f43493d3a96b87e20488a773472a6"
        }
      ]
    }
  ]
}
