{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-version-paper-1_21",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "size": 2018,
          "sha512": "f8995a98a8d3670f4270553a3773e5055262b3a7e1bfecc8039d2bc434aed23ca5e8b7f42b38414b1daa2d2199f38841197cb9491a9961922eb8dd92f6f626f6",
          "sha256": "7f7e2d8586c8f9877b15fc63a23691f2ce7e08d09b0fc0d5a9799e39e3cd6024",
          "sha1": "0dcaaba38b36cfe2231e6ef7d90d4acd09c76c67",
          "md5": "a6a2b22b43b509ea8a994193228de7a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-version-common",
          "version": {
            "requires": "6.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-alpha.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "4.0.0-rc.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT.jar",
          "size": 2018,
          "sha512": "f8995a98a8d3670f4270553a3773e5055262b3a7e1bfecc8039d2bc434aed23ca5e8b7f42b38414b1daa2d2199f38841197cb9491a9961922eb8dd92f6f626f6",
          "sha256": "7f7e2d8586c8f9877b15fc63a23691f2ce7e08d09b0fc0d5a9799e39e3cd6024",
          "sha1": "0dcaaba38b36cfe2231e6ef7d90d4acd09c76c67",
          "md5": "a6a2b22b43b509ea8a994193228de7a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT-javadoc.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT-javadoc.jar",
          "size": 81459,
          "sha512": "71421f2ba6f36f6e412d30975fd9c36dbaaf40a171b05042797559b5cda349210eff42efbe1b26efc4a958e4a45595b988957c1d644fe38a601d993de835c229",
          "sha256": "9972c9d916b1fc32259eece6416e56883582561636d88eae9577c7751523e648",
          "sha1": "d4a4f8e74178c399e66245e13e5415e2f16e57b0",
          "md5": "ae48832efa51d60808d4884fc25faf5a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-version-paper-1_21-6.0.0-SNAPSHOT-sources.jar",
          "url": "box-version-paper-1_21-6.0.0-SNAPSHOT-sources.jar",
          "size": 1360,
          "sha512": "573675d0de8e0622d6b7cd1defcbf68bd2c349596fc7649749493f177f52bdfaef55fd99496d6b90c928bd3fb68a59819fb072485a0347fff689cf8869f674cc",
          "sha256": "cc7df1808debf5e77ee8faa701469d0eba4f8518357c731bd18160c7c152b5e7",
          "sha1": "0a3c5c2dc1955705b266726f3f73d3cc4a70af1c",
          "md5": "a76b2a76ac28f49c165405a28eacf1ad"
        }
      ]
    }
  ]
}
