{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-autostore-feature",
    "version": "6.0.0-rc.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.siroshun.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-rc.2.jar",
          "url": "box-autostore-feature-6.0.0-rc.2.jar",
          "size": 53010,
          "sha512": "ef92ebd97857b37974d0beff8c0a0301698aecdc3f2911d246f1a1f7189e1b8cbfff770fe450e180ccbe7d8d718a0de256ec72608cc2c6aae7064a45e5df6408",
          "sha256": "b406d9a32416f220f205daeb2eb9f241d7dc6bae9f5a524fb46a55eb6ee36a56",
          "sha1": "d76e136f09a318e5cbc3461889d53adbbd137b33",
          "md5": "b7108ff5edb509cc4d1ce4d5ccf92f1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.siroshun.configapi",
          "module": "configapi-format-yaml",
          "version": {
            "requires": "5.0.0-beta.4"
          },
          "excludes": [
            {
              "group": "org.yaml",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "dev.siroshun.event4j",
          "module": "event4j-tree",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.github.siroshun09.messages",
          "module": "messages-minimessage",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-rc.2.jar",
          "url": "box-autostore-feature-6.0.0-rc.2.jar",
          "size": 53010,
          "sha512": "ef92ebd97857b37974d0beff8c0a0301698aecdc3f2911d246f1a1f7189e1b8cbfff770fe450e180ccbe7d8d718a0de256ec72608cc2c6aae7064a45e5df6408",
          "sha256": "b406d9a32416f220f205daeb2eb9f241d7dc6bae9f5a524fb46a55eb6ee36a56",
          "sha1": "d76e136f09a318e5cbc3461889d53adbbd137b33",
          "md5": "b7108ff5edb509cc4d1ce4d5ccf92f1c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-rc.2-javadoc.jar",
          "url": "box-autostore-feature-6.0.0-rc.2-javadoc.jar",
          "size": 110259,
          "sha512": "a549d07102f9e1efd6ad3037250cb9457fdd974c28a880b75c990c68403e1d499262367550f1bd3a0ce22a90870f4e7e23fafc81b547e9e23024f2a2bfa035dc",
          "sha256": "87f3f69239cd7034bf7621df41c9fe3a43643a53e8ed14274d88b7ac93d17a9d",
          "sha1": "de58bba6be06a8e1ca063a2447dfa19372442bd8",
          "md5": "dbc1f1bb153db8e4b6f2977047e2bda5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-autostore-feature-6.0.0-rc.2-sources.jar",
          "url": "box-autostore-feature-6.0.0-rc.2-sources.jar",
          "size": 26617,
          "sha512": "4140de32f56e9feda3edda95571f765626c9052c4fbe27684affb0595000210228c6db3d46d99491442a00c7ce48ebebec9d82ee0a75986eeb2f6de152d2caa3",
          "sha256": "084e86af2b5a16507e72f79942ee1976923fae237ccd74280ddbb306072f8914",
          "sha1": "c7d02f303e66029251527ccedbdfc4bce7465e63",
          "md5": "0e6e8e4fb800c594f598c015eb41a70d"
        }
      ]
    }
  ]
}
