{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-storage-yaml",
    "version": "5.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.3"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-5.3.0.jar",
          "url": "box-storage-yaml-5.3.0.jar",
          "size": 17578,
          "sha512": "5f6045b6b0124860577254bf646c772de49082efb8a4dafe3674a9bc35a340539cd1eb9791a75daf425ea0599469bba3a11001397d27cbd5c31ccbfa6e26224d",
          "sha256": "13559e2839fc5f73a3c3877f5540e02383b549602de3c18c9cca7cb24247b996",
          "sha1": "029dca22aeac33721d26c631375a8cec002aea0e",
          "md5": "19f2008976960a1af51ca12d6e0b0215"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.3"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-storage-yaml-5.3.0.jar",
          "url": "box-storage-yaml-5.3.0.jar",
          "size": 17578,
          "sha512": "5f6045b6b0124860577254bf646c772de49082efb8a4dafe3674a9bc35a340539cd1eb9791a75daf425ea0599469bba3a11001397d27cbd5c31ccbfa6e26224d",
          "sha256": "13559e2839fc5f73a3c3877f5540e02383b549602de3c18c9cca7cb24247b996",
          "sha1": "029dca22aeac33721d26c631375a8cec002aea0e",
          "md5": "19f2008976960a1af51ca12d6e0b0215"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-5.3.0-javadoc.jar",
          "url": "box-storage-yaml-5.3.0-javadoc.jar",
          "size": 87973,
          "sha512": "ecf5a21a9d8b2a09b9b602f39852cef0bedfb0c22db9278e13dacd9573b49e221503775aaaad91a1da1fbb92d5600254a921bdaf84cd5c3315aaac2d669a6211",
          "sha256": "601666f2fe7f0ccb4c75b7e0323fc3d969df73a7d959fc70eb5cabf4d1d453ae",
          "sha1": "0b72e32e31821a99b10701f5b5bffe494e715f99",
          "md5": "3aa1b6e5a93d528a0abaa6d20a144896"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-storage-yaml-5.3.0-sources.jar",
          "url": "box-storage-yaml-5.3.0-sources.jar",
          "size": 7525,
          "sha512": "9c6b1ad76973517374eb59864c3f73f369f4c649c79bc2d7340c83788cfd3783130eb8b76b06b11dad355148ac04081ac388d483a5fb914995f3622d87887867",
          "sha256": "5e8fd0e9766897836590ef562ce86ac395a5855f911e8196f535b7402c99eab8",
          "sha1": "e225ed2a65aa2ac659b80807babf8d0262e52b33",
          "md5": "8322c37831515c29935a0c6c93175a2a"
        }
      ]
    }
  ]
}
