{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-notifier-feature",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.4.0.jar",
          "url": "box-notifier-feature-5.4.0.jar",
          "size": 7503,
          "sha512": "b1092458b66cdcf9583600bce1d23d5c86e556760c900e52d22fdbc8443f774968664462e4659853be969595c6c34fef2168c3a7cbd366d3419b5cf465246302",
          "sha256": "c1a17d122b4897cd2e16aeba2d22cb2026defba667f2975f2d4764642601954d",
          "sha1": "b734630a91934ec6535d21f7deb5a6808294c468",
          "md5": "9adb03e92c69be00b806ca2662575787"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-notifier-feature-5.4.0.jar",
          "url": "box-notifier-feature-5.4.0.jar",
          "size": 7503,
          "sha512": "b1092458b66cdcf9583600bce1d23d5c86e556760c900e52d22fdbc8443f774968664462e4659853be969595c6c34fef2168c3a7cbd366d3419b5cf465246302",
          "sha256": "c1a17d122b4897cd2e16aeba2d22cb2026defba667f2975f2d4764642601954d",
          "sha1": "b734630a91934ec6535d21f7deb5a6808294c468",
          "md5": "9adb03e92c69be00b806ca2662575787"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.4.0-javadoc.jar",
          "url": "box-notifier-feature-5.4.0-javadoc.jar",
          "size": 95712,
          "sha512": "4d1445b680bb77d589bd448b3b39720f0a655944dbb29c379c7164c0bdbc2c3e27204e487ef7d252fb508d4770c96bfe479f40b002a38a0ff0e189882710e553",
          "sha256": "96286c7f8e4720537eabe6fae7e38a89dbc4a25a3ee2918e2bc4d31195dc172b",
          "sha1": "430de34b2ec946290292b62d333955ad30e49255",
          "md5": "050377fdb23374e930f3dd131b067b12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-notifier-feature-5.4.0-sources.jar",
          "url": "box-notifier-feature-5.4.0-sources.jar",
          "size": 3874,
          "sha512": "3740f29b5d498a9dc683fefc0fd9a295d7079d2321c1bdbb41c1c33291fe2e4f28808f68123292bd847a538ccc40ab07ca0522a1884957f60827a9d7f5c69f66",
          "sha256": "1e27ae2ea21d847585f204c7dced9e052ffbc53c6af9800095b24223735a4629",
          "sha1": "1334c21dd7db9b61b9fa9a0532f72513635d0e65",
          "md5": "2024c3bd5f323ce9512dc8eaccb60d3c"
        }
      ]
    }
  ]
}
