{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-gui-feature",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-5.1.0.jar",
          "url": "box-gui-feature-5.1.0.jar",
          "size": 73967,
          "sha512": "ccf11a10e00401ddb3ecf86e28c3802f077129269014f6df90d0e3d04d5ef8485b6d3a22d844269ed98322bf16bb3a61c0bf7de40c7ed0083e4b9a657ce8cf25",
          "sha256": "03e7384fe5f056fabd74dbce84a7779be9a2c94a24241be8b8fb6ff3d2bdfdde",
          "sha1": "804c1f4546bce68bc6122a7969331ca288d23c88",
          "md5": "100e76a60faa09d05268666485e1c988"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-gui-feature-5.1.0.jar",
          "url": "box-gui-feature-5.1.0.jar",
          "size": 73967,
          "sha512": "ccf11a10e00401ddb3ecf86e28c3802f077129269014f6df90d0e3d04d5ef8485b6d3a22d844269ed98322bf16bb3a61c0bf7de40c7ed0083e4b9a657ce8cf25",
          "sha256": "03e7384fe5f056fabd74dbce84a7779be9a2c94a24241be8b8fb6ff3d2bdfdde",
          "sha1": "804c1f4546bce68bc6122a7969331ca288d23c88",
          "md5": "100e76a60faa09d05268666485e1c988"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-5.1.0-javadoc.jar",
          "url": "box-gui-feature-5.1.0-javadoc.jar",
          "size": 260380,
          "sha512": "b6ac2e86fbac57e45a580b6a61416b8e4f1bd696d639b95a822e5a96d65ea4c0dd82c8e7e0d97a3ad542fec91a4e36a1562cabcf1bb9d7bc36b60a5e0bb4f96e",
          "sha256": "3a4ba96f3360310ed297ceddc6de9e6739f260c666cec99d84c05b204c4fe7fa",
          "sha1": "0e71cb32d1cc5107c82edee15e8dadcf373230f0",
          "md5": "0e1f53e8e528c2bb784bec15b5f2d9a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-gui-feature-5.1.0-sources.jar",
          "url": "box-gui-feature-5.1.0-sources.jar",
          "size": 35308,
          "sha512": "9b7409703a393fae4a7e69d6cd668514b07a53950ed5ba8238d6c3fd130c4e2df1e50b47d85810775163daa31833d0cad6f4dde0159d35f841e704ccf5732cfd",
          "sha256": "a1581c9af035b43c55bbdb82141f26e1bc906767640c79033a724b7208aff5f2",
          "sha1": "c4b67e29e709f077c19ac3db7b68b6386b1592f1",
          "md5": "f8af97de115f6d96f0511caaacc8e8dd"
        }
      ]
    }
  ]
}
