{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "5.2.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-5.2.0-rc.1.jar",
          "url": "box-bundle-5.2.0-rc.1.jar",
          "size": 13995,
          "sha512": "6379db1ce038bff885b06d0c8f054f99772e72883c6d9b6b0ea0ea408ac3b6ce1976ac508874df8c23c543d193406d915f5e08c8b06b56c1279e66aa8e794dc5",
          "sha256": "38df60150dfdba208dea25965a75603de4aa1c87215fbbc845b72af8d4de62bf",
          "sha1": "5a3f9bb334e2bee058f99b2a9caa0a399fffedfd",
          "md5": "3c8ffacddb792e5d0d205758602e783f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "5.2.0-rc.1"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-5.2.0-rc.1.jar",
          "url": "box-bundle-5.2.0-rc.1.jar",
          "size": 13995,
          "sha512": "6379db1ce038bff885b06d0c8f054f99772e72883c6d9b6b0ea0ea408ac3b6ce1976ac508874df8c23c543d193406d915f5e08c8b06b56c1279e66aa8e794dc5",
          "sha256": "38df60150dfdba208dea25965a75603de4aa1c87215fbbc845b72af8d4de62bf",
          "sha1": "5a3f9bb334e2bee058f99b2a9caa0a399fffedfd",
          "md5": "3c8ffacddb792e5d0d205758602e783f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.2.0-rc.1-javadoc.jar",
          "url": "box-bundle-5.2.0-rc.1-javadoc.jar",
          "size": 82141,
          "sha512": "1637d6de99ca169c6a3bd78fc43dfe1eb0c7c1cb0c1b414e6e187ca35c83021905a0713314ae217d9702034a305001e258586c7795f78b3a74bd09f62fa39d74",
          "sha256": "d3165f367d9a21118c6254c85defb007d864d55b65d947d6a1278d71fe59b2e7",
          "sha1": "1ee27cf4d2abd70b8c78ce9c9c452c979c8b47d9",
          "md5": "a3e61190c7da58887295926983bbb509"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.2.0-rc.1-sources.jar",
          "url": "box-bundle-5.2.0-rc.1-sources.jar",
          "size": 11801,
          "sha512": "fbfdcc7f66633bab50d143d1c497597b56b1663a1b393cbfc9e6cce4d47f226c6c306027408abae2ef08e128d2c25746b30c2f0eb2474d27b424a0d951ce4b39",
          "sha256": "2218ddd3965f0290aff12db4cd51c08fc67e6c3a00d65a99ab25746c7716f15d",
          "sha1": "de4d71197dba56f407b55a019a40c2110d7801a2",
          "md5": "dedb87aabb3237f79e058a49e0a39f41"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.2.0-rc.1-all.jar",
          "url": "box-bundle-5.2.0-rc.1-all.jar",
          "size": 819616,
          "sha512": "69ea3fc5448dcf1c7ee7f2a1a61344b93aec172ea9ec7465692b2f33c47c4c47f718d6d0900be517a33be8d3e1ec80f7d4f8af627746dbb617b26c167443c68a",
          "sha256": "952903208c75f84c78a016405a6df3c6225de38116b9e0097dc12984925fd9a7",
          "sha1": "87d188a1871747ed51b257266d427acff85499de",
          "md5": "2d5bdd9333a43bb32a06ca830ca2c217"
        }
      ]
    }
  ]
}
