{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "core",
    "version": "4.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-4.4.1.jar",
          "url": "core-4.4.1.jar",
          "size": 86976,
          "sha512": "e1a379563f35aae728e8e48495855fb89b9c266783c0ecdf9d1bf474eba50b05495ae49e5ff6b027dae5b22e7fe74cf3411206c8692a6ba7cf982bd9f0d5e553",
          "sha256": "12d6b7448bc3ba86271090f10d1e7e308563104b00e6215ddf7dc0dbc8c061a2",
          "sha1": "7fee013c249278c41090e8a5ed97b56811bd3977",
          "md5": "a37519252cbca2655c8879a7dd70fc91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.siroshun09.translationloader",
          "module": "translationloader",
          "version": {
            "requires": "2.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-4.4.1.jar",
          "url": "core-4.4.1.jar",
          "size": 86976,
          "sha512": "e1a379563f35aae728e8e48495855fb89b9c266783c0ecdf9d1bf474eba50b05495ae49e5ff6b027dae5b22e7fe74cf3411206c8692a6ba7cf982bd9f0d5e553",
          "sha256": "12d6b7448bc3ba86271090f10d1e7e308563104b00e6215ddf7dc0dbc8c061a2",
          "sha1": "7fee013c249278c41090e8a5ed97b56811bd3977",
          "md5": "a37519252cbca2655c8879a7dd70fc91"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-4.4.1-javadoc.jar",
          "url": "core-4.4.1-javadoc.jar",
          "size": 280044,
          "sha512": "c43f02cf70091ef81eb941a316cfb1afc28965649ab83011020f8ba4e408d13630325b00b8b406978ecba026bcbd12a9ef046600f0f066d48ad61b1344a76d72",
          "sha256": "7dd91d4ed2a18ff2dd33e8f342479ef5e92ccb325925b77539045d9e1226c3a5",
          "sha1": "5e66098384944b47b70412ee01c5459fba66880d",
          "md5": "3895c501a634f862d5cb8822b733efeb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-4.4.1-sources.jar",
          "url": "core-4.4.1-sources.jar",
          "size": 39364,
          "sha512": "6d3e6bc2d302efdede557f50eaaf23cb0c8f5f7657410ff7958c02fa9b74df8572b6a51e14ef7a77018a940b4e2430e3c3f61be412ac1cea876ac54cfbd61843",
          "sha256": "e8397f0a662ca9cecc0d5ca9e132e1ffc8617b18de60397eacc07728e0758dca",
          "sha1": "1d7f3bf714017d7cc6322869a883fa618cd7b39a",
          "md5": "67d5efc414973d57aa820438429ba844"
        }
      ]
    }
  ]
}
