{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-craft-feature",
    "version": "5.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-5.5.0.jar",
          "url": "box-craft-feature-5.5.0.jar",
          "size": 64407,
          "sha512": "8e86f952543e5bc76c49c182febad1dc0e8948f61e5568399a3fe7600d9fa4b19950cd0e801db48275498f1eae2010540c5b3f5bc341c937d809441cce84fa6c",
          "sha256": "3ed650cef2c497c25de1a17f6b4be4c70811ef1ac76aaa1d294b12742a0e7130",
          "sha1": "a3bff8b1ba7abc74f53c9fd9e89b132c2aaba5cc",
          "md5": "ec54c3df742674576df711137c092272"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-craft-feature-5.5.0.jar",
          "url": "box-craft-feature-5.5.0.jar",
          "size": 64407,
          "sha512": "8e86f952543e5bc76c49c182febad1dc0e8948f61e5568399a3fe7600d9fa4b19950cd0e801db48275498f1eae2010540c5b3f5bc341c937d809441cce84fa6c",
          "sha256": "3ed650cef2c497c25de1a17f6b4be4c70811ef1ac76aaa1d294b12742a0e7130",
          "sha1": "a3bff8b1ba7abc74f53c9fd9e89b132c2aaba5cc",
          "md5": "ec54c3df742674576df711137c092272"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-5.5.0-javadoc.jar",
          "url": "box-craft-feature-5.5.0-javadoc.jar",
          "size": 208213,
          "sha512": "45fd5bab4ea38c28f905bc559af4b3ffdb917e95c45c038af6a6bc225a348a7e1f41b7ff944fdc7adce1a1737c1d8d099291bb0102a01612f15836234a0889a9",
          "sha256": "0b67c46831462a036aa3ac96404ecc97602b1f486712d7aad9aae2b259b252be",
          "sha1": "68e96fd08e4a3dc4049fcf173ee6cd89c74f4efe",
          "md5": "75fb2f9edaf1a294406f03254e680ac4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-craft-feature-5.5.0-sources.jar",
          "url": "box-craft-feature-5.5.0-sources.jar",
          "size": 30339,
          "sha512": "f912d1476aa90e59e0997ddafb5fe989c03044e3a724f7411b30e36472d5ad4fa0e948b723d051c383d50ce61e819180bf8210366255c3bbce03f1c075fcb183",
          "sha256": "1f645e65ee5fd1be88d8f0a4c474887d0157c1496dc08d9662764cddc2e2513f",
          "sha1": "880b2497bb473ea1f3f7b77aa1741e6600f05a16",
          "md5": "cc655806670b07d9f88bcf0b8b26b240"
        }
      ]
    }
  ]
}
