name: BoxDataGenerator
api-version: ${minecraftVersion}
main: net.okocraft.box.datagenerator.Main
version: ${projectVersion}
author: Siroshun09
folia-supported: true
commands:
  regen-data:
    description: "Regenerates data files"
