name: Box
version: '${projectVersion}'
description: A Paper plugin to provide virtual containers that can store 2.1 billion items per item.
main: net.okocraft.box.plugin.BoxPlugin
bootstrapper: net.okocraft.box.bootstrap.BoxBootstrap
api-version: '1.19'
folia-supported: true

dependencies:
  server:
    CoreProtect:
      required: false
    LWC:
      required: false
    Bolt:
      required: false
