name: Box
main: net.okocraft.box.bundle.BoxBootstrap
version: ${project.version}
authors: [lazy_gon, Siroshun09]
api-version: 1.17
commands:
  box:
    aliases: [b, okobox]
  boxadmin:
    aliases: [ba, badmin]
