{
  "formatVersion": "1.1",
  "component": {
    "group": "net.okocraft.box",
    "module": "box-bundle",
    "version": "5.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-5.5.0.jar",
          "url": "box-bundle-5.5.0.jar",
          "size": 15542,
          "sha512": "493f9b3ef956cd4b2b6a6139a5105655eea28dbfeda7072c16b6b2cf85c59fda585582b245bd722fc96f4845ae94f7670dc95843763503e54cbc58bf080f9594",
          "sha256": "3c08531a3f9065096b862cb1a8bd6dafd14eaa25c7629a58c0b11b5f6f61122c",
          "sha1": "93fa389594d8eca7f5acac5f911fe691854f4a14",
          "md5": "141a492af4e31c16f2b9409b8835f721"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.okocraft.box",
          "module": "box-storage-yaml",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-api",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-gui-feature",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-database",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-stick-feature",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-command-feature",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-notifier-feature",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-api",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-bemode-feature",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-craft-feature",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-storage-migrator",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-autostore-feature",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-core",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.okocraft.box",
          "module": "box-category-feature",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.github.siroshun09.configapi",
          "module": "configapi-yaml",
          "version": {
            "requires": "4.6.4"
          }
        },
        {
          "group": "com.github.siroshun09.event4j",
          "module": "event4j",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "box-bundle-5.5.0.jar",
          "url": "box-bundle-5.5.0.jar",
          "size": 15542,
          "sha512": "493f9b3ef956cd4b2b6a6139a5105655eea28dbfeda7072c16b6b2cf85c59fda585582b245bd722fc96f4845ae94f7670dc95843763503e54cbc58bf080f9594",
          "sha256": "3c08531a3f9065096b862cb1a8bd6dafd14eaa25c7629a58c0b11b5f6f61122c",
          "sha1": "93fa389594d8eca7f5acac5f911fe691854f4a14",
          "md5": "141a492af4e31c16f2b9409b8835f721"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.5.0-javadoc.jar",
          "url": "box-bundle-5.5.0-javadoc.jar",
          "size": 82275,
          "sha512": "0b039cbfe368000786c09fa76ccc1b54909f3efbb7dc6d48daacfaa0a140ac64a9b73a554bc0443bbce6b79885ee703c246a87004705ede46fc093fb452601e1",
          "sha256": "6ec3b0b627368a7820f223526779fd558f10ffaafcb14731264185fd2b7f996a",
          "sha1": "dd8aee5b9f10b50c46117d0b013fef2637bdea49",
          "md5": "407af245767ad9ee1602330e8be8dab6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.5.0-sources.jar",
          "url": "box-bundle-5.5.0-sources.jar",
          "size": 12687,
          "sha512": "7600d3ee0bb4e005c5b3f86d5535f3617ac1ebc13c8d772020ebbcc9e256af022652bdac37003382142574a405bc5b90b801224f968ff522241474fd90d2292a",
          "sha256": "d6d8d9f2ec2fd83e1d83260c853dd8f901fa8ab02839a01d6738b7ae90e82b04",
          "sha1": "621fdf67bf52521f57d61e1f62bef7973fb66765",
          "md5": "5f02b1206d453ae6f205474fbccd1432"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box-bundle-5.5.0-all.jar",
          "url": "box-bundle-5.5.0-all.jar",
          "size": 905631,
          "sha512": "17fa72fed6bea9b9b6e469fd6fe68f36b53b2ecef558bc327bd735ca47a0dd6e82da3478a94d947623f0b7a89525a93022de0d41ba48fcad8b359be904028147",
          "sha256": "3c60cb737c17fa5b2e663b747a912a3c0dc1e6608acbc9029f548dffc54d4d21",
          "sha1": "f0a65649426c00d491efc8826ebe6fb141d55093",
          "md5": "8bad254a8843715888fe2a4d236d5385"
        }
      ]
    }
  ]
}
